const http=require("http"),fs=require("fs"),path=require("path"),crypto=require("crypto");
const {Pool}=require("pg");
const pool=process.env.DATABASE_URL?new Pool({connectionString:process.env.DATABASE_URL,ssl:process.env.DATABASE_URL.includes("localhost")?false:{rejectUnauthorized:false}}):null;
const PORT=process.env.PORT||10000,DB_FILE=process.env.ECHTPREIS_DB_FILE||path.join("/tmp","echtpreis-db.json");
function load(){try{return JSON.parse(fs.readFileSync(DB_FILE,"utf8"))}catch(e){return{observations:[],aliases:[]}}}
function save(db){try{fs.writeFileSync(DB_FILE,JSON.stringify(db))}catch(e){}}
function send(res,status,obj){res.writeHead(status,{"Content-Type":"application/json; charset=utf-8","Access-Control-Allow-Origin":"https://julienfehlberg.github.io","Access-Control-Allow-Headers":"Content-Type","Access-Control-Allow-Methods":"POST,GET,OPTIONS","Cache-Control":"no-store"});res.end(JSON.stringify(obj))}
function body(req,cb){let raw="";req.on("data",c=>{raw+=c;if(raw.length>1e6)req.destroy()});req.on("end",()=>{try{cb(null,JSON.parse(raw||"{}"))}catch(e){cb(e)}})}
function clean(x){return String(x||"").trim().slice(0,120)}
async function initDb(){if(!pool)return;await pool.query(`CREATE TABLE IF NOT EXISTS price_observations(id uuid PRIMARY KEY,key text NOT NULL,store text NOT NULL,price numeric NOT NULL,per text NOT NULL,date date NOT NULL,region text,kind text NOT NULL DEFAULT 'community',source text,product text,proof text NOT NULL,trust int NOT NULL DEFAULT 60,status text NOT NULL DEFAULT 'observed',line_total numeric,regular_total numeric,discount numeric,pack_amount numeric,pack_unit text,pricing_confidence text,created_at timestamptz NOT NULL DEFAULT now());ALTER TABLE price_observations ADD COLUMN IF NOT EXISTS line_total numeric;ALTER TABLE price_observations ADD COLUMN IF NOT EXISTS regular_total numeric;ALTER TABLE price_observations ADD COLUMN IF NOT EXISTS discount numeric;ALTER TABLE price_observations ADD COLUMN IF NOT EXISTS pack_amount numeric;ALTER TABLE price_observations ADD COLUMN IF NOT EXISTS pack_unit text;ALTER TABLE price_observations ADD COLUMN IF NOT EXISTS pricing_confidence text;CREATE UNIQUE INDEX IF NOT EXISTS obs_dedupe ON price_observations(proof,key,store,price);CREATE INDEX IF NOT EXISTS obs_date_idx ON price_observations(date DESC);CREATE TABLE IF NOT EXISTS product_aliases(normalized text NOT NULL,key text NOT NULL,raw text,seen int NOT NULL DEFAULT 1,last_seen timestamptz NOT NULL DEFAULT now(),PRIMARY KEY(normalized,key));`)}
async function dbObservations(since){if(!pool)return null;let q=since?await pool.query("SELECT id,key,store,price::float,per,date::text,region,kind,source,product,proof,trust,status,created_at AS \"createdAt\" FROM price_observations WHERE date >= $1 ORDER BY created_at DESC LIMIT 5000",[since]):await pool.query("SELECT id,key,store,price::float,per,date::text,region,kind,source,product,proof,trust,status,created_at AS \"createdAt\" FROM price_observations ORDER BY created_at DESC LIMIT 5000");return q.rows}
async function dbAliases(){if(!pool)return null;return (await pool.query("SELECT normalized,key,raw,seen,last_seen AS \"lastSeen\" FROM product_aliases ORDER BY last_seen DESC LIMIT 5000")).rows}
async function dbSelfTest(){if(!pool)return{ok:false,storage:"fallback",reason:"DATABASE_URL fehlt"};const c=await pool.connect();try{await c.query("BEGIN");const id=crypto.randomUUID(),proof="selftest_"+Date.now();await c.query("INSERT INTO price_observations(id,key,store,price,per,date,region,kind,source,product,proof,trust,status) VALUES($1,'selftest','Lidl',0.01,'piece',CURRENT_DATE,'TEST','selftest','ECHTPREIS Selftest','TEST',$2,0,'test')",[id,proof]);const r=await c.query("SELECT id,proof FROM price_observations WHERE id=$1 AND proof=$2",[id,proof]);await c.query("ROLLBACK");return{ok:r.rowCount===1,storage:"postgres",write:true,read:r.rowCount===1,rollback:true}}catch(e){try{await c.query("ROLLBACK")}catch(_e){}return{ok:false,storage:"postgres",error:String(e.message||e).slice(0,160)}}finally{c.release()}}
function validObs(x){return x&&x.pricingConfidence==="confirmed"&&["Lidl","Kaufland","REWE","EDEKA"].includes(x.store)&&/^[a-z0-9 äöüß-]{2,60}$/i.test(x.key||"")&&Number.isFinite(+x.price)&&+x.price>0&&+x.price<10000&&["kg","l","piece"].includes(x.per)&&/^20\d\d-\d\d-\d\d$/.test(x.date||"")&&clean(x.proof)}
const server=http.createServer(async(req,res)=>{
 if(req.method==="OPTIONS")return send(res,204,{});
 if(req.method==="GET"&&req.url==="/health"){let db=load(),obs=pool?(await pool.query("SELECT count(*)::int n FROM price_observations")).rows[0].n:db.observations.length,als=pool?(await pool.query("SELECT count(*)::int n FROM product_aliases")).rows[0].n:db.aliases.length;return send(res,200,{ok:true,service:"ECHTPREIS Data API",version:"3.6",observations:obs,aliases:als,storage:pool?"postgres":"ephemeral-fallback"})}
 if(req.method==="GET"&&req.url.startsWith("/v1/observations")){let db=load(),u=new URL(req.url,"http://x"),since=u.searchParams.get("since"),rows=await dbObservations(since);if(!rows)rows=db.observations.filter(x=>!since||x.date>=since).slice(-5000);return send(res,200,{version:"3.6",items:rows})}
 if(req.method==="GET"&&req.url.startsWith("/v1/aliases")){let db=load(),rows=await dbAliases();return send(res,200,{version:"3.6",items:rows||db.aliases.slice(-5000)})}
 if(req.method==="GET"&&req.url.startsWith("/health/db-selftest")){return send(res,200,{version:"3.6",...(await dbSelfTest())})}
 if(req.method==="POST"&&req.url==="/v1/receipt-observations")return body(req,async(err,b)=>{
  if(err||!b||!Array.isArray(b.items)||!clean(b.proof))return send(res,400,{error:"Ungültige Anfrage"});
  let db=load(),accepted=0,rejected=0,proof=clean(b.proof);
  for(const raw of b.items.slice(0,100)){let x={id:crypto.randomUUID(),key:clean(raw.key).toLowerCase(),store:clean(raw.store),price:+raw.price,per:clean(raw.per),date:clean(raw.date),region:clean(raw.region),kind:"community",source:"ECHTPREIS Bon",product:clean(raw.product),proof,trust:60,status:"observed",lineTotal:+raw.lineTotal||null,regularTotal:+raw.regularTotal||null,discount:+raw.discount||0,packAmount:+raw.packAmount||null,packUnit:clean(raw.packUnit),pricingConfidence:clean(raw.pricingConfidence),createdAt:new Date().toISOString()};if(!validObs(x)){rejected++;continue}let dupe=db.observations.some(o=>o.proof===x.proof&&o.key===x.key&&o.store===x.store&&o.price===x.price);if(dupe){rejected++;continue}if(pool){try{await pool.query("INSERT INTO price_observations(id,key,store,price,per,date,region,kind,source,product,proof,trust,status,created_at,line_total,regular_total,discount,pack_amount,pack_unit,pricing_confidence) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12,$13,$14,$15,$16,$17,$18,$19,$20) ON CONFLICT DO NOTHING",[x.id,x.key,x.store,x.price,x.per,x.date,x.region,x.kind,x.source,x.product,x.proof,x.trust,x.status,x.createdAt,x.lineTotal,x.regularTotal,x.discount,x.packAmount,x.packUnit,x.pricingConfidence]);accepted++;if(raw.rawName){let n=clean(raw.rawName).toLowerCase();await pool.query("INSERT INTO product_aliases(normalized,key,raw,seen,last_seen) VALUES($1,$2,$3,1,now()) ON CONFLICT(normalized,key) DO UPDATE SET seen=product_aliases.seen+1,last_seen=now(),raw=EXCLUDED.raw",[n,x.key,clean(raw.rawName)])}}catch(e){rejected++}}else{db.observations.push(x);accepted++;if(raw.rawName){let n=clean(raw.rawName).toLowerCase(),a=db.aliases.find(a=>a.normalized===n&&a.key===x.key);if(a){a.seen++;a.lastSeen=x.createdAt}else db.aliases.push({normalized:n,raw:clean(raw.rawName),key:x.key,seen:1,lastSeen:x.createdAt})}}
  }
  if(!pool){db.observations=db.observations.slice(-50000);db.aliases=db.aliases.slice(-10000);save(db)}return send(res,200,{ok:true,accepted,rejected,storage:pool?"postgres":"fallback"})
 });
 return send(res,404,{error:"Not found"});
});
initDb().then(()=>server.listen(PORT,()=>console.log("ECHTPREIS Data API 3.6 on "+PORT))).catch(e=>{console.error("DB init failed",e);server.listen(PORT,()=>console.log("ECHTPREIS Data API 3.6 fallback on "+PORT))});