"use strict";
const assert=require("node:assert/strict"),Refresh=require("../aldi-category-refresh"),Fetch=require("../aldi-category-fetch-client"),Fixture=require("./fixtures/aldi-category-capture"),util=require("node:util");
const time=Date.UTC(2026,9,3,5,0),deadline=new Date(time+3600000).toISOString();
function harness({failPersist=false,failCheckpoint=false,failCommit=false,failRollback=false}={}){
 let borrowed=false,pending=null,latest=0,saved=null;const events=[];
 const tx={query:async(sql,params)=>{events.push(sql);if(sql==="BEGIN")pending={latest,saved};if(sql==="ROLLBACK"){pending=null;if(failRollback)throw Error("rollback failed");}if(sql==="COMMIT"){if(failCommit)throw Error("commit failed");latest=pending.latest;saved=pending.saved;pending=null;}if(sql.startsWith("INSERT INTO aldi_category_catalog_state")){if(failCheckpoint)throw Error("checkpoint failed");pending.saved=params;}return{rows:[],rowCount:1};},release:error=>{assert(borrowed);borrowed=false;events.push(error?"release-broken":"release");}};
 const pool={connect:async()=>{assert(!borrowed);borrowed=true;events.push("connect");return tx;},query:async(sql,params)=>{assert.equal(borrowed,false,"The only pooled client must be returned before fallback checkpoint");events.push("pool:"+sql);if(sql.startsWith("INSERT INTO aldi_category_catalog_state"))saved=params;return{rows:[],rowCount:1};}};
 const service={ensure:async p=>assert.equal(p,pool),persist:async(client,capture,options)=>{assert.equal(client,tx);assert(events.includes("SELECT txid_current()"));assert.equal(capture.status,200);assert.equal(options.now,time);pending.latest++;if(failPersist)throw Error("retention failed");return{retainedOnly:true};}};
 return{pool,service,events,get latest(){return latest;},get saved(){return saved;},get borrowed(){return borrowed;}};
}
(async()=>{let groups=0;
 const originalBody=Fixture.html().replace(/an_prd_de_de_products2/g,"unadmitted_landing_index");let rejected;
 await assert.rejects(Fetch.fetchPage(Fixture.url,{now:()=>time,fetchImpl:async()=>new Response(originalBody,{headers:{date:new Date(time).toUTCString(),age:"0","content-type":"text/html"}})}),error=>{rejected=error;return error.code==="aldi-category-native-index-conflict";});
 assert(!util.inspect(rejected).includes("unadmitted_landing_index"));groups++;
 const good=harness();await Refresh.retainFailure(good.pool,rejected,rejected.code,deadline,time,good.service);assert.equal(good.latest,1);assert.equal(good.saved[2],rejected.code);assert.equal(good.saved[3],deadline);assert.equal(good.borrowed,false);assert(good.events.indexOf("COMMIT")>good.events.findIndex(x=>x.startsWith("INSERT")));assert.equal(rejected.retentionErrorCode,undefined);groups++;
 for(const failure of["failPersist","failCheckpoint","failCommit","failRollback"]){const h=harness({[failure]:true,...(failure==="failRollback"?{failPersist:true}:{})});const error=Object.assign(Error(rejected.code),{code:rejected.code});Object.defineProperty(error,"rejectedCapture",{value:rejected.rejectedCapture});await Refresh.retainFailure(h.pool,error,error.code,deadline,time,h.service);assert.equal(h.latest,0);assert.equal(h.saved[2],error.code);assert.equal(h.saved[3],deadline);assert.equal(h.borrowed,false);assert.equal(error.code,rejected.code);assert.equal(error.retentionErrorCode,"aldi-category-rejected-retention-failed");const release=h.events.findIndex(x=>x.startsWith("release")),fallback=h.events.findIndex(x=>x.startsWith("pool:INSERT"));assert(release>=0&&fallback>release);assert.equal(h.events.includes("release-broken"),failure==="failRollback");groups++;}
 const denied=harness(),http=Object.assign(Error("denied"),{code:"aldi-category-http-403"});await Refresh.retainFailure(denied.pool,http,http.code,deadline,time,denied.service);assert.equal(denied.latest,0);assert(!denied.events.includes("connect"));assert.equal(denied.saved[2],http.code);groups++;
 const unavailable=harness({failPersist:true}),sourceError=Object.assign(Error(rejected.code),{code:rejected.code});Object.defineProperty(sourceError,"rejectedCapture",{value:rejected.rejectedCapture});unavailable.pool.query=async()=>{assert.equal(unavailable.borrowed,false);throw Object.assign(Error("database unavailable"),{code:"XX001"});};await Refresh.retainFailure(unavailable.pool,sourceError,sourceError.code,deadline,time,unavailable.service);assert.equal(sourceError.code,rejected.code);assert.equal(sourceError.failurePersistenceErrorCode,"XX001");assert.equal(sourceError.failureCheckpointPersisted,false);assert.equal(unavailable.latest,0);assert.equal(unavailable.saved,null);groups++;
 const plainError=Object.assign(Error("403"),{code:"aldi-category-http-403"});await Refresh.retainFailure(unavailable.pool,plainError,plainError.code,deadline,time,unavailable.service);assert.equal(plainError.code,"aldi-category-http-403");assert.equal(plainError.failureCheckpointPersisted,false);assert.equal(plainError.failurePersistenceErrorCode,"XX001");groups++;
 console.log("aldi-category-failure-retention: "+groups+" actual transport/atomic checkpoint and single-client fallback groups passed; no HTTP or database calls");
})().catch(error=>{console.error(error);process.exitCode=1;});
