"use strict";

const assert=require("node:assert/strict"),crypto=require("node:crypto"),Client=require("../aldi-assortment-category-client"),Price=require("../aldi-assortment-price-service"),Articles=require("../aldi-assortment-article-service");
const now=Date.parse("2026-10-03T03:00:00.500Z"),capturedAt=new Date(now-1000).toISOString(),categoryUrl="https://www.aldi-nord.de/sortiment/milchprodukte/milch-milchgetraenke.html",index=Client.INDEX,clone=structuredClone;let groups=0;
// Every body and HTTP proof below is explicitly synthetic; the saved real HTML
// lacks Date/Age and is only inspected outside this portable offline test.
const product=(sku="1018999",patch={})=>({objectID:sku,productSlug:"unit-test-milch-"+sku,name:"UNIT TEST Vollmilch",brandName:"MILSANI",shortDescription:"3,5 % Fett",salesUnit:"1-L-Packung",categoryIDs:["milch-milchgetraenke","milsani"],country:"DE",isAvailable:true,currentPrice:{priceValue:.95,validFrom:1,validUntil:1893366000},...patch});
function native(hits=[product()],pagination={}){const hitsPerPage=pagination.hitsPerPage??1000,nbHits=pagination.nbHits??hits.length;return{page:"/product-overview/[...categories]",query:{categories:["milchprodukte","milch-milchgetraenke"]},props:{pageProps:{locale:"de",page:{"@path":"/germany/sortiment/milchprodukte/milch-milchgetraenke",categoryKey:"milch-milchgetraenke"},mgnlContext:{isMagnoliaEdit:false,isMagnoliaPreview:false},algoliaState:{initialResults:{[index]:{state:{index,filters:"categoryIDs:milch-milchgetraenke",hitsPerPage,numericRefinements:{},tagRefinements:[]},requestParams:[{filters:"categoryIDs:milch-milchgetraenke",hitsPerPage}],results:[{hits,nbHits,nbPages:Math.ceil(nbHits/hitsPerPage),page:0,hitsPerPage,index,query:"",params:new URLSearchParams({filters:"categoryIDs:milch-milchgetraenke",hitsPerPage:String(hitsPerPage)}).toString(),exhaustiveNbHits:true,exhaustive:{nbHits:true},...pagination}]}}}}}};}
function html(n=native(),canonical=categoryUrl){return '<!doctype html><html><head><link rel="canonical" href="'+canonical+'"/></head><body><script id="__NEXT_DATA__" type="application/json">'+JSON.stringify(n)+'</script></body></html>';}
const meta=body=>({sourceResponseUrl:categoryUrl,sourceResponseHash:crypto.createHash("sha256").update(body).digest("hex"),capturedAt,sourceResponseDate:new Date(capturedAt).toUTCString(),sourceAgeSeconds:0,scopeCountry:"DE"});
const parse=(n=native(),patch={},options={})=>{const body=html(n);return Client.parsePage(body,{...meta(body),...patch},{now,...options});};
const fails=(operation,code)=>{assert.throws(operation,error=>error.code===code,code);groups++;};
const n=native(),body=html(n),before=clone(n),r=parse(n),c=r.candidates[0];
assert.equal(r.receivedCount,1);assert.equal(r.candidateCount,1);assert.equal(r.rejectedCount,0);assert.equal(r.freshCaptureVerified,true);assert.equal(r.offlineOnly,false);assert.equal(r.extractionComplete,true);assert.equal(r.assortmentComplete,false);assert.equal(r.physicalStorePriceVerified,false);assert.deepEqual(n,before);assert.equal(c.sourceId,Client.SOURCE);assert.notEqual(c.sourceId,Price.SOURCE);assert.equal(c.purpose,"category-identity-candidate");assert.equal(c.state,"unadmitted");assert.equal(c.admitted,false);assert.equal(c.identity.retailerSku,"1018999");assert.equal(c.identity.productIdentityUrl,"https://www.aldi-nord.de/produkt/unit-test-milch-1018999.html");assert.equal(c.identity.nativeSalesUnit,"1-L-Packung");assert.deepEqual(c.identity.normalizedSalesPack,{amount:1,unit:"l",count:1,total:{amount:1000,unit:"ml"}});assert.equal(c.identity.gtin,null);assert.equal(c.locationScope,"unknown");assert.equal(c.availability,"unknown");assert.equal(c.truthEligible,false);assert.equal(c.currentPriceVerified,false);assert.equal(c.physicalStorePriceVerified,false);assert.equal(c.categoryProof.categoryUrl,categoryUrl);assert.equal(c.categoryProof.sourceResponseUrl,categoryUrl);assert.equal(c.categoryProof.sourceResponseHash,meta(body).sourceResponseHash);assert.notEqual(c.categoryProof.sourceResponseUrl,c.identity.productIdentityUrl);assert.equal(c.categoryProof.proofKind,"original-category-html");assert.equal(c.sourceUrl,undefined);assert.equal(c.observedAt,undefined);assert.equal(c.sourceResponseHash,undefined);assert.equal(c.price,undefined);assert.equal(c.packAmount,undefined);assert.deepEqual(c.rawNativeProduct,n.props.pageProps.algoliaState.initialResults[index].results[0].hits[0]);assert.equal(Price.validateOffer(c,{now}).ok,false);assert.equal(Articles.validateArticle(c,{now}).ok,false);groups++;
// Mutating a returned source witness cannot mutate another candidate's proof or
// the input/native source. Original HTTP hash is never a PDP serialization hash.
const many=parse(native([product(),product("1019000")]));many.candidates[0].categoryProof.sourceResponseHash="0".repeat(64);many.candidates[0].rawNativeProduct.name="changed";assert.equal(many.candidates[1].categoryProof.sourceResponseHash,many.categoryProof.sourceResponseHash);assert.equal(many.candidates[1].rawNativeProduct.name,"UNIT TEST Vollmilch");groups++;
const offline=Client.parsePage(Buffer.from(body),{},{now});assert.equal(offline.offlineOnly,true);assert.equal(offline.freshCaptureVerified,false);assert.equal(offline.candidates.length,1);assert.equal(offline.categoryProof.capturedAt,null);assert.equal(offline.categoryProof.sourceResponseDate,null);assert.equal(offline.categoryProof.sourceResponseUrl,null);assert.equal(offline.categoryProof.sourceResponseHash,meta(body).sourceResponseHash);assert.equal(offline.candidates[0].admitted,false);groups++;
for(const missing of["sourceResponseUrl","sourceResponseHash","sourceResponseDate","sourceAgeSeconds","capturedAt"]){const proof=meta(body);delete proof[missing];if(missing==="capturedAt")delete proof.sourceResponseDate;const result=Client.parsePage(body,proof,{now});assert.equal(result.offlineOnly,true,missing);assert.equal(result.freshCaptureVerified,false,missing);groups++;}
const historic=Client.parsePage(body,{...meta(body),capturedAt:"2026-09-01T00:00:00.000Z",sourceResponseDate:null},{now});assert.equal(historic.offlineOnly,true);assert.equal(historic.categoryProof.capturedAt,"2026-09-01T00:00:00.000Z");assert.equal(historic.candidates[0].admitted,false);groups++;
for(const [pack,amount,unit,count]of[["1.000-g-Packung",1000,"g",1],["20x10-g-Packung",10,"g",20],["9x500ml",500,"ml",9],["0.250 l",.25,"l",1]]){const result=parse(native([product("1018999",{salesUnit:pack})]));assert.equal(result.candidates.length,1);assert.equal(result.candidates[0].identity.nativeSalesUnit,pack);assert.deepEqual(Object.fromEntries(["amount","unit","count"].map(k=>[k,result.candidates[0].identity.normalizedSalesPack[k]])),{amount,unit,count});groups++;}
for(const [patch,reason]of[[{objectID:1018999},"aldi-category-native-sku-invalid"],[{objectID:"01018999"},"aldi-category-native-sku-invalid"],[{objectID:"0"},"aldi-category-native-sku-invalid"],[{objectID:"1234567890123456"},"aldi-category-native-sku-invalid"],[{productSlug:"unit-test-milch-1019000"},"aldi-category-native-identity-conflict"],[{productSlug:"../milch-1018999"},"aldi-category-native-identity-conflict"],[{categoryIDs:["butter"]},"aldi-category-native-identity-conflict"],[{categoryIDs:["milch-milchgetraenke",1]},"aldi-category-native-identity-conflict"],[{name:"<b>Milk</b>"},"aldi-category-native-product-label-invalid"],[{brandName:123},"aldi-category-native-product-label-invalid"],[{salesUnit:"z. B. 770 g"},"aldi-category-exact-sales-pack-required"],[{salesUnit:"500–750 g"},"aldi-category-exact-sales-pack-required"],[{salesUnit:"1.000.5 g"},"aldi-category-exact-sales-pack-required"],[{salesUnit:"2 x 500 g oder 1 kg"},"aldi-category-exact-sales-pack-required"],[{shortDescription:"Verschiedene Sorten"},"aldi-category-product-variant-unresolved"],[{name:"Verschiedene Gewichte"},"aldi-category-product-variant-unresolved"],[{isDrainedWeight:true,drainedWeightValue:0},"aldi-category-drained-weight-unresolved"],[{country:"AT"},"aldi-category-native-product-country-conflict"]]){const result=parse(native([product("1018999",patch)]));assert.equal(result.candidates.length,0,reason);assert.equal(result.receivedCount,1);assert.equal(result.rejectedCount,1);assert(result.rejected[0].reasons.includes(reason));assert.equal(result.assortmentComplete,false);groups++;}
const rawGtin=parse(native([product("1018999",{gtin:"4046700026519",ean:"4046700026519"})]));assert.equal(rawGtin.candidates[0].identity.gtin,null,"Category candidate does not invent GTIN admission from extra source fields");groups++;
const priceLess=parse(native([product("1018999",{currentPrice:null,isAvailable:false,isComingSoon:true,brandName:"",shortDescription:""})]));assert.equal(priceLess.candidates.length,1,"Native identity extraction is independent from price/availability");assert.equal(priceLess.candidates[0].identity.brand,null);assert.equal(priceLess.candidates[0].identity.variant,null);assert.equal(priceLess.candidates[0].availability,"unknown");assert.equal(priceLess.candidates[0].currentPriceVerified,false);groups++;
for(const raw of[null,[],"milk"]){const rejected=parse(native([raw]));assert.equal(rejected.candidates.length,0);assert.equal(rejected.rejectedCount,1);assert(rejected.rejected[0].reasons.includes("aldi-category-native-product-schema-invalid"));groups++;}
const empty=parse(native([]));assert.equal(empty.receivedCount,0);assert.equal(empty.pagination.nbPages,0);assert.equal(empty.extractionComplete,true);assert.equal(empty.assortmentComplete,false);groups++;
const truncated=parse(native([product(),product("1019000")],{hitsPerPage:2,nbHits:3}));assert.equal(truncated.candidates.length,2);assert.equal(truncated.pagination.nbHits,3);assert.equal(truncated.pagination.nbPages,2);assert.equal(truncated.pagination.truncated,true);assert.equal(truncated.extractionComplete,false);assert.equal(truncated.assortmentComplete,false);groups++;
fails(()=>parse(native([product(),product("1019000")]),{}, {maxRows:1}),"aldi-category-row-bound-exceeded");
fails(()=>parse(native([product(),product()])),"aldi-category-duplicate-native-sku");
fails(()=>parse(native([product(),product("1018999",{salesUnit:"500 g"})])),"aldi-category-duplicate-native-sku");
const changed=(mutate,code)=>{const value=native();mutate(value,value.props.pageProps,value.props.pageProps.algoliaState.initialResults[index],value.props.pageProps.algoliaState.initialResults[index].results[0]);fails(()=>parse(value),code);};
changed(n=>n.query.categories=["milchprodukte","butter"],"aldi-category-native-route-conflict");changed(n=>n.query.q="Milk","aldi-category-native-route-conflict");changed(n=>n.page="/product/[slug]","aldi-category-native-route-conflict");changed((n,p)=>p.locale="nl","aldi-category-native-country-or-category-conflict");changed((n,p)=>p.country="AT","aldi-category-native-country-or-category-conflict");changed((n,p)=>p.page["@path"]="/austria/sortiment/milchprodukte/milch-milchgetraenke","aldi-category-native-country-or-category-conflict");changed((n,p)=>p.page.categoryKey="butter","aldi-category-native-country-or-category-conflict");changed((n,p)=>p.mgnlContext.isMagnoliaPreview=true,"aldi-category-native-country-or-category-conflict");changed((n,p)=>p.hasError=true,"aldi-category-native-country-or-category-conflict");changed((n,p)=>p.algoliaState.initialResults.other={results:[]},"aldi-category-native-index-conflict");changed((n,p,e)=>e.state.index="an_prd_nl_nl_products2","aldi-category-native-index-conflict");changed((n,p,e,r)=>r.index="other","aldi-category-native-index-conflict");changed((n,p,e)=>e.results.push(clone(e.results[0])),"aldi-category-native-index-conflict");changed((n,p,e)=>e.requestParams.push(clone(e.requestParams[0])),"aldi-category-native-index-conflict");
for(const mutate of[(n,p,e)=>e.state.filters="categoryIDs:butter",(n,p,e)=>e.requestParams[0].filters="categoryIDs:butter",(n,p,e)=>e.requestParams[0].facetFilters=["brandName:MILSANI"],(n,p,e,r)=>r.query="Milch",(n,p,e)=>e.state.numericRefinements={price:{">":1}},(n,p,e,r)=>r.params+="&filters=categoryIDs:butter",(n,p,e,r)=>r.params+="&query=Milch",(n,p,e,r)=>r.params+="&country=AT"]){changed(mutate,"aldi-category-native-query-conflict");}
for(const mutate of[(n,p,e,r)=>r.page=1,(n,p,e)=>e.state.page=1,(n,p,e)=>e.requestParams[0].page=1,(n,p,e,r)=>r.params+="&page=1"]){changed(mutate,"aldi-category-native-page-conflict");}
for(const mutate of[(n,p,e,r)=>r.nbHits=2,(n,p,e,r)=>r.nbHits="1",(n,p,e,r)=>r.nbPages=2,(n,p,e,r)=>r.hitsPerPage=0,(n,p,e,r)=>r.exhaustiveNbHits=false,(n,p,e,r)=>r.exhaustive.nbHits=false,(n,p,e)=>e.state.hitsPerPage=999,(n,p,e)=>e.requestParams[0].hitsPerPage=999]){changed(mutate,"aldi-category-native-count-conflict");}
for(const url of[categoryUrl+"?q=milch",categoryUrl+"#milk","https://aldi-nord.de/sortiment/milch.html","https://www.aldi-nord.de:444/sortiment/milch.html","https://user@www.aldi-nord.de/sortiment/milch.html","http://www.aldi-nord.de/sortiment/milch.html","https://www.aldi-nord.de/produkt/milch-1018999.html","https://www.aldi-nord.de/sortiment/milch%2Fgetraenke.html"]){fails(()=>Client.parsePage(html(native(),url),{},{now}),"aldi-category-url-not-allowed");}
fails(()=>parse(native(),{sourceResponseUrl:"https://www.aldi-nord.de/sortiment/milchprodukte/butter.html"}),"aldi-category-source-canonical-conflict");fails(()=>parse(native(),{scopeCountry:"AT"}),"aldi-category-country-conflict");fails(()=>parse(native(),{sourceResponseHash:"0".repeat(64)}),"aldi-category-original-response-hash-conflict");fails(()=>parse(native(),{sourceResponseHash:"bad"}),"aldi-category-original-response-hash-conflict");fails(()=>parse(native(),{sourceUrl:c.identity.productIdentityUrl}),"aldi-category-proof-schema-invalid");
fails(()=>parse(native(),{capturedAt:new Date(now+1).toISOString()}),"aldi-category-capture-future");fails(()=>parse(native(),{capturedAt:"2026-02-30T00:00:00.000Z"}),"aldi-category-capture-invalid");fails(()=>parse(native(),{capturedAt:new Date(now-300001).toISOString(),sourceResponseDate:new Date(now-300001).toISOString()}),"aldi-category-capture-stale");fails(()=>parse(native(),{sourceResponseDate:new Date(Date.parse(capturedAt)-300001).toISOString()}),"aldi-category-source-proof-invalid");fails(()=>parse(native(),{sourceResponseDate:new Date(Date.parse(capturedAt)+300001).toISOString()}),"aldi-category-source-proof-invalid");fails(()=>parse(native(),{sourceResponseDate:"0"}),"aldi-category-source-proof-invalid");fails(()=>parse(native(),{capturedAt:null}),"aldi-category-date-without-capture");
for(const age of[-1,301,"0",undefined,NaN,0.1])fails(()=>parse(native(),{sourceAgeSeconds:age}),"aldi-category-source-age-invalid");const noCacheAge=parse(native(),{sourceAgeSeconds:null});assert.equal(noCacheAge.freshCaptureVerified,true);assert.equal(noCacheAge.categoryProof.sourceAgeSeconds,null);groups++;
for(const opts of[{maxRows:0},{maxRows:1001},{maxRows:"50"},{now:"yesterday"},{now:Infinity},{url:"https://other.invalid"}])fails(()=>parse(native(),{},opts),"aldi-category-options-invalid");
fails(()=>Client.parsePage(null),"aldi-category-html-required");fails(()=>Client.parsePage(Buffer.from([255])),"aldi-category-utf8-required");fails(()=>Client.parsePage("x".repeat(Client.MAX_BYTES+1)),"aldi-category-body-bound-exceeded");fails(()=>Client.parsePage(body.replace('<link rel="canonical" href="'+categoryUrl+'"/>',"")),"aldi-category-canonical-required");fails(()=>Client.parsePage(body.replace('</head>','<link rel="canonical" href="'+categoryUrl+'"/></head>')),"aldi-category-canonical-required");fails(()=>Client.parsePage(body.replace('</body>','<script id="__NEXT_DATA__" type="application/json">{}</script></body>')),"aldi-category-next-data-required");fails(()=>Client.parsePage(body.replace(JSON.stringify(n),"{")),"aldi-category-next-data-invalid");
console.log(`aldi-assortment-category-client: ${groups} offline groups passed; original category proof, separate unadmitted native SKU candidates, exact pack/variant/count/country bounds and truthful partial/offline extraction`);
