"use strict";
const assert=require("node:assert/strict"),{Pool}=require("pg"),Service=require("../aldi-assortment-price-service"),Refresh=require("../aldi-assortment-refresh"),Inventory=require("../published-retailer-inventory");
function gtin(index){const body=String(950000000000+index),sum=[...body].reduce((n,d,i)=>n+Number(d)*(i%2?3:1),0);return body+(10-sum%10)%10;}
async function main(){
 const connectionString=process.env.DATABASE_URL;assert(connectionString,"DATABASE_URL is required");const database=new URL(connectionString);assert.equal(database.hostname,"localhost");assert(database.pathname.endsWith("_test"),"Only a dedicated local test database is allowed");
 const pool=new Pool({connectionString,ssl:false,connectionTimeoutMillis:5000}),now=Date.now();let api;
 const fixture=(index,patch={})=>{const sku=String(960000000+index),capturedAt=new Date(now-1000).toISOString();return{sourceId:Service.SOURCE,merchant:"ALDI Nord",retailerSku:sku,gtin:null,name:"POSTGRES TEST ALDI product "+index,brand:"POSTGRES TEST",variant:"fixed native variant",pack:"1-L-Packung",packAmount:1,packUnit:"l",packCount:1,price:1.29,deposit:0,depositIncluded:false,currency:"EUR",priceBasis:"pack",priceKind:"published-current",regularPrice:null,promotionStatus:"unknown",availability:"unknown",publicationAvailable:true,capturedAt,nativeValidFrom:new Date(now-86400000).toISOString(),nativeValidUntil:new Date(now+2*86400000).toISOString(),expiresAt:new Date(now+7*86400000).toISOString(),proofHash:"d".repeat(64),sourceResponseHash:"c".repeat(64),sourceResponseDate:capturedAt,sourceAgeSeconds:0,sourceUrl:"https://www.aldi-nord.de/produkt/postgres-test-aldi-product-"+sku+".html",scopeCountry:"DE",scopeChannel:"assortment-publication",locationScope:"unknown",truthEligible:false,...patch};};
 try{
  const exists=async table=>!!(await pool.query("SELECT to_regclass($1) AS name",["public."+table])).rows[0].name,baseline={};
  for(const table of["products","stores","price_observations","receipts","receipt_submissions"])baseline[table]=await exists(table)?(await pool.query("SELECT count(*)::int AS count FROM "+table)).rows[0].count:null;
  const inventoryBefore=await Inventory.status(pool,{now});
  for(const table of["retailer_published_prices","wolt_retailer_published_prices","rewe_retailer_published_prices"])baseline[table]=await exists(table)?(await pool.query("SELECT count(*)::int AS count FROM "+table)).rows[0].count:null;
  const fixtures=Array.from({length:501},(_,index)=>fixture(index)),saved=await Service.persist(pool,fixtures,{now});assert.equal(saved.accepted,501);assert.equal(saved.rejected,0);assert.equal(saved.upserted,501);
  const stored=(await pool.query(`SELECT count(*)::int AS total,count(*) FILTER(WHERE gtin IS NULL AND scope_country='DE' AND scope_channel='assortment-publication' AND location_scope='unknown' AND currency='EUR' AND pack_amount=1000 AND pack_unit='ml' AND pack_count=1 AND price=1.29 AND deposit=0 AND expires_at=captured_at+interval '24 hours')::int AS exact FROM ${Service.TABLE} WHERE retailer_sku=ANY($1::text[])`,[fixtures.map(row=>row.retailerSku)])).rows[0];assert.equal(stored.total,501);assert.equal(stored.exact,501,"Native pack/TTL and zero GTIN identity are enforced in stored rows");
  const inventoryAfter=await Inventory.status(pool,{now});assert.equal(inventoryAfter.currentPrices,inventoryBefore.currentPrices+501);assert.equal(inventoryAfter.productsWithCurrentPublishedPrices,inventoryBefore.productsWithCurrentPublishedPrices,"ALDI native SKUs without GTIN cannot inflate exact-product union");assert(inventoryAfter.scopeChannels.includes("assortment-publication"));
  assert.equal((await Service.persist(pool,fixtures,{now})).unchanged,501);
  assert.equal((await Service.persist(pool,[fixture(0,{price:1.59})],{now})).rejected,1,"Contradictory equal-time native price cannot overwrite stored evidence");
  const updated=fixture(0,{price:1.39,capturedAt:new Date(now).toISOString(),sourceResponseDate:new Date(now).toISOString(),sourceResponseHash:"e".repeat(64),proofHash:"f".repeat(64)});assert.equal((await Service.persist(pool,[updated],{now})).upserted,1);assert.equal((await Service.persist(pool,[fixture(0)],{now})).unchanged,1);
  let result=await Service.search(pool,{retailerSku:updated.retailerSku,now});assert.equal(result.items.length,1);const selected=result.items[0];assert.equal(selected.price,1.39);assert.equal(selected.gtin,null);assert.equal(selected.identityStatus,"native-retailer-sku");assert.equal(selected.scopeChannel,"assortment-publication");assert.equal(selected.locationScope,"unknown");assert.equal(selected.truthEligible,false);assert.equal(selected.physicalStorePriceVerified,false);assert.equal(selected.priceType,"unknown");assert.equal(selected.regularPrice,null);assert.equal(selected.shippingIncluded,false);assert.equal(selected.serviceFeesIncluded,false);assert.equal(selected.payablePackPrice,1.39);assert(!("storeId"in selected));assert(!("canonicalProductId"in selected));assert.equal(Date.parse(selected.expiresAt),now+Service.DAY_MS);
  assert.equal((await Service.search(pool,{gtin:gtin(0),now})).items.length,0,"Unattested GTIN is never guessed from a product name");assert.equal((await Service.search(pool,{merchant:"REWE",now})).items.length,0);assert.equal((await Service.search(pool,{search:"product 500",now})).items.length,1);assert.equal((await Service.search(pool,{search:"product%_",now})).items.length,0);assert.equal((await Service.search(pool,{limit:999,now})).items.length,200);
  const oldCapture=new Date(now-Service.DAY_MS-1).toISOString(),expired=fixture(501,{capturedAt:oldCapture,sourceResponseDate:oldCapture,nativeValidFrom:new Date(now-2*Service.DAY_MS).toISOString()});assert.equal((await Service.persist(pool,[expired],{now})).upserted,1);assert.equal((await Service.search(pool,{retailerSku:expired.retailerSku,now})).items.length,0);
  const nativeDeadline=now+3600000,short=fixture(502,{nativeValidUntil:new Date(nativeDeadline).toISOString()});assert.equal((await Service.persist(pool,[short],{now})).upserted,1);result=await Service.search(pool,{retailerSku:short.retailerSku,now});assert.equal(result.items.length,1);assert.equal(Date.parse(result.items[0].expiresAt),nativeDeadline,"Native price validity wins over a supplied longer expiry");assert.equal((await Service.search(pool,{retailerSku:short.retailerSku,now:nativeDeadline+1})).items.length,0);
  const unknownDeposit=fixture(503,{deposit:null,depositIncluded:null});assert.equal((await Service.persist(pool,[unknownDeposit],{now})).upserted,1);assert.equal((await Service.search(pool,{retailerSku:unknownDeposit.retailerSku,now})).items[0].payablePackPrice,null);
  const conflict=await Service.persist(pool,[fixture(504),fixture(504,{price:1.59})],{now});assert.equal(conflict.accepted,0);assert.equal(conflict.rejected,2);assert.equal((await Service.search(pool,{retailerSku:fixture(504).retailerSku,now})).items.length,0);
  const invalid=await Service.persist(pool,[fixture(510,{gtin:gtin(510)}),fixture(511,{storeId:"imaginary",scopeChannel:"store"}),fixture(512,{scopeCountry:"AT"}),fixture(513,{regularPrice:1.69,priceType:"regular"}),fixture(514,{availability:"available"}),fixture(515,{deposit:.25}),fixture(516,{sourceResponseDate:new Date(now-400000).toISOString()}),fixture(517,{sourceAgeSeconds:301}),fixture(518,{packAmount:2}),fixture(519,{capturedAt:new Date(now+1).toISOString()}),fixture(520,{nativeValidUntil:new Date(now-2000).toISOString()}),fixture(521,{price:1.299}),fixture(522,{sourceResponseUrl:"https://unapproved.example/test"})],{now});assert.equal(invalid.accepted,0);assert.equal(invalid.rejected,13);
  for(const update of["gtin='3017620422003'","scope_channel='store'","expires_at=captured_at+interval '25 hours'","source_response_date=captured_at-interval '6 minutes'"]){await assert.rejects(()=>pool.query(`UPDATE ${Service.TABLE} SET ${update} WHERE retailer_sku=$1`,[updated.retailerSku]),error=>error.code==="23514","Database constraints must reject inadmissible identities/scopes/expiry/freshness even outside the JS validator");}
  await assert.rejects(()=>pool.query(`UPDATE ${Service.TABLE} SET expires_at=native_valid_until+interval '1 minute' WHERE retailer_sku=$1`,[short.retailerSku]),error=>error.code==="23514","Expiry within 24 hours must still respect its earlier native deadline");
  let status=await Service.status(pool,{now});assert.equal(status.storedPrices,504);assert.equal(status.currentPrices,503);assert.equal(status.productsWithCurrentPublishedPrices,0);assert.equal(status.availableCurrentPrices,0);assert.equal(status.physicalStorePriceVerified,false);assert.equal(status.normalPriceClassificationVerified,false);assert.equal(status.independentOfUserReceipts,true);assert.equal(status.scopeChannel,"assortment-publication");
  // Exercise the actual persistent cursor SQL and admission writes together in a rollback-only transaction.
  const checkpoint=await pool.connect();try{
   await checkpoint.query("BEGIN");await Refresh.ensure(checkpoint);await checkpoint.query("DELETE FROM aldi_assortment_catalog_state WHERE source_id=$1",[Service.SOURCE]);
   const hash="9".repeat(64),offers=[fixture(8000),fixture(8001),fixture(8002)],targets=offers.map(row=>({retailerSku:row.retailerSku,sourceUrl:row.sourceUrl})),discovery={targets,snapshotHash:hash,requests:1,bytes:100},cursor={snapshotHash:hash,nextIndex:1,lastSku:targets[0].retailerSku};
   const first={offers:[offers[0]],products:[{retailerSku:offers[0].retailerSku}],rejected:[],processed:1,requests:1,bytes:100,complete:false,partialError:null,cursor,cursorReset:false,targetCount:3,snapshotHash:hash};
   assert.equal((await Refresh.refresh({pool:checkpoint,maxRequests:2,now:()=>now},{discoverTargets:async()=>discovery,fetchProducts:async()=>first})).accepted,1);let state=await Refresh.load(checkpoint);assert.deepEqual(state.cursor,cursor);assert.equal(state.nextIndex,1);assert.equal(state.processedCumulative,1);assert.equal((await Refresh.status(checkpoint)).publishedAssortmentComplete,false);assert.equal(await Refresh.resumeAt(checkpoint,now),new Date(now+60000).toISOString());
   const second={...first,offers:[offers[1]],products:[{retailerSku:offers[1].retailerSku}],cursor:{...cursor,nextIndex:2,lastSku:targets[1].retailerSku}};
   await assert.rejects(()=>Refresh.refresh({pool:checkpoint,now:()=>now},{discoverTargets:async()=>discovery,fetchProducts:async()=>second,persist:async()=>{throw Error("POSTGRES TEST admission failed");}}),/admission failed/);state=await Refresh.load(checkpoint);assert.deepEqual(state.cursor,cursor);assert.equal(state.nextIndex,1);
   await assert.rejects(()=>Refresh.refresh({pool:checkpoint,now:()=>now},{discoverTargets:async()=>discovery,fetchProducts:async()=>({...second,requests:2,partialError:{code:"aldi-source-http-429",status:429,retryAfterMs:7200000}})}),error=>error.code==="aldi-source-http-429"&&error.accepted===1&&error.checkpointSaved===true);state=await Refresh.load(checkpoint);assert.equal(state.nextIndex,2);assert.equal(state.lastError,"aldi-source-http-429");assert.equal(new Date(state.retryAfter).getTime(),now+7200000);assert.equal((await Service.search(checkpoint,{retailerSku:offers[1].retailerSku,now})).items.length,1,"Native quote before denial survives its failed scheduler run");assert.equal(state.completedCycles,0);
   assert.equal((await Refresh.refresh({pool:checkpoint,now:()=>now+60000},{discoverTargets:async()=>{throw Error("Cooldown must prevent a network read");}})).skipped,"source-cooldown");
   const last={...first,offers:[offers[2]],products:[{retailerSku:offers[2].retailerSku}],cursor:null,complete:true};await Refresh.refresh({pool:checkpoint,now:()=>now+7200000},{discoverTargets:async()=>discovery,fetchProducts:async()=>last});state=await Refresh.status(checkpoint);assert.equal(state.publishedAssortmentComplete,true);assert.equal(state.completedCycles,1);assert.equal(state.cursor,null);assert.equal(state.nextIndex,3);assert.equal(state.lastError,null);assert.equal(state.retryAfter,null);
   const newHash="8".repeat(64),newTargets=[...targets,{retailerSku:fixture(8003).retailerSku,sourceUrl:fixture(8003).sourceUrl}],newBatch={...first,offers:[offers[0]],cursor:{snapshotHash:newHash,nextIndex:1,lastSku:targets[0].retailerSku},snapshotHash:newHash,targetCount:4,cursorReset:false};
   // A completed cycle has no continuation cursor: its next scan naturally starts at zero.
   await Refresh.refresh({pool:checkpoint,now:()=>now+7200000},{discoverTargets:async()=>({...discovery,targets:newTargets,snapshotHash:newHash}),fetchProducts:async()=>newBatch});state=await Refresh.status(checkpoint);assert.equal(state.publishedAssortmentComplete,false);assert.equal(state.completedCycles,1);assert.equal(state.nextIndex,1);assert.equal(new Date(state.lastCompletedAt).getTime(),now+7200000);
  }finally{await checkpoint.query("ROLLBACK");checkpoint.release();}
  assert.equal((await Service.search(pool,{now:now+Service.DAY_MS+1})).items.length,0);
  await pool.query(`UPDATE ${Service.TABLE} SET captured_at=$2::timestamptz,expires_at=$2::timestamptz+interval '24 hours',source_response_date=$2::timestamptz WHERE retailer_sku=$1`,[fixture(1).retailerSku,new Date(now+3600000).toISOString()]);assert.equal((await Service.search(pool,{retailerSku:fixture(1).retailerSku,now})).items.length,0,"Future stored captures are never current");
  process.env.PORT="0";api=require("../server");await new Promise((resolve,reject)=>{api.server.once("error",reject);api.server.listen(0,"127.0.0.1",()=>{api.server.off("error",reject);resolve();});});const base="http://127.0.0.1:"+api.server.address().port;
  async function get(url){const res=await fetch(base+url,{signal:AbortSignal.timeout(10000)});return{status:res.status,body:await res.json()};}
  const publicQuery=await get("/v1/published-prices?merchant=ALDI%20Nord&search="+encodeURIComponent("product 0"));assert.equal(publicQuery.status,200,JSON.stringify(publicQuery));assert.equal(publicQuery.body.items.length,1);assert.equal(publicQuery.body.items[0].price,1.39);assert.equal(publicQuery.body.items[0].scopeChannel,"assortment-publication");assert.equal(publicQuery.body.items[0].gtin,null);assert.equal(publicQuery.body.items[0].physicalStorePriceVerified,false);
  const publicStatus=await get("/v1/published-prices/status");assert.equal(publicStatus.status,200,JSON.stringify(publicStatus));assert.equal(publicStatus.body.retailers.aldiNordAssortment.productsWithCurrentPublishedPrices,0);assert.equal(publicStatus.body.retailers.aldiNordAssortment.currentPrices,502);assert.equal(publicStatus.body.retailerResearch.aldiNordAssortment.physicalStoreAssortmentVerified,false);assert.equal(publicStatus.body.retailerResearch.aldiNordAssortment.normalPriceClassificationVerified,false);assert.equal(publicStatus.body.retailerResearch.aldiNordAssortment.independentOfUserReceipts,true);
  const noExactMatch=await get("/v1/published-prices?merchant=ALDI%20Nord&gtin="+gtin(0));assert.equal(noExactMatch.status,200);assert.equal(noExactMatch.body.items.length,0);
  const comparedResponse=await fetch(base+"/v1/current-prices",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({gtin:gtin(0),pack:"1 l",merchants:["ALDI Nord"]}),signal:AbortSignal.timeout(10000)}),compared=await comparedResponse.json();assert.equal(comparedResponse.status,200,JSON.stringify(compared));assert(compared.results.every(row=>row.state==="unknown"&&row.price===null));assert(!compared.publishedAlternatives.some(row=>row.sourceId===Service.SOURCE),"An ALDI article name cannot answer an exact GTIN comparison");
  for(const[table,count]of Object.entries(baseline)){if(count===null)assert.equal(await exists(table),false,"Separate ALDI evidence must not create "+table);else assert.equal((await pool.query("SELECT count(*)::int AS count FROM "+table)).rows[0].count,count,"Separate ALDI evidence must not mutate "+table);}
  console.log("aldi-assortment-price-postgres: 501 TEST native article prices, zero guessed GTINs, actual SQL admission/scope/freshness/native-expiry constraints, idempotent newer-only writes, saved partial denial checkpoints, HTTP search/status and unchanged canonical/physical/receipt ledgers OK");
 }finally{if(api){if(api.server.listening)await new Promise((resolve,reject)=>api.server.close(error=>error?reject(error):resolve()));await api.closeDb();}await pool.end();}
}
main().catch(error=>{console.error(error);process.exitCode=1;});
