"use strict";
const assert=require("node:assert/strict"),Service=require("../aldi-assortment-price-service"),Semantics=require("../source-semantics"),Sources=require("../price-sources"),Combined=require("../published-retailer-inventory");
const NOW=Date.parse("2026-10-01T12:00:00Z"),iso=n=>new Date(n).toISOString();
function offer(patch={}){return{sourceId:Service.SOURCE,merchant:"ALDI Nord",retailerSku:"1018999",gtin:null,name:"UNIT TEST Haltbare Vollmilch",brand:"MILSANI",variant:null,pack:"1-L-Packung",packAmount:1,packUnit:"l",packCount:1,price:.95,deposit:0,depositIncluded:false,currency:"EUR",priceBasis:"pack",priceKind:"published-current",regularPrice:null,promotionStatus:"unknown",availability:"unknown",publicationAvailable:true,capturedAt:iso(NOW-1000),nativeValidFrom:iso(NOW-86400000),nativeValidUntil:iso(NOW+86400000*2),sourceUrl:"https://www.aldi-nord.de/produkt/haltbare-vollmilch-1018999.html",sourceResponseHash:"a".repeat(64),proofHash:"b".repeat(64),sourceResponseDate:iso(NOW-1000),sourceAgeSeconds:null,scopeCountry:"DE",scopeChannel:"assortment-publication",locationScope:"unknown",...patch};}
function database(){const rows=new Map(),calls=[];return{rows,calls,query:async(sql,params=[])=>{calls.push({sql,params});if(sql.startsWith("CREATE TABLE"))return{rows:[],rowCount:0};if(sql.startsWith("SELECT p.source_id"))return{rows:JSON.parse(params[0]).map(r=>rows.get(r.source_id+"|"+r.retailer_sku)).filter(Boolean),rowCount:0};if(sql.startsWith("INSERT INTO aldi_assortment_published_prices")){let rowCount=0;for(const row of JSON.parse(params[0])){const key=row.source_id+"|"+row.retailer_sku,old=rows.get(key);if(!old||row.captured_at>old.captured_at){rows.set(key,row);rowCount++;}}return{rows:[],rowCount};}return{rows:[],rowCount:0};}};}
const valid=Service.validateOffer(offer(),{now:NOW});assert.equal(valid.ok,true,JSON.stringify(valid));assert.equal(valid.offer.packAmount,1000);assert.equal(valid.offer.packUnit,"ml");assert.equal(valid.offer.price,.95);assert.equal(valid.offer.gtin,null);assert.equal(valid.offer.expiresAt,iso(NOW-1000+Service.DAY_MS));assert.equal(valid.offer.truthEligible,false);
const deadline=Service.validateOffer(offer({nativeValidUntil:iso(NOW+500)}),{now:NOW});assert.equal(deadline.ok,true);assert.equal(deadline.offer.expiresAt,iso(NOW+500),"A native price deadline caps local freshness");
const unknown=Service.validateOffer(offer({deposit:null,depositIncluded:null}),{now:NOW});assert.equal(unknown.ok,true);assert.equal(unknown.offer.deposit,null);assert.equal(unknown.offer.payablePackPrice,null);
assert.equal(Service.validateOffer(offer({price:.9500000001}),{now:NOW}).offer.price,.95,"An accepted cent value is normalized before PostgreSQL numeric constraints");
for(const[patch,reason]of[
 [{sourceId:"ALDI Nord"},"retailer-source-not-approved"],[{merchant:"ALDI SÜD"},"retailer-source-not-approved"],[{retailerSku:"6525"},"native-article-id-required"],[{retailerSku:"01018999"},"native-article-id-required"],[{sourceUrl:"https://www.aldi-nord.de/produkt/haltbare-vollmilch-1018999.html?fake=1"},"exact-native-product-url-required"],
 [{gtin:"4008400401621"},"native-gtin-unattested"],[{storeId:"invented-berlin"},"physical-identity-scope-unsupported"],[{scopeChannel:"store"},"assortment-DE-scope-required"],[{locationScope:"Berlin"},"assortment-DE-scope-required"],[{scopeCountry:"AT"},"assortment-DE-scope-required"],
 [{pack:"ca. 1 l"},"known-fixed-pack-required"],[{pack:"1 l + 100 ml"},"known-fixed-pack-required"],[{packAmount:2},"pack-metadata-conflict"],[{packCount:true},"pack-metadata-conflict"],[{price:true},"positive-cent-pack-price-required"],[{price:.951},"positive-cent-pack-price-required"],[{price:Infinity},"positive-cent-pack-price-required"],[{currency:"USD"},"EUR-pack-price-required"],
 [{priceKind:"regular"},"normal-price-classification-unattested"],[{regularPrice:1.09},"normal-price-classification-unattested"],[{promotionStatus:"promotion"},"normal-price-classification-unattested"],[{availability:"available"},"publication-availability-scope-required"],[{publicationAvailable:false},"publication-availability-scope-required"],[{deposit:.25},"deposit-price-basis-unresolved"],[{depositIncluded:true},"deposit-price-basis-unresolved"],
 [{capturedAt:iso(NOW+1)},"capture-time-future"],[{capturedAt:"2026-02-30T12:00:00Z"},"capture-time-required"],[{nativeValidFrom:iso(NOW)},"native-current-validity-required"],[{nativeValidUntil:iso(NOW-1000)},"native-current-validity-required"],[{sourceResponseDate:null},"fresh-source-response-date-required"],[{sourceResponseDate:iso(NOW-302000)},"fresh-source-response-date-required"],[{sourceAgeSeconds:301},"source-cache-age-stale-or-invalid"],[{sourceAgeSeconds:-1},"source-cache-age-stale-or-invalid"],[{sourceAgeSeconds:"2"},"source-cache-age-stale-or-invalid"],[{sourceResponseHash:"fake"},"source-proof-hash-required"],[{proofHash:"fake"},"source-proof-hash-required"],[{sourceResponseUrl:"https://example.test/price"},"exact-native-response-url-required"]
]){const checked=Service.validateOffer(offer(patch),{now:NOW});assert.equal(checked.ok,false,reason);assert(checked.reasons.includes(reason),JSON.stringify(checked));}
assert(Sources.canImport(Service.SOURCE));assert.equal(Semantics.truthEligible({source:Service.SOURCE}),false);assert.equal(Semantics.allowedFor({source:Service.SOURCE},"identity"),true);assert.equal(Combined.matchesProductQuery(valid.offer,{gtin:"4008400401621",pack:"1 l"}),false,"Native SKU articles must never be invented as GTIN matches");
async function main(){
 const db=database(),original=offer(),snapshot=JSON.stringify(original);let saved=await Service.persist(db,[original,offer({price:0})],{now:NOW});assert.equal(saved.accepted,1);assert.equal(saved.rejected,1);assert.equal(saved.upserted,1);assert.equal(JSON.stringify(original),snapshot);
 assert.equal((await Service.persist(db,[original],{now:NOW})).unchanged,1);
 const conflict=offer({price:1.09});saved=await Service.persist(db,[conflict],{now:NOW});assert.equal(saved.rejected,1);assert.equal(saved.reasons["same-capture-conflict"],1);assert.equal([...db.rows.values()][0].price,.95);
 const empty=database();saved=await Service.persist(empty,[original,conflict],{now:NOW});assert.equal(saved.accepted,0);assert.equal(saved.rejected,2);assert.equal(empty.rows.size,0);
 const newer=offer({price:1.09,capturedAt:iso(NOW),sourceResponseDate:iso(NOW),proofHash:"c".repeat(64)});assert.equal((await Service.persist(db,[newer],{now:NOW})).upserted,1);assert.equal((await Service.persist(db,[original],{now:NOW})).unchanged,1);assert.equal([...db.rows.values()][0].price,1.09);
 assert(!db.calls.some(c=>/price_observations|INSERT INTO (?:products|stores|receipts)\b/.test(c.sql)));
 const q=Service.querySpec({now:NOW,merchant:"ALDI Nord",search:"Milch%_",limit:999});assert.equal(q.params.at(-1),200);assert.equal(q.params[2],"%Milch\\%\\_%");assert(q.sql.includes("native_valid_until>$1"));assert(q.sql.includes("interval '24 hours'"));
 assert.throws(()=>Service.querySpec({gtin:"invalid"}),/invalid-gtin/);assert.throws(()=>Service.querySpec({today:"2026-02-30"}),/invalid-date/);
 await assert.rejects(()=>Service.persist(null,[]),/database-required/);await assert.rejects(()=>Service.search(null),/database-required/);await assert.rejects(()=>Service.persist(db,{}),/invalid-published-offers/);
 console.log("aldi-assortment-price-service: strict source/SKU/pack/validity and HTTP proof, unknown GTIN/branch/normal price, deposit gaps, capped expiry, idempotency and conflicting capture rejection OK");
}
main().catch(e=>{console.error(e);process.exitCode=1;});
