"use strict";
const assert=require("node:assert/strict"),crypto=require("node:crypto"),Client=require("../aldi-category-fetch-client"),Fixture=require("./fixtures/aldi-category-capture");
const time=Date.UTC(2026,9,3,3,30),body=Fixture.html(),headers={"content-type":"text/html; charset=utf-8",date:new Date(time).toUTCString(),age:"0"};
async function capture(response,options={}){const calls=[];const result=await Client.fetchPage(Fixture.url,{now:()=>time,fetchImpl:async(url,request)=>{calls.push({url,request});return response;},...options});return{result,calls};}
async function rejected(code,response,options={}){let calls=0;await assert.rejects(Client.fetchPage(Fixture.url,{now:()=>time,fetchImpl:async()=>{calls++;return response;},...options}),error=>error.code===code);assert.equal(calls,1,"No retry or alternate URL after a source error");}
(async()=>{let checks=0;
 const successful=await capture(new Response(body,{status:200,headers}));assert.equal(successful.calls.length,1);assert.equal(successful.calls[0].request.redirect,"error");assert.equal(successful.calls[0].request.credentials,"omit");assert.equal(successful.calls[0].request.method,"GET");assert.equal(successful.result.requests,1);assert.equal(successful.result.original.body,body);assert.equal(successful.result.original.meta.sourceResponseHash,crypto.createHash("sha256").update(body).digest("hex"));assert.equal(successful.result.page.candidateCount,1);assert.equal(successful.result.page.candidates[0].admitted,false);assert.equal(successful.result.assortmentComplete,false);assert.deepEqual(successful.result.discoveredTargets,[Fixture.url,"https://www.aldi-nord.de/sortiment/vorraete.html"].sort());checks++;
 for(const status of[403,429,500,404,301]){await rejected("aldi-category-http-"+status,new Response("source refused",{status,headers:{"retry-after":"3600"}}));checks++;}
 for(const url of["https://www.aldi-nord.de/sortiment/vorraete.html?x=1","https://www.aldi-nord.de/sortiment/vorraete.html#x","https://www.aldi-nord.de/produkt/milk-1040001.html","https://www.aldi-sued.de/sortiment/vorraete.html","https://u:p@www.aldi-nord.de/sortiment/vorraete.html"]){let called=false;await assert.rejects(Client.fetchPage(url,{fetchImpl:async()=>{called=true;}}),e=>e.code==="aldi-category-url-not-allowed");assert.equal(called,false);checks++;}
 await rejected("aldi-category-html-response-required",new Response(body,{headers:{...headers,"content-type":"application/json"}}));checks++;
 for(const [code,response]of[["aldi-category-response-url-conflict",{status:200,url:"https://www.aldi-nord.de/sortiment/vorraete.html",headers:new Headers(headers)}],["aldi-category-html-response-required",new Response(body,{headers:{...headers,"content-type":"application/json"}})],["aldi-category-response-byte-budget",new Response(body,{headers:{...headers,"content-length":String(5*1024*1024)}})]]){let signal;await assert.rejects(Client.fetchPage(Fixture.url,{now:()=>time,fetchImpl:async(_url,request)=>{signal=request.signal;return response;}}),e=>e.code===code);assert.equal(signal.aborted,true,"Early rejected headers terminate the underlying response, too");checks++;}
 await rejected("aldi-category-response-byte-budget",new Response(body,{headers:{...headers,"content-length":String(body.length+1)}}),{maxBytes:body.length});checks++;
 await rejected("aldi-category-response-byte-budget",new Response(body,{headers}),{maxBytes:10});checks++;
 await rejected("aldi-category-response-utf8-required",new Response(new Uint8Array([0xc3,0x28]),{headers}));checks++;
 await rejected("aldi-category-source-proof-invalid",new Response(body,{headers:{...headers,date:new Date(time-6*60000).toUTCString()}}));checks++;
 await rejected("aldi-category-source-age-invalid",new Response(body,{headers:{...headers,age:"NaN"}}));checks++;
 await rejected("aldi-category-original-http-proof-required",new Response(body,{headers:{"content-type":"text/html"}}));checks++;
 const bom="\ufeff"+body,roundtrip=(await capture(new Response(bom,{headers}))).result.original;assert.equal(roundtrip.body,bom);assert.equal(roundtrip.meta.sourceResponseHash,crypto.createHash("sha256").update(roundtrip.body).digest("hex"),"Retained original text reproduces BOM-inclusive capture bytes");checks++;
 let calls=0;await assert.rejects(Client.fetchPage(Fixture.url,{fetchImpl:async()=>{calls++;throw Error("network failed");}}),e=>e.code==="aldi-category-fetch-failed"&&e.requestStarted===true);assert.equal(calls,1);checks++;
 assert.equal(Client.retryAfter(new Headers({"retry-after":"7200"}),time),7200000);assert.equal(Client.retryAfter(new Headers({"retry-after":new Date(time+60000).toUTCString()}),time),60000);assert.equal(Client.retryAfter(new Headers({"retry-after":"-1"}),time),null);checks++;
 for(const retry of["691200",new Date(time+8*86400000).toUTCString()]){let calls=0;await assert.rejects(Client.fetchPage(Fixture.url,{now:()=>time,fetchImpl:async()=>{calls++;return new Response("wait",{status:429,headers:{"retry-after":retry}});}}),e=>e.code==="aldi-category-http-429"&&e.retryAfterMs===8*86400000);assert.equal(calls,1);checks++;}
 assert.equal(Client.retryAfter(new Headers({"retry-after":"999999999999999999999999999999"}),time),8640000000000000-time);checks++;
 assert.throws(()=>Client.targets([Fixture.url,Fixture.url]),e=>e.code==="aldi-category-targets-duplicate");assert.throws(()=>Client.targets([]),e=>e.code==="aldi-category-targets-invalid");assert.deepEqual(Client.targets([Fixture.url]),[Fixture.url]);checks++;
 const foreign=Fixture.html(undefined,{navigation:[{Produkte:{children:[{path:"https://evil.example/sortiment/vorraete.html"},{path:"https://www.aldi-nord.de/sortiment/vorraete.html?private=1"}]}},{Other:{path:"https://www.aldi-nord.de/sortiment/snacks.html"}}]});assert.deepEqual(Client.navigationTargets(foreign),[]);checks++;
 const nativeShape=JSON.parse(body.match(/<script[^>]*>([\s\S]*?)<\/script>/)[1]),originalHeader=nativeShape.props.pageProps.page.header[0];originalHeader.sideDrawerNavigation={0:originalHeader.sideDrawerNavigation[0]};nativeShape.props.pageProps.page.header={0:originalHeader,"@path":"/germany/metadata/header","@nodes":["0"]};const actualLayout=body.replace(/(<script[^>]*>)[\s\S]*?(<\/script>)/,"$1"+JSON.stringify(nativeShape)+"$2");assert.deepEqual(Client.navigationTargets(actualLayout),successful.result.discoveredTargets,"The real archived CMS navigation uses numbered objects, not arrays");checks++;
 console.log("aldi-category-fetch-client: "+checks+" original transport, bounded body, native navigation and no-retry groups passed");
})().catch(error=>{console.error(error);process.exitCode=1;});
