"use strict";
const assert=require("node:assert/strict"),Refresh=require("../aldi-assortment-refresh"),Client=require("../aldi-assortment-client");
const NOW=Date.parse("2026-10-01T12:00:00Z"),HASH=Client.stableTargets(targets()).snapshotHash,OTHER_HASH=Client.stableTargets(targets(7)).snapshotHash,copy=value=>structuredClone(value),snapshotCache=new WeakMap();
function database(initial={}){const state=copy(initial),calls=[];let failCheckpoint=false;return{state,calls,get failCheckpoint(){return failCheckpoint;},set failCheckpoint(value){failCheckpoint=value;},query:async(sql,params=[])=>{calls.push({sql,params:copy(params)});if(sql.startsWith("SELECT cursor"))return{rows:Object.keys(state).length?[copy(state)]:[]};if(sql.startsWith("INSERT INTO aldi_assortment_catalog_state")&&params.length===4){Object.assign(state,{lastError:params[1],retryAfter:params[2],updatedAt:params[3]});return{rowCount:1,rows:[]};}if(sql.startsWith("INSERT INTO aldi_assortment_catalog_state")){if(failCheckpoint)throw Error("checkpoint-database-down");Object.assign(state,{cursor:JSON.parse(params[1]),lastCompletedAt:params[2]?params[3]:state.lastCompletedAt||null,completedCycles:(state.completedCycles||0)+(params[2]?1:0),targetCount:params[4],nextIndex:params[5],processedCumulative:params[6],snapshotHash:params[7],lastError:params[8],retryAfter:params[9],updatedAt:params[3],priceRefreshState:JSON.parse(params[10])});return{rowCount:1,rows:[]};}return{rows:[],rowCount:0};}};}
function targets(size=6){return Array.from({length:size},(_,i)=>({retailerSku:String(1000000+i),sourceUrl:"https://www.aldi-nord.de/produkt/test-product-"+(1000000+i)+".html"}));}
function snapshot(list){if(!snapshotCache.has(list))snapshotCache.set(list,Client.stableTargets(list).snapshotHash);return snapshotCache.get(list);}
function discovered(list=targets(),snapshotHash=snapshot(list)){return{targets:list,snapshotHash,requests:1,bytes:100,discoveredAt:new Date(NOW).toISOString(),sourceId:Client.SOURCE};}
function cursor(list,index,snapshotHash=snapshot(list)){return{snapshotHash,nextIndex:index,lastSku:index?list[index-1].retailerSku:null};}
function newCursor(list,index,gaps=[]){return{...cursor(list,index),unresolvedTargets:copy(gaps)};}
function proof(target,time=NOW,patch={}){return{...target,status:200,kind:"detail",capturedAt:new Date(time).toISOString(),sourceResponseHash:"c".repeat(64),sourceResponseDate:new Date(time).toISOString(),sourceAgeSeconds:null,...patch};}
function product(proof){return{retailerSku:proof.retailerSku,sourceUrl:proof.sourceUrl,observedAt:proof.capturedAt,sourceResponseHash:proof.sourceResponseHash,sourceResponseDate:proof.sourceResponseDate,sourceAgeSeconds:proof.sourceAgeSeconds};}
function offer(proof){return{...product(proof),capturedAt:proof.capturedAt,gtin:null,name:"UNIT TEST ALDI published product",price:1.29,scopeChannel:"assortment-publication",truthEligible:false};}
function gap(target,time=NOW,attempts=1,code="aldi-native-source-unavailable"){const p=proof(target,time);delete p.status;delete p.kind;return{...p,code,attempts,retryAfter:new Date(time+3600000).toISOString()};}
function batch(list,start,processed,patch={}){const nextIndex=start+processed,complete=nextIndex===list.length,confirmedTargets=list.slice(start,nextIndex).map(t=>proof(t)),offers=confirmedTargets.map(p=>offer(p)),products=confirmedTargets.map(p=>product(p));if(patch.products?.length===0)confirmedTargets.forEach(p=>{p.kind="rejected";});return{offers,products,rejected:[],processed,requests:processed,bytes:200*processed,complete,partialError:null,cursor:complete?null:newCursor(list,nextIndex),cursorReset:false,snapshotHash:snapshot(list),targetCount:list.length,nextIndex,unresolvedTargets:[],gapAttempts:0,deferredUntil:null,confirmedTargets,...patch};}
function gapBatch(list,{start=0,nextIndex,confirmed=[],gaps=[],gapAttempts=0,requests=nextIndex-start,partialError=null,time=NOW}={}){const complete=nextIndex===list.length&&!gaps.length;return{offers:confirmed.filter(p=>p.kind==="detail").map(p=>offer(p)),products:confirmed.filter(p=>p.kind==="detail").map(p=>product(p)),rejected:[],processed:confirmed.length,requests,bytes:requests*200,complete,partialError,cursor:complete?null:newCursor(list,nextIndex,gaps),cursorReset:false,snapshotHash:snapshot(list),targetCount:list.length,nextIndex,unresolvedTargets:copy(gaps),gapAttempts,deferredUntil:nextIndex===list.length&&gaps.length&&gaps.every(g=>Date.parse(g.retryAfter)>time)?new Date(Math.min(...gaps.map(g=>Date.parse(g.retryAfter)))).toISOString():null,confirmedTargets:copy(confirmed)};}
function regular(list,patch={}){return{snapshotHash:snapshot(list),nextIndex:0,lastSku:null,lastCompletedAt:null,completedPasses:0,lastRunKind:"catalog",nextPassAt:new Date(NOW).toISOString(),passStartedAt:null,...patch};}
function ended(list,gaps,patch={}){return{cursor:newCursor(list,list.length,gaps),targetCount:list.length,nextIndex:list.length,processedCumulative:list.length-gaps.length,snapshotHash:snapshot(list),updatedAt:new Date(NOW).toISOString(),priceRefreshState:regular(list),...patch};}
async function main(){
 const list=targets(),pool=database(),steps=[],seen=[];let start=0;
 const deps={discoverTargets:async options=>{assert.equal(options.maxRequests,1);assert.equal(options.now(),new Date(NOW).toISOString());steps.push("sitemap");return discovered(list);},fetchProducts:async(input,options)=>{assert.deepEqual(input,list);assert.equal(options.maxRequests,2);assert.equal(options.now(),new Date(NOW).toISOString());seen.push(copy(options.cursor));steps.push("product-pages");const result=batch(list,start,2);start+=2;return result;},persist:async(db,offers)=>{assert.equal(db,pool);steps.push("save-prices");return{received:offers.length,accepted:offers.length,rejected:0,upserted:offers.length};}};
 for(let run=1;run<=3;run++){const result=await Refresh.refresh({pool,maxRequests:3,now:()=>NOW},deps);assert.equal(result.requests,3);assert.equal(result.accepted,2);assert.equal(result.catalog.nextIndex,run*2);assert.equal(result.catalog.processedCumulative,run*2);assert.equal(result.catalog.publishedAssortmentComplete,run===3);assert.equal(result.catalog.physicalStoreAssortmentVerified,false);assert.equal(result.scope.channel,"assortment-publication");assert.equal(result.scope.location,"unknown");assert.equal(result.independentOfUserReceipts,true);assert.equal(result.nextAttemptAt,run===3?null:new Date(NOW+60000).toISOString());const current=await Refresh.status(pool);assert.equal(current.publishedAssortmentComplete,run===3);assert.equal(current.completedCycles||0,run===3?1:0);assert.equal(current.normalPriceClassificationVerified,false);assert.equal(current.physicalStoreAssortmentVerified,false);}
 assert.deepEqual(seen,[null,newCursor(list,2),newCursor(list,4)]);assert.deepEqual(steps,Array(3).fill(["sitemap","product-pages","save-prices"]).flat());assert.equal(pool.state.cursor,null);assert.equal(pool.state.lastCompletedAt,new Date(NOW).toISOString());assert(!pool.calls.some(call=>/INSERT INTO (?:products|stores|price_observations|receipts|receipt_submissions)\b/.test(call.sql)));
 assert.equal(await Refresh.resumeAt(pool,NOW),null);
 for(const[value,expected]of[[undefined,16],[999,32],[1,2],[0,16],[NaN,16]]){let actual;const result=await Refresh.refresh({pool:database(),maxRequests:value,now:()=>NOW},{discoverTargets:async()=>discovered(targets(1)),fetchProducts:async(_,options)=>{actual=options.maxRequests;return batch(targets(1),0,1);},persist:async()=>({accepted:1})});assert.equal(actual,expected-1);assert.equal(result.requests,2);}
 // A catalog larger than 6,000 articles is traversed in bounded batches, including pages without a price.
 const large=targets(6001),largeDb=database();let visited=0,largestBudget=0;
 while(visited<large.length){const result=await Refresh.refresh({pool:largeDb,maxRequests:999,now:()=>NOW},{discoverTargets:async()=>discovered(large),fetchProducts:async(_,options)=>{largestBudget=Math.max(largestBudget,options.maxRequests);const count=Math.min(options.maxRequests,large.length-visited),result=batch(large,visited,count,{offers:[],products:[],rejected:Array(count).fill({reasons:["aldi-current-pack-price-required"]})});visited+=count;return result;},persist:async(_,offers)=>{assert.equal(offers.length,0);return{received:0,accepted:0,rejected:0};}});assert(result.requests<=32);assert.equal(result.accepted,0);}
 assert.equal(visited,6001);assert.equal(largestBudget,31);assert.equal((await Refresh.status(largeDb)).publishedAssortmentComplete,true);assert.equal(largeDb.state.processedCumulative,6001);
 const partialDb=database({cursor:cursor(list,2),nextIndex:2,processedCumulative:2,targetCount:6}),before=copy(partialDb.state);let saved=0;
 await assert.rejects(()=>Refresh.refresh({pool:partialDb,now:()=>NOW},{discoverTargets:async()=>discovered(list),fetchProducts:async()=>batch(list,2,1),persist:async()=>{throw Error("quote-database-down");}}),/quote-database-down/);assert.deepEqual(partialDb.state,before,"Failed price persistence must not skip a source page");
 partialDb.failCheckpoint=true;await assert.rejects(()=>Refresh.refresh({pool:partialDb,now:()=>NOW},{discoverTargets:async()=>discovered(list),fetchProducts:async()=>batch(list,2,1),persist:async(_,offers)=>{saved+=offers.length;return{accepted:offers.length};}}),/checkpoint-database-down/);assert.equal(saved,1);assert.deepEqual(partialDb.state,before);partialDb.failCheckpoint=false;
 let retried;await Refresh.refresh({pool:partialDb,now:()=>NOW},{discoverTargets:async()=>discovered(list),fetchProducts:async(_,options)=>{retried=options.cursor;return batch(list,2,1);},persist:async()=>({received:1,accepted:0,rejected:1})});assert.deepEqual(retried,before.cursor);assert.equal(partialDb.state.nextIndex,3,"A scanned native page advances even when price admission rejects it");
 for(const[stage,code,retryAfterMs,delay]of[["discovery","aldi-source-http-403",undefined,3600000],["products","aldi-source-http-429",7200000,7200000]]){const blocked=database({cursor:cursor(list,2),nextIndex:2,processedCumulative:2}),beforeCursor=copy(blocked.state.cursor);let calls=0,persists=0;const error=Object.assign(Error(code),{code,retryAfterMs}),blockedDeps={discoverTargets:async()=>{calls++;if(stage==="discovery")throw error;return discovered(list);},fetchProducts:async()=>{calls++;throw error;},persist:async()=>{persists++;return{accepted:0};}};await assert.rejects(()=>Refresh.refresh({pool:blocked,now:()=>NOW},blockedDeps),err=>err.code===code&&err.nextAttemptAt===new Date(NOW+delay).toISOString());assert.deepEqual(blocked.state.cursor,beforeCursor);assert.equal(persists,0);const priorCalls=calls,skipped=await Refresh.refresh({pool:blocked,now:()=>NOW+delay-1},blockedDeps);assert.equal(skipped.skipped,"source-cooldown");assert.equal(calls,priorCalls);assert.equal(await Refresh.resumeAt(blocked,NOW),new Date(NOW+delay).toISOString());assert.equal(await Refresh.resumeAt(blocked,NOW+delay+1),new Date(NOW+delay+1).toISOString());}
 // Prices preceding a denial are retained, while the failed source run remains a failure.
 for(const[retryAfterMs,delay]of[[undefined,3600000],[1000,Refresh.REFRESH_MS],[7200000,7200000]]){const denied=database({cursor:cursor(list,2),nextIndex:2,processedCumulative:2,completedCycles:1,lastCompletedAt:new Date(NOW-86400000).toISOString()}),order=[];const partial=batch(list,2,1,{requests:2,partialError:{code:"aldi-source-http-429",status:429,retryAfterMs,requestStarted:true,retryingGap:false,...list[3]}});await assert.rejects(()=>Refresh.refresh({pool:denied,now:()=>NOW},{discoverTargets:async()=>discovered(list),fetchProducts:async()=>partial,persist:async(_,offers)=>{order.push("price-saved");assert.equal(offers.length,1);return{received:1,accepted:1,rejected:0};}}),err=>{assert.equal(err.code,"aldi-source-http-429");assert.equal(err.nextAttemptAt,new Date(NOW+delay).toISOString());assert.equal(err.accepted,1);assert.equal(err.received,1);assert.equal(err.checkpointSaved,true);assert.equal(err.partialResult.catalog.nextIndex,3);assert.equal(denied.state.nextIndex,3,"Error must be thrown only after saved-price checkpoint");return true;});assert.deepEqual(order,["price-saved"]);assert.equal(denied.state.completedCycles,1);assert.equal(denied.state.lastCompletedAt,new Date(NOW-86400000).toISOString());assert.equal(denied.state.lastError,"aldi-source-http-429");assert.equal((await Refresh.status(denied)).publishedAssortmentComplete,false);}
 const drift=database({cursor:cursor(list,4),nextIndex:4,processedCumulative:4,targetCount:6,snapshotHash:HASH,completedCycles:2,lastCompletedAt:new Date(NOW-100000).toISOString()}),newList=targets(7);let driftCursor;
 const changed=batch(newList,0,1,{snapshotHash:OTHER_HASH,cursor:cursor(newList,1,OTHER_HASH),cursorReset:true});const driftResult=await Refresh.refresh({pool:drift,now:()=>NOW},{discoverTargets:async()=>discovered(newList,OTHER_HASH),fetchProducts:async(_,options)=>{driftCursor=options.cursor;return changed;},persist:async()=>({accepted:1})});assert.deepEqual(driftCursor,cursor(list,4));assert.equal(driftResult.cursorReset,true);assert.equal(drift.state.nextIndex,1);assert.equal(drift.state.processedCumulative,1);assert.equal(drift.state.completedCycles,2);assert.equal((await Refresh.status(drift)).publishedAssortmentComplete,false);assert.equal(await Refresh.resumeAt(drift,NOW),new Date(NOW+60000).toISOString());
 const invalid=[{offers:null},{products:null},{rejected:null},{targetCount:7},{snapshotHash:OTHER_HASH},{processed:-1},{processed:0,requests:1,cursor:cursor(list,2)},{processed:2,requests:1},{requests:99},{bytes:-1},{complete:true,cursor:null},{cursor:null},{cursor:cursor(list,4)},{cursor:{...cursor(list,3),lastSku:"wrong"}},{cursorReset:true}];
 for(const patch of invalid){const db=database({cursor:cursor(list,2),nextIndex:2,processedCumulative:2,targetCount:6});let persists=0;await assert.rejects(()=>Refresh.refresh({pool:db,maxRequests:3,now:()=>NOW},{discoverTargets:async()=>discovered(list),fetchProducts:async()=>batch(list,2,1,patch),persist:async()=>{persists++;return{accepted:0};}}),/aldi-catalog-(?:progress|snapshot)/);assert.equal(persists,0);assert.deepEqual(db.state.cursor,cursor(list,2));assert.equal(db.state.nextIndex,2);}
 const driftWithoutReset=database({cursor:cursor(list,2),nextIndex:2,processedCumulative:2});await assert.rejects(()=>Refresh.refresh({pool:driftWithoutReset,now:()=>NOW},{discoverTargets:async()=>discovered(newList,OTHER_HASH),fetchProducts:async()=>({...changed,cursorReset:false}),persist:async()=>{throw Error("Must not persist unconfirmed drift");}}),/snapshot-reset-unconfirmed/);
 // HTTP200 native item failures are durable gaps, not source-wide failures or completed catalog pages.
 const firstGap=gap(list[0]),gapDb=database(),gapSaved=[];
 const gapDeps=result=>({discoverTargets:async()=>discovered(list),fetchProducts:async()=>result,persist:async(_,offers)=>{gapSaved.push(offers.length);return{received:offers.length,accepted:offers.length,rejected:0};}});
 const firstGapRun=await Refresh.refresh({pool:gapDb,maxRequests:4,now:()=>NOW},gapDeps(gapBatch(list,{nextIndex:3,confirmed:[proof(list[1]),proof(list[2])],gaps:[firstGap],gapAttempts:1})));
 assert.equal(firstGapRun.catalog.nextIndex,3);assert.equal(firstGapRun.catalog.scannedCount,3);assert.equal(firstGapRun.catalog.processedCumulative,2);assert.equal(firstGapRun.catalog.unresolvedCount,1);assert.equal(firstGapRun.catalog.publishedAssortmentComplete,false);assert.equal(gapDb.state.lastError,null);assert.equal(gapDb.state.retryAfter,null);assert.deepEqual(gapDb.state.cursor.unresolvedTargets,[firstGap]);assert.equal(firstGapRun.nextAttemptAt,new Date(NOW+60000).toISOString());
 const continuationAt=NOW+60000,finishedFrontier=gapBatch(list,{start:3,nextIndex:6,confirmed:list.slice(3).map(t=>proof(t,continuationAt)),gaps:[firstGap],time:continuationAt});
 const scanned=await Refresh.refresh({pool:gapDb,maxRequests:4,now:()=>continuationAt},gapDeps(finishedFrontier));
 const firstRescanAt=new Date(continuationAt+Refresh.REFRESH_MS).toISOString();assert.equal(scanned.catalog.scannedCount,6);assert.equal(scanned.catalog.processedCumulative,5);assert.equal(scanned.catalog.unresolvedCount,1);assert.equal(scanned.catalog.publishedAssortmentComplete,false);assert.equal(scanned.deferredUntil,firstGap.retryAfter);assert.equal(scanned.nextAttemptAt,firstRescanAt);assert.equal(gapDb.state.completedCycles,0);assert.equal((await Refresh.status(gapDb)).unresolvedCount,1);assert.equal((await Refresh.status(gapDb)).scannedCount,6);assert.equal(await Refresh.resumeAt(gapDb,continuationAt),firstRescanAt);
 const waitAt=NOW+120000,waiting=await Refresh.refresh({pool:gapDb,maxRequests:2,now:()=>waitAt},gapDeps(gapBatch(list,{start:6,nextIndex:6,gaps:[firstGap],time:waitAt})));
 assert.equal(waiting.requests,1,"A deferred end cursor consumes only its bounded sitemap discovery");assert.equal(waiting.processed,0);assert.equal(waiting.gapAttempts,0);assert.equal(waiting.catalog.processedCumulative,5);assert.equal(waiting.nextAttemptAt,firstRescanAt);assert.equal(waiting.runKind,"deferred");assert.equal(gapDb.state.lastError,null);assert.equal(gapDb.state.retryAfter,null);assert.equal(await Refresh.resumeAt(gapDb,NOW+3600001),new Date(NOW+3600001).toISOString());
 const retryAt=NOW+3600000,repeatedGap=gap(list[0],retryAt,2,"aldi-product-page-schema-invalid");
 gapDb.state.priceRefreshState.lastRunKind="price-refresh";
 const repeated=await Refresh.refresh({pool:gapDb,maxRequests:2,now:()=>retryAt},gapDeps(gapBatch(list,{start:6,nextIndex:6,gaps:[repeatedGap],gapAttempts:1,requests:1,time:retryAt})));
 assert.equal(repeated.processed,0);assert.equal(repeated.gapAttempts,1);assert.equal(repeated.catalog.processedCumulative,5);assert.equal(repeated.runKind,"gap-retry");assert.equal(repeated.nextAttemptAt,new Date(retryAt).toISOString());assert.deepEqual(gapDb.state.cursor.unresolvedTargets,[repeatedGap]);assert.equal(gapDb.state.lastError,null);
 gapDb.state.priceRefreshState.lastRunKind="price-refresh";
 const recoveredAt=NOW+7200000,recovered=await Refresh.refresh({pool:gapDb,maxRequests:2,now:()=>recoveredAt},gapDeps(gapBatch(list,{start:6,nextIndex:6,confirmed:[proof(list[0],recoveredAt)],gapAttempts:1,requests:1,time:recoveredAt})));
 assert.equal(recovered.processed,1);assert.equal(recovered.catalog.nextIndex,6);assert.equal(recovered.catalog.processedCumulative,6);assert.equal(recovered.catalog.unresolvedCount,0);assert.equal(recovered.catalog.publishedAssortmentComplete,true);assert.equal(gapDb.state.cursor,null);assert.equal(gapDb.state.completedCycles,1);assert.deepEqual(gapSaved,[2,3,0,0,1]);assert.equal((await Refresh.status(gapDb)).publishedAssortmentComplete,true);
 const only=targets(2),onlyGaps=only.map(t=>gap(t)),allGapDb=database();
 const allGaps=await Refresh.refresh({pool:allGapDb,maxRequests:3,now:()=>NOW},{discoverTargets:async()=>discovered(only),fetchProducts:async()=>gapBatch(only,{nextIndex:2,gaps:onlyGaps,gapAttempts:2}),persist:async(_,offers)=>{assert.equal(offers.length,0);return{accepted:0};}});
 assert.equal(allGaps.processed,0);assert.equal(allGaps.catalog.scannedCount,2);assert.equal(allGaps.catalog.processedCumulative,0);assert.equal(allGaps.catalog.unresolvedCount,2);assert.equal(allGapDb.state.lastError,null);assert.equal(allGapDb.state.cursor.nextIndex,2);assert.equal(allGapDb.state.completedCycles,0);
 // Permanent native 404/410 attests an absent listing; a rejected HTTP200 retry cannot erase a gap.
 for(const status of[404,410]){const ended=database({cursor:newCursor(only,2,[onlyGaps[0]]),nextIndex:2,processedCumulative:1,targetCount:2});const p=proof(only[0],retryAt,{status,kind:"missing",sourceResponseHash:null,sourceResponseDate:null,sourceAgeSeconds:null});const missing=await Refresh.refresh({pool:ended,maxRequests:2,now:()=>retryAt},{discoverTargets:async()=>discovered(only),fetchProducts:async()=>gapBatch(only,{start:2,nextIndex:2,confirmed:[p],gapAttempts:1,requests:1,time:retryAt}),persist:async(_,offers)=>{assert.equal(offers.length,0);return{accepted:0};}});assert.equal(missing.catalog.publishedAssortmentComplete,true);assert.equal(missing.catalog.processedCumulative,2);}
 for(const code of["aldi-source-http-403","aldi-source-http-429"]){const blockedGap=database({cursor:newCursor(only,2,[onlyGaps[0]]),nextIndex:2,processedCumulative:1,targetCount:2});const result=gapBatch(only,{start:2,nextIndex:2,gaps:[onlyGaps[0]],gapAttempts:1,requests:1,time:retryAt,partialError:{code,status:Number(code.slice(-3)),retryingGap:true,requestStarted:true,...only[0]}});await assert.rejects(()=>Refresh.refresh({pool:blockedGap,maxRequests:2,now:()=>retryAt},{discoverTargets:async()=>discovered(only),fetchProducts:async()=>result,persist:async()=>({accepted:0})}),err=>err.code===code&&err.checkpointSaved&&err.partialResult.catalog.unresolvedCount===1);assert.deepEqual(blockedGap.state.cursor.unresolvedTargets,[onlyGaps[0]]);assert.equal(blockedGap.state.lastError,code);assert.equal(blockedGap.state.retryAfter,new Date(retryAt+3600000).toISOString());assert.equal(await Refresh.resumeAt(blockedGap,retryAt),blockedGap.state.retryAfter);}
 const gapThenDenied=database(),partialGap=gapBatch(only,{nextIndex:1,gaps:[onlyGaps[0]],gapAttempts:1,requests:2,partialError:{code:"aldi-source-http-429",status:429,retryingGap:false,requestStarted:true,...only[1]}});
 await assert.rejects(()=>Refresh.refresh({pool:gapThenDenied,maxRequests:3,now:()=>NOW},{discoverTargets:async()=>discovered(only),fetchProducts:async()=>partialGap,persist:async()=>({accepted:0})}),err=>err.code==="aldi-source-http-429"&&err.checkpointSaved&&err.partialResult.processed===0);assert.equal(gapThenDenied.state.nextIndex,1);assert.equal(gapThenDenied.state.processedCumulative,0);assert.deepEqual(gapThenDenied.state.cursor.unresolvedTargets,[onlyGaps[0]]);
 const withGapState={cursor:newCursor(only,2,[onlyGaps[0]]),nextIndex:2,processedCumulative:1,targetCount:2};
 // A valid no-request deferral crossing its exact deadline during validation is due, not forged progress.
 const crossed=database(withGapState);let boundaryClock=retryAt-1;
 const crossedResult=await Refresh.refresh({pool:crossed,maxRequests:2,now:()=>boundaryClock},{discoverTargets:async()=>discovered(only),fetchProducts:async()=>{const result=gapBatch(only,{start:2,nextIndex:2,gaps:[onlyGaps[0]],time:boundaryClock});boundaryClock=retryAt+1;return result;},persist:async()=>({accepted:0})});
 assert.equal(crossedResult.requests,1);assert.equal(crossedResult.processed,0);assert.equal(crossedResult.deferredUntil,null);assert.equal(crossedResult.nextAttemptAt,new Date(retryAt+1).toISOString());assert.equal(crossed.state.lastError,null);assert.equal(await Refresh.resumeAt(crossed,boundaryClock),new Date(boundaryClock).toISOString());
 const validRecovery=gapBatch(only,{start:2,nextIndex:2,confirmed:[proof(only[0],retryAt)],gapAttempts:1,requests:1,time:retryAt});
 const badGapResults=[
  {...validRecovery,confirmedTargets:[proof(only[0],retryAt,{kind:"rejected"})],products:[],offers:[]},
  {...validRecovery,confirmedTargets:[],products:[],offers:[],processed:0},
  {...validRecovery,gapAttempts:0},
  {...validRecovery,confirmedTargets:[proof(only[1],retryAt)],products:[product(proof(only[1],retryAt))],offers:[offer(proof(only[1],retryAt))]},
  {...validRecovery,confirmedTargets:[proof(only[0],retryAt,{sourceResponseHash:null})]},
  {...validRecovery,confirmedTargets:[proof(only[0],retryAt,{sourceResponseDate:new Date(retryAt-300001).toISOString()})]},
  {...validRecovery,confirmedTargets:[proof(only[0],retryAt,{sourceAgeSeconds:301})]},
  {...validRecovery,confirmedTargets:[proof(only[0],retryAt+1)]},
  {...validRecovery,confirmedTargets:[proof(only[0],NOW)]},
  gapBatch(only,{start:2,nextIndex:2,gaps:[gap(only[0],retryAt,3)],gapAttempts:1,requests:1,time:retryAt}),
  gapBatch(only,{start:2,nextIndex:2,gaps:[{...gap(only[0],retryAt,2),code:"anything"}],gapAttempts:1,requests:1,time:retryAt}),
  gapBatch(only,{start:2,nextIndex:2,gaps:[{...gap(only[0],retryAt,2),retryAfter:new Date(retryAt+1).toISOString()}],gapAttempts:1,requests:1,time:retryAt}),
  gapBatch(only,{start:2,nextIndex:2,gaps:[onlyGaps[0]],time:retryAt}),
  {...gapBatch(only,{start:2,nextIndex:2,gaps:[onlyGaps[0]],time:NOW}),deferredUntil:null}
 ];
 for(const result of badGapResults){const db=database(withGapState),beforeCursor=copy(db.state.cursor);let persists=0;await assert.rejects(()=>Refresh.refresh({pool:db,maxRequests:3,now:()=>retryAt},{discoverTargets:async()=>discovered(only),fetchProducts:async()=>result,persist:async()=>{persists++;return{accepted:0};}}),/aldi-catalog-progress-unconfirmed/);assert.equal(persists,0);assert.deepEqual(db.state.cursor,beforeCursor);assert.equal(db.state.processedCumulative,1);}
 for(const badState of[
  {...withGapState,processedCumulative:2},
  {...withGapState,cursor:newCursor(only,2,[onlyGaps[0],onlyGaps[0]])},
  {...withGapState,cursor:newCursor(only,2,[{...onlyGaps[0],sourceUrl:"https://evil.test/produkt/test-product-1000000.html"}])},
  {...withGapState,cursor:newCursor(only,2,[{...onlyGaps[0],sourceResponseDate:null}])},
  {...withGapState,cursor:newCursor(only,2,[{...onlyGaps[0],attempts:0}])},
  {...withGapState,cursor:newCursor(only,2,[{...onlyGaps[0],sourceAgeSeconds:-1}])}
 ]){const db=database(badState);let persists=0;await assert.rejects(()=>Refresh.refresh({pool:db,maxRequests:2,now:()=>retryAt},{discoverTargets:async()=>discovered(only),fetchProducts:async()=>validRecovery,persist:async()=>{persists++;return{accepted:0};}}),/aldi-catalog-progress-unconfirmed/);assert.equal(persists,0);assert.deepEqual(db.state.cursor,badState.cursor);}
 // Gap mutations also checkpoint only after successful quote persistence, including zero-price runs.
 for(const stage of["persist","checkpoint"]){const db=database(withGapState),initial=copy(db.state);if(stage==="checkpoint")db.failCheckpoint=true;await assert.rejects(()=>Refresh.refresh({pool:db,maxRequests:2,now:()=>retryAt},{discoverTargets:async()=>discovered(only),fetchProducts:async()=>validRecovery,persist:async()=>{if(stage==="persist")throw Error("gap-price-save-failed");return{accepted:1};}}),stage==="persist"?/gap-price-save-failed/:/checkpoint-database-down/);assert.deepEqual(db.state,initial);}
 const unsavedNewGap=database(),initialEmpty=copy(unsavedNewGap.state);await assert.rejects(()=>Refresh.refresh({pool:unsavedNewGap,maxRequests:3,now:()=>NOW},{discoverTargets:async()=>discovered(only),fetchProducts:async()=>gapBatch(only,{nextIndex:2,gaps:onlyGaps,gapAttempts:2}),persist:async()=>{throw Error("zero-price-save-failed");}}),/zero-price-save-failed/);assert.deepEqual(unsavedNewGap.state,initialEmpty);
 // A changed sitemap restarts at zero; prior-snapshot gaps cannot be silently carried or counted resolved.
 const gapDrift=database(withGapState),freshList=targets(3),reset=batch(freshList,0,1,{cursorReset:true});const restart=await Refresh.refresh({pool:gapDrift,maxRequests:2,now:()=>NOW},{discoverTargets:async()=>discovered(freshList),fetchProducts:async()=>reset,persist:async()=>({accepted:1})});assert.equal(restart.cursorReset,true);assert.equal(restart.catalog.nextIndex,1);assert.equal(restart.catalog.processedCumulative,1);assert.equal(restart.catalog.unresolvedCount,0);assert.equal(restart.catalog.publishedAssortmentComplete,false);
 // Exercise the actual native client and refresh contract together using local HTTP-shaped fixtures.
 const fixture=require("./fixtures/retailers/aldi-public-assortment.json"),nativeList=Client.stableTargets(fixture.sitemapUrls).targets,nativeDb=database(),nativeRequests=[];let nativeClock=NOW,nativeMode="gap";
 const nativeHtml=props=>'<script id="__NEXT_DATA__" type="application/json">'+JSON.stringify(props)+"</script>";
 const nativeFetch=async(url,options)=>{assert.equal(options.credentials,"omit");assert.equal(options.redirect,"error");nativeRequests.push(url);let raw;
  if(url===Client.SITEMAP_URL)raw='<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'+fixture.sitemapUrls.map(u=>"<url><loc>"+u+"</loc></url>").join("")+"</urlset>";
  else{const target=Client.targetForUrl(url),p={...copy(fixture.product),objectID:target.retailerSku,productSlug:url.split("/").at(-1).replace(/\.html$/,""),name:"UNIT TEST native product "+target.retailerSku};if(nativeMode==="no-price")p.currentPrice=null;raw=nativeMode==="gap"&&url===fixture.sourceUrl?nativeHtml(fixture.sourceUnavailablePage):nativeHtml({props:{pageProps:{apiData:JSON.stringify([["PRODUCT_DETAIL_GET",{req:{productIds:[target.retailerSku]},res:{products:[p]}}]])}}});}
  return{status:200,headers:{get:key=>key==="date"?new Date(nativeClock).toUTCString():key==="age"?"0":null},text:async()=>raw};};
 const nativeDeps={discoverTargets:options=>Client.discoverTargets({...options,fetchImpl:nativeFetch,sleep:async()=>{}}),fetchProducts:(input,options)=>Client.fetchProducts(input,{...options,fetchImpl:nativeFetch,sleep:async()=>{}}),persist:async(_,offers)=>{for(const quote of offers){assert.equal(require("../aldi-assortment-price-service").validateOffer(quote,{now:nativeClock}).ok,true);assert.equal(quote.gtin,null);assert.equal(quote.truthEligible,false);}return{received:offers.length,accepted:offers.length};}};
 const nativeFirst=await Refresh.refresh({pool:nativeDb,maxRequests:4,now:()=>nativeClock},nativeDeps);assert.equal(nativeFirst.requests,4);assert.equal(nativeFirst.processed,2);assert.equal(nativeFirst.accepted,2);assert.equal(nativeFirst.catalog.unresolvedCount,1);assert.equal(nativeFirst.catalog.scannedCount,3);assert.equal(nativeDb.state.cursor.unresolvedTargets[0].sourceAgeSeconds,0);assert.equal(nativeDb.state.lastError,null);
 const beforeWaitRequests=nativeRequests.length;nativeClock=NOW+60000;const nativeWait=await Refresh.refresh({pool:nativeDb,maxRequests:2,now:()=>nativeClock},nativeDeps);assert.equal(nativeWait.requests,1);assert.equal(nativeRequests.length,beforeWaitRequests+1);assert.equal(nativeRequests.at(-1),Client.SITEMAP_URL);assert.equal(nativeWait.catalog.publishedAssortmentComplete,false);
 nativeClock=NOW+Refresh.REFRESH_MS;const nativeRescan=await Refresh.refresh({pool:nativeDb,maxRequests:4,now:()=>nativeClock},nativeDeps);assert.equal(nativeRescan.runKind,"price-refresh");assert.equal(nativeRescan.requests,3);assert.equal(nativeRescan.processed,2);assert.equal(nativeRescan.regularRefresh.completedPasses,1);assert.equal(nativeRescan.catalog.publishedAssortmentComplete,false);assert.equal(nativeDb.state.cursor.unresolvedTargets[0].attempts,1);
 nativeClock=retryAt;nativeMode="recovered";const nativeRecovered=await Refresh.refresh({pool:nativeDb,maxRequests:2,now:()=>nativeClock},nativeDeps);assert.equal(nativeRecovered.runKind,"gap-retry");assert.equal(nativeRecovered.processed,1);assert.equal(nativeRecovered.gapAttempts,1);assert.equal(nativeRecovered.accepted,1);assert.equal(nativeRecovered.catalog.processedCumulative,nativeList.length);assert.equal(nativeRecovered.catalog.publishedAssortmentComplete,true);assert.equal(nativeDb.state.cursor,null);assert.equal(nativeRecovered.regularRefresh.enabled,false);
 // The rescan cursor counts original targets, including only previously attested gap skips.
 const windowList=targets(4),windowGaps=[gap(windowList[0]),gap(windowList[2])],windowDb=database(ended(windowList,windowGaps));let windowClock=NOW,windowFetches=0;
 const windowDeps={discoverTargets:async()=>discovered(windowList),fetchProducts:async(input,options)=>{windowFetches++;assert.equal(options.cursor,null);assert.equal(options.maxRequests,1);return gapBatch(input,{nextIndex:input.length,confirmed:input.map(t=>proof(t,windowClock)),time:windowClock});},persist:async(_,offers)=>({accepted:offers.length})};
 const skippedWindow=await Refresh.refresh({pool:windowDb,maxRequests:2,now:()=>windowClock},windowDeps);assert.equal(skippedWindow.runKind,"price-refresh");assert.equal(skippedWindow.requests,1);assert.equal(windowFetches,0);assert.equal(skippedWindow.processed,0);assert.equal(skippedWindow.regularRefresh.nextIndex,1);assert.equal(skippedWindow.regularRefresh.lastSku,windowList[0].retailerSku);assert.equal(skippedWindow.regularRefresh.inProgress,true);assert.equal(skippedWindow.nextAttemptAt,new Date(NOW+60000).toISOString());assert.deepEqual(windowDb.state.cursor.unresolvedTargets,windowGaps);assert.equal(await Refresh.resumeAt(windowDb,NOW),new Date(NOW+60000).toISOString());
 const restartedWindowDb=database(copy(windowDb.state));
 for(let i=1;i<4;i++){windowClock=NOW+i*60000;const result=await Refresh.refresh({pool:restartedWindowDb,maxRequests:2,now:()=>windowClock},windowDeps);assert.equal(result.runKind,"price-refresh");assert.equal(result.regularRefresh.nextIndex,i+1);assert.equal(result.requests,i===2?1:2);assert.equal(result.catalog.processedCumulative,2);assert.equal(result.catalog.unresolvedCount,2);assert.equal(result.catalog.publishedAssortmentComplete,false);assert.deepEqual(restartedWindowDb.state.cursor.unresolvedTargets,windowGaps);}
 assert.equal(windowFetches,2);assert.equal(restartedWindowDb.state.priceRefreshState.completedPasses,1);assert.equal(restartedWindowDb.state.priceRefreshState.lastCompletedAt,new Date(windowClock).toISOString());assert.equal(restartedWindowDb.state.priceRefreshState.passStartedAt,null);assert.equal(restartedWindowDb.state.completedCycles,0);assert.equal(await Refresh.resumeAt(restartedWindowDb,windowClock),new Date(windowClock+Refresh.REFRESH_MS).toISOString());assert.equal((await Refresh.status(restartedWindowDb)).regularRefresh.enabled,true);
 const loadedMs=NOW+123,pgDateState=ended(windowList,windowGaps,{updatedAt:new Date(loadedMs),priceRefreshState:regular(windowList,{nextIndex:1,lastSku:windowList[0].retailerSku,passStartedAt:new Date(NOW).toISOString(),nextPassAt:null})});assert.equal(await Refresh.resumeAt(database(pgDateState),loadedMs),new Date(loadedMs+Refresh.CONTINUATION_MS).toISOString());
 const legacyMs=database({...ended(windowList,windowGaps),priceRefreshState:null,updatedAt:new Date(loadedMs)});assert.equal(await Refresh.resumeAt(legacyMs,loadedMs),new Date(loadedMs+Refresh.REFRESH_MS).toISOString());assert.equal((await Refresh.status(legacyMs)).regularRefresh.nextPassAt,new Date(loadedMs+Refresh.REFRESH_MS).toISOString());assert.equal((await Refresh.status(legacyMs)).regularRefresh.completedPasses,0);
 const allSkippedDb=database(ended(only,onlyGaps));let allSkippedFetches=0;
 for(let i=0;i<2;i++){const result=await Refresh.refresh({pool:allSkippedDb,maxRequests:2,now:()=>NOW+i*60000},{discoverTargets:async()=>discovered(only),fetchProducts:async()=>{allSkippedFetches++;throw Error("Known gaps must not be queried by the rescan lane");},persist:async(_,quotes)=>{assert.equal(quotes.length,0);return{accepted:0};}});assert.equal(result.requests,1);assert.equal(result.catalog.unresolvedCount,2);assert.equal(result.catalog.processedCumulative,0);assert.equal(result.catalog.publishedAssortmentComplete,false);assert.equal(result.regularRefresh.nextIndex,i+1);}
 assert.equal(allSkippedFetches,0);assert.equal(allSkippedDb.state.priceRefreshState.completedPasses,1);assert.equal(allSkippedDb.state.completedCycles,0);assert.equal(allSkippedDb.state.lastCompletedAt,null);
 // A fresh hasError discovered during price renewal joins the existing main gaps without changing them.
 const mergeDb=database(ended(windowList,[windowGaps[0]])),newGap=gap(windowList[1]),oldMergedGap=copy(mergeDb.state.cursor.unresolvedTargets[0]);let mergeInput;
 const mergedRun=await Refresh.refresh({pool:mergeDb,maxRequests:4,now:()=>NOW},{discoverTargets:async()=>discovered(windowList),fetchProducts:async(input,options)=>{mergeInput=copy(input);assert.equal(options.cursor,null);return gapBatch(input,{nextIndex:2,confirmed:[proof(input[1])],gaps:[newGap],gapAttempts:1});},persist:async(_,offers)=>{assert.equal(offers.length,1);return{accepted:1};}});
 assert.deepEqual(mergeInput.map(t=>t.retailerSku),windowList.slice(1,3).map(t=>t.retailerSku));assert.equal(mergedRun.requests,3);assert.equal(mergedRun.processed,1);assert.equal(mergedRun.regularRefresh.nextIndex,3);assert.equal(mergedRun.regularRefresh.lastSku,windowList[2].retailerSku);assert.equal(mergedRun.catalog.processedCumulative,2);assert.equal(mergedRun.catalog.unresolvedCount,2);assert.deepEqual(mergeDb.state.cursor.unresolvedTargets.find(g=>g.retailerSku===windowList[0].retailerSku),oldMergedGap);assert.equal(mergeDb.state.cursor.snapshotHash,snapshot(windowList));assert.equal(mergedRun.regularRefresh.snapshotHash,snapshot(windowList));
 // Partial global errors save admitted quotes and exact original frontier, but do not skip the failed item.
 const partialRenewDb=database(ended(windowList,[windowGaps[0]])),renewOrder=[];
 const partialRenewDeps={discoverTargets:async()=>discovered(windowList),fetchProducts:async input=>gapBatch(input,{nextIndex:2,confirmed:[proof(input[0])],gaps:[gap(input[1])],gapAttempts:1,requests:3,partialError:{code:"aldi-source-http-429",status:429,retryingGap:false,requestStarted:true,...input[2]}}),persist:async(_,quotes)=>{renewOrder.push("quotes-saved");assert.equal(quotes.length,1);return{received:1,accepted:1};}};
 await assert.rejects(()=>Refresh.refresh({pool:partialRenewDb,maxRequests:5,now:()=>NOW},partialRenewDeps),err=>err.code==="aldi-source-http-429"&&err.checkpointSaved&&err.partialResult.runKind==="price-refresh"&&err.partialResult.regularRefresh.nextIndex===3&&err.partialResult.catalog.unresolvedCount===2);assert.deepEqual(renewOrder,["quotes-saved"]);assert.equal(partialRenewDb.state.priceRefreshState.nextIndex,3);assert.equal(partialRenewDb.state.priceRefreshState.passStartedAt,new Date(NOW).toISOString());assert.equal(partialRenewDb.state.retryAfter,new Date(retryAt).toISOString());assert.equal(await Refresh.resumeAt(partialRenewDb,NOW),new Date(retryAt).toISOString());
 const unchangedCooldown=copy(partialRenewDb.state);let forbiddenFetches=0;const cooldownSkipped=await Refresh.refresh({pool:partialRenewDb,maxRequests:2,now:()=>retryAt-1},{discoverTargets:async()=>{forbiddenFetches++;throw Error("Source cooldown must dominate regular renewal");}});assert.equal(cooldownSkipped.skipped,"source-cooldown");assert.equal(forbiddenFetches,0);assert.deepEqual(partialRenewDb.state,unchangedCooldown);
 const persistedRestart=database(copy(partialRenewDb.state));
 const dueGaps=persistedRestart.state.cursor.unresolvedTargets.map(g=>gap(Client.targetForUrl(g.sourceUrl),retryAt,g.attempts+1));
 const retryBetween=await Refresh.refresh({pool:persistedRestart,maxRequests:3,now:()=>retryAt},{discoverTargets:async()=>discovered(windowList),fetchProducts:async(input,options)=>{assert.equal(input.length,4);assert.equal(options.cursor.nextIndex,4);return gapBatch(windowList,{start:4,nextIndex:4,gaps:dueGaps,gapAttempts:2,requests:2,time:retryAt});},persist:async()=>({accepted:0})});assert.equal(retryBetween.runKind,"gap-retry");assert.equal(retryBetween.regularRefresh.nextIndex,3);assert.equal(retryBetween.regularRefresh.passStartedAt,new Date(NOW).toISOString());
 const completedRenewal=await Refresh.refresh({pool:persistedRestart,maxRequests:2,now:()=>retryAt},{discoverTargets:async()=>discovered(windowList),fetchProducts:async input=>{assert.deepEqual(input.map(t=>t.retailerSku),[windowList[3].retailerSku]);return gapBatch(input,{nextIndex:1,confirmed:[proof(input[0],retryAt)],time:retryAt});},persist:async()=>({accepted:1})});assert.equal(completedRenewal.runKind,"price-refresh");assert.equal(completedRenewal.regularRefresh.completedPasses,1);assert.equal(completedRenewal.regularRefresh.lastCompletedAt,new Date(retryAt).toISOString());assert.equal(completedRenewal.catalog.publishedAssortmentComplete,false);assert.equal(persistedRestart.state.completedCycles,0);
 // Renewal failures leave both durable frontiers unchanged; the additive column also supports legacy rows.
 for(const stage of["persist","checkpoint"]){const db=database(ended(windowList,[windowGaps[0]])),before=copy(db.state);if(stage==="checkpoint")db.failCheckpoint=true;await assert.rejects(()=>Refresh.refresh({pool:db,maxRequests:4,now:()=>NOW},{discoverTargets:async()=>discovered(windowList),fetchProducts:async input=>gapBatch(input,{nextIndex:input.length,confirmed:input.map(t=>proof(t))}),persist:async()=>{if(stage==="persist")throw Error("renewal-price-save-failed");return{accepted:2};}}),stage==="persist"?/renewal-price-save-failed/:/checkpoint-database-down/);assert.deepEqual(db.state,before);}
 assert(windowDb.calls.some(call=>/ALTER TABLE aldi_assortment_catalog_state ADD COLUMN IF NOT EXISTS price_refresh_state jsonb/.test(call.sql)));
 const renewalDrift=database(ended(windowList,[windowGaps[0]],{priceRefreshState:regular(windowList,{nextIndex:2,lastSku:windowList[1].retailerSku,passStartedAt:new Date(NOW).toISOString(),nextPassAt:null,lastCompletedAt:new Date(NOW-Refresh.REFRESH_MS).toISOString(),completedPasses:2,lastRunKind:"price-refresh"})})),changedList=targets(5);
 const resetRenewal=await Refresh.refresh({pool:renewalDrift,maxRequests:2,now:()=>NOW},{discoverTargets:async()=>discovered(changedList),fetchProducts:async(_,options)=>{assert.equal(options.cursor.snapshotHash,snapshot(windowList));return batch(changedList,0,1,{cursorReset:true});},persist:async()=>({accepted:1})});assert.equal(resetRenewal.runKind,"catalog");assert.equal(resetRenewal.cursorReset,true);assert.equal(resetRenewal.regularRefresh.snapshotHash,snapshot(changedList));assert.equal(resetRenewal.regularRefresh.nextIndex,0);assert.equal(resetRenewal.regularRefresh.completedPasses,0);assert.equal(resetRenewal.regularRefresh.lastCompletedAt,null);assert.equal(resetRenewal.catalog.nextIndex,1);assert.equal(resetRenewal.catalog.publishedAssortmentComplete,false);
 for(const invalidRegular of[{nextIndex:5},{nextIndex:2,lastSku:"wrong",passStartedAt:new Date(NOW).toISOString(),nextPassAt:null},{completedPasses:-1},{completedPasses:1,lastCompletedAt:null},{passStartedAt:new Date(NOW+1).toISOString(),nextPassAt:null},{lastRunKind:"complete"},{nextPassAt:new Date(NOW+Refresh.REFRESH_MS+1).toISOString()}]){const db=database(ended(windowList,[windowGaps[0]],{priceRefreshState:regular(windowList,invalidRegular)}));let fetches=0;await assert.rejects(()=>Refresh.refresh({pool:db,now:()=>NOW},{discoverTargets:async()=>discovered(windowList),fetchProducts:async()=>{fetches++;throw Error("Invalid renewal state must not request articles");}}),/aldi-catalog-progress-unconfirmed/);assert.equal(fetches,0);}
 // A permanently failing native page cannot age every other product out: actual 25h captures keep renewing.
 const permanentDb=database(),latestQuotes=new Map();nativeClock=NOW;nativeMode="gap";
 const permanentDeps={...nativeDeps,persist:async(_,quotes)=>{for(const quote of quotes){assert.equal(require("../aldi-assortment-price-service").validateOffer(quote,{now:nativeClock}).ok,true);latestQuotes.set(quote.retailerSku,copy(quote));}return{received:quotes.length,accepted:quotes.length};}};
 await Refresh.refresh({pool:permanentDb,maxRequests:4,now:()=>nativeClock},permanentDeps);const initialQuotes=copy([...latestQuotes.values()]);assert.equal(initialQuotes.length,2);
 let fairGapRuns=0;
 for(let quarter=1;quarter<=100;quarter++){
  nativeClock=NOW+quarter*Refresh.REFRESH_MS;const expectedPass=permanentDb.state.priceRefreshState.completedPasses+1;let runs=0;
  while(permanentDb.state.priceRefreshState.completedPasses<expectedPass){const beforeQuotes=copy([...latestQuotes.values()]),result=await Refresh.refresh({pool:permanentDb,maxRequests:4,now:()=>nativeClock},permanentDeps);runs++;assert(runs<=2,"Neither due gap retries nor ready price refreshes may starve");assert.equal(result.catalog.publishedAssortmentComplete,false);assert.equal(result.catalog.unresolvedCount,1);assert.equal(result.catalog.processedCumulative,2);assert(result.requests<=4);
   if(result.runKind==="gap-retry"){fairGapRuns++;assert.equal(result.accepted,0);assert.deepEqual([...latestQuotes.values()],beforeQuotes,"A gap-only checkpoint must not extend existing quotes");}
   else{assert.equal(result.runKind,"price-refresh");assert.equal(result.accepted,2);assert.equal(result.requests,3);for(const quote of latestQuotes.values()){assert.equal(quote.capturedAt,new Date(nativeClock).toISOString());assert.equal(quote.expiresAt,new Date(nativeClock+24*60*60*1000).toISOString());}}
  }
 }
 assert.equal(fairGapRuns,25);assert.equal(permanentDb.state.priceRefreshState.completedPasses,100);assert.equal(permanentDb.state.cursor.unresolvedTargets[0].attempts,26);assert.equal(permanentDb.state.completedCycles,0);assert(initialQuotes.every(quote=>Date.parse(quote.expiresAt)<nativeClock));assert([...latestQuotes.values()].every(quote=>Date.parse(quote.expiresAt)>nativeClock));
 const beforeNoPrice=copy([...latestQuotes.values()]);nativeClock+=Refresh.REFRESH_MS;nativeMode="no-price";const noPrice=await Refresh.refresh({pool:permanentDb,maxRequests:4,now:()=>nativeClock},permanentDeps);assert.equal(noPrice.runKind,"price-refresh");assert.equal(noPrice.accepted,0);assert.equal(noPrice.processed,2);assert.equal(noPrice.catalog.unresolvedCount,1);assert.deepEqual([...latestQuotes.values()],beforeNoPrice,"Identity-only publications must not refresh price expiry");
 for(const bad of[{targets:[]},{snapshotHash:"wrong"},{requests:2}]){let fetches=0;await assert.rejects(()=>Refresh.refresh({pool:database(),now:()=>NOW},{discoverTargets:async()=>({...discovered(list),...bad}),fetchProducts:async()=>{fetches++;return batch(list,0,1);}}),/discovery-unconfirmed/);assert.equal(fetches,0);}
 let release,startHeld;const started=new Promise(resolve=>{startHeld=resolve;}),held=Refresh.refresh({pool:database(),now:()=>NOW},{discoverTargets:async()=>{startHeld();await new Promise(resolve=>{release=resolve;});return discovered(targets(1));},fetchProducts:async()=>batch(targets(1),0,1),persist:async()=>({accepted:1})});await started;assert.equal((await Refresh.refresh({pool:database(),now:()=>NOW})).skipped,"already-running");release();await held;
 assert.equal(await Refresh.resumeAt(database({cursor:cursor(list,1),lastError:"failure",updatedAt:new Date(NOW).toISOString()}),NOW),null);
 console.log("aldi-assortment-refresh: 6,000+ target traversal, durable native gaps, independent bounded 25h price renewal, fair retry alternation, exact original/subset cursors, legacy migration, partial-error checkpoints, millisecond-safe PostgreSQL scheduling and unchanged source cooldowns/price TTLs OK");
}
main().catch(error=>{console.error(error);process.exitCode=1;});
