"use strict";
const assert=require("node:assert/strict"),Refresh=require("../aldi-assortment-refresh"),Client=require("../aldi-assortment-client");
const NOW=Date.parse("2026-10-01T12:00:00Z"),HASH="a".repeat(64),OTHER_HASH="b".repeat(64),copy=value=>structuredClone(value);
function database(initial={}){const state=copy(initial),calls=[];let failCheckpoint=false;return{state,calls,get failCheckpoint(){return failCheckpoint;},set failCheckpoint(value){failCheckpoint=value;},query:async(sql,params=[])=>{calls.push({sql,params:copy(params)});if(sql.startsWith("SELECT cursor"))return{rows:Object.keys(state).length?[copy(state)]:[]};if(sql.startsWith("INSERT INTO aldi_assortment_catalog_state")&&params.length===4){Object.assign(state,{lastError:params[1],retryAfter:params[2],updatedAt:params[3]});return{rowCount:1,rows:[]};}if(sql.startsWith("INSERT INTO aldi_assortment_catalog_state")){if(failCheckpoint)throw Error("checkpoint-database-down");Object.assign(state,{cursor:JSON.parse(params[1]),lastCompletedAt:params[2]?params[3]:state.lastCompletedAt||null,completedCycles:(state.completedCycles||0)+(params[2]?1:0),targetCount:params[4],nextIndex:params[5],processedCumulative:params[6],snapshotHash:params[7],lastError:params[8],retryAfter:params[9],updatedAt:params[3]});return{rowCount:1,rows:[]};}return{rows:[],rowCount:0};}};}
function targets(size=6){return Array.from({length:size},(_,i)=>({retailerSku:String(1000000+i),sourceUrl:"https://www.aldi-nord.de/produkt/test-product-"+(1000000+i)+".html"}));}
function discovered(list=targets(),snapshotHash=HASH){return{targets:list,snapshotHash,requests:1,bytes:100,discoveredAt:new Date(NOW).toISOString(),sourceId:Client.SOURCE};}
function cursor(list,index,snapshotHash=HASH){return{snapshotHash,nextIndex:index,lastSku:index?list[index-1].retailerSku:null};}
function batch(list,start,processed,patch={}){const nextIndex=start+processed,complete=nextIndex===list.length,offers=Array.from({length:processed},(_,i)=>({retailerSku:list[start+i].retailerSku,gtin:null,name:"UNIT TEST ALDI published product",price:1.29,scopeChannel:"assortment-publication",truthEligible:false}));return{offers,products:offers.map(o=>({retailerSku:o.retailerSku})),rejected:[],processed,requests:processed,bytes:200*processed,complete,partialError:null,cursor:complete?null:cursor(list,nextIndex),cursorReset:false,snapshotHash:HASH,targetCount:list.length,...patch};}
async function main(){
 const list=targets(),pool=database(),steps=[],seen=[];let start=0;
 const deps={discoverTargets:async options=>{assert.equal(options.maxRequests,1);assert.equal(options.now(),new Date(NOW).toISOString());steps.push("sitemap");return discovered(list);},fetchProducts:async(input,options)=>{assert.deepEqual(input,list);assert.equal(options.maxRequests,2);assert.equal(options.now(),new Date(NOW).toISOString());seen.push(copy(options.cursor));steps.push("product-pages");const result=batch(list,start,2);start+=2;return result;},persist:async(db,offers)=>{assert.equal(db,pool);steps.push("save-prices");return{received:offers.length,accepted:offers.length,rejected:0,upserted:offers.length};}};
 for(let run=1;run<=3;run++){const result=await Refresh.refresh({pool,maxRequests:3,now:()=>NOW},deps);assert.equal(result.requests,3);assert.equal(result.accepted,2);assert.equal(result.catalog.nextIndex,run*2);assert.equal(result.catalog.processedCumulative,run*2);assert.equal(result.catalog.publishedAssortmentComplete,run===3);assert.equal(result.catalog.physicalStoreAssortmentVerified,false);assert.equal(result.scope.channel,"assortment-publication");assert.equal(result.scope.location,"unknown");assert.equal(result.independentOfUserReceipts,true);assert.equal(result.nextAttemptAt,run===3?null:new Date(NOW+60000).toISOString());const current=await Refresh.status(pool);assert.equal(current.publishedAssortmentComplete,run===3);assert.equal(current.completedCycles||0,run===3?1:0);assert.equal(current.normalPriceClassificationVerified,false);assert.equal(current.physicalStoreAssortmentVerified,false);}
 assert.deepEqual(seen,[null,cursor(list,2),cursor(list,4)]);assert.deepEqual(steps,Array(3).fill(["sitemap","product-pages","save-prices"]).flat());assert.equal(pool.state.cursor,null);assert.equal(pool.state.lastCompletedAt,new Date(NOW).toISOString());assert(!pool.calls.some(call=>/INSERT INTO (?:products|stores|price_observations|receipts|receipt_submissions)\b/.test(call.sql)));
 assert.equal(await Refresh.resumeAt(pool,NOW),null);
 for(const[value,expected]of[[undefined,16],[999,32],[1,2],[0,16],[NaN,16]]){let actual;const result=await Refresh.refresh({pool:database(),maxRequests:value,now:()=>NOW},{discoverTargets:async()=>discovered(targets(1)),fetchProducts:async(_,options)=>{actual=options.maxRequests;return batch(targets(1),0,1);},persist:async()=>({accepted:1})});assert.equal(actual,expected-1);assert.equal(result.requests,2);}
 // A catalog larger than 6,000 articles is traversed in bounded batches, including pages without a price.
 const large=targets(6001),largeDb=database();let visited=0,largestBudget=0;
 while(visited<large.length){const result=await Refresh.refresh({pool:largeDb,maxRequests:999,now:()=>NOW},{discoverTargets:async()=>discovered(large),fetchProducts:async(_,options)=>{largestBudget=Math.max(largestBudget,options.maxRequests);const count=Math.min(options.maxRequests,large.length-visited),result=batch(large,visited,count,{offers:[],products:[],rejected:Array(count).fill({reasons:["aldi-current-pack-price-required"]})});visited+=count;return result;},persist:async(_,offers)=>{assert.equal(offers.length,0);return{received:0,accepted:0,rejected:0};}});assert(result.requests<=32);assert.equal(result.accepted,0);}
 assert.equal(visited,6001);assert.equal(largestBudget,31);assert.equal((await Refresh.status(largeDb)).publishedAssortmentComplete,true);assert.equal(largeDb.state.processedCumulative,6001);
 const partialDb=database({cursor:cursor(list,2),nextIndex:2,processedCumulative:2,targetCount:6}),before=copy(partialDb.state);let saved=0;
 await assert.rejects(()=>Refresh.refresh({pool:partialDb,now:()=>NOW},{discoverTargets:async()=>discovered(list),fetchProducts:async()=>batch(list,2,1),persist:async()=>{throw Error("quote-database-down");}}),/quote-database-down/);assert.deepEqual(partialDb.state,before,"Failed price persistence must not skip a source page");
 partialDb.failCheckpoint=true;await assert.rejects(()=>Refresh.refresh({pool:partialDb,now:()=>NOW},{discoverTargets:async()=>discovered(list),fetchProducts:async()=>batch(list,2,1),persist:async(_,offers)=>{saved+=offers.length;return{accepted:offers.length};}}),/checkpoint-database-down/);assert.equal(saved,1);assert.deepEqual(partialDb.state,before);partialDb.failCheckpoint=false;
 let retried;await Refresh.refresh({pool:partialDb,now:()=>NOW},{discoverTargets:async()=>discovered(list),fetchProducts:async(_,options)=>{retried=options.cursor;return batch(list,2,1);},persist:async()=>({received:1,accepted:0,rejected:1})});assert.deepEqual(retried,before.cursor);assert.equal(partialDb.state.nextIndex,3,"A scanned native page advances even when price admission rejects it");
 for(const[stage,code,retryAfterMs,delay]of[["discovery","aldi-source-http-403",undefined,3600000],["products","aldi-source-http-429",7200000,7200000]]){const blocked=database({cursor:cursor(list,2),nextIndex:2,processedCumulative:2}),beforeCursor=copy(blocked.state.cursor);let calls=0,persists=0;const error=Object.assign(Error(code),{code,retryAfterMs}),blockedDeps={discoverTargets:async()=>{calls++;if(stage==="discovery")throw error;return discovered(list);},fetchProducts:async()=>{calls++;throw error;},persist:async()=>{persists++;return{accepted:0};}};await assert.rejects(()=>Refresh.refresh({pool:blocked,now:()=>NOW},blockedDeps),err=>err.code===code&&err.nextAttemptAt===new Date(NOW+delay).toISOString());assert.deepEqual(blocked.state.cursor,beforeCursor);assert.equal(persists,0);const priorCalls=calls,skipped=await Refresh.refresh({pool:blocked,now:()=>NOW+delay-1},blockedDeps);assert.equal(skipped.skipped,"source-cooldown");assert.equal(calls,priorCalls);assert.equal(await Refresh.resumeAt(blocked,NOW),new Date(NOW+delay).toISOString());assert.equal(await Refresh.resumeAt(blocked,NOW+delay+1),new Date(NOW+delay+1).toISOString());}
 // Prices preceding a denial are retained, while the failed source run remains a failure.
 for(const[retryAfterMs,delay]of[[undefined,3600000],[1000,Refresh.REFRESH_MS],[7200000,7200000]]){const denied=database({cursor:cursor(list,2),nextIndex:2,processedCumulative:2,completedCycles:1,lastCompletedAt:new Date(NOW-86400000).toISOString()}),order=[];const partial=batch(list,2,1,{requests:2,partialError:{code:"aldi-source-http-429",status:429,retryAfterMs}});await assert.rejects(()=>Refresh.refresh({pool:denied,now:()=>NOW},{discoverTargets:async()=>discovered(list),fetchProducts:async()=>partial,persist:async(_,offers)=>{order.push("price-saved");assert.equal(offers.length,1);return{received:1,accepted:1,rejected:0};}}),err=>{assert.equal(err.code,"aldi-source-http-429");assert.equal(err.nextAttemptAt,new Date(NOW+delay).toISOString());assert.equal(err.accepted,1);assert.equal(err.received,1);assert.equal(err.checkpointSaved,true);assert.equal(err.partialResult.catalog.nextIndex,3);assert.equal(denied.state.nextIndex,3,"Error must be thrown only after saved-price checkpoint");return true;});assert.deepEqual(order,["price-saved"]);assert.equal(denied.state.completedCycles,1);assert.equal(denied.state.lastCompletedAt,new Date(NOW-86400000).toISOString());assert.equal(denied.state.lastError,"aldi-source-http-429");assert.equal((await Refresh.status(denied)).publishedAssortmentComplete,false);}
 const drift=database({cursor:cursor(list,4),nextIndex:4,processedCumulative:4,targetCount:6,snapshotHash:HASH,completedCycles:2,lastCompletedAt:new Date(NOW-100000).toISOString()}),newList=targets(7);let driftCursor;
 const changed=batch(newList,0,1,{snapshotHash:OTHER_HASH,cursor:cursor(newList,1,OTHER_HASH),cursorReset:true});const driftResult=await Refresh.refresh({pool:drift,now:()=>NOW},{discoverTargets:async()=>discovered(newList,OTHER_HASH),fetchProducts:async(_,options)=>{driftCursor=options.cursor;return changed;},persist:async()=>({accepted:1})});assert.deepEqual(driftCursor,cursor(list,4));assert.equal(driftResult.cursorReset,true);assert.equal(drift.state.nextIndex,1);assert.equal(drift.state.processedCumulative,1);assert.equal(drift.state.completedCycles,2);assert.equal((await Refresh.status(drift)).publishedAssortmentComplete,false);assert.equal(await Refresh.resumeAt(drift,NOW),new Date(NOW+60000).toISOString());
 const invalid=[{offers:null},{products:null},{rejected:null},{targetCount:7},{snapshotHash:OTHER_HASH},{processed:-1},{processed:0,requests:1,cursor:cursor(list,2)},{processed:2,requests:1},{requests:99},{bytes:-1},{complete:true,cursor:null},{cursor:null},{cursor:cursor(list,4)},{cursor:{...cursor(list,3),lastSku:"wrong"}},{cursorReset:true}];
 for(const patch of invalid){const db=database({cursor:cursor(list,2),nextIndex:2,processedCumulative:2,targetCount:6});let persists=0;await assert.rejects(()=>Refresh.refresh({pool:db,maxRequests:3,now:()=>NOW},{discoverTargets:async()=>discovered(list),fetchProducts:async()=>batch(list,2,1,patch),persist:async()=>{persists++;return{accepted:0};}}),/aldi-catalog-(?:progress|snapshot)/);assert.equal(persists,0);assert.deepEqual(db.state.cursor,cursor(list,2));assert.equal(db.state.nextIndex,2);}
 const driftWithoutReset=database({cursor:cursor(list,2),nextIndex:2,processedCumulative:2});await assert.rejects(()=>Refresh.refresh({pool:driftWithoutReset,now:()=>NOW},{discoverTargets:async()=>discovered(newList,OTHER_HASH),fetchProducts:async()=>({...changed,cursorReset:false}),persist:async()=>{throw Error("Must not persist unconfirmed drift");}}),/snapshot-reset-unconfirmed/);
 for(const bad of[{targets:[]},{snapshotHash:"wrong"},{requests:2}]){let fetches=0;await assert.rejects(()=>Refresh.refresh({pool:database(),now:()=>NOW},{discoverTargets:async()=>({...discovered(list),...bad}),fetchProducts:async()=>{fetches++;return batch(list,0,1);}}),/discovery-unconfirmed/);assert.equal(fetches,0);}
 let release,startHeld;const started=new Promise(resolve=>{startHeld=resolve;}),held=Refresh.refresh({pool:database(),now:()=>NOW},{discoverTargets:async()=>{startHeld();await new Promise(resolve=>{release=resolve;});return discovered(targets(1));},fetchProducts:async()=>batch(targets(1),0,1),persist:async()=>({accepted:1})});await started;assert.equal((await Refresh.refresh({pool:database(),now:()=>NOW})).skipped,"already-running");release();await held;
 assert.equal(await Refresh.resumeAt(database({cursor:cursor(list,1),lastError:"failure",updatedAt:new Date(NOW).toISOString()}),NOW),null);
 console.log("aldi-assortment-refresh: bounded full sitemap continuation past 6,000 targets, exact request budgets, safe persistence/checkpoints, 403/429 cooldown, saved partial-error prices, zero-index snapshot restart and unverified physical/normal-price scopes OK");
}
main().catch(error=>{console.error(error);process.exitCode=1;});
