"use strict";
// New, explicitly synthetic HTTP-original fixtures exercise the actual retained
// diagnostic. No merchant capture is retimed or admitted as a product or price.
const assert=require("node:assert/strict"),crypto=require("node:crypto"),Store=require("../aldi-category-rejected-capture-store"),Parser=require("../aldi-assortment-category-client"),Navigation=require("../aldi-category-navigation-parser");
const now=Date.parse("2026-10-03T07:30:00.123Z"),url="https://www.aldi-nord.de/sortiment/milchprodukte.html",categoryPath="/sortiment/milchprodukte",privateValue="PRIVATE_CONTEXT_DIAGNOSTIC_TOKEN";
function row(id="joghurt-quark"){return{categoryKey:id,title:"UNIT TEST Joghurt",hideInCategory:false,marketingCategory:false,children:[],reference:{type:"pages",path:categoryPath+"/"+id}};}
function native(){return{page:"/product-overview/[...categories]",query:{categories:["milchprodukte"]},syntheticOriginal:true,props:{pageProps:{locale:"de",algoliaState:null,page:{"@name":"milchprodukte","@path":"/germany"+categoryPath,categoryKey:"milchprodukte","mgnl:template":Navigation.TEMPLATE,componentList:["banner"]},apiData:JSON.stringify([[Navigation.CHILDREN,{req:{categoryPath,locale:"de"},res:[row()]}]])}}};}
function capture(n=native()){const body='<html><head><link rel="canonical" href="'+url+'"></head><body><script id="__NEXT_DATA__" type="application/json">'+JSON.stringify(n)+'</script></body></html>',meta={sourceResponseUrl:url,sourceResponseHash:crypto.createHash("sha256").update(body).digest("hex"),sourceResponseDate:new Date(now-1000).toISOString(),sourceAgeSeconds:0,capturedAt:new Date(now-1000).toISOString(),scopeCountry:"DE"};let failureCode;try{Parser.parsePage(body,meta,{now});}catch(e){failureCode=e.code;}assert.equal(failureCode,"aldi-category-native-index-conflict");return{status:200,failureCode,original:{body,meta}};}
function summary(change=()=>{},at=now){const n=native();change(n.props.pageProps);return Store.diagnosticSummary(capture(n),{now:at});}
function entries(p,mutate){const a=JSON.parse(p.apiData);mutate(a);p.apiData=JSON.stringify(a);}
let groups=0;function test(name,fn){try{fn();groups++;}catch(e){console.error("Failed: "+name);throw e;}}
test("actual retained summary reads serialized native context without changing product failure",()=>{const s=summary(),c=s.nativeContext,e=c.knownEntries[0];assert.equal(s.failureCode,"aldi-category-native-index-conflict");assert.equal(c.apiDataKind,"string");assert.equal(c.parseState,"parsed");assert.equal(c.nativeEntryCount,1);assert.equal(e.name,Navigation.CHILDREN);assert.deepEqual(e.request,{categoryPath,locale:"de"});assert.equal(e.nativeChildCount,1);assert.deepEqual(e.children[0].reference,{type:"pages",path:categoryPath+"/joghurt-quark"});assert.equal(e.children[0].childParentBindingVerified,false);assert.equal(c.admitted,false);assert.equal(c.sourceRevalidationRequired,true);for(const key of["current","fresh","admitted","truthEligible","currentPriceVerified","physicalStorePriceVerified","canonicalIdentityVerified","assortmentComplete"])assert.equal(s[key],false);assert.equal(s.articleRowsCreated,0);assert.equal(s.priceRowsCreated,0);});
test("original and diagnostic capture hash never change while summarizing context",()=>{const v=capture(),before=JSON.stringify(v),s=Store.diagnosticSummary(v,{now});assert.equal(JSON.stringify(v),before);assert.equal(s.sourceResponseHash,v.original.meta.sourceResponseHash);assert.equal(s.capturedAt,v.original.meta.capturedAt);assert.equal(s.sourceResponseDate,v.original.meta.sourceResponseDate);assert.equal(s.sourceAgeSeconds,0);});
test("a dated original is still diagnostic after its capture freshness expires",()=>{const s=summary(()=>{},now+30*86400000);assert.equal(s.nativeContext.parseState,"parsed");assert.equal(s.current,false);assert.equal(s.fresh,false);assert.equal(s.expiresAt,null);assert.equal(s.nativeContext.admitted,false);});
test("missing context is explicit and confers no empty product or navigation success",()=>{const s=summary(p=>delete p.apiData);assert.equal(s.nativeContext.apiDataKind,"missing");assert.equal(s.nativeContext.parseState,"aldi-navigation-context-required");assert.deepEqual(s.nativeContext.knownEntries,[]);assert.equal(s.articleRowsCreated,0);});
test("nonserialized context and malformed JSON are safely diagnosed",()=>{for(const value of[[[Navigation.CHILDREN,{}]],{secret:privateValue},"{bad"]){const s=summary(p=>p.apiData=value);assert.notEqual(s.nativeContext.parseState,"parsed");assert.equal(s.nativeContext.knownEntries.length,0);assert(!JSON.stringify(s.nativeContext).includes(privateValue));} });
test("duplicate native keys are held without choosing one set of children",()=>{const s=summary(p=>entries(p,a=>a.push(structuredClone(a[0])))),e=s.nativeContext.knownEntries[0];assert.equal(e.name,Navigation.CHILDREN);assert.equal(e.held,true);assert.equal(e.duplicateCount,2);assert.equal(e.children,undefined);});
test("unknown APIs and raw headers or private payload fields are never echoed",()=>{const s=summary(p=>entries(p,a=>{a.push(["UNKNOWN_PRIVATE_API",{secret:privateValue}]);a[0][1].headers={authorization:privateValue};a[0][1].res[0].token=privateValue;}));assert(!JSON.stringify(s).includes(privateValue));assert.equal(s.nativeContext.knownEntries.length,1);assert.equal(s.nativeContext.knownEntries[0].children.length,1);});
test("sensitive request path is omitted and marked unsafe",()=>{const s=summary(p=>entries(p,a=>a[0][1].req.categoryPath=categoryPath+"/access_token/"+privateValue)),c=s.nativeContext;assert.equal(c.knownEntries[0].request,null);assert.equal(c.truncation.unsafeValues,true);assert(!JSON.stringify(s).includes(privateValue));});
test("foreign or expanded references remain excluded",()=>{for(const ref of[{type:"pages",path:"https://foreign.example/"+privateValue},{type:"pages",path:categoryPath+"/joghurt-quark",publicUrl:"https://foreign.example/"+privateValue}]){const s=summary(p=>entries(p,a=>a[0][1].res[0].reference=ref));assert.equal(s.nativeContext.knownEntries[0].children.length,0);assert.equal(s.nativeContext.truncation.unsafeValues,true);assert(!JSON.stringify(s).includes(privateValue));}});
test("unsafe child display text stays private",()=>{const s=summary(p=>entries(p,a=>a[0][1].res[0].title="access_token="+privateValue));assert.equal(s.nativeContext.knownEntries[0].children.length,0);assert.equal(s.nativeContext.truncation.unsafeValues,true);assert(!JSON.stringify(s).includes(privateValue));});
test("native child array caps remain explicit and do not establish discovery completeness",()=>{const s=summary(p=>entries(p,a=>a[0][1].res=Array.from({length:Navigation.MAX_CHILDREN+1},(_,i)=>row("synthetic-child-"+i)))),c=s.nativeContext;assert.equal(c.knownEntries[0].nativeChildCount,Navigation.MAX_CHILDREN+1);assert.equal(c.knownEntries[0].children.length,Navigation.MAX_CHILDREN);assert.equal(c.truncation.children,true);assert.equal(c.admitted,false);assert.equal(s.assortmentComplete,false);});
test("retained diagnostic still rejects an altered body hash",()=>{const v=capture();v.original.meta.sourceResponseHash="f".repeat(64);assert.throws(()=>Store.diagnosticSummary(v,{now}),/aldi-rejected-original-hash-conflict/);});
console.log("aldi-retained-context-diagnostics: "+groups+" actual retained summary/context/capture/hash/privacy/closed-key/bounds groups passed; synthetic originals only, no HTTP or SQL");
