"use strict";
const assert=require("node:assert/strict"),fs=require("node:fs"),path=require("node:path"),crypto=require("node:crypto"),Service=require("../aldi-assortment-article-service"),Client=require("../aldi-assortment-client"),fixture=require("./fixtures/retailers/aldi-public-assortment.json");
const now=Date.parse("2026-10-03T00:30:00.000Z"),at=new Date(now-1000).toISOString(),clone=structuredClone;
// Synthetic native originals below test identity admission, never a live import.
const meta={...Client.targetForUrl(fixture.sourceUrl),capturedAt:at,sourceResponseDate:at,sourceAgeSeconds:0,sourceResponseHash:"a".repeat(64)};
function product(patch={}){const raw=clone(fixture.product);raw.currentPrice=null;const parsed=Client.parseProduct({...raw,...patch},meta);assert.equal(parsed.ok,true);assert.equal(parsed.offer,null);return parsed.product;}
let checks=0;function check(fn){fn();checks++;}
async function main(){
 const native=product();check(()=>{const result=Service.validateArticle(native,{now});assert(result.ok,JSON.stringify(result));assert.equal(result.article.gtin,null);assert.equal(result.article.storeId,null);assert.equal(result.article.price,undefined);assert.equal(result.article.packAmount,1000);assert.equal(result.article.packUnit,"ml");assert.equal(result.article.observedAt,at);});
 check(()=>{const old={...native,observedAt:new Date(now-30*86400000).toISOString(),sourceResponseDate:new Date(now-30*86400000).toISOString()};assert(Service.validateArticle(old,{now}).ok,"Identity capture may outlive price24h without becoming currently available");});
 check(()=>{const absent=product({isAvailable:false});assert.equal(absent.publicationAvailable,false);assert(Service.validateArticle(absent,{now}).ok,"Historical native publication flag is not asserted current availability");});
 for(const [patch,reason]of[[{sourceId:"Open Food Facts"},"native-article-source-required"],[{merchant:"REWE"},"native-article-source-required"],[{purpose:"price"},"native-article-source-required"],[{identityScope:"gtin"},"native-article-source-required"],[{gtin:"3017620422003"},"unverified-article-identity-or-market"],[{storeId:"imaginary"},"unverified-article-identity-or-market"],[{shop:{city:"Berlin"}},"unverified-article-identity-or-market"],[{scopeCountry:"AT"},"native-article-scope-required"],[{scopeChannel:"physical-store"},"native-article-scope-required"],[{locationScope:"Berlin"},"native-article-scope-required"],[{truthEligible:true},"native-article-scope-required"],[{current:true},"article-price-or-stock-authority-forbidden"],[{availability:"available"},"article-price-or-stock-authority-forbidden"],[{price:1.29},"article-price-or-stock-authority-forbidden"],[{deposit:.25},"article-price-or-stock-authority-forbidden"],[{expiresAt:new Date(now+86400000).toISOString()},"article-price-or-stock-authority-forbidden"],[{sourceUrl:native.sourceUrl+"?fresh=1"},"native-article-url-required"],[{retailerSku:"0001"},"native-article-sku-required"],[{sourceUrl:native.sourceUrl.replace(native.retailerSku,"1939")},"native-article-sku-required"],[{pack:"ca.1Liter"},"native-article-exact-sales-pack-required"],[{packAmount:2},"native-article-pack-metadata-conflict"],[{packCount:2},"native-article-pack-metadata-conflict"],[{packUnit:"kg"},"native-article-pack-metadata-conflict"],[{variant:"Verschiedene Sorten"},"native-article-variant-unresolved"],[{name:"<b>Milch</b>"},"native-article-label-required"],[{sourceResponseHash:"A".repeat(64)},"native-article-original-hash-and-age-required"],[{sourceAgeSeconds:301},"native-article-original-hash-and-age-required"],[{sourceAgeSeconds:-1},"native-article-original-hash-and-age-required"],[{observedAt:new Date(now+1).toISOString()},"native-article-observation-time-required"],[{observedAt:"2026-10-03"},"native-article-observation-time-required"],[{sourceResponseDate:new Date(now-400000).toISOString()},"native-article-original-response-freshness-required"],[{publicationAvailable:"true"},"native-article-publication-flag-required"]])check(()=>{const r=Service.validateArticle({...native,...patch},{now});assert.equal(r.ok,false,JSON.stringify(patch));assert(r.reasons.includes(reason),JSON.stringify(r));});
 check(()=>{const missing=clone(native);delete missing.sourceAgeSeconds;assert(!Service.validateArticle(missing,{now}).ok);});
 check(()=>{const raw=product({salesUnit:"9x0,5-Liter-Flasche"}),r=Service.validateArticle(raw,{now});assert(r.ok);assert.equal(r.article.packCount,9);assert.equal(r.article.packAmount,500);assert.equal(r.article.packUnit,"ml");assert.equal(r.article.pack,"9x0,5-Liter-Flasche");});
 for(const name of["classic-1026202","original-taste-4039"])check(()=>{const base=path.join(__dirname,"fixtures/retailers/aldi-deposit",name),body=fs.readFileSync(base+".html","utf8"),response=JSON.parse(fs.readFileSync(base+"-response.json","utf8"));assert.equal(crypto.createHash("sha256").update(body).digest("hex"),response.sourceResponseHash);const parsed=Client.parseProduct(Client.extractProducts(body).products[0],{...response,raw:body,sourceResponseDate:response.headers.date,sourceAgeSeconds:null});assert(parsed.ok);assert(Service.validateArticle(parsed.product,{now:Date.parse(response.capturedAt)}).ok);assert.equal(parsed.product.observedAt,new Date(response.capturedAt).toISOString());});
 check(()=>{const q=Service.querySpec({search:"Milk%_",pack:"9 x 500 ml",limit:200,offset:20,now});assert(q.sql.includes("held=false"));assert(!q.sql.includes("interval '24 hours'"));assert(q.params.includes("%Milk\\%\\_%"));assert(q.params.includes(9));assert(q.params.includes(500));assert(!q.params.includes(4500));});
 for(const options of[{limit:true},{limit:201},{limit:0},{offset:-1},{offset:10001},{search:""},{merchant:""},{gtin:"3017620422003"},{scopeChannel:"store"},{pack:"ca.500g"},{retailerSku:"01"},{now:"2026-10-03"}])check(()=>assert.throws(()=>Service.querySpec(options),/invalid-/));
 check(()=>assert(Service.querySpec({scopeChannel:"pickup",now}).sql.includes("false")));
 await assert.rejects(()=>Service.persist({query:async()=>({rows:[]})},[native],{now}),/transaction-client-required/);checks++;
 await assert.rejects(()=>Service.persist({release(){},query:async()=>({rows:[{transactionOpen:false}]})},[native],{now}),/open-writing-transaction-required/);checks++;
 let schemaCalls=0;const pool={connect(){},query:async()=>{schemaCalls++;return{rows:[]};}};await Service.ensure(pool);await Service.ensure(pool);assert.equal(schemaCalls,1);checks++;
 let clientCalls=0;const tx={release(){},query:async()=>{clientCalls++;return{rows:[]};}};await Service.ensure(tx);await Service.ensure(tx);assert.equal(clientCalls,2,"Rollback-prone clients must never cache schema completion");checks++;
 let failOnce=true,failedCalls=0;const retryPool={connect(){},query:async()=>{failedCalls++;if(failOnce){failOnce=false;throw Error("synthetic-ddl-failure");}return{rows:[]};}};await assert.rejects(()=>Service.ensure(retryPool),/synthetic-ddl-failure/);await Service.ensure(retryPool);assert.equal(failedCalls,2);checks++;
 console.log(`aldi-assortment-article-service: ${checks} groups passed; genuine native identity independent of price, exact sales pack, no GTIN/stock/city upgrades, dated evidence, bounded reads and transaction/schema guards`);
}
main().catch(e=>{console.error(e);process.exitCode=1;});
