"use strict";
const assert = require("node:assert/strict"), Store = require("../aldi-category-rejected-capture-store"), Fixture = require("./fixtures/aldi-category-capture");
const now = Date.parse("2026-10-03T06:00:00.500Z"), at = now - 10000, clone = structuredClone;
// NEW synthetic originals. No archive is retimed or admitted as a retailer capture.
function capture(time = at, change = () => {}, code = "aldi-category-native-index-conflict") {
  let body = Fixture.html(); const m = /(<script\b[^>]*id="__NEXT_DATA__"[^>]*>)([\s\S]*?)(<\/script>)/.exec(body), native = JSON.parse(m[2]);
  delete native.props.pageProps.algoliaState; native.syntheticDiagnosticFixture = true; change(native);
  body = body.replace(m[0], m[1] + JSON.stringify(native) + m[3]);
  return { status: 200, failureCode: code, original: Fixture.original(body, time), bytes: Buffer.byteLength(body) };
}
function rehash(c) { c.original.meta.sourceResponseHash = Store.hash(c.original.body); c.bytes = Buffer.byteLength(c.original.body); return c; }
function memory() {
  let state = { originals: new Map(), history: new Map(), latest: new Map() }, stage = null, assigned = false, failWrite = null, boundOverride = null;
  const events = [], data = () => stage || state, key = (source, url) => JSON.stringify([source,url]);
  const joined = (h, l) => h ? { ...clone(h), ...clone(data().originals.get(h.source_response_hash)), ...(l ? clone(l) : {}) } : undefined;
  const tx = Object.assign(Object.create({ connect() { assert.fail("Never reconnect an inherited PoolClient"); } }), { release() { events.push("release"); }, async query(sql, p = []) {
    events.push(sql);
    if (sql === "BEGIN") { stage = clone(state); assigned = false; return { rows: [] }; }
    if (sql === "SELECT txid_current()") { assigned = !!stage; return { rows: [] }; }
    if (sql === "COMMIT") { state = stage; stage = null; assigned = false; return { rows: [] }; }
    if (sql === "ROLLBACK") { stage = null; assigned = false; return { rows: [] }; }
    if (sql.includes("txid_current_if_assigned")) return { rows: [{ assigned }] };
    if (sql.startsWith("SELECT pg_advisory")) return { rows: [] };
    if (sql.startsWith("SELECT capture_hash,captured_at")) return { rows: [...data().history.values()].filter(h => h.source_id === p[0] && h.source_response_url === p[1] && h.source_response_hash === p[2] && h.source_response_date === p[3] && h.source_age_seconds === p[4]) };
    if (sql.startsWith("SELECT l.held")) { const ls = [...data().latest.values()].filter(l => l.source_id === p[0] && (p[1] === undefined || l.source_response_url === p[1])); return { rows: ls.map(l => { const r=joined(data().history.get(l.capture_hash),l);if(sql.includes("b.body_bytes")&&!sql.includes("b.body,b.body_bytes"))delete r.body;return r; }) }; }
    if (sql.startsWith("SELECT c.*,b.body")) { const r=joined(data().history.get(p[0]));if(r&&sql.includes("b.body_bytes")&&!sql.includes("b.body,b.body_bytes"))delete r.body;return { rows:r?[r]:[] }; }
    if (sql.startsWith("SELECT body,body_bytes")) return { rows: data().originals.has(p[0]) ? [clone(data().originals.get(p[0]))] : [] };
    if (sql.startsWith("SELECT (SELECT count")) return { rows: [{ captures: data().history.size, bytes: [...data().originals.values()].reduce((s,v) => s + v.body_bytes, 0), urls: data().latest.size, ...boundOverride }] };
    if (failWrite && sql.startsWith(failWrite)) { failWrite = null; throw Error("synthetic rejected-store SQL failure"); }
    if (sql.startsWith("INSERT INTO " + Store.ORIGINAL_TABLE)) { if (!data().originals.has(p[0])) data().originals.set(p[0], { source_response_hash:p[0],body:p[1],body_bytes:p[2] }); return { rows: [], rowCount: 1 }; }
    if (sql.startsWith("INSERT INTO " + Store.CAPTURE_TABLE)) { if (!data().history.has(p[0])) data().history.set(p[0], { capture_hash:p[0],source_id:p[1],source_response_url:p[2],http_status:p[3],failure_code:p[4],source_response_hash:p[5],captured_at:p[6],source_response_date:p[7],original_response_date:p[8],source_age_seconds:p[9] }); return { rows: [], rowCount: 1 }; }
    if (sql.startsWith("INSERT INTO " + Store.TABLE)) { data().latest.set(key(p[0],p[1]), { source_id:p[0],source_response_url:p[1],capture_hash:p[2],held:false,conflict_capture_hash:null }); return { rows: [], rowCount: 1 }; }
    if (sql.startsWith("UPDATE " + Store.TABLE)) { const l = data().latest.get(key(p[0],p[1])); if (sql.includes("SET held=true")) { l.held = true; l.conflict_capture_hash = p[2]; } else { l.capture_hash = p[2]; l.held = false; l.conflict_capture_hash = null; } return { rows: [], rowCount: 1 }; }
    throw Error("Unexpected SQL: " + sql);
  } });
  const pool = { connect: async () => tx, query: async (sql,p) => sql.includes("CREATE TABLE") ? { rows: [] } : tx.query(sql,p) };
  return { tx, pool, events, snapshot: () => JSON.stringify([...state.originals,...state.history,...state.latest]), set fail(v) { failWrite = v; }, set bounds(v) { boundOverride = v; }, data,
    async open() { await tx.query("BEGIN"); await tx.query("SELECT txid_current()"); }, async save(c) { await this.open(); try { const r = await Store.persist(tx,c,{now}); await tx.query("COMMIT"); return r; } catch (e) { await tx.query("ROLLBACK"); throw e; } } };
}
let groups = 0; async function test(name, fn) { try { await fn(); groups++; } catch(e) { console.error("Failed: " + name); throw e; } }
(async () => {
  await test("actual product parser proves rejection and input remains unchanged", () => { const c = capture(), before = JSON.stringify(c), v = Store.validateCapture(c,{now}); assert.equal(v.failureCode,"aldi-category-native-index-conflict"); assert.equal(v.sourceId,Store.SOURCE); assert.equal(v.body,c.original.body); assert.equal(v.bytes,c.bytes); assert.equal(JSON.stringify(c),before); });
  for (const [name, change] of [
    ["non200",c=>c.status=403], ["invented code",c=>c.failureCode="price-missing"], ["incorrect genuine code",c=>c.failureCode="aldi-category-native-page-conflict"],
    ["invented authority",c=>c.price=1], ["wrong source country",c=>c.original.meta.scopeCountry="AT"], ["unknown meta",c=>c.original.meta.gtin="123"],
    ["corrupt body",c=>c.original.body+=" "], ["incorrect bytes",c=>c.bytes++], ["bad hash",c=>c.original.meta.sourceResponseHash="0".repeat(64)],
    ["foreign URL",c=>c.original.meta.sourceResponseUrl="https://other.example/sortiment/milk.html"], ["query URL",c=>c.original.meta.sourceResponseUrl+="?page=1"],
    ["future capture",c=>c.original.meta.capturedAt=new Date(now+1).toISOString()], ["stale capture",c=>{c.original.meta.capturedAt=new Date(now-300001).toISOString();c.original.meta.sourceResponseDate=c.original.meta.capturedAt;}],
    ["invalid calendar capture",c=>c.original.meta.capturedAt="2026-02-31T01:00:00.000Z"], ["missing Age",c=>delete c.original.meta.sourceAgeSeconds],
    ["Age string",c=>c.original.meta.sourceAgeSeconds="0"], ["cached Age",c=>c.original.meta.sourceAgeSeconds=301], ["negative Age",c=>c.original.meta.sourceAgeSeconds=-1],
    ["missing Date",c=>c.original.meta.sourceResponseDate=null], ["old Date",c=>c.original.meta.sourceResponseDate=new Date(at-300001).toISOString()],
    ["invalid UTF8 surrogate",c=>{c.original.body+="\ud800";rehash(c);}], ["NUL",c=>{c.original.body+="\u0000";rehash(c);}]
  ]) await test(name + " rejects without admission", () => { const c=capture();change(c);assert.throws(()=>Store.validateCapture(c,{now}),/aldi-rejected-/); });
  await test("full byte bound and invalid original byte sequence reject", () => { const c=capture();c.original.body=" ".repeat(Store.MAX_BYTES+1);rehash(c);assert.throws(()=>Store.validateCapture(c,{now}),/byte-bound/);c.original.body=Buffer.from([0xc3,0x28]);assert.throws(()=>Store.validateCapture(c,{now}),/utf8/); });
  await test("a successful native product page cannot be mislabeled as rejected", () => { const original=Fixture.original(Fixture.html(),at);assert.throws(()=>Store.validateCapture({status:200,failureCode:"aldi-category-native-index-conflict",original},{now}),/parser-failure-conflict/); });
  await test("actual malformed JSON is retained only under its exact parser code", () => { const c=capture();c.original.body=c.original.body.replace('"syntheticDiagnosticFixture":true','"syntheticDiagnosticFixture":');c.failureCode="aldi-category-next-data-invalid";rehash(c);const s=Store.diagnosticSummary(c,{now});assert.equal(s.nativeRoute,null);assert.equal(s.fresh,false); });
  await test("original HTTP Date normalizes without rewriting its private original header", () => { const c=capture();c.original.meta.sourceResponseDate=new Date(at).toUTCString();const v=Store.validateCapture(c,{now});assert.equal(v.originalResponseDate,c.original.meta.sourceResponseDate);assert.equal(v.sourceResponseDate,new Date(Date.parse(c.original.meta.sourceResponseDate)).toISOString()); });
  await test("diagnostics preserve dated capture, expose only actually present category URLs and no authority/body", () => {
    const c=capture(at,n=>{n.props.pageProps.page.componentList={0:{"@name":"link-block","mgnl:template":"synthetic:links",path:"/sortiment/milchprodukte.html",title:"<b>unsafe</b>"}};n.props.pageProps.page.productLink="https://www.aldi-nord.de/produkt/test-1040001.html";});
    const s=Store.diagnosticSummary(c,{now:now+30*86400000});assert.equal(s.capturedAt,c.original.meta.capturedAt);assert.equal(s.current,false);assert.equal(s.fresh,false);assert.equal(s.admitted,false);assert.equal(s.discoveryOnly,true);assert(s.presentCategoryUrls.includes("https://www.aldi-nord.de/sortiment/milchprodukte.html"));assert(!s.presentCategoryUrls.some(v=>v.includes("/produkt/")));assert(s.urlEvidence.some(v=>v.originalValue==="/sortiment/milchprodukte.html"));assert(!JSON.stringify(s).includes("<b>"));for(const key of["body","original","gtin","price","storeId"])assert(!Object.hasOwn(s,key));for(const key of["truthEligible","currentPriceVerified","physicalStorePriceVerified","currentAvailabilityVerified","canonicalIdentityVerified","normalPriceClassificationVerified","assortmentComplete"])assert.equal(s[key],false);
  });
  await test("diagnostic URL output is bounded",()=>{const c=capture(at,n=>{n.links=Array.from({length:200},(_,i)=>"https://www.aldi-nord.de/sortiment/synthetic-"+i+".html")});assert.equal(Store.diagnosticSummary(c,{now}).presentCategoryUrls.length,128);});
  await test("genuine-style inherited client needs assigned writing transaction; no owned COMMIT",async()=>{const h=memory();assert.equal(typeof h.tx.connect,"function");await assert.rejects(Store.persist(h.tx,capture(),{now}),/writing-transaction-required/);await assert.rejects(Store.persist(h.pool,capture(),{now}),/writing-client-required/);await h.open();const saved=await Store.persist(h.tx,capture(),{now});assert.equal(saved.storedCaptures,1);assert.equal(saved.cursorAdvanced,false);assert.equal(saved.cooldownChanged,false);assert.equal(saved.priceRowsCreated,0);assert(!h.events.includes("COMMIT"));assert(!h.events.includes("release"));await h.tx.query("ROLLBACK");});
  await test("private original/history/latest commit together; exact replay is immutable",async()=>{const h=memory(),c=capture();await h.save(c);const before=h.snapshot(),r=await h.save(c);assert.equal(r.storedCaptures,0);assert.equal(r.latestUpdated,0);assert.equal(r.unchangedCaptures,1);assert.equal(h.snapshot(),before);const s=await Store.status(h.pool,{now});assert.equal(s.readableLatestUrls,1);assert.equal(s.diagnostics[0].capturedAt,c.original.meta.capturedAt);});
  await test("same original Date/hash/Age cannot be retimed; genuinely new response Date can",async()=>{const h=memory(),c=capture();await h.save(c);const v=clone(c);v.original.meta.capturedAt=new Date(at+1000).toISOString();await assert.rejects(h.save(v),/retimed-original-forbidden/);const newer=capture(at+1000);const saved=await h.save(newer);assert.equal(saved.latestUpdated,1);assert.equal(h.data().originals.size,1);assert.equal(h.data().history.size,2);});
  await test("sameclock contradiction holds latest and original replay cannot reveal clean fallback",async()=>{const h=memory(),c=capture();await h.save(c);const changed=capture(at,n=>n.note="SYNTHETIC contradiction");assert.equal((await h.save(changed)).held,true);const s=await Store.status(h.pool,{now});assert.equal(s.heldUrls,1);assert.equal(s.diagnostics.length,0);await h.save(c);assert.equal((await Store.status(h.pool,{now})).heldUrls,1);await h.save(capture(at+1000,n=>n.note="SYNTHETIC new response"));assert.equal((await Store.status(h.pool,{now})).readableLatestUrls,1);assert.equal(h.data().history.size,3);});
  await test("older genuine capture is historical only and cannot replace latest",async()=>{const h=memory();await h.save(capture(at+1000));assert.equal((await h.save(capture(at))).latestUpdated,0);assert.equal((await Store.status(h.pool,{now})).diagnostics[0].capturedAt,new Date(at+1000).toISOString());});
  await test("unexpected write failure rolls back all private tables and a retry can commit",async()=>{const h=memory();h.fail="INSERT INTO "+Store.CAPTURE_TABLE;await assert.rejects(h.save(capture()),/SQL failure/);assert.equal(h.data().originals.size,0);assert.equal(h.data().history.size,0);assert.equal(h.data().latest.size,0);assert.equal((await h.save(capture())).storedCaptures,1);});
  await test("reader rechecks actual body/checksum and excludes corrupt latest without fallback",async()=>{const h=memory();await h.save(capture());h.data().originals.values().next().value.body+=" ";const s=await Store.status(h.pool,{now});assert.equal(s.readableLatestUrls,0);assert.equal(s.excludedInvalidLatest,1);});
  await test("status loads distinct original bodies once after metadata, including held conflicts",async()=>{const h=memory();await h.save(capture());await h.save(capture(at+1000));await h.save(capture(at+1000,n=>n.note="SYNTHETIC tied conflict"));const start=h.events.length,s=await Store.status(h.pool,{now}),reads=h.events.slice(start);assert.equal(s.heldUrls,1);assert.equal(s.diagnostics.length,0);assert(reads[0].startsWith("SELECT l.held"));assert(!reads.filter(sql=>sql.startsWith("SELECT l.held")||sql.startsWith("SELECT c.*")).some(sql=>sql.includes("b.body,b.body_bytes")));assert.equal(reads.filter(sql=>sql.startsWith("SELECT body,body_bytes")).length,2);});
  await test("many malformed URL captures share one original and status fetches that body only once",async()=>{const h=memory(),body="<!doctype html><p>SYNTHETIC fehlendes Canonical: Grüße</p>";for(let i=0;i<32;i++){const original=Fixture.original(body,at);original.meta.sourceResponseUrl="https://www.aldi-nord.de/sortiment/synthetic-shared-"+i+".html";await h.save({status:200,failureCode:"aldi-category-canonical-required",original});}const start=h.events.length,s=await Store.status(h.pool,{now});assert.equal(s.readableLatestUrls,32);assert.equal(h.data().originals.size,1);assert.equal(h.events.slice(start).filter(sql=>sql.startsWith("SELECT body,body_bytes")).length,1);assert(!JSON.stringify(s).includes(body));});
  for(const [name,bounds] of[["capture count",{captures:Store.MAX_CAPTURES}],["body bytes",{bytes:Store.MAX_TOTAL_BYTES}],["URL count",{urls:Store.MAX_URLS}]])await test("private "+name+" bound fails closed",async()=>{const h=memory();h.bounds=bounds;await assert.rejects(h.save(capture()),/storage-bound/);assert.equal(h.data().history.size,0);});
  await test("schema init shares success, retry on failure, never caches a rollback client",async()=>{let calls=0;const pool={connect(){},query:async()=>{calls++;return{rows:[]}}};await Promise.all([Store.ensure(pool),Store.ensure(pool)]);await Store.ensure(pool);assert.equal(calls,1);let fails=0;const retry={connect(){},query:async()=>{if(++fails===1)throw Error("DDL failure");return{rows:[]}}};await assert.rejects(Store.ensure(retry),/DDL failure/);await Store.ensure(retry);assert.equal(fails,2);let clientCalls=0;const tx={release(){},query:async()=>{clientCalls++;return{rows:[]}}};await Store.ensure(tx);await Store.ensure(tx);assert.equal(clientCalls,2);});
  console.log(`aldi-category-rejected-capture-store: ${groups} offline groups passed; actual parser failures, immutable originals, private latest/held/bounds/transactions; no HTTP or real SQL`);
})().catch(e=>{console.error(e);process.exitCode=1});
