"use strict";
const assert=require("node:assert/strict"),Refresh=require("../aldi-category-refresh"),Parser=require("../aldi-assortment-category-client"),Fetch=require("../aldi-category-fetch-client"),Articles=require("../aldi-category-article-service"),Fixture=require("./fixtures/aldi-category-capture");
const time=Date.UTC(2026,9,3,3,30);
function observation(at=time,body=Fixture.html()){const original=Fixture.original(body,at);return{page:Parser.parsePage(body,original.meta,{now:at}),original,discoveredTargets:Fetch.navigationTargets(body),requests:1,bytes:Buffer.byteLength(body)};}
function harness(options={}){
 let clock=time,saved={},pending=null,storedArticles=0,storedPrices=0,fetches=0,releasedWith;const events=[];
 const tx={release:error=>{releasedWith=error;events.push("release");},query:async(sql,params)=>{events.push(sql);if(sql==="BEGIN")pending={saved:structuredClone(saved),articles:storedArticles,prices:storedPrices};if(sql==="ROLLBACK"){pending=null;if(options.failRollback)throw options.failRollback;}if(sql==="COMMIT"){if(options.failCommit)throw options.failCommit;saved=pending.saved;storedArticles=pending.articles;storedPrices=pending.prices;pending=null;}if(/SELECT cursor FROM/.test(sql))return{rows:pending.saved.cursor?[{cursor:pending.saved.cursor}]:[]};if(/INSERT INTO aldi_category_catalog_state/.test(sql)){if(options.failCheckpoint)throw options.failCheckpoint;pending.saved={cursor:JSON.parse(params[1]),lastError:null,retryAfter:null};}return{rows:[],rowCount:1};}};
 const pool={query:async(sql,params)=>{events.push(sql);if(/INSERT INTO aldi_category_catalog_state/.test(sql)){saved={...saved,lastError:params[2],retryAfter:params[3]};}return{rows:[],rowCount:1};},connect:async()=>{events.push("connect");return tx;}};
 const deps={load:async()=>saved,canFetch:async()=>options.gate??true,fetchPage:async()=>{fetches++;if(options.fetchError)throw options.fetchError;return options.observed||observation(clock);},sleep:async()=>{},articles:{ensure:async()=>{},persist:async(client,page,{original,now})=>{assert.equal(client,tx);const real=Articles.originalPage(original,now);assert.deepEqual(real.parsed,page);pending.articles+=page.candidateCount;if(options.failArticle)throw options.failArticle;return{received:page.receivedCount,accepted:page.candidateCount};}},prices:{ensure:async()=>{},persist:async(client,page)=>{assert.equal(client,tx);pending.prices+=page.candidateCount;if(options.failPrice)throw options.failPrice;return{received:page.candidateCount,accepted:page.candidateCount};}}};
 return{pool,deps,events,get saved(){return saved;},set saved(x){saved=x;},get fetches(){return fetches;},get articles(){return storedArticles;},get prices(){return storedPrices;},get releaseError(){return releasedWith;},set clock(x){clock=x;},run:(extra={})=>Refresh.refresh({pool,maxRequests:1,now:()=>clock,...extra},deps)};
}
(async()=>{let checks=0;
 const good=harness(),result=await good.run();assert.equal(result.pages,1);assert.equal(result.requests,1);assert.equal(result.identityAccepted,1);assert.equal(result.accepted,1);assert.equal(good.articles,1);assert.equal(good.prices,1);assert.equal(good.saved.cursor.nextIndex,1);assert.equal(good.saved.cursor.targets.length,2);assert.equal(good.saved.cursor.targetProofs[0].sourceResponseHash,observation().original.meta.sourceResponseHash);assert(good.events.indexOf("COMMIT")>good.events.findIndex(x=>/INSERT INTO aldi_category_catalog_state/.test(x)));assert.equal(good.releaseError,undefined);assert.equal(result.catalog.fullAssortment,false);checks++;
 const paused=await good.run();assert.equal(paused.skipped,"category-not-due");assert.equal(good.fetches,1);checks++;
 for(const kind of["failArticle","failPrice","failCheckpoint","failCommit"]){const original=Error(kind),h=harness({[kind]:original});await assert.rejects(h.run(),e=>e===original);assert.equal(h.articles,0);assert.equal(h.prices,0);assert.equal(h.saved.cursor,undefined);assert.equal(h.saved.retryAfter,new Date(time+3600000).toISOString());assert(h.events.includes("ROLLBACK"));assert.equal(h.releaseError,undefined);checks++;}
 const broken=Error("rollback broken"),hBroken=harness({failPrice:Error("price write failed"),failRollback:broken});await assert.rejects(hBroken.run(),/price write failed/);assert.equal(hBroken.releaseError,broken,"Broken rollback evicts the pooled client");checks++;
 for(const status of[403,429]){const error=Object.assign(Error("source refused"),{code:"aldi-category-http-"+status,status,retryAfterMs:7200000}),h=harness({fetchError:error});await assert.rejects(h.run(),e=>e===error&&e.nextAttemptAt===new Date(time+7200000).toISOString());assert.equal(h.fetches,1);assert(!h.events.includes("connect"));assert.equal((await h.run()).skipped,"category-not-due");assert.equal(h.fetches,1);checks++;}
 const extreme=harness({fetchError:Object.assign(Error("source paused beyond ordinary years"),{code:"aldi-category-http-429",retryAfterMs:8640000000000000-time})});await assert.rejects(extreme.run(),e=>e.nextAttemptAt==="+275760-09-13T00:00:00.000Z");assert(extreme.saved.retryAfter instanceof Date);assert.equal(extreme.saved.retryAfter.getTime(),8640000000000000);assert.equal((await extreme.run()).skipped,"category-not-due");assert.equal(extreme.fetches,1);checks++;
 const denied=harness({gate:false});assert.equal((await denied.run()).skipped,"shared-source-not-eligible");assert.equal(denied.fetches,0);assert(!denied.events.includes("connect"));checks++;
 const lostDuringPause=harness();let eligible=true;lostDuringPause.deps.canFetch=async()=>eligible;lostDuringPause.deps.sleep=async()=>{eligible=false;};const partial=await lostDuringPause.run({maxRequests:2});assert.equal(partial.pages,1);assert.equal(partial.requests,1);assert.equal(lostDuringPause.fetches,1,"Shutdown or lease loss during the inter-request pause prevents the next GET");assert.equal(lostDuringPause.saved.cursor.nextIndex,1);checks++;
 const explicit=harness({gate:new Date(time+3600000).toISOString()});assert.equal((await explicit.run()).nextAttemptAt,new Date(time+3600000).toISOString());assert.equal(explicit.fetches,0);checks++;
 const forged=observation();forged.discoveredTargets=["https://www.aldi-nord.de/sortiment/forged-category.html"];const hForged=harness({observed:forged});await assert.rejects(hForged.run(),/aldi-category-result-unconfirmed/);assert.equal(hForged.articles,0);assert.equal(hForged.saved.cursor,undefined);checks++;
 const badCheckpoint=Refresh.state();badCheckpoint.targets.push("https://www.aldi-nord.de/sortiment/unwitnessed.html");assert.throws(()=>Refresh.state({cursor:badCheckpoint}),/aldi-category-discovery-proof-required/);assert.throws(()=>Refresh.state({cursor:{...Refresh.state(),nextIndex:2}}),/aldi-category-checkpoint-invalid/);checks++;
 assert.equal(Refresh.eligibleNavigation("https://www.aldi-nord.de/sortiment/sortiment-highlights/preis-highlights.html"),false);assert.equal(Refresh.eligibleNavigation("https://www.aldi-nord.de/sortiment/milchprodukte.html"),true);checks++;
 const expired=harness();expired.saved={retryAfter:new Date(time+60000).toISOString()};assert.equal((await expired.run()).skipped,"category-not-due");assert.equal(expired.fetches,0);expired.clock=time+60001;const retry=await expired.run();assert.equal(retry.pages,1);assert.equal(expired.fetches,1);checks++;
 const single=observation(time,Fixture.html(undefined,{navigation:[]})),complete=harness({observed:single}),done=await complete.run();assert.equal(done.catalog.categoryTraversalFinished,true);assert.equal(done.catalog.fullAssortment,false);assert.equal(complete.saved.cursor.completedPasses,1);assert.equal(complete.saved.cursor.nextPassAt,new Date(time+Refresh.REFRESH_MS).toISOString());assert.equal((await complete.run()).skipped,"category-not-due");checks++;
 await assert.rejects(Refresh.refresh({pool:good.pool}),/aldi-shared-source-gate-required/);for(const maxRequests of[0,5,1.5,true])await assert.rejects(good.run({maxRequests}),/aldi-category-request-budget-invalid/);checks++;
 console.log("aldi-category-refresh: "+checks+" atomic original/identity/price/checkpoint, shared-gate, durable pause and witnessed cursor groups passed");
})().catch(error=>{console.error(error);process.exitCode=1;});
