"use strict";
const assert=require("node:assert/strict"),{Pool}=require("pg"),crypto=require("node:crypto"),Service=require("../aldi-assortment-article-service"),Client=require("../aldi-assortment-client"),Price=require("../aldi-assortment-price-service"),Refresh=require("../aldi-assortment-refresh"),original=require("./fixtures/retailers/aldi-public-assortment.json");
async function main(){
 const connectionString=process.env.DATABASE_URL;assert(connectionString,"DATABASE_URL is required");const database=new URL(connectionString);assert(["localhost","127.0.0.1"].includes(database.hostname)&&!database.search&&!database.hash&&/^\/[a-z][a-z0-9_]*_test$/.test(database.pathname),"Only a dedicated named loopback *_test database is allowed");
 const pool=new Pool({connectionString,ssl:false,connectionTimeoutMillis:5000}),now=Date.now(),base=now-10000;let tx,groups=0;
 // These are synthetic originals with their own UTF8 hashes. No old capture is
 // retimed or imported, no native HTTP is sent, and all fixture writes roll back.
 function capture(index,at=base,patch={},withPrice=false){const sku=String(950330000000+index),product={...structuredClone(original.product),objectID:sku,productSlug:"postgres-test-native-article-"+sku,name:"POSTGRES TEST ALDI article "+index,shortDescription:"fixed native variety",brandName:"POSTGRES TEST",salesUnit:"1-Liter-Packung",isAvailable:true,isComingSoon:false,isRecall:false,isDepositProduct:false,depositValue:0,currentPrice:withPrice?{priceValue:1.29,validFrom:Math.floor(at/1000)-86400,validUntil:Math.floor(at/1000)+86400}:null,...patch};
  const body='<script id="__NEXT_DATA__" type="application/json">'+JSON.stringify({props:{pageProps:{syntheticSQLOriginal:true,apiData:JSON.stringify([["PRODUCT_DETAIL_GET",{req:{productIds:[sku]},res:{products:[product]}}]])}}})+'</script>',meta={sourceUrl:"https://www.aldi-nord.de/produkt/postgres-test-native-article-"+sku+".html",capturedAt:new Date(at).toISOString(),sourceResponseDate:new Date(at).toISOString(),sourceAgeSeconds:0,sourceResponseHash:crypto.createHash("sha256").update(body).digest("hex"),raw:body};const parsed=Client.parseProduct(Client.extractProducts(body).products[0],meta);assert(parsed.ok,JSON.stringify(parsed));assert.equal(!!parsed.offer,withPrice);return parsed;}
 const count=async(table,client=pool)=>{const exists=(await client.query("SELECT to_regclass($1) AS name",["public."+table])).rows[0].name;return exists?(await client.query("SELECT count(*)::int AS total FROM "+table)).rows[0].total:null;};
 try{
  const baseline={};for(const table of["products","stores","price_observations","receipt_submissions"])baseline[table]=await count(table);
  await Service.ensure(pool);await Price.ensure(pool);await Refresh.ensure(pool);
  const before={articles:await count(Service.TABLE),prices:await count(Price.TABLE),refresh:JSON.stringify((await pool.query(`SELECT * FROM ${Refresh.TABLE} WHERE source_id=$1`,[Service.SOURCE])).rows)};
  const schema=(await pool.query("SELECT column_name FROM information_schema.columns WHERE table_schema='public' AND table_name=$1",[Service.TABLE])).rows.map(r=>r.column_name);assert(!schema.includes("price")&&!schema.includes("expires_at")&&!schema.includes("store_id"));groups++;
  tx=await pool.connect();assert.equal(typeof tx.connect,"function");assert.equal(Object.hasOwn(tx,"connect"),false,"Exercise the genuine PoolClient with inherited connect, without a masking wrapper");await assert.rejects(()=>Service.persist(tx,[capture(0).product],{now}),/open-writing-transaction-required/);await assert.rejects(()=>Service.persist(pool,[],{now}),/transaction-client-required/);groups++;
  await tx.query("BEGIN");await assert.rejects(()=>Service.persist(tx,[],{now}),/open-writing-transaction-required/,"BEGIN without an assigned writing transaction cannot authorize article writes");await tx.query("SELECT txid_current()");groups++;
  const first=capture(0),water=capture(1,base,{salesUnit:"9x0,5-Liter-Flasche",isAvailable:false}),old=capture(2,now-30*86400000);assert.equal(first.offer,null);let saved=await Service.persist(tx,[first.product,water.product,old.product],{now});assert.equal(saved.upserted,3);assert.equal(saved.priceRowsCreated,0);assert.equal(saved.canonicalProductsCreated,0);groups++;
  const search=async(index,extra={})=>Service.search(tx,{retailerSku:String(950330000000+index),now,...extra});
  let result=await search(0);assert.equal(result.items.length,1);const item=result.items[0];assert.equal(item.gtin,null);assert.equal(item.state,"last-observed");assert.equal(item.currentPriceVerified,false);assert.equal(item.availability,"unknown");assert.equal(item.locationScope,"unknown");assert.equal(item.scopeCountry,"DE");assert.equal(item.truthEligible,false);assert.equal(item.price,undefined);assert.equal(item.expiresAt,null);assert.equal(item.observedAt,first.product.observedAt);assert.equal(item.sourceResponseHash,first.product.sourceResponseHash);groups++;
  result=await search(2);assert.equal(result.items.length,1);assert.equal(result.items[0].recentlyObserved,false);assert.equal(result.items[0].observedAt,old.product.observedAt,"A price deadline must not delete dated article identity");groups++;
  assert.equal((await search(1,{pack:"9 x 500 ml"})).items.length,1);assert.equal((await search(1,{pack:"4.5 l"})).items.length,0);assert.equal((await search(1)).items[0].nativePublicationAvailableAtObservation,false);groups++;
  const snapshot=async(index)=>(await tx.query(`SELECT observed_at,source_response_hash,capture_hash,identity_hash,held,conflict_capture FROM ${Service.TABLE} WHERE retailer_sku=$1`,[String(950330000000+index)])).rows[0];
  const firstSnapshot=await snapshot(0);saved=await Service.persist(tx,[first.product,first.product],{now});assert.equal(saved.upserted,0);assert.equal(saved.duplicates,1);assert.deepEqual(await snapshot(0),firstSnapshot);groups++;
  const newer=capture(0,base+1000,{name:"POSTGRES TEST newer fixed article"});saved=await Service.persist(tx,[newer.product],{now});assert.equal(saved.upserted,1);assert.equal((await search(0)).items[0].name,newer.product.name);assert.equal((await search(0)).items[0].observedAt,newer.product.observedAt);groups++;
  const newerSnapshot=await snapshot(0);saved=await Service.persist(tx,[first.product],{now});assert.equal(saved.upserted,0);assert.deepEqual(await snapshot(0),newerSnapshot,"Older unique originals cannot overwrite latest evidence");groups++;
  const retimed={...newer.product,observedAt:new Date(base+2000).toISOString()};saved=await Service.persist(tx,[retimed],{now});assert.equal(saved.accepted,0);assert.equal(saved.rejected,1);assert.equal(saved.reasons["original-capture-replay-retimed"],1);assert.deepEqual(await snapshot(0),newerSnapshot);groups++;
  const contrary=capture(0,base+1000,{name:"POSTGRES TEST contradictory article"});saved=await Service.persist(tx,[contrary.product],{now});assert.equal(saved.heldArticles,1);assert.equal((await search(0)).items.length,0);let held=await snapshot(0);assert.equal(held.held,true);assert.equal(held.conflict_capture.source_response_hash,contrary.product.sourceResponseHash);assert.equal(held.source_response_hash,newer.product.sourceResponseHash);groups++;
  saved=await Service.persist(tx,[newer.product,contrary.product],{now});assert.equal(saved.upserted,0);assert.deepEqual(await snapshot(0),held,"Same original retries cannot release a held article");groups++;
  await Service.persist(tx,[first.product],{now});assert.deepEqual(await snapshot(0),held,"Older clean evidence cannot be used as held latest fallback");groups++;
  const resolved=capture(0,base+3000,{name:"POSTGRES TEST genuine new unique article"});await Service.persist(tx,[resolved.product],{now});assert.equal((await search(0)).items.length,1);assert.equal((await snapshot(0)).held,false);assert.equal((await snapshot(0)).conflict_capture,null);groups++;
  const sameBatchA=capture(3,base+1000),sameBatchB=capture(3,base+1000,{salesUnit:"2x0,5-Liter-Packung"}),olderClean=capture(3,base);saved=await Service.persist(tx,[olderClean.product,sameBatchA.product,sameBatchB.product],{now});assert.equal(saved.upserted,1);assert.equal(saved.heldArticles,1);assert.equal((await search(3)).items.length,0,"Latest equal-time pack conflict cannot fall back to older clean article");assert.equal((await snapshot(3)).held,true);groups++;
  const sameIdentity=capture(4),anotherProof=capture(4,base,{syntheticDifferentOriginal:true});assert.notEqual(sameIdentity.product.sourceResponseHash,anotherProof.product.sourceResponseHash);await Service.persist(tx,[sameIdentity.product,anotherProof.product],{now});assert.equal((await search(4)).items.length,1,"Different response bytes alone are not a native identity contradiction");assert.equal((await snapshot(4)).held,false);groups++;
  const invalid=[{...first.product,scopeCountry:"AT"},{...first.product,gtin:"3017620422003"},{...first.product,scopeChannel:"physical-store"},{...first.product,packCount:99},{...first.product,availability:"available"},{...first.product,sourceResponseDate:new Date(base-400000).toISOString()}];saved=await Service.persist(tx,invalid,{now});assert.equal(saved.accepted,0);assert.equal(saved.rejected,6);groups++;
  for(const change of["gtin='3017620422003'","scope_country='AT'","scope_channel='pickup'","location_scope='Berlin'","pack_amount=0","pack_amount='NaN'::numeric","pack_count=0","source_url='https://www.aldi-nord.de/produkt/wrong-1.html'","source_response_hash='BAD'","source_response_date=observed_at-interval '6 minutes'","held=true,conflict_capture=NULL","held=true,conflict_capture='{}'::jsonb"]){await tx.query("SAVEPOINT invalid_sql");await assert.rejects(()=>tx.query(`UPDATE ${Service.TABLE} SET ${change} WHERE retailer_sku=$1`,[first.product.retailerSku]),e=>e.code==="23514",change);await tx.query("ROLLBACK TO SAVEPOINT invalid_sql");groups++;}
  await tx.query("SAVEPOINT bad_reader");await tx.query(`UPDATE ${Service.TABLE} SET capture_hash=repeat('0',64) WHERE retailer_sku=$1`,[first.product.retailerSku]);assert.equal((await search(0)).items.length,0,"Reader rechecks actual canonical serialization hash");await tx.query("ROLLBACK TO SAVEPOINT bad_reader");groups++;
  assert.equal((await Service.search(tx,{search:"article%_",now})).items.length,0);assert.equal((await Service.search(tx,{merchant:"REWE",now})).items.length,0);assert.equal((await Service.search(tx,{scopeChannel:"pickup",now})).items.length,0);await assert.rejects(()=>Service.search(tx,{gtin:"3017620422003",now}),/invalid-article-query/);groups++;
  const status=await Service.status(tx,{now});assert.equal(status.currentAvailabilityVerified,false);assert.equal(status.currentPriceVerified,false);assert.equal(status.assortmentComplete,false);assert.equal(status.locationScope,"unknown");assert(status.heldArticles>=1);groups++;
  // Synthetic legacy rows below have self-consistent serialization hashes but
  // an uncertain native quantity. They remain stored, never valid inventory.
  const fixedLegacy=capture(6,base+5000,{salesUnit:"770-g-Packung"});await Service.persist(tx,[fixedLegacy.product],{now});
  const legacyColumns=["source_id","merchant","retailer_sku","gtin","name","brand","variant","pack","pack_amount","pack_unit","pack_count","source_url","scope_country","scope_channel","location_scope","observed_at","source_response_hash","source_response_date","source_age_seconds","publication_available","identity_hash","capture_hash"];
  const legacyTemplate=(await tx.query(`SELECT ${legacyColumns.join(",")} FROM ${Service.TABLE} WHERE retailer_sku=$1`,[fixedLegacy.product.retailerSku])).rows[0];
  for(const key of["pack_amount","pack_count","source_age_seconds"])if(legacyTemplate[key]!==null)legacyTemplate[key]=Number(legacyTemplate[key]);for(const key of["observed_at","source_response_date"])legacyTemplate[key]=new Date(legacyTemplate[key]).toISOString();
  const beforeLegacy=await Service.status(tx,{now});
  for(const patch of[...["z. B. 770 g","ca. 770 g","700-900 g","700 bis 900 g","770 g / 900 g","je nach Gewicht 770 g"].map(pack=>({pack})),...["verschiedene Gewichte","verschiedene Größen","verschiedene Mengen"].map(variant=>({variant}))]){
   await tx.query("SAVEPOINT legacy_uncertain_pack");const legacy={...legacyTemplate,...patch};
   legacy.identity_hash=crypto.createHash("sha256").update(JSON.stringify([legacy.source_id,legacy.merchant,legacy.retailer_sku,legacy.name,legacy.brand,legacy.variant,legacy.pack,legacy.pack_amount,legacy.pack_unit,legacy.pack_count,legacy.source_url,legacy.scope_country,legacy.scope_channel,legacy.location_scope,legacy.publication_available])).digest("hex");const serialized={};for(const key of legacyColumns)if(key!=="capture_hash")serialized[key]=legacy[key];legacy.capture_hash=crypto.createHash("sha256").update(JSON.stringify(serialized)).digest("hex");
   await tx.query(`UPDATE ${Service.TABLE} SET pack=$1,variant=$2,identity_hash=$3,capture_hash=$4 WHERE retailer_sku=$5`,[legacy.pack,legacy.variant,legacy.identity_hash,legacy.capture_hash,fixedLegacy.product.retailerSku]);assert.equal((await search(6)).items.length,0,"Legacy uncertain pack/variant cannot be a fixed-pack DTO: "+JSON.stringify(patch));
   const excluded=await Service.status(tx,{now});assert.equal(excluded.storedArticles,beforeLegacy.storedArticles);assert.equal(excluded.heldArticles,beforeLegacy.heldArticles);assert.equal(excluded.excludedInvalidArticles,beforeLegacy.excludedInvalidArticles+1);assert.equal(excluded.lastObservedArticles,beforeLegacy.lastObservedArticles-1);assert.equal(excluded.storedArticles,excluded.heldArticles+excluded.excludedInvalidArticles+excluded.lastObservedArticles);assert.equal(excluded.currentPriceVerified,false);assert.equal(excluded.currentAvailabilityVerified,false);await tx.query("ROLLBACK TO SAVEPOINT legacy_uncertain_pack");groups++;
  }
  // Real price, native article, and refresh checkpoint participate in one outer
  // transaction. A later checkpoint failure rolls every preceding write back.
  const priced=capture(5,base,{},true);await Service.persist(tx,[priced.product],{now});assert.equal((await Price.persist(tx,[priced.offer],{now})).upserted,1);await tx.query(`INSERT INTO ${Refresh.TABLE}(source_id,target_count,next_index) VALUES($1,1,1) ON CONFLICT(source_id) DO UPDATE SET target_count=1,next_index=1`,[Service.SOURCE]);await assert.rejects(()=>tx.query(`UPDATE ${Refresh.TABLE} SET next_index=NULL WHERE source_id=$1`,[Service.SOURCE]),e=>e.code==="23502","A real final checkpoint failure aborts the outer transaction");await tx.query("ROLLBACK");assert.equal(await count(Service.TABLE),before.articles);assert.equal(await count(Price.TABLE),before.prices);assert.equal(JSON.stringify((await pool.query(`SELECT * FROM ${Refresh.TABLE} WHERE source_id=$1`,[Service.SOURCE])).rows),before.refresh);groups++;
  for(const [table,total]of Object.entries(baseline))assert.equal(await count(table),total,"Native catalog cannot mutate "+table);groups++;
  // A transaction client initialized under a temporary schema must retry real
  // DDL after rollback; no client cache may survive and hide a missing table.
  for(let i=0;i<2;i++){await tx.query("BEGIN");await tx.query("SET LOCAL search_path=pg_temp");await Service.ensure(tx);assert((await tx.query("SELECT to_regclass('pg_temp.'||$1) AS name",[Service.TABLE])).rows[0].name);await tx.query("ROLLBACK");}groups++;
  const version=(await pool.query("SHOW server_version")).rows[0].server_version;console.log(`aldi-assortment-article-postgres: PostgreSQL ${version}; ${groups} actual SQL groups passed; price-less native identities, bounded latest rows, same-capture holds, replay/rollback and no canonical/stock upgrades`);
 }finally{if(tx){try{await tx.query("ROLLBACK");}catch{}tx.release();}await pool.end();}
}
main().catch(e=>{console.error(e);process.exitCode=1;});
