"use strict";
const assert=require("node:assert/strict"),Refresh=require("../aldi-category-refresh"),Fetch=require("../aldi-category-fetch-client"),Navigation=require("../aldi-category-navigation-parser"),Fixture=require("./fixtures/aldi-navigation-capture");
const now=Fixture.time,clone=structuredClone,base="https://www.aldi-nord.de/sortiment/";let groups=0;
function test(name,fn){try{fn();groups++;}catch(error){console.error(name);throw error;}}
function frontier(){const cursor=Refresh.state();cursor.targets.push(Fixture.parentUrl,base+"getraenke.html",base+"obst-und-gemuese.html",base+"backwaren.html");cursor.nextIndex=1;cursor.revision=8;cursor.lastRunAt=new Date(now-120000).toISOString();cursor.targetProofs=cursor.targets.slice(1).map(target=>({target,from:Fetch.SEED,sourceResponseHash:"a".repeat(64),capturedAt:cursor.lastRunAt}));return Refresh.state({cursor});}
function parent(){const original=Fixture.parent(),navigation=Navigation.parseNavigationParent(original.body,original.meta,{now});return{original,navigation,discoveredTargets:navigation.discoveredTargets};}
test("fresh authored parent proves discovery but still admits no article or price",()=>{const value=parent();assert.equal(value.navigation.articleRowsCreated,0);assert.equal(value.navigation.priceRowsCreated,0);assert.equal(value.navigation.assortmentComplete,false);assert(!value.discoveredTargets.includes(base+"vorraete.html"));});
test("new milk children precede the older broad pending catalogue without revisiting completed seed or parent",()=>{const previous=frontier(),before=JSON.stringify(previous),next=Refresh.nextState(previous,parent(),now);assert.equal(JSON.stringify(previous),before);assert.deepEqual(next.targets.slice(0,next.nextIndex),[Fetch.SEED,Fixture.parentUrl]);assert.equal(next.nextIndex,2);assert.equal(next.revision,9);const pending=next.targets.slice(next.nextIndex),milk=pending.filter(target=>target.includes("/milchprodukte/"));assert.equal(milk.length,2);assert.deepEqual(pending.slice(0,2),milk);assert(!pending.includes(Fetch.SEED));assert.equal(next.completedPasses,0);assert.equal(next.nextPassAt,null);});
test("every prior proof survives and each new child carries the exact source body hash and clock",()=>{const previous=frontier(),value=parent(),next=Refresh.nextState(previous,value,now);for(const proof of previous.targetProofs)assert.deepEqual(next.targetProofs.find(p=>p.target===proof.target),proof);for(const target of value.discoveredTargets.filter(target=>!previous.targets.includes(target)))assert.deepEqual(next.targetProofs.find(p=>p.target===target),{target,from:Fixture.parentUrl,sourceResponseHash:value.original.meta.sourceResponseHash,capturedAt:value.original.meta.capturedAt});assert.equal(new Set(next.targets).size,next.targets.length);assert.equal(next.targetProofs.length,next.targets.length-1);});
test("source pause and one-minute continuation remain effective on the reordered checkpoint",()=>{const next=Refresh.nextState(frontier(),parent(),now),pause=new Date(now+8*86400000).toISOString();assert.equal(Refresh.dueAt({cursor:next,retryAfter:pause},now),Date.parse(pause));assert.equal(Refresh.dueAt({cursor:next},now),now+Refresh.CONTINUATION_MS);assert.equal(Refresh.state({cursor:next}).revision,next.revision);});
test("validated native leaf siblings use the same pending priority and keep independent header proof",()=>{const original=Fixture.leaf(),targets=Fetch.discoveryTargets(original,{now}),previous=Refresh.state();previous.targets.push(base+"getraenke.html");previous.targetProofs=[{target:base+"getraenke.html",from:Fetch.SEED,sourceResponseHash:"b".repeat(64),capturedAt:new Date(now-1000).toISOString()}];const next=Refresh.nextState(previous,{original,discoveredTargets:targets},now),pending=next.targets.slice(1);assert.equal(next.targets[0],Fetch.SEED);assert(pending[0].includes("/milchprodukte/"));assert(pending.includes(base+"getraenke.html"));assert(pending.includes(base+"vorraete.html"));assert.deepEqual(next.targetProofs.find(p=>p.target===base+"getraenke.html"),previous.targetProofs[0]);});
test("the 256 target limit fails without modifying the old checkpoint",()=>{const previous=frontier();while(previous.targets.length<Fetch.MAX_TARGETS){const target=base+"synthetic-extra-"+previous.targets.length+".html";previous.targets.push(target);previous.targetProofs.push({target,from:Fetch.SEED,sourceResponseHash:"c".repeat(64),capturedAt:previous.lastRunAt});}const checked=Refresh.state({cursor:previous}),before=JSON.stringify(checked);assert.throws(()=>Refresh.nextState(checked,parent(),now),error=>error.code==="aldi-category-discovery-bound-exceeded");assert.equal(JSON.stringify(checked),before);});
test("no new targets still completes an actual traversal with its existing four-hour pass delay",()=>{const previous=Refresh.state(),original=Fixture.leaf(),next=Refresh.nextState(previous,{original,discoveredTargets:[]},now);assert.deepEqual(next.targets,[Fetch.SEED]);assert.equal(next.nextIndex,1);assert.equal(next.completedPasses,1);assert.equal(next.nextPassAt,new Date(now+Refresh.REFRESH_MS).toISOString());assert.equal(Refresh.dueAt({cursor:next},now),now+Refresh.REFRESH_MS);});
test("unwitnessed targets remain rejected instead of entering a preferred queue",()=>{const previous=frontier(),bad=clone(previous);bad.targets.push(base+"milchprodukte/forged.html");assert.throws(()=>Refresh.state({cursor:bad}),error=>error.code==="aldi-category-discovery-proof-required");assert.deepEqual(Refresh.state({cursor:previous}),previous);});
console.log("aldi-category-frontier-priority: "+groups+" witnessed pending-order/visited-prefix/proof/bound/cadence groups passed; authored originals only, no HTTP, SQL, article or price admission");
