"use strict";
const assert=require("node:assert/strict"),{Pool}=require("pg"),Service=require("../aldi-assortment-price-service"),Refresh=require("../aldi-assortment-refresh"),Articles=require("../aldi-assortment-article-service"),Inventory=require("../published-retailer-inventory"),Client=require("../aldi-assortment-client");
const fs=require("node:fs"),path=require("node:path"),crypto=require("node:crypto"),DepositProof=require("../aldi-deposit-proof"),Schema=require("../retailer-schema-lifecycle");
function gtin(index){const body=String(950000000000+index),sum=[...body].reduce((n,d,i)=>n+Number(d)*(i%2?3:1),0);return body+(10-sum%10)%10;}
// Keep this existing rollback-only fixture on its genuine connected PostgreSQL
// client. Refresh's inner transactions use real SAVEPOINT SQL so COMMIT cannot
// commit the outer fixture, and no second connection waits on its DDL locks.
// The separate article PostgreSQL program exercises actual Pool/PoolClient use.
function rollbackRefreshPool(client){
 let sequence=0,active=false;const counts={connected:0,released:0};
 return{counts,query:(...args)=>client.query(...args),connect:async()=>{
  assert.equal(active,false,"Refresh must release its scoped writing client");active=true;counts.connected++;const savepoint="aldi_refresh_fixture_"+(++sequence);let begun=false,finished=false,released=false;
  return{query:async(sql,params)=>{
   assert.equal(released,false);
   if(sql==="BEGIN"){assert.equal(begun,false);await client.query("SAVEPOINT "+savepoint);begun=true;return{rows:[],rowCount:null};}
   if(sql==="COMMIT"){assert(begun&&!finished);const result=await client.query("RELEASE SAVEPOINT "+savepoint);finished=true;return result;}
   if(sql==="ROLLBACK"){assert(begun&&!finished);await client.query("ROLLBACK TO SAVEPOINT "+savepoint);const result=await client.query("RELEASE SAVEPOINT "+savepoint);finished=true;return result;}
   return client.query(sql,params);
  },release(){assert(!begun||finished,"Scoped release cannot hide an uncommitted refresh transaction");assert.equal(released,false);released=true;active=false;counts.released++;}};
 }};
}
async function main(){
 const connectionString=process.env.DATABASE_URL;assert(connectionString,"DATABASE_URL is required");const database=new URL(connectionString);assert(["localhost","127.0.0.1"].includes(database.hostname));assert(!database.search&&!database.hash&&/^\/[a-z][a-z0-9_]*_test$/.test(database.pathname),"Only an explicitly named dedicated loopback test database is allowed");
 const pool=new Pool({connectionString,ssl:false,connectionTimeoutMillis:5000}),now=Date.now();let api;
 const fixture=(index,patch={})=>{const sku=String(960000000+index),capturedAt=new Date(now-1000).toISOString();return{sourceId:Service.SOURCE,merchant:"ALDI Nord",retailerSku:sku,gtin:null,name:"POSTGRES TEST ALDI product "+index,brand:"POSTGRES TEST",variant:"fixed native variant",pack:"1-L-Packung",packAmount:1,packUnit:"l",packCount:1,price:1.29,deposit:0,depositIncluded:false,currency:"EUR",priceBasis:"pack",priceKind:"published-current",regularPrice:null,promotionStatus:"unknown",availability:"unknown",publicationAvailable:true,capturedAt,nativeValidFrom:new Date(now-86400000).toISOString(),nativeValidUntil:new Date(now+2*86400000).toISOString(),expiresAt:new Date(now+7*86400000).toISOString(),proofHash:"d".repeat(64),sourceResponseHash:"c".repeat(64),sourceResponseDate:capturedAt,sourceAgeSeconds:0,sourceUrl:"https://www.aldi-nord.de/produkt/postgres-test-aldi-product-"+sku+".html",scopeCountry:"DE",scopeChannel:"assortment-publication",locationScope:"unknown",truthEligible:false,...patch};};
 try{
  const exists=async table=>!!(await pool.query("SELECT to_regclass($1) AS name",["public."+table])).rows[0].name,baseline={};
  for(const table of["products","stores","price_observations","receipts","receipt_submissions"])baseline[table]=await exists(table)?(await pool.query("SELECT count(*)::int AS count FROM "+table)).rows[0].count:null;
  const inventoryBefore=await Inventory.status(pool,{now});
  for(const table of["retailer_published_prices","wolt_retailer_published_prices","rewe_retailer_published_prices"])baseline[table]=await exists(table)?(await pool.query("SELECT count(*)::int AS count FROM "+table)).rows[0].count:null;
  const fixtures=Array.from({length:501},(_,index)=>fixture(index)),saved=await Service.persist(pool,fixtures,{now});assert.equal(saved.accepted,501);assert.equal(saved.rejected,0);assert.equal(saved.upserted,501);
  assert.equal((await Service.search(pool,{...{retailerSku:fixtures[0].retailerSku,now,limit:1},pack:"1 l"})).items.length,1,"Real SQL selects an equivalent normalized single pack before its cap");
  assert.equal((await Service.search(pool,{...{retailerSku:fixtures[0].retailerSku,now,limit:1},pack:"2 x 500 ml"})).items.length,0,"Equal total volume must not admit a different sales pack");
  assert.equal((await Service.search(pool,{...{retailerSku:fixtures[0].retailerSku,now,limit:1},pack:"500 ml"})).items.length,0);
  const stored=(await pool.query(`SELECT count(*)::int AS total,count(*) FILTER(WHERE gtin IS NULL AND scope_country='DE' AND scope_channel='assortment-publication' AND location_scope='unknown' AND currency='EUR' AND pack_amount=1000 AND pack_unit='ml' AND pack_count=1 AND price=1.29 AND deposit=0 AND expires_at=captured_at+interval '24 hours')::int AS exact FROM ${Service.TABLE} WHERE retailer_sku=ANY($1::text[])`,[fixtures.map(row=>row.retailerSku)])).rows[0];assert.equal(stored.total,501);assert.equal(stored.exact,501,"Native pack/TTL and zero GTIN identity are enforced in stored rows");
  const inventoryAfter=await Inventory.status(pool,{now});assert.equal(inventoryAfter.currentPrices,inventoryBefore.currentPrices+501);assert.equal(inventoryAfter.productsWithCurrentPublishedPrices,inventoryBefore.productsWithCurrentPublishedPrices,"ALDI native SKUs without GTIN cannot inflate exact-product union");assert(inventoryAfter.scopeChannels.includes("assortment-publication"));
  const weightTx=await pool.connect();try{
   await weightTx.query("BEGIN");for(const [pack,variant,amount] of [["z. B. 770 g","fixed native variant",770],["770 g","Frisch; ausgenommen; mit Kopf; verschiedene Gewichte",770],["1.000-g-Packung","fixed native variant",1]]){await weightTx.query(`UPDATE ${Service.TABLE} SET pack=$2,pack_amount=$4,pack_unit='g',variant=$3 WHERE retailer_sku=$1`,[fixtures[0].retailerSku,pack,variant,amount]);assert.equal((await Service.search(weightTx,{retailerSku:fixtures[0].retailerSku,now})).items.length,0,"Actual SQL legacy uncertain weights or thousand-grouping errors are excluded by read validation");assert.equal((await weightTx.query(`SELECT pack FROM ${Service.TABLE} WHERE retailer_sku=$1`,[fixtures[0].retailerSku])).rows[0].pack,pack,"Read validation preserves the original stored evidence");}
   const grouped=fixture(97000,{pack:"1.000-g-Packung",packAmount:1000,packUnit:"g"});assert.equal((await Service.persist(weightTx,[grouped],{now})).accepted,1);let groupedResult=await Service.search(weightTx,{retailerSku:grouped.retailerSku,pack:"1 kg",now});assert.equal(groupedResult.items.length,1);assert.equal(groupedResult.items[0].packAmount,1000);assert.equal((await Service.search(weightTx,{retailerSku:grouped.retailerSku,pack:"1 g",now})).items.length,0);
   const originalGrouped=(await weightTx.query(`SELECT captured_at,source_response_hash,price FROM ${Service.TABLE} WHERE retailer_sku=$1`,[grouped.retailerSku])).rows[0];await weightTx.query(`UPDATE ${Service.TABLE} SET pack_amount=1 WHERE retailer_sku=$1`,[grouped.retailerSku]);assert.equal((await Service.search(weightTx,{retailerSku:grouped.retailerSku,now})).items.length,0);assert.deepEqual((await weightTx.query(`SELECT captured_at,source_response_hash,price FROM ${Service.TABLE} WHERE retailer_sku=$1`,[grouped.retailerSku])).rows[0],originalGrouped,"Legacy metadata rejection cannot retime, rewrite prices or replace original source proof");
  }finally{await weightTx.query("ROLLBACK");Schema.reset(weightTx,Service.TABLE);weightTx.release();}assert.equal((await Service.search(pool,{retailerSku:fixtures[0].retailerSku,now})).items.length,1,"The rollback restores the genuine fixed-pack fixture");
  assert.equal((await Service.persist(pool,fixtures,{now})).unchanged,501);
  assert.equal((await Service.persist(pool,[fixture(0,{price:1.59})],{now})).rejected,1,"Contradictory equal-time native price cannot overwrite stored evidence");
  const updated=fixture(0,{price:1.39,capturedAt:new Date(now).toISOString(),sourceResponseDate:new Date(now).toISOString(),sourceResponseHash:"e".repeat(64),proofHash:"f".repeat(64)});assert.equal((await Service.persist(pool,[updated],{now})).upserted,1);assert.equal((await Service.persist(pool,[fixture(0)],{now})).unchanged,1);
  let result=await Service.search(pool,{retailerSku:updated.retailerSku,now});assert.equal(result.items.length,1);const selected=result.items[0];assert.equal(selected.price,1.39);assert.equal(selected.gtin,null);assert.equal(selected.identityStatus,"native-retailer-sku");assert.equal(selected.scopeChannel,"assortment-publication");assert.equal(selected.locationScope,"unknown");assert.equal(selected.truthEligible,false);assert.equal(selected.physicalStorePriceVerified,false);assert.equal(selected.priceType,"unknown");assert.equal(selected.regularPrice,null);assert.equal(selected.shippingIncluded,false);assert.equal(selected.serviceFeesIncluded,false);assert.equal(selected.payablePackPrice,1.39);assert(!("storeId"in selected));assert(!("canonicalProductId"in selected));assert.equal(Date.parse(selected.expiresAt),now+Service.DAY_MS);
  assert.equal((await Service.search(pool,{gtin:gtin(0),now})).items.length,0,"Unattested GTIN is never guessed from a product name");assert.equal((await Service.search(pool,{merchant:"REWE",now})).items.length,0);assert.equal((await Service.search(pool,{search:"product 500",now})).items.length,1);assert.equal((await Service.search(pool,{search:"product%_",now})).items.length,0);assert.equal((await Service.search(pool,{limit:999,now})).items.length,200);
  const oldCapture=new Date(now-Service.DAY_MS-1).toISOString(),expired=fixture(501,{capturedAt:oldCapture,sourceResponseDate:oldCapture,nativeValidFrom:new Date(now-2*Service.DAY_MS).toISOString()});assert.equal((await Service.persist(pool,[expired],{now})).upserted,1);assert.equal((await Service.search(pool,{retailerSku:expired.retailerSku,now})).items.length,0);
  const nativeDeadline=now+3600000,short=fixture(502,{nativeValidUntil:new Date(nativeDeadline).toISOString()});assert.equal((await Service.persist(pool,[short],{now})).upserted,1);result=await Service.search(pool,{retailerSku:short.retailerSku,now});assert.equal(result.items.length,1);assert.equal(Date.parse(result.items[0].expiresAt),nativeDeadline,"Native price validity wins over a supplied longer expiry");assert.equal((await Service.search(pool,{retailerSku:short.retailerSku,now:nativeDeadline+1})).items.length,0);
  const unknownDeposit=fixture(503,{deposit:null,depositIncluded:null});assert.equal((await Service.persist(pool,[unknownDeposit],{now})).upserted,1);assert.equal((await Service.search(pool,{retailerSku:unknownDeposit.retailerSku,now})).items[0].payablePackPrice,null);
  const conflict=await Service.persist(pool,[fixture(504),fixture(504,{price:1.59})],{now});assert.equal(conflict.accepted,0);assert.equal(conflict.rejected,2);assert.equal((await Service.search(pool,{retailerSku:fixture(504).retailerSku,now})).items.length,0);
  const invalid=await Service.persist(pool,[fixture(510,{gtin:gtin(510)}),fixture(511,{storeId:"imaginary",scopeChannel:"store"}),fixture(512,{scopeCountry:"AT"}),fixture(513,{regularPrice:1.69,priceType:"regular"}),fixture(514,{availability:"available"}),fixture(515,{deposit:.25}),fixture(516,{sourceResponseDate:new Date(now-400000).toISOString()}),fixture(517,{sourceAgeSeconds:301}),fixture(518,{packAmount:2}),fixture(519,{capturedAt:new Date(now+1).toISOString()}),fixture(520,{nativeValidUntil:new Date(now-2000).toISOString()}),fixture(521,{price:1.299}),fixture(522,{sourceResponseUrl:"https://unapproved.example/test"})],{now});assert.equal(invalid.accepted,0);assert.equal(invalid.rejected,13);
  for(const update of["gtin='3017620422003'","scope_channel='store'","expires_at=captured_at+interval '25 hours'","source_response_date=captured_at-interval '6 minutes'"]){await assert.rejects(()=>pool.query(`UPDATE ${Service.TABLE} SET ${update} WHERE retailer_sku=$1`,[updated.retailerSku]),error=>error.code==="23514","Database constraints must reject inadmissible identities/scopes/expiry/freshness even outside the JS validator");}
  await assert.rejects(()=>pool.query(`UPDATE ${Service.TABLE} SET expires_at=native_valid_until+interval '1 minute' WHERE retailer_sku=$1`,[short.retailerSku]),error=>error.code==="23514","Expiry within 24 hours must still respect its earlier native deadline");
  let status=await Service.status(pool,{now});assert.equal(status.storedPrices,504);assert.equal(status.currentPrices,503);assert.equal(status.productsWithCurrentPublishedPrices,0);assert.equal(status.availableCurrentPrices,0);assert.equal(status.physicalStorePriceVerified,false);assert.equal(status.normalPriceClassificationVerified,false);assert.equal(status.independentOfUserReceipts,true);assert.equal(status.scopeChannel,"assortment-publication");
  // Fresh timestamps below describe synthetic SQL fixtures only. Original byte
  // fixtures are unchanged; no archived capture is imported into production.
  function depositFixture(name){
   const original=fs.readFileSync(path.join(__dirname,"fixtures/retailers/aldi-deposit",name+".html"),"utf8"),response=JSON.parse(fs.readFileSync(path.join(__dirname,"fixtures/retailers/aldi-deposit",name+"-response.json"),"utf8"));assert.equal(crypto.createHash("sha256").update(original).digest("hex"),response.sourceResponseHash);
   const marker=/<script id="__NEXT_DATA__" type="application\/json">([\s\S]*?)<\/script>/,match=original.match(marker);assert(match);const outer=JSON.parse(match[1]);outer.props.pageProps.syntheticSqlDepositFixture=true;
   const raw=original.replace(marker,'<script id="__NEXT_DATA__" type="application/json">'+JSON.stringify(outer)+'<\/script>'),capturedAt=new Date(now-1000).toISOString(),meta={...response,raw,capturedAt,sourceResponseHash:crypto.createHash("sha256").update(raw).digest("hex"),sourceResponseDate:capturedAt,sourceAgeSeconds:0};assert.notEqual(meta.sourceResponseHash,response.sourceResponseHash);
   const product=Client.extractProducts(raw).products[0],parsed=Client.parseProduct(product,meta);assert(parsed.offer,JSON.stringify(parsed));assert.equal(DepositProof.validateProof(parsed.offer),true);return parsed.offer;
  }
  const depositTx=await pool.connect();let depositGroups=0;try{
   await depositTx.query("BEGIN");
   const before=(await depositTx.query(`SELECT count(*)::int AS total,sum(price) AS prices,max(captured_at) AS captured FROM ${Service.TABLE}`)).rows[0];
   // Recreate the previous released zero-only schema in this rollback-only
   // transaction, then run the real additive migration over its existing rows.
   await depositTx.query(`ALTER TABLE ${Service.TABLE} DROP CONSTRAINT aldi_assortment_deposit_proof_check;ALTER TABLE ${Service.TABLE} DROP COLUMN deposit_basis_proof;ALTER TABLE ${Service.TABLE} ADD CONSTRAINT aldi_assortment_published_prices_deposit_check CHECK(deposit=0)`);
   assert.equal((await depositTx.query("SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name=$1 AND column_name='deposit_basis_proof'",[Service.TABLE])).rowCount,0);
   await Service.ensure(depositTx);
   assert.equal((await depositTx.query("SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name=$1 AND column_name='deposit_basis_proof' AND data_type='jsonb'",[Service.TABLE])).rowCount,1);
   assert.deepEqual((await depositTx.query(`SELECT count(*)::int AS total,sum(price) AS prices,max(captured_at) AS captured FROM ${Service.TABLE}`)).rows[0],before,"Migration retains every historical price and original timestamp");
   assert.equal((await depositTx.query("SELECT conname FROM pg_constraint WHERE conrelid=$1::regclass AND conname='aldi_assortment_published_prices_deposit_check'",[Service.TABLE])).rowCount,0);depositGroups++;
   const water=depositFixture("classic-1026202"),cola=depositFixture("original-taste-4039"),input=[water,cola],saved=await Service.persist(depositTx,input,{now});assert.equal(saved.accepted,2);assert.equal(saved.upserted,2);depositGroups++;
   const stored=(await depositTx.query(`SELECT deposit::float,pack_count,deposit_basis_proof AS proof,source_response_hash,captured_at,expires_at FROM ${Service.TABLE} WHERE retailer_sku=$1`,[water.retailerSku])).rows[0];assert.equal(stored.deposit,2.25);assert.equal(stored.pack_count,9);assert.deepEqual(stored.proof,water.depositBasisProof);assert.equal(stored.source_response_hash,water.sourceResponseHash);assert.equal(new Date(stored.captured_at).toISOString(),water.capturedAt);assert.equal(new Date(stored.expires_at).getTime(),Date.parse(water.capturedAt)+Service.DAY_MS);depositGroups++;
   const found=(await Service.search(depositTx,{retailerSku:water.retailerSku,pack:"9 x 500 ml",now})).items;assert.equal(found.length,1);assert.equal(found[0].price,1.35);assert.equal(found[0].deposit,2.25);assert.equal(found[0].depositIncluded,false);assert.equal(found[0].payablePackPrice,3.60,"Native total-pack deposit must not be multiplied by its nine bottles");assert.equal(found[0].packCount,9);assert.equal(found[0].packAmount,500);assert.equal(DepositProof.validateProof(found[0]),true);assert.equal(found[0].gtin,null);assert.equal(found[0].locationScope,"unknown");assert.equal(found[0].physicalStorePriceVerified,false);assert.equal(found[0].priceType,"unknown");depositGroups++;
   assert.equal((await Service.search(depositTx,{retailerSku:water.retailerSku,pack:"4.5 l",now})).items.length,0,"Matching total volume cannot replace an exact nine-bottle sales pack");assert.equal((await Service.search(depositTx,{retailerSku:cola.retailerSku,now})).items[0].payablePackPrice,1.84);assert.equal((await Service.persist(depositTx,found,{now})).unchanged,1,"A PostgreSQL JSONB roundtrip keeps duplicate capture idempotency");depositGroups++;
   assert.equal((await Service.persist(depositTx,[{...water,depositBasisProof:{...water.depositBasisProof,depositCents:25}}],{now})).accepted,0);depositGroups++;
   for(const [name,sql,params] of[
    ["missing proof","deposit_basis_proof=NULL",[]],
    ["empty proof","deposit_basis_proof='{}'::jsonb",[]],
    ["nonobject proof","deposit_basis_proof='[]'::jsonb",[]],
    ["changed native pfand","deposit=0.25",[]],
    ["noncent pfand","deposit=2.251",[]],
    ["negative pfand","deposit=-0.25",[]],
    ["excessive pfand","deposit=10000.01",[]],
    ["NaN pfand","deposit='NaN'::numeric",[]],
    ["infinite pfand","deposit='Infinity'::numeric",[]],
    ["negative infinite pfand","deposit='-Infinity'::numeric",[]],
    ["wrong SKU","deposit_basis_proof=jsonb_set(deposit_basis_proof,'{retailerSku}',to_jsonb('4039'::text))",[]],
    ["wrong original hash","deposit_basis_proof=jsonb_set(deposit_basis_proof,'{sourceResponseHash}',to_jsonb(repeat('0',64)))",[]],
    ["wrong capture","deposit_basis_proof=jsonb_set(deposit_basis_proof,'{capturedAt}',to_jsonb('2020-01-01T00:00:00.000Z'::text))",[]],
    ["wrong salespack","deposit_basis_proof=jsonb_set(deposit_basis_proof,'{pack}',to_jsonb('4.5 l'::text))",[]],
    ["unknown proof version","deposit_basis_proof=jsonb_set(deposit_basis_proof,'{version}','2'::jsonb)",[]],
    ["included pfand","deposit_basis_proof=jsonb_set(deposit_basis_proof,'{depositPriceBasis}',to_jsonb('included'::text))",[]],
    ["per-bottle pfand","deposit_basis_proof=jsonb_set(deposit_basis_proof,'{depositAmountBasis}',to_jsonb('per-container'::text))",[]],
    ["unknown renderer manifest","deposit_basis_proof=jsonb_set(deposit_basis_proof,'{rendererManifestHash}',to_jsonb(repeat('0',64)))",[]],
    ["extraneous authority","deposit_basis_proof=deposit_basis_proof||'{\"currentBerlinShelf\":true}'::jsonb",[]]
   ]){await depositTx.query("SAVEPOINT rejected_deposit");await assert.rejects(()=>depositTx.query(`UPDATE ${Service.TABLE} SET ${sql} WHERE retailer_sku=$1`,[water.retailerSku,...params]),error=>error.code==="23514",name);await depositTx.query("ROLLBACK TO SAVEPOINT rejected_deposit");depositGroups++;}
   // The SQL boundary authenticates the closed shape and row bindings. Reads
   // additionally verify the ordered proof hash instead of trusting JSONB.
   await depositTx.query("SAVEPOINT bad_proof_hash");await depositTx.query(`UPDATE ${Service.TABLE} SET deposit_basis_proof=jsonb_set(deposit_basis_proof,'{proofHash}',to_jsonb(repeat('0',64))) WHERE retailer_sku=$1`,[water.retailerSku]);assert.equal((await Service.search(depositTx,{retailerSku:water.retailerSku,now})).items.length,0);await depositTx.query("ROLLBACK TO SAVEPOINT bad_proof_hash");depositGroups++;
   await depositTx.query("SAVEPOINT shorter_native_expiry");const shorterExpiry=new Date(now+60000).toISOString();await depositTx.query(`UPDATE ${Service.TABLE} SET expires_at=$2::timestamptz WHERE retailer_sku=$1`,[water.retailerSku,shorterExpiry]);assert.equal((await Service.search(depositTx,{retailerSku:water.retailerSku,now})).items[0].expiresAt,shorterExpiry,"The actual DTO preserves a shorter SQL deadline instead of recalculating a longer TTL");await depositTx.query("ROLLBACK TO SAVEPOINT shorter_native_expiry");depositGroups++;
   assert.equal((await Service.search(depositTx,{retailerSku:water.retailerSku,now:Date.parse(water.expiresAt)+1})).items.length,0);depositGroups++;
  }finally{await depositTx.query("ROLLBACK");Schema.reset(depositTx,Service.TABLE);depositTx.release();}
  assert.deepEqual(await Service.status(pool,{now}),status,"Rollback-only migration and positive-pfand cases leave the original coverage baseline unchanged");assert.equal((await Service.search(pool,{retailerSku:"1026202",now})).items.length,0);depositGroups++;
  // Schema setup finishes outside the rollback-only fixture; article+checkpoint
  // writes below still share each actual PostgreSQL SAVEPOINT transaction scope.
  await Articles.ensure(pool);await Refresh.ensure(pool);
  const originalArticles=(await pool.query(`SELECT count(*)::int AS total FROM ${Articles.TABLE}`)).rows[0].total,originalCheckpoint=JSON.stringify((await pool.query(`SELECT * FROM ${Refresh.TABLE} WHERE source_id=$1`,[Service.SOURCE])).rows);
  // Exercise the actual persistent cursor SQL and admission writes together in a rollback-only transaction.
  const checkpoint=await pool.connect(),refreshPool=rollbackRefreshPool(checkpoint);try{
   await checkpoint.query("BEGIN");await Refresh.ensure(checkpoint);await checkpoint.query("ALTER TABLE aldi_assortment_catalog_state DROP COLUMN price_refresh_state");await Refresh.ensure(checkpoint);assert((await checkpoint.query("SELECT 1 FROM information_schema.columns WHERE table_name='aldi_assortment_catalog_state' AND column_name='price_refresh_state'")).rowCount===1,"Existing catalog tables receive the additive regular-refresh state column");await checkpoint.query("DELETE FROM aldi_assortment_catalog_state WHERE source_id=$1",[Service.SOURCE]);
   const offers=[8000,8001,8002].map(index=>fixture(index,{capturedAt:new Date(now).toISOString(),sourceResponseDate:new Date(now).toISOString()})),targets=offers.map(row=>({retailerSku:row.retailerSku,sourceUrl:row.sourceUrl})),hash=Client.stableTargets(targets).snapshotHash,discovery={targets,snapshotHash:hash,requests:1,bytes:100},cursor={snapshotHash:hash,nextIndex:1,lastSku:targets[0].retailerSku,unresolvedTargets:[]};
   const confirmed=(target,at=now)=>({...target,status:200,kind:"detail",capturedAt:new Date(at).toISOString(),sourceResponseHash:"c".repeat(64),sourceResponseDate:new Date(at).toISOString(),sourceAgeSeconds:0});
   const identity=offer=>({sourceId:Service.SOURCE,merchant:"ALDI Nord",purpose:"identity",identityScope:"retailer-sku",retailerSku:offer.retailerSku,gtin:null,storeId:null,name:offer.name,brand:offer.brand,variant:offer.variant,pack:offer.pack,packAmount:offer.packAmount,packUnit:offer.packUnit,packCount:offer.packCount,sourceUrl:offer.sourceUrl,observedAt:offer.capturedAt,sourceResponseHash:offer.sourceResponseHash,sourceResponseDate:offer.sourceResponseDate,sourceAgeSeconds:offer.sourceAgeSeconds,scopeCountry:"DE",scopeChannel:"assortment-publication",locationScope:"unknown",truthEligible:false,publicationAvailable:offer.publicationAvailable});
   const first={offers:[offers[0]],products:[identity(offers[0])],rejected:[],processed:1,requests:1,bytes:100,complete:false,partialError:null,cursor,cursorReset:false,targetCount:3,snapshotHash:hash,nextIndex:1,unresolvedTargets:[],gapAttempts:0,deferredUntil:null,confirmedTargets:[confirmed(targets[0])]};
   assert.equal(Articles.validateArticle(first.products[0],{now}).ok,true,"Explicit identity fixture obeys the real native article contract");
   const firstSaved=await Refresh.refresh({pool:refreshPool,maxRequests:2,now:()=>now},{discoverTargets:async()=>discovery,fetchProducts:async()=>first});assert.equal(firstSaved.accepted,1);assert.equal(firstSaved.nativeArticlesCounts.accepted,1);assert.equal(firstSaved.nativeArticlesCounts.rejected,0);assert.equal(firstSaved.nativeArticlesCounts.priceRowsCreated,0);assert.equal((await Articles.search(checkpoint,{retailerSku:offers[0].retailerSku,now})).items.length,1);let state=await Refresh.load(checkpoint);assert.deepEqual(state.cursor,cursor);assert.equal(state.nextIndex,1);assert.equal(state.processedCumulative,1);assert.equal((await Refresh.status(checkpoint)).publishedAssortmentComplete,false);assert.equal(await Refresh.resumeAt(checkpoint,now),new Date(now+60000).toISOString());
   const second={...first,offers:[offers[1]],products:[identity(offers[1])],nextIndex:2,confirmedTargets:[confirmed(targets[1])],cursor:{...cursor,nextIndex:2,lastSku:targets[1].retailerSku}};
   await assert.rejects(()=>Refresh.refresh({pool:refreshPool,now:()=>now},{discoverTargets:async()=>discovery,fetchProducts:async()=>second,persist:async()=>{throw Error("POSTGRES TEST admission failed");}}),/admission failed/);state=await Refresh.load(checkpoint);assert.deepEqual(state.cursor,cursor);assert.equal(state.nextIndex,1);
   await assert.rejects(()=>Refresh.refresh({pool:refreshPool,now:()=>now},{discoverTargets:async()=>discovery,fetchProducts:async()=>({...second,requests:2,partialError:{code:"aldi-source-http-429",status:429,retryAfterMs:7200000,requestStarted:true,retryingGap:false,...targets[2]}})}),error=>error.code==="aldi-source-http-429"&&error.accepted===1&&error.checkpointSaved===true);state=await Refresh.load(checkpoint);assert.equal(state.nextIndex,2);assert.equal(state.lastError,"aldi-source-http-429");assert.equal(new Date(state.retryAfter).getTime(),now+7200000);assert.equal((await Service.search(checkpoint,{retailerSku:offers[1].retailerSku,now})).items.length,1,"Native quote before denial survives its failed scheduler run");assert.equal(state.completedCycles,0);
   assert.equal((await Refresh.refresh({pool:refreshPool,now:()=>now+60000},{discoverTargets:async()=>{throw Error("Cooldown must prevent a network read");}})).skipped,"source-cooldown");
   const later=offer=>({...offer,capturedAt:new Date(now+7200000).toISOString(),sourceResponseDate:new Date(now+7200000).toISOString()});
   const last={...first,offers:[later(offers[2])],products:[identity(later(offers[2]))],nextIndex:3,confirmedTargets:[confirmed(targets[2],now+7200000)],cursor:null,complete:true};await Refresh.refresh({pool:refreshPool,now:()=>now+7200000},{discoverTargets:async()=>discovery,fetchProducts:async()=>last});state=await Refresh.status(checkpoint);assert.equal(state.publishedAssortmentComplete,true);assert.equal(state.completedCycles,1);assert.equal(state.cursor,null);assert.equal(state.nextIndex,3);assert.equal(state.lastError,null);assert.equal(state.retryAfter,null);
   const newTargets=[...targets,{retailerSku:fixture(8003).retailerSku,sourceUrl:fixture(8003).sourceUrl}],newHash=Client.stableTargets(newTargets).snapshotHash,newBatch={...first,offers:[later(offers[0])],products:[identity(later(offers[0]))],confirmedTargets:[confirmed(targets[0],now+7200000)],cursor:{snapshotHash:newHash,nextIndex:1,lastSku:targets[0].retailerSku,unresolvedTargets:[]},snapshotHash:newHash,targetCount:4,cursorReset:false};
   // A completed cycle has no continuation cursor: its next scan naturally starts at zero.
   await Refresh.refresh({pool:refreshPool,now:()=>now+7200000},{discoverTargets:async()=>({...discovery,targets:newTargets,snapshotHash:newHash}),fetchProducts:async()=>newBatch});state=await Refresh.status(checkpoint);assert.equal(state.publishedAssortmentComplete,false);assert.equal(state.completedCycles,1);assert.equal(state.nextIndex,1);assert.equal(new Date(state.lastCompletedAt).getTime(),now+7200000);
   // Real client responses and SQL checkpoints: one native error cannot pin the remaining catalog.
   await checkpoint.query("DELETE FROM aldi_assortment_catalog_state WHERE source_id=$1",[Service.SOURCE]);
   const nativeTargets=Client.stableTargets([9000,9001,9002].map(index=>fixture(index).sourceUrl));let activeNativeTargets=nativeTargets,nativeDiscovery={...nativeTargets,requests:1,bytes:100};
   let clock=now,mode="unavailable",nativeReads=0,nativeBudget=2;const nativeReadLog=[];
   const unavailable='<script id="__NEXT_DATA__">'+JSON.stringify({props:{pageProps:{hasError:true,apiData:null}}})+'</script>';
   const nativeFetch=async url=>{
    nativeReads++;nativeReadLog.push({url,clock});const target=Client.targetForUrl(url),f=fixture(Number(target.retailerSku)-960000000),blocked=target.retailerSku===activeNativeTargets.targets[0].retailerSku;
    if(blocked&&mode==="denied")return{status:429,headers:{get:key=>key==="retry-after"?"7200":null}};
    const raw={objectID:target.retailerSku,name:f.name,shortDescription:"fixed native variant",productSlug:target.sourceUrl.split("/").at(-1).replace(/\.html$/,""),brandName:f.brand,salesUnit:"1-Liter-Packung",isAvailable:true,isComingSoon:false,isRecall:false,isDepositProduct:false,depositValue:0,currentPrice:{priceValue:1.29,validFrom:Math.floor(now/1000)-86400,validUntil:Math.floor(now/1000)+864000}};
    if(blocked&&mode==="identity-conflict")raw.objectID="1";
    const body=blocked&&mode==="unavailable"?unavailable:'<script id="__NEXT_DATA__">'+JSON.stringify({props:{pageProps:{apiData:[["PRODUCT_DETAIL_GET",{req:{productIds:[target.retailerSku]},res:{products:[raw]}}]]}}})+'</script>';
    return{status:200,headers:{get:key=>key==="date"?new Date(clock).toUTCString():null},text:async()=>body};
   };
   const nativeDeps={discoverTargets:async()=>nativeDiscovery,fetchProducts:(targets,options)=>Client.fetchProducts(targets,{...options,fetchImpl:nativeFetch,sleep:async()=>{}})};
   const nativeRun=()=>Refresh.refresh({pool:refreshPool,maxRequests:nativeBudget,now:()=>clock},nativeDeps);
   async function prepareDueGap(){const current=await Refresh.load(checkpoint),refresh=current.priceRefreshState,ready=refresh&&(refresh.passStartedAt||Date.parse(refresh.nextPassAt)<=clock);if(ready&&refresh.lastRunKind!=="price-refresh"){const pass=await nativeRun();assert.equal(pass.runKind,"price-refresh");clock+=60000;}}
   async function nativeGapRun(){await prepareDueGap();const result=await nativeRun();assert.equal(result.runKind,"gap-retry");return result;}
   let gapResult=await nativeRun();assert.equal(gapResult.accepted,0);state=await Refresh.status(checkpoint);assert.equal(state.nextIndex,1);assert.equal(state.processedCumulative,0);assert.equal(state.unresolvedCount,1);assert.equal(state.lastError,null);assert.equal(state.publishedAssortmentComplete,false);
   const gap=state.cursor.unresolvedTargets[0];assert.equal(gap.retailerSku,nativeTargets.targets[0].retailerSku);assert.equal(gap.sourceUrl,nativeTargets.targets[0].sourceUrl);assert.match(gap.sourceResponseHash,/^[a-f0-9]{64}$/);assert.equal(gap.attempts,1);assert.equal(Date.parse(gap.retryAfter),clock+3600000);
   // Independent reloads use the persisted JSONB cursor, including the failed SKU and its retry time.
   for(let step=1;step<=2;step++){clock=now+step*60000;gapResult=await nativeRun();assert.equal(gapResult.accepted,1);state=await Refresh.status(checkpoint);assert.equal(state.nextIndex,step+1);assert.equal(state.processedCumulative,step);assert.equal(state.unresolvedCount,1);assert.equal(state.publishedAssortmentComplete,false);assert.equal(state.completedCycles,0);}
   assert.equal(state.nextIndex,3);assert.equal(state.cursor.unresolvedTargets[0].attempts,1);assert.equal(await Refresh.resumeAt(checkpoint,clock),state.priceRefreshState.nextPassAt);
   const readsBeforeWaiting=nativeReads;clock=now+180000;gapResult=await nativeRun();assert.equal(nativeReads,readsBeforeWaiting,"Neither an article retry nor a pending regular-pass deadline requests a product URL");assert.equal(gapResult.nextAttemptAt,state.priceRefreshState.nextPassAt);assert.equal((await Refresh.status(checkpoint)).publishedAssortmentComplete,false);
   clock=Date.parse(gap.retryAfter);gapResult=await nativeGapRun();state=await Refresh.status(checkpoint);assert.equal(state.cursor.unresolvedTargets[0].attempts,2);assert.equal(state.unresolvedCount,1);assert.equal(state.processedCumulative,2);assert.equal(state.publishedAssortmentComplete,false);assert.equal(gapResult.accepted,0);
   clock=Date.parse(state.cursor.unresolvedTargets[0].retryAfter);mode="identity-conflict";await nativeGapRun();state=await Refresh.status(checkpoint);assert.equal(state.unresolvedCount,1,"A different native product cannot resolve the failed SKU");assert.equal(state.processedCumulative,2);assert.equal(state.publishedAssortmentComplete,false);
   clock=Date.parse(state.cursor.unresolvedTargets[0].retryAfter);mode="denied";const beforeDenial=structuredClone(state.cursor);await assert.rejects(nativeGapRun,error=>error.code==="aldi-source-http-429");state=await Refresh.status(checkpoint);assert.deepEqual(state.cursor,beforeDenial);assert.equal(state.unresolvedCount,1);assert.equal(new Date(state.retryAfter).getTime(),clock+7200000);
   const readsBeforeDenialWait=nativeReads;clock+=60000;assert.equal((await nativeRun()).skipped,"source-cooldown");assert.equal(nativeReads,readsBeforeDenialWait);
   clock=new Date(state.retryAfter).getTime();mode="valid";await prepareDueGap();const beforeFailedAdmission=await Refresh.load(checkpoint);await assert.rejects(()=>Refresh.refresh({pool:refreshPool,maxRequests:2,now:()=>clock},{...nativeDeps,persist:async()=>{throw Error("POSTGRES TEST recovered quote admission failed");}}),/recovered quote admission failed/);assert.deepEqual(await Refresh.load(checkpoint),beforeFailedAdmission,"A recovered article remains unresolved until its new quote has been saved");
   gapResult=await nativeGapRun();state=await Refresh.status(checkpoint);assert.equal(gapResult.accepted,1);assert.equal(state.cursor,null);assert.equal(state.unresolvedCount,0);assert.equal(state.nextIndex,3);assert.equal(state.processedCumulative,3);assert.equal(state.completedCycles,1);assert.equal(state.publishedAssortmentComplete,true);assert.equal(state.lastError,null);assert.equal(state.retryAfter,null);
   assert.equal((await Service.search(checkpoint,{retailerSku:nativeTargets.targets[0].retailerSku,now:clock})).items.length,1,"A recovered gap obtains a new native price, never a renewed error or cached fixture");
   // A permanent native gap must not prevent new successful captures beyond the original 24-hour TTL.
   await checkpoint.query("DELETE FROM aldi_assortment_catalog_state WHERE source_id=$1",[Service.SOURCE]);
   activeNativeTargets=Client.stableTargets([9100,9101,9102].map(index=>fixture(index).sourceUrl));nativeDiscovery={...activeNativeTargets,requests:1,bytes:100};clock=now;mode="unavailable";nativeBudget=4;
   let regular=await nativeRun();assert.equal(regular.accepted,2);state=await Refresh.load(checkpoint);assert.equal(state.cursor.unresolvedTargets.length,1);assert.equal(state.processedCumulative,2);assert.equal(state.priceRefreshState.nextIndex,0);assert.equal(state.priceRefreshState.completedPasses,0);
   const successfulTargets=activeNativeTargets.targets.slice(1),permanentGap=activeNativeTargets.targets[0];clock=now+25*3600000;nativeBudget=3;
   for(const target of successfulTargets)assert.equal((await Service.search(checkpoint,{retailerSku:target.retailerSku,now:clock})).items.length,0,"Unrefetched quotes really expire; a permanent gap must never renew their timestamp");
   regular=await nativeRun();assert.equal(regular.runKind,"price-refresh");assert.equal(regular.accepted,1);assert.equal(regular.requests,2,"The existing gap is skipped without a native GET; one sitemap and one good page are read");state=await Refresh.load(checkpoint);assert.equal(state.priceRefreshState.nextIndex,2);assert.equal(state.cursor.nextIndex,3);assert.equal(state.processedCumulative,2);assert.equal(state.cursor.unresolvedTargets[0].attempts,1);const firstPassStart=state.priceRefreshState.passStartedAt;assert.equal(Date.parse(firstPassStart),clock);
   const freshFirst=(await Service.search(checkpoint,{retailerSku:successfulTargets[0].retailerSku,now:clock})).items[0];assert.equal(Date.parse(freshFirst.capturedAt),clock);assert.equal(Date.parse(freshFirst.expiresAt),clock+Service.DAY_MS);
   clock+=60000;regular=await nativeRun();assert.equal(regular.runKind,"gap-retry","Ready refresh and ready gaps alternate instead of starving one another");state=await Refresh.load(checkpoint);assert.equal(state.priceRefreshState.nextIndex,2);assert.equal(state.priceRefreshState.passStartedAt,firstPassStart);assert.equal(state.cursor.unresolvedTargets[0].attempts,2);assert.equal(state.priceRefreshState.completedPasses,0);
   clock+=60000;regular=await nativeRun();assert.equal(regular.runKind,"price-refresh");assert.equal(regular.accepted,1);state=await Refresh.status(checkpoint);assert.equal(state.priceRefreshState.completedPasses,1);assert.equal(Date.parse(state.priceRefreshState.lastCompletedAt),clock);assert.equal(state.priceRefreshState.passStartedAt,null);assert.equal(state.unresolvedCount,1);assert.equal(state.publishedAssortmentComplete,false);assert.equal(state.completedCycles,0);assert.equal(state.lastCompletedAt,null);
   const freshSecond=(await Service.search(checkpoint,{retailerSku:successfulTargets[1].retailerSku,now:clock})).items[0];assert.equal(Date.parse(freshSecond.capturedAt),clock);assert.equal(freshSecond.gtin,null);assert.equal(freshSecond.physicalStorePriceVerified,false);assert.equal(await Refresh.resumeAt(checkpoint,clock),state.priceRefreshState.nextPassAt);
   const gapReadsBeforeSecondPass=nativeReadLog.filter(entry=>entry.url===permanentGap.sourceUrl).length;clock=Date.parse(state.priceRefreshState.nextPassAt);regular=await nativeRun();assert.equal(regular.runKind,"price-refresh");state=await Refresh.load(checkpoint);assert.equal(state.priceRefreshState.nextIndex,2);assert.equal(state.priceRefreshState.completedPasses,1);clock+=60000;regular=await nativeRun();assert.equal(regular.runKind,"price-refresh");state=await Refresh.status(checkpoint);assert.equal(state.priceRefreshState.completedPasses,2);assert.equal(state.unresolvedCount,1);assert.equal(state.completedCycles,0);assert.equal(state.publishedAssortmentComplete,false);assert.equal(nativeReadLog.filter(entry=>entry.url===permanentGap.sourceUrl).length,gapReadsBeforeSecondPass,"Regular refresh never bypasses the independent one-hour article retry deadline");
   for(const target of successfulTargets){const quote=(await Service.search(checkpoint,{retailerSku:target.retailerSku,now:clock})).items[0];assert(quote);assert(Date.parse(quote.capturedAt)>now+25*3600000);assert.equal(quote.gtin,null);}
   assert.equal(refreshPool.counts.connected,refreshPool.counts.released,"Every inner writing transaction is released without closing the outer actual client");assert(refreshPool.counts.connected>0);
  }finally{await checkpoint.query("ROLLBACK");Schema.reset(refreshPool,Service.TABLE);checkpoint.release();}
  assert.equal((await pool.query(`SELECT count(*)::int AS total FROM ${Articles.TABLE}`)).rows[0].total,originalArticles,"Rollback fixture preserves original native article rows");
  assert.equal(JSON.stringify((await pool.query(`SELECT * FROM ${Refresh.TABLE} WHERE source_id=$1`,[Service.SOURCE])).rows),originalCheckpoint,"Rollback fixture restores the pre-existing source checkpoint including original captures");
  assert.equal((await Service.search(pool,{now:now+Service.DAY_MS+1})).items.length,0);
  await pool.query(`UPDATE ${Service.TABLE} SET captured_at=$2::timestamptz,expires_at=$2::timestamptz+interval '24 hours',source_response_date=$2::timestamptz WHERE retailer_sku=$1`,[fixture(1).retailerSku,new Date(now+3600000).toISOString()]);assert.equal((await Service.search(pool,{retailerSku:fixture(1).retailerSku,now})).items.length,0,"Future stored captures are never current");
  process.env.PORT="0";api=require("../server");await new Promise((resolve,reject)=>{api.server.once("error",reject);api.server.listen(0,"127.0.0.1",()=>{api.server.off("error",reject);resolve();});});const base="http://127.0.0.1:"+api.server.address().port;
  async function get(url){const res=await fetch(base+url,{signal:AbortSignal.timeout(10000)});return{status:res.status,body:await res.json()};}
  const publicQuery=await get("/v1/published-prices?merchant=ALDI%20Nord&search="+encodeURIComponent("product 0"));assert.equal(publicQuery.status,200,JSON.stringify(publicQuery));assert.equal(publicQuery.body.items.length,1);assert.equal(publicQuery.body.items[0].price,1.39);assert.equal(publicQuery.body.items[0].scopeChannel,"assortment-publication");assert.equal(publicQuery.body.items[0].gtin,null);assert.equal(publicQuery.body.items[0].physicalStorePriceVerified,false);
  const publicStatus=await get("/v1/published-prices/status");assert.equal(publicStatus.status,200,JSON.stringify(publicStatus));assert.equal(publicStatus.body.retailers.aldiNordAssortment.productsWithCurrentPublishedPrices,0);assert.equal(publicStatus.body.retailers.aldiNordAssortment.currentPrices,502);assert.equal(publicStatus.body.retailerResearch.aldiNordAssortment.physicalStoreAssortmentVerified,false);assert.equal(publicStatus.body.retailerResearch.aldiNordAssortment.normalPriceClassificationVerified,false);assert.equal(publicStatus.body.retailerResearch.aldiNordAssortment.independentOfUserReceipts,true);
  const noExactMatch=await get("/v1/published-prices?merchant=ALDI%20Nord&gtin="+gtin(0));assert.equal(noExactMatch.status,200);assert.equal(noExactMatch.body.items.length,0);
  const comparedResponse=await fetch(base+"/v1/current-prices",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({gtin:gtin(0),pack:"1 l",merchants:["ALDI Nord"]}),signal:AbortSignal.timeout(10000)}),compared=await comparedResponse.json();assert.equal(comparedResponse.status,200,JSON.stringify(compared));assert(compared.results.every(row=>row.state==="unknown"&&row.price===null));assert(!compared.publishedAlternatives.some(row=>row.sourceId===Service.SOURCE),"An ALDI article name cannot answer an exact GTIN comparison");
  for(const[table,count]of Object.entries(baseline)){if(count===null)assert.equal(await exists(table),false,"Separate ALDI evidence must not create "+table);else assert.equal((await pool.query("SELECT count(*)::int AS count FROM "+table)).rows[0].count,count,"Separate ALDI evidence must not mutate "+table);}
  console.log("aldi-assortment-price-postgres: actual SQL migration/constraints, durable native gaps, fair regular-refresh/retry alternation, fresh captures beyond 24-hour expiry despite permanent gaps, multiple restart-safe refresh passes, global cooldown and unchanged physical/receipt ledgers OK ("+depositGroups+" deposit groups)");
 }finally{if(api){if(api.server.listening)await new Promise((resolve,reject)=>api.server.close(error=>error?reject(error):resolve()));await api.closeDb();}await pool.end();}
}
main().catch(error=>{console.error(error);process.exitCode=1;});
