"use strict";
const assert=require("node:assert/strict"),crypto=require("node:crypto"),Category=require("../aldi-assortment-category-client"),Service=require("../aldi-category-article-service"),Price=require("../aldi-assortment-price-service"),PdpArticle=require("../aldi-assortment-article-service");
const now=Date.parse("2026-10-03T03:00:00.500Z"),at=now-1000,url="https://www.aldi-nord.de/sortiment/milchprodukte/milch-milchgetraenke.html",clone=structuredClone,sha=b=>crypto.createHash("sha256").update(b).digest("hex");let groups=0;const check=fn=>{fn();groups++;};
// All bodies, clocks and HTTP metadata below are explicitly synthetic original test captures.
function product(sku="1018999",patch={}){return{objectID:sku,productSlug:"unit-test-milch-"+sku,name:"UNIT TEST Vollmilch",brandName:"MILSANI",shortDescription:"3,5 % Fett",salesUnit:"1-L-Packung",categoryIDs:["milch-milchgetraenke"],country:"DE",currentPrice:null,isAvailable:false,...patch};}
function capture(patch={},time=at,changeNative=()=>{},address=url){const categoryId=new URL(address).pathname.split("/").at(-1).replace(/\.html$/,""),categories=new URL(address).pathname.slice("/sortiment/".length).replace(/\.html$/,"").split("/"),hits=[product("1018999",{categoryIDs:[categoryId],...patch})],entry={state:{index:Category.INDEX,filters:"categoryIDs:"+categoryId,hitsPerPage:1000,numericRefinements:{},tagRefinements:[]},requestParams:[{filters:"categoryIDs:"+categoryId,hitsPerPage:1000}],results:[{hits,nbHits:1,nbPages:1,page:0,hitsPerPage:1000,index:Category.INDEX,query:"",params:new URLSearchParams({filters:"categoryIDs:"+categoryId,hitsPerPage:"1000"}).toString(),exhaustiveNbHits:true,exhaustive:{nbHits:true}}]},native={page:"/product-overview/[...categories]",query:{categories},props:{pageProps:{locale:"de",page:{"@path":"/germany"+new URL(address).pathname.replace(/\.html$/,""),categoryKey:categoryId},mgnlContext:{isMagnoliaEdit:false,isMagnoliaPreview:false},algoliaState:{initialResults:{[Category.INDEX]:entry}}}}};changeNative(native,entry);const body='<html><head><link rel="canonical" href="'+address+'"></head><body><script id="__NEXT_DATA__" type="application/json">'+JSON.stringify(native)+'</script></body></html>',stamp=new Date(time).toISOString(),original={body,meta:{sourceResponseUrl:address,sourceResponseHash:sha(body),capturedAt:stamp,sourceResponseDate:stamp,sourceAgeSeconds:0,scopeCountry:"DE"}},page=Category.parsePage(body,original.meta,{now:time+1000});return{native,entry,original,page,candidate:page.candidates[0]};}
function makePool(){const articles=new Map(),captures=new Map(),calls=[];let writes=0;const p={articles,captures,calls,connect(){},release(){},async query(sql,params=[]){calls.push({sql,params});if(sql.includes("txid_current_if_assigned"))return{rows:[{transactionOpen:true}]};if(sql.startsWith("CREATE TABLE")){writes++;return{rows:[]};}if(sql.startsWith("SELECT source_response_hash,body"))return{rows:captures.has(params[0])?[clone(captures.get(params[0]))]:[]};if(sql.startsWith("INSERT INTO "+Service.CAPTURE_TABLE)){if(!captures.has(params[0]))captures.set(params[0],{source_response_hash:params[0],body:params[1],body_bytes:params[2]});return{rows:[],rowCount:1};}if(sql.startsWith("SELECT retailer_sku"))return{rows:params[1].map(k=>articles.get(k)).filter(Boolean).map(v=>clone(v))};if(sql.startsWith("INSERT INTO "+Service.TABLE)){let count=0;for(const r of JSON.parse(params[0])){assert(captures.has(r.source_response_hash),"Article writes require original body first");const old=articles.get(r.retailer_sku);if(!old||r.observed_at>old.observed_at){articles.set(r.retailer_sku,clone(r));count++;}else if(r.observed_at===old.observed_at&&!old.held&&r.identity_hash!==old.identity_hash){old.held=true;old.conflict_capture=clone(r);old.conflict_response_hash=r.source_response_hash;count++;}}return{rows:[],rowCount:count};}if(sql.startsWith("SELECT count(*)")&&sql.includes(" FROM "+Service.CAPTURE_TABLE))return{rows:[{storedCaptureBodies:captures.size,storedCaptureBytes:[...captures.values()].reduce((n,c)=>n+c.body_bytes,0)}]};if(sql.startsWith("SELECT count(*)"))return{rows:[{count:params[1].filter(k=>articles.get(k)?.held).length}]};if(sql.startsWith("SELECT ")&&sql.includes(" FROM "+Service.TABLE)){const rows=[...articles.values()].map(v=>clone(v));return{rows:sql.includes(" LIMIT ")?rows.slice(Number(params.at(-1)),Number(params.at(-1))+Number(params.at(-2))):rows};}return{rows:[]};},ddlCount(){return writes;}};return p;}
async function persist(p,c,options={}){return Service.persist(p,c.page,{now,...options,original:c.original});}
async function main(){
 const c=capture(),valid=Service.validateArticle(c.candidate,{now,original:c.original});check(()=>{assert(valid.ok,JSON.stringify(valid));const a=valid.article;assert.equal(a.sourceId,Category.SOURCE);assert.equal(a.scopeChannel,"assortment-publication");assert.equal(a.originalCategoryResponseUrl,url);assert.equal(a.sourceResponseUrl,url);assert.equal(a.productIdentityUrl,c.candidate.identity.productIdentityUrl);assert.notEqual(a.sourceResponseUrl,a.productIdentityUrl);assert.equal(a.packAmount,1000);assert.equal(a.packUnit,"ml");assert.equal(a.gtin,null);assert.equal(a.shop,null);assert.equal(a.observedAt,new Date(at).toISOString());assert.equal(a.price,undefined);assert.equal(a.publicationAvailable,undefined);assert.equal(Price.validateOffer(a,{now}).ok,false);assert.equal(PdpArticle.validateArticle(a,{now}).ok,false);});
 for(const raw of[null,[],{},valid.article])check(()=>assert.equal(Service.validateArticle(raw,{now,original:c.original}).ok,false));
 check(()=>assert.equal(Service.validateArticle(c.candidate,{now}).ok,false,"Metadata/candidate alone cannot authorize admission"));
 for(const key of["sourceResponseUrl","sourceResponseHash","sourceResponseDate","sourceAgeSeconds","capturedAt"]){const original=clone(c.original);delete original.meta[key];check(()=>assert.equal(Service.validateArticle(c.candidate,{now,original}).ok,false,key));}
 for(const patch of[{sourceResponseHash:"0".repeat(64)},{scopeCountry:"AT"},{sourceResponseUrl:url+"?query=milk"},{capturedAt:new Date(now+1).toISOString()},{sourceAgeSeconds:301},{sourceResponseDate:new Date(at-300001).toISOString()}])check(()=>assert.equal(Service.validateArticle(c.candidate,{now,original:{...c.original,meta:{...c.original.meta,...patch}}}).ok,false,JSON.stringify(patch)));
 for(const mutate of[x=>x.identity.gtin="4046700026519",x=>x.identity.retailerSku="1019000",x=>x.identity.nativeSalesUnit="500 g",x=>x.identity.normalizedSalesPack.count=2,x=>x.identity.name="Another milk",x=>x.categoryProof.offlineOnly=true,x=>x.rawNativeProduct.currentPrice={priceValue:.95},x=>x.scopeCountry="AT",x=>x.truthEligible=true,x=>x.state="published"]){const candidate=clone(c.candidate);mutate(candidate);check(()=>assert.equal(Service.validateArticle(candidate,{now,original:c.original}).ok,false));}
 for(const mutate of[(n,e)=>n.query.query="milk",(n,e)=>e.state.filters="categoryIDs:butter",(n,e)=>e.results[0].page=1,(n,e)=>e.results[0].nbHits=2,(n,e)=>e.results[0].index="other",n=>n.props.pageProps.country="AT",n=>n.props.pageProps.page.categoryKey="other"]){const bad=clone(c.native);mutate(bad,bad.props.pageProps.algoliaState.initialResults[Category.INDEX]);const body=c.original.body.replace(JSON.stringify(c.native),JSON.stringify(bad));check(()=>assert.equal(Service.validateArticle(c.candidate,{now,original:{body,meta:{...c.original.meta,sourceResponseHash:sha(body)}}}).ok,false,"Malformed native route/filter/index/count proof"));}
 for(const patch of[{salesUnit:"z. B. 770 g"},{salesUnit:"1.000.5 g"},{salesUnit:"500–750 g"},{shortDescription:"verschiedene Gewichte"},{productSlug:"other-1019000"},{objectID:1018999},{categoryIDs:["butter"]}]){const bad=capture(patch);check(()=>{assert.equal(bad.page.candidates.length,0);assert.equal(bad.page.rejectedCount,1);});}
 for(const[pack,amount,unit,count]of[["1.000-g-Packung",1000,"g",1],["9x0,5-Liter-Flasche",500,"ml",9],["20x10-g-Packung",10,"g",20]]){const p=capture({salesUnit:pack}),a=Service.validateArticle(p.candidate,{now,original:p.original});check(()=>{assert(a.ok);assert.equal(a.article.pack,pack);assert.equal(a.article.packAmount,amount);assert.equal(a.article.packUnit,unit);assert.equal(a.article.packCount,count);});}
 const pool=makePool(),saved=await persist(pool,c);check(()=>{assert.equal(saved.accepted,1);assert.equal(saved.upserted,1);assert.equal(saved.priceRowsCreated,0);assert.equal(saved.canonicalProductsCreated,0);assert.equal(pool.captures.size,1);assert(!pool.calls.some(x=>/price_observations|INSERT INTO products/.test(x.sql)));assert(pool.calls.findIndex(x=>x.sql.startsWith("INSERT INTO "+Service.CAPTURE_TABLE))<pool.calls.findIndex(x=>x.sql.startsWith("INSERT INTO "+Service.TABLE)));});
 const replay=await persist(pool,c);check(()=>{assert.equal(replay.upserted,0);assert.equal(replay.unchanged,1);assert.equal(pool.captures.size,1);assert.equal(pool.articles.get("1018999").observed_at,new Date(at).toISOString());});
 const forgedPage=clone(c.page);forgedPage.candidates[0].identity.name="Forged";await assert.rejects(()=>Service.persist(pool,forgedPage,{now,original:c.original}),/page-original-conflict/);groups++;
 const retimed=clone(c.original);retimed.meta.capturedAt=new Date(at+100).toISOString();const retimedPage=Category.parsePage(retimed.body,retimed.meta,{now});const refused=await Service.persist(pool,retimedPage,{now,original:retimed});check(()=>{assert.equal(refused.accepted,0);assert.equal(refused.retimedReplays,1);assert.equal(pool.articles.get("1018999").observed_at,new Date(at).toISOString());});
 const newer=capture({},at+100),updated=await persist(pool,newer);check(()=>{assert.equal(updated.upserted,1);assert.equal(pool.captures.size,1,"Identical bytes with genuinely new HTTP Date reuse the original body");assert.equal(pool.articles.get("1018999").observed_at,new Date(at+100).toISOString());});
 const conflict=capture({salesUnit:"500 ml"},at+100),held=await persist(pool,conflict);check(()=>{assert.equal(held.heldArticles,1);assert.equal(held.accepted,0);assert.equal(pool.articles.get("1018999").held,true);assert(pool.captures.has(pool.articles.get("1018999").conflict_response_hash));});await persist(pool,newer);check(()=>assert.equal(pool.articles.get("1018999").held,true,"Replay cannot unblock a same-capture native conflict"));
 const recovery=capture({},at+200);await persist(pool,recovery);check(()=>assert.equal(pool.articles.get("1018999").held,false,"Only a newer genuine unique capture recovers identity"));
 const otherCategory=capture({categoryIDs:["butter"]},at+200,()=>{},"https://www.aldi-nord.de/sortiment/milchprodukte/butter.html");const overlap=await persist(pool,otherCategory);check(()=>{assert.equal(overlap.heldArticles,0,"Same identity in another native category must not become a fake conflict");assert.equal(overlap.upserted,0);});
 const view=(await Service.search(pool,{now})).items[0];check(()=>{assert(view);assert.equal(view.nativeProduct,undefined);assert.equal(view.body,undefined);assert.equal(view.storeId,undefined);assert.equal(view.price,undefined);assert.equal(view.state,"last-observed");assert.equal(view.gtin,null);assert.equal(view.shop,null);assert.equal(view.currentPriceVerified,false);assert.equal(view.currentAvailabilityVerified,false);assert.equal(view.availability,"unknown");assert.equal(view.expiresAt,null);assert(Service.validateView(view,{now}).ok);assert.equal(Service.validateArticle(view,{now}).ok,false);});
 for(const patch of[{scopeCountry:"AT"},{scopeChannel:"physical-store"},{locationScope:"Berlin"},{gtin:"4046700026519"},{shop:{city:"Berlin"}},{nativeMarketId:"123"},{price:1},{deposit:.25},{current:true},{normalPriceClassificationVerified:true},{currentPriceVerified:true},{availability:"available"},{expiresAt:new Date(now+86400000).toISOString()},{nativeProduct:c.candidate.rawNativeProduct},{captureHash:""}])check(()=>assert.equal(Service.validateView({...view,...patch},{now}).ok,false));
 const old=capture({},now-30*86400000),oldPool=makePool();await persist(oldPool,old,{now:now-30*86400000});const oldRead=await Service.search(oldPool,{now});check(()=>{assert.equal(oldRead.items.length,1);assert.equal(oldRead.items[0].observedAt,old.original.meta.capturedAt);assert.equal(oldRead.items[0].recentlyObserved,false);assert.equal(oldRead.items[0].currentPriceVerified,false);});
 const recorded=clone(pool.articles.get("1018999"));for(const mutate of[r=>r.pack="z. B. 770 g",r=>r.native_product.salesUnit="500 ml",r=>r.scope_country="AT",r=>r.category_response_url=url+"?q=milk",r=>r.source_response_date=new Date(at-400000).toISOString(),r=>r.pack_amount=1,r=>r.source_response_hash="a".repeat(64),r=>r.capture_hash="b".repeat(64)]){const r=clone(recorded);mutate(r);if(r.capture_hash===recorded.capture_hash){const a=Service.articleFor(recovery.candidate,recovery.page.categoryId);for(const[key,column]of Object.entries({pack:"pack",packAmount:"pack_amount",scopeCountry:"scope_country",nativeProduct:"native_product"}))a[key]=r[column];const hashes=Service.rowForArticle(a);r.witness_hash=hashes.witness_hash;r.identity_hash=hashes.identity_hash;r.capture_hash=hashes.capture_hash;}pool.articles.set(r.retailer_sku,r);assert.equal((await Service.search(pool,{now})).items.length,0);const s=await Service.status(pool,{now});check(()=>{assert.equal(s.storedArticles,1);assert.equal(s.excludedInvalidArticles,1);assert.equal(s.lastObservedArticles,0);assert.equal(s.lastObservedAt,null);});}pool.articles.set(recorded.retailer_sku,recorded);
 const originalBody=pool.captures.get(recorded.source_response_hash);pool.captures.set(recorded.source_response_hash,{...originalBody,body:originalBody.body+" ",body_bytes:originalBody.body_bytes+1});assert.equal((await Service.search(pool,{now})).items.length,0);groups++;const beforeWrites=pool.calls.filter(x=>x.sql.startsWith("INSERT INTO "+Service.TABLE)).length;await assert.rejects(()=>persist(pool,recovery),/stored-original-conflict/);check(()=>assert.equal(pool.calls.filter(x=>x.sql.startsWith("INSERT INTO "+Service.TABLE)).length,beforeWrites,"A corrupt reused capture cannot authorize any new article write"));pool.captures.set(recorded.source_response_hash,originalBody);
 const bom=clone(c.original);bom.body="\ufeff"+bom.body;bom.meta.sourceResponseHash=sha(bom.body);const bomPage=Category.parsePage(bom.body,bom.meta,{now}),bomPool=makePool();await Service.persist(bomPool,bomPage,{now,original:bom});check(()=>{assert.equal(bomPool.captures.get(bom.meta.sourceResponseHash).body,bom.body);assert.equal(bomPool.captures.get(bom.meta.sourceResponseHash).body_bytes,Buffer.byteLength(bom.body));});assert.equal((await Service.search(bomPool,{now})).items.length,1);groups++;
 for(const patch of[{extra:"x".repeat(17000)},{extra:"\u0000"},{extra:"\ud800"}]){const bounded=capture(patch);check(()=>assert.equal(Service.validateArticle(bounded.candidate,{now,original:bounded.original}).ok,false,"JSONB-bound native witness is checked before writes"));}
 const stats=await Service.status(pool,{now});check(()=>{assert.equal(stats.lastObservedArticles,1);assert.equal(stats.storedArticles,stats.lastObservedArticles+stats.heldArticles+stats.excludedInvalidArticles);assert.equal(stats.lastObservedAt,view.observedAt);assert.equal(stats.currentPriceVerified,false);});
 const aligned=await Service.readRows(pool,[recorded,{...recorded,held:true},{...recorded,capture_hash:"0".repeat(64)}],{now});check(()=>{assert.equal(aligned.length,3);assert.equal(aligned[0].retailerSku,recorded.retailer_sku);assert.equal(aligned[1],null);assert.equal(aligned[2],null);});await assert.rejects(()=>Service.readRows(pool,Array(50001).fill(recorded),{now}),/invalid-category-article-read-rows/);groups++;
 const malformedRead=await Service.readRows(pool,[null,[],{},recorded],{now});check(()=>{assert.deepEqual(malformedRead.slice(0,3),[null,null,null]);assert.equal(malformedRead[3].retailerSku,recorded.retailer_sku);});const nulOriginal=clone(c.original);nulOriginal.body+="\u0000";nulOriginal.meta.sourceResponseHash=sha(nulOriginal.body);check(()=>assert.equal(Service.validateArticle(c.candidate,{now,original:nulOriginal}).ok,false,"A PostgreSQL text original must preserve bytes and cannot contain NUL"));
 const q=Service.querySpec({search:"Milk%_",pack:"9 x 500 ml",offset:100,limit:200,now});check(()=>{assert(q.sql.includes("held=false"));assert(q.params.includes("%Milk\\%\\_%"));assert(q.params.includes(500));assert(q.params.includes(9));assert(!q.sql.includes("interval '24 hours'"));assert(Service.querySpec({scopeChannel:"pickup",now}).sql.includes("false"));assert(Service.querySpec({gtin:"4046700026519",now}).sql.includes("false"));});
 for(const options of[{limit:201},{limit:true},{limit:0},{offset:-1},{offset:100001},{search:""},{retailerSku:"01"},{gtin:"milk"},{pack:"ca. 1 kg"},{scopeChannel:"category-publication"},{categoryUrl:url+"?q=milk"},{future:true},{now:"2026-10-03"}])check(()=>assert.throws(()=>Service.querySpec(options),/invalid-|not-allowed/));
 const inherited=Object.create(require("pg").Client.prototype);inherited.release=()=>{};inherited.query=pool.query.bind(pool);assert.equal(typeof inherited.connect,"function");assert.equal(Object.hasOwn(inherited,"connect"),false);assert.equal((await persist(inherited,c)).received,1);groups++;
 await assert.rejects(()=>Service.persist({query:async()=>({rows:[]})},c.page,{now,original:c.original}),/transaction-client-required/);groups++;
 await assert.rejects(()=>Service.persist({release(){},query:async()=>({rows:[{transactionOpen:false}]})},c.page,{now,original:c.original}),/open-writing-transaction-required/);groups++;
 const actualPool=new(require("pg").Pool)();await assert.rejects(()=>Service.persist(actualPool,c.page,{now,original:c.original}),/transaction-client-required/);await actualPool.end();groups++;
 let ddl=0;const cachePool={connect(){},query:async()=>{ddl++;return{rows:[]};}};await Service.ensure(cachePool);await Service.ensure(cachePool);check(()=>assert.equal(ddl,1));let clientDdl=0;inherited.query=async()=>{clientDdl++;return{rows:[]};};await Service.ensure(inherited);await Service.ensure(inherited);check(()=>assert.equal(clientDdl,2,"Inherited connect must not cache a rollback-prone client schema"));let retry=0;const retryPool={connect(){},query:async()=>{if(++retry===1)throw Error("synthetic-DDL-failure");return{rows:[]};}};await assert.rejects(()=>Service.ensure(retryPool),/synthetic-DDL-failure/);await Service.ensure(retryPool);check(()=>assert.equal(retry,2));
 const filtered=makePool();filtered.captures=pool.captures;const bad={...recorded,capture_hash:"0".repeat(64)};for(let i=0;i<50;i++)filtered.articles.set(String(i),i===0?recorded:bad);filtered.query=async(sql,params)=>sql.startsWith("SELECT source_response_hash,body")?{rows:[originalBody]}:sql.includes(" FROM "+Service.TABLE)?{rows:[recorded,...Array(49).fill(bad)]}:{rows:[]};const page=await Service.search(filtered,{now,offset:100});check(()=>{assert.equal(page.items.length,1);assert.equal(page.scannedRows,50);assert.equal(page.nextOffset,150);assert.equal(page.hasMore,true,"Invalid legacy rows cannot conceal the next raw page");});
 console.log(`aldi-category-article-service: ${groups} synthetic original groups passed; category originals/FK, native-only dated identity, pack/scope/clock revalidation, latest/held/replay and genuine-client/schema bounds`);
}
main().catch(error=>{console.error(error);process.exitCode=1;});
