"use strict";
const assert=require("node:assert/strict"),Service=require("../aldi-assortment-price-service"),Semantics=require("../source-semantics"),Sources=require("../price-sources"),Combined=require("../published-retailer-inventory");
const fs=require("node:fs"),path=require("node:path"),crypto=require("node:crypto"),Client=require("../aldi-assortment-client"),DepositProof=require("../aldi-deposit-proof");
const NOW=Date.parse("2026-10-01T12:00:00Z"),iso=n=>new Date(n).toISOString();
function offer(patch={}){return{sourceId:Service.SOURCE,merchant:"ALDI Nord",retailerSku:"1018999",gtin:null,name:"UNIT TEST Haltbare Vollmilch",brand:"MILSANI",variant:null,pack:"1-L-Packung",packAmount:1,packUnit:"l",packCount:1,price:.95,deposit:0,depositIncluded:false,currency:"EUR",priceBasis:"pack",priceKind:"published-current",regularPrice:null,promotionStatus:"unknown",availability:"unknown",publicationAvailable:true,capturedAt:iso(NOW-1000),nativeValidFrom:iso(NOW-86400000),nativeValidUntil:iso(NOW+86400000*2),sourceUrl:"https://www.aldi-nord.de/produkt/haltbare-vollmilch-1018999.html",sourceResponseHash:"a".repeat(64),proofHash:"b".repeat(64),sourceResponseDate:iso(NOW-1000),sourceAgeSeconds:null,scopeCountry:"DE",scopeChannel:"assortment-publication",locationScope:"unknown",...patch};}
function database(){const rows=new Map(),calls=[];return{rows,calls,query:async(sql,params=[])=>{calls.push({sql,params});if(sql.startsWith("CREATE TABLE"))return{rows:[],rowCount:0};if(sql.startsWith("SELECT p.source_id"))return{rows:JSON.parse(params[0]).map(r=>rows.get(r.source_id+"|"+r.retailer_sku)).filter(Boolean),rowCount:0};if(sql.startsWith("INSERT INTO aldi_assortment_published_prices")){let rowCount=0;for(const row of JSON.parse(params[0])){const key=row.source_id+"|"+row.retailer_sku,old=rows.get(key);if(!old||row.captured_at>old.captured_at){rows.set(key,row);rowCount++;}}return{rows:[],rowCount};}return{rows:[],rowCount:0};}};}
const valid=Service.validateOffer(offer(),{now:NOW});assert.equal(valid.ok,true,JSON.stringify(valid));assert.equal(valid.offer.packAmount,1000);assert.equal(valid.offer.packUnit,"ml");assert.equal(valid.offer.price,.95);assert.equal(valid.offer.gtin,null);assert.equal(valid.offer.expiresAt,iso(NOW-1000+Service.DAY_MS));assert.equal(valid.offer.truthEligible,false);
assert.equal(valid.offer.depositBasisProof,null);
const deadline=Service.validateOffer(offer({nativeValidUntil:iso(NOW+500)}),{now:NOW});assert.equal(deadline.ok,true);assert.equal(deadline.offer.expiresAt,iso(NOW+500),"A native price deadline caps local freshness");
const unknown=Service.validateOffer(offer({deposit:null,depositIncluded:null}),{now:NOW});assert.equal(unknown.ok,true);assert.equal(unknown.offer.deposit,null);assert.equal(unknown.offer.payablePackPrice,null);
assert.equal(unknown.offer.depositBasisProof,null);
for(const patch of[{pack:"z. B. 770 g",packAmount:770,packUnit:"g"},{pack:"770 g",packAmount:770,packUnit:"g",variant:"Frisch; ausgenommen; mit Kopf; verschiedene Gewichte"},{variant:"verschiedene Größen"},{name:"UNIT TEST verschiedene Mengen"}]){const checked=Service.validateOffer(offer(patch),{now:NOW});assert.equal(checked.ok,false);assert(checked.reasons.includes("known-fixed-pack-required"),JSON.stringify(checked));}
function originalDeposit(name){const file=path.join(__dirname,"fixtures/retailers/aldi-deposit",name+".html"),raw=fs.readFileSync(file,"utf8"),response=JSON.parse(fs.readFileSync(file.replace(".html","-response.json"),"utf8"));assert.equal(crypto.createHash("sha256").update(raw).digest("hex"),response.sourceResponseHash);const meta={...response,raw,sourceResponseDate:response.headers.date,sourceAgeSeconds:null},native=Client.extractProducts(raw).products[0],parsed=Client.parseProduct(native,meta);assert(parsed.offer,JSON.stringify(parsed));return parsed.offer;}
const water=originalDeposit("classic-1026202"),cola=originalDeposit("original-taste-4039"),DEPOSIT_NOW=Date.parse(water.capturedAt)+1;
for(const[input,deposit,payable,count]of[[water,2.25,3.60,9],[cola,.25,1.84,1]]){const checked=Service.validateOffer(input,{now:DEPOSIT_NOW});assert.equal(checked.ok,true,JSON.stringify(checked));assert.equal(checked.offer.deposit,deposit);assert.equal(checked.offer.payablePackPrice,payable);assert.equal(checked.offer.packCount,count);assert.equal(checked.offer.depositIncluded,false);assert.equal(checked.offer.depositBasisProof.depositAmountBasis,"sales-pack-total");assert.equal(DepositProof.validateProof(checked.offer),true);assert.equal(checked.offer.gtin,null);assert.equal(checked.offer.locationScope,"unknown");assert.equal(checked.offer.promotionStatus,"unknown");assert.notEqual(checked.offer.depositBasisProof,input.depositBasisProof,"The admitted proof is copied rather than retaining mutable caller authority");}
let depositCases=2;
for(const patch of[{depositBasisProof:null},{depositBasisProof:{}},{depositBasisProof:[]},{depositIncluded:true},{depositIncluded:null},{deposit:"2.25"},{deposit:.001},{deposit:-.25},{deposit:Infinity},{deposit:NaN},{deposit:10000.01},{price:1.36},{pack:"9x0,6-Liter-Flasche"},{sourceResponseHash:"f".repeat(64)},{capturedAt:iso(DEPOSIT_NOW)},{depositBasisProof:{...water.depositBasisProof,retailerSku:1026202}},{depositBasisProof:{...water.depositBasisProof,proofHash:"f".repeat(64)}},{depositBasisProof:{...water.depositBasisProof,depositCents:25}},{depositBasisProof:{...water.depositBasisProof,depositAmountBasis:"per-container"}},{depositBasisProof:{...water.depositBasisProof,depositPriceBasis:"included"}},{depositBasisProof:{...water.depositBasisProof,rendererManifestHash:"a".repeat(64)}},{depositBasisProof:{...water.depositBasisProof,extraAuthority:true}}]){const checked=Service.validateOffer({...water,...patch},{now:DEPOSIT_NOW});assert.equal(checked.ok,false,JSON.stringify(patch));assert(checked.reasons.includes("deposit-price-basis-unresolved"),JSON.stringify(checked));depositCases++;}
assert.equal(Service.validateOffer(offer({depositBasisProof:water.depositBasisProof}),{now:NOW}).ok,false,"A positive-deposit attestation must not be attached to a zero deposit");depositCases++;
assert.equal(Service.validateOffer(offer({price:.9500000001}),{now:NOW}).offer.price,.95,"An accepted cent value is normalized before PostgreSQL numeric constraints");
for(const[patch,reason]of[
 [{sourceId:"ALDI Nord"},"retailer-source-not-approved"],[{merchant:"ALDI SÜD"},"retailer-source-not-approved"],[{retailerSku:"6525"},"native-article-id-required"],[{retailerSku:"01018999"},"native-article-id-required"],[{sourceUrl:"https://www.aldi-nord.de/produkt/haltbare-vollmilch-1018999.html?fake=1"},"exact-native-product-url-required"],
 [{gtin:"4008400401621"},"native-gtin-unattested"],[{storeId:"invented-berlin"},"physical-identity-scope-unsupported"],[{scopeChannel:"store"},"assortment-DE-scope-required"],[{locationScope:"Berlin"},"assortment-DE-scope-required"],[{scopeCountry:"AT"},"assortment-DE-scope-required"],
 [{pack:"ca. 1 l"},"known-fixed-pack-required"],[{pack:"1 l + 100 ml"},"known-fixed-pack-required"],[{packAmount:2},"pack-metadata-conflict"],[{packCount:true},"pack-metadata-conflict"],[{price:true},"positive-cent-pack-price-required"],[{price:.951},"positive-cent-pack-price-required"],[{price:Infinity},"positive-cent-pack-price-required"],[{currency:"USD"},"EUR-pack-price-required"],
 [{priceKind:"regular"},"normal-price-classification-unattested"],[{regularPrice:1.09},"normal-price-classification-unattested"],[{promotionStatus:"promotion"},"normal-price-classification-unattested"],[{availability:"available"},"publication-availability-scope-required"],[{publicationAvailable:false},"publication-availability-scope-required"],[{deposit:.25},"deposit-price-basis-unresolved"],[{depositIncluded:true},"deposit-price-basis-unresolved"],
 [{capturedAt:iso(NOW+1)},"capture-time-future"],[{capturedAt:"2026-02-30T12:00:00Z"},"capture-time-required"],[{nativeValidFrom:iso(NOW)},"native-current-validity-required"],[{nativeValidUntil:iso(NOW-1000)},"native-current-validity-required"],[{sourceResponseDate:null},"fresh-source-response-date-required"],[{sourceResponseDate:iso(NOW-302000)},"fresh-source-response-date-required"],[{sourceAgeSeconds:301},"source-cache-age-stale-or-invalid"],[{sourceAgeSeconds:-1},"source-cache-age-stale-or-invalid"],[{sourceAgeSeconds:"2"},"source-cache-age-stale-or-invalid"],[{sourceResponseHash:"fake"},"source-proof-hash-required"],[{proofHash:"fake"},"source-proof-hash-required"],[{sourceResponseUrl:"https://example.test/price"},"exact-native-response-url-required"]
]){const checked=Service.validateOffer(offer(patch),{now:NOW});assert.equal(checked.ok,false,reason);assert(checked.reasons.includes(reason),JSON.stringify(checked));}
assert(Sources.canImport(Service.SOURCE));assert.equal(Semantics.truthEligible({source:Service.SOURCE}),false);assert.equal(Semantics.allowedFor({source:Service.SOURCE},"identity"),true);assert.equal(Combined.matchesProductQuery(valid.offer,{gtin:"4008400401621",pack:"1 l"}),false,"Native SKU articles must never be invented as GTIN matches");
async function main(){
 const db=database(),original=offer(),snapshot=JSON.stringify(original);let saved=await Service.persist(db,[original,offer({price:0})],{now:NOW});assert.equal(saved.accepted,1);assert.equal(saved.rejected,1);assert.equal(saved.upserted,1);assert.equal(JSON.stringify(original),snapshot);
 assert.equal((await Service.persist(db,[original],{now:NOW})).unchanged,1);
 const conflict=offer({price:1.09});saved=await Service.persist(db,[conflict],{now:NOW});assert.equal(saved.rejected,1);assert.equal(saved.reasons["same-capture-conflict"],1);assert.equal([...db.rows.values()][0].price,.95);
 const empty=database();saved=await Service.persist(empty,[original,conflict],{now:NOW});assert.equal(saved.accepted,0);assert.equal(saved.rejected,2);assert.equal(empty.rows.size,0);
 const newer=offer({price:1.09,capturedAt:iso(NOW),sourceResponseDate:iso(NOW),proofHash:"c".repeat(64)});assert.equal((await Service.persist(db,[newer],{now:NOW})).upserted,1);assert.equal((await Service.persist(db,[original],{now:NOW})).unchanged,1);assert.equal([...db.rows.values()][0].price,1.09);
 assert(!db.calls.some(c=>/price_observations|INSERT INTO (?:products|stores|receipts)\b/.test(c.sql)));
 const legacyRow={...db.rows.get(Service.SOURCE+"|"+original.retailerSku)};delete legacyRow.offer_hash;delete legacyRow.deposit_basis_proof;assert.equal(db.rows.get(Service.SOURCE+"|"+original.retailerSku).offer_hash,crypto.createHash("sha256").update(JSON.stringify(legacyRow)).digest("hex"),"Adding the nullable proof column preserves legacy zero-pfand capture hashes");
 const depositDb=database(),waterSnapshot=JSON.stringify(water);assert.equal((await Service.persist(depositDb,[water],{now:DEPOSIT_NOW})).upserted,1);assert.equal(JSON.stringify(water),waterSnapshot);const storedWater=depositDb.rows.get(Service.SOURCE+"|"+water.retailerSku);assert.equal(storedWater.deposit,2.25);assert.equal(storedWater.pack_count,9);assert.deepEqual(storedWater.deposit_basis_proof,water.depositBasisProof);depositCases++;
 const reversedProof=Object.fromEntries(Object.entries(water.depositBasisProof).reverse());assert.equal((await Service.persist(depositDb,[{...water,depositBasisProof:reversedProof}],{now:DEPOSIT_NOW})).unchanged,1,"JSONB key order must not turn a duplicate original into a same-capture conflict");depositCases++;
 const validWater=Service.validateOffer(water,{now:DEPOSIT_NOW}).offer,shorterExpiry=iso(DEPOSIT_NOW+60000),queryRows=[{...validWater,expiresAt:shorterExpiry,depositBasisProof:reversedProof},{...validWater,retailerSku:cola.retailerSku,sourceUrl:cola.sourceUrl},{...validWater,depositBasisProof:{...water.depositBasisProof,proofHash:"0".repeat(64)}}],readDb={query:async sql=>({rows:sql.startsWith("SELECT source_id")?queryRows:[],rowCount:0})};const read=await Service.search(readDb,{now:DEPOSIT_NOW});assert.equal(read.items.length,1,"Readers independently reject a mismatched or forged stored proof");assert.equal(read.items[0].payablePackPrice,3.60);assert.equal(read.items[0].depositBasisProof.proofHash,water.depositBasisProof.proofHash);assert.equal(read.items[0].expiresAt,shorterExpiry,"Revalidation cannot extend a shorter stored expiry");assert.equal(DepositProof.validateProof(read.items[0]),true);depositCases++;
 const fixed=Service.validateOffer(offer(),{now:NOW}).offer,legacyRows=[fixed,{...fixed,pack:"z. B. 770 g",packAmount:770,packUnit:"g"},{...fixed,pack:"770 g",packAmount:770,packUnit:"g",variant:"Frisch; ausgenommen; mit Kopf; verschiedene Gewichte"}],legacyDb={query:async sql=>({rows:sql.startsWith("SELECT source_id")?legacyRows:[],rowCount:0})};const legacy=await Service.search(legacyDb,{now:NOW});assert.equal(legacy.items.length,1,"A formerly stored variable-weight offer must be rejected on read without changing its original row");assert.equal(legacy.items[0].pack,"1-L-Packung");assert.equal(legacyRows[1].pack,"z. B. 770 g");
 const ddl=depositDb.calls.find(c=>c.sql.startsWith("CREATE TABLE")).sql;for(const fragment of["ADD COLUMN IF NOT EXISTS deposit_basis_proof jsonb","DROP CONSTRAINT IF EXISTS aldi_assortment_published_prices_deposit_check","aldi_assortment_deposit_proof_check",DepositProof.MANIFEST_HASH,"sales-pack-total","to_jsonb(deposit*100)"])assert(ddl.includes(fragment),fragment);depositCases++;
 const q=Service.querySpec({now:NOW,merchant:"ALDI Nord",search:"Milch%_",limit:999});assert.equal(q.params.at(-1),200);assert.equal(q.params[2],"%Milch\\%\\_%");assert(q.sql.includes("native_valid_until>$1"));assert(q.sql.includes("interval '24 hours'"));
 assert.throws(()=>Service.querySpec({gtin:"invalid"}),/invalid-gtin/);assert.throws(()=>Service.querySpec({today:"2026-02-30"}),/invalid-date/);
 await assert.rejects(()=>Service.persist(null,[]),/database-required/);await assert.rejects(()=>Service.search(null),/database-required/);await assert.rejects(()=>Service.persist(db,{}),/invalid-published-offers/);
 console.log("aldi-assortment-price-service: strict source/SKU/pack/validity and HTTP proof, unknown GTIN/branch/normal price, authenticated whole-pack deposit, JSONB/legacy idempotency, capped expiry and conflicting capture rejection OK ("+depositCases+" deposit groups)");
}
main().catch(e=>{console.error(e);process.exitCode=1;});
