"use strict";
const assert=require("node:assert/strict"),Source=require("../aldi-source-refresh"),Category=require("../aldi-category-refresh"),Client=require("../aldi-assortment-client");
const time=Date.UTC(2026,9,3,4,0),owner="UNIT TEST shared owner",pool={query:async()=>({rows:[]})};
function setup(patch={}){let pdpCalls=0,categoryCalls=0;const pdpState={updatedAt:new Date(time-3600000).toISOString(),...patch.pdp},categoryState={...patch.category},global={leaseOwner:owner,leaseUntil:new Date(time+900000).toISOString(),consecutiveFailures:0,...patch.global};
 const deps={pdp:{load:async()=>pdpState,resumeAt:async()=>patch.pdpResume??null,refresh:async(args,child)=>{pdpCalls++;if(patch.pdpHook)await patch.pdpHook(args,child,global);pdpState.updatedAt=new Date(time).toISOString();return{received:2,accepted:2,requests:2};}},category:{load:async()=>categoryState,state:Category.state,dueAt:Category.dueAt,refresh:async(args,child)=>{categoryCalls++;assert.equal(await child.canFetch(),true);assert(args.maxRequests<=4);categoryState.cursor={...Category.state(categoryState),lastRunAt:new Date(time).toISOString()};return{received:3,accepted:3,requests:1};}},store:{loadAll:async()=>({[Source.SOURCE]:global})},...patch.deps};
 return{deps,pdpState,categoryState,global,get pdpCalls(){return pdpCalls;},get categoryCalls(){return categoryCalls;},run:args=>Source.refresh({pool,leaseOwner:owner,maxRequests:16,now:()=>time,...args},deps)};
}
(async()=>{let checks=0;
 const first=setup(),result=await first.run();assert.equal(first.categoryCalls,1);assert.equal(first.pdpCalls,0);assert.equal(result.captureMode,"category-original");assert.equal(result.runnerSourceId,Source.SOURCE);assert.equal(result.sharedSourceLease,true);assert.equal(Date.parse(result.nextAttemptAt),time+60000,"Routing does not start another host batch immediately");checks++;
 const failed=setup({global:{consecutiveFailures:14,lastAttemptAt:new Date(time-3600000).toISOString(),nextAttemptAt:new Date(time+3600000).toISOString()},pdp:{retryAfter:new Date(time+2*3600000).toISOString()},category:{retryAfter:new Date(time+3*3600000).toISOString()}}),blocked=await failed.run();assert.equal(blocked.skipped,"shared-source-not-eligible");assert.equal(Date.parse(blocked.nextAttemptAt),time+5*3600000,"Exponential durable global backoff beats earlier route cooldowns");assert.equal(failed.categoryCalls+failed.pdpCalls,0);checks++;
 for(const global of[{leaseOwner:"OTHER OWNER"},{leaseUntil:new Date(time-1).toISOString()},{leaseUntil:null}]){const h=setup({global});assert.equal((await h.run()).skipped,"shared-source-not-eligible");assert.equal(h.categoryCalls+h.pdpCalls,0);checks++;}
 const stopped=setup({deps:{shouldContinue:()=>false}});assert.equal((await stopped.run()).skipped,"shared-source-not-eligible");assert.equal(stopped.categoryCalls+stopped.pdpCalls,0);checks++;
 // A durable refusal in either route blocks the other route through the same host.
 for(const refused of["category","pdp"]){const h=setup(),until=new Date(time+8*86400000).toISOString();(refused==="category"?h.categoryState:h.pdpState).retryAfter=until;const result=await h.run();assert.equal(result.skipped,"shared-source-not-eligible");assert.equal(result.nextAttemptAt,until);assert.equal(h.pdpCalls+h.categoryCalls,0);checks++;}
 const nestedPause=new Date(time+8*86400000).toISOString(),nested=setup({category:{cursor:{...Category.state(),retryAfter:nestedPause}}});assert.equal((await nested.run()).nextAttemptAt,nestedPause);assert.equal(nested.categoryCalls+nested.pdpCalls,0,"A persisted category cursor pause also applies to the shared PDP host");checks++;
 const wait=setup({category:{cursor:{...Category.state(),nextIndex:1,completedPasses:1,nextPassAt:new Date(time+3600000).toISOString(),lastRunAt:new Date(time-60000).toISOString()}},pdpResume:new Date(time+600000).toISOString()});assert.equal((await wait.run()).skipped,"source-not-due");assert.equal(wait.pdpCalls+wait.categoryCalls,0);checks++;
 const fair=setup({category:{cursor:{...Category.state(),lastRunAt:new Date(time-120000).toISOString()}},pdp:{updatedAt:new Date(time-180000).toISOString()},pdpResume:new Date(time-120000).toISOString(),pdpHook:async(args,child,global)=>{assert.equal(typeof child.discoverTargets,"function");assert.equal(typeof child.fetchProducts,"function");global.leaseOwner="LOST OWNER";await assert.rejects(child.discoverTargets({fetchImpl:async()=>assert.fail("No GET after lease loss"),now:()=>new Date(time).toISOString()}),/aldi-shared-source-not-eligible/);}});assert.equal((await fair.run()).captureMode,"product-detail-original");assert.equal(fair.pdpCalls,1);assert.equal(fair.categoryCalls,0);checks++;
 for(const global of[{consecutiveFailures:-1},{consecutiveFailures:1,lastAttemptAt:"bad-date"},{consecutiveFailures:1,lastAttemptAt:null}]){const h=setup({global});await assert.rejects(h.run(),/aldi-shared-source-state-invalid/);assert.equal(h.categoryCalls+h.pdpCalls,0);checks++;}
 await assert.rejects(first.run({leaseOwner:undefined}),/aldi-shared-source-lease-owner-required/);checks++;
 let http=0;await assert.rejects(Client.discoverTargets({canFetch:async()=>false,fetchImpl:async()=>{http++;assert.fail("No denied sitemap GET");}}),/aldi-shared-source-not-eligible/);assert.equal(http,0);checks++;
 const targets=[Client.targetForUrl("https://www.aldi-nord.de/produkt/unit-test-a-1040001.html"),Client.targetForUrl("https://www.aldi-nord.de/produkt/unit-test-b-1040002.html")];let gateCalls=0;const partial=await Client.fetchProducts(targets,{maxRequests:2,canFetch:async()=>++gateCalls===1,fetchImpl:async()=>{http++;return{status:404,headers:new Headers()};},sleep:async()=>{},now:()=>new Date(time).toISOString()});assert.equal(http,1);assert.equal(partial.requests,1);assert.equal(partial.nextIndex,1);assert.equal(partial.processed,1);assert.equal(partial.partialError.requestStarted,false);assert.equal(partial.partialError.code,"aldi-shared-source-not-eligible");assert.equal(partial.products.length,0);assert.equal(partial.offers.length,0);checks++;
 console.log("aldi-source-refresh: "+checks+" shared durable backoff/lease, fair cadence, shutdown and per-GET PDP gate groups passed");
})().catch(error=>{console.error(error);process.exitCode=1;});
