"use strict";
const assert=require("node:assert/strict"),crypto=require("node:crypto"),Category=require("../aldi-assortment-category-client"),Articles=require("../aldi-category-article-service"),Service=require("../aldi-category-price-service");
const now=Date.parse("2026-10-03T04:00:00.500Z"),categoryUrl="https://www.aldi-nord.de/sortiment/milchprodukte/milch-milchgetraenke.html",index=Category.INDEX;let groups=0;
const clone=v=>structuredClone(v);
// Synthetic complete HTML and HTTP proofs only. No archived source is retimed.
function product(sku="1018999",patch={}){return{objectID:sku,productSlug:"unit-milch-"+sku,name:"UNIT Vollmilch",brandName:"MILSANI",shortDescription:"3,5 % Fett",salesUnit:"1-L-Packung",categoryIDs:["milch-milchgetraenke"],currentPrice:{priceValue:.95,validFrom:Math.floor((now-86400000)/1000),validUntil:Math.floor((now+86400000*3)/1000)},isAvailable:true,isRecall:false,isComingSoon:false,isDepositProduct:false,depositValue:0,...patch};}
function original(hits=[product()],at=now-1000,patch={}){
 const entry={state:{index,filters:"categoryIDs:milch-milchgetraenke",hitsPerPage:1000},requestParams:[{filters:"categoryIDs:milch-milchgetraenke",hitsPerPage:1000}],results:[{index,query:"",params:"filters=categoryIDs%3Amilch-milchgetraenke&hitsPerPage=1000",hits,page:0,nbHits:hits.length,nbPages:hits.length?1:0,hitsPerPage:1000,exhaustiveNbHits:true,exhaustive:{nbHits:true}}]};
 const n={page:"/product-overview/[...categories]",query:{categories:["milchprodukte","milch-milchgetraenke"]},props:{pageProps:{locale:"de",page:{"@path":"/germany/sortiment/milchprodukte/milch-milchgetraenke",categoryKey:"milch-milchgetraenke"},algoliaState:{initialResults:{[index]:entry}}}}};
 const body='<html><head><link rel="canonical" href="'+categoryUrl+'"/></head><body><script id="__NEXT_DATA__" type="application/json">'+JSON.stringify(n)+'</script></body></html>';return{body,meta:{sourceResponseUrl:categoryUrl,sourceResponseHash:crypto.createHash("sha256").update(body).digest("hex"),capturedAt:new Date(at).toISOString(),sourceResponseDate:new Date(at).toUTCString(),sourceAgeSeconds:0,scopeCountry:"DE",...patch}};
}
function parsed(o,time=now){return Category.parsePage(o.body,o.meta,{now:time});}
function freshQuote(o=original(),time=now){const p=parsed(o,time);return Service.quoteFor(p.candidates[0],p.categoryId,time).offer;}
class FakeTransaction{
 constructor(o=original()){this.articles=new Map();this.prices=new Map();this.captures=new Map();this.calls=[];this.assigned=true;this.release=()=>{};this.failWrite=null;this.setArticle(o);}
 setArticle(o,time=Date.parse(o.meta.capturedAt)+1000){const p=parsed(o,time);this.captures.set(o.meta.sourceResponseHash,{source_response_hash:o.meta.sourceResponseHash,body:o.body,body_bytes:Buffer.byteLength(o.body)});for(const candidate of p.candidates){const row=Articles.rowForArticle(Articles.articleFor(candidate,p.categoryId));this.articles.set(row.retailer_sku,{...row,held:false,conflict_capture:null,conflict_response_hash:null});}return p;}
 async query(sql,params=[]){this.calls.push({sql,params:clone(params)});if(sql.includes("txid_current_if_assigned"))return{rows:[{transactionOpen:this.assigned}]};if(sql.startsWith("SELECT pg_advisory"))return{rows:[]};if(sql.includes("CREATE TABLE"))return{rows:[],rowCount:0};
  if(sql.includes("FROM "+Articles.CAPTURE_TABLE)){const row=this.captures.get(params[0]);return{rows:row?[clone(row)]:[]};}
  if(sql.startsWith("SELECT * FROM "+Articles.TABLE)){return{rows:[...this.articles.values()].filter(r=>r.source_id===params[0]&&params[1].includes(r.retailer_sku)).map(clone)};}
  if(sql.startsWith("INSERT INTO "+Service.TABLE)){if(this.failWrite)throw this.failWrite;let rowCount=0;for(const input of JSON.parse(params[0])){const old=this.prices.get(input.retailer_sku);if(!old||Date.parse(input.captured_at)>Date.parse(old.captured_at)){this.prices.set(input.retailer_sku,clone(input));rowCount++;}else if(input.captured_at===old.captured_at&&!old.held&&input.price_identity_hash!==old.price_identity_hash){old.held=true;old.conflict_capture=clone(input);old.conflict_response_hash=input.source_response_hash;rowCount++;}}return{rows:[],rowCount};}
  if(sql.startsWith("SELECT count(*)")&&sql.includes("FROM "+Service.TABLE))return{rows:[{count:[...this.prices.values()].filter(r=>r.held===true&&params[1].includes(r.retailer_sku)).length}]};
  if(sql.includes("FROM "+Service.TABLE)){let rows=[...this.prices.values()];if(sql.startsWith("SELECT source_id"))rows=rows.filter(r=>r.source_id===params[0]&&params[1].includes(r.retailer_sku));if(sql.startsWith("SELECT p.*")){const t=Date.parse(params[0]);rows=rows.filter(r=>!r.held&&Date.parse(r.captured_at)<=t&&Date.parse(r.captured_at)+Service.DAY_MS>t&&Date.parse(r.expires_at)>t&&Date.parse(r.native_valid_from)<=t&&Date.parse(r.native_valid_until)>t);if(sql.includes(" AND false"))rows=[];rows=rows.slice(Number(params.at(-1)),Number(params.at(-1))+Number(params.at(-2)));}return{rows:rows.map(clone)};}
  throw Error("Unexpected fake SQL: "+sql.slice(0,160));
 }
}
async function test(name,fn){try{await fn();groups++;}catch(e){console.error("Failed:",name);throw e;}}
const rejection=(offer,reason)=>{const r=Service.validateOffer(offer,{now});assert.equal(r.ok,false);assert(r.reasons.includes(reason));};
(async()=>{
 await test("two native rows yield separate proved category quotes, positive Pfand stays unknown",async()=>{const o=original([product(),product("1019000",{name:"UNIT Mehrpack",salesUnit:"9x500ml",isDepositProduct:true,depositValue:2.25})]),p=parsed(o),tx=new FakeTransaction(o),result=await Service.persist(tx,p,{original:o,now});assert.equal(result.received,2);assert.equal(result.accepted,2);assert.equal(result.upserted,2);const read=await Service.search(tx,{now});assert.equal(read.items.length,2);const milk=read.items.find(x=>x.retailerSku==="1018999"),multi=read.items.find(x=>x.retailerSku==="1019000");assert.equal(milk.sourceId,Category.SOURCE);assert.equal(milk.sourceUrl,categoryUrl);assert.equal(milk.sourceResponseUrl,categoryUrl);assert.equal(milk.productIdentityUrl,"https://www.aldi-nord.de/produkt/unit-milch-1018999.html");assert.equal(milk.sourceResponseHash,o.meta.sourceResponseHash);assert.notEqual(milk.proofHash,o.meta.sourceResponseHash);assert.equal(milk.deposit,0);assert.equal(milk.payablePackPrice,.95);assert.equal(multi.deposit,null);assert.equal(multi.depositIncluded,null);assert.equal(multi.payablePackPrice,null);assert.equal(multi.packAmount,500);assert.equal(multi.packCount,9);for(const offer of read.items){assert.equal(offer.gtin,null);assert.equal(offer.promotionStatus,"unknown");assert.equal(offer.regularPrice,null);assert.equal(offer.currentAvailabilityVerified,false);assert.equal(offer.physicalStorePriceVerified,false);assert.equal(offer.truthEligible,false);assert.equal(Service.validateOffer(offer,{now}).ok,true);}assert(!tx.calls.some(x=>/\b(BEGIN|COMMIT|ROLLBACK)\b/.test(x.sql)));assert(tx.calls.some(x=>x.sql.includes("pg_advisory")&&x.params[0]===Service.SOURCE+":articles"));});
 await test("every default quote preserves original TTL/native validity, no source metadata change",async()=>{const o=original(),before=clone(o),offer=freshQuote(o);assert.equal(Date.parse(offer.expiresAt),Date.parse(o.meta.capturedAt)+Service.DAY_MS);assert.equal(offer.capturedAt,o.meta.capturedAt);assert.equal(offer.sourceResponseDate,new Date(o.meta.sourceResponseDate).toISOString());assert.deepEqual(o,before);const shorter=original([product("1018999",{currentPrice:{priceValue:1.19,validFrom:Math.floor((now-10000)/1000),validUntil:Math.floor((now+10000)/1000)}})]),q=freshQuote(shorter);assert.equal(q.expiresAt,q.nativeValidUntil);});
 for(const patch of[{isAvailable:false},{isAvailable:null},{isAvailable:"true"},{isRecall:true},{isRecall:null},{isComingSoon:true},{isComingSoon:null}])await test("actual availability/recall/comingsoon schema rejects "+JSON.stringify(patch),async()=>{const o=original([product("1018999",patch)]),tx=new FakeTransaction(o),result=await Service.persist(tx,parsed(o),{original:o,now});assert.equal(result.accepted,0);assert.equal(result.rejected,1);assert.equal(tx.prices.size,0);assert(result.reasons["category-native-current-publication-unavailable"]);});
 for(const value of[0,-1,1.001,NaN,Infinity,".95",10000.01])await test("only native positive exact cents "+String(value),async()=>{const o=original([product("1018999",{currentPrice:{priceValue:value,validFrom:1,validUntil:1893366000}})]),tx=new FakeTransaction(o),result=await Service.persist(tx,parsed(o),{original:o,now});assert.equal(result.accepted,0);assert.equal(tx.prices.size,0);assert(result.reasons["category-positive-cent-pack-price-required"]);});
 for(const price of[null,{priceValue:.95,validFrom:1,validUntil:1},{priceValue:.95,validFrom:Math.floor(now/1000)+1,validUntil:1893366000},{priceValue:.95,validFrom:1,validUntil:Math.floor(now/1000)},{priceValue:.95,validFrom:"1",validUntil:1893366000},{priceValue:.95,validFrom:1.1,validUntil:1893366000}])await test("native validity excludes stale/future/missing epochs "+JSON.stringify(price),async()=>{const o=original([product("1018999",{currentPrice:price})]),tx=new FakeTransaction(o),result=await Service.persist(tx,parsed(o),{original:o,now});assert.equal(result.accepted,0);assert.equal(tx.prices.size,0);assert(result.reasons["category-native-current-validity-required"]);});
 for(const patch of[{isDepositProduct:true,depositValue:.25},{isDepositProduct:false,depositValue:.25},{isDepositProduct:null,depositValue:0},{isDepositProduct:undefined,depositValue:undefined},{isDepositProduct:true,depositValue:-1}])await test("unsupported category Pfand remains unknown "+JSON.stringify(patch),async()=>{const o=original([product("1018999",patch)]),tx=new FakeTransaction(o);await Service.persist(tx,parsed(o),{original:o,now});const q=(await Service.search(tx,{now})).items[0];assert(q);assert.equal(q.deposit,null);assert.equal(q.depositBasisProof,null);assert.equal(q.depositIncluded,null);assert.equal(q.payablePackPrice,null);});
 for(const [pack,amount,unit,count]of[["1.000-g-Packung",1000,"g",1],["0.250 l",250,"ml",1],["20x10-g-Packung",10,"g",20]])await test("fixed sales amount/count "+pack,async()=>{const o=original([product("1018999",{salesUnit:pack})]),tx=new FakeTransaction(o);await Service.persist(tx,parsed(o),{original:o,now});const q=(await Service.search(tx,{now})).items[0];assert.equal(q.packAmount,amount);assert.equal(q.packUnit,unit);assert.equal(q.packCount,count);});
 for(const patch of[{salesUnit:"z. B. 770 g"},{salesUnit:"500-750 g"},{salesUnit:"1.000.5 g"},{salesUnit:"1000 g oder 1 l"},{shortDescription:"verschiedene Sorten"},{name:"verschiedene Gewichte"}])await test("source unresolved identity never creates price "+JSON.stringify(patch),async()=>{const o=original([product("1018999",patch)]),p=parsed(o),tx=new FakeTransaction(o),result=await Service.persist(tx,p,{original:o,now});assert.equal(result.accepted,0);assert.equal(p.candidates.length,0);assert.equal(tx.prices.size,0);});
 await test("whole original reparse required, forged DTO/body/clock rejected",async()=>{const o=original(),p=parsed(o),tx=new FakeTransaction(o);await assert.rejects(()=>Service.persist(tx,p,{now}),e=>e.code==="category-original-required");const forged=clone(p);forged.candidates[0].identity.name="forged";await assert.rejects(()=>Service.persist(tx,forged,{original:o,now}),e=>e.code==="category-price-page-original-conflict");await assert.rejects(()=>Service.persist(tx,p,{original:{...o,body:o.body+" "},now}),e=>e.code==="aldi-category-original-response-hash-conflict");assert.equal(tx.prices.size,0);});
 await test("pool and unassigned transaction refused before any price mutation",async()=>{const o=original(),p=parsed(o),tx=new FakeTransaction(o);await assert.rejects(()=>Service.persist({query:tx.query.bind(tx),connect:async()=>tx},p,{original:o,now}),e=>e.code==="category-price-transaction-client-required");tx.assigned=false;await assert.rejects(()=>Service.persist(tx,p,{original:o,now}),e=>e.code==="category-price-open-writing-transaction-required");assert.equal(tx.prices.size,0);});
 await test("missing/held/corrupted/different pack original article basis cannot admit quote",async()=>{for(const kind of["missing","held","capture","hash","pack"]){const o=original(),tx=new FakeTransaction(o),a=tx.articles.get("1018999");if(kind==="missing")tx.articles.clear();if(kind==="held")a.held=true;if(kind==="capture")a.observed_at=new Date(now-2000).toISOString();if(kind==="hash")a.capture_hash="0".repeat(64);if(kind==="pack"){a.pack_amount=1;a.identity_hash="1".repeat(64);}const result=await Service.persist(tx,parsed(o),{original:o,now});assert.equal(result.accepted,0,kind);assert.equal(tx.prices.size,0,kind);}});
 await test("later original price-less article hides old quote without renewing timestamps",async()=>{const o=original(),tx=new FakeTransaction(o);await Service.persist(tx,parsed(o),{original:o,now});const old=clone(tx.prices.get("1018999")),next=original([product("1018999",{currentPrice:null,isAvailable:false})],now+1000);tx.setArticle(next,now+2000);assert.equal((await Service.search(tx,{now:now+2000})).items.length,0);assert.deepEqual(tx.prices.get("1018999"),old);});
 await test("retimed same original Date/Age rejected; genuinely new Date with same bytes accepted",async()=>{const o=original(),tx=new FakeTransaction(o);await Service.persist(tx,parsed(o),{original:o,now});const old=clone(tx.prices.get("1018999")),retimed=original([product()],now+1000,{sourceResponseDate:o.meta.sourceResponseDate});tx.setArticle(retimed,now+2000);const rejected=await Service.persist(tx,parsed(retimed,now+2000),{original:retimed,now:now+2000});assert.equal(rejected.retimedReplays,1);assert.deepEqual(tx.prices.get("1018999"),old);const genuine=original([product()],now+3000);assert.equal(genuine.meta.sourceResponseHash,o.meta.sourceResponseHash);tx.setArticle(genuine,now+4000);const good=await Service.persist(tx,parsed(genuine,now+4000),{original:genuine,now:now+4000});assert.equal(good.upserted,1);assert.equal(tx.prices.get("1018999").captured_at,genuine.meta.capturedAt);assert.equal(Date.parse(tx.prices.get("1018999").expires_at),Date.parse(genuine.meta.capturedAt)+Service.DAY_MS);});
 await test("same capture price conflict held, repeated old capture cannot clear it, newer unique recovers",async()=>{const o=original(),tx=new FakeTransaction(o);await Service.persist(tx,parsed(o),{original:o,now});const conflicting=original([product("1018999",{currentPrice:{...product().currentPrice,priceValue:1.09}})],Date.parse(o.meta.capturedAt));tx.setArticle(conflicting);const held=await Service.persist(tx,parsed(conflicting),{original:conflicting,now});assert.equal(held.heldPrices,1);assert.equal(held.accepted,0);assert.equal((await Service.search(tx,{now})).items.length,0);assert.equal(tx.prices.get("1018999").price,.95);assert.equal(tx.prices.get("1018999").conflict_response_hash,conflicting.meta.sourceResponseHash);tx.setArticle(o);await Service.persist(tx,parsed(o),{original:o,now});assert.equal(tx.prices.get("1018999").held,true);const newer=original([product()],now+3000);tx.setArticle(newer,now+4000);await Service.persist(tx,parsed(newer,now+4000),{original:newer,now:now+4000});assert.equal(tx.prices.get("1018999").held,false);assert.equal((await Service.search(tx,{now:now+4000})).items.length,1);});
 await test("original body tampering is not accepted even when stored metadata hashes were consistent",async()=>{const o=original(),tx=new FakeTransaction(o);await Service.persist(tx,parsed(o),{original:o,now});tx.captures.get(o.meta.sourceResponseHash).body=tx.captures.get(o.meta.sourceResponseHash).body.replace("UNIT Vollmilch","OTHER milk");assert.equal((await Service.search(tx,{now})).items.length,0);assert.equal((await Service.status(tx,{now})).currentPrices,0);});
 for(const field of["price","pack_amount","pack_count","category_response_url","product_identity_url","source_response_hash","proof_hash","witness_hash","article_identity_hash","price_identity_hash","capture_hash","expires_at","source_age_seconds"]){await test("reader rejects edited stored "+field,async()=>{const o=original(),tx=new FakeTransaction(o);await Service.persist(tx,parsed(o),{original:o,now});const r=tx.prices.get("1018999");r[field]=typeof r[field]==="number"?r[field]+1:field==="expires_at"?new Date(now+86400000*2).toISOString():"changed";assert.equal((await Service.search(tx,{now})).items.length,0);});}
 await test("JSONB nested key order does not alter genuine witness identity",async()=>{const o=original(),tx=new FakeTransaction(o);await Service.persist(tx,parsed(o),{original:o,now});const a=tx.articles.get("1018999");a.native_product=Object.fromEntries(Object.entries(a.native_product).reverse());a.native_product.currentPrice=Object.fromEntries(Object.entries(a.native_product.currentPrice).reverse());assert.equal((await Service.search(tx,{now})).items.length,1);});
 await test("expired/future/native expiry never appears current, metadata status uses reader",async()=>{const o=original(),tx=new FakeTransaction(o);await Service.persist(tx,parsed(o),{original:o,now});assert.equal((await Service.search(tx,{now:Date.parse(o.meta.capturedAt)+Service.DAY_MS})).items.length,0);const s=await Service.status(tx,{now:Date.parse(o.meta.capturedAt)+Service.DAY_MS});assert.equal(s.storedPrices,1);assert.equal(s.currentPrices,0);assert.equal(s.productsWithCurrentPublishedPrices,0);assert.equal(s.lastCapturedAt,null);assert.equal(s.assortmentComplete,false);assert.equal(s.physicalStorePriceVerified,false);assert.equal(s.normalPriceClassificationVerified,false);});
 await test("database failure propagates without owning caller transaction or price checkpoint",async()=>{const o=original(),tx=new FakeTransaction(o),error=Object.assign(Error("actual DB failure"),{code:"23514"});tx.failWrite=error;await assert.rejects(()=>Service.persist(tx,parsed(o),{original:o,now}),e=>e===error);assert.equal(tx.prices.size,0);assert(!tx.calls.some(x=>/^(BEGIN|COMMIT|ROLLBACK|DELETE|UPDATE price_source)/.test(x.sql)));});
 await test("query is parameterized, exactly pack-count scoped, no GTIN invention, bounded raw pagination",async()=>{const q=Service.querySpec({now,search:"Milch%_\\",pack:"2x500ml",limit:2,offset:3});assert(q.sql.includes("JOIN "+Articles.TABLE));assert(q.sql.includes("a.observed_at=p.captured_at"));assert(q.sql.includes("a.source_response_hash=p.source_response_hash"));assert(q.sql.includes("p.pack_count="));assert(!q.sql.includes("Milch%"));assert(q.params.includes("%Milch\\%\\_\\\\%"));assert(q.params.includes(2));assert.equal(q.limit,2);assert.equal(q.offset,3);assert(Service.querySpec({now,gtin:"4046700026519"}).sql.includes(" AND false"));assert(Service.querySpec({now,scopeChannel:"physical-store"}).sql.includes(" AND false"));});
 for(const options of[{search:"x"},{search:""},{search:"x".repeat(121)},{gtin:"4046700026510"},{retailerSku:"001"},{merchant:[]},{scopeChannel:"category-published"},{limit:0},{limit:201},{limit:"01"},{offset:-1},{offset:100001},{today:"2026-02-30"},{url:"https://other.invalid"},{priorityRetailersOnly:"true"},{now:Infinity}])await test("invalid bounded query "+JSON.stringify(options),async()=>{assert.throws(()=>Service.querySpec({now,...options}),e=>e.code.startsWith("invalid-"));});
 const clean=freshQuote();for(const [patch,reason]of[[{gtin:"4046700026519"},"category-price-unverified-identity-forbidden"],[{storeId:"fake"},"category-price-unverified-identity-forbidden"],[{sourceId:"ALDI Nord published assortment"},"category-price-source-scope-required"],[{sourceResponseUrl:clean.productIdentityUrl},"category-price-original-url-required"],[{packAmount:1},"category-exact-pack-metadata-required"],[{deposit:.25,depositIncluded:false,payablePackPrice:1.20},"category-deposit-price-basis-unresolved"],[{regularPrice:1.99},"category-normal-price-classification-forbidden"],[{promotionStatus:"none"},"category-normal-price-classification-forbidden"],[{truthEligible:true},"category-price-authority-forbidden"],[{physicalStorePriceVerified:true},"category-price-authority-forbidden"],[{currentAvailabilityVerified:true},"category-price-authority-forbidden"],[{sourceAgeSeconds:301},"category-original-http-proof-invalid"],[{expiresAt:new Date(now+86400000*2).toISOString()},"category-original-price-validity-required"]])await test("closed public offer structural gate "+Object.keys(patch).join(),async()=>{const x={...clean,...patch};x.proofHash=Service.proofHash(x);rejection(x,reason);});
 await test("schema has source/native/sourcecapture FK/cents/TTL/holds only, no canonical business tables",async()=>{const tx=new FakeTransaction();await Service.ensure(tx);const sql=tx.calls.filter(x=>x.sql.includes("CREATE TABLE IF NOT EXISTS "+Service.TABLE)).at(-1).sql;for(const term of["FOREIGN KEY(source_id,retailer_sku)","REFERENCES "+Articles.TABLE,"REFERENCES "+Articles.CAPTURE_TABLE,"price*100=trunc(price*100)","deposit IS NULL OR deposit=0","expires_at=LEAST(captured_at+interval '24 hours',native_valid_until)","price_identity_hash","conflict_response_hash"])assert(sql.includes(term),term);assert(!/\b(canonical_products|canonical_stores|price_observations|product_store_status)\b/.test(sql));});
 console.log(`aldi-category-price-service: ${groups} synthetic offline groups passed; real category originals, native article coupling, strict pack/price/validity, unknown positive Pfand, replay/holds and read-only truthful scope`);
})().catch(e=>{console.error(e);process.exitCode=1;});
