"use strict";
const assert=require("node:assert/strict"),fs=require("node:fs"),path=require("node:path"),{JSDOM}=require("jsdom");
const Overview=require("../app/assortment-overview"),Client=require("../app/kaufland-publication-view"),Publications=require("../kaufland-berlin-publications"),master=require("../data/grocery-assortment.json");
const copy=structuredClone,at=Date.parse("2026-10-03T02:29:19.413Z"),html=fs.readFileSync(path.join(__dirname,"../sortiment.html"),"utf8");
// These are explicitly NEW synthetic original bodies and clocks. The actual
// frozen source parser creates50 dated groups, never fresh live shelf prices.
const examples=[
  {id:"01383309",title:"K-CLASSIC",subtitle:"Gouda jung",quantity:"je 450-g-Stück",base:"(1 kg = 6.65)",price:"2.99"},
  {id:"01202136",title:"MEGGLE",subtitle:"Baguette",quantity:"je 160-g-Packg.",base:"(1 kg = 6.19) / (1 kg = 5.50)**",price:"0.99",card:"0.88"},
  {id:"00450098",title:"WEIHENSTEPHAN",subtitle:"Haltbare Milch, 3,5 % Fett",quantity:"je 1-l-Packg.",base:"",price:"9.99",bby:"12 Stück",calculation:"entspr. pro Packg. 0.84"},
  {id:"01504659",title:"STORCK",subtitle:"Super Dickmann's",quantity:"je 6 St. = 168-g-Packg.",base:"(1 kg = 9.30)",price:"1.59 *"},
  {id:"01272955",title:"FROSTA",subtitle:"Fertiggericht",quantity:"je 450 - 500-g-Packg.",base:"(1 kg = 4.58 - 5.09)",price:"2.29"}
];
const esc=v=>String(v).replace(/&/g,"&amp;").replace(/"/g,"&quot;").replace(/</g,"&lt;");
function card(r){return `<a class="k-product-tile k-product-tile--slider" href="/angebote/uebersicht.html?kloffer-category=135_Foodknueller&amp;kloffer-articleID=${r.id}"><div class="k-product-tile__title">${esc(r.title)}</div><div class="k-product-tile__subtitle">${esc(r.subtitle)}</div><div class="k-product-tile__unit-price">${esc(r.quantity)}</div><div class="k-product-tile__base-price">${esc(r.base)}</div><div class="k-product-tile__pricetags-normal"><div class="k-price-tag">${r.bby?`<div class="k-price-tag__bby-message"><div class="k-price-tag__bby-message-top">${esc(r.bby)}</div><div class="k-price-tag__bby-message-bottom">${esc(r.calculation)}</div></div>`:""}<div class="k-price-tag__price">${esc(r.price)}</div></div></div>${r.card?`<div class="k-product-tile__pricetags-loyalty"><div class="k-price-tag k-price-tag--xtra"><div class="k-price-tag__with-card">Mit Kaufland Card XTRA **</div><div class="k-price-tag__price">${esc(r.card)}</div></div></div>`:""}</a>`;}
function original(){const rows=[...examples,...Array.from({length:45},(_,i)=>({...examples[0],id:String(90000000+i),subtitle:"SYNTHETIC display group "+i}))];const body=`<!doctype html><html><head><script class="o-special-offers-controller__settings" type="application/json">{"settings":{"apiUrl":"/.kloffers.storeName={storeName}.json"}}</script></head><body><!-- SYNTHETIC JSDOM TEST ORIGINAL -->
  <div data-force-store-change="DE1980"><h1 itemprop="name" content="Kaufland Berlin-Reinickendorf">Kaufland Berlin-Reinickendorf</h1><span itemprop="url" content="/service/filiale.storeName=DE1980.html"></span><div itemprop="streetAddress" content="Ollenhauerstraße 122">Ollenhauerstraße 122</div><span itemprop="addressLocality" content="Berlin"></span><span itemprop="postalCode" content="13403"></span></div><div class="t-tiles-slider"><h3>Unsere Knüller der Woche</h3><h3>Gültig vom 01.10.2026 bis 07.10.2026</h3><div class="o-slider__list">${rows.map(card).join("")}</div></div></body></html>`;
  const record=(url,body,time,type)=>({status:200,sourceResponseUrl:url,sourceResponseHash:Publications.hash(body),body,capturedAt:new Date(time).toISOString(),headers:{date:new Date(time).toUTCString(),age:"0","content-type":type},bytes:Buffer.byteLength(body)});
  return{branch:record(Publications.PAGE_URL,body,at,"text/html; charset=UTF-8"),index:record(Publications.INDEX_URL,JSON.stringify(rows.map(r=>({klNr:r.id,dateFrom:"2026-10-01",dateTo:"2026-10-07"}))),at+1000,"application/json")};}
const originals=original(),parsed=Publications.parseCapture(originals,{now:at+120000});assert.equal(parsed.accepted,50);
function payload(search=""){const rows=parsed.promotionalPublications.filter(r=>!search||r.publication.name.toLocaleLowerCase("de").includes(search.toLocaleLowerCase("de")));return{ok:true,promotionalPublications:copy(rows),promotionalPublicationCoverage:{sourceId:Publications.SOURCE,merchant:"Kaufland",receivedGroups:50,acceptedGroups:50,heldGroups:0,matchedGroups:rows.length,documentCapturedAt:parsed.documentCapturedAt,ambiguousLatestCapture:false,current:false,physicalStorePriceVerified:false,normalPriceClassificationVerified:false,nativeProductIdentities:0,fullAssortment:false},truncated:false};}
// Synthetic ALDI read DTO is for native-card separation only; it is never
// persisted or counted as a newly acquired retailer article.
const article={merchant:"ALDI",sourceMerchant:"ALDI Nord",sourceId:"ALDI Nord published assortment",retailerSku:"1234567",name:"SYNTHETIC dated ALDI native article",brand:null,variant:null,pack:"1 l",gtin:null,scopeCountry:"DE",scopeChannel:"assortment-publication",locationScope:"unknown",sourceUrl:"https://www.aldi-nord.de/produkt/unit-1234567.html",observedAt:new Date(at).toISOString(),state:"last-observed",availability:"unknown",currentPriceVerified:false,assortmentComplete:false};
const jsonResponse=body=>({ok:true,json:async()=>copy(body)}),flush=async()=>{for(let i=0;i<3;i++)await new Promise(resolve=>setImmediate(resolve));},debounce=async()=>{await new Promise(resolve=>setTimeout(resolve,210));await flush();};
function setup({publicationReply=async url=>jsonResponse(payload(url.searchParams.get("search")||"")),client=Client,browserBootstrap=false}={}){
  const dom=new JSDOM(html,{url:"https://unit.test/sortiment.html",runScripts:"outside-only"}),document=dom.window.document,calls=[];
  const fetcher=async value=>{calls.push(value);if(value==="data/grocery-assortment.json")return jsonResponse(master);const url=new URL(value);
    assert.equal(url.origin,"https://echtpreis-api.onrender.com","All request calls are stubbed own-API fixture URLs");
    if(url.pathname==="/v1/kaufland-berlin-publications"){assert.deepEqual([...url.searchParams.keys()].sort(),url.searchParams.has("search")?["limit","search"]:["limit"]);assert.equal(url.searchParams.get("limit"),"50");return publicationReply(url);}
    assert.equal(url.pathname,"/v1/assortment/articles","No source, receipt, refresh, canonical or price API call is allowed");const merchant=url.searchParams.get("merchant");return jsonResponse({merchant,assortmentComplete:false,status:merchant==="ALDI"?"observed-articles":"unsupported-source",items:merchant==="ALDI"?[copy(article)]:[]});
  };
  let mounted;
  if(browserBootstrap){dom.window.fetch=async value=>{const r=await fetcher(value);return{ok:r.ok,json:async()=>dom.window.JSON.parse(JSON.stringify(await r.json()))};};for(const script of document.querySelectorAll("script[src]")){assert(["app/kaufland-publication-view.js","app/assortment-overview.js"].includes(script.getAttribute("src")));dom.window.eval(fs.readFileSync(path.join(__dirname,"../",script.getAttribute("src")),"utf8"));}mounted={ready:flush()};}
  else mounted=Overview.mount(document,fetcher,client);
  const select=name=>[...document.querySelectorAll("#merchantFilter button")].find(button=>button.textContent===name).click();
  const query=value=>{document.getElementById("assortmentSearch").value=value;document.getElementById("assortmentSearch").dispatchEvent(new dom.window.Event("input"));};
  return{dom,document,calls,mounted,select,query,close:()=>dom.window.close()};
}
let groups=0;async function test(name,fn){try{await fn();groups++;}catch(error){console.error("Failed: "+name);throw error;}}
function publicationCard(document,id){return [...document.querySelectorAll(".publication-card")].find(card=>new URL(card.querySelector("a").href).searchParams.get("kloffer-articleID")===id);}
async function main(){
  await test("real HTML loads separate safe view before actual overview; master makes no publication fetch",async()=>{assert.deepEqual([...new JSDOM(html).window.document.querySelectorAll("script[src]")].map(s=>s.getAttribute("src")),["app/kaufland-publication-view.js","app/assortment-overview.js"]);const f=setup();try{await f.mounted.ready;assert.equal(f.document.getElementById("typeCount").textContent,"705");assert.equal(f.calls.length,1);assert.equal(f.document.getElementById("publicationPanel").hidden,true);assert.equal(f.document.querySelectorAll(".publication-card").length,0);}finally{f.close();}});
  await test("fifty genuine parser groups display separately from native article and taxonomy counts",async()=>{const before=JSON.stringify(originals),f=setup();try{await f.mounted.ready;f.document.getElementById("articlesTab").click();await flush();assert.equal(f.document.querySelectorAll(".article-card").length,1);assert.equal(f.document.querySelectorAll(".publication-card").length,0);f.select("Kaufland");await flush();assert.equal(f.document.querySelectorAll(".publication-card").length,50);assert.equal(f.document.querySelectorAll(".article-card").length,0);assert(f.document.getElementById("articleResult").textContent.includes("noch keine Artikel erfasst"));assert.equal(f.document.getElementById("typeCount").textContent,"705");assert(f.document.getElementById("publicationResult").textContent.includes("50 angekündigte Angebote"));assert(f.document.getElementById("publicationResult").textContent.includes("kein vollständiges Sortiment"));assert.equal(f.document.getElementById("loadMore").hidden,true);assert.equal(JSON.stringify(originals),before);}finally{f.close();}});
  await test("conditional Card XTRA and9.99 minimum12 milk never become cheap single-pack/winner choices",async()=>{const f=setup();try{await f.mounted.ready;f.document.getElementById("articlesTab").click();f.select("Kaufland");await flush();const club=publicationCard(f.document,"01202136"),milk=publicationCard(f.document,"00450098");assert(club.textContent.includes("Angekündigt: 0,99"));assert(club.textContent.includes("Mit Kaufland Card XTRA: 0,88"));assert(milk.textContent.includes("Mehrkauf: 9,99"));assert(milk.textContent.includes("12 Stück"));assert.equal(milk.querySelector(".announced-price"),null);assert(!milk.textContent.includes("0,84 €"));for(const card of f.document.querySelectorAll(".publication-card")){assert.equal(card.querySelectorAll("button,input,select,[data-gtin],[data-retailer-sku]").length,0);assert(card.textContent.includes("Ankündigung"));assert(card.textContent.includes("heutige Gültigkeit unbestätigt"));assert(!card.textContent.includes("Normalpreis"));assert(!card.textContent.includes("günstigster"));const link=card.querySelector("a");assert.equal(new URL(link.href).origin,"https://filiale.kaufland.de");assert.equal(link.target,"_blank");assert.equal(link.rel,"noopener noreferrer");}}finally{f.close();}});
  await test("Dickmann discrepancy and variable ranges retain visible comparison hold, not inferred pack identity",async()=>{const f=setup();try{await f.mounted.ready;f.document.getElementById("articlesTab").click();f.select("Kaufland");await flush();const dickmann=publicationCard(f.document,"01504659"),range=publicationCard(f.document,"01272955");assert(dickmann.textContent.includes("je 6 St. = 168-g-Packg."));assert(dickmann.textContent.includes("Angekündigt: 1,59"));assert(dickmann.querySelector(".publication-hold").textContent.includes("nicht im Preisvergleich"));assert(range.textContent.includes("je 450 - 500-g-Packg."));assert(range.querySelector(".publication-hold"));assert(!range.textContent.includes("Verkaufspackung:"));}finally{f.close();}});
  await test("dated old document display preserves actual original capture, not today or new expiry",async()=>{const f=setup();try{await f.mounted.ready;f.document.getElementById("articlesTab").click();f.select("Kaufland");await flush();const card=publicationCard(f.document,"01383309"),expected=new Intl.DateTimeFormat("de-DE",{dateStyle:"short",timeStyle:"short",timeZone:"Europe/Berlin"}).format(new Date(at));assert(card.querySelector(".last-seen").textContent.includes(expected));assert(card.querySelector(".last-seen").textContent.includes("Dokument abgerufen:"));assert(card.textContent.includes("heutige Gültigkeit unbestätigt"));assert.equal(parsed.promotionalPublications[0].publication.expiresAt,null);}finally{f.close();}});
  await test("late publisher result cannot cross a merchant token into PENNY",async()=>{let resolve;const f=setup({publicationReply:()=>new Promise(r=>{resolve=r;})});try{await f.mounted.ready;f.document.getElementById("articlesTab").click();f.select("Kaufland");assert(resolve);f.select("PENNY");resolve(jsonResponse(payload()));await flush();assert.equal(f.document.querySelectorAll(".publication-card").length,0);assert.equal(f.document.getElementById("publicationPanel").hidden,true);assert(f.document.getElementById("articleScope").textContent.includes("PENNY"));assert.equal(f.document.getElementById("typeCount").textContent,"705");}finally{f.close();}});
  await test("late publisher result after tab switch cannot mutate visible master or create cards",async()=>{let resolve;const f=setup({publicationReply:()=>new Promise(r=>{resolve=r;})});try{await f.mounted.ready;f.document.getElementById("articlesTab").click();f.select("Kaufland");f.document.getElementById("masterTab").click();resolve(jsonResponse(payload()));await flush();assert.equal(f.document.getElementById("articlesPanel").hidden,true);assert.equal(f.document.getElementById("masterPanel").hidden,false);assert.equal(f.document.querySelectorAll(".publication-card").length,0);assert.equal(f.document.getElementById("typeCount").textContent,"705");}finally{f.close();}});
  await test("search invalidates in-flight old result before debounce and binds new milk query",async()=>{const pending=[];const f=setup({publicationReply:url=>new Promise(resolve=>pending.push({url,resolve}))});try{await f.mounted.ready;f.document.getElementById("articlesTab").click();f.select("Kaufland");assert.equal(pending.length,1);f.query("Milch");pending[0].resolve(jsonResponse(payload()));await flush();assert.equal(f.document.querySelectorAll(".publication-card").length,0);assert.equal(f.document.getElementById("publicationPanel").hidden,true);await debounce();assert.equal(pending.length,2);assert.equal(pending[1].url.searchParams.get("search"),"Milch");pending[1].resolve(jsonResponse(payload("Milch")));await flush();assert.equal(f.document.querySelectorAll(".publication-card").length,1);assert(publicationCard(f.document,"00450098"));assert(f.document.getElementById("publicationResult").textContent.includes("1 angekündigte Angebote"));}finally{f.close();}});
  await test("late failure cannot erase newer successful query or show a private cause",async()=>{const pending=[];const f=setup({publicationReply:url=>new Promise((resolve,reject)=>pending.push({url,resolve,reject}))});try{await f.mounted.ready;f.document.getElementById("articlesTab").click();f.select("Kaufland");f.query("Milch");await debounce();pending[1].resolve(jsonResponse(payload("Milch")));await flush();assert.equal(f.document.querySelectorAll(".publication-card").length,1);pending[0].reject(Error("PRIVATE OLD ORIGINAL BODY"));await flush();assert.equal(f.document.querySelectorAll(".publication-card").length,1);assert(!f.document.body.textContent.includes("PRIVATE OLD"));assert(!f.document.getElementById("publicationResult").textContent.includes("nicht erreichbar"));}finally{f.close();}});
  await test("current HTTP/read failure clears earlier groups without older fallback or private disclosure",async()=>{let bad=false;const f=setup({publicationReply:async()=>bad?{ok:false,json:async()=>{throw Error("PRIVATE BODY");}}:jsonResponse(payload())});try{await f.mounted.ready;f.document.getElementById("articlesTab").click();f.select("Kaufland");await flush();assert.equal(f.document.querySelectorAll(".publication-card").length,50);bad=true;f.query("Milch");await debounce();assert.equal(f.document.querySelectorAll(".publication-card").length,0);assert(f.document.getElementById("publicationResult").textContent.includes("nicht erreichbar"));assert(!f.document.body.textContent.includes("PRIVATE BODY"));assert.equal(f.document.querySelectorAll(".article-card").length,0);}finally{f.close();}});
  await test("ambiguous latest snapshot displays explicit unknown state without revived groups",async()=>{const r=payload();r.promotionalPublications=[];Object.assign(r.promotionalPublicationCoverage,{acceptedGroups:0,heldGroups:50,matchedGroups:0,ambiguousLatestCapture:true});const f=setup({publicationReply:async()=>jsonResponse(r)});try{await f.mounted.ready;f.document.getElementById("articlesTab").click();f.select("Kaufland");await flush();assert.equal(f.document.querySelectorAll(".publication-card").length,0);assert(f.document.getElementById("publicationResult").textContent.includes("noch nicht eindeutig geprüft"));assert.equal(f.document.getElementById("typeCount").textContent,"705");}finally{f.close();}});
  await test("forged source/current/raw body envelope cannot leak through actual safe-view rendering",async()=>{const r=payload();r.promotionalPublications[0].publication.current=true;r.rawCapture="PRIVATE ORIGINAL HTML";const f=setup({publicationReply:async()=>jsonResponse(r)});try{await f.mounted.ready;f.document.getElementById("articlesTab").click();f.select("Kaufland");await flush();assert.equal(f.document.querySelectorAll(".publication-card").length,0);assert(f.document.getElementById("publicationResult").textContent.includes("nicht erreichbar"));assert(!f.document.body.textContent.includes("PRIVATE ORIGINAL"));assert.equal(f.document.querySelectorAll("script:not([src])").length,0);}finally{f.close();}});
  await test("missing view fails closed before publisher fetch, and other merchants never fetch Kaufland",async()=>{const f=setup({client:null});try{await f.mounted.ready;f.document.getElementById("articlesTab").click();f.select("Kaufland");await flush();assert(f.document.getElementById("publicationResult").textContent.includes("nicht verfügbar"));assert(!f.calls.some(url=>url.includes("kaufland-berlin-publications")));for(const name of["PENNY","EDEKA","Lidl","ALDI","REWE"]){f.select(name);await flush();assert.equal(f.document.getElementById("publicationPanel").hidden,true);}assert(!f.calls.some(url=>url.includes("kaufland-berlin-publications")));assert.equal(f.document.getElementById("typeCount").textContent,"705");}finally{f.close();}});
  await test("actual browser UMD scripts from real HTML bootstrap render same safe groups without real network",async()=>{const f=setup({browserBootstrap:true});try{await f.mounted.ready;await flush();assert.equal(f.document.getElementById("typeCount").textContent,"705");assert(f.dom.window.CaddyKauflandPublicationView);assert(f.dom.window.CaddyAssortmentOverview);f.document.getElementById("articlesTab").click();f.select("Kaufland");await flush();assert.equal(f.document.querySelectorAll(".publication-card").length,50);assert.equal(f.document.querySelectorAll(".article-card").length,0);assert.equal(f.document.getElementById("typeCount").textContent,"705");}finally{f.close();}});
  console.log("assortment-kaufland-publications: "+groups+" actual JSDOM/real HTML/mount/source-parser/client/card/multibuy/count/race/error groups passed; synthetic own-API fixtures only, no HTTP or SQL");
}
main().catch(error=>{console.error(error);process.exitCode=1;});
