"use strict";
const assert=require("node:assert/strict"),Directory=require("../assortment-article-directory"),Aldi=require("../aldi-assortment-article-service"),AldiClient=require("../aldi-assortment-client"),Wolt=require("../wolt-retailer-article-service"),WoltClient=require("../wolt-retailer-price-client"),woltFixture=require("./fixtures/retailers/wolt-edeka-berlin.json"),Rewe=require("../rewe-retailer-price-service"),fixture=require("./fixtures/retailers/aldi-public-assortment.json");
const now=Date.parse("2026-10-03T01:00:00.000Z"),at=new Date(now-1000).toISOString(),old=new Date(now-30*86400000).toISOString();
const pool={query(){throw Error("Directory must delegate validated native services; these units perform no database calls");}};
let checks=0;function check(fn){fn();checks++;}
function aldiArticle(patch={},capturedAt=old){
 const raw=structuredClone(fixture.product);raw.currentPrice=null;
 const parsed=AldiClient.parseProduct(raw,{...AldiClient.targetForUrl(fixture.sourceUrl),capturedAt,sourceResponseDate:capturedAt,sourceAgeSeconds:0,sourceResponseHash:"a".repeat(64)});assert.equal(parsed.ok,true);
 const checked=Aldi.validateArticle(parsed.product,{now});assert.equal(checked.ok,true);
 const {publicationAvailable,...article}=checked.article;
 return{...article,kind:"native-retailer-article",state:"last-observed",availability:"unknown",currentPriceVerified:false,physicalStorePriceVerified:false,normalPriceClassificationVerified:false,assortmentComplete:false,nativePublicationAvailableAtObservation:publicationAvailable,expiresAt:null,...patch};
}
function woltOffer(patch={},capturedAt=at){
 const venue=structuredClone(woltFixture.venueState.queries[0].state.data),native=structuredClone(woltFixture.pages[1].items[0]);
 // Explicit unit fixture. No original source record is retimed or imported.
 native.id="1dc18e85145be6774701f54d";native.name="LOCAL TEST Coca-Cola, 1 l";native.barcode_gtin="5449000017888";native.unit_info="1 l";native.options=[];native.variant=null;native.sell_by_weight_config=null;
 const venueIdentityProof={capturedAt,sourceResponseUrl:WoltClient.VENUE_API_URL,sourceResponseHash:"a".repeat(64),sourceResponseDate:capturedAt,sourceAgeSeconds:null},shop=WoltClient.parseNativeVenue(venue,venueIdentityProof);
 const result=WoltClient.parseArticles([native],{shop,capturedAt,sourceResponseUrl:WoltClient.API_ORIGIN+WoltClient.API_PATH+"/categories/slug/cola-cola-mix-127",sourceResponseHash:"b".repeat(64),sourceResponseDate:capturedAt,sourceAgeSeconds:null,venueIdentityProof,venueIdentityOriginal:venue});assert.equal(result.products.length,1,JSON.stringify(result.identityRejected));
 const checked=Wolt.validateArticle(result.products[0],{now});assert.equal(checked.ok,true,JSON.stringify(checked));const row=Wolt.rowForArticle(checked.article),{nativeWitness,storeId,...a}=checked.article;
 const view={...a,witnessHash:row.witness_hash,identityHash:row.identity_hash,captureHash:row.capture_hash,kind:"native-retailer-article",state:"last-observed",availability:"unknown",currentAvailabilityVerified:false,currentPriceVerified:false,physicalStorePriceVerified:false,normalPriceClassificationVerified:false,assortmentComplete:false,expiresAt:null};assert.equal(Wolt.validateView(view,{now}).ok,true);return{...view,...patch};
}
function reweOffer(patch={}){
 const raw={sourceId:Rewe.SOURCE,merchant:"REWE",nativeMarketId:Rewe.MARKET.nativeMarketId,nativeStoreId:Rewe.MARKET.nativeStoreId,retailerSku:"8-FKRIL2JI-"+Rewe.MARKET.nativeStoreId,retailerProductId:"9482185",nativeArticleId:"FKRIL2JI",gtin:"90486647",name:"LOCAL TEST Red Bull Glacier 0,25l",brand:"Red Bull",pack:"0.25 l",packAmount:.25,packUnit:"l",packCount:1,price:1.49,deposit:.25,displayedPrice:1.49,currency:"EUR",priceType:"unknown",promotionStatus:"unknown",availability:"unavailable",capturedAt:at,sourceUrl:"https://www.rewe.de/shop/p/red-bull-energy-drink-glacier-0-25l/9482185",sourceResponseUrl:"https://www.rewe.de/shop/api/products?marketId=8321066&serviceTypes=PICKUP&page=1&objectsPerPage=40",proofHash:"c".repeat(64),sourceResponseHash:"c".repeat(64),shop:{...Rewe.MARKET},scopeCountry:"DE",scopeChannel:"pickup",fulfillmentChannel:"pickup",serviceType:"PICKUP",priceBasis:"pack"};
 const checked=Rewe.validateOffer(raw,{now});assert.equal(checked.ok,true,JSON.stringify(checked));return{...checked.offer,...patch};
}
function services(rows={}){
 const calls=[],providers={};
 for(const [key,service,channel]of[["aldi",Aldi,"assortment-publication"],["wolt",Wolt,"online"],["rewe",Rewe,"pickup"]])providers[key]={search:async(received,options)=>{assert.equal(received,pool);calls.push({key,options});return{ok:true,items:rows[key]||[],...(key==="rewe"?{}:{scannedRows:(rows[key]||[]).length,nextOffset:options.offset+(rows[key]||[]).length,hasMore:(rows[key]||[]).length===options.limit&&options.offset+(rows[key]||[]).length<=10000}),sourceId:service.SOURCE,scopeCountry:"DE",scopeChannel:channel,truthEligible:false};}};
 return{providers,calls};
}
const moneyFields=["price","deposit","displayedPrice","nativePriceEUR","nativeDeposit","payablePackPrice","payablePrice","regularPrice","originalPrice","priceType","promotionStatus","currency","expiresAt","nativePromotionValidTo","priceBasis","nativePriceIncludesDeposit","depositIncludedInDisplayedPrice","shippingIncluded","serviceFeesIncluded","current"];
function noPrice(article){for(const field of moneyFields)assert.equal(Object.hasOwn(article,field),false,"Native directory must strip monetary/price authority field "+field);assert.equal(article.currentPriceVerified,false);assert.equal(article.physicalStorePriceVerified,false);assert.equal(article.truthEligible,false);assert.equal(article.assortmentComplete,false);assert.equal(article.availability,"unknown");assert.equal(article.state,"last-observed");assert.equal(article.productId,undefined);assert.equal(article.storeId,undefined);assert.equal(article.canonicalProductId,undefined);}
async function main(){
 check(()=>{assert.deepEqual(Directory.MERCHANTS,["PENNY","EDEKA","Lidl","ALDI","Kaufland","REWE"]);assert(Object.isFrozen(Directory.MERCHANTS));assert.equal(Directory.queryOptions({merchant:"ALDI",now}).limit,50);assert.equal(Directory.queryOptions({merchant:"ALDI",search:" Milch ",limit:"200",offset:"20",now}).search,"Milch");});
 const invalid=[null,[],new Date(),{}, {merchant:"ALDI Nord"},{merchant:"aldi"},{merchant:" ALDI"},{merchant:["ALDI","REWE"]},{merchant:"HIT"},{merchant:"dm"},{merchant:"REWE",search:""},{merchant:"REWE",search:"a"},{merchant:"REWE",search:"x".repeat(121)},{merchant:"REWE",search:["Milch","Butter"]},{merchant:"REWE",search:null},{merchant:"REWE",search:"Mi\u0000lch"},{merchant:"ALDI",limit:0},{merchant:"ALDI",limit:201},{merchant:"ALDI",limit:1.5},{merchant:"ALDI",limit:true},{merchant:"ALDI",limit:null},{merchant:"ALDI",limit:"1e2"},{merchant:"ALDI",limit:[2]},{merchant:"ALDI",offset:-1},{merchant:"ALDI",offset:10001},{merchant:"ALDI",offset:true},{merchant:"ALDI",offset:null},{merchant:"ALDI",offset:"01"},{merchant:"EDEKA",offset:10001},{merchant:"REWE",offset:1},{merchant:"ALDI",now:"2026-10-03"},{merchant:"ALDI",now:NaN},{merchant:"ALDI",now:-1},{merchant:"ALDI",gtin:"3017620422003"},{merchant:"ALDI",scopeChannel:"physical-store"},{merchant:"ALDI",sourceId:"unapproved"}];
 for(const query of invalid){const fake=services();await assert.rejects(()=>Directory.search(pool,query,fake.providers),/invalid-|offset-not-supported/);assert.equal(fake.calls.length,0);checks++;}
 await assert.rejects(()=>Directory.search(null,{merchant:"ALDI",now}),/database-required/);checks++;

 const original=aldiArticle(),before=JSON.stringify(original),ald=services({aldi:[original]});
 const browse=await Directory.search(pool,{merchant:"ALDI",now},ald.providers);
 check(()=>{assert.equal(browse.status,"observed-articles");assert.deepEqual(ald.calls,[{key:"aldi",options:{merchant:"ALDI Nord",limit:50,scopeChannel:"assortment-publication",now,offset:0}}]);assert.equal(browse.items.length,1);assert.equal(browse.items[0].observedAt,old);assert.equal(browse.items[0].merchant,"ALDI");assert.equal(browse.items[0].sourceMerchant,"ALDI Nord");assert.equal(browse.items[0].gtin,null);assert.equal(browse.items[0].packAmount,1000);assert.equal(browse.items[0].packUnit,"ml");assert.equal(browse.items[0].packCount,1);assert.equal(browse.items[0].locationScope,"unknown");assert.equal(browse.items[0].shop,null);assert.equal(browse.independentOfPrice,true);assert.equal(browse.pricedOnly,false);assert.equal(browse.total,null);assert.equal(browse.assortmentComplete,false);noPrice(browse.items[0]);assert.equal(JSON.stringify(original),before);});
 await Directory.search(pool,{merchant:"ALDI",search:"Milk%_",limit:2,offset:10000,now},ald.providers);
 check(()=>{assert.equal(ald.calls[1].options.search,"Milk%_");assert.equal(ald.calls[1].options.offset,10000);assert.equal(ald.calls[1].options.limit,2);});

 const wolt=woltOffer({extraPriceLeak:999,ean:"fake-alias"}),woltSameGtin=woltOffer({retailerSku:"134440f9c36e0a550f7dcd6e"}),ed=services({wolt:[wolt,woltSameGtin]});
 const edeka=await Directory.search(pool,{merchant:"EDEKA",search:"Coca-Cola",limit:2,now},ed.providers);
 check(()=>{assert.equal(ed.calls.length,1);assert.equal(ed.calls[0].key,"wolt");assert.equal(ed.calls[0].options.merchant,"EDEKA");assert.equal(ed.calls[0].options.offset,0);assert.equal(edeka.items.length,2,"Same GTIN and pack do not merge different native SKUs");assert.equal(new Set(edeka.items.map(x=>x.identityKey)).size,2);assert.equal(new Set(edeka.items.map(x=>x.gtin)).size,1);for(const article of edeka.items){noPrice(article);assert.equal(article.observedAt,at);assert.equal(article.scopeChannel,"online");assert.equal(article.locationScope,"native-venue");assert.equal(article.shop.nativeVenueId,Wolt.VENUE.nativeVenueId);assert.equal(article.shop.city,"Berlin");assert.equal(article.extraPriceLeak,undefined);assert.equal(article.ean,undefined);}assert.equal(edeka.pricedOnly,false);assert.equal(edeka.independentOfPrice,true);assert.equal(edeka.total,null);});
 const rw=services({rewe:[reweOffer()]});const rewe=await Directory.search(pool,{merchant:"REWE",now},rw.providers);
 check(()=>{assert.equal(rewe.items.length,1,"A last-observed article is not silently hidden because the source currently says unavailable");noPrice(rewe.items[0]);assert.equal(rewe.items[0].scopeChannel,"pickup");assert.equal(rewe.items[0].locationScope,"pickup-market");assert.equal(rewe.items[0].shop.nativeMarketId,Rewe.MARKET.nativeMarketId);assert.equal(rewe.items[0].shop.serviceType,"PICKUP");assert.equal(rewe.items[0].shop.address,"Hallesches Ufer 40");assert.equal(rewe.independentOfPrice,false);});

 for(const merchant of["PENNY","Lidl","Kaufland"]){const fake=services(),result=await Directory.search(pool,{merchant,search:"Milch",now},fake.providers);check(()=>{assert.equal(result.status,"unsupported-source");assert.equal(result.reason,"no-captured-article-source");assert.equal(result.sourceId,null);assert.equal(result.total,null);assert.equal(result.independentOfPrice,null);assert.equal(result.assortmentComplete,false);assert.deepEqual(result.items,[]);assert.equal(fake.calls.length,0);assert(result.note.includes("keine Aussage"));});}
 for(const merchant of["ALDI","EDEKA","REWE"]){const fake=services(),result=await Directory.search(pool,{merchant,now},fake.providers);check(()=>{assert.equal(result.status,"no-observed-articles");assert.equal(result.reason,"no-matching-captured-articles");assert.equal(result.total,null);assert.equal(result.assortmentComplete,false);assert.deepEqual(result.items,[]);assert.equal(fake.calls.length,1,"An empty search string is not required to browse the supported native ledger");});}

 const aldiBad=[{sourceId:"ALDI nationwide"},{merchant:"ALDI Süd"},{gtin:"3017620422003"},{scopeCountry:"AT"},{scopeChannel:"physical-store"},{locationScope:"Berlin"},{storeId:"imaginary"},{price:1.19},{deposit:.25},{expiresAt:new Date(now+1000).toISOString()},{availability:"available"},{currentPriceVerified:true},{assortmentComplete:true},{packAmount:1},{packCount:2},{variant:"Verschiedene Sorten"},{sourceResponseHash:"not-proof"},{sourceAgeSeconds:301},{observedAt:new Date(now+1).toISOString()},{sourceResponseDate:new Date(Date.parse(old)+400000).toISOString()},{retailerSku:"1939"},{nativePublicationAvailableAtObservation:undefined}];
 for(const patch of aldiBad){const fake=services({aldi:[aldiArticle(patch)]}),result=await Directory.search(pool,{merchant:"ALDI",now},fake.providers);check(()=>{assert.equal(result.items.length,0,JSON.stringify(patch));assert.equal(result.excludedRows,1);assert.equal(result.assortmentComplete,false);});}
 const woltBad=[{sourceId:"Wolt nahkauf Berlin Wrangelstraße"},{merchant:"nahkauf"},{nativeVenueId:"0".repeat(24)},{gtin:"5449000017880"},{scopeCountry:"AT"},{scopeChannel:"physical-store"},{pack:"ca.1 l"},{packCount:2},{retailerSku:"synthetic"},{shop:{...Wolt.VENUE,city:"Hamburg"}},{sourceUrl:"https://wolt.com/de/deu/berlin/venue/another-shop"},{sourceResponseHash:"bad"},{observedAt:new Date(now+1).toISOString()},{expiresAt:"2099-01-01T00:00:00.000Z"},{nativeWitness:{}},{currentAvailabilityVerified:true},{name:"Milka Tender Milch 5 x 37 g",pack:"37 g",packAmount:37,packUnit:"g",packCount:1}];
 for(const patch of woltBad){const fake=services({wolt:[woltOffer(patch)]});fake.providers.wolt.validateView=()=>({ok:true,article:woltOffer()});const result=await Directory.search(pool,{merchant:"EDEKA",now},fake.providers);check(()=>{assert.equal(result.items.length,0,JSON.stringify(patch));assert.equal(result.excludedRows,1,"Injected search cannot replace the real closed-source validator");});}
 const reweBad=[{scopeChannel:"online"},{nativeMarketId:"9999999"},{nativeStoreId:"ffffffff-fa98-3b7e-9ee5-8132f39c189c"},{gtin:"90486640"},{shop:{...Rewe.MARKET,address:"Other Street 40"}},{retailerSku:"fake"},{nativePriceIncludesDeposit:true},{nativePromotionValidTo:new Date(now-1).toISOString()},{expiresAt:new Date(now+2*86400000).toISOString()}];
 for(const patch of reweBad){const fake=services({rewe:[reweOffer(patch)]}),result=await Directory.search(pool,{merchant:"REWE",now},fake.providers);check(()=>assert.equal(result.items.length,0,JSON.stringify(patch)));}
 const staleCapture=new Date(now-30*86400000).toISOString(),oldNative=await Directory.search(pool,{merchant:"EDEKA",offset:100,now},services({wolt:[woltOffer({},staleCapture)]}).providers);
 check(()=>{assert.equal(oldNative.items.length,1,"Native identities survive price expiry without renewing the original observation");assert.equal(oldNative.items[0].observedAt,staleCapture);assert.equal(oldNative.offsetSupported,true);noPrice(oldNative.items[0]);});
 const expired=await Directory.search(pool,{merchant:"REWE",now},services({rewe:[reweOffer({capturedAt:new Date(now-86400000).toISOString(),expiresAt:new Date(now).toISOString()})]}).providers);check(()=>assert.equal(expired.items.length,0,"REWE priced-only captures retain their expiry boundary"));
 const unknownGtin=services({wolt:[woltOffer({gtin:null,ean:"5449000017888"})]});
 check(()=>assert.equal(Directory.queryOptions({merchant:"ALDI",now}).offset,0));
 const unknown=await Directory.search(pool,{merchant:"EDEKA",now},unknownGtin.providers);check(()=>{assert.equal(unknown.items.length,1);assert.equal(unknown.items[0].gtin,null,"Do not invent GTIN from alias fields");});
 const multipack=woltOffer({gtin:null,name:"LOCAL TEST Water 6 x 0.5 l",pack:"6 x 500 ml",nativeUnitInfo:"6 x 500 ml",packAmount:500,packUnit:"ml",packCount:6}),multi=await Directory.search(pool,{merchant:"EDEKA",now},services({wolt:[multipack]}).providers);
 check(()=>{assert.equal(multi.items.length,1);assert.equal(multi.items[0].packAmount,500);assert.equal(multi.items[0].packUnit,"ml");assert.equal(multi.items[0].packCount,6);assert.equal(multi.items[0].pack,"6 x 500 ml");noPrice(multi.items[0]);});
 const promotionEnd=new Date(now+60000).toISOString(),promotion=reweOffer({nativePromotionValidTo:promotionEnd,expiresAt:promotionEnd});
 const promoResult=await Directory.search(pool,{merchant:"REWE",now},services({rewe:[promotion]}).providers);check(()=>{assert.equal(promoResult.items.length,1);noPrice(promoResult.items[0]);assert.equal(promoResult.items[0].observedAt,at);});
 const ended=await Directory.search(pool,{merchant:"REWE",now:now+60000},services({rewe:[promotion]}).providers);check(()=>assert.equal(ended.items.length,0,"The original promotion expiry remains effective after stripping price fields"));

 const duplicates=services({wolt:[woltOffer(),woltOffer()]});const dedup=await Directory.search(pool,{merchant:"EDEKA",now},duplicates.providers);check(()=>assert.equal(dedup.items.length,1));
 const contradictory=services({wolt:[woltOffer(),woltOffer({gtin:"4100290068608"})]});const conflict=await Directory.search(pool,{merchant:"EDEKA",now},contradictory.providers);check(()=>{assert.equal(conflict.items.length,0,"Same native SKU/capture with conflicting identity fails closed");assert.equal(conflict.excludedRows,2);});
 const newerAt=new Date(now-500).toISOString(),dated=services({wolt:[woltOffer(),woltOffer({name:"LOCAL TEST latest native title"},newerAt)]});const latest=await Directory.search(pool,{merchant:"EDEKA",now},dated.providers);check(()=>{assert.equal(latest.items.length,1);assert.equal(latest.items[0].observedAt,newerAt);assert.equal(latest.items[0].name,"LOCAL TEST latest native title");});
 for(const response of[{items:[],scopeCountry:"AT",scopeChannel:"online",truthEligible:false},{items:[],scopeCountry:"DE",scopeChannel:"physical-store",truthEligible:false},{items:[],scopeCountry:"DE",scopeChannel:"online",truthEligible:true},{items:Array(2).fill(woltOffer()),scopeCountry:"DE",scopeChannel:"online",truthEligible:false},{items:{},scopeCountry:"DE",scopeChannel:"online",truthEligible:false},{ok:false,items:[],scopeCountry:"DE",scopeChannel:"online",truthEligible:false}]){await assert.rejects(()=>Directory.search(pool,{merchant:"EDEKA",limit:1,now},{wolt:{search:async()=>response}}),/invalid-article-directory-source-response/);checks++;}
 const filteredNativePage={ok:true,items:[],sourceId:Wolt.SOURCE,scopeCountry:"DE",scopeChannel:"online",truthEligible:false,scannedRows:50,nextOffset:150,hasMore:true},filteredNative=await Directory.search(pool,{merchant:"EDEKA",offset:100,now},{wolt:{search:async()=>filteredNativePage}});check(()=>{assert.equal(filteredNative.items.length,0);assert.equal(filteredNative.excludedRows,50);assert.equal(filteredNative.nextOffset,150);assert.equal(filteredNative.hasMore,true,"An entirely filtered raw SQL page must keep the later native pages reachable");assert.equal(filteredNative.assortmentComplete,false);});
 for(const patch of[{scannedRows:51},{scannedRows:"50"},{nextOffset:101},{hasMore:false},{scannedRows:49,nextOffset:149,hasMore:true}]){await assert.rejects(()=>Directory.search(pool,{merchant:"EDEKA",offset:100,now},{wolt:{search:async()=>({...filteredNativePage,...patch})}}),/invalid-article-directory-source-(pagination|count)/);checks++;}
 const failure=Error("original-DB-read-failed");await assert.rejects(()=>Directory.search(pool,{merchant:"ALDI",now},{aldi:{search:async()=>{throw failure;}}}),error=>error===failure);checks++;

 const statuses={
  aldi:{status:async(received,options)=>{assert.equal(received,pool);assert.deepEqual(options,{now});return{ok:true,sourceId:Aldi.SOURCE,merchant:Aldi.MERCHANT,scopeCountry:"DE",scopeChannel:"assortment-publication",storedArticles:100,heldArticles:10,lastObservedArticles:90,lastObservedAt:old};}},
  wolt:{status:async()=>({ok:true,sourceId:Wolt.SOURCE,merchant:Wolt.MERCHANT,scopeCountry:"DE",scopeChannel:"online",storedArticles:1000,heldArticles:0,lastObservedArticles:900,excludedInvalidArticles:100,lastObservedAt:old})},
  rewe:{status:async()=>({ok:true,scopeCountry:"DE",scopeChannel:"pickup",storedPrices:100,currentPrices:0,lastCapturedAt:old})}
 };
 const status=await Directory.status(pool,{now},statuses);check(()=>{assert.equal(status.merchants.length,6);assert.equal(status.total,null);assert.equal(status.assortmentComplete,false);const aldi=status.merchants.find(x=>x.merchant==="ALDI"),edeka=status.merchants.find(x=>x.merchant==="EDEKA"),rewe=status.merchants.find(x=>x.merchant==="REWE");assert.equal(aldi.lastObservedArticles,90);assert.equal(aldi.heldArticles,10);assert.equal(aldi.independentOfPrice,true);assert.equal(aldi.countBasis,"native-article-ledger");assert.equal(aldi.currentNativePricedRows,null);assert.equal(edeka.lastObservedArticles,900);assert.equal(edeka.pricedOnly,false);assert.equal(edeka.independentOfPrice,true);assert.equal(edeka.countBasis,"native-article-ledger");assert.equal(rewe.status,"no-observed-articles");for(const merchant of["PENNY","Lidl","Kaufland"]){const empty=status.merchants.find(x=>x.merchant===merchant);assert.equal(empty.status,"unsupported-source");assert.equal(empty.lastObservedArticles,null);assert.equal(empty.storedNativeRows,null);}assert.equal(status.productsWithCurrentPublishedPrices,undefined);});
 await assert.rejects(()=>Directory.status(pool,{merchant:"ALDI",now},statuses),/invalid-article-directory-query/);checks++;
 await assert.rejects(()=>Directory.status(pool,{now},{...statuses,wolt:{status:async()=>({ok:true,sourceId:Wolt.SOURCE,merchant:Wolt.MERCHANT,scopeCountry:"DE",scopeChannel:"online",storedArticles:1,heldArticles:0,lastObservedArticles:2})}}),/invalid-article-directory-source-count/);checks++;
 await assert.rejects(()=>Directory.status(pool,{now},{...statuses,aldi:{status:async()=>({ok:true,sourceId:Aldi.SOURCE,merchant:Aldi.MERCHANT,scopeCountry:"DE",scopeChannel:"assortment-publication",storedArticles:100,heldArticles:10,lastObservedArticles:91})}}),/invalid-article-directory-source-count/);checks++;
 const originalPgTime=new Date(now-613),pgDate=await Directory.status(pool,{now},{...statuses,wolt:{status:async()=>({ok:true,sourceId:Wolt.SOURCE,merchant:Wolt.MERCHANT,scopeCountry:"DE",scopeChannel:"online",storedArticles:10,heldArticles:0,lastObservedArticles:2,lastObservedAt:originalPgTime})}});
 check(()=>assert.equal(pgDate.merchants.find(x=>x.merchant==="EDEKA").lastObservedAt,originalPgTime.toISOString(),"Preserve PostgreSQL Date milliseconds without rounding or inventing another capture"));
 const futureDate=await Directory.status(pool,{now},{...statuses,wolt:{status:async()=>({ok:true,sourceId:Wolt.SOURCE,merchant:Wolt.MERCHANT,scopeCountry:"DE",scopeChannel:"online",storedArticles:10,heldArticles:0,lastObservedArticles:2,lastObservedAt:new Date(now+1)})}});
 check(()=>assert.equal(futureDate.merchants.find(x=>x.merchant==="EDEKA").lastObservedAt,null));
 await assert.rejects(()=>Directory.status(pool,{now},{...statuses,wolt:{status:async()=>({ok:true,sourceId:Wolt.SOURCE,merchant:Wolt.MERCHANT,scopeCountry:"DE",scopeChannel:"online",storedArticles:"",heldArticles:0,lastObservedArticles:0})}}),/invalid-article-directory-source-count/);checks++;
 console.log(`assortment-article-directory: ${checks} groups passed; six exact merchants, dated SKU identities, no GTIN merge or price/stock truth, isolated channel scopes, bounded validated browse/search and honest separate counts`);
}
main().catch(error=>{console.error(error);process.exitCode=1;});
