"use strict";
const assert=require('node:assert/strict'),Client=require('../app/berlin-reference-client'),Current=require('../app/current-price-client');
const now=Date.parse('2026-10-02T16:00:00Z'),capturedAt=new Date(now-60000).toISOString(),expiresAt=new Date(now-60000+86400000).toISOString();
const offer={sourceId:'Wolt EDEKA Berlin',merchant:'EDEKA',nativeVenueId:'67ebb70ed3581534a525c522',retailerSku:'1dc18e85145be6774701f54d',gtin:'4046700026519',name:'UNIT TEST Milch 1,5%',brand:null,pack:'1 l',packAmount:1000,packUnit:'ml',packCount:1,price:1.29,deposit:null,displayedPrice:1.29,nativePriceIncludesDeposit:true,payablePackPrice:null,currency:'EUR',priceBasis:'pack',capturedAt,expiresAt,proofHash:'a'.repeat(64),sourceUrl:'https://wolt.com/de/deu/berlin/venue/edeka-hilbrecht',shop:{name:'EDEKA Hilbrecht',address:'Ritterstr. 38-40',postalCode:'10969',city:'Berlin',country:'DE',nativeVenueId:'67ebb70ed3581534a525c522'},scopeCountry:'DE',scopeChannel:'online',state:'published',current:true,truthEligible:false,shippingIncluded:false,serviceFeesIncluded:false};
function row(patch={}){const o={...offer,...patch};return{offer:o,reference:{kind:'last-observed',city:'Berlin',country:'DE',merchant:o.merchant,key:JSON.stringify([o.merchant,o.gtin||o.retailerSku,o.pack,o.scopeChannel]),identityKind:o.gtin?'native-gtin':'native-retailer-sku',observedAt:o.capturedAt,sourceMarket:o.shop,observedMarkets:1,knownPriceRange:{min:o.price,max:o.price}}};}
(async()=>{const input=row(),before=JSON.stringify(input),valid=Client.candidate(input,{now});assert(valid);assert.equal(valid.offer.price,1.29);assert.equal(valid.offer.truthEligible,false);assert.equal(valid.reference.sourceMarket.city,'Berlin');assert.equal(JSON.stringify(input),before);
 const native=row({gtin:null});assert(Client.candidate(native,{now}));assert.equal(Current.normalizePublishedAlternative(native.offer,{pack:'1 l'},{now}),null,'Native article references never turn into canonical GTIN matches');
 for(const patch of[{shop:{...offer.shop,city:'Potsdam'}},{shop:{...offer.shop,address:'Other store'}},{scopeCountry:'AT'},{scopeChannel:'physical-store'},{sourceId:'dm online',merchant:'dm'},{nativeVenueId:'0'.repeat(24)},{gtin:'4046700026518'},{retailerSku:'madeup'},{pack:'ca. 1 l'},{packCount:2},{price:1.295},{capturedAt:new Date(now+1).toISOString()},{expiresAt:new Date(now).toISOString()},{truthEligible:true},{shippingIncluded:true}])assert.equal(Client.candidate(row(patch),{now}),null,JSON.stringify(patch));
 for(const patch of[{city:'Hamburg'},{observedAt:new Date(now).toISOString()},{sourceMarket:{...offer.shop,address:'Another reference branch'}},{identityKind:'native-retailer-sku'},{observedMarkets:0},{knownPriceRange:{min:1.5,max:2}}])assert.equal(Client.candidate({...input,reference:{...input.reference,...patch}},{now}),null,JSON.stringify(patch));
 const response={ok:true,city:'Berlin',country:'DE',items:[input],bounded:true};assert.equal(Client.normalizeResponse(response,{now}).items.length,1);assert.equal(Client.normalizeResponse({...response,items:[input,input]},{now}).items.length,0,'Duplicate reference keys cannot silently merge records');assert.equal(Client.normalizeResponse({...response,city:'Hamburg'},{now}).ok,false);
 assert.equal(Client.request({gtin:offer.gtin,pack:'1 l'}).gtin,offer.gtin);assert.throws(()=>Client.request({search:'Milch',region:'Berlin'}));assert.throws(()=>Client.request({search:'Milch',scopeChannel:'all'}));assert.throws(()=>Client.request({gtin:'4046700026518'}));
 for(const query of[{gtin:'4008400401621'},{gtin:offer.gtin,pack:'2 x 500 ml'},{gtin:offer.gtin,pack:'500 ml'},{search:'Butter'},{search:'Milch',merchant:'REWE'},{search:'Milch',scopeChannel:'pickup'}])assert.equal(Client.normalizeResponse(response,{now,request:query}).items.length,0,'Returned offer must match the requested identity: '+JSON.stringify(query));
 assert.equal(Client.normalizeResponse(response,{now,request:{search:'Milch',pack:'1000 ml',merchant:'EDEKA',scopeChannel:'online'}}).items.length,1);assert.equal(Client.normalizeResponse(response,{now}).truncated,false);
 for(const query of[{search:5},{search:'Milch',gtin:5},{search:'Milch',merchant:''}])assert.throws(()=>Client.request(query));
 const rewe=row({sourceId:'REWE Berlin pickup',merchant:'REWE',nativeVenueId:null,nativeMarketId:'8321066',retailerSku:'8-FKRIL2JI-7ae33841-fa98-3b7e-9ee5-8132f39c189c',sourceUrl:'https://www.rewe.de/shop/p/test-milk/9482185',scopeChannel:'pickup',nativePriceIncludesDeposit:false,shop:{name:'REWE Steven Horn oHG',address:'Hallesches Ufer 40',postalCode:'10963',city:'Berlin',country:'DE',nativeMarketId:'8321066'}});assert(Client.candidate(rewe,{now}),'Native composite REWE listing remains eligible');
 let calls=0;const api=Client.create({apiBase:'https://example.test',now:()=>now,fetchImpl:async(url,options)=>{calls++;const u=new URL(url);assert.equal(u.pathname,'/v1/berlin-reference-prices');assert.equal(u.searchParams.get('gtin'),offer.gtin);assert.equal(options.credentials,'omit');assert(!options.body);return{ok:true,json:async()=>response};}});assert.equal((await api.search({gtin:offer.gtin,pack:'1 l'})).items.length,1);assert.equal(calls,1);assert.equal((await api.search({search:'x'})).ok,false);assert.equal(calls,1);
 const unavailable=Client.create({now:()=>now,fetchImpl:async()=>{throw Error('offline');}});assert.deepEqual((await unavailable.search({search:'Milch'})).items,[]);
 console.log('berlin-reference-client: branch proof, original freshness, native-SKU separation, channel/deposit boundaries and bounded request failure handling OK');
})().catch(error=>{console.error(error);process.exitCode=1;});
