"use strict";
const assert=require('assert/strict'),fs=require('fs'),{JSDOM,VirtualConsole}=require('jsdom');
const gtin='4046700026519';
function quote(patch={}){const capturedAt=new Date(Date.now()-1000).toISOString(),offer={sourceId:'Wolt EDEKA Berlin',merchant:'EDEKA',nativeVenueId:'67ebb70ed3581534a525c522',retailerSku:'1dc18e85145be6774701f54d',gtin,name:'BROWSER TEST Milch 1,5%',brand:null,pack:'1 l',packAmount:1000,packUnit:'ml',packCount:1,price:1.29,deposit:null,displayedPrice:1.29,nativePriceIncludesDeposit:true,payablePackPrice:null,currency:'EUR',priceBasis:'pack',capturedAt,expiresAt:new Date(Date.now()+3600000).toISOString(),proofHash:'a'.repeat(64),sourceUrl:'https://wolt.com/de/deu/berlin/venue/edeka-hilbrecht',shop:{name:'EDEKA Hilbrecht',address:'Ritterstr. 38-40',postalCode:'10969',city:'Berlin',country:'DE',nativeVenueId:'67ebb70ed3581534a525c522'},scopeCountry:'DE',scopeChannel:'online',state:'published',current:true,truthEligible:false,shippingIncluded:false,serviceFeesIncluded:false,...patch};return{offer,reference:{kind:'last-observed',city:'Berlin',country:'DE',merchant:offer.merchant,key:JSON.stringify([offer.gtin||offer.retailerSku,offer.pack]),identityKind:offer.gtin?'native-gtin':'native-retailer-sku',observedAt:offer.capturedAt,sourceMarket:offer.shop,observedMarkets:1,knownPriceRange:{min:offer.price,max:offer.price}}};}
async function setup(){const errors=[],calls=[],vc=new VirtualConsole();vc.on('jsdomError',e=>errors.push(e.message));let next=quote(),hold=null;
 const dom=new JSDOM(fs.readFileSync('index.html','utf8'),{runScripts:'dangerously',url:'https://julienfehlberg.github.io/Echtpreis/',pretendToBeVisual:true,virtualConsole:vc,beforeParse(w){
  w.AbortController=global.AbortController;w.SPARKORB_CONFIG={apiBase:'https://prices.example.test'};
  w.fetch=async(input)=>{const u=new URL(String(input),w.location.href);if(u.pathname==='/v1/berlin-reference-prices'){calls.push(u);const row=next,dated=row?.publication?.kind==='dated-national-price-publication';if(hold){const wait=hold;hold=null;await wait;}return{ok:true,json:async()=>({ok:true,city:'Berlin',country:'DE',items:row?.publication?[]:[row],publications:row?.publication&&!dated?[row]:[],datedPublications:dated?[row]:[],bounded:true,truncated:false})};}return{ok:false,status:503,json:async()=>({})};};
  for(const file of ['app/price-engine.js','wolt-sales-pack-validation.js','app/current-price-client.js','app/published-product-client.js','app/penny-reference-client.js','app/lidl-reference-client.js','app/berlin-reference-client.js','shopping-need-matcher.js'])w.eval(fs.readFileSync(file,'utf8'));
  w.alert=()=>{};w.confirm=()=>true;w.prompt=()=>null;w.scrollTo=()=>{};w.HTMLElement.prototype.scrollIntoView=function(){};
  Object.defineProperty(w.navigator,'geolocation',{configurable:true,value:{getCurrentPosition:()=>{throw Error('Location must not be required')}}});
  w.localStorage.setItem('sparkorb_receipt_consent','0');
 }});await new Promise(resolve=>setTimeout(resolve,60));
 return{dom,w:dom.window,calls,errors,set(row){next=row;},hold(){let release;hold=new Promise(resolve=>{release=resolve});return release;}};
}
async function waitFor(fn){for(let i=0;i<150;i++){if(fn())return;await new Promise(r=>setTimeout(r,5));}throw Error('Expected Berlin reference UI did not appear');}
(async()=>{const f=await setup(),w=f.w,d=w.document;try{
 w.eval("selected=new Set(['ALDI','PENNY','REWE','Lidl','Kaufland','EDEKA']);verifiedPriceLocation=null;nearbyStores=[];basket=[parseWish('1 l Milch')];comparisonRevision++;hasCompared=false;");
 await w.compare({skipLocation:true,scroll:false});const section=d.getElementById('berlinReferenceComparison');assert.equal(section.style.display,'block');assert(section.textContent.includes('EDEKA Hilbrecht'));assert(section.textContent.includes('Ritterstr. 38-40'));assert(section.textContent.includes('1,29'));assert(section.textContent.includes('Lieferung'));assert(section.textContent.includes('Pfand unbekannt'));assert(section.textContent.includes('Preisart offen'));assert(section.textContent.includes('Stand'));assert(!section.textContent.includes('Durchschnitt'));assert(section.textContent.includes('Noch kein passender Berliner Preisbeleg: ALDI, PENNY, REWE, Lidl, Kaufland'));assert.equal(f.calls[0].searchParams.get('pack'),'1 l');assert.equal(d.getElementById('storeComparisonDetails').open,false);assert.equal(d.getElementById('physicalComparison').style.display,'none');
 w.eval("basket[0].selectedProduct={gtin:'4046700026519',name:'Milch',brand:null,pack:'1 l',packAmount:1000,packUnit:'ml',packCount:1};comparisonRevision++;");f.set(quote({pack:'500 ml',packAmount:500}));await w.compare({skipLocation:true,scroll:false});assert(!section.textContent.includes('1,29'),'Different sales pack must not populate exact shopping item');assert.equal(f.calls.at(-1).searchParams.get('gtin'),gtin);assert.equal(f.calls.at(-1).searchParams.get('pack'),'1 l');
 f.set(quote({expiresAt:new Date(Date.now()-1).toISOString()}));await w.compare({skipLocation:true,scroll:false});assert(!section.textContent.includes('1,29'),'Expired quote must disappear');
 w.eval('delete basket[0].selectedProduct;comparisonRevision++;');f.set(quote({gtin:null}));await w.compare({skipLocation:true,scroll:false});assert(section.textContent.includes('1,29'),'Native SKU reference must remain visible without invented GTIN');assert(!w.eval('basket[0].selectedProduct'));
 f.set(quote());w.eval('comparisonRevision++;');let releaseCanonical;w.loadCanonicalComparison=()=>new Promise(resolve=>{releaseCanonical=resolve});const pending=w.compare({skipLocation:true,scroll:false});await waitFor(()=>section.style.display==='block'&&section.textContent.includes('1,29'));assert.equal(d.getElementById('results').style.display,'block');assert.equal(d.getElementById('storeComparisonDetails').style.display,'none','Old results stay hidden while they load');releaseCanonical();await pending;
 w.loadCanonicalComparison=async()=>{};f.set(quote());const release=f.hold(),before=f.calls.length,stale=w.compare({skipLocation:true,scroll:false});await waitFor(()=>f.calls.length>before);w.eval("basket=[parseWish('250 g Butter')];comparisonRevision++;");f.set(quote({gtin:'4008400401621',name:'BROWSER TEST Butter',pack:'250 g',packAmount:250,packUnit:'g',price:2.19,displayedPrice:2.19}));await w.compare({skipLocation:true,scroll:false});release();await stale;assert(section.textContent.includes('Butter'));assert(section.textContent.includes('2,19'));assert(!section.textContent.includes('1,29'),'Old basket response cannot overwrite newer results');assert.deepEqual(f.errors,[]);
 w.eval("basket=[parseWish('250 g Butter')];comparisonRevision++;");f.set(quote({gtin:'4008400401621',name:'Milram Buttermilchquark',pack:'250 g',packAmount:250,packUnit:'g'}));await w.compare({skipLocation:true,scroll:false});assert(!section.textContent.includes('Buttermilchquark'),'Butter substring is not butter evidence');
 w.eval("basket=[parseWish('1 l Milch 1,5%')];comparisonRevision++;");f.set(quote({name:'BROWSER TEST Hafermilch 1,5%'}));await w.compare({skipLocation:true,scroll:false});assert(!section.textContent.includes('Hafermilch'),'Plant substitute is not default milk');f.set(quote({name:'BROWSER TEST Milch 3,5%'}));await w.compare({skipLocation:true,scroll:false});assert(!section.textContent.includes('Milch 3,5%'),'Contradictory explicit milk fat is excluded');f.set(quote({name:'BROWSER TEST Milch'}));await w.compare({skipLocation:true,scroll:false});assert(section.textContent.includes('BROWSER TEST Milch'));assert(section.textContent.includes('Fehlende Angaben'),'Unknown desired properties stay open');
 w.eval("basket=[parseWish('1 l Milch')];comparisonRevision++;");
 for(const name of ['Elkos Body Cremeseife Milch & Honig, 1 l','Elkos Body Cremebad Milch & Honig, 1 l','Reinigungsmilch mit Milch & Honig, 1 l']){f.set(quote({name}));await w.compare({skipLocation:true,scroll:false});assert(!section.textContent.includes(name),'Cosmetic milk names cannot populate a food wish: '+name);}
 for(const raw of ['1 l Vollmilch 3,5%','1 l fettarme Milch 1,5%','Milch 1,5% laktosefrei mit Vanille']){w.eval("basket=[{...parseWish('1 l Milch'),raw:"+JSON.stringify(raw)+",label:"+JSON.stringify(raw)+"}];comparisonRevision++;");f.set(quote({name:'BROWSER TEST Milch 3,5%'}));await w.compare({skipLocation:true,scroll:false});assert(!section.textContent.includes('1,29'),'Unsupported qualifier must not erase explicit constraints: '+raw);assert(section.textContent.includes('Bitte wähle ein konkretes Produkt'));}
 const Pub=require('../penny-berlin-publications'),capture=require('./helpers/penny-capture-fixture').capture;
 const native=Pub.parseCapture(capture(Date.now()-1000)).publications[0];
 w.eval("basket=[{...parseWish('125 g Schoko'),label:'Schoko',raw:'125 g Schoko',key:'penny_reference_test',packLabel:'125 g'}];comparisonRevision++;");f.set(native);await w.compare({skipLocation:true,scroll:false});
 assert(section.textContent.includes('Penny Emser Straße'));assert(section.textContent.includes('Emser Str. 1-2'));assert(section.textContent.includes('1,49'));assert(section.textContent.includes('Regionale Preisveröffentlichung'));assert(section.textContent.includes('Keine eindeutige Artikelkennung'));assert(section.textContent.includes('Filialpreis noch offen'));assert(section.textContent.includes('Pfand unbekannt'));assert(!section.textContent.includes('Normalpreis'));assert(section.textContent.includes('Noch kein passender Berliner Preisbeleg: ALDI, REWE, Lidl, Kaufland, EDEKA'));assert(!w.eval('basket[0].selectedProduct'));
 w.eval("basket[0].selectedProduct={gtin:'4046700026519',name:'Schoko',brand:null,pack:'125 g',packAmount:125,packUnit:'g',packCount:1};comparisonRevision++;");await w.compare({skipLocation:true,scroll:false});assert(!section.textContent.includes('1,49'),'CMS publication must not populate selected GTIN');
 w.eval("delete basket[0].selectedProduct;basket[0].packLabel='250 g';comparisonRevision++;");await w.compare({skipLocation:true,scroll:false});assert(!section.textContent.includes('1,49'),'Wrong sales pack must not populate shopping wish');
 w.eval("basket[0].packLabel='125 g';comparisonRevision++;");f.set({...native,publication:{...native.publication,expiresAt:new Date(Date.now()-1).toISOString()}});await w.compare({skipLocation:true,scroll:false});assert(!section.textContent.includes('1,49'),'Expired CMS card must disappear');assert.deepEqual(f.errors,[]);
 const Lidl=require('../lidl-price-publications'),lidlRaw=require('./helpers/lidl-capture-fixture').fixture(),lidl=Lidl.parseCapture(lidlRaw,{now:Date.parse('2026-10-02T18:00:00Z')}).datedPublications;
 w.eval("basket=[parseWish('Cashewkerne200g')];comparisonRevision++;");f.set(lidl.find(x=>x.publication.groupOrdinal===1));await w.compare({skipLocation:true,scroll:false});
 assert(section.textContent.includes('Alesto Cashewkerne'));assert(section.textContent.includes('2,49'));assert(section.textContent.includes('200 Gramm'));assert(section.textContent.includes('Veröffentlicht am 01.10.2026'));assert(section.textContent.includes('Deutschlandweit veröffentlicht, auch für Berlin'));assert(section.textContent.includes('Heutiger Filialpreis/Pfand/Variante offen'));assert(!section.textContent.includes('Normalpreis'));assert(!section.textContent.includes('Stand'));assert(!section.textContent.includes('Dauerhaft'));assert.equal(section.querySelectorAll('button').length,0,'Publication has no product selection or checkout action');assert(!w.eval('basket[0].selectedProduct'));
 w.eval("basket[0].selectedProduct={gtin:'4046700026519',name:'Cashew',brand:null,pack:'200 g',packAmount:200,packUnit:'g',packCount:1};comparisonRevision++;");await w.compare({skipLocation:true,scroll:false});assert(!section.textContent.includes('2,49'),'Dated source group is never a selected GTIN product');
 w.eval("delete basket[0].selectedProduct;basket[0].ean='4046700026519';comparisonRevision++;");await w.compare({skipLocation:true,scroll:false});assert(!section.textContent.includes('2,49'),'Dated source group is never an EAN match');
 w.eval("delete basket[0].ean;basket[0].packLabel='150 g';comparisonRevision++;");await w.compare({skipLocation:true,scroll:false});assert(!section.textContent.includes('2,49'),'Wrong sales pack remains excluded');
 f.set(lidl.find(x=>x.publication.groupOrdinal===23));w.eval("basket=[{...parseWish('Cola'),label:'Cola',raw:'Cola',key:'lidl_cola_test',packLabel:'9 x 0.33 l'}];comparisonRevision++;");await w.compare({skipLocation:true,scroll:false});assert(section.textContent.includes('2,59'));assert(section.textContent.includes('9 x 0,33 l'),'Native multipack label stays visible');assert.equal(f.calls.at(-1).searchParams.get('pack'),'9 x 0.33 l');
 w.eval("basket[0].packLabel='2.97 l';comparisonRevision++;");await w.compare({skipLocation:true,scroll:false});assert(!section.textContent.includes('2,59'),'Total volume alone cannot stand in for a native multipack');assert.deepEqual(f.errors,[]);
 console.log('browser-berlin-reference: city prices, native SKU, exact pack/expiry/races/family boundaries, PENNY regional cards and dated Lidl groups without canonical selection OK');
 }finally{w.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
