const fs=require("fs"),assert=require("assert");
const {JSDOM,VirtualConsole}=require("jsdom");
(async()=>{
 const html=fs.readFileSync("index.html","utf8"),errors=[],vc=new VirtualConsole();
 vc.on("jsdomError",e=>errors.push(String(e.message||e)));
 const dom=new JSDOM(html,{runScripts:"dangerously",url:"https://julienfehlberg.github.io/Echtpreis/",pretendToBeVisual:true,virtualConsole:vc,beforeParse(w){
  w.fetch=async()=>({ok:false,status:503,json:async()=>({})});w.alert=()=>{};w.confirm=()=>true;w.prompt=()=>null;w.scrollTo=()=>{};Object.defineProperty(w.navigator,"geolocation",{configurable:true,value:{getCurrentPosition:(ok,fail)=>fail&&fail({code:1})}});
  if(w.HTMLElement)w.HTMLElement.prototype.scrollIntoView=function(){};
 }});
 await new Promise(r=>setTimeout(r,120));
 const w=dom.window,d=w.document;
 assert.strictEqual(errors.length,0,"browser startup errors: "+errors.join(" | "));
 assert.strictEqual(d.getElementById("contribute").checked,false,"receipt price sharing must require explicit opt-in");
 assert.strictEqual(typeof w.parseWish,"function");
 assert.strictEqual(w.detectReceiptStore("ALDI SÜD\n28.09.26"),"ALDI Süd");
 assert.strictEqual(w.detectReceiptStore("ALDI Nord\n28.09.26"),"ALDI Nord");
 assert.strictEqual(w.detectReceiptDate("Datum 2026-09-28"),"2026-09-28");
 assert.strictEqual(w.detectReceiptDate("Datum 31.02.2026"),"");
 const taxOnlyOcr="EDEKA Fil. 5401\n28.09.26\nSUMME 8,46\nMwSt NETTO MwSt UMSATZ\nA 7% 4,65 0,33 4,98\nB 19% 2,92 0,90 3,48";
 w.applyReceiptText(taxOnlyOcr,"Foto");
 assert.strictEqual(d.querySelectorAll("#reviewRows .reviewrow").length,0,"VAT summary must never become receipt products");
 assert.notStrictEqual(w.detectReceiptStore("Unbekannter Markt\nSUMME 8,46\nMwSt NETTO MwSt UMSATZ"),"Netto","VAT NETTO must never be mistaken for Netto supermarket");
 assert.strictEqual(w.detectReceiptStore("ALDI SÜD\nMusterstraße 1\n28.09.26"),"ALDI Süd","ALDI Süd must never be classified as ALDI Nord");
 assert.strictEqual(w.detectReceiptStore("ALDI Nord\n28.09.26"),"ALDI Nord","ALDI Nord detection regressed");
 assert.strictEqual(w.detectReceiptStore("ALDI\n28.09.26"),"ALDI","ambiguous ALDI receipt should remain neutral");
 assert.strictEqual(w.canShareReceiptPrices("Unbekannter Händler"),false,"unknown merchant prices must never enter community price data");assert.strictEqual(w.canShareReceiptPrices("ALDI"),false,"ambiguous ALDI prices must not be shared as a regional chain price");assert.strictEqual(w.canShareReceiptPrices("EDEKA"),true,"known merchant receipt prices should remain shareable with consent");
 assert.strictEqual(w.detectReceiptStore("MARKTKAUF\n28.09.26"),"Marktkauf","major German receipt chains should be recognized");
 assert.strictEqual(w.storeBrand({brand:"ALDI Süd"}),"ALDI Süd","nearby-store ALDI Süd detection regressed");
 assert.strictEqual(w.referencePrice("milch","ALDI Süd",w.parseWish("1 l Milch")),null,"ALDI Süd must not receive an invented model price without evidence");
 assert(!d.getElementById("receiptTotalCheck").textContent.startsWith("✓"),"VAT arithmetic must not falsely verify a receipt");
 assert.strictEqual(d.getElementById("analysisSaving").textContent,"–","VAT summary must not trigger a market comparison");
 assert(d.getElementById("analysisBestStore").textContent.includes("wartet"),"unverified receipt should explicitly wait for a safe scan");
 assert.strictEqual(w.detectReceiptStore("GLOBUS Markthalle\n28.09.26\nMilch 1,09\nSUMME 1,09"),"Globus","additional German retailers should be recognized for receipt history");
 d.getElementById("receiptStore").value="";d.getElementById("receiptDate").value="";w.applyReceiptText("KLEINER LADEN\n28.09.26\nMilch 1,09\nBrot 1,99\nSUMME 3,08","Foto");assert.strictEqual(d.getElementById("receiptStore").value,"Unbekannter Händler","strong unknown-retailer receipts should remain saveable");assert(d.getElementById("receiptTotalCheck").textContent.startsWith("✓"),"unknown retailer must not invalidate otherwise reconciled receipt content");assert(d.getElementById("analysisNote").textContent.includes("persönliche Statistik"),"unknown retailer should disable comparison but keep personal analytics");
 const realPhotoOcr="EDEKA Fil. 5491\n28.09.26\nG&G Mini-Hdrnchen 1,49 A\nOetker Ristorante 3,49 A\nRed Bull 0,25 1,49 € x 2 2,98 B\nPfand 0,25 € xX 2 9 ,50*B\nSUMME ® 8 ,46\nBar € 20,00\nMwSt NETTO MwSt UMSATZ\nA 7% 4,65 0,33 4,98";
 w.applyReceiptText(realPhotoOcr,"Bonausschnitt");
 assert.strictEqual(d.getElementById("receiptTotalInput").value,"8,46","real receipt photo should yield its printed total");
 assert(d.getElementById("receiptPaymentDetail").textContent.includes("20,00")&&d.getElementById("receiptPaymentDetail").textContent.includes("11,54"),"cash tender and calculated change should be displayed separately");
 assert.strictEqual(w.extractReceiptPaymentMethod("Kartenzahlung VISA\nSUMME 8,46"),"Visa","Visa receipt payment should be recognized");
 assert.strictEqual(w.extractReceiptPaymentMethod("APPLE PAY\nMastercard Debit"),"Apple Pay","wallet payment should take precedence over underlying card brand");
 w.applyReceiptText(realPhotoOcr.replace("Bar € 20,00","Kartenzahlung VISA 8,46"),"Bonausschnitt");assert(d.getElementById("receiptPaymentDetail").textContent.includes("Zahlung: Visa"),"card payment method should be shown as receipt context");assert(!d.getElementById("reviewRows").textContent.includes("Kartenzahlung"),"payment method must never become a receipt product");
 w.applyReceiptText(realPhotoOcr,"Bonausschnitt");
 w.applyReceiptText(realPhotoOcr.replace("Bar € 20,00","Bar € 20,00\nRückgeld 1,54"),"Bonausschnitt");assert(d.getElementById("receiptPaymentDetail").textContent.includes("11,54")&&d.getElementById("receiptPaymentDetail").textContent.includes("geprüft"),"implausible OCR change must be corrected from cash minus total");
 w.applyReceiptText(realPhotoOcr,"Bonausschnitt");
 assert(d.getElementById("reviewRows").textContent.includes("2 × 1,49"),"multipack quantities should be readable in receipt summary");
 assert.strictEqual(d.querySelectorAll("#reviewRows .reviewrow").length,4,"real receipt photo OCR should retain the three products and deposit");
 assert(d.getElementById("receiptTotalCheck").textContent.startsWith("✓"),"corrected deposit OCR should reconcile the printed total");
 assert.notStrictEqual(d.getElementById("receiptInsight").style.display,"none","verified receipt should immediately show a personal insight preview");
 assert(d.getElementById("receiptInsightTitle").textContent.trim().length>0,"receipt insight preview should contain a fact");
 assert(!d.getElementById("analysisSaving").textContent.includes("noch"),"recognized receipt items should reach a complete market comparison");
 const productOnlyOcr="G&G Mini-Hdrnchen 1,49 A\nOetker Ristorante 3,49 A\nRed Bull 0,25 1,49 € x 2 2,98 B\nPfand 0,25 € x 2 0,50";let ocrPasses=0;w.Tesseract={recognize:async()=>({data:{text:++ocrPasses===1?taxOnlyOcr:productOnlyOcr}})};
 w.createImageBitmap=async()=>({width:1152,height:1536,close(){}});
 w.HTMLCanvasElement.prototype.getContext=()=>({drawImage(){}});
 await w.runImageReceiptOCR(new w.File(["receipt"],"bon.jpg",{type:"image/jpeg"}));
 assert.strictEqual(ocrPasses,2,"tax-only OCR should retry a focused crop");
 assert.strictEqual(d.querySelectorAll("#reviewRows .reviewrow").length,4,"focused crop should replace tax rows with products");
 assert.strictEqual(d.getElementById("receiptStore").value,"EDEKA","focused crop must retain merchant from the first OCR pass");
 assert.strictEqual(d.getElementById("receiptDate").value,"2026-09-28","focused crop must retain date from the first OCR pass");
 assert.strictEqual(d.getElementById("receiptTotalInput").value,"8,46","focused crop must retain printed total from the first OCR pass");
 assert.strictEqual(w.extractReceiptTotal("EDEKA\nSUMME £ 8 , 46\nBar 20,00"),8.46,"OCR-spaced printed receipt total must be recovered");
 assert.strictEqual(w.extractReceiptTotal("EDEKA\nSUMME 8,46\nBar 20,00"),8.46,"cash tender must never replace the printed total");
 assert(w.receiptCandidateScore(realPhotoOcr).score>w.receiptCandidateScore(taxOnlyOcr).score,"real product rows should outrank VAT-only OCR");
 w.applyReceiptText("EDEKA Fil. 5491\n28.09.26\nSUMME £ 8 , 46\nBar 20,00","Foto");
 assert.strictEqual(d.getElementById("receiptTotalInput").type,"hidden","receipt total must not require manual editing");
 assert.strictEqual(w.formatReceiptDate("2026-09-28"),"28.09.2026","saved receipt dates should be human readable");
 assert.strictEqual(w.receiptLocalFingerprint("EDEKA","2026-09-28",8.46,[{name:"Pizza",price:3.49}]),w.receiptLocalFingerprint("EDEKA","2026-09-28",8.46,[{name:"Pizza",price:3.49}]),"local receipt fingerprint must be deterministic");
 assert.strictEqual(d.getElementById("receiptTotalInput").value,"8,46","recognized total should be captured internally");
 assert(d.getElementById("analysisPaid").textContent.includes("8,46"),"paid total must appear even without recognized line items");
 assert.strictEqual(w.detectReceiptDate("EDEKA 28.09.26"),"2026-09-28","receipt date should be normalized");
 assert.strictEqual(w.plausibleReceiptItemName("nel"),false,"short OCR fragments must never verify as products");
 assert.strictEqual(d.getElementById("finishPurchaseBtn").disabled,true,"total-only receipt must not be saved as a verified scan");
 assert.strictEqual(d.getElementById("statsWeekly").textContent,"12,50 €","unverified receipt must not change weekly spending");
 assert.strictEqual(d.getElementById("statsMonthly").textContent,"12,50 €","unverified receipt must not change monthly spending");
 assert.strictEqual(typeof w.parseWish,"function");
 let p=w.parseWish("0,5 kg Tomaten");assert.strictEqual(p.key,"tomaten");assert.strictEqual(p.amount,0.5);assert.strictEqual(p.unit,"kg");
 p=w.parseWish("2 l Coca Cola");assert.strictEqual(p.key,"cola");assert.strictEqual(p.matchMode,"exact");
 p=w.parseWish("500 g Erdbeeren");assert.strictEqual(p.key,"erdbeeren");assert.strictEqual(p.unit,"kg");assert.strictEqual(p.amount,0.5);assert(w.referencePrice("erdbeeren","Lidl",p)?.reference,"strawberry reference fallback missing");
 p=w.parseWish("250 g Blaubeeren");assert.strictEqual(p.key,"blaubeeren");assert(w.referencePrice("blaubeeren","REWE",p)?.price>0,"blueberry reference fallback missing");
 p=w.parseWish("1 kg Süßkartoffeln");assert.strictEqual(p.key,"suesskartoffeln");
 for(const product of ["500 g Rinderhack","500 g Hackfleisch","1 kg Hähnchenbrust"]){const wish=w.parseWish(product);assert.strictEqual(w.activePrice(wish.key,"dm",wish),null,"dm must not claim to sell "+product);assert.strictEqual(w.activePrice(wish.key,"Rossmann",wish),null,"Rossmann must not claim to sell "+product)}
 assert(w.storeCanCarry("dm",w.parseWish("1 Zahnpasta")),"drugstore categories should remain eligible when verified observations become available");
 assert.strictEqual(w.activePrice("zahnpasta","dm",w.parseWish("1 Zahnpasta")),null,"a category guess must not invent a drugstore price or availability");w.resetPriceLookupMemo();
 const exactEnergy=w.parseWish("2 Red Bull");assert.strictEqual(w.referencePrice(exactEnergy.key,"Lidl",exactEnergy),null,"exact brands must not fall back to generic model prices");
 const exactPizza=w.parseWish("1 Oetker Ristorante");assert.strictEqual(exactPizza.matchMode,"exact","Oetker receipt/list items must remain exact-brand products");assert.strictEqual(w.referencePrice(exactPizza.key,"Lidl",exactPizza),null,"Oetker must not fall back to generic pizza pricing");
 const meatWish=w.parseWish("500 g Rinderhack");assert.strictEqual(w.storeCanCarry("dm",meatWish,meatWish.key),false,"dm must never be considered for fresh minced meat");assert.strictEqual(w.storeCanCarry("Rossmann",meatWish,meatWish.key),false,"Rossmann must never be considered for fresh minced meat");assert.strictEqual(w.storeCanCarry("EDEKA",meatWish,meatWish.key),true,"supermarkets must remain eligible for fresh minced meat");

 const exactOwnBrand=w.parseWish("1 G&G Mini-Hörnchen");assert.strictEqual(exactOwnBrand.matchMode,"exact","retailer own-brand receipt items must remain exact");
 const observationDate=new Date().toISOString().slice(0,10);
 [1,2].forEach(n=>w.addCommunityObservation({key:"zahnpasta",store:"dm",price:1.99,per:"piece",date:observationDate,proof:"independent_"+n}));
 assert(w.activePrice("zahnpasta","dm",w.parseWish("1 Zahnpasta")),"two current independent observations should enable a drugstore comparison");
 w.localStorage.removeItem("echtpreis_community_observations_v2");w.invalidateDataEngine();w.resetPriceLookupMemo();
 let restored=w.restoreBasketItem({raw:"Lachs",choice:{Art:"frozen",Menge:"500g"},checked:true});assert.strictEqual(restored.needsClarification,false,"saved product choice must survive reload");assert.strictEqual(restored.checked,true);
 restored=w.restoreBasketItem({raw:"250 g Testprodukt",ean:"12345678",label:"Testprodukt · 250 g"});assert.strictEqual(restored.key,"ean:12345678","barcode identity must survive reload");
 assert.strictEqual(w.identifyReceiptProduct("Red Bull 0,25").key,"energydrink");
 assert.strictEqual(w.plausibleReceiptItemName("Terminal"),false,"terminal metadata must never verify as a product");
 assert.strictEqual(w.plausibleReceiptItemName("Kartenzahlung"),false,"payment metadata must never verify as a product");
 assert.strictEqual(w.plausibleReceiptItemName("Milch"),true,"normal short product names must remain valid");
 assert.strictEqual(w.receiptArithmeticMatches(8.46,8.45),true,"one-cent OCR rounding differences should be tolerated");
 assert.strictEqual(w.receiptArithmeticMatches(8.46,8.36),false,"material receipt arithmetic differences must still fail");

 const rb=w.inferPackFromName("Red Bull 0,25");assert.strictEqual(rb.packAmount,0.25);assert.strictEqual(rb.packUnit,"l");
 assert.strictEqual(w.receiptObservationUnitPrice({price:2.98,packAmount:.25,packUnit:"l",count:2},{unit:"l"}),5.96,"two 250 ml cans for 2.98 must normalize to 5.96 EUR/l, not 11.92");
 assert.strictEqual(w.receiptObservationUnitPrice({price:1.49,packAmount:.25,packUnit:"l",count:1},{unit:"l"}),5.96,"single 250 ml can normalization regressed");
 assert.strictEqual(w.receiptObservationUnitPrice({price:2.98,packAmount:.25,packUnit:"l",count:2},{unit:"kg"}),null,"incompatible receipt units must never be shared as market prices");

 const receipt=w.parseReceiptText("G&G Mini-Hörnchen 1,49\nOetker Ristorante 3,49\nRed Bull 0,25 1,49 x 2 2,98\nPfand 0,25 x 2 0,50\nSUMME 8,46");
 const barcodePromise=w.addEchtpreisBarcode("Testprodukt","250 g","12345678");assert.strictEqual(w.getEchtpreisRawList().length,1,"barcode product should enter the primary basket immediately");w.replaceEchtpreisList([]);void barcodePromise;
 assert(receipt.length>=4,"receipt parser lost rows");
 const longReceipt=Array.from({length:55},(_,i)=>"Milch "+String(i+1)+" 1,00").join("\n")+"\nSUMME 55,00";assert.strictEqual(w.parseReceiptText(longReceipt).length,55,"normal large grocery receipts must not be truncated at 40 lines");

 assert(receipt.some(x=>x.isDeposit),"deposit line not recognized");
 const prof=w.receiptItemProfile({name:"Pfand",price:.5,isDeposit:true});assert.strictEqual(prof.isDeposit,true,"deposit analytics flag missing");assert.strictEqual(prof.category,"Pfand","deposit must not enter normal spending categories");
 const searchRows=w.searchPersonalPurchases("Red Bull",[{id:"a",store:"EDEKA",date:"2026-09-28",items:[{name:"Red Bull 0,25",price:2.98,count:2,unitLinePrice:1.49}]},{id:"b",store:"Lidl",date:"2026-09-20",items:[{name:"Red Bull 0,25",price:1.49,count:1}]}]);assert.strictEqual(searchRows[0].price,1.49,"purchase search must compare multipacks per unit");
 const multipackSearchRows=w.searchPersonalPurchases("Milch",[{id:"a",store:"EDEKA",date:"2026-09-01",items:[{name:"Milch 1 l",price:1.49}]},{id:"b",store:"Kaufland",date:"2026-09-05",items:[{name:"Milch 1 l",price:1.19},{name:"Pfand",price:.25,isDeposit:true}]}]);assert.strictEqual(multipackSearchRows.length,2,"personal purchase search should find matching receipt items");assert.strictEqual(multipackSearchRows[0].store,"Kaufland","personal purchase search should sort newest first");
 assert.strictEqual(w.personalComparablePrice({price:2.98,count:2}),1.49,"multipack personal comparison must normalize line total by count");
 assert.strictEqual(w.personalComparablePrice({price:1.49,count:1}),1.49,"single-item personal comparison must preserve price");
 const marketReceipts=[{store:"EDEKA",date:"2026-09-10",total:"5.00",items:[{name:"Milch 1 l",price:1.49},{name:"Butter 250 g",price:2.49}]},{store:"Kaufland",date:"2026-09-11",total:"4.00",items:[{name:"Milch 1 l",price:1.19},{name:"Butter 250 g",price:1.99}]}];w.renderStatsMarketProfile(marketReceipts);const marketText=d.getElementById("statsMarketProfile").textContent;assert(marketText.includes("EDEKA")&&marketText.includes("Kaufland"),"market profile should compare overlapping products across stores");assert(marketText.includes("direkt vergleichbare Produkte"),"market profile must disclose its comparison basis");
 const insight=w.buildReceiptInsight([{id:"1",store:"EDEKA",date:"2026-09-01",total:"20.00",items:[{name:"Milch",price:1.09}]},{id:"2",store:"EDEKA",date:"2026-09-08",total:"22.00",items:[{name:"Milch",price:1.09}]},{id:"3",store:"EDEKA",date:"2026-09-15",total:"21.00",items:[{name:"Milch",price:1.09}]},{id:"4",store:"EDEKA",date:"2026-09-28",total:"35.00",items:[{name:"Milch",price:1.39},{name:"Red Bull",price:5.96}]}],{id:"4",store:"EDEKA",date:"2026-09-28",total:"35.00",items:[{name:"Milch",price:1.39},{name:"Red Bull",price:5.96}]});assert(insight&&insight.title,"receipt insight should produce a personal fact");assert(/teurer|Einkauf|Milch|Bon/i.test(insight.title),"receipt insight should be meaningful");
 const splitQty=w.parseReceiptText("Red Bull 1,49\n1,49 x 2\nPfand 0,25 x 2\nSUMME 3,48");assert.strictEqual(Number(splitQty[0].price),2.98,"separate quantity line must update article total");
 const discounted=w.parseReceiptText("Pizza 3,99\nAktionsrabatt -0,50\nSUMME 3,49");assert.strictEqual(Number(discounted[0].price),3.49,"separate discount must reduce recognized paid total");assert.strictEqual(discounted[0].regularTotal,3.99,"regular pre-discount price should remain available");
 const couponRows=w.parseReceiptText("Pizza 3,99\nCoupon-Rabatt -0,50\nSUMME 3,49");assert.strictEqual(couponRows.length,2,"receipt-level coupon should remain an explicit adjustment row");assert.strictEqual(couponRows[1].isAdjustment,true,"receipt-level coupon must be marked as adjustment");assert.strictEqual(Number(couponRows[1].price),-.50,"coupon adjustment amount should stay negative");assert.strictEqual(Number(couponRows.reduce((n,x)=>n+Number(x.price),0).toFixed(2)),3.49,"coupon-adjusted receipt rows must reconcile total");
 assert.strictEqual(w.receiptItemProfile({name:"Coupon / Rabatt",price:-.5,isAdjustment:true}).category,"Rabatte","coupon adjustment must not become a normal product category");
 assert.strictEqual(w.searchPersonalPurchases("Coupon",[{store:"EDEKA",date:"2026-09-28",items:[{name:"Coupon / Rabatt",price:-.5,isAdjustment:true}]}]).length,0,"coupon adjustments must stay out of personal product search");
 d.getElementById("receiptStore").value="";d.getElementById("receiptDate").value="";w.applyReceiptText("EDEKA\n28.09.26\nPizza 3,99\nCoupon-Rabatt -0,50\nSUMME 3,49","Foto");assert(d.getElementById("receiptTotalCheck").textContent.startsWith("✓"),"coupon-adjusted receipt should verify against printed total");assert(d.getElementById("reviewRows").textContent.includes("Bon-Rabatt"),"coupon adjustment should be labeled as non-product in receipt review");
 assert.strictEqual(w.detectReceiptDate("Datum 2026-09-28"),"2026-09-28","ISO receipt date should be supported");
 assert.strictEqual(w.detectReceiptDate("Datum 31.02.2026"),"","impossible receipt dates must be rejected");
 w.localStorage.removeItem("echtpreis_open_purchase");d.getElementById("compareBtn").click();await new Promise(r=>setTimeout(r,20));assert.strictEqual(w.localStorage.getItem("echtpreis_open_purchase"),null,"failed comparison must not open a purchase");
 d.getElementById("demoListBtn").click();assert.strictEqual(d.querySelectorAll("#list .item").length,2,"demo list must use primary basket only"); let spoken=w.parseWish("drei rote Tomaten");assert.strictEqual(spoken.key,"tomaten");assert.strictEqual(spoken.amount,3);
 let genericTomato=w.parseWish("Tomaten"),cherryTomato=w.parseWish("500 g Cherrytomaten");assert.strictEqual(genericTomato.needsClarification,true);assert.strictEqual(cherryTomato.needsClarification,false);
 let meatWish=w.parseWish("500 g Rinderhack");assert.strictEqual(w.storeCanCarry("dm",meatWish,meatWish.key),false);assert.strictEqual(w.storeCanCarry("EDEKA",meatWish,meatWish.key),true);
 console.log("browser smoke OK · single basket · quantity parser · receipt parser");
 dom.window.close();
})().catch(e=>{console.error(e);process.exit(1)});
