const fs=require("fs"),assert=require("assert");
const {JSDOM,VirtualConsole}=require("jsdom");
(async()=>{
 const html=fs.readFileSync("index.html","utf8"),errors=[],vc=new VirtualConsole();
 vc.on("jsdomError",e=>errors.push(String(e.message||e)));
 const dom=new JSDOM(html,{runScripts:"dangerously",url:"https://julienfehlberg.github.io/Echtpreis/",pretendToBeVisual:true,virtualConsole:vc,beforeParse(w){
  w.fetch=async()=>({ok:false,status:503,json:async()=>({})});w.alert=()=>{};w.confirm=()=>true;w.prompt=()=>null;w.scrollTo=()=>{};Object.defineProperty(w.navigator,"geolocation",{configurable:true,value:{getCurrentPosition:(ok,fail)=>fail&&fail({code:1})}});
  if(w.HTMLElement)w.HTMLElement.prototype.scrollIntoView=function(){};
 }});
 await new Promise(r=>setTimeout(r,120));
 const w=dom.window,d=w.document;
 assert.strictEqual(errors.length,0,"browser startup errors: "+errors.join(" | "));
 assert.strictEqual(d.getElementById("contribute").checked,false,"receipt price sharing must require explicit opt-in");
 d.getElementById("productInput").value="hack";d.getElementById("productInput").dispatchEvent(new w.Event("input",{bubbles:true}));assert(d.getElementById("suggestions").textContent.toLowerCase().includes("hack"),"typing should surface matching product suggestions");d.getElementById("productInput").value="";d.getElementById("productInput").dispatchEvent(new w.Event("input",{bubbles:true}));
 assert(![...d.body.childNodes].some(n=>n.nodeType===3&&n.textContent.trim()),"stray CSS or text appears before the app");
 d.getElementById("homePlan").click();
 assert.strictEqual(d.getElementById("planner").previousElementSibling.id,"homePlan","opened list must appear directly after its menu button");
 assert.strictEqual(d.getElementById("planner").nextElementSibling.id,"homeStats","statistics menu must follow the opened list");
 assert.strictEqual(d.getElementById("homeReceipt").nextElementSibling.id,"receipt","receipt panel must follow its menu button");
 assert.strictEqual(d.getElementById("planner").style.display,"block","list should be expanded");
 d.getElementById("homePlan").click();
 assert.strictEqual(d.getElementById("planner").style.display,"none","tapping list menu again should close it");
 d.getElementById("homePlan").click();
 assert.strictEqual(d.getElementById("planner").style.display,"block","list should reopen");
 d.getElementById("homeReceipt").click();
 assert.strictEqual(d.getElementById("receipt").previousElementSibling.id,"homeReceipt","opened receipt analysis must appear directly below its menu button");
 assert.strictEqual(d.getElementById("receipt").nextElementSibling.id,"homePlan","shopping-list menu must follow receipt analysis");
 assert.strictEqual(d.getElementById("receipt").style.display,"block","receipt analysis should be expanded");
 d.getElementById("backPlanBtn").click();
 assert.strictEqual(d.getElementById("receipt").style.display,"none","receipt back button should close receipt view");
 assert.strictEqual(d.getElementById("planner").style.display,"none","receipt back button must not open the shopping list");
 d.getElementById("homeReceipt").click();
 d.getElementById("homeReceipt").click();
 assert.strictEqual(d.getElementById("receipt").style.display,"none","tapping receipt menu again should close it");
 d.getElementById("homeReceipt").click();
 w.Tesseract={recognize:async()=>({data:{text:"EDEKA\n28.09.26\nMilch 1,09\nBananen 1,79\nSUMME 2,88"}})};
 const receiptInput=d.getElementById("receiptFile");
 Object.defineProperty(receiptInput,"files",{configurable:true,value:[new w.File(["receipt"],"bon.jpg",{type:"image/jpeg"})]});
 receiptInput.dispatchEvent(new w.Event("change"));await new Promise(r=>setTimeout(r,20));
 assert.strictEqual(d.getElementById("receiptStore").value,"EDEKA","receipt merchant should be detected");
 assert(d.getElementById("ocrStatus").textContent.includes("Bon automatisch erkannt")||d.getElementById("ocrStatus").textContent.includes("Positionen erkannt"),"receipt OCR must complete with an automatic recognition status");
 assert.strictEqual(d.getElementById("receiptAnalysis").style.display,"block","receipt analysis should appear after OCR");
 assert.strictEqual(d.getElementById("finishPurchaseBtn").disabled,false,"receipt should be reviewable after OCR");
 w.Tesseract={recognize:async()=>({data:{text:"unlesbarer scan"}})};
 Object.defineProperty(receiptInput,"files",{configurable:true,value:[new w.File(["bad"],"bon2.jpg",{type:"image/jpeg"})]});
 receiptInput.dispatchEvent(new w.Event("change"));await new Promise(r=>setTimeout(r,20));
 assert.strictEqual(d.getElementById("receiptStore").value,"","a second unreadable scan must not inherit the previous merchant");
 assert.strictEqual(d.getElementById("receiptDate").value,"","a second unreadable scan must not inherit the previous date");
 assert.strictEqual(d.getElementById("finishPurchaseBtn").disabled,true,"an unreadable second scan must remain blocked");
 const today=new Date().toISOString().slice(0,10);
 w.localStorage.setItem("echtpreis_personal_receipts",JSON.stringify([{id:"test-receipt",date:today,total:"12.50",potentialSaving:2.10}]));
 d.getElementById("homeStats").click();
 assert.strictEqual(d.getElementById("statsCard").previousElementSibling.id,"homeStats","statistics should appear directly below its menu button");
 assert.strictEqual(d.getElementById("statsCard").style.display,"block");
 d.getElementById("homeStats").click();
 assert.strictEqual(d.getElementById("statsCard").style.display,"none","tapping statistics menu again should close it");
 d.getElementById("homeStats").click();
 assert.strictEqual(d.getElementById("statsReceipts").textContent,"1","statistics should count saved receipts");
 assert.strictEqual(d.getElementById("statsSpent").textContent,"12,50 €","statistics should sum spending for this year");
 assert.strictEqual(d.getElementById("statsMonthly").textContent,"12,50 €","statistics should sum spending for this month");
 assert(d.getElementById("statsPotential").textContent.includes("2,10"),"statistics should show known estimated savings");
 assert.strictEqual(d.getElementById("statsWeekly").textContent,"12,50 €","statistics should include this week's spending");
 assert.strictEqual(d.getElementById("statsAverage").textContent,"12,50 €","statistics should show the average receipt value");
 assert(d.getElementById("statsRecent").textContent.includes("12,50"),"statistics should show recent receipts");
 const taxOnlyOcr="EDEKA Fil. 5401\n28.09.26\nSUMME 8,46\nMwSt NETTO MwSt UMSATZ\nA 7% 4,65 0,33 4,98\nB 19% 2,92 0,90 3,48";
 w.applyReceiptText(taxOnlyOcr,"Foto");
 assert.strictEqual(d.querySelectorAll("#reviewRows .reviewrow").length,0,"VAT summary must never become receipt products");
 assert.notStrictEqual(w.detectReceiptStore("Unbekannter Markt\nSUMME 8,46\nMwSt NETTO MwSt UMSATZ"),"Netto","VAT NETTO must never be mistaken for Netto supermarket");
 assert(!d.getElementById("receiptTotalCheck").textContent.startsWith("✓"),"VAT arithmetic must not falsely verify a receipt");
 assert.strictEqual(d.getElementById("analysisSaving").textContent,"–","VAT summary must not trigger a market comparison");
 assert(d.getElementById("analysisBestStore").textContent.includes("wartet"),"unverified receipt should explicitly wait for a safe scan");
 const realPhotoOcr="EDEKA Fil. 5491\n28.09.26\nG&G Mini-Hdrnchen 1,49 A\nOetker Ristorante 3,49 A\nRed Bull 0,25 1,49 € x 2 2,98 B\nPfand 0,25 € xX 2 9 ,50*B\nSUMME ® 8 ,46\nBar € 20,00\nMwSt NETTO MwSt UMSATZ\nA 7% 4,65 0,33 4,98";
 w.applyReceiptText(realPhotoOcr,"Bonausschnitt");
 assert.strictEqual(d.getElementById("receiptTotalInput").value,"8,46","real receipt photo should yield its printed total");
 assert(d.getElementById("receiptPaymentDetail").textContent.includes("20,00")&&d.getElementById("receiptPaymentDetail").textContent.includes("11,54"),"cash tender and calculated change should be displayed separately");
 w.applyReceiptText(realPhotoOcr.replace("Bar € 20,00","Bar € 20,00\nRückgeld 1,54"),"Bonausschnitt");assert(d.getElementById("receiptPaymentDetail").textContent.includes("11,54")&&d.getElementById("receiptPaymentDetail").textContent.includes("geprüft"),"implausible OCR change must be corrected from cash minus total");
 w.applyReceiptText(realPhotoOcr,"Bonausschnitt");
 assert(d.getElementById("reviewRows").textContent.includes("2 × 1,49"),"multipack quantities should be readable in receipt summary");
 assert.strictEqual(d.querySelectorAll("#reviewRows .reviewrow").length,4,"real receipt photo OCR should retain the three products and deposit");
 assert(d.getElementById("receiptTotalCheck").textContent.startsWith("✓"),"corrected deposit OCR should reconcile the printed total");
 assert.notStrictEqual(d.getElementById("receiptInsight").style.display,"none","verified receipt should immediately show a personal insight preview");
 assert(d.getElementById("receiptInsightTitle").textContent.trim().length>0,"receipt insight preview should contain a fact");
 assert(!d.getElementById("analysisSaving").textContent.includes("noch"),"recognized receipt items should reach a complete market comparison");
 const productOnlyOcr="G&G Mini-Hdrnchen 1,49 A\nOetker Ristorante 3,49 A\nRed Bull 0,25 1,49 € x 2 2,98 B\nPfand 0,25 € x 2 0,50";let ocrPasses=0;w.Tesseract={recognize:async()=>({data:{text:++ocrPasses===1?taxOnlyOcr:productOnlyOcr}})};
 w.createImageBitmap=async()=>({width:1152,height:1536,close(){}});
 w.HTMLCanvasElement.prototype.getContext=()=>({drawImage(){}});
 await w.runImageReceiptOCR(new w.File(["receipt"],"bon.jpg",{type:"image/jpeg"}));
 assert.strictEqual(ocrPasses,2,"tax-only OCR should retry a focused crop");
 assert.strictEqual(d.querySelectorAll("#reviewRows .reviewrow").length,4,"focused crop should replace tax rows with products");
 assert.strictEqual(d.getElementById("receiptStore").value,"EDEKA","focused crop must retain merchant from the first OCR pass");
 assert.strictEqual(d.getElementById("receiptDate").value,"2026-09-28","focused crop must retain date from the first OCR pass");
 assert.strictEqual(d.getElementById("receiptTotalInput").value,"8,46","focused crop must retain printed total from the first OCR pass");
 assert.strictEqual(w.extractReceiptTotal("EDEKA\nSUMME £ 8 , 46\nBar 20,00"),8.46,"OCR-spaced printed receipt total must be recovered");
 assert.strictEqual(w.extractReceiptTotal("EDEKA\nSUMME 8,46\nBar 20,00"),8.46,"cash tender must never replace the printed total");
 assert(w.receiptCandidateScore(realPhotoOcr).score>w.receiptCandidateScore(taxOnlyOcr).score,"real product rows should outrank VAT-only OCR");
 w.applyReceiptText("EDEKA Fil. 5491\n28.09.26\nSUMME £ 8 , 46\nBar 20,00","Foto");
 assert.strictEqual(d.getElementById("receiptTotalInput").type,"hidden","receipt total must not require manual editing");
 assert.strictEqual(w.formatReceiptDate("2026-09-28"),"28.09.2026","saved receipt dates should be human readable");
 assert.strictEqual(w.receiptLocalFingerprint("EDEKA","2026-09-28",8.46,[{name:"Pizza",price:3.49}]),w.receiptLocalFingerprint("EDEKA","2026-09-28",8.46,[{name:"Pizza",price:3.49}]),"local receipt fingerprint must be deterministic");
 assert.strictEqual(d.getElementById("receiptTotalInput").value,"8,46","recognized total should be captured internally");
 assert(d.getElementById("analysisPaid").textContent.includes("8,46"),"paid total must appear even without recognized line items");
 assert.strictEqual(w.detectReceiptDate("EDEKA 28.09.26"),"2026-09-28","receipt date should be normalized");
 assert.strictEqual(w.plausibleReceiptItemName("nel"),false,"short OCR fragments must never verify as products");
 assert.strictEqual(d.getElementById("finishPurchaseBtn").disabled,true,"total-only receipt must not be saved as a verified scan");
 assert.strictEqual(d.getElementById("statsWeekly").textContent,"12,50 €","unverified receipt must not change weekly spending");
 assert.strictEqual(d.getElementById("statsMonthly").textContent,"12,50 €","unverified receipt must not change monthly spending");
 assert.strictEqual(typeof w.parseWish,"function");
 let p=w.parseWish("0,5 kg Tomaten");assert.strictEqual(p.key,"tomaten");assert.strictEqual(p.amount,0.5);assert.strictEqual(p.unit,"kg");
 p=w.parseWish("2 l Coca Cola");assert.strictEqual(p.key,"cola");assert.strictEqual(p.matchMode,"exact");
 p=w.parseWish("500 g Erdbeeren");assert.strictEqual(p.key,"erdbeeren");assert.strictEqual(p.unit,"kg");assert.strictEqual(p.amount,0.5);assert(w.referencePrice("erdbeeren","Lidl",p)?.reference,"strawberry reference fallback missing");
 p=w.parseWish("250 g Blaubeeren");assert.strictEqual(p.key,"blaubeeren");assert(w.referencePrice("blaubeeren","REWE",p)?.price>0,"blueberry reference fallback missing");
 p=w.parseWish("1 kg Süßkartoffeln");assert.strictEqual(p.key,"suesskartoffeln");
 for(const product of ["500 g Rinderhack","500 g Hackfleisch","1 kg Hähnchenbrust"]){const wish=w.parseWish(product);assert.strictEqual(w.activePrice(wish.key,"dm",wish),null,"dm must not claim to sell "+product);assert.strictEqual(w.activePrice(wish.key,"Rossmann",wish),null,"Rossmann must not claim to sell "+product)}
 assert(w.storeCanCarry("dm",w.parseWish("1 Zahnpasta")),"drugstore categories should remain eligible when verified observations become available");
 assert.strictEqual(w.activePrice("zahnpasta","dm",w.parseWish("1 Zahnpasta")),null,"a category guess must not invent a drugstore price or availability");
 const exactEnergy=w.parseWish("2 Red Bull");assert.strictEqual(w.referencePrice(exactEnergy.key,"Lidl",exactEnergy),null,"exact brands must not fall back to generic model prices");
 const exactPizza=w.parseWish("1 Oetker Ristorante");assert.strictEqual(exactPizza.matchMode,"exact","Oetker receipt/list items must remain exact-brand products");assert.strictEqual(w.referencePrice(exactPizza.key,"Lidl",exactPizza),null,"Oetker must not fall back to generic pizza pricing");
 const exactOwnBrand=w.parseWish("1 G&G Mini-Hörnchen");assert.strictEqual(exactOwnBrand.matchMode,"exact","retailer own-brand receipt items must remain exact");
 const observationDate=new Date().toISOString().slice(0,10);
 w.localStorage.setItem("echtpreis_community_observations_v2",JSON.stringify([1,2].map(n=>({key:"zahnpasta",store:"dm",price:1.99,per:"piece",date:observationDate,kind:"community",proof:"independent_"+n,trust:60}))));
 assert(w.activePrice("zahnpasta","dm",w.parseWish("1 Zahnpasta")),"two current independent observations should enable a drugstore comparison");
 w.localStorage.removeItem("echtpreis_community_observations_v2");
 let restored=w.restoreBasketItem({raw:"Lachs",choice:{Art:"frozen",Menge:"500g"},checked:true});assert.strictEqual(restored.needsClarification,false,"saved product choice must survive reload");assert.strictEqual(restored.checked,true);
 restored=w.restoreBasketItem({raw:"250 g Testprodukt",ean:"12345678",label:"Testprodukt · 250 g"});assert.strictEqual(restored.key,"ean:12345678","barcode identity must survive reload");
 assert.strictEqual(w.identifyReceiptProduct("Red Bull 0,25").key,"energydrink");
 const rb=w.inferPackFromName("Red Bull 0,25");assert.strictEqual(rb.packAmount,0.25);assert.strictEqual(rb.packUnit,"l");
 const receipt=w.parseReceiptText("G&G Mini-Hörnchen 1,49\nOetker Ristorante 3,49\nRed Bull 0,25 1,49 x 2 2,98\nPfand 0,25 x 2 0,50\nSUMME 8,46");
 await w.addEchtpreisBarcode("Testprodukt","250 g","12345678");assert.strictEqual(d.querySelectorAll("#list .item").length,1,"barcode product should enter the primary basket");w.replaceEchtpreisList([]);
 for(let i=0;i<24;i++){
  const chips=[...d.querySelectorAll("#quickSuggestions [data-quick]")];
  assert.strictEqual(chips.length,3,"three fresh suggestions should remain after "+i+" additions");
  chips[0].click();
  assert.strictEqual(w.getEchtpreisRawList().length,i+1,"suggestion should add a new product");
 }
 assert.strictEqual(new Set(w.getEchtpreisRawList().map(raw=>w.parseWish(raw).key)).size,24,"quick suggestions should avoid repeated products");
 w.replaceEchtpreisList([]);
 assert(receipt.length>=4,"receipt parser lost rows");
 assert(receipt.some(x=>x.isDeposit),"deposit line not recognized");
 const prof=w.receiptItemProfile({name:"Pfand",price:.5,isDeposit:true});assert.strictEqual(prof.isDeposit,true,"deposit analytics flag missing");assert.strictEqual(prof.category,"Pfand","deposit must not enter normal spending categories");
 const searchRows=w.searchPersonalPurchases("Red Bull",[{id:"a",store:"EDEKA",date:"2026-09-28",items:[{name:"Red Bull 0,25",price:2.98,count:2,unitLinePrice:1.49}]},{id:"b",store:"Lidl",date:"2026-09-20",items:[{name:"Red Bull 0,25",price:1.49,count:1}]}]);assert.strictEqual(searchRows[0].price,1.49,"purchase search must compare multipacks per unit");
 const multipackSearchRows=w.searchPersonalPurchases("Milch",[{id:"a",store:"EDEKA",date:"2026-09-01",items:[{name:"Milch 1 l",price:1.49}]},{id:"b",store:"Kaufland",date:"2026-09-05",items:[{name:"Milch 1 l",price:1.19},{name:"Pfand",price:.25,isDeposit:true}]}]);assert.strictEqual(multipackSearchRows.length,2,"personal purchase search should find matching receipt items");assert.strictEqual(multipackSearchRows[0].store,"Kaufland","personal purchase search should sort newest first");
 assert.strictEqual(w.personalComparablePrice({price:2.98,count:2}),1.49,"multipack personal comparison must normalize line total by count");
 assert.strictEqual(w.personalComparablePrice({price:1.49,count:1}),1.49,"single-item personal comparison must preserve price");
 const marketReceipts=[{store:"EDEKA",date:"2026-09-10",total:"5.00",items:[{name:"Milch 1 l",price:1.49},{name:"Butter 250 g",price:2.49}]},{store:"Kaufland",date:"2026-09-11",total:"4.00",items:[{name:"Milch 1 l",price:1.19},{name:"Butter 250 g",price:1.99}]}];w.renderStatsMarketProfile(marketReceipts);const marketText=d.getElementById("statsMarketProfile").textContent;assert(marketText.includes("EDEKA")&&marketText.includes("Kaufland"),"market profile should compare overlapping products across stores");assert(marketText.includes("direkt vergleichbare Produkte"),"market profile must disclose its comparison basis");
 const insight=w.buildReceiptInsight([{id:"1",store:"EDEKA",date:"2026-09-01",total:"20.00",items:[{name:"Milch",price:1.09}]},{id:"2",store:"EDEKA",date:"2026-09-08",total:"22.00",items:[{name:"Milch",price:1.09}]},{id:"3",store:"EDEKA",date:"2026-09-15",total:"21.00",items:[{name:"Milch",price:1.09}]},{id:"4",store:"EDEKA",date:"2026-09-28",total:"35.00",items:[{name:"Milch",price:1.39},{name:"Red Bull",price:5.96}]}],{id:"4",store:"EDEKA",date:"2026-09-28",total:"35.00",items:[{name:"Milch",price:1.39},{name:"Red Bull",price:5.96}]});assert(insight&&insight.title,"receipt insight should produce a personal fact");assert(/teurer|Einkauf|Milch|Bon/i.test(insight.title),"receipt insight should be meaningful");
 const splitQty=w.parseReceiptText("Red Bull 1,49\n1,49 x 2\nPfand 0,25 x 2\nSUMME 3,48");assert.strictEqual(Number(splitQty[0].price),2.98,"separate quantity line must update article total");
 const discounted=w.parseReceiptText("Pizza 3,99\nAktionsrabatt -0,50\nSUMME 3,49");assert.strictEqual(Number(discounted[0].price),3.49,"separate discount must reduce recognized paid total");assert.strictEqual(discounted[0].regularTotal,3.99,"regular pre-discount price should remain available");
 assert.strictEqual(w.detectReceiptDate("Datum 2026-09-28"),"2026-09-28","ISO receipt date should be supported");
 assert.strictEqual(w.detectReceiptDate("Datum 31.02.2026"),"","impossible receipt dates must be rejected");
 w.localStorage.removeItem("echtpreis_open_purchase");d.getElementById("compareBtn").click();await new Promise(r=>setTimeout(r,20));assert.strictEqual(w.localStorage.getItem("echtpreis_open_purchase"),null,"failed comparison must not open a purchase");
 d.getElementById("demoListBtn").click();assert.strictEqual(d.querySelectorAll("#list .item").length,2,"demo list must use primary basket only");let ambiguous=w.parseWish("Lachs");assert.strictEqual(ambiguous.needsClarification,true,"ambiguous salmon must require a variant");let precise=w.parseWish("500 g TK Lachs");assert.strictEqual(precise.needsClarification,false,"precise salmon should be comparison-ready");
 d.getElementById("productInput").value="0,5 kg Tomaten";d.getElementById("addBtn").click();assert.strictEqual(d.querySelectorAll("#list .item").length,3,"add button should add exactly one item");
 d.getElementById("compareBtn").click();await new Promise(r=>setTimeout(r,20));assert.notStrictEqual(d.getElementById("results").style.display,"none","compare should render results");assert(/ca\.|Referenz/i.test(d.getElementById("winnerPrice").textContent+" "+d.getElementById("winnerCoverage").textContent),"reference fallback should be visibly marked");
 assert(!/\bdm\b|Rossmann/.test(d.getElementById("merchantResults").textContent),"drugstores must not appear as complete baskets containing meat");
 assert(d.getElementById("merchantResults").textContent.includes("Preisquellen anzeigen"),"market totals should expose their underlying product price sources");
 assert.strictEqual(d.querySelectorAll("#list .item").length,3,"basket should render only once");
 const oldPrice=d.getElementById("winnerPrice").textContent;
 w.addEchtpreisItem("10 Eier");assert.strictEqual(d.querySelectorAll("#list .item").length,4);
 assert.notStrictEqual(d.getElementById("winnerPrice").textContent,oldPrice,"adding after comparison must automatically update total");
 d.querySelector("[data-edit=\"3\"]").click();d.querySelector("[data-edit-input=\"3\"]").value="20 Eier";d.querySelector("[data-save-edit=\"3\"]").click();
 assert.strictEqual(w.getEchtpreisRawList()[3],"20 Eier");assert.notStrictEqual(d.getElementById("winnerPrice").textContent,oldPrice,"edited quantity must be compared again");
 assert(d.querySelector(".savings-card").previousElementSibling.classList.contains("winner"),"savings should follow winner");
 d.querySelector("[data-del=\"3\"]").click();assert.strictEqual(d.getElementById("winnerPrice").textContent,oldPrice,"deleting after comparison must restore total");
 d.querySelector("[data-check=\"0\"]").click();assert(d.getElementById("clearChecked"),"checked items should offer a compact cleanup action");d.getElementById("clearChecked").click();assert.strictEqual(d.querySelectorAll("#list .item").length,2,"completed items should be removable in one action");
 console.log("browser smoke OK · single basket · quantity parser · receipt parser");
 dom.window.close();
})().catch(e=>{console.error(e);process.exit(1)});
