"use strict";
const assert=require('assert/strict'),fs=require('fs'),{JSDOM,VirtualConsole}=require('jsdom');
const gtin='4046700026519';
function quote(patch={}){const capturedAt=new Date(Date.now()-1000).toISOString(),offer={sourceId:'Wolt EDEKA Berlin',merchant:'EDEKA',nativeVenueId:'67ebb70ed3581534a525c522',retailerSku:'1dc18e85145be6774701f54d',gtin,name:'BROWSER TEST Milch 1,5%',brand:null,pack:'1 l',packAmount:1000,packUnit:'ml',packCount:1,price:1.29,deposit:null,displayedPrice:1.29,nativePriceIncludesDeposit:true,payablePackPrice:null,currency:'EUR',priceBasis:'pack',capturedAt,expiresAt:new Date(Date.now()+3600000).toISOString(),proofHash:'a'.repeat(64),sourceUrl:'https://wolt.com/de/deu/berlin/venue/edeka-hilbrecht',shop:{name:'EDEKA Hilbrecht',address:'Ritterstr. 38-40',postalCode:'10969',city:'Berlin',country:'DE',nativeVenueId:'67ebb70ed3581534a525c522'},scopeCountry:'DE',scopeChannel:'online',state:'published',current:true,truthEligible:false,shippingIncluded:false,serviceFeesIncluded:false,...patch};return{offer,reference:{kind:'last-observed',city:'Berlin',country:'DE',merchant:offer.merchant,key:JSON.stringify([offer.gtin||offer.retailerSku,offer.pack]),identityKind:offer.gtin?'native-gtin':'native-retailer-sku',observedAt:offer.capturedAt,sourceMarket:offer.shop,observedMarkets:1,knownPriceRange:{min:offer.price,max:offer.price}}};}
async function setup(){const errors=[],calls=[],vc=new VirtualConsole();vc.on('jsdomError',e=>errors.push(e.message));let next=quote(),hold=null;
 const dom=new JSDOM(fs.readFileSync('index.html','utf8'),{runScripts:'dangerously',url:'https://julienfehlberg.github.io/Echtpreis/',pretendToBeVisual:true,virtualConsole:vc,beforeParse(w){
  w.AbortController=global.AbortController;w.SPARKORB_CONFIG={apiBase:'https://prices.example.test'};
  w.fetch=async(input)=>{const u=new URL(String(input),w.location.href);if(u.pathname==='/v1/berlin-reference-prices'){calls.push(u);const row=next;if(hold){const wait=hold;hold=null;await wait;}return{ok:true,json:async()=>({ok:true,city:'Berlin',country:'DE',items:[row],bounded:true,truncated:false})};}return{ok:false,status:503,json:async()=>({})};};
  for(const file of ['app/price-engine.js','app/current-price-client.js','app/published-product-client.js','app/berlin-reference-client.js'])w.eval(fs.readFileSync(file,'utf8'));
  w.alert=()=>{};w.confirm=()=>true;w.prompt=()=>null;w.scrollTo=()=>{};w.HTMLElement.prototype.scrollIntoView=function(){};
  Object.defineProperty(w.navigator,'geolocation',{configurable:true,value:{getCurrentPosition:()=>{throw Error('Location must not be required')}}});
  w.localStorage.setItem('sparkorb_receipt_consent','0');
 }});await new Promise(resolve=>setTimeout(resolve,60));
 return{dom,w:dom.window,calls,errors,set(row){next=row;},hold(){let release;hold=new Promise(resolve=>{release=resolve});return release;}};
}
async function waitFor(fn){for(let i=0;i<150;i++){if(fn())return;await new Promise(r=>setTimeout(r,5));}throw Error('Expected Berlin reference UI did not appear');}
(async()=>{const f=await setup(),w=f.w,d=w.document;try{
 w.eval("selected=new Set(['ALDI','PENNY','REWE','Lidl','Kaufland','EDEKA']);verifiedPriceLocation=null;nearbyStores=[];basket=[parseWish('1 l Milch')];comparisonRevision++;hasCompared=false;");
 await w.compare({skipLocation:true,scroll:false});const section=d.getElementById('berlinReferenceComparison');assert.equal(section.style.display,'block');assert(section.textContent.includes('EDEKA Hilbrecht'));assert(section.textContent.includes('Ritterstr. 38-40'));assert(section.textContent.includes('1,29'));assert(section.textContent.includes('Lieferung'));assert(section.textContent.includes('Pfand unbekannt'));assert(section.textContent.includes('Preisart offen'));assert(section.textContent.includes('Stand'));assert(!section.textContent.includes('Durchschnitt'));assert(section.textContent.includes('Noch kein passender Berliner Preisbeleg: ALDI, PENNY, REWE, Lidl, Kaufland'));assert.equal(f.calls[0].searchParams.get('pack'),'1 l');assert.equal(d.getElementById('storeComparisonDetails').open,false);assert.equal(d.getElementById('physicalComparison').style.display,'none');
 w.eval("basket[0].selectedProduct={gtin:'4046700026519',name:'Milch',brand:null,pack:'1 l',packAmount:1000,packUnit:'ml',packCount:1};comparisonRevision++;");f.set(quote({pack:'500 ml',packAmount:500}));await w.compare({skipLocation:true,scroll:false});assert(!section.textContent.includes('1,29'),'Different sales pack must not populate exact shopping item');assert.equal(f.calls.at(-1).searchParams.get('gtin'),gtin);assert.equal(f.calls.at(-1).searchParams.get('pack'),'1 l');
 f.set(quote({expiresAt:new Date(Date.now()-1).toISOString()}));await w.compare({skipLocation:true,scroll:false});assert(!section.textContent.includes('1,29'),'Expired quote must disappear');
 w.eval('delete basket[0].selectedProduct;comparisonRevision++;');f.set(quote({gtin:null}));await w.compare({skipLocation:true,scroll:false});assert(section.textContent.includes('1,29'),'Native SKU reference must remain visible without invented GTIN');assert(!w.eval('basket[0].selectedProduct'));
 f.set(quote());w.eval('comparisonRevision++;');let releaseCanonical;w.loadCanonicalComparison=()=>new Promise(resolve=>{releaseCanonical=resolve});const pending=w.compare({skipLocation:true,scroll:false});await waitFor(()=>section.style.display==='block'&&section.textContent.includes('1,29'));assert.equal(d.getElementById('results').style.display,'block');assert.equal(d.getElementById('storeComparisonDetails').style.display,'none','Old results stay hidden while they load');releaseCanonical();await pending;
 w.loadCanonicalComparison=async()=>{};f.set(quote());const release=f.hold(),before=f.calls.length,stale=w.compare({skipLocation:true,scroll:false});await waitFor(()=>f.calls.length>before);w.eval("basket=[parseWish('250 g Butter')];comparisonRevision++;");f.set(quote({gtin:'4008400401621',name:'BROWSER TEST Butter',pack:'250 g',packAmount:250,packUnit:'g',price:2.19,displayedPrice:2.19}));await w.compare({skipLocation:true,scroll:false});release();await stale;assert(section.textContent.includes('Butter'));assert(section.textContent.includes('2,19'));assert(!section.textContent.includes('1,29'),'Old basket response cannot overwrite newer results');assert.deepEqual(f.errors,[]);
 console.log('browser-berlin-reference: city prices without location/branch selection, native SKU visibility, exact pack binding, expiry, immediate independent rendering and stale basket race OK');
 }finally{w.close();}})().catch(e=>{console.error(e);process.exitCode=1;});
