const fs=require("fs"),assert=require("assert");
const {JSDOM,VirtualConsole}=require("jsdom");
(async()=>{
 const html=fs.readFileSync("index.html","utf8"),errors=[],vc=new VirtualConsole();
 vc.on("jsdomError",e=>errors.push(String(e.message||e)));
 const dom=new JSDOM(html,{runScripts:"dangerously",url:"https://julienfehlberg.github.io/Echtpreis/",pretendToBeVisual:true,virtualConsole:vc,beforeParse(w){
  w.fetch=async()=>({ok:false,status:503,json:async()=>({})});w.alert=()=>{};w.confirm=()=>true;w.prompt=()=>null;w.scrollTo=()=>{};Object.defineProperty(w.navigator,"geolocation",{configurable:true,value:{getCurrentPosition:(ok,fail)=>fail&&fail({code:1})}});
  if(w.HTMLElement)w.HTMLElement.prototype.scrollIntoView=function(){};
 }});
 await new Promise(r=>setTimeout(r,120));
 const w=dom.window,d=w.document;
 assert.strictEqual(errors.length,0,"browser startup errors: "+errors.join(" | "));
 assert(![...d.body.childNodes].some(n=>n.nodeType===3&&n.textContent.trim()),"stray CSS or text appears before the app");
 d.getElementById("homePlan").click();
 assert.strictEqual(d.getElementById("planner").previousElementSibling.id,"homePlan","opened list must appear directly after its menu button");
 assert.strictEqual(d.getElementById("planner").nextElementSibling.id,"homeReceipt","receipt menu must follow the opened list");
 assert.strictEqual(d.getElementById("homeReceipt").nextElementSibling.id,"receipt","receipt panel must follow its menu button");
 assert.strictEqual(d.getElementById("planner").style.display,"block","list should be expanded");
 d.getElementById("homeReceipt").click();
 assert.strictEqual(d.getElementById("receipt").previousElementSibling.id,"homeReceipt","opened receipt analysis must appear directly below its menu button");
 assert.strictEqual(d.getElementById("receipt").nextElementSibling.id,"homeStats","statistics menu must follow receipt analysis");
 assert.strictEqual(d.getElementById("receipt").style.display,"block","receipt analysis should be expanded");
 w.Tesseract={recognize:async()=>({data:{text:"EDEKA\nMilch 1,09\nBananen 1,79\nSUMME 2,88"}})};
 const receiptInput=d.getElementById("receiptFile");
 Object.defineProperty(receiptInput,"files",{configurable:true,value:[new w.File(["receipt"],"bon.jpg",{type:"image/jpeg"})]});
 receiptInput.dispatchEvent(new w.Event("change"));await new Promise(r=>setTimeout(r,20));
 assert.strictEqual(d.getElementById("receiptStore").value,"EDEKA","receipt merchant should be detected");
 assert(d.getElementById("ocrStatus").textContent.includes("mögliche Preiszeilen"),"receipt OCR must complete without a missing status element");
 assert.strictEqual(d.getElementById("receiptAnalysis").style.display,"block","receipt analysis should appear after OCR");
 assert.strictEqual(d.getElementById("finishPurchaseBtn").disabled,false,"receipt should be reviewable after OCR");
 const today=new Date().toISOString().slice(0,10);
 w.localStorage.setItem("echtpreis_personal_receipts",JSON.stringify([{id:"test-receipt",date:today,total:"12.50",potentialSaving:2.10}]));
 d.getElementById("homeStats").click();
 assert.strictEqual(d.getElementById("statsReceipts").textContent,"1","statistics should count saved receipts");
 assert.strictEqual(d.getElementById("statsSpent").textContent,"12,50 €","statistics should sum spending for this year");
 assert.strictEqual(d.getElementById("statsMonthly").textContent,"12,50 €","statistics should sum spending for this month");
 assert(d.getElementById("statsPotential").textContent.includes("2,10"),"statistics should show known estimated savings");
 assert.strictEqual(typeof w.parseWish,"function");
 let p=w.parseWish("0,5 kg Tomaten");assert.strictEqual(p.key,"tomaten");assert.strictEqual(p.amount,0.5);assert.strictEqual(p.unit,"kg");
 p=w.parseWish("2 l Coca Cola");assert.strictEqual(p.key,"cola");assert.strictEqual(p.matchMode,"exact");
 p=w.parseWish("500 g Erdbeeren");assert.strictEqual(p.key,"erdbeeren");assert.strictEqual(p.unit,"kg");assert.strictEqual(p.amount,0.5);assert(w.referencePrice("erdbeeren","Lidl",p)?.reference,"strawberry reference fallback missing");
 p=w.parseWish("250 g Blaubeeren");assert.strictEqual(p.key,"blaubeeren");assert(w.referencePrice("blaubeeren","REWE",p)?.price>0,"blueberry reference fallback missing");
 p=w.parseWish("1 kg Süßkartoffeln");assert.strictEqual(p.key,"suesskartoffeln");
 let restored=w.restoreBasketItem({raw:"Lachs",choice:{Art:"frozen",Menge:"500g"},checked:true});assert.strictEqual(restored.needsClarification,false,"saved product choice must survive reload");assert.strictEqual(restored.checked,true);
 restored=w.restoreBasketItem({raw:"250 g Testprodukt",ean:"12345678",label:"Testprodukt · 250 g"});assert.strictEqual(restored.key,"ean:12345678","barcode identity must survive reload");
 assert.strictEqual(w.identifyReceiptProduct("Red Bull 0,25").key,"energydrink");
 const rb=w.inferPackFromName("Red Bull 0,25");assert.strictEqual(rb.packAmount,0.25);assert.strictEqual(rb.packUnit,"l");
 const receipt=w.parseReceiptText("G&G Mini-Hörnchen 1,49\nOetker Ristorante 3,49\nRed Bull 0,25 1,49 x 2 2,98\nPfand 0,25 x 2 0,50\nSUMME 8,46");
 await w.addEchtpreisBarcode("Testprodukt","250 g","12345678");assert.strictEqual(d.querySelectorAll("#list .item").length,1,"barcode product should enter the primary basket");w.replaceEchtpreisList([]);
 assert(receipt.length>=4,"receipt parser lost rows");
 assert(receipt.some(x=>x.isDeposit),"deposit line not recognized");
 w.localStorage.removeItem("echtpreis_open_purchase");d.getElementById("compareBtn").click();await new Promise(r=>setTimeout(r,20));assert.strictEqual(w.localStorage.getItem("echtpreis_open_purchase"),null,"failed comparison must not open a purchase");
 d.getElementById("demoListBtn").click();assert.strictEqual(d.querySelectorAll("#list .item").length,2,"demo list must use primary basket only");let ambiguous=w.parseWish("Lachs");assert.strictEqual(ambiguous.needsClarification,true,"ambiguous salmon must require a variant");let precise=w.parseWish("500 g TK Lachs");assert.strictEqual(precise.needsClarification,false,"precise salmon should be comparison-ready");
 d.getElementById("productInput").value="0,5 kg Tomaten";d.getElementById("addBtn").click();assert.strictEqual(d.querySelectorAll("#list .item").length,3,"add button should add exactly one item");
 d.getElementById("compareBtn").click();await new Promise(r=>setTimeout(r,20));assert.notStrictEqual(d.getElementById("results").style.display,"none","compare should render results");assert(/ca\.|Referenz/i.test(d.getElementById("winnerPrice").textContent+" "+d.getElementById("winnerCoverage").textContent),"reference fallback should be visibly marked");
 assert.strictEqual(d.querySelectorAll("#list .item").length,3,"basket should render only once");
 const oldPrice=d.getElementById("winnerPrice").textContent;
 w.addEchtpreisItem("10 Eier");assert.strictEqual(d.querySelectorAll("#list .item").length,4);
 assert.notStrictEqual(d.getElementById("winnerPrice").textContent,oldPrice,"adding after comparison must automatically update total");
 d.querySelector("[data-edit=\"3\"]").click();d.querySelector("[data-edit-input=\"3\"]").value="20 Eier";d.querySelector("[data-save-edit=\"3\"]").click();
 assert.strictEqual(w.getEchtpreisRawList()[3],"20 Eier");assert.notStrictEqual(d.getElementById("winnerPrice").textContent,oldPrice,"edited quantity must be compared again");
 assert(d.querySelector(".savings-card").previousElementSibling.classList.contains("winner"),"savings should follow winner");
 d.querySelector("[data-del=\"3\"]").click();assert.strictEqual(d.getElementById("winnerPrice").textContent,oldPrice,"deleting after comparison must restore total");
 console.log("browser smoke OK · single basket · quantity parser · receipt parser");
 dom.window.close();
})().catch(e=>{console.error(e);process.exit(1)});
