const assert=require("assert"),R=require("../current-price-resolver");
const today="2026-09-30",mark=xs=>xs.map(x=>x.sourceType?x:{...x,sourceType:"open_data"}),rows=[
{merchant:"EDEKA",product:"Rinderhack 500 g",brand:"Gut & Günstig",pack:"500 g",price:3.99,date:today,observedAt:today,priceType:"promotion",region:"Berlin",source:"edeka",proof:"a",sourceHealthScore:95},
{merchant:"ALDI",product:"Rinderhackfleisch 500 g",brand:"Meine Metzgerei",pack:"500 g",price:4.49,date:today,region:"Berlin",source:"aldi",proof:"b",sourceHealthScore:95},
{merchant:"LIDL",product:"Rinderhack 500 g",price:2.99,date:"2026-09-01",region:"Berlin",source:"lidl",proof:"old",sourceHealthScore:95},
{merchant:"REWE",product:"Veganes Hack 250 g",price:1.99,date:today,region:"Berlin",source:"rewe",proof:"v",sourceHealthScore:95}
];
let out=R.compare({name:"Rinderhack"},["EDEKA","ALDI","LIDL"],mark(rows),{today,region:"Berlin",maxAgeDays:7});assert.strictEqual(out[0].price,3.99,JSON.stringify(out[0]));assert.strictEqual(out[1].price,4.49,JSON.stringify(out[1]));assert.strictEqual(out[2].state,"unknown",JSON.stringify(out[2]));
assert.strictEqual(R.queryMode({name:"Hackfleisch"}),"category");assert.strictEqual(R.queryMode({name:"Nutella",brand:"Ferrero",pack:"450 g"}),"sku");
console.log("current-price-resolver: ok");
{const rows=[{merchant:"EDEKA",product:"Rinderhack 500 g",price:4.99,date:today,region:"Berlin",storeId:"other",priceType:"regular",proof:"x",sourceHealthScore:95},{merchant:"EDEKA",product:"Rinderhack 500 g",price:3.99,date:today,region:"Berlin",priceType:"regular",proof:"y",sourceHealthScore:95}];let x=R.resolveMerchant({name:"Rinderhack"},"EDEKA",mark(rows),{today,region:"Berlin",storeId:"mine"});assert.strictEqual(x.price,3.99);assert.strictEqual(x.locationLevel,"regional-fallback");}
{const rows=[{merchant:"EDEKA",product:"Rinderhack 500 g",price:2.99,date:today,region:"Berlin",priceType:"app",proof:"a",sourceHealthScore:95},{merchant:"EDEKA",product:"Rinderhack 500 g",price:3.99,date:today,region:"Berlin",priceType:"regular",proof:"b",sourceHealthScore:95}];assert.strictEqual(R.resolveMerchant({name:"Rinderhack"},"EDEKA",mark(rows),{today,region:"Berlin"}).price,3.99);const app=R.resolveMerchant({name:"Rinderhack"},"EDEKA",mark(rows),{today,region:"Berlin",eligibility:{app:true}});assert.strictEqual(app.price,2.99);assert.strictEqual(app.payablePrice,2.99);assert.strictEqual(app.publicReferencePrice,3.99);assert.strictEqual(app.conditional,true);}
{const rows=[{merchant:"EDEKA",product:"Rinderhack 500 g",price:3.49,date:today,region:"Berlin",priceType:"regular",proof:"a",sourceHealthScore:95},{merchant:"EDEKA",product:"Rinderhack 500 g",price:4.49,date:today,region:"Berlin",priceType:"regular",proof:"b",sourceHealthScore:95}];assert.strictEqual(R.resolveMerchant({name:"Rinderhack"},"EDEKA",mark(rows),{today,region:"Berlin"}).state,"unknown");}

{const expired=[{merchant:"EDEKA",product:"Butter 250 g",price:1.99,date:today,observedAt:today,validFrom:"2026-09-20",validTo:"2026-09-29",region:"Berlin",priceType:"promotion",proof:"expired",sourceHealthScore:95},{merchant:"EDEKA",product:"Butter 250 g",price:2.49,date:today,observedAt:today,region:"Berlin",priceType:"regular",proof:"current",sourceHealthScore:95}];const x=R.resolveMerchant({name:"Butter"},"EDEKA",mark(expired),{today,region:"Berlin"});assert.strictEqual(x.price,2.49);}
{const future=[{merchant:"EDEKA",product:"Butter 250 g",price:1.79,date:today,observedAt:today,validFrom:"2026-10-01",validTo:"2026-10-07",region:"Berlin",priceType:"promotion",proof:"future",sourceHealthScore:95}];assert.strictEqual(R.resolveMerchant({name:"Butter"},"EDEKA",mark(future),{today,region:"Berlin"}).state,"unknown");}

{const stale=[{merchant:"EDEKA",product:"Butter 250 g",price:1.99,date:"2026-09-01",observedAt:"2026-09-01",validFrom:"2026-09-01",validTo:"2026-10-05",region:"Berlin",priceType:"promotion",proof:"stale-valid-window",sourceHealthScore:95}];assert.strictEqual(R.resolveMerchant({name:"Butter"},"EDEKA",mark(stale),{today,region:"Berlin",maxAgeDays:7}).state,"unknown");}

{const multi=[{merchant:"EDEKA",product:"Cola 1L",price:1.25,date:today,observedAt:today,region:"Berlin",priceType:"multi_buy",minQuantity:2,proof:"multi",sourceHealthScore:95},{merchant:"EDEKA",product:"Cola 1L",price:1.49,date:today,observedAt:today,region:"Berlin",priceType:"regular",proof:"single",sourceHealthScore:95}];assert.strictEqual(R.resolveMerchant({name:"Cola"},"EDEKA",mark(multi),{today,region:"Berlin",quantity:1}).price,1.49);assert.strictEqual(R.resolveMerchant({name:"Cola"},"EDEKA",mark(multi),{today,region:"Berlin",quantity:2}).price,1.25);}
