"use strict";
const assert=require("node:assert/strict"),fs=require("node:fs"),path=require("node:path"),{JSDOM}=require("jsdom");
const View=require("../app/assortment-overview"),master=require("../data/grocery-assortment.json"),copy=value=>structuredClone(value),pause=()=>new Promise(resolve=>setTimeout(resolve,230));
async function main(){
 assert.equal(View.validateMaster(master),master);assert.equal(master.statistics.categories,37);assert.equal(master.statistics.productTypes,705);assert.equal(master.statistics.exampleVariants,1654);
 const ids=new Set();for(const category of master.categories)for(const type of category.productTypes){assert(!ids.has(type.id));ids.add(type.id);assert(!Object.hasOwn(type,"gtin"));assert(!Object.hasOwn(type,"price"));assert(!Object.hasOwn(type,"merchant"));}
 for(const query of["Milch","Wurst","Käse","Gemüse","Waschmittel","Katzenfutter","Zigaretten"]){assert(View.filterMaster(master,query).length,"Missing broad type: "+query);}
 assert(View.filterMaster(master,"Kase").length);assert(View.filterMaster(master,"tiefgekuhlt").length);assert.equal(View.filterMaster(master,"unbekanntesxyz").length,0);
 const subset=View.filterMaster(master,"",master.categories[0].id);assert.equal(subset.length,1);assert(subset[0].productTypes.length<705);
 for(const patch of[{retailerStockVerified:true},{currentPricesIncluded:true},{complete:true},{canonicalProductIdentities:true},{statistics:{...master.statistics,productTypes:706}}])assert.throws(()=>View.validateMaster({...master,...patch}),/invalid-assortment/);
 const duplicate=copy(master);duplicate.categories[0].productTypes.push(copy(duplicate.categories[0].productTypes[0]));assert.throws(()=>View.validateMaster(duplicate),/invalid-assortment/);
 for(const url of["javascript:alert(1)","http://www.aldi-nord.de/produkt/test-123.html","https://evil.example/","https://user:pass@wolt.com/"])assert.equal(View.safeSource(url),null);
 const article={merchant:"ALDI",sourceMerchant:"ALDI Nord",sourceId:"ALDI Nord published assortment",retailerSku:"1234567",name:"<script>Injected milk</script>",brand:"Beispiel",variant:"3,5 % Fett",pack:"1 l",gtin:null,scopeCountry:"DE",scopeChannel:"assortment-publication",locationScope:"unknown",sourceUrl:"https://www.aldi-nord.de/produkt/milch-1234567.html",observedAt:"2026-09-30T12:00:00.000Z",state:"last-observed",availability:"unknown",currentPriceVerified:false,assortmentComplete:false};
 assert.equal(View.safeArticle(article),article);for(const patch of[{state:"current"},{availability:"in-stock"},{scopeCountry:"AT"},{merchant:"EDEKA"},{scopeChannel:"online"},{currentPriceVerified:true},{assortmentComplete:true},{sourceUrl:"javascript:alert(1)"}])assert.equal(View.safeArticle({...article,...patch}),null);
 // This is an explicitly synthetic public display DTO; no archived retailer
 // original is moved to today or treated as a Berlin/price/stock observation.
 const category={identityKey:JSON.stringify(["ALDI Nord category publication","assortment-publication","1042504"]),kind:"native-retailer-article",merchant:"ALDI",sourceMerchant:"ALDI Nord",sourceId:"ALDI Nord category publication",retailerSku:"1042504",name:"UNIT TEST category rice",brand:"UNIT TEST",variant:"Langkornreis",pack:"1.000-g-Packung",packAmount:1000,packUnit:"g",packCount:1,gtin:null,scopeCountry:"DE",scopeChannel:"assortment-publication",locationScope:"unknown",scopeLabel:"Datierte Artikel aus Deutschland; Berlinfiliale unbekannt.",shop:null,sourceUrl:"https://www.aldi-nord.de/sortiment/vorraete/reis-nudeln-getreide.html",originalCategoryResponseUrl:"https://www.aldi-nord.de/sortiment/vorraete/reis-nudeln-getreide.html",sourceResponseUrl:"https://www.aldi-nord.de/sortiment/vorraete/reis-nudeln-getreide.html",productIdentityUrl:"https://www.aldi-nord.de/produkt/langkornreis-1042504.html",proofKind:"original-category-html",sourceResponseHash:"ab".repeat(32),observedAt:"2026-09-30T12:00:00.000Z",state:"last-observed",availability:"unknown",truthEligible:false,currentPriceVerified:false,physicalStorePriceVerified:false,normalPriceClassificationVerified:false,assortmentComplete:false,pricedOnly:false,independentOfPrice:true};
 const categoryBefore=copy(category);assert.equal(View.safeArticle(category),category);assert.deepEqual(category,categoryBefore,"Display validation preserves original source/hash/capture and native pack");
 for(const patch of[
  {sourceId:"ALDI Nord published assortment"},{sourceId:"ALDI Nord published assortment",sourceUrl:category.productIdentityUrl},{scopeCountry:"AT"},{scopeChannel:"physical-store"},{locationScope:"Berlin"},{shop:{city:"Berlin"}},{gtin:"3017620422003"},{merchant:"EDEKA"},
  {sourceUrl:category.productIdentityUrl},{sourceResponseUrl:category.productIdentityUrl},{originalCategoryResponseUrl:category.productIdentityUrl},{proofKind:"original-product-html"},{sourceResponseHash:"AB".repeat(32)},{sourceResponseHash:""},
  {sourceUrl:category.sourceUrl+"?page=0"},{sourceResponseUrl:category.sourceUrl+"#products"},{sourceUrl:category.sourceUrl.replace("www.aldi-nord.de","www.aldi-sued.de")},{productIdentityUrl:category.productIdentityUrl.replace("1042504","1042505")},{productIdentityUrl:category.productIdentityUrl+"?x=1"},{productIdentityUrl:"https://u:p@www.aldi-nord.de/produkt/langkornreis-1042504.html"},
  {retailerSku:"01042504"},{identityKey:JSON.stringify(["ALDI Nord published assortment","assortment-publication","1042504"])},{observedAt:"2026-09-30T12:00:00Z"},{observedAt:new Date(Date.now()+60000).toISOString()},
  {packAmount:0},{packAmount:Infinity},{packUnit:"kg"},{packCount:1.5},{packCount:1001},{name:"<script>milk</script>"},{variant:"rice\u0000water"},
  {price:1.19},{current:true},{availability:"in-stock"},{currentPriceVerified:true},{currentAvailabilityVerified:true},{normalPriceClassificationVerified:true},{physicalStorePriceVerified:true},{truthEligible:true},{pricedOnly:true},{independentOfPrice:false},{expiresAt:new Date(Date.now()+86400000).toISOString()},
  {rawNativeProduct:{objectID:"1042504"}},{nativeProduct:{objectID:"1042504"}},{body:"private original"},{nativeWitness:{raw:"private"}}
 ])assert.equal(View.safeArticle({...category,...patch}),null,"Reject changed category display boundary: "+Object.keys(patch).join(","));
 for(const field of["sourceResponseHash","sourceResponseUrl","originalCategoryResponseUrl","productIdentityUrl","proofKind","gtin","shop"]){const missing=copy(category);delete missing[field];assert.equal(View.safeArticle(missing),null,"Category display proof is required: "+field);}
 const dom=new JSDOM(fs.readFileSync(path.join(__dirname,"../sortiment.html"),"utf8"),{url:"https://test.local/sortiment.html"}),document=dom.window.document,calls=[];
 const fetcher=async url=>{calls.push(url);if(url==="data/grocery-assortment.json")return{ok:true,json:async()=>master};const params=new URL(url).searchParams,merchant=params.get("merchant");return{ok:true,json:async()=>({merchant,assortmentComplete:false,status:merchant==="ALDI"?"observed-articles":"unsupported-source",items:merchant==="ALDI"?[article]:[]})};};
 const mounted=View.mount(document,fetcher);await mounted.ready;assert.equal(document.getElementById("typeCount").textContent,"705");assert.equal(document.querySelectorAll(".category").length,37);assert.equal(calls.length,1,"Master must load without merchant HTTP");
 document.getElementById("assortmentSearch").value="Wurst";document.getElementById("assortmentSearch").dispatchEvent(new dom.window.Event("input"));await pause();assert(document.querySelectorAll(".type-card").length>1);assert(document.querySelectorAll(".type-card").length<705);
 document.getElementById("clearSearch").click();assert.equal(document.querySelectorAll(".type-card").length,705);document.getElementById("expandAll").click();assert([...document.querySelectorAll(".category")].every(d=>d.open));
 document.getElementById("articlesTab").click();await pause();assert.equal(document.getElementById("masterPanel").hidden,true);assert.equal(document.querySelectorAll(".article-card").length,1);assert.equal(document.querySelectorAll(".article-card script").length,0);assert(document.querySelector(".article-card h3").textContent.includes("<script>"));assert(document.getElementById("articleScope").textContent.includes("keine Berliner Filiale"));assert(!document.querySelector(".article-card").textContent.includes("€"));
 [...document.querySelectorAll("#merchantFilter button")].find(b=>b.textContent==="PENNY").click();await pause();assert.equal(document.querySelectorAll(".article-card").length,0);assert(document.getElementById("articleResult").textContent.includes("noch keine Artikel erfasst"));assert(!document.getElementById("articleResult").textContent.includes("führt"));
 document.getElementById("masterTab").click();assert.equal(document.querySelectorAll(".type-card").length,705);assert.equal(document.getElementById("typeCount").textContent,"705","Article searches must not inflate master counts");dom.window.close();
 const categoryDom=new JSDOM(fs.readFileSync(path.join(__dirname,"../sortiment.html"),"utf8")),categoryDocument=categoryDom.window.document;
 const categoryMounted=View.mount(categoryDocument,async url=>url==="data/grocery-assortment.json"?{ok:true,json:async()=>master}:{ok:true,json:async()=>({merchant:"ALDI",assortmentComplete:false,status:"observed-articles",items:[category,{...category,price:.99},{...category,body:"private"}]})});
 await categoryMounted.ready;categoryDocument.getElementById("articlesTab").click();await pause();assert.equal(categoryDocument.querySelectorAll(".article-card").length,1,"Only a closed category original DTO can render");const categoryCard=categoryDocument.querySelector(".article-card"),links=[...categoryCard.querySelectorAll("a")];assert.deepEqual(links.map(link=>link.href),[category.sourceUrl,category.productIdentityUrl],"Actual category evidence and separate product identity link are not interchangeable");assert(links[0].textContent.includes("Originalquelle"));assert(links[1].textContent.includes("Produktlink"));assert(links.every(link=>link.rel==="noopener noreferrer"));assert(categoryCard.textContent.includes("Deutschland"));assert(categoryCard.textContent.includes("1.000-g-Packung"));assert(categoryCard.textContent.includes("30.09.26"));assert(!categoryCard.textContent.includes("€"));assert(!categoryCard.textContent.includes("Normalpreis"));assert(categoryDocument.getElementById("articleScope").textContent.includes("keine Berliner Filiale"));assert.equal(categoryDocument.getElementById("typeCount").textContent,"705");assert.deepEqual(category,categoryBefore);categoryDom.window.close();
 // A previous merchant response must not appear under the newly typed search, even before debounce expires.
 const slowDom=new JSDOM(fs.readFileSync(path.join(__dirname,"../sortiment.html"),"utf8")),slowDocument=slowDom.window.document;let resolveOld;
 const slow=View.mount(slowDocument,async url=>{if(url==="data/grocery-assortment.json")return{ok:true,json:async()=>master};if(!new URL(url).searchParams.has("search"))return new Promise(resolve=>{resolveOld=resolve;});return{ok:true,json:async()=>({merchant:"ALDI",assortmentComplete:false,status:"no-observed-articles",items:[]})};});await slow.ready;slowDocument.getElementById("articlesTab").click();slowDocument.getElementById("assortmentSearch").value="Butter";slowDocument.getElementById("assortmentSearch").dispatchEvent(new slowDom.window.Event("input"));resolveOld({ok:true,json:async()=>({merchant:"ALDI",assortmentComplete:false,status:"observed-articles",items:[article]})});await new Promise(resolve=>setImmediate(resolve));assert.equal(slowDocument.querySelectorAll(".article-card").length,0);assert(slowDocument.getElementById("articleResult").textContent.includes("aktualisiert"));await pause();assert.equal(slowDocument.querySelectorAll(".article-card").length,0);slowDom.window.close();
 // EDEKA identities can be browsed beyond the first page without price-only restrictions.
 const edekaDom=new JSDOM(fs.readFileSync(path.join(__dirname,"../sortiment.html"),"utf8")),edekaDocument=edekaDom.window.document,edekaCalls=[];
 const edekaArticle=index=>({...article,merchant:"EDEKA",sourceMerchant:"EDEKA",sourceId:"Wolt EDEKA Berlin",retailerSku:index.toString(16).padStart(24,"0"),name:"UNIT TEST dated delivery article "+index,scopeChannel:"online",sourceUrl:"https://wolt.com/de/deu/berlin/venue/edeka-hilbrecht",shop:{name:"EDEKA Hilbrecht",address:"Ritterstr. 38-40",city:"Berlin"}});
 const edekaMounted=View.mount(edekaDocument,async url=>{if(url==="data/grocery-assortment.json")return{ok:true,json:async()=>master};const params=new URL(url).searchParams,merchant=params.get("merchant"),offset=Number(params.get("offset"));edekaCalls.push({merchant,offset});return{ok:true,json:async()=>({merchant,assortmentComplete:false,offsetSupported:merchant==="EDEKA",scannedRows:offset===0?50:4,nextOffset:offset===0?50:54,hasMore:merchant==="EDEKA"&&offset===0,status:"observed-articles",note:merchant==="EDEKA"?"Datierte EDEKA Lieferartikel, auch ohne Preis.":"ALDI Artikel",items:merchant!=="EDEKA"?[]:offset===0?Array.from({length:49},(_,i)=>edekaArticle(i+1)):[edekaArticle(49),edekaArticle(50),edekaArticle(51),edekaArticle(52)]})};});await edekaMounted.ready;edekaDocument.getElementById("articlesTab").click();await pause();assert.equal(edekaDocument.getElementById("loadMore").hidden,true,"A merchant without offset support cannot expose an ineffective more button");
 [...edekaDocument.querySelectorAll("#merchantFilter button")].find(b=>b.textContent==="EDEKA").click();await pause();assert.equal(edekaDocument.querySelectorAll(".article-card").length,49);assert.equal(edekaDocument.getElementById("loadMore").hidden,false,"A filtered invalid row in a full SQL page must not hide later valid articles");assert.equal(edekaDocument.getElementById("articleScope").textContent,"Datierte EDEKA Lieferartikel, auch ohne Preis.");edekaDocument.getElementById("loadMore").click();await pause();assert.equal(edekaDocument.querySelectorAll(".article-card").length,52,"Append distinct native SKUs while deduplicating overlapping pages");assert.deepEqual(edekaCalls.filter(c=>c.merchant==="EDEKA").map(c=>c.offset),[0,50]);assert.equal(edekaDocument.getElementById("loadMore").hidden,true);assert(!edekaDocument.getElementById("articleList").textContent.includes("€"));edekaDom.window.close();
 await typedUiTests(category);
 console.log("OK grocery assortment overview: taxonomy, identity separation, raw/typed pagination, exact mapping/sidecar binding, lazy fallback, type races, search, merchant scope and safe rendering");
}
async function typedUiTests(category){
 const Types=require("../grocery-article-type-service"),mapping=Types.mappingStatus(),html=fs.readFileSync(path.join(__dirname,"../sortiment.html"),"utf8");
 const noDb={query(){throw Error("No real database/source call is permitted in this UI test");}},emptyStatus=async()=>{throw Error("No status query expected");};
 const native=(name,variant=null,sku="1042504",merchant="ALDI")=>{
  const item={...copy(category),name,variant,retailerSku:sku,productIdentityUrl:"https://www.aldi-nord.de/produkt/unit-type-"+sku+".html"};
  if(merchant==="EDEKA"){for(const key of["productIdentityUrl","originalCategoryResponseUrl","sourceResponseUrl","proofKind"])delete item[key];item.merchant=item.sourceMerchant="EDEKA";item.sourceId="Wolt EDEKA Berlin";item.scopeChannel="online";item.locationScope="native-venue";item.sourceUrl="https://wolt.com/de/deu/berlin/venue/edeka-hilbrecht";item.shop={name:"EDEKA Hilbrecht",address:"Ritterstr. 38-40",city:"Berlin"};}
  item.identityKey=JSON.stringify([item.sourceId,item.scopeChannel,item.retailerSku]);return item;
 };
 async function typedPage(rows,typeId,options={}){
  const merchant=options.merchant||rows[0]?.merchant||"ALDI",offset=options.offset||0,paged=["ALDI","EDEKA"].includes(merchant);
  const query={merchant,limit:50,now:Date.now(),productTypeId:typeId,...(paged?{offset}:{})};
  return Types.search(noDb,query,{directory:{status:emptyStatus,search:async()=>({ok:true,merchant,scopeCountry:"DE",truthEligible:false,currentPriceVerified:false,physicalStorePriceVerified:false,assortmentComplete:false,total:null,limit:50,offset,items:rows,returnedCount:rows.length,excludedRows:0,offsetSupported:paged,scannedRows:paged?rows.length:null,nextOffset:paged?offset+rows.length:null,hasMore:paged&&rows.length===50&&offset+rows.length<=10000,status:rows.length?"observed-articles":"no-observed-articles",note:"Datierte Artikelquelle; kein heutiger Filialbestand und kein Filialpreis."})}});
 }
 const gouda=native("Gouda"),goudaPage=await typedPage([gouda],"kaese.gouda"),colaPage=await typedPage([native("Cola",null,"1042505")],"getraenke.cola");
 const before=JSON.stringify(goudaPage);assert.equal(View.validateMapping(mapping,master),mapping);assert.equal(View.typedItems(goudaPage,"ALDI","kaese.gouda",0)[0],gouda);
 assert.equal(View.safeTypeAnnotation(goudaPage.typeAnnotations[0],gouda,"kaese.gouda").state,"assigned");assert.equal(JSON.stringify(goudaPage),before);
 for(const mutate of[value=>{value.taxonomySha256="0".repeat(64);},value=>{value.types.pop();},value=>{value.types[0].name="changed master name";},value=>{value.types[0].categoryId="other-category";},value=>{value.types[0].productTypeId="unknown-type";},value=>{value.types[1]=copy(value.types[0]);},value=>{value.types.find(t=>t.productTypeId==="kaese.gouda").state="mapping-unavailable";},value=>{value.types.find(t=>t.state==="mapping-unavailable").state="mapping-supported";},value=>{value.currentPriceVerified=true;},value=>{value.sourceValidationPerformed=true;},value=>{value.ruleCoveredProductTypes=26;},value=>{value.currentArticles=700;}]){
  const bad=copy(mapping);mutate(bad);assert.throws(()=>View.validateMapping(bad,master),/invalid-type-mapping/);
 }
 for(const mutate of[value=>{value.identityKey="other-capture";},value=>{value.binding.sourceResponseHash="0".repeat(64);},value=>{value.binding.observedAt="2026-10-01T12:00:00.000Z";},value=>{value.binding.sourceId="ALDI Nord published assortment";},value=>{value.annotation.state="ambiguous";},value=>{value.annotation.productTypeIds=["getraenke.cola"];},value=>{value.annotation.candidateTypeIds=["kaese.gouda"];},value=>{value.annotation.nativeRef.packCount=2;},value=>{value.annotation.nativeRef.sourceUrl=gouda.productIdentityUrl;},value=>{value.annotation.nativeRef.gtin="4046700026519";},value=>{value.annotation.sourceValidationPerformed=true;},value=>{value.annotation.truthEligible=true;},value=>{value.annotation.price=1.19;}]){
  const bad=copy(goudaPage.typeAnnotations[0]);mutate(bad);assert.equal(View.safeTypeAnnotation(bad,gouda,"kaese.gouda"),null);
 }
 assert.equal(View.safeTypeAnnotation(goudaPage.typeAnnotations[0],{...gouda,observedAt:"invalid"},"kaese.gouda"),null);
 assert.equal(View.safeTypeAnnotation(null,null,"kaese.gouda"),null);
 for(const patch of[{truthEligible:true},{physicalStorePriceVerified:true},{productId:"fake-canonical"},{price:1.19}]){
  const bad=copy(goudaPage);Object.assign(bad.items[0],patch);assert.throws(()=>View.typedItems(bad,"ALDI","kaese.gouda",0),/invalid-typed/);
 }
 for(const patch of[{packAmount:0},{packAmount:100000001},{packCount:0},{packCount:1.5},{packUnit:"kg"}]){
  const bad=copy(goudaPage);Object.assign(bad.items[0],patch);Object.assign(bad.typeAnnotations[0].annotation.nativeRef,patch);assert.throws(()=>View.typedItems(bad,"ALDI","kaese.gouda",0),/invalid-typed/);
 }
 for(const patch of[{scannedRows:"1"},{nextOffset:"1"},{nextOffset:2},{hasMore:true},{scannedRows:51}])assert.throws(()=>View.typedItems({...goudaPage,...patch},"ALDI","kaese.gouda",0),/invalid-typed-pagination/);
 const raw=(merchant="ALDI",items=[])=>({merchant,assortmentComplete:false,status:items.length?"observed-articles":"no-observed-articles",items});
 async function ui(handler){
  const dom=new JSDOM(html,{url:"https://test.local/sortiment.html"}),document=dom.window.document,calls=[];
  const mounted=View.mount(document,async url=>{calls.push(url);if(url==="data/grocery-assortment.json")return{ok:true,json:async()=>master};return handler(new URL(url));});
  await mounted.ready;assert.equal(calls.length,1,"Master browse does not depend on mapping API");
  return{dom,document,calls,select(typeId){if(document.getElementById("masterPanel").hidden){document.getElementById("masterTab").click();document.getElementById("clearSearch").click();}const button=document.querySelector('[data-product-type-id="'+typeId+'"]');assert(button,"Actual master type card exists: "+typeId);button.click();},merchant(name){[...document.querySelectorAll("#merchantFilter button")].find(button=>button.textContent===name).click();}};
 }
 const ok=data=>({ok:true,json:async()=>data});
 // Full genuine offline service chain: an explicitly synthetic whole HTML
 // original is reparsed by the native reader, then the Directory and typed
 // service return their actual unmodified DTO and Mapper sidecar to the UI.
 const Category=require("../aldi-category-article-service"),Directory=require("../assortment-article-directory"),Composite=require("../aldi-native-article-directory"),Fixture=require("./fixtures/aldi-category-capture");
 const clock=Date.now(),body=Fixture.html([Fixture.item({name:"Gouda",shortDescription:"",salesUnit:"250-g-Packung",currentPrice:null,isAvailable:false})]),original=Fixture.original(body,clock-1000);
 const parsed=Category.originalPage(original,clock).parsed,rows=parsed.candidates.map(candidate=>Category.rowForArticle(Category.articleFor(candidate,parsed.categoryId))),bodyPool={query:async()=>({rows:[{source_response_hash:original.meta.sourceResponseHash,body,body_bytes:Buffer.byteLength(body)}]})};
 const views=await Category.readRows(bodyPool,rows,{now:clock}),directory={status:emptyStatus,search:async(pool,options)=>Directory.search(pool,options,{aldi:{search:async(_db,query)=>({ok:true,sourceId:Composite.SOURCE,scopeCountry:"DE",scopeChannel:"assortment-publication",truthEligible:false,items:views,scannedRows:views.length,nextOffset:query.offset+views.length,hasMore:false})}})};
 const genuine=await Types.search(noDb,{merchant:"ALDI",productTypeId:"kaese.gouda",limit:50,now:clock},{directory}),genuineBefore=JSON.stringify(genuine);
 assert.equal(View.typedItems(genuine,"ALDI","kaese.gouda",0)[0],genuine.items[0]);assert.equal(genuine.typeAnnotations[0].annotation.nativeRef.observedAt,original.meta.capturedAt);assert.equal(genuine.items[0].sourceResponseHash,original.meta.sourceResponseHash);
 const fullPipeline=await ui(async url=>url.pathname.endsWith("/type-mapping")?ok(mapping):ok(genuine));fullPipeline.select("kaese.gouda");await pause();assert.equal(fullPipeline.document.querySelectorAll(".type-badge").length,1);assert.equal(fullPipeline.document.querySelector(".article-card h3").textContent,"Gouda");assert(fullPipeline.document.querySelector(".article-card").textContent.includes("250-g-Packung"));assert(fullPipeline.document.querySelector(".article-card").textContent.includes("Deutschland"));assert(!fullPipeline.document.querySelector(".article-card").textContent.includes("€"));assert.equal(JSON.stringify(genuine),genuineBefore);fullPipeline.dom.window.close();
 // Supported type cards use one lazy capability request, an explicit ID and a
 // visible broad retrieval hint. Merchant switches keep the chosen type.
 const selected=await ui(async url=>{
  if(url.pathname.endsWith("/type-mapping"))return ok(mapping);
  if(url.pathname.endsWith("/typed-articles"))return ok(url.searchParams.get("merchant")==="EDEKA"?await typedPage([native("Gouda",null,"abc000000000000000000001","EDEKA")],"kaese.gouda",{merchant:"EDEKA"}):goudaPage);
  return ok(raw(url.searchParams.get("merchant")));
 });
 selected.select("kaese.gouda");await pause();const d=selected.document;
 assert.equal(d.getElementById("assortmentSearch").value,"Gouda");assert(d.getElementById("selectedTypeFilter").textContent.includes("Produktart: Gouda"));assert.equal(d.querySelectorAll(".type-badge").length,1);assert.equal(d.querySelectorAll(".article-card").length,1);
 assert(d.querySelector(".article-card").textContent.includes("1.000-g-Packung"));assert(!d.querySelector(".article-card").textContent.includes("€"));assert(d.getElementById("typeFilterStatus").textContent.includes("Packung"));assert.equal(d.getElementById("typeCount").textContent,"705");
 selected.merchant("EDEKA");await pause();assert(d.getElementById("selectedTypeFilter").textContent.includes("Produktart: Gouda"));assert(d.querySelector(".article-card").textContent.includes("Lieferangebot"));assert.equal(d.querySelectorAll(".type-badge").length,1);
 const typedCalls=selected.calls.filter(url=>url.includes("/typed-articles?")).map(url=>new URL(url));assert.deepEqual(typedCalls.map(url=>url.searchParams.get("productTypeId")),["kaese.gouda","kaese.gouda"]);assert.deepEqual(typedCalls.map(url=>url.searchParams.get("search")),["Gouda","Gouda"]);assert.equal(selected.calls.filter(url=>url.endsWith("/type-mapping")).length,1);
 d.getElementById("assortmentSearch").value="Butter";d.getElementById("assortmentSearch").dispatchEvent(new selected.dom.window.Event("input"));assert.equal(d.getElementById("selectedTypeFilter").hidden,true);await pause();assert.equal(d.querySelectorAll(".type-badge").length,0);assert(selected.calls.at(-1).includes("/articles?"));assert.equal(new URL(selected.calls.at(-1)).searchParams.has("productTypeId"),false);
 d.getElementById("clearSearch").click();await pause();assert.equal(d.getElementById("selectedTypeFilter").hidden,true);assert.equal(new URL(selected.calls.at(-1)).searchParams.has("search"),false);selected.dom.window.close();
 // A supported type may legitimately have no matches in the current full raw
 // page. Its next pointer must still find later assigned native articles.
 const unassigned=Array.from({length:50},(_,i)=>native("UNIT neutral article",null,String(1043000+i))),emptyFull=await typedPage(unassigned,"kaese.gouda"),later=await typedPage([gouda],"kaese.gouda",{offset:50});
 const pages=await ui(async url=>url.pathname.endsWith("/type-mapping")?ok(mapping):ok(url.searchParams.get("offset")==="50"?later:emptyFull));pages.select("kaese.gouda");await pause();assert.equal(pages.document.querySelectorAll(".article-card").length,0);assert.equal(pages.document.getElementById("loadMore").hidden,false);assert(pages.document.getElementById("articleResult").textContent.includes("Ergebnisseite"));pages.document.getElementById("loadMore").click();await pause();assert.equal(pages.document.querySelectorAll(".type-badge").length,1);assert.equal(pages.document.getElementById("loadMore").hidden,true);assert.deepEqual(pages.calls.filter(url=>url.includes("/typed-articles?")).map(url=>new URL(url).searchParams.get("offset")),[null,"50"]);pages.dom.window.close();
 // The 680 unruled types keep ordinary text discovery; an unavailable rule is
 // never represented as absence of a product in a merchant's real assortment.
 const unavailable=await ui(async url=>url.pathname.endsWith("/type-mapping")?ok(mapping):ok(raw(url.searchParams.get("merchant"))));unavailable.select("getraenke.mineralwasser");await pause();assert(unavailable.document.getElementById("typeFilterStatus").textContent.includes("noch keinen Typfilter"));assert(unavailable.document.getElementById("typeFilterStatus").textContent.includes("Textsuche"));assert.equal(new URL(unavailable.calls.at(-1)).searchParams.get("search"),"Mineralwasser");assert(unavailable.calls.at(-1).includes("/articles?"));assert.equal(new URL(unavailable.calls.at(-1)).searchParams.has("productTypeId"),false);assert.equal(unavailable.document.querySelectorAll(".type-badge").length,0);assert(unavailable.document.getElementById("articleResult").textContent.includes("sagt nichts"));unavailable.dom.window.close();
 for(const capability of[null,{...copy(mapping),taxonomySha256:"0".repeat(64)}]){
  const fallback=await ui(async url=>url.pathname.endsWith("/type-mapping")?(capability?ok(capability):{ok:false}):ok(raw("ALDI",[gouda])));fallback.select("kaese.gouda");await pause();assert(fallback.document.getElementById("typeFilterStatus").textContent.includes("gerade nicht verfügbar"));assert(fallback.document.getElementById("typeFilterStatus").textContent.includes("Textsuche"));assert.equal(fallback.document.querySelectorAll(".type-badge").length,0);assert.equal(fallback.document.querySelectorAll(".article-card").length,1);assert.equal(fallback.calls.filter(url=>url.includes("/typed-articles?")).length,0);assert.equal(fallback.document.getElementById("typeCount").textContent,"705");fallback.dom.window.close();
 }
 // A forged/mismatched sidecar cannot grant a type badge or leave the user
 // trapped in a broken filter. The explicitly marked raw search remains usable.
 const changed=copy(goudaPage);changed.typeAnnotations[0].binding.sourceResponseHash="0".repeat(64);
 for(const payload of[changed,null]){
  const invalid=await ui(async url=>url.pathname.endsWith("/type-mapping")?ok(mapping):url.pathname.endsWith("/typed-articles")?(payload?ok(payload):{ok:false}):ok(raw("ALDI",[gouda])));invalid.select("kaese.gouda");await pause();assert.equal(invalid.document.querySelectorAll(".type-badge").length,0);assert(invalid.document.getElementById("typeFilterStatus").textContent.includes("Textsuche"));assert.equal(invalid.document.querySelectorAll(".article-card").length,1);assert.equal(invalid.calls.filter(url=>url.includes("/articles?")).length,1);invalid.dom.window.close();
 }
 // One in-flight capability request serves rapid selections, but only the
 // still-selected ID is allowed to issue/render a typed article request.
 let finishMapping;const mapRace=await ui(async url=>url.pathname.endsWith("/type-mapping")?new Promise(resolve=>{finishMapping=resolve;}):ok(colaPage));mapRace.select("kaese.gouda");mapRace.select("getraenke.cola");finishMapping(ok(mapping));await pause();assert.equal(mapRace.calls.filter(url=>url.endsWith("/type-mapping")).length,1);assert.deepEqual(mapRace.calls.filter(url=>url.includes("/typed-articles?")).map(url=>new URL(url).searchParams.get("productTypeId")),["getraenke.cola"]);assert.equal(mapRace.document.querySelector(".article-card h3").textContent,"Cola");mapRace.dom.window.close();
 let finishOld;const race=await ui(async url=>url.pathname.endsWith("/type-mapping")?ok(mapping):url.searchParams.get("productTypeId")==="kaese.gouda"?new Promise(resolve=>{finishOld=resolve;}):ok(colaPage));race.select("kaese.gouda");await pause();race.select("getraenke.cola");await pause();finishOld(ok(goudaPage));await new Promise(resolve=>setImmediate(resolve));assert.equal(race.document.querySelectorAll(".article-card").length,1);assert.equal(race.document.querySelector(".article-card h3").textContent,"Cola");assert(race.document.getElementById("selectedTypeFilter").textContent.includes("Cola"));race.dom.window.close();
 let finishTyped;const textRace=await ui(async url=>url.pathname.endsWith("/type-mapping")?ok(mapping):url.pathname.endsWith("/typed-articles")?new Promise(resolve=>{finishTyped=resolve;}):ok(raw()));textRace.select("kaese.gouda");await pause();textRace.document.getElementById("assortmentSearch").value="Butter";textRace.document.getElementById("assortmentSearch").dispatchEvent(new textRace.dom.window.Event("input"));finishTyped(ok(goudaPage));await new Promise(resolve=>setImmediate(resolve));assert.equal(textRace.document.querySelectorAll(".article-card").length,0);assert.equal(textRace.document.getElementById("selectedTypeFilter").hidden,true);await pause();assert.equal(textRace.document.querySelectorAll(".type-badge").length,0);assert(textRace.calls.at(-1).includes("/articles?"));textRace.dom.window.close();
 const plainMilk=await ui(async url=>url.pathname.endsWith("/type-mapping")?ok(mapping):ok(await typedPage([],"milch-sahne.h-kuhmilch")));plainMilk.select("milch-sahne.h-kuhmilch");await pause();assert.equal(plainMilk.document.getElementById("assortmentSearch").value,"Milch");assert(plainMilk.document.getElementById("selectedTypeFilter").textContent.includes("H-Kuhmilch"));assert.equal(new URL(plainMilk.calls.at(-1)).searchParams.get("productTypeId"),"milch-sahne.h-kuhmilch");plainMilk.dom.window.close();
 console.log("OK typed assortment UI: exact 705 capability binding, 25 supported/680 unavailable, separate capture-bound badges, truthful lazy raw fallback, empty-page pagination and selection/request races");
}
main().catch(error=>{console.error(error);process.exitCode=1;});
