"use strict";
const assert=require("node:assert/strict"),fs=require("node:fs"),path=require("node:path"),{JSDOM}=require("jsdom");
const View=require("../app/assortment-overview"),master=require("../data/grocery-assortment.json"),copy=value=>structuredClone(value),pause=()=>new Promise(resolve=>setTimeout(resolve,230));
async function main(){
 assert.equal(View.validateMaster(master),master);assert.equal(master.statistics.categories,37);assert.equal(master.statistics.productTypes,705);assert.equal(master.statistics.exampleVariants,1654);
 const ids=new Set();for(const category of master.categories)for(const type of category.productTypes){assert(!ids.has(type.id));ids.add(type.id);assert(!Object.hasOwn(type,"gtin"));assert(!Object.hasOwn(type,"price"));assert(!Object.hasOwn(type,"merchant"));}
 for(const query of["Milch","Wurst","Käse","Gemüse","Waschmittel","Katzenfutter","Zigaretten"]){assert(View.filterMaster(master,query).length,"Missing broad type: "+query);}
 assert(View.filterMaster(master,"Kase").length);assert(View.filterMaster(master,"tiefgekuhlt").length);assert.equal(View.filterMaster(master,"unbekanntesxyz").length,0);
 const subset=View.filterMaster(master,"",master.categories[0].id);assert.equal(subset.length,1);assert(subset[0].productTypes.length<705);
 for(const patch of[{retailerStockVerified:true},{currentPricesIncluded:true},{complete:true},{canonicalProductIdentities:true},{statistics:{...master.statistics,productTypes:706}}])assert.throws(()=>View.validateMaster({...master,...patch}),/invalid-assortment/);
 const duplicate=copy(master);duplicate.categories[0].productTypes.push(copy(duplicate.categories[0].productTypes[0]));assert.throws(()=>View.validateMaster(duplicate),/invalid-assortment/);
 for(const url of["javascript:alert(1)","http://www.aldi-nord.de/produkt/test-123.html","https://evil.example/","https://user:pass@wolt.com/"])assert.equal(View.safeSource(url),null);
 const article={merchant:"ALDI",sourceMerchant:"ALDI Nord",sourceId:"ALDI Nord published assortment",retailerSku:"1234567",name:"<script>Injected milk</script>",brand:"Beispiel",variant:"3,5 % Fett",pack:"1 l",gtin:null,scopeCountry:"DE",scopeChannel:"assortment-publication",locationScope:"unknown",sourceUrl:"https://www.aldi-nord.de/produkt/milch-1234567.html",observedAt:"2026-09-30T12:00:00.000Z",state:"last-observed",availability:"unknown",currentPriceVerified:false,assortmentComplete:false};
 assert.equal(View.safeArticle(article),article);for(const patch of[{state:"current"},{availability:"in-stock"},{scopeCountry:"AT"},{merchant:"EDEKA"},{scopeChannel:"online"},{currentPriceVerified:true},{assortmentComplete:true},{sourceUrl:"javascript:alert(1)"}])assert.equal(View.safeArticle({...article,...patch}),null);
 const dom=new JSDOM(fs.readFileSync(path.join(__dirname,"../sortiment.html"),"utf8"),{url:"https://test.local/sortiment.html"}),document=dom.window.document,calls=[];
 const fetcher=async url=>{calls.push(url);if(url==="data/grocery-assortment.json")return{ok:true,json:async()=>master};const params=new URL(url).searchParams,merchant=params.get("merchant");return{ok:true,json:async()=>({merchant,assortmentComplete:false,status:merchant==="ALDI"?"observed-articles":"unsupported-source",items:merchant==="ALDI"?[article]:[]})};};
 const mounted=View.mount(document,fetcher);await mounted.ready;assert.equal(document.getElementById("typeCount").textContent,"705");assert.equal(document.querySelectorAll(".category").length,37);assert.equal(calls.length,1,"Master must load without merchant HTTP");
 document.getElementById("assortmentSearch").value="Wurst";document.getElementById("assortmentSearch").dispatchEvent(new dom.window.Event("input"));await pause();assert(document.querySelectorAll(".type-card").length>1);assert(document.querySelectorAll(".type-card").length<705);
 document.getElementById("clearSearch").click();assert.equal(document.querySelectorAll(".type-card").length,705);document.getElementById("expandAll").click();assert([...document.querySelectorAll(".category")].every(d=>d.open));
 document.getElementById("articlesTab").click();await pause();assert.equal(document.getElementById("masterPanel").hidden,true);assert.equal(document.querySelectorAll(".article-card").length,1);assert.equal(document.querySelectorAll(".article-card script").length,0);assert(document.querySelector(".article-card h3").textContent.includes("<script>"));assert(document.getElementById("articleScope").textContent.includes("keine Berliner Filiale"));assert(!document.querySelector(".article-card").textContent.includes("€"));
 [...document.querySelectorAll("#merchantFilter button")].find(b=>b.textContent==="PENNY").click();await pause();assert.equal(document.querySelectorAll(".article-card").length,0);assert(document.getElementById("articleResult").textContent.includes("noch keine Artikel erfasst"));assert(!document.getElementById("articleResult").textContent.includes("führt"));
 document.getElementById("masterTab").click();assert.equal(document.querySelectorAll(".type-card").length,705);assert.equal(document.getElementById("typeCount").textContent,"705","Article searches must not inflate master counts");dom.window.close();
 // A previous merchant response must not appear under the newly typed search, even before debounce expires.
 const slowDom=new JSDOM(fs.readFileSync(path.join(__dirname,"../sortiment.html"),"utf8")),slowDocument=slowDom.window.document;let resolveOld;
 const slow=View.mount(slowDocument,async url=>{if(url==="data/grocery-assortment.json")return{ok:true,json:async()=>master};if(!new URL(url).searchParams.has("search"))return new Promise(resolve=>{resolveOld=resolve;});return{ok:true,json:async()=>({merchant:"ALDI",assortmentComplete:false,status:"no-observed-articles",items:[]})};});await slow.ready;slowDocument.getElementById("articlesTab").click();slowDocument.getElementById("assortmentSearch").value="Butter";slowDocument.getElementById("assortmentSearch").dispatchEvent(new slowDom.window.Event("input"));resolveOld({ok:true,json:async()=>({merchant:"ALDI",assortmentComplete:false,status:"observed-articles",items:[article]})});await new Promise(resolve=>setImmediate(resolve));assert.equal(slowDocument.querySelectorAll(".article-card").length,0);assert(slowDocument.getElementById("articleResult").textContent.includes("aktualisiert"));await pause();assert.equal(slowDocument.querySelectorAll(".article-card").length,0);slowDom.window.close();
 console.log("OK grocery assortment overview: taxonomy, identity separation, search, merchant scope, safe rendering and empty states");
}
main().catch(error=>{console.error(error);process.exitCode=1;});
