"use strict";
const assert=require("node:assert/strict"),fs=require("node:fs"),path=require("node:path"),{JSDOM}=require("jsdom");
const View=require("../app/assortment-overview"),master=require("../data/grocery-assortment.json"),copy=value=>structuredClone(value),pause=()=>new Promise(resolve=>setTimeout(resolve,230));
async function main(){
 assert.equal(View.validateMaster(master),master);assert.equal(master.statistics.categories,37);assert.equal(master.statistics.productTypes,705);assert.equal(master.statistics.exampleVariants,1654);
 const ids=new Set();for(const category of master.categories)for(const type of category.productTypes){assert(!ids.has(type.id));ids.add(type.id);assert(!Object.hasOwn(type,"gtin"));assert(!Object.hasOwn(type,"price"));assert(!Object.hasOwn(type,"merchant"));}
 for(const query of["Milch","Wurst","Käse","Gemüse","Waschmittel","Katzenfutter","Zigaretten"]){assert(View.filterMaster(master,query).length,"Missing broad type: "+query);}
 assert(View.filterMaster(master,"Kase").length);assert(View.filterMaster(master,"tiefgekuhlt").length);assert.equal(View.filterMaster(master,"unbekanntesxyz").length,0);
 const subset=View.filterMaster(master,"",master.categories[0].id);assert.equal(subset.length,1);assert(subset[0].productTypes.length<705);
 for(const patch of[{retailerStockVerified:true},{currentPricesIncluded:true},{complete:true},{canonicalProductIdentities:true},{statistics:{...master.statistics,productTypes:706}}])assert.throws(()=>View.validateMaster({...master,...patch}),/invalid-assortment/);
 const duplicate=copy(master);duplicate.categories[0].productTypes.push(copy(duplicate.categories[0].productTypes[0]));assert.throws(()=>View.validateMaster(duplicate),/invalid-assortment/);
 for(const url of["javascript:alert(1)","http://www.aldi-nord.de/produkt/test-123.html","https://evil.example/","https://user:pass@wolt.com/"])assert.equal(View.safeSource(url),null);
 const article={merchant:"ALDI",sourceMerchant:"ALDI Nord",sourceId:"ALDI Nord published assortment",retailerSku:"1234567",name:"<script>Injected milk</script>",brand:"Beispiel",variant:"3,5 % Fett",pack:"1 l",gtin:null,scopeCountry:"DE",scopeChannel:"assortment-publication",locationScope:"unknown",sourceUrl:"https://www.aldi-nord.de/produkt/milch-1234567.html",observedAt:"2026-09-30T12:00:00.000Z",state:"last-observed",availability:"unknown",currentPriceVerified:false,assortmentComplete:false};
 assert.equal(View.safeArticle(article),article);for(const patch of[{state:"current"},{availability:"in-stock"},{scopeCountry:"AT"},{merchant:"EDEKA"},{scopeChannel:"online"},{currentPriceVerified:true},{assortmentComplete:true},{sourceUrl:"javascript:alert(1)"}])assert.equal(View.safeArticle({...article,...patch}),null);
 // This is an explicitly synthetic public display DTO; no archived retailer
 // original is moved to today or treated as a Berlin/price/stock observation.
 const category={identityKey:JSON.stringify(["ALDI Nord category publication","assortment-publication","1042504"]),kind:"native-retailer-article",merchant:"ALDI",sourceMerchant:"ALDI Nord",sourceId:"ALDI Nord category publication",retailerSku:"1042504",name:"UNIT TEST category rice",brand:"UNIT TEST",variant:"Langkornreis",pack:"1.000-g-Packung",packAmount:1000,packUnit:"g",packCount:1,gtin:null,scopeCountry:"DE",scopeChannel:"assortment-publication",locationScope:"unknown",scopeLabel:"Datierte Artikel aus Deutschland; Berlinfiliale unbekannt.",shop:null,sourceUrl:"https://www.aldi-nord.de/sortiment/vorraete/reis-nudeln-getreide.html",originalCategoryResponseUrl:"https://www.aldi-nord.de/sortiment/vorraete/reis-nudeln-getreide.html",sourceResponseUrl:"https://www.aldi-nord.de/sortiment/vorraete/reis-nudeln-getreide.html",productIdentityUrl:"https://www.aldi-nord.de/produkt/langkornreis-1042504.html",proofKind:"original-category-html",sourceResponseHash:"ab".repeat(32),observedAt:"2026-09-30T12:00:00.000Z",state:"last-observed",availability:"unknown",truthEligible:false,currentPriceVerified:false,physicalStorePriceVerified:false,normalPriceClassificationVerified:false,assortmentComplete:false,pricedOnly:false,independentOfPrice:true};
 const categoryBefore=copy(category);assert.equal(View.safeArticle(category),category);assert.deepEqual(category,categoryBefore,"Display validation preserves original source/hash/capture and native pack");
 for(const patch of[
  {sourceId:"ALDI Nord published assortment"},{sourceId:"ALDI Nord published assortment",sourceUrl:category.productIdentityUrl},{scopeCountry:"AT"},{scopeChannel:"physical-store"},{locationScope:"Berlin"},{shop:{city:"Berlin"}},{gtin:"3017620422003"},{merchant:"EDEKA"},
  {sourceUrl:category.productIdentityUrl},{sourceResponseUrl:category.productIdentityUrl},{originalCategoryResponseUrl:category.productIdentityUrl},{proofKind:"original-product-html"},{sourceResponseHash:"AB".repeat(32)},{sourceResponseHash:""},
  {sourceUrl:category.sourceUrl+"?page=0"},{sourceResponseUrl:category.sourceUrl+"#products"},{sourceUrl:category.sourceUrl.replace("www.aldi-nord.de","www.aldi-sued.de")},{productIdentityUrl:category.productIdentityUrl.replace("1042504","1042505")},{productIdentityUrl:category.productIdentityUrl+"?x=1"},{productIdentityUrl:"https://u:p@www.aldi-nord.de/produkt/langkornreis-1042504.html"},
  {retailerSku:"01042504"},{identityKey:JSON.stringify(["ALDI Nord published assortment","assortment-publication","1042504"])},{observedAt:"2026-09-30T12:00:00Z"},{observedAt:new Date(Date.now()+60000).toISOString()},
  {packAmount:0},{packAmount:Infinity},{packUnit:"kg"},{packCount:1.5},{packCount:1001},{name:"<script>milk</script>"},{variant:"rice\u0000water"},
  {price:1.19},{current:true},{availability:"in-stock"},{currentPriceVerified:true},{currentAvailabilityVerified:true},{normalPriceClassificationVerified:true},{physicalStorePriceVerified:true},{truthEligible:true},{pricedOnly:true},{independentOfPrice:false},{expiresAt:new Date(Date.now()+86400000).toISOString()},
  {rawNativeProduct:{objectID:"1042504"}},{nativeProduct:{objectID:"1042504"}},{body:"private original"},{nativeWitness:{raw:"private"}}
 ])assert.equal(View.safeArticle({...category,...patch}),null,"Reject changed category display boundary: "+Object.keys(patch).join(","));
 for(const field of["sourceResponseHash","sourceResponseUrl","originalCategoryResponseUrl","productIdentityUrl","proofKind","gtin","shop"]){const missing=copy(category);delete missing[field];assert.equal(View.safeArticle(missing),null,"Category display proof is required: "+field);}
 const dom=new JSDOM(fs.readFileSync(path.join(__dirname,"../sortiment.html"),"utf8"),{url:"https://test.local/sortiment.html"}),document=dom.window.document,calls=[];
 const fetcher=async url=>{calls.push(url);if(url==="data/grocery-assortment.json")return{ok:true,json:async()=>master};const params=new URL(url).searchParams,merchant=params.get("merchant");return{ok:true,json:async()=>({merchant,assortmentComplete:false,status:merchant==="ALDI"?"observed-articles":"unsupported-source",items:merchant==="ALDI"?[article]:[]})};};
 const mounted=View.mount(document,fetcher);await mounted.ready;assert.equal(document.getElementById("typeCount").textContent,"705");assert.equal(document.querySelectorAll(".category").length,37);assert.equal(calls.length,1,"Master must load without merchant HTTP");
 document.getElementById("assortmentSearch").value="Wurst";document.getElementById("assortmentSearch").dispatchEvent(new dom.window.Event("input"));await pause();assert(document.querySelectorAll(".type-card").length>1);assert(document.querySelectorAll(".type-card").length<705);
 document.getElementById("clearSearch").click();assert.equal(document.querySelectorAll(".type-card").length,705);document.getElementById("expandAll").click();assert([...document.querySelectorAll(".category")].every(d=>d.open));
 document.getElementById("articlesTab").click();await pause();assert.equal(document.getElementById("masterPanel").hidden,true);assert.equal(document.querySelectorAll(".article-card").length,1);assert.equal(document.querySelectorAll(".article-card script").length,0);assert(document.querySelector(".article-card h3").textContent.includes("<script>"));assert(document.getElementById("articleScope").textContent.includes("keine Berliner Filiale"));assert(!document.querySelector(".article-card").textContent.includes("€"));
 [...document.querySelectorAll("#merchantFilter button")].find(b=>b.textContent==="PENNY").click();await pause();assert.equal(document.querySelectorAll(".article-card").length,0);assert(document.getElementById("articleResult").textContent.includes("noch keine Artikel erfasst"));assert(!document.getElementById("articleResult").textContent.includes("führt"));
 document.getElementById("masterTab").click();assert.equal(document.querySelectorAll(".type-card").length,705);assert.equal(document.getElementById("typeCount").textContent,"705","Article searches must not inflate master counts");dom.window.close();
 const categoryDom=new JSDOM(fs.readFileSync(path.join(__dirname,"../sortiment.html"),"utf8")),categoryDocument=categoryDom.window.document;
 const categoryMounted=View.mount(categoryDocument,async url=>url==="data/grocery-assortment.json"?{ok:true,json:async()=>master}:{ok:true,json:async()=>({merchant:"ALDI",assortmentComplete:false,status:"observed-articles",items:[category,{...category,price:.99},{...category,body:"private"}]})});
 await categoryMounted.ready;categoryDocument.getElementById("articlesTab").click();await pause();assert.equal(categoryDocument.querySelectorAll(".article-card").length,1,"Only a closed category original DTO can render");const categoryCard=categoryDocument.querySelector(".article-card"),links=[...categoryCard.querySelectorAll("a")];assert.deepEqual(links.map(link=>link.href),[category.sourceUrl,category.productIdentityUrl],"Actual category evidence and separate product identity link are not interchangeable");assert(links[0].textContent.includes("Originalquelle"));assert(links[1].textContent.includes("Produktlink"));assert(links.every(link=>link.rel==="noopener noreferrer"));assert(categoryCard.textContent.includes("Deutschland"));assert(categoryCard.textContent.includes("1.000-g-Packung"));assert(categoryCard.textContent.includes("30.09.26"));assert(!categoryCard.textContent.includes("€"));assert(!categoryCard.textContent.includes("Normalpreis"));assert(categoryDocument.getElementById("articleScope").textContent.includes("keine Berliner Filiale"));assert.equal(categoryDocument.getElementById("typeCount").textContent,"705");assert.deepEqual(category,categoryBefore);categoryDom.window.close();
 // A previous merchant response must not appear under the newly typed search, even before debounce expires.
 const slowDom=new JSDOM(fs.readFileSync(path.join(__dirname,"../sortiment.html"),"utf8")),slowDocument=slowDom.window.document;let resolveOld;
 const slow=View.mount(slowDocument,async url=>{if(url==="data/grocery-assortment.json")return{ok:true,json:async()=>master};if(!new URL(url).searchParams.has("search"))return new Promise(resolve=>{resolveOld=resolve;});return{ok:true,json:async()=>({merchant:"ALDI",assortmentComplete:false,status:"no-observed-articles",items:[]})};});await slow.ready;slowDocument.getElementById("articlesTab").click();slowDocument.getElementById("assortmentSearch").value="Butter";slowDocument.getElementById("assortmentSearch").dispatchEvent(new slowDom.window.Event("input"));resolveOld({ok:true,json:async()=>({merchant:"ALDI",assortmentComplete:false,status:"observed-articles",items:[article]})});await new Promise(resolve=>setImmediate(resolve));assert.equal(slowDocument.querySelectorAll(".article-card").length,0);assert(slowDocument.getElementById("articleResult").textContent.includes("aktualisiert"));await pause();assert.equal(slowDocument.querySelectorAll(".article-card").length,0);slowDom.window.close();
 // EDEKA identities can be browsed beyond the first page without price-only restrictions.
 const edekaDom=new JSDOM(fs.readFileSync(path.join(__dirname,"../sortiment.html"),"utf8")),edekaDocument=edekaDom.window.document,edekaCalls=[];
 const edekaArticle=index=>({...article,merchant:"EDEKA",sourceMerchant:"EDEKA",sourceId:"Wolt EDEKA Berlin",retailerSku:index.toString(16).padStart(24,"0"),name:"UNIT TEST dated delivery article "+index,scopeChannel:"online",sourceUrl:"https://wolt.com/de/deu/berlin/venue/edeka-hilbrecht",shop:{name:"EDEKA Hilbrecht",address:"Ritterstr. 38-40",city:"Berlin"}});
 const edekaMounted=View.mount(edekaDocument,async url=>{if(url==="data/grocery-assortment.json")return{ok:true,json:async()=>master};const params=new URL(url).searchParams,merchant=params.get("merchant"),offset=Number(params.get("offset"));edekaCalls.push({merchant,offset});return{ok:true,json:async()=>({merchant,assortmentComplete:false,offsetSupported:merchant==="EDEKA",scannedRows:offset===0?50:4,nextOffset:offset===0?50:54,hasMore:merchant==="EDEKA"&&offset===0,status:"observed-articles",note:merchant==="EDEKA"?"Datierte EDEKA Lieferartikel, auch ohne Preis.":"ALDI Artikel",items:merchant!=="EDEKA"?[]:offset===0?Array.from({length:49},(_,i)=>edekaArticle(i+1)):[edekaArticle(49),edekaArticle(50),edekaArticle(51),edekaArticle(52)]})};});await edekaMounted.ready;edekaDocument.getElementById("articlesTab").click();await pause();assert.equal(edekaDocument.getElementById("loadMore").hidden,true,"A merchant without offset support cannot expose an ineffective more button");
 [...edekaDocument.querySelectorAll("#merchantFilter button")].find(b=>b.textContent==="EDEKA").click();await pause();assert.equal(edekaDocument.querySelectorAll(".article-card").length,49);assert.equal(edekaDocument.getElementById("loadMore").hidden,false,"A filtered invalid row in a full SQL page must not hide later valid articles");assert.equal(edekaDocument.getElementById("articleScope").textContent,"Datierte EDEKA Lieferartikel, auch ohne Preis.");edekaDocument.getElementById("loadMore").click();await pause();assert.equal(edekaDocument.querySelectorAll(".article-card").length,52,"Append distinct native SKUs while deduplicating overlapping pages");assert.deepEqual(edekaCalls.filter(c=>c.merchant==="EDEKA").map(c=>c.offset),[0,50]);assert.equal(edekaDocument.getElementById("loadMore").hidden,true);assert(!edekaDocument.getElementById("articleList").textContent.includes("€"));edekaDom.window.close();
 console.log("OK grocery assortment overview: taxonomy, identity separation, native EDEKA pagination, search, merchant scope, safe rendering and empty states");
}
main().catch(error=>{console.error(error);process.exitCode=1;});
