"use strict";
const assert=require("node:assert/strict"),crypto=require("node:crypto"),Client=require("../hit-assortment-client");
const clock="2026-10-01T18:36:41.305Z",storeProfile={storeId:1775,storeNumber:"258",name:"Berlin-Mitte",city:"Berlin",country:"DE"};
const sku="000000000000548963ST",baseUrl="https://www.hit.de/sortiment/kaese-eier-molkerei/milch-h-kuh-4261891/rewe-bio-h-vollmilch-38-"+sku;
// Native main identity, pack and normal-price fields from the saved anonymous HIT milk HTML.
const row={external_id:sku,ean:"4388860095920",eans:["4311501318485"],storeId:1775,storeNumber:"258",headline:"REWE BIO H-Vollmilch 3,8%",brand:"REWE BIO",overview:"1l Packung",price:"1.25",deposit:null,url:baseUrl,published:true,inventoryAvailable:true,inventoryUpdatedAt:"2026-10-01T15:06:05+02:00",packageVariants:null,variantArticles:null,priceTag:{type:"discount",badgeText:"DAUER\nDISCOUNT\nPREIS",priceEuro:"1",priceCent:"25",priceStrikeThroughText:null,beforeText:null,belowText:null,appPriceEuro:null,appPriceCent:null,highlightUntil:"2026-10-01T23:59:59+00:00",basePriceText:" 1l=1.25",couponCode:null,couponName:null}};
const clone=structuredClone,hash=value=>crypto.createHash("sha256").update(value).digest("hex");
const attr=value=>JSON.stringify(value).replace(/&/g,"&amp;").replace(/"/g,"&quot;").replace(/</g,"&lt;").replace(/>/g,"&gt;");
const card=raw=>'<div data-leaflet="'+attr(raw)+'"></div>';
const list=(rows,pagination={page:0,limit:40,total:rows.length},params={for_store:1775})=>'<div data-component="assortment/list" data-data="'+attr({data:rows,pagination,status:200})+'" data-params="'+attr(params)+'"></div>';
const meta=(html,overrides={})=>({storeProfile,capturedAt:clock,responseDate:new Date(clock).toUTCString(),responseAgeSeconds:0,sourceResponseHash:hash(html),sourceResponseUrl:baseUrl+"?markt=258",...overrides});
const parse=(raw,overrides={})=>{const html=list([raw]);return Client.parsePage(html,meta(html,overrides))};
const rejected=(result,reason)=>{assert.equal(result.accepted.length,0,reason);assert(result.rejected.some(row=>row.reasons.includes(reason)),reason+": "+JSON.stringify(result.rejected))};
const actualNow=Date.now;Date.now=()=>Date.parse(clock);
try{
 const original=clone(row),good=parse(row);assert.equal(good.accepted.length,1);assert.deepEqual(row,original,"Parsing does not mutate original native input");
 const c=good.accepted[0];assert.equal(c.sourceId,"HIT Berlin store assortment");assert.equal(c.gtin,row.ean);assert.equal(c.name,"REWE BIO H-Vollmilch 3,8%");assert.equal(c.pack,"1l Packung");assert.equal(c.packAmount,1);assert.equal(c.packUnit,"l");assert.equal(c.packCount,1);assert.deepEqual(c.normalizedPack,{amount:1000,unit:"ml"});assert.equal(c.price,1.25);assert.equal(c.priceCents,125);assert.equal(c.deposit,null);assert.equal(c.depositIncluded,null);assert.equal(c.priceIncludesDeposit,null);assert.equal(c.nativeStoreId,1775);assert.equal(c.nativeStoreNumber,"258");assert.equal(c.storeId,null);assert.equal(c.truthEligible,false);assert.equal(c.physicalStorePriceVerified,false);assert.equal(c.scopeChannel,"store-assortment-publication");assert.equal(c.promotionStatus,"unknown");assert.equal(c.regularPrice,null);assert.equal(c.availability,"unknown");assert.equal(c.capturedAt,clock);assert.equal(c.expiresAt,"2026-10-02T18:36:41.305Z");assert.equal(c.sourceResponseDate,"2026-10-01T18:36:41.000Z");assert.equal(c.nativeProductUrl,baseUrl);assert.equal(c.sourceUrl,baseUrl+"?markt=258");assert.match(c.proofHash,/^[a-f0-9]{64}$/);assert.equal(c.aliases,undefined);assert.equal(c.eans,undefined);assert.equal(good.assortmentComplete,false);
 const reproved=Client.parseRow(c.nativeProof,meta(list([row])));assert.equal(reproved.ok,true);assert.equal(reproved.candidate.proofHash,c.proofHash);assert.deepEqual(reproved.candidate,c,"All relevant native fields survive proof reparse");
 const standard=clone(row);standard.priceTag.type="standard";standard.priceTag.badgeText=null;standard.priceTag.highlightUntil=null;assert.equal(parse(standard).accepted[0].normalPriceEvidence,"native-standard-price-tag");
 for(const [changes,reason]of[
  [{storeId:1776},"hit-native-store-identity-conflict"],[{storeId:"1775"},"hit-native-store-identity-conflict"],[{storeNumber:"259"},"hit-native-store-identity-conflict"],[{storeNumber:258},"hit-native-store-identity-conflict"],[{storeId:undefined,storeNumber:undefined},"hit-native-store-identity-conflict"],
  [{ean:"4388860095921"},"hit-valid-native-main-gtin-required"],[{ean:"invalid",eans:[row.ean]},"hit-valid-native-main-gtin-required"],[{ean:4388860095920},"hit-valid-native-main-gtin-required"],[{ean:"4388860095920 "},"hit-valid-native-main-gtin-required"],
  [{external_id:""},"hit-native-sku-required"],[{external_id:548963},"hit-native-sku-required"],[{price:"1.255"},"hit-current-pack-price-required"],[{price:1.255},"hit-current-pack-price-required"],[{price:"0.00"},"hit-current-pack-price-required"],[{price:"-1.25"},"hit-current-pack-price-required"],[{price:"1e1"},"hit-current-pack-price-required"],[{price:null,appPrice:"1.25",recommendedPrice:"1.25"},"hit-current-pack-price-required"],[{deposit:"0.255"},"hit-native-deposit-invalid"],
  [{headline:"Milch verschiedene Sorten"},"hit-product-variant-unresolved"],[{headline:"Milch 1,5%/3,5% Fett"},"hit-product-variant-unresolved"],[{packageVariants:[{overview:"2l Packung"}]},"hit-product-variant-unresolved"],[{variantArticles:[{ean:row.ean}]},"hit-product-variant-unresolved"],[{headline:"Milch\ufffd"},"hit-native-product-name-required"],[{headline:"<script>Milch</script>"},"hit-native-product-name-required"],[{published:false},"hit-native-product-not-published"],
  [{stringBeforePrice:"Nur mit App"},"hit-price-condition-unresolved"],[{stringBelowPrice:"ab 2 Stück"},"hit-price-condition-unresolved"],[{inApp:true},"hit-price-condition-unresolved"],[{stringBeforePriceIsStrikethrough:true},"hit-strikethrough-price-not-supported"]
 ])rejected(parse({...clone(row),...changes}),reason);
 for(const pack of["ca. 1l Packung","je 100g","1l/2l Packung","500g oder 750g Packung","500-750g Packung","500g + 250g gratis","1l Packung 250ml extra","1 Literatur",".5l Packung","-1l Packung","0x1l Packung","1,5x1l Packung","2,5 Stück","1l Flasche, verschiedene Sorten",""])rejected(parse({...row,overview:pack}),"hit-exact-native-sales-pack-required");
 for(const [pack,amount,unit,count,total]of[["6x0,33l Dosen",.33,"l",6,1980],["2 x 250g Packung",250,"g",2,500],["2×0,5 l Flaschen",.5,"l",2,1000],["0,125kg Becher",.125,"kg",1,125],["500ml Packung",500,"ml",1,500],["10 Stück Packung",10,"piece",1,10],["10St Packung",10,"piece",1,10],["2x6 Stück",6,"piece",2,12]]){const c=parse({...row,overview:pack}).accepted[0];assert(c,pack);assert.equal(c.packAmount,amount);assert.equal(c.packUnit,unit);assert.equal(c.packCount,count);assert.equal(c.normalizedPack.amount,total);assert.equal(c.pack,pack)}
 const named=parse({...row,headline:"B12 Milch 3,8% 99",overview:"500ml Packung"}).accepted[0];assert.equal(named.packAmount,500,"Numbers in a headline never become sales quantity");assert.equal(named.name,"B12 Milch 3,8% 99");
 for(const overrides of[{type:"promotion",badgeText:"AKTION!"},{type:"standard",badgeText:"AKTION!"},{type:"app"},{type:"discount",badgeText:"AKTION!"},{priceEuro:"1",priceCent:"29"},{priceEuro:"01"},{priceCent:"5"},{priceCent:"25.5"},{priceStrikeThroughText:"2.99"},{couponCode:"SAVE"},{beforeText:"UVP 2,99"},{beforeText:"Gültig bis 03.10.26"}]){const result=parse({...clone(row),priceTag:{...row.priceTag,...overrides}});assert.equal(result.accepted.length,0)}
 const alternatives=clone(row);alternatives.appPrice="0.95";alternatives.recommendedPrice="4.99";alternatives.priceTag.appPriceEuro="0";alternatives.priceTag.appPriceCent="95";assert.equal(parse(alternatives).accepted[0].price,1.25,"A separate app/UVP value cannot replace the unconditional native price");
 const euros=clone(standard);euros.price="2.00";euros.priceTag.priceEuro="2";euros.priceTag.priceCent="-";assert.equal(parse(euros).accepted[0].priceCents,200);
 for(const deposit of["0.25",0.25,0]){const c=parse({...row,deposit}).accepted[0];assert.equal(c.price,1.25);assert.equal(c.deposit,Number(deposit));assert.equal(c.depositIncluded,false);assert.equal(c.priceIncludesDeposit,false)}
 const inventory=clone(row);inventory.inventoryUpdatedAt="2099-01-01T00:00:00Z";inventory.priceTag.highlightUntil="2099-01-01T00:00:00Z";inventory.inventoryAvailable=false;const unchanged=parse(inventory).accepted[0];assert.equal(unchanged.capturedAt,clock);assert.equal(unchanged.expiresAt,c.expiresAt);assert.equal(unchanged.availability,"unknown");assert.equal(unchanged.nativeInventoryAvailable,false);
 for(const [overrides,reason]of[
  [{responseDate:null},"hit-source-response-date-stale-or-invalid"],[{responseDate:"0"},"hit-source-response-date-stale-or-invalid"],[{responseDate:"Thu, 01 Oct 2026 18:31:41 GMT"},"hit-source-response-date-stale-or-invalid"],[{responseDate:"Thu, 01 Oct 2026 18:41:42 GMT"},"hit-source-response-date-stale-or-invalid"],
  [{responseAgeSeconds:301},"hit-source-cache-age-stale-or-invalid"],[{responseAgeSeconds:-1},"hit-source-cache-age-stale-or-invalid"],[{responseAgeSeconds:"0"},"hit-source-cache-age-stale-or-invalid"],[{responseAgeSeconds:undefined},"hit-source-cache-age-stale-or-invalid"],
  [{capturedAt:"2099-01-01T00:00:00Z"},"hit-real-capture-time-required"],[{capturedAt:"2026-02-30T00:00:00Z"},"hit-real-capture-time-required"],[{sourceResponseHash:"a".repeat(64)},"hit-source-response-body-hash-conflict"],[{sourceResponseHash:"not a hash"},"hit-source-response-hash-required"],
  [{storeProfile:{...storeProfile,city:"Hamburg"}},"hit-explicit-berlin-store-profile-required"],[{storeProfile:{...storeProfile,country:"AT"}},"hit-explicit-berlin-store-profile-required"],[{storeProfile:undefined},"hit-explicit-berlin-store-profile-required"]
 ])rejected(parse(row,overrides),reason);
 const boundary=Date.parse(clock);assert.equal(parse(row,{responseDate:new Date(boundary-300000).toISOString(),responseAgeSeconds:300}).accepted.length,1);assert.equal(parse(row,{responseDate:new Date(boundary+300000).toISOString(),responseAgeSeconds:null}).accepted.length,1);
 for(const url of[baseUrl+"?markt=259",baseUrl+"?markt=258&markt=258",baseUrl+"?markt=258&foo=1",baseUrl+"#price",baseUrl.replace("https:","http:"),baseUrl.replace("www.hit.de","evil.example"),baseUrl.replace(sku,"000000000000000001ST"),baseUrl.replace("https://","https://user:password@"),baseUrl.replace("www.hit.de","www.hit.de:444")])assert.equal(parse({...row,url}).accepted.length,0,url);
 for(const url of[baseUrl+"?markt=259",baseUrl+"#price",baseUrl.replace("https:","http:"),"https://www.hit.de/konto"])rejected(parse(row,{sourceResponseUrl:url}),"hit-source-url-not-allowed");
 const category="https://www.hit.de/sortiment/kaese-eier-molkerei/milch-h-kuh-4261891";const page=list([row],{page:0,limit:40,total:1});const parsed=Client.parsePage(page,meta(page,{sourceResponseUrl:category}));assert.equal(parsed.accepted.length,1);assert.equal(parsed.accepted[0].sourceResponseUrl,category,"Actual response URL is never synthesized");assert.equal(parsed.assortmentComplete,false);assert.deepEqual(parsed.nativePagination,{page:0,limit:40,total:1});
 for(const pagination of[{page:0,limit:40,total:29},{page:1,limit:40,total:29},{page:0,limit:40,total:0}]){const short=list([row],pagination);rejected(Client.parsePage(short,meta(short)),"hit-native-list-schema-invalid")}
 const incomplete=list(Array.from({length:40},()=>clone(row)),{page:0,limit:40,total:2206});assert.equal(Client.parsePage(incomplete,meta(incomplete)).assortmentComplete,false);
 const header='<header data-store-id="1775" data-store-number="258">Berlin</header>';const wrong=header+list([{...row,storeId:1776}]);rejected(Client.parsePage(wrong,meta(wrong)),"hit-native-store-identity-conflict");
 const badParams=list([row],undefined,{for_store:1776});rejected(Client.parsePage(badParams,meta(badParams)),"hit-native-list-store-context-conflict");
 const exactDuplicate=list([row,clone(row)]);assert.equal(Client.parsePage(exactDuplicate,meta(exactDuplicate)).accepted.length,1);
 const conflicting={...clone(row),price:"1.35",priceTag:{...row.priceTag,priceCent:"35"}};const conflict=list([row,conflicting,row]);rejected(Client.parsePage(conflict,meta(conflict)),"hit-conflicting-native-sku-quotes");
 const secondSku="000000000000999999ST",second={...conflicting,external_id:secondSku,url:baseUrl.replace(sku,secondSku)};const gtinConflict=list([row,second]);rejected(Client.parsePage(gtinConflict,meta(gtinConflict)),"hit-conflicting-native-gtin-pack-quotes");
 const invalidConflict=list([row,{...second,price:"1.355"}]);rejected(Client.parsePage(invalidConflict,meta(invalidConflict)),"hit-conflicting-native-gtin-pack-quotes");
 const gtinOtherPack=list([row,{...row,external_id:secondSku,url:baseUrl.replace(sku,secondSku),overview:"2x500ml Packung"}]);assert.equal(Client.parsePage(gtinOtherPack,meta(gtinOtherPack)).accepted.length,2,"Different native pack counts do not collapse into an invented same-pack quote");
 const main=card(row)+card({...row,external_id:secondSku,url:baseUrl.replace(sku,secondSku)});const detail=Client.parsePage(main,meta(main));assert.equal(detail.accepted.length,1);assert.equal(detail.accepted[0].retailerSku,sku);assert(detail.rejected.some(r=>r.reasons.includes("hit-related-product-not-primary")));
 const mixed=card({...row,price:"4.99"})+list([row]);assert.equal(Client.parsePage(mixed,meta(mixed)).accepted[0].price,1.25,"Authoritative native list rows are separated from related leaflet cards");
 const empty=list([],{page:0,limit:40,total:0});const validEmpty=Client.parsePage(empty,meta(empty,{sourceResponseUrl:category}));assert.equal(validEmpty.emptyPage,true);assert.equal(validEmpty.rejected.length,0);assert.equal(validEmpty.assortmentComplete,false);
 const noRows="<header>Keine Artikel</header>";const missing=Client.parsePage(noRows,meta(noRows));assert.equal(missing.emptyPage,false);rejected(missing,"hit-page-native-offers-required");
 const unrelated='<script>const fake="'+card(row)+'";</script><!--'+card(row)+'-->';rejected(Client.parsePage(unrelated,meta(unrelated)),"hit-page-native-offers-required");
 const broken='<div data-leaflet="&quot;badJSON"></div>';rejected(Client.parsePage(broken,meta(broken)),"hit-native-row-json-invalid");
 const numeric=card(row).replace(/&quot;/g,"&#34;");assert.equal(Client.parsePage(numeric,meta(numeric)).accepted.length,1);
 const doubled=list([row])+list([row]);rejected(Client.parsePage(doubled,meta(doubled)),"hit-multiple-native-lists-unresolved");
 const unsupported='<div data-component="assortment/list" data-data="'+attr({data:[row],pagination:{page:0,limit:40,total:1},status:403})+'"></div>';rejected(Client.parsePage(unsupported,meta(unsupported)),"hit-native-list-schema-invalid");
 assert.throws(()=>Client.extractRows("a".repeat(6*1024*1024+1)),/hit-page-body-invalid-or-too-large/);
 // Native filters/URLs/counts from saved public category HTML, offline only.
 const nativeCategories=[
  {id:4261253,name:"Käse, Eier & Molkerei",url:"/sortiment/kaese-eier-molkerei-4261253",order:173,level:1,count:2206},
  {id:4261298,name:"Milch",url:"/sortiment/kaese-eier-molkerei/milch-4261298",order:229,level:2,count:68},
  {id:4261892,name:"Frischmilch Kuh",url:"/sortiment/kaese-eier-molkerei/milch-frischmilch-kuh-4261892",order:230,level:3,count:31},
  {id:4261891,name:"H- Kuh",url:"/sortiment/kaese-eier-molkerei/milch-h-kuh-4261891",order:231,level:3,count:29},
  {id:4261890,name:"Milchspezialitäten",url:"/sortiment/kaese-eier-molkerei/milch-milchspezialitaeten-4261890",order:232,level:3,count:5},
  {id:4261889,name:"Schafsmilch",url:"/sortiment/kaese-eier-molkerei/milch-schafsmilch-4261889",order:233,level:3,count:1},
  {id:4261888,name:"Ziegenmilch",url:"/sortiment/kaese-eier-molkerei/milch-ziegenmilch-4261888",order:234,level:3,count:2}
 ];
 const leafCategoryUrl="https://www.hit.de"+nativeCategories[3].url;
 const categoryList=(categories=nativeCategories,{pagination={page:0,limit:40,total:29},params={for_store:1775,for_category:"4261891"},meta={category:{id:"4261891"}},filters={categories}}={})=>'<div data-component="assortment/list" data-data="'+attr({data:Array.from({length:Math.min(pagination.limit,pagination.total-pagination.page*pagination.limit)},()=>row),pagination,meta,filters,status:200})+'" data-params="'+attr(params)+'"></div>';
 const categoryHtml=categoryList(),categorySnapshot=clone(nativeCategories),categories=Client.extractCategories(categoryHtml,leafCategoryUrl);assert.equal(categories.categories.length,7);assert.equal(categories.rejected.length,0);assert.deepEqual(nativeCategories,categorySnapshot);assert.equal(categories.currentCategoryId,"4261891");assert.equal(categories.nativeStoreId,1775);assert.deepEqual(categories.nativePagination,{page:0,limit:40,total:29});assert.equal(categories.categoryTreeComplete,false);assert.equal(categories.assortmentComplete,false);
 const milkParent=categories.categories.find(c=>c.id==="4261298"),hMilk=categories.categories.find(c=>c.id==="4261891");assert.equal(hMilk.url,leafCategoryUrl);assert.equal(hMilk.level,3);assert.equal(hMilk.count,29);assert.equal(hMilk.parentId,"4261298");assert.equal(hMilk.evidence,"native-assortment-filters");assert.deepEqual(milkParent.observedChildIds,["4261892","4261891","4261890","4261889","4261888"],"Native levels/order bind the subtree; flattened URL segments do not invent a parent");
 const observedPage1=categoryList(nativeCategories,{pagination:{page:0,limit:40,total:2206},params:{for_store:1775,for_category:"4261253"},meta:{category:{id:"4261253"}}}),page1Result=Client.extractCategories(observedPage1,"https://www.hit.de/sortiment/kaese-eier-molkerei-4261253?page=1");assert.equal(page1Result.nativePagination.page,0,"The native returned page wins over a silently ignored public query parameter");assert.equal(page1Result.nativePagination.total,2206);assert.equal(page1Result.assortmentComplete,false);
 const nav='<a href="/sortiment/obst-gemuese-4261243" class="group ga_filter_assortment_category"><img alt="Obst &amp; Gemüse"/>/sortiment/obst-gemuese-4261243<span class="hit-font-h5">Obst &amp; Gemüse</span></a>',navResult=Client.extractCategories(nav,"https://www.hit.de/sortiment");assert.equal(navResult.categories.length,1);assert.equal(navResult.categories[0].name,"Obst & Gemüse");assert.equal(navResult.categories[0].id,"4261243");assert.equal(navResult.categories[0].url,"https://www.hit.de/sortiment/obst-gemuese-4261243");assert.equal(navResult.categories[0].count,null);assert.equal(navResult.categories[0].level,1);assert.equal(navResult.categories[0].evidence,"native-navigation-link");assert.equal(navResult.nativePagination,null);assert.equal(navResult.assortmentComplete,false);
 assert.equal(Client.extractCategories(nav+nav,"https://www.hit.de/sortiment").categories.length,1,"Repeated desktop/mobile navigation does not duplicate a queue target");
 assert.equal(Client.extractCategories(categoryHtml+nav+nav,leafCategoryUrl).categories.length,8);assert.equal(Client.extractCategories('<a href="/sortiment/obst-gemuese-4261243">unclassified link</a>',"https://www.hit.de/sortiment").categories.length,0,"Unclassified page links are not invented as category metadata");
 assert.equal(Client.extractCategories("<script>"+nav+"</script><!--"+nav+"-->","https://www.hit.de/sortiment").categories.length,0);
 assert.equal(Client.extractCategories("<main>Nothing offered</main>","https://www.hit.de/sortiment").categories.length,0);
 for(const url of[baseUrl,"https://evil.example/sortiment/milch-4261891","https://evil.hit.de/sortiment/milch-4261891","http://www.hit.de/sortiment/milch-4261891","https://user:password@www.hit.de/sortiment/milch-4261891","https://www.hit.de:444/sortiment/milch-4261891",leafCategoryUrl+"#fragment",leafCategoryUrl+"?sort=price_asc",leafCategoryUrl+"?markt=258&markt=259",leafCategoryUrl+"?page=oops"]){assert.throws(()=>Client.extractCategories(categoryHtml,url),/hit-category-source-url-not-allowed/,url)}
 for(const url of[row.url,"https://evil.example/sortiment/milch-h-kuh-4261891","//evil.example/sortiment/milch-h-kuh-4261891","http://www.hit.de/sortiment/milch-h-kuh-4261891","https://user:pw@www.hit.de/sortiment/milch-h-kuh-4261891","https://www.hit.de:444/sortiment/milch-h-kuh-4261891",nativeCategories[3].url+"#x",nativeCategories[3].url+"?page=1",nativeCategories[3].url+"?markt=259",nativeCategories[3].url+"?markt=258&markt=258","/sortiment/../sortiment/milch-h-kuh-4261891","/sortiment/kaese-eier-molkerei%2Fmilch-h-kuh-4261891"]){const bad=Client.extractCategories(categoryList([{...nativeCategories[3],url}]),leafCategoryUrl);assert.equal(bad.categories.length,0,url);assert(bad.rejected.length,url)}
 for(const change of[{id:"4261892"},{id:0},{id:"04261891"},{count:-1},{count:1.5},{count:"29"},{level:0},{level:4},{level:"3"},{name:"<script>Milk</script>"},{order:-1}]){const bad=Client.extractCategories(categoryList([{...nativeCategories[3],...change}]),leafCategoryUrl);assert.equal(bad.categories.length,0,JSON.stringify(change));assert(bad.rejected.length)}
 const missingCount=Client.extractCategories(categoryList([{...nativeCategories[3],count:undefined}]),leafCategoryUrl);assert.equal(missingCount.categories[0].count,null,"No native count remains unknown");
 const badParent=Client.extractCategories(categoryList([nativeCategories[0],nativeCategories[1],{...nativeCategories[1],id:4261999,url:"https://evil.example/sortiment/unknown-4261999"},nativeCategories[3]]),leafCategoryUrl);assert.equal(badParent.categories.find(c=>c.id==="4261891").parentId,null,"A rejected intermediate category cannot leave an unrelated prior parent on the stack");
 const duplicateCategories=Client.extractCategories(categoryList([nativeCategories[0],nativeCategories[0],nativeCategories[1]]),leafCategoryUrl);assert.equal(duplicateCategories.categories.length,2);
 const conflictingCategories=Client.extractCategories(categoryList([nativeCategories[3],{...nativeCategories[3],count:30}]),leafCategoryUrl);assert.equal(conflictingCategories.categories.length,0);assert(conflictingCategories.rejected.every(row=>row.reasons.includes("hit-conflicting-native-category-metadata")));
 const wrongId=categoryList(nativeCategories,{params:{for_store:1775,for_category:"4261892"}});assert.throws(()=>Client.extractCategories(wrongId,leafCategoryUrl),/hit-native-category-context-conflict/);assert.throws(()=>Client.extractCategories(categoryHtml,"https://www.hit.de"+nativeCategories[2].url),/hit-native-category-context-conflict/);assert.throws(()=>Client.extractCategories(categoryHtml,leafCategoryUrl+"?markt=259"),/hit-native-category-store-context-conflict/);
 assert.throws(()=>Client.extractCategories(categoryList(nativeCategories,{params:{for_store:"1775",for_category:"4261891"}}),leafCategoryUrl),/hit-native-category-store-context-conflict/);assert.throws(()=>Client.extractCategories(categoryList(nativeCategories,{filters:{categories:{}}}),leafCategoryUrl),/hit-native-category-filters-schema-invalid/);assert.throws(()=>Client.extractCategories(categoryHtml+categoryHtml,leafCategoryUrl),/hit-multiple-native-lists-unresolved/);assert.throws(()=>Client.extractCategories("a".repeat(6*1024*1024+1),leafCategoryUrl),/hit-page-body-invalid-or-too-large/);
 console.log("hit-assortment-client: OK");
}finally{Date.now=actualNow}
