"use strict";
const assert=require("node:assert/strict"),crypto=require("node:crypto"),Client=require("../hit-assortment-client"),Import=require("../hit-price-import");
const clock="2026-10-01T18:46:43.203Z",at=Date.parse(clock),sku="000000000000869561ST",storeProfile=Import.STORE_PROFILE;
// Main GTIN, normal-price tag and pack from the saved public Berlin-Mitte milk card.
const raw={external_id:sku,ean:"4388844177314",storeId:1775,storeNumber:"258",headline:"ja! H-Milch 1,5%",overview:"1l Packung",price:"0.85",deposit:null,url:"https://www.hit.de/sortiment/kaese-eier-molkerei/milch-h-kuh-4261891/ja-h-milch-15-"+sku,inventoryAvailable:true,inventoryUpdatedAt:"2026-10-01T19:24:29+02:00",priceTag:{type:"discount",badgeText:"DAUER\nDISCOUNT\nPREIS",priceEuro:"0",priceCent:"85",priceStrikeThroughText:null,beforeText:null,belowText:null,couponCode:null,couponName:null}};
const hash=value=>crypto.createHash("sha256").update(value).digest("hex"),clone=structuredClone;
function candidate(changes={},capture=clock){const result=Client.parseRow({...clone(raw),...changes},{storeProfile,capturedAt:capture,responseDate:new Date(capture).toUTCString(),responseAgeSeconds:0,sourceResponseHash:hash("TEST response "+capture+JSON.stringify(changes)),sourceResponseUrl:"https://www.hit.de/sortiment/kaese-eier-molkerei/milch-h-kuh-4261891?markt=258"});assert(result.ok,JSON.stringify(result.reasons));return result.candidate}
function checked(c,opts={}){return Import.validateCandidate(c,{storeProfile,now:at,...opts})}
function reject(c,reason,opts={}){const result=checked(c,opts);assert.equal(result.ok,false,reason);assert(result.reasons.includes(reason),reason+": "+JSON.stringify(result));}
function fakePool({conflictPack=false,storeConflict=false,failRow=false,failCommit=false}={}){
 const queries=[],records=new Map(),merchant="10000000-0000-4000-8000-000000000001",store="20000000-0000-4000-8000-000000000001",product="30000000-0000-4000-8000-000000000001";let released=false;
 async function query(sql,args=[]){queries.push({sql,args});
  if(sql==="COMMIT"&&failCommit&&records.size)throw Error("test transaction failure");
  if(sql.startsWith("SELECT id,name,active FROM merchants"))return{rows:[{id:merchant,name:"HIT",active:true}]};
  if(sql.startsWith("SELECT * FROM stores"))return{rows:[{id:store,merchant_id:merchant,active:true,address:storeProfile.address,postal_code:storeProfile.postalCode,city:storeConflict?"Hamburg":"Berlin",region:"Berlin",country:"DE",latitude:storeProfile.latitude,longitude:storeProfile.longitude}]};
  if(sql.startsWith("SELECT store_id,status"))return{rows:[{store_id:store,status:"verified",confidence:"1"}]};
  if(sql.startsWith("SELECT signature,observation_id"))return{rows:records.has(args[2]+args[3])?[records.get(args[2]+args[3])]:[]};
  if(sql.startsWith("SELECT id,gtin,pack_amount"))return{rows:[{id:product,gtin:raw.ean,packAmount:conflictPack?500:1000,packUnit:"ml",packCount:1}]};
  if(sql.startsWith("SELECT product_id,status"))return{rows:[{product_id:product,status:"verified",confidence:"1"}]};
  if(sql.startsWith("INSERT INTO price_observations")&&failRow)throw Object.assign(Error("test check"),{code:"23514"});
  if(sql.startsWith("INSERT INTO "+Import.TABLE))records.set(args[3]+args[4],{signature:args[22],observation_id:args[6]});
  return{rows:[],rowCount:1};
 }
 return{query,connect:async()=>({query,release(){released=true}}),queries,records,get released(){return released}};
}
function assertQuarantineScope(call){
 assert.deepEqual(call.args,[Import.SOURCE,1775,"258","1775"]);assert.match(call.sql,/^UPDATE price_observations po SET truth_eligible=false,status='unsupported-weight-sale-unit' FROM hit_price_import_evidence evidence WHERE /);
 for(const predicate of["po.id=evidence.observation_id","evidence.source_id=$1","evidence.native_store_id=$2","evidence.native_store_number=$3","evidence.retailer_sku~'^[0-9]+KG$'","po.source=$1","po.source_id=$1","po.store_id=evidence.store_id","po.product_id=evidence.product_id","po.gtin=evidence.gtin","po.external_location_id=$4","po.external_product_id=('hit:store:'||$4||':sku:'||evidence.retailer_sku)","po.truth_eligible=true"])assert(call.sql.includes(predicate),"Legacy quarantine must retain the exact identity/source boundary: "+predicate);
 assert.equal(call.sql.split(";").filter(text=>text.trim()).length,1,"Quarantine performs one observation update");assert(!/\b(?:INSERT|DELETE|TRUNCATE)\b/i.test(call.sql));assert(!/\bUPDATE\s+(?:products|stores|external_product_mappings|external_store_mappings|hit_price_import_evidence)\b/i.test(call.sql),"Evidence history and canonical identities are retained");
}
async function quarantineCases(){
 for(const rowCount of[3,0,undefined,null,-1,1.5,"2"]){const calls=[],pool={query:async(sql,args)=>{calls.push({sql,args});return{rowCount}}},count=await Import.quarantineUnsupportedWeight(pool);assert.equal(count,rowCount===3?3:0);assert.equal(calls.length,1);assertQuarantineScope(calls[0]);}
 for(const rowCount of[3,0,undefined,null,-1,1.5,"2"]){const calls=[],pool={query:async(sql,args)=>{calls.push({sql,args});return{rowCount}}},count=await Import.repairValidityWindow(pool);assert.equal(count,rowCount===3?3:0);assert.equal(calls.length,1);assertRepairScope(calls[0]);}
 const events=[],queries=[];let failAt="quarantine",releases=0;
 const pool={query:async()=>{throw Error("Schema repair must execute on its acquired transaction")},connect:async()=>({release(){releases++},query:async(sql,args=[])=>{queries.push({sql,args});if(sql==="BEGIN"||sql==="COMMIT"||sql==="ROLLBACK")events.push(sql);else if(sql.includes("CREATE TABLE IF NOT EXISTS "+Import.TABLE))events.push("schema");else if(sql.startsWith("UPDATE price_observations po")){const step=sql.startsWith("UPDATE price_observations po SET valid_from=")?"repair":"quarantine";events.push(step);(step==="repair"?assertRepairScope:assertQuarantineScope)({sql,args});if(failAt===step)throw Object.assign(Error(step+" write outage"),{code:"XX000"});return{rowCount:2}}else throw Error("Unexpected schema/quarantine mutation: "+sql);return{rows:[],rowCount:0}}})};
 await assert.rejects(Import.ensure(pool),error=>error.code==="XX000");assert.deepEqual(events,["BEGIN","schema","quarantine","ROLLBACK"],"Failed quarantine cannot commit schema/admission preparation");assert.equal(releases,1);assert(!queries.some(q=>/\b(?:INSERT INTO|UPDATE)\s+(?:products|stores|external_product_mappings|external_store_mappings)\b/i.test(q.sql)));
 failAt="repair";events.length=0;await assert.rejects(Import.ensure(pool),error=>error.code==="XX000");assert.deepEqual(events,["BEGIN","schema","quarantine","repair","ROLLBACK"]);assert.equal(releases,2,"Validity repair failure rolls back the entire schema migration");
 failAt=null;events.length=0;await Import.ensure(pool);assert.deepEqual(events,["BEGIN","schema","quarantine","repair","COMMIT"],"Quarantine and original-window repair commit together after schema creation");assert.equal(releases,3,"Failed migration jobs can be retried without a rejected cached promise");
}
function assertRepairScope(call){
 assert.deepEqual(call.args,[Import.SOURCE,1775,"258","1775"]);
 assert.match(call.sql,/^UPDATE price_observations po SET valid_from=\(evidence\.captured_at AT TIME ZONE 'Europe\/Berlin'\)::date,valid_to=\(\(evidence\.expires_at-interval '1 millisecond'\) AT TIME ZONE 'Europe\/Berlin'\)::date FROM hit_price_import_evidence evidence WHERE /);
 for(const predicate of["po.id=evidence.observation_id","evidence.source_id=$1","evidence.native_store_id=$2","evidence.native_store_number=$3","evidence.retailer_sku~'^[0-9]+ST$'","po.source=$1","po.source_id=$1","po.store_id=evidence.store_id","po.product_id=evidence.product_id","po.gtin=evidence.gtin","po.external_location_id=$4","po.external_product_id=('hit:store:'||$4||':sku:'||evidence.retailer_sku)","po.truth_eligible=true","po.observed_at=evidence.captured_at","po.fetched_at=evidence.captured_at","po.proof_hash=evidence.proof_hash","isfinite(evidence.captured_at)","isfinite(evidence.expires_at)","evidence.expires_at=evidence.captured_at+interval '24 hours'","(po.eligibility->>'sourceExpiresAt')=to_char(evidence.expires_at AT TIME ZONE 'UTC'","po.valid_from IS DISTINCT FROM","po.valid_to IS DISTINCT FROM"])assert(call.sql.includes(predicate),"Original-window migration boundary: "+predicate);
 const set=call.sql.split(" SET ")[1].split(" FROM ")[0];assert(!/truth_eligible|status|observed_at|fetched_at|price|proof|date=|expires_at=/.test(set),"Repair changes only validity dates; quarantined history and native timestamps are retained");assert.equal(call.sql.split(";").filter(text=>text.trim()).length,1);assert(!/\b(?:INSERT|DELETE|TRUNCATE)\b/i.test(call.sql));
}
async function main(){
 const previous=Date.now;Date.now=()=>at;
 try{
  await quarantineCases();
  const good=candidate(),original=clone(good),result=checked(good);assert.equal(result.ok,true);assert.deepEqual(result.pack,{amount:1000,unit:"ml",count:1});assert.equal(result.strictPack,"1000 ml");assert.equal(result.date,"2026-10-01");assert.equal(result.externalLocationId,"1775");assert.equal(result.externalProductId,"hit:store:1775:sku:"+sku);assert.equal(result.candidate.brand,null,"No brand is invented from ja! in the native name");assert.match(result.observationId,/^[a-f0-9]{8}-[a-f0-9]{4}-5[a-f0-9]{3}-a[a-f0-9]{3}-[a-f0-9]{12}$/);assert.deepEqual(good,original);
  for(const change of[{sourceId:"HIT published store assortment"},{merchant:"REWE"},{nativeStoreId:1776},{nativeStoreNumber:"259"},{storeId:"canonical-guess"},{truthEligible:true},{physicalStorePriceVerified:true},{locationScope:"country"},{country:"AT"}])reject({...clone(good),...change},"hit-import-native-source-scope-conflict");
  for(const field of["gtin","price","priceCents","packAmount","packCount","packUnit","brand","name","normalPriceEvidence","depositCents","proofHash","sourceUrl"]){const c=clone(good);c[field]=typeof c[field]==="number"?c[field]+1:"tampered";reject(c,"hit-import-reparsed-candidate-conflict");}
  reject({...clone(good),gtin:good.gtin+" "},"hit-import-native-gtin-required");reject({...clone(good),normalizedPack:{amount:6000,unit:"ml"}},"hit-import-reparsed-candidate-conflict");
  reject(good,"hit-import-capture-stale-or-future",{now:at+300001});assert.equal(checked(good,{now:at+300000}).ok,true);
  reject(good,"hit-import-capture-stale-or-future",{now:at-1});reject({...clone(good),expiresAt:new Date(at+86400001).toISOString()},"hit-import-native-expiry-invalid");reject({...clone(good),sourceResponseDate:new Date(at+1000).toISOString()},"hit-import-response-date-stale-or-future");
  for(const storeProfile of[{...Import.STORE_PROFILE,storeId:1776},{...Import.STORE_PROFILE,storeNumber:"259"},{...Import.STORE_PROFILE,city:"Hamburg"},{...Import.STORE_PROFILE,country:"AT"}])reject(good,"hit-import-approved-store-profile-required",{storeProfile});
  assert.equal(Import.STORE_PROFILE.officialUrl,Import.STORE_PROFILE.sourceUrl);for(const field of["address","postalCode","region","latitude","longitude","sourceUrl","officialUrl"])reject(good,"hit-import-store-profile-conflict",{storeProfile:{...Import.STORE_PROFILE,[field]:"wrong"}});
  const malformed=clone(good);malformed.nativeProof.priceTag.couponCode="APP";assert.equal(checked(malformed).ok,false,"Independent native-proof reparse catches hidden conditions");
  const fixedKg=candidate({headline:"TEST feste 1kg Verkaufspackung",overview:"1kg Packung"});assert.equal(checked(fixedKg).ok,true,"A fixed 1kg ST sales pack remains supported");assert.deepEqual(checked(fixedKg).pack,{amount:1000,unit:"g",count:1});
  const variableSku=sku.replace(/ST$/,"KG"),variableKg=clone(fixedKg);variableKg.retailerSku=variableSku;variableKg.nativeSku=variableSku;variableKg.nativeProductUrl=variableKg.nativeProductUrl.replace(sku,variableSku);variableKg.sourceUrl=variableKg.sourceUrl.replace(sku,variableSku);variableKg.nativeProof.external_id=variableSku;variableKg.nativeProof.url=variableKg.nativeProof.url.replace(sku,variableSku);variableKg.proofHash=hash(JSON.stringify({sourceResponseHash:variableKg.sourceResponseHash,sourceResponseUrl:variableKg.sourceResponseUrl,nativeProof:variableKg.nativeProof}));
  reject(variableKg,"hit-variable-weight-sale-unit-not-supported");const variablePool=fakePool(),variableBlocked=await Import.persist(variablePool,[variableKg],{storeProfile,now:at});assert.equal(variableBlocked.accepted.length,0);assert.equal(variableBlocked.rejected.length,1);assert(variableBlocked.rejected[0].reasons.includes("hit-variable-weight-sale-unit-not-supported"));assert.equal(variablePool.queries.length,0,"A native KG sales SKU cannot create a canonical identity or price even with a valid main GTIN, literal 1kg and a matching native URL/proof hash");
  for(const overview of["6x1l Flaschen","2x250g Packung","10 Stück Packung"]){const c=candidate({overview});assert(checked(c).ok);assert.equal(checked(c).pack.count,c.packCount);}
  const deposit=candidate({deposit:"0.25"});assert.equal(checked(deposit).candidate.price,.85);assert.equal(deposit.depositCents,25);assert.equal(deposit.priceIncludesDeposit,false);
  for(const [capture,from,to]of[["2026-10-01T21:59:59.999Z","2026-10-01","2026-10-02"],["2026-10-01T22:00:00.000Z","2026-10-02","2026-10-02"],["2026-10-24T22:30:00.000Z","2026-10-25","2026-10-25"],["2026-03-28T23:30:00.000Z","2026-03-29","2026-03-30"]]){Date.now=()=>Date.parse(capture);const native=candidate({},capture),window=checked(native,{now:Date.now()});assert.equal(window.ok,true);assert.equal(window.date,from);assert.equal(window.validFrom,from);assert.equal(window.validTo,to);assert.equal(Date.parse(native.expiresAt)-Date.parse(native.capturedAt),86400000,"Calendar and DST boundaries never change the original 24-hour TTL");const stalePool=fakePool(),late=await Import.persist(stalePool,[native],{storeProfile,now:Date.now()+86400000});assert.equal(late.accepted.length,0);assert(late.rejected[0].reasons.includes("hit-import-native-expiry-invalid"));assert.equal(stalePool.queries.length,0,"Expiry cannot create a fresh observation from an old proof");}Date.now=()=>at;
  const pool=fakePool(),first=await Import.persist(pool,[good],{storeProfile,now:at});assert.equal(first.accepted.length,1);assert.equal(first.rejected.length,0);assert.equal(first.conservativeValidity,"original-capture-24-hours");assert.equal(first.captureValidity,"original-capture-24-hours");assert(pool.released);
  const obs=pool.queries.find(q=>q.sql.startsWith("INSERT INTO price_observations"));const columns=obs.sql.match(/\(([^)]+)\)/)[1].split(","),stored=Object.fromEntries(columns.map((key,index)=>[key,obs.args[index]]));assert.equal(stored.price,.85);assert.equal(stored.pack,"1000 ml");assert.equal(stored.per,"piece");assert.equal(stored.source_type,"official_retailer");assert.equal(stored.truth_eligible,true);assert.equal(stored.identity_verified,true);assert.equal(stored.proof_verified,false);assert.equal(stored.status,"observed");assert.equal(stored.observed_at,clock);assert.equal(stored.fetched_at,clock);assert.equal(stored.date,stored.valid_from);assert.equal(stored.valid_to,"2026-10-02");assert.equal(stored.price_type,"regular");assert.equal(stored.proof_actor,undefined);assert.equal(stored.min_quantity,undefined);assert.equal(stored.regular_price,undefined);assert.equal(stored.pack_count,undefined);
  const duplicate=await Import.persist(pool,[good],{storeProfile,now:at});assert.equal(duplicate.duplicates,1);assert.equal(duplicate.accepted.length,0);assert.equal(pool.queries.filter(q=>q.sql.startsWith("INSERT INTO price_observations")).length,1);
  const metadata=JSON.parse(stored.eligibility);assert.deepEqual(metadata,{scopeChannel:"physical-store",sourceScope:"physical-store",nativeStoreId:1775,nativeStoreNumber:"258",goodsPriceCents:85,depositCents:null,priceIncludesDeposit:false,checkoutPriceVerified:false,sourceExpiresAt:good.expiresAt});
  assert.equal(stored.region,"Berlin","Browser scope matches the canonical Berlin profile exactly");assert.equal(stored.evidence_purpose,"current-price");
  const depositPool=fakePool();await Import.persist(depositPool,[deposit],{storeProfile,now:at});const depositInsert=depositPool.queries.find(q=>q.sql.startsWith("INSERT INTO price_observations"));const depositMetadata=JSON.parse(depositInsert.args.at(-1));assert.equal(depositMetadata.depositCents,25);assert.equal(depositMetadata.goodsPriceCents,85);assert.equal(depositMetadata.checkoutPriceVerified,true);assert.equal(depositMetadata.sourceExpiresAt,deposit.expiresAt);assert.equal(Date.parse(depositMetadata.sourceExpiresAt)-Date.parse(deposit.capturedAt),86400000);assert.equal(depositInsert.args[3],.85);
  const conflicting=candidate({price:"0.95",priceTag:{...raw.priceTag,priceCent:"95"}});const conflict=await Import.persist(pool,[conflicting],{storeProfile,now:at});assert(conflict.rejected[0].reasons.includes("hit-import-same-capture-conflict"));assert.equal(pool.records.size,1);
  const contradictory=fakePool(),both=await Import.persist(contradictory,[good,conflicting],{storeProfile,now:at});assert.equal(both.accepted.length,0);assert.equal(both.rejected.length,2);assert(both.rejected.every(r=>r.reasons[0]==="hit-import-conflicting-batch-capture"));assert.equal(contradictory.queries.length,0,"Neither side of an internally conflicting native capture can establish a price");
  const otherSku="000000000000999999ST",other=candidate({external_id:otherSku,headline:"POSTGRES TEST HIT different SKU same identity",url:raw.url.replace(sku,otherSku),price:"0.95",priceTag:{...raw.priceTag,priceCent:"95"}}),identityPool=fakePool(),identityConflict=await Import.persist(identityPool,[good,other],{storeProfile,now:at});assert.equal(identityConflict.rejected.length,2);assert(identityConflict.rejected.every(r=>r.reasons[0]==="hit-import-conflicting-batch-product-quote"));assert.equal(identityPool.queries.length,0);
  const updates=pool.queries.filter(q=>q.sql.startsWith("UPDATE price_observations"));assert(updates.some(q=>q.sql.includes("old.captured_at<$4")&&q.sql.includes("old.retailer_sku=$3")&&q.sql.includes("po.store_id=$5")&&q.args[0]===Import.SOURCE));assert(updates.some(q=>q.sql.includes("newer.captured_at>$5")),"Out-of-order capture admission checks the retained source history");
  const wrongPack=fakePool({conflictPack:true}),blocked=await Import.persist(wrongPack,[good],{storeProfile,now:at});assert.equal(blocked.accepted.length,0);assert.equal(blocked.rejected[0].reasons[0],"hit-import-canonical-product-pack-conflict");assert(wrongPack.queries.some(q=>q.sql==="ROLLBACK TO SAVEPOINT hit_import_row"));assert(!wrongPack.queries.some(q=>q.sql.startsWith("INSERT INTO price_observations")));
  const wrongStore=fakePool({storeConflict:true}),market=await Import.persist(wrongStore,[good],{storeProfile,now:at});assert.equal(market.rejected[0].reasons[0],"hit-import-canonical-store-conflict");assert(wrongStore.queries.some(q=>q.sql==="ROLLBACK"));assert(!wrongStore.queries.some(q=>q.sql.startsWith("INSERT INTO price_observations")));
  const failure=fakePool({failRow:true});await assert.rejects(Import.persist(failure,[good],{storeProfile,now:at}),error=>error.code==="23514");assert(failure.queries.some(q=>q.sql==="ROLLBACK TO SAVEPOINT hit_import_row"));assert.equal(failure.queries.at(-1).sql,"ROLLBACK","An unexpected database error aborts all price writes, so the collector cannot advance its checkpoint");assert.equal(failure.queries.filter(q=>q.sql==="COMMIT").length,1,"Only schema preparation committed; source data did not");
  const transaction=fakePool({failCommit:true});await assert.rejects(Import.persist(transaction,[good],{storeProfile,now:at}),/test transaction failure/);assert(transaction.released);assert(transaction.queries.some(q=>q.sql==="ROLLBACK"));
  const noQueries=fakePool();const invalid=await Import.persist(noQueries,[{...good,price:1}],{storeProfile,now:at});assert.equal(invalid.rejected.length,1);assert.equal(noQueries.queries.length,0,"Invalid native candidates cannot create even a canonical store");
  await assert.rejects(Import.persist(noQueries,[],{storeProfile:{...storeProfile,storeId:1776},now:at}),/approved-store-profile/);await assert.rejects(Import.persist(noQueries,Array(4001).fill(good),{storeProfile,now:at}),/bounded-candidate/);
  console.log("hit-price-import tests passed");
 }finally{Date.now=previous}
}
main().catch(error=>{console.error(error);process.exitCode=1});
