"use strict";
const assert=require("node:assert/strict"),crypto=require("node:crypto"),{Pool}=require("pg"),Import=require("../hit-price-import"),Client=require("../hit-assortment-client"),Query=require("../current-price-query-service"),Benchmark=require("../current-price-benchmark-service"),Semantics=require("../source-semantics"),Aliases=require("../product-alias-store"),Browser=require("../app/current-price-client");
const Refresh=require("../hit-price-refresh"),SOURCE=Import.SOURCE,storeProfile=Import.STORE_PROFILE,sku="000000000000869561ST",gtin="4388844177314",hash=value=>crypto.createHash("sha256").update(value).digest("hex");
const BrandFixture=require("./fixtures/hit-brand-probe");
// Native identity/normal-price fields from the saved public Berlin-Mitte milk card.
// Capture metadata and subsequent changed prices are explicitly local TEST responses.
const raw={external_id:sku,ean:gtin,storeId:1775,storeNumber:"258",headline:"ja! H-Milch 1,5%",overview:"1l Packung",price:"0.85",deposit:null,url:"https://www.hit.de/sortiment/kaese-eier-molkerei/milch-h-kuh-4261891/ja-h-milch-15-"+sku,inventoryAvailable:true,inventoryUpdatedAt:"2026-10-01T19:24:29+02:00",priceTag:{type:"discount",badgeText:"DAUER\nDISCOUNT\nPREIS",priceEuro:"0",priceCent:"85",priceStrikeThroughText:null,beforeText:null,belowText:null,couponCode:null,couponName:null}};
function candidate(capture,changes={}){const result=Client.parseRow({...structuredClone(raw),...changes},{storeProfile,capturedAt:new Date(capture).toISOString(),responseDate:new Date(capture).toUTCString(),responseAgeSeconds:0,sourceResponseHash:hash("POSTGRES TEST HIT response "+capture+JSON.stringify(changes)),sourceResponseUrl:"https://www.hit.de/sortiment/kaese-eier-molkerei/milch-h-kuh-4261891?markt=258"});assert(result.ok,JSON.stringify(result));return result.candidate}
function refreshBatch(time){
 const cursorDay=Query.today(new Date(time)),url="https://www.hit.de/sortiment/uebersicht",otherSku="000000000000999991ST",otherGtin="4000000000013",child={id:"4261329",name:"POSTGRES TEST category",url:"https://www.hit.de/sortiment/kaese-eier-molkerei/joghurt-4261329",level:1,count:1,order:0,parentId:null,observedChildIds:[],evidence:"native-assortment-filters"};
 const meta={storeProfile,capturedAt:new Date(time).toISOString(),responseDate:new Date(time).toUTCString(),responseAgeSeconds:0,sourceResponseHash:hash("POSTGRES TEST refresh page "+time),sourceResponseUrl:url};
 const parsed=Client.parseRow({...structuredClone(raw),external_id:otherSku,ean:otherGtin,headline:"POSTGRES TEST unrelated packaged product",overview:"500g Beutel",url:"https://www.hit.de/sortiment/vorraete/test-"+otherSku},meta);assert.equal(parsed.ok,true,JSON.stringify(parsed));
 const unrelated=parsed.candidate,quoteKey=[unrelated.gtin,unrelated.normalizedPack.unit,unrelated.normalizedPack.amount/unrelated.packCount,unrelated.packCount].join("|"),seenQuotes={[quoteKey]:{gtin:unrelated.gtin,signature:hash(JSON.stringify([unrelated.name,unrelated.priceCents,unrelated.depositCents,unrelated.nativePriceType]))}};
 const categoryCoverage={visited:1,pending:1,truncatedLeaves:[],unresolvedNodes:[],conflictingIdentities:[gtin]},cursor={version:2,cursorDay,nativeStoreId:1775,nativeStoreNumber:"258",total:3,pagesFetched:1,received:2,initialIndexLoaded:true,overviewLoaded:true,pending:[child],visited:[{id:null,url,level:null,total:3,rowCount:2,uniqueRowCount:2,children:[child.id],truncated:false,unresolved:false,conflictGtins:[gtin]}],seenSkus:[sku,otherSku],seenQuotes,conflictGtins:[gtin],categoryCoverage};
 return{sourceId:SOURCE,cursorDay,accepted:[parsed.candidate],rejected:[{retailerSku:sku,gtin,reasons:["hit-conflicting-native-gtin-cycle-quarantine"]}],pages:[{...meta,rowCount:2,uniqueRowCount:2,categoryId:null,children:[child.id],truncated:false,accepted:1,rejected:1,conflictGtins:[gtin],pagination:{page:0,limit:2,total:3}}],requests:4,complete:false,categoryTraversalCycleComplete:false,nativePaginationComplete:false,publishedTraversalComplete:false,physicalStoreAssortmentComplete:false,categoryCoverage,conflictGtins:[gtin],cursor,total:3,pagesFetched:1,received:2,error:null};
}
const count=async(pool,table,where="true",args=[])=>Number((await pool.query("SELECT count(*)::int AS n FROM "+table+" WHERE "+where,args)).rows[0].n);
function brandProbeBatch(time){
 const probe=BrandFixture.record({now:time-1000}),page={...probe.control.meta,rowCount:3,uniqueRowCount:3,categoryId:probe.category.id,children:[],truncated:false,accepted:0,rejected:3,conflictGtins:[],pagination:{page:0,limit:40,total:3}},coverage={visited:1,pending:0,truncatedLeaves:[],unresolvedNodes:[],conflictingIdentities:[]};
 return{sourceId:SOURCE,cursorDay:Query.today(new Date(time)),accepted:[],rejected:probe.control.skuIds.map(retailerSku=>({retailerSku,reasons:["synthetic-diagnostic-fixture-without-prices"]})),pages:[page],requests:5,complete:true,categoryTraversalCycleComplete:true,nativePaginationComplete:true,publishedTraversalComplete:true,physicalStoreAssortmentComplete:false,categoryCoverage:coverage,conflictGtins:[],cursor:null,total:3,pagesFetched:1,received:3,error:null,brandFilterProbe:probe};
}
async function main(){
 const connectionString=process.env.DATABASE_URL;assert(connectionString,"DATABASE_URL is required for the HIT PostgreSQL test");const database=new URL(connectionString);assert.equal(database.hostname,"localhost","HIT integration writes only to a dedicated local test database");assert(database.pathname.endsWith("_test"),"Use a dedicated _test database");
 const pool=new Pool({connectionString,ssl:false,connectionTimeoutMillis:5000}),api=require("../server");let testError;
 try{
  await api.initDb();await Import.ensure(pool);await Aliases.ensure(pool);assert(Semantics.policy({source:SOURCE,sourceType:"official_retailer"}).registered,"Root must register the real HIT source before API admission");
  const now=Date.now(),capture=now-120000,today=Query.today(new Date(capture)),good=candidate(capture),options={storeProfile,now};
  const baseline={products:await count(pool,"products"),observations:await count(pool,"price_observations"),receipts:await count(pool,"receipt_submissions"),availability:await count(pool,"availability_observations"),aliases:await count(pool,"product_alias_evidence")};
  const first=await Import.persist(pool,[good],options);assert.equal(first.accepted.length,1,JSON.stringify(first));assert.equal(first.rejected.length,0);const accepted=first.accepted[0],storeId=accepted.storeId,productId=accepted.productId;
  const product=(await pool.query("SELECT name,brand,pack_amount::float AS amount,pack_unit AS unit,pack_count::int AS count FROM products WHERE id=$1",[productId])).rows[0];assert.equal(product.amount*({l:1000,kg:1000,cl:10}[product.unit]||1),1000);assert.equal(product.count,1);
  if(first.productsCreated)assert.equal(product.brand,null,"ja! is not inferred as a canonical brand");
  const store=(await pool.query("SELECT s.*,m.name AS merchant FROM stores s JOIN merchants m ON m.id=s.merchant_id WHERE s.id=$1",[storeId])).rows[0];assert.equal(store.external_id,"hit:store:1775");assert.equal(store.address,storeProfile.address);assert.equal(store.postal_code,"10117");assert.equal(store.city,"Berlin");assert.equal(store.country,"DE");assert.equal(Number(store.latitude),storeProfile.latitude);assert.equal(Number(store.longitude),storeProfile.longitude);assert.equal(store.merchant,"HIT");assert.equal(store.active,true);
  const storeMap=(await pool.query("SELECT * FROM external_store_mappings WHERE source_id=$1 AND external_location_id='1775'",[SOURCE])).rows[0];assert.equal(storeMap.store_id,storeId);assert.equal(storeMap.status,"verified");assert.equal(Number(storeMap.confidence),1);
  const nativeId="hit:store:1775:sku:"+sku,productMap=(await pool.query("SELECT * FROM external_product_mappings WHERE source_id=$1 AND external_product_id=$2",[SOURCE,nativeId])).rows[0];assert.equal(productMap.product_id,productId);assert.equal(productMap.status,"verified");
  const fact=(await pool.query("SELECT *,date::text AS day,valid_from::text AS from_day,valid_to::text AS to_day FROM price_observations WHERE id=$1",[accepted.observationId])).rows[0];assert.equal(Number(fact.price),.85);assert.equal(fact.per,"piece");assert.equal(fact.source_type,"official_retailer");assert.equal(fact.source_id,SOURCE);assert.equal(fact.evidence_purpose,"current-price");assert.equal(fact.pack,"1000 ml");assert.equal(fact.status,"observed");assert.equal(fact.truth_eligible,true);assert.equal(fact.identity_verified,true);assert.equal(fact.proof_verified,false);assert.equal(fact.proof_actor,null);assert.equal(fact.min_quantity,null);assert.equal(fact.regular_price,null);assert.equal(fact.observed_at.toISOString(),good.capturedAt);assert.equal(fact.fetched_at.toISOString(),good.capturedAt);assert.equal(fact.day,today);assert.equal(fact.from_day,today);assert.equal(fact.to_day,Query.today(new Date(Date.parse(good.expiresAt)-1)));assert.deepEqual(fact.eligibility,{scopeChannel:"physical-store",sourceScope:"physical-store",nativeStoreId:1775,nativeStoreNumber:"258",goodsPriceCents:85,depositCents:null,priceIncludesDeposit:false,checkoutPriceVerified:false,sourceExpiresAt:good.expiresAt});
  const ledger=(await pool.query("SELECT * FROM hit_price_import_evidence WHERE observation_id=$1",[accepted.observationId])).rows[0];assert.equal(ledger.expires_at.toISOString(),good.expiresAt);assert.equal(ledger.captured_at.toISOString(),good.capturedAt);assert.equal(ledger.source_response_hash,good.sourceResponseHash);assert.deepEqual(ledger.native_proof,good.nativeProof);assert.equal(ledger.deposit_cents,null);
  const fixed=await count(pool,"price_observations","source_id=$1",[SOURCE]);const duplicate=await Import.persist(pool,[good],options);assert.equal(duplicate.duplicates,1);assert.equal(duplicate.accepted.length,0);assert.equal(await count(pool,"price_observations","source_id=$1",[SOURCE]),fixed);
  const conflicting=candidate(capture,{price:"0.95",priceTag:{...raw.priceTag,priceCent:"95"}}),same=await Import.persist(pool,[conflicting],options);assert.equal(same.rejected[0].reasons[0],"hit-import-same-capture-conflict");assert.equal(await count(pool,"price_observations","source_id=$1",[SOURCE]),fixed);
  const wrongPack=candidate(capture+1000,{headline:"POSTGRES TEST HIT conflicting pack",overview:"2x500ml Packung"}),packBlocked=await Import.persist(pool,[wrongPack],options);assert.equal(packBlocked.rejected[0].reasons[0],"hit-import-canonical-product-pack-conflict");assert.equal(await count(pool,"price_observations","source_id=$1",[SOURCE]),fixed);
  await pool.query("UPDATE external_product_mappings SET status='review' WHERE source_id=$1 AND external_product_id=$2",[SOURCE,nativeId]);try{const blocked=await Import.persist(pool,[candidate(capture+2000)],options);assert.equal(blocked.rejected[0].reasons[0],"hit-import-product-mapping-conflict");assert.equal(await count(pool,"price_observations","source_id=$1",[SOURCE]),fixed)}finally{await pool.query("UPDATE external_product_mappings SET status='verified' WHERE source_id=$1 AND external_product_id=$2",[SOURCE,nativeId])}
  const newer=candidate(capture+10000,{price:"0.95",priceTag:{...raw.priceTag,priceCent:"95"}}),next=await Import.persist(pool,[newer],options);assert.equal(next.accepted.length,1);let history=(await pool.query("SELECT id,status,truth_eligible,observed_at FROM price_observations WHERE id=ANY($1::uuid[]) ORDER BY observed_at",[[accepted.observationId,next.accepted[0].observationId]])).rows;assert.equal(history[0].status,"superseded");assert.equal(history[0].truth_eligible,false);assert.equal(history[0].observed_at.toISOString(),good.capturedAt);assert.equal(history[1].status,"observed");assert.equal(history[1].truth_eligible,true);assert.equal(await count(pool,"hit_price_import_evidence","source_id=$1 AND retailer_sku=$2",[SOURCE,sku]),2,"New captures preserve both original proofs");
  const late=await Import.persist(pool,[candidate(capture+5000,{headline:"POSTGRES TEST HIT alternate native wording",brand:"POSTGRES TEST HIT explicit native brand"})],options);assert.equal(late.accepted.length,1);const lateFact=(await pool.query("SELECT status,truth_eligible FROM price_observations WHERE id=$1",[late.accepted[0].observationId])).rows[0];assert.equal(lateFact.status,"superseded");assert.equal(lateFact.truth_eligible,false,"Out-of-order arrival cannot make an older price current again");assert.deepEqual((await pool.query("SELECT name,brand FROM products WHERE id=$1",[productId])).rows[0],{name:product.name,brand:product.brand},"Existing canonical name/brand are not overwritten by retailer wording");
  const input={product:good.name,gtin,pack:"1 l",merchants:["HIT"],storeIds:{HIT:storeId},region:"Berlin",today,maxAgeDays:7,refresh:false};const quote=await Query.compareCurrentPrices(pool,input);assert.equal(quote.ok,true,JSON.stringify(quote));const row=quote.results.find(r=>r.merchant==="HIT");assert(row);assert.equal(row.price,.95,JSON.stringify(row));assert.equal(row.locationLevel,"store");assert.equal(row.storeId,storeId);assert.equal(row.source,SOURCE);assert.equal(row.identityVerified,true);assert.equal(row.proofVerified,false);assert.equal(row.sourceEligibility.depositCents,null);assert.equal(row.sourceEligibility.checkoutPriceVerified,false);
  assert.equal(row.region,"Berlin");assert.equal(quote.leaders.lowestCheckout,null);const browser=Browser.normalizeDecision(JSON.parse(JSON.stringify(row)),{query:{gtin,pack:"1 l"},region:"Berlin",storeId,today,maxAgeDays:7});assert.equal(browser.price,.95,JSON.stringify(browser));assert.equal(browser.checkoutPriceVerified,false);assert.equal(browser.payablePackPrice,null);assert.equal(Browser.toComparablePrice(browser,"piece","1 l"),null,"A physical goods price remains visible but cannot become a payable basket without a native deposit amount");
  const benchmark=await Benchmark.compare(pool,{products:[{product:good.name,gtin,pack:"1 l",quantity:1}],merchants:["HIT"],storeIds:{HIT:storeId},region:"Berlin",today,maxAgeDays:7});assert.equal(benchmark.ok,true,JSON.stringify(benchmark));assert.equal(benchmark.summary.knownCells,1);assert.equal(benchmark.summary.verifiedCells,0,"Native identity evidence does not claim a manually reviewed proof");
  const tomorrow=new Date(Date.parse(today+"T12:00:00Z")+86400000).toISOString().slice(0,10),expired=await Query.compareCurrentPrices(pool,{...input,today:tomorrow});assert.equal(expired.results.find(r=>r.merchant==="HIT").price,.95,"The original unexpired 24-hour capture remains usable on the next Berlin day");
  const concurrent=candidate(capture+20000),parallel=await Promise.all([Import.persist(pool,[concurrent],options),Import.persist(pool,[concurrent],options)]);assert.equal(parallel.reduce((sum,r)=>sum+r.accepted.length,0),1);assert.equal(parallel.reduce((sum,r)=>sum+r.duplicates,0),1);assert.equal(await count(pool,"stores","external_id='hit:store:1775'"),1);assert.equal(await count(pool,"products","gtin=$1",[gtin]),1);
  const poolProxy={query:(...args)=>pool.query(...args),connect:async()=>{const tx=await pool.connect();return{release:()=>tx.release(),query:async(sql,args)=>{if(sql.startsWith("INSERT INTO product_identity_evidence"))throw Object.assign(Error("POSTGRES TEST injected source persistence outage"),{code:"XX000"});return tx.query(sql,args)}}}};
  const beforeFailure=await count(pool,"price_observations","source_id=$1",[SOURCE]),latest=(await pool.query("SELECT observation_id FROM hit_price_import_evidence WHERE source_id=$1 ORDER BY captured_at DESC LIMIT 1",[SOURCE])).rows[0].observation_id;
  await assert.rejects(Import.persist(poolProxy,[candidate(capture+30000)],options),error=>error.code==="XX000");assert.equal(await count(pool,"price_observations","source_id=$1",[SOURCE]),beforeFailure,"A database failure rolls back the real observation insert, not just a simulated counter");assert.equal((await pool.query("SELECT truth_eligible FROM price_observations WHERE id=$1",[latest])).rows[0].truth_eligible,true,"A failed capture does not supersede the previous valid price");
  const resume=await Import.persist(pool,[candidate(capture+30000)],options);assert.equal(resume.accepted.length,1,"The same capture can be retried after the failed transaction");
  const withDeposit=candidate(capture+40000,{headline:"POSTGRES TEST HIT ja! H-Milch 1,5% explicit deposit case",deposit:"0.25"}),paid=await Import.persist(pool,[withDeposit],options);assert.equal(paid.accepted.length,1);const depositQuote=await Query.compareCurrentPrices(pool,input),depositRow=depositQuote.results.find(r=>r.merchant==="HIT");assert.equal(depositRow.goodsPrice,.85,JSON.stringify(depositRow));assert.equal(depositRow.deposit,.25);assert.equal(depositRow.payablePackPrice,1.10);assert.equal(depositRow.checkoutPriceVerified,true);const payable=Browser.normalizeDecision(JSON.parse(JSON.stringify(depositRow)),{query:{gtin,pack:"1 l"},region:"Berlin",storeId,today,maxAgeDays:7});assert.equal(Browser.toComparablePrice(payable,"piece","1 l").price,1.10,"The browser uses the separately evidenced deposit without changing the goods price");
  await pool.query("UPDATE price_observations SET observed_at=statement_timestamp()-interval '24 hours 1 second' WHERE id=$1",[paid.accepted[0].observationId]);const beyond24h=await Query.compareCurrentPrices(pool,input);assert.equal(beyond24h.results.find(r=>r.merchant==="HIT").price,null,"A still-valid calendar day cannot admit a capture older than 24 hours, including the 25-hour DST day");await pool.query("UPDATE price_observations SET observed_at=$2 WHERE id=$1",[paid.accepted[0].observationId,withDeposit.capturedAt]);
  const invalid=await Import.persist(pool,[{...good,nativeStoreId:1776},{...good,gtin:"invalid"},{...good,capturedAt:new Date(now-300001).toISOString()}],options);assert.equal(invalid.rejected.length,3);assert.equal(invalid.accepted.length,0);
  assert.equal(await count(pool,"receipt_submissions"),baseline.receipts);assert.equal(await count(pool,"availability_observations"),baseline.availability,"Public price cards do not claim observed shelf stock");assert.equal(await count(pool,"product_alias_evidence"),baseline.aliases,"No alias EAN or receipt-name learning is performed");
  const status=await Refresh.status(pool);assert.equal(status.nativeStoreId,1775);assert.equal(status.physicalStoreAssortmentComplete,false);assert.equal(status.publishedTraversalComplete,false);assert.equal(status.historicalProducts,1);assert.equal(status.currentProducts,1);assert.equal(status.unknownDepositPrices,0);
  // Legacy date windows are repaired only from original ledger timestamps.
  const paidId=paid.accepted[0].observationId,originalPaid=(await pool.query("SELECT * FROM price_observations WHERE id=$1",[paidId])).rows[0],originalLedger=(await pool.query("SELECT * FROM hit_price_import_evidence WHERE observation_id=$1",[paidId])).rows[0];
  await pool.query("UPDATE price_observations SET valid_to=valid_from WHERE id=$1",[paidId]);
  assert.equal(await Import.repairValidityWindow(pool),1);assert.equal(await Import.repairValidityWindow(pool),0);
  const repaired=(await pool.query("SELECT * FROM price_observations WHERE id=$1",[paidId])).rows[0];assert.deepEqual(repaired,originalPaid,"Repair changes only the old date window, keeping price, capture, hashes, status and eligibility unchanged");
  assert.deepEqual((await pool.query("SELECT * FROM hit_price_import_evidence WHERE observation_id=$1",[paidId])).rows[0],originalLedger,"The original ledger and native response remain immutable");
  // Real PostgreSQL join and browser admission for a separately labelled physical offer.
  const Physical=require("../hit-product-discovery"),Published=require("../published-product-discovery"),Picker=require("../app/published-product-client");
  const SearchFilters=require("../retailer-product-search-filters");
  for(const [pack,amount,count]of[["0.0049 kg",4.9,1],["4.9 g",4.9,1],["0.0041 kg",4.1,1],["4.1 g",4.1,1],["2 x 4.9 g",4.9,2]]){
   const values=[],clause=SearchFilters.sqlPack(pack,value=>{values.push(value);return "$"+values.length;});
   const rows=(await pool.query("SELECT pack_amount::float AS amount,pack_count AS count FROM (VALUES (4.9::numeric,'g',1),(4.1::numeric,'g',1),(9.8::numeric,'g',1),(4.9::numeric,'g',2)) AS fixture(pack_amount,pack_unit,pack_count) WHERE "+clause,values)).rows;
   assert.deepEqual(rows,[{amount,count}],"Decimal conversion uses the same narrow comparison while retaining multipack count: "+pack);
  }
  let physical=await Physical.search(pool,{search:"H-Milch",limit:200,now:Date.now()});assert.equal(physical.items.length,1,JSON.stringify(physical));
  assert.equal((await Physical.search(pool,{search:"H-Milch",pack:"1 l",limit:1})).items.length,1,"The real SQL matches canonical 1l/native 1000ml before LIMIT");
  assert.equal((await Physical.search(pool,{search:"H-Milch",pack:"2 x 500 ml",limit:1})).items.length,0,"Equal total volume cannot match a different sales pack");
  assert.equal((await Physical.search(pool,{search:"H-Milch",pack:"500 ml",limit:1})).items.length,0);
  const scopedPack=await Published.search(pool,{search:"H-Milch",pack:"1000 ml",scopeChannel:"physical-store",limit:1},{search:async()=>{throw Error("No online lookup for physical scope");}});assert.equal(scopedPack.items.length,1);assert.deepEqual(scopedPack.scopeChannels,["physical-store"]);
  const picked=await Published.search(pool,{search:"H-Milch",limit:20}, {search:async()=>({items:[]})});
  assert.equal(picked.items.length,1);assert.equal(picked.physicalStorePrices,true);assert.equal(picked.items[0].offers.length,0);assert.equal(picked.items[0].physicalOffers.length,1);
  const normalizedPicker=Picker.normalizeResponse(JSON.parse(JSON.stringify(picked)),{now:Date.now()});assert.equal(normalizedPicker.items.length,1,JSON.stringify(normalizedPicker));assert.equal(normalizedPicker.items[0].physicalOffers[0].storeId,storeId);
  await pool.query("UPDATE stores SET country='AT' WHERE id=$1",[storeId]);try{assert.equal((await Physical.search(pool,{search:"H-Milch",limit:200})).items.length,0,"A wrong-country branch cannot enter physical product selection");}finally{await pool.query("UPDATE stores SET country='DE' WHERE id=$1",[storeId]);}
  await pool.query("UPDATE external_product_mappings SET status='review' WHERE source_id=$1 AND external_product_id=$2",[SOURCE,nativeId]);try{assert.equal((await Physical.search(pool,{search:"H-Milch",limit:200})).items.length,0,"Physical selection requires the verified native SKU mapping");}finally{await pool.query("UPDATE external_product_mappings SET status='verified' WHERE source_id=$1 AND external_product_id=$2",[SOURCE,nativeId]);}
  await pool.query("UPDATE price_observations SET truth_eligible=false WHERE id=$1",[paidId]);try{assert.equal((await Physical.search(pool,{search:"H-Milch",limit:200})).items.length,0,"Quarantined or superseded captures never enter product selection");}finally{await pool.query("UPDATE price_observations SET truth_eligible=true WHERE id=$1",[paidId]);}
  await pool.query("UPDATE price_observations SET eligibility=jsonb_set(eligibility,'{sourceExpiresAt}',to_jsonb((statement_timestamp()-interval '1 second')::text)) WHERE id=$1",[paidId]);try{assert.equal((await Query.compareCurrentPrices(pool,input)).results.find(r=>r.merchant==="HIT").price,null,"The real query enforces the original native expiry before making a price decision");assert.equal((await Physical.search(pool,{search:"H-Milch",limit:200})).items.length,0);}finally{await pool.query("UPDATE price_observations SET eligibility=$2::jsonb WHERE id=$1",[paidId,JSON.stringify(originalPaid.eligibility)]);}
  const oldKilogramSku="000000000002001956KG",paidObservation=paid.accepted[0].observationId;
  // Simulate a legacy kilogram observation in this isolated test DB. Historical evidence stays present.
  await pool.query("UPDATE price_observations SET external_product_id=$2 WHERE id=$1",[paidObservation,"hit:store:1775:sku:"+oldKilogramSku]);
  await pool.query("UPDATE hit_price_import_evidence SET retailer_sku=$2 WHERE observation_id=$1",[paidObservation,oldKilogramSku]);
  assert.equal((await Query.compareCurrentPrices(pool,input)).results.find(r=>r.merchant==="HIT").price,null,"Already stored kilogram prices are excluded from fixed pack queries");
  assert.equal(await count(pool,"price_observations","id=$1 AND truth_eligible=true",[paidObservation]),1,"The isolated legacy fixture starts with the incorrect active truth flag");
  const originalKilogramEvidence=(await pool.query("SELECT * FROM hit_price_import_evidence WHERE observation_id=$1",[paidObservation])).rows[0];
  assert.equal(await Import.quarantineUnsupportedWeight(pool),1,"Deactivate only the matching legacy source/store/SKU weight observation");
  assert.equal(await Import.quarantineUnsupportedWeight(pool),0,"The source repair is idempotent");
  assert.deepEqual((await pool.query("SELECT truth_eligible,status FROM price_observations WHERE id=$1",[paidObservation])).rows[0],{truth_eligible:false,status:"unsupported-weight-sale-unit"});
  assert.deepEqual((await pool.query("SELECT * FROM hit_price_import_evidence WHERE observation_id=$1",[paidObservation])).rows[0],originalKilogramEvidence,"Original native evidence, hashes, capture times and price remain unchanged");
  const quarantinedStatus=await Refresh.status(pool);assert.equal(quarantinedStatus.truthEligibleKilogramCaptures,0);assert.equal(quarantinedStatus.unsupportedKilogramCaptures,1);assert.equal(quarantinedStatus.currentPrices,0);assert.equal(quarantinedStatus.currentProducts,0);assert.equal(quarantinedStatus.historicalProducts,1,"Excluded observations remain historical evidence");
  await pool.query("UPDATE price_observations SET external_product_id=$2,truth_eligible=true,status='observed' WHERE id=$1",[paidObservation,nativeId]);
  await pool.query("UPDATE hit_price_import_evidence SET retailer_sku=$2 WHERE observation_id=$1",[paidObservation,sku]);
  assert.equal((await Refresh.status(pool)).unsupportedKilogramCaptures,0);
  // The caller owns one transaction across quarantine, fresh admission and checkpoint.
  // A failed checkpoint must roll all three back, preserving native captures and prior truth.
  const beforeAtomic=(await pool.query("SELECT * FROM price_observations WHERE id=$1",[paidObservation])).rows[0],beforeAtomicLedger=(await pool.query("SELECT * FROM hit_price_import_evidence WHERE observation_id=$1",[paidObservation])).rows[0],beforeAtomicCaptures=await count(pool,Import.TABLE),atomic=await pool.connect();
  let enlistedId;try{await atomic.query("BEGIN");assert.equal(await Import.quarantineConflictingIdentities(atomic,[gtin]),1);assert.equal(await Import.quarantineConflictingIdentities(atomic,[gtin]),0,"Quarantine is idempotent inside its transaction");assert.equal((await atomic.query("SELECT truth_eligible,status FROM price_observations WHERE id=$1",[paidObservation])).rows[0].status,"conflicting-source");assert.deepEqual((await atomic.query("SELECT * FROM hit_price_import_evidence WHERE observation_id=$1",[paidObservation])).rows[0],beforeAtomicLedger);
   const enlisted=await Import.persist(pool,[candidate(capture+50000)],{...options,transactionClient:atomic});assert.equal(enlisted.accepted.length,1);enlistedId=enlisted.accepted[0].observationId;assert.equal(await count(atomic,Import.TABLE),beforeAtomicCaptures+1);assert.equal(await count(pool,Import.TABLE),beforeAtomicCaptures,"An enlisted import cannot commit before the outer checkpoint");
   await assert.rejects(atomic.query("SELECT 1/0"),error=>error.code==="22012"); // A real PostgreSQL checkpoint failure aborts the outer transaction.
  }finally{await atomic.query("ROLLBACK");atomic.release();}
  assert.equal(await count(pool,Import.TABLE),beforeAtomicCaptures);assert.equal(await count(pool,"price_observations","id=$1",[enlistedId]),0);assert.deepEqual((await pool.query("SELECT * FROM price_observations WHERE id=$1",[paidObservation])).rows[0],beforeAtomic);assert.deepEqual((await pool.query("SELECT * FROM hit_price_import_evidence WHERE observation_id=$1",[paidObservation])).rows[0],beforeAtomicLedger);
  // Exercise the actual refresh owner and actual progress INSERT, with no source requests.
  assert.equal(await count(pool,Refresh.TABLE,"source_id=$1",[SOURCE]),0,"This dedicated test DB has no running collector checkpoint");
  const refreshTime=Date.now(),refreshResult=refreshBatch(refreshTime),failingRefreshPool={query:(...args)=>pool.query(...args),connect:async()=>{const tx=await pool.connect();return{release:()=>tx.release(),query:(sql,args)=>sql.startsWith("INSERT INTO "+Refresh.TABLE)&&args?.length===10?tx.query("SELECT 1/0"):tx.query(sql,args)}}};
  try{
   await assert.rejects(Refresh.refresh({pool:failingRefreshPool,now:()=>refreshTime},{collect:async()=>structuredClone(refreshResult)}),error=>error.code==="22012");
   assert.equal(await count(pool,Import.TABLE),beforeAtomicCaptures,"The actual checkpoint failure rolls back its new capture");
   assert.deepEqual((await pool.query("SELECT * FROM price_observations WHERE id=$1",[paidObservation])).rows[0],beforeAtomic,"The actual refresh rollback restores the quarantined prior observation");
   assert.deepEqual((await pool.query("SELECT * FROM hit_price_import_evidence WHERE observation_id=$1",[paidObservation])).rows[0],beforeAtomicLedger);
   const failedState=(await Refresh.load(pool));assert.equal(failedState.cursor,null);assert.equal(failedState.pagesFetched,0);assert.equal(failedState.receivedCumulative,0);assert.equal(failedState.lastError,"22012");assert.equal(new Date(failedState.retryAfter).getTime(),refreshTime+3600000);
   const paused=await Refresh.refresh({pool,now:()=>refreshTime+1},{collect:async()=>{throw Error("The database retry cooldown must be respected");}});assert.equal(paused.skipped,"source-cooldown");
   // Remove only the deliberately injected failure metadata in the isolated test DB.
   await pool.query("DELETE FROM "+Refresh.TABLE+" WHERE source_id=$1",[SOURCE]);
   const refusedFailure={...structuredClone(refreshResult),error:{code:"hit-source-http-429",retryAfterMs:7200000}};
   await assert.rejects(Refresh.refresh({pool:failingRefreshPool,now:()=>refreshTime},{collect:async()=>refusedFailure}),error=>error.code==="22012"&&Date.parse(error.nextAttemptAt)===refreshTime+7200000);
   const failedRefusalState=await Refresh.load(pool);assert.equal(failedRefusalState.lastError,"hit-source-http-429");assert.equal(new Date(failedRefusalState.retryAfter).getTime(),refreshTime+7200000,"A checkpoint outage cannot shorten the observed native source pause");assert.equal(await count(pool,Import.TABLE),beforeAtomicCaptures);assert.deepEqual((await pool.query("SELECT * FROM price_observations WHERE id=$1",[paidObservation])).rows[0],beforeAtomic);
   await pool.query("DELETE FROM "+Refresh.TABLE+" WHERE source_id=$1",[SOURCE]);
   const resumed=await Refresh.refresh({pool,now:()=>refreshTime},{collect:async()=>structuredClone(refreshResult)});assert.equal(resumed.accepted,1);assert.equal(resumed.quarantinedObservations,1);assert.deepEqual(resumed.conflictGtins,[gtin]);assert.equal(resumed.publishedTraversalComplete,false);
   const savedState=await Refresh.load(pool);assert.deepEqual(savedState.cursor,refreshResult.cursor);assert.equal(savedState.pagesFetched,1);assert.equal(savedState.receivedCumulative,2);assert.equal(savedState.lastError,null);assert.equal(savedState.retryAfter,null);assert.deepEqual(savedState.scanCoverage.categoryCoverage.conflictingIdentities,[gtin]);
   assert.equal(await count(pool,Import.TABLE),beforeAtomicCaptures+1);assert.deepEqual((await pool.query("SELECT * FROM price_observations WHERE id=$1",[paidObservation])).rows[0],{...beforeAtomic,truth_eligible:false,status:"conflicting-source"});assert.deepEqual((await pool.query("SELECT * FROM hit_price_import_evidence WHERE observation_id=$1",[paidObservation])).rows[0],beforeAtomicLedger);
   // A changed durable checkpoint while collection runs wins over the stale batch.
   const laterTime=refreshTime+60001,newerStamp=new Date(laterTime+1).toISOString(),beforeStale=await count(pool,Import.TABLE);
   const stale=await Refresh.refresh({pool,now:()=>laterTime},{collect:async()=>{await pool.query("UPDATE "+Refresh.TABLE+" SET updated_at=$2 WHERE source_id=$1",[SOURCE,newerStamp]);return{...refreshResult,accepted:[],rejected:[],pages:[],requests:2,error:{code:"hit-source-http-500"}};}});
   assert.equal(stale.skipped,"checkpoint-changed");assert.equal(await count(pool,Import.TABLE),beforeStale);assert.equal(new Date((await Refresh.load(pool)).updatedAt).toISOString(),newerStamp,"A stale collector cannot overwrite a newer progress checkpoint");
   const refusalTime=laterTime+60002,refusalStamp=new Date(refusalTime+1).toISOString();
   const refused=await Refresh.refresh({pool,now:()=>refusalTime},{collect:async()=>{await pool.query("UPDATE "+Refresh.TABLE+" SET updated_at=$2 WHERE source_id=$1",[SOURCE,refusalStamp]);return{...refreshResult,accepted:[],rejected:[],pages:[],requests:2,error:{code:"hit-source-http-429",retryAfterMs:7200000}};}});
   assert.equal(refused.skipped,"checkpoint-changed");assert.equal(refused.sourceError,"hit-source-http-429");const refusedState=await Refresh.load(pool);assert.equal(refusedState.lastError,"hit-source-http-429");assert.equal(new Date(refusedState.retryAfter).getTime(),refusalTime+7200000,"A real source refusal survives a newer concurrent checkpoint and keeps native Retry-After");assert.deepEqual(refusedState.cursor,refreshResult.cursor);assert.equal(await count(pool,Import.TABLE),beforeStale);
  }finally{await pool.query("DELETE FROM "+Refresh.TABLE+" WHERE source_id=$1",[SOURCE]);await pool.query("UPDATE price_observations SET truth_eligible=$2,status=$3 WHERE id=$1",[paidObservation,beforeAtomic.truth_eligible,beforeAtomic.status]);}
  // The original diagnostic body is enlisted in the SAME actual checkpoint transaction.
  const probeTime=Date.now(),probeResult=brandProbeBatch(probeTime),probeCaptures=await count(pool,Import.TABLE),failingProbePool={query:(...args)=>pool.query(...args),connect:async()=>{const tx=await pool.connect();return{release:()=>tx.release(),query:async(sql,args)=>{const result=await tx.query(sql,args);if(sql.startsWith("UPDATE "+Refresh.TABLE+" SET brand_filter_probe="))await tx.query("SELECT 1/0");return result;}}}};
  try{
   await assert.rejects(Refresh.refresh({pool:failingProbePool,now:()=>probeTime},{collect:async options=>{assert.equal(options.brandProbeEnabled,true);return structuredClone(probeResult)}}),error=>error.code==="22012");
   const rolledBack=await Refresh.load(pool);assert.equal(rolledBack.brandFilterProbeAttempted,false);assert.equal(rolledBack.brandFilterProbe,null);assert.equal(rolledBack.pagesFetched,0);assert.equal(rolledBack.receivedCumulative,0);assert.equal(rolledBack.lastError,"22012");assert.equal(await count(pool,Import.TABLE),probeCaptures,"The probe never imports its filtered rows");assert.equal((await pool.query("SELECT brand_filter_probe FROM "+Refresh.TABLE+" WHERE source_id=$1",[SOURCE])).rows[0].brand_filter_probe,null,"Actual PostgreSQL aborted both written original bodies and the normal checkpoint");
   await pool.query("DELETE FROM "+Refresh.TABLE+" WHERE source_id=$1",[SOURCE]);
   const probeSaved=await Refresh.refresh({pool,now:()=>probeTime},{collect:async options=>{assert.equal(options.brandProbeEnabled,true);return structuredClone(probeResult)}});assert.equal(probeSaved.accepted,0);assert.equal(probeSaved.receivedCumulative,3,"The two diagnostic filter SKUs cannot inflate the ordinary three-SKU control traversal");
   const stored=(await pool.query("SELECT brand_filter_probe FROM "+Refresh.TABLE+" WHERE source_id=$1",[SOURCE])).rows[0].brand_filter_probe;assert.equal(stored.outcome,"confirmed");assert.equal(stored.control.body,probeResult.brandFilterProbe.control.body);assert.equal(stored.filtered.body,probeResult.brandFilterProbe.filtered.body);assert.deepEqual(stored.control.skuIds,probeResult.brandFilterProbe.control.skuIds);assert.equal(stored.control.meta.capturedAt,probeResult.brandFilterProbe.control.meta.capturedAt);assert.equal(stored.filtered.meta.sourceResponseHash,probeResult.brandFilterProbe.filtered.meta.sourceResponseHash);assert.equal(stored.collectionEnabled,false);assert.equal(stored.priceImportEnabled,false);assert.equal(stored.complete,false);
   const publicState=await Refresh.status(pool);assert.equal(publicState.brandFilterProbeAttempted,true);assert.equal(publicState.brandFilterProbe.actualHTMLFilterVerified,true);assert.equal(publicState.brandFilterProbe.collectionEnabled,false);assert.equal(publicState.brandFilterProbe.complete,false);assert(!JSON.stringify(publicState).includes("<html>"));assert(!JSON.stringify(publicState).includes('"skuIds"'));assert(!JSON.stringify(publicState).includes('"body"'),"The real public status SELECT explicitly redacts both original bodies and full SKU sets");
   const repeatTime=probeTime+Refresh.REFRESH_MS+1,nextBatch=brandProbeBatch(repeatTime);delete nextBatch.brandFilterProbe;await Refresh.refresh({pool,now:()=>repeatTime},{collect:async options=>{assert.equal(options.brandProbeEnabled,false,"A new process and completed ordinary cycle cannot repeat a durable attempt");return nextBatch}});assert.deepEqual((await pool.query("SELECT brand_filter_probe FROM "+Refresh.TABLE+" WHERE source_id=$1",[SOURCE])).rows[0].brand_filter_probe,stored,"Later checkpoints cannot replace or renew the original probe captures");
   const refusalTime=repeatTime+Refresh.REFRESH_MS+1;await assert.rejects(Refresh.refresh({pool,now:()=>refusalTime},{collect:async options=>{assert.equal(options.brandProbeEnabled,false);throw Object.assign(Error("Synthetic source refusal"),{code:"hit-source-http-429",retryAfterMs:7200000});}}),error=>error.code==="hit-source-http-429");assert.equal(new Date((await Refresh.load(pool)).retryAfter).getTime(),refusalTime+7200000);assert.deepEqual((await pool.query("SELECT brand_filter_probe FROM "+Refresh.TABLE+" WHERE source_id=$1",[SOURCE])).rows[0].brand_filter_probe,stored,"Source failure and reset paths leave the immutable capture record intact");assert.equal(await count(pool,Import.TABLE),probeCaptures);
  }finally{await pool.query("DELETE FROM "+Refresh.TABLE+" WHERE source_id=$1",[SOURCE]);}
  await require("./hit-list-gap-postgres")(pool);
  await require("./hit-brand-partition-postgres")(pool);
  // Need suitability operates on real joined current HIT evidence, with exact packs.
  const needInput={search:"H-Milch 1,5%",pack:"1 l",scopeChannel:"physical-store",constraints:{family:"milk",processing:"uht",fatPercent:1.5}},need=await Published.searchNeed(pool,needInput);
  assert.equal(need.items.length,1,JSON.stringify(need));assert.equal(need.items[0].gtin,gtin);assert.equal(need.items[0].needAssessment.status,"confirmed");assert.equal(need.selectionRequired,true);assert.equal(need.automaticSelection,false);assert.equal(need.items[0].physicalOffers[0].storeId,storeId);assert.equal(need.items[0].physicalOffers[0].proofHash,originalLedger.proof_hash);assert.equal(need.items[0].physicalOffers[0].capturedAt,withDeposit.capturedAt);assert.equal(need.items[0].physicalOffers[0].payablePackPrice,1.10);
  assert.equal((await Published.searchNeed(pool,{...needInput,pack:"2 x 500 ml"})).items.length,0);
  assert.equal((await Published.searchNeed(pool,{...needInput,search:"Milch",constraints:{family:"milk",processing:"fresh"}})).items.length,0,"Fresh milk cannot inherit an actual UHT milk quote");
  const unspecified=await Published.searchNeed(pool,{...needInput,search:"Milch",constraints:{family:"milk",lactose:"contains"}});assert.equal(unspecified.items[0].needAssessment.status,"unconfirmed");assert(unspecified.items[0].needAssessment.offerMatches[0].missing.includes("lactose"));
  await new Promise((resolve,reject)=>{api.server.once("error",reject);api.server.listen(0,"127.0.0.1",resolve);});
  try{const endpoint="http://127.0.0.1:"+api.server.address().port+"/v1/shopping-need",post=async body=>{const response=await fetch(endpoint,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body),signal:AbortSignal.timeout(10000)});return{status:response.status,data:await response.json()};};
   const valid=await post(needInput);assert.equal(valid.status,200);assert.equal(valid.data.items[0].gtin,gtin);assert.equal(valid.data.selectionRequired,true);
   for(const invalid of[{...needInput,refresh:true},{...needInput,now:new Date(now).toISOString()},{...needInput,constraints:{family:"milk",fatPercent:"1.5"}},[]])assert.equal((await post(invalid)).status,400);
   assert.deepEqual((await pool.query("SELECT * FROM hit_price_import_evidence WHERE observation_id=$1",[paidObservation])).rows[0],beforeAtomicLedger,"Need HTTP reads preserve native capture ledger");
   // Explicitly synthetic butter cards admitted by the actual HIT import, joins and HTTP route.
   const butterTime=Date.now(),butterNames=["SYNTHETIC POSTGRES Butter Ungesalzen","SYNTHETIC POSTGRES Butter","SYNTHETIC POSTGRES Butter Gesalzen","SYNTHETIC POSTGRES Buttertoast"],butterCandidates=butterNames.map((headline,index)=>{const number=7301+index,base="4000000"+String(number).padStart(5,"0"),sum=[...base].reduce((total,n,i)=>total+Number(n)*(i%2?3:1),0),butterGtin=base+(10-sum%10)%10,nativeSku=String(number).padStart(18,"0")+"ST";return candidate(butterTime-1000,{headline,overview:"250g Packung",ean:butterGtin,external_id:nativeSku,url:"https://www.hit.de/sortiment/kaese-eier-molkerei/butter-4261339/synthetic-postgres-butter-"+nativeSku});});
   const butterImported=await Import.persist(pool,butterCandidates,{storeProfile,now:butterTime});assert.equal(butterImported.accepted.length,4,JSON.stringify(butterImported));const butterLedgerBefore=(await pool.query("SELECT * FROM "+Import.TABLE+" WHERE observation_id=ANY($1::uuid[]) ORDER BY observation_id",[butterImported.accepted.map(row=>row.observationId)])).rows,allCapturesBefore=await count(pool,Import.TABLE),receiptsBefore=await count(pool,"receipt_submissions");
   const butterInput={search:"Butter",pack:"250 g",scopeChannel:"physical-store",constraints:{family:"butter",salt:"unsalted"}},butterReply=await post(butterInput);assert.equal(butterReply.status,200);assert.equal(butterReply.data.items.length,2);assert.equal(butterReply.data.items[0].gtin,butterCandidates[0].gtin);assert.equal(butterReply.data.items[0].needAssessment.status,"confirmed");assert.equal(butterReply.data.items[1].gtin,butterCandidates[1].gtin);assert.equal(butterReply.data.items[1].needAssessment.status,"unconfirmed");assert(butterReply.data.items[1].needAssessment.offerMatches[0].missing.includes("salt"));assert.equal(butterReply.data.needCoverage.contradictedOffers,2);assert.equal(butterReply.data.needCoverage.complete,false);assert.equal(butterReply.data.selectionRequired,true);assert.equal(butterReply.data.automaticSelection,false);for(const item of butterReply.data.items){assert.equal(item.offers.length,0);assert.equal(item.physicalOffers[0].storeId,storeId);assert.equal(item.physicalOffers[0].scopeChannel,"physical-store");assert.equal(item.physicalOffers[0].payablePackPrice,null);assert.equal(item.physicalOffers[0].proofVerified,false);assert.equal(item.physicalOffers[0].capturedAt,butterCandidates[0].capturedAt);}
   assert.equal((await post({...butterInput,pack:"2 x 125 g"})).data.items.length,0);assert.equal((await post({...butterInput,scopeChannel:"online"})).data.items.length,0);assert.equal((await post({...butterInput,constraints:{family:"butter"}})).data.items.length,3);for(const invalid of[{...butterInput,constraints:{family:"butter",salt:true}},{...butterInput,constraints:{family:"butter",salt:"none"}},{...butterInput,constraints:{family:"butter",composition:"pure"}},{...butterInput,search:"Butter pur"}])assert.equal((await post(invalid)).status,400);
   assert.equal(await count(pool,Import.TABLE),allCapturesBefore);assert.equal(await count(pool,"receipt_submissions"),receiptsBefore);assert.deepEqual((await pool.query("SELECT * FROM "+Import.TABLE+" WHERE observation_id=ANY($1::uuid[]) ORDER BY observation_id",[butterImported.accepted.map(row=>row.observationId)])).rows,butterLedgerBefore,"Butter classification and invalid needs cannot rewrite any real original capture, deposit, ledger signature or price");console.log("butter-shopping-need-postgres: actual import/join/HTTP, literal salt, exact pack, native scope, unconfirmed properties and immutable capture passed");
  }finally{await new Promise((resolve,reject)=>api.server.close(error=>error?reject(error):resolve()));}
  const coverageColumn=(await pool.query("SELECT data_type FROM information_schema.columns WHERE table_name=$1 AND column_name='scan_coverage'",[Refresh.TABLE])).rows[0];assert.equal(coverageColumn.data_type,"jsonb","The persisted category coverage schema is real PostgreSQL DDL");
  console.log("hit-price-postgres tests passed");
 }catch(error){testError=error;throw error}finally{await pool.end();await api.closeDb();if(testError)process.exitCode=1}
}
main().catch(error=>{console.error(error);process.exitCode=1});
