"use strict";
const assert=require("node:assert/strict"),Refresh=require("../hit-price-refresh"),Gap=require("../hit-native-list-gap"),Store=require("../hit-list-gap-store"),Fixture=require("./fixtures/hit-list-gap"),Batches=require("./fixtures/hit-list-gap-refresh");
const NOW=Fixture.NOW,copy=structuredClone,iso=n=>new Date(n).toISOString();let cases=0;
function database(initial={}){
 const db={state:copy(initial),rows:[],calls:[],events:[],insertFault:false,checkpointFault:false,forcedTotals:null};let snapshot;
 db.connect=async()=>({query:db.query,release(){}});
 db.query=async(sql,args=[])=>{
  db.calls.push({sql,args:copy(args)});
  if(sql.includes('AS "eventCount"'))return{rows:[{eventCount:0,blockedGtinCount:0}]};
  if(sql==="BEGIN"){snapshot=copy({state:db.state,rows:db.rows});return{rows:[]};}
  if(sql==="ROLLBACK"){if(snapshot){db.state=snapshot.state;db.rows=snapshot.rows;snapshot=null;}db.events.push("rollback");return{rows:[]};}
  if(sql==="COMMIT"){snapshot=null;db.events.push("commit");return{rows:[]};}
  if(sql.startsWith("SELECT cursor,"))return{rows:Object.keys(db.state).length?[copy(db.state)]:[]};
  if(sql.startsWith('SELECT gap_id AS "gapId"'))return{rows:copy(db.rows.filter(r=>args[2].includes(r.gapId)))};
  if(sql.startsWith('SELECT count(*)::int AS "records"'))return{rows:[db.forcedTotals||{records:db.rows.length,bytes:db.rows.reduce((n,r)=>n+r.recordBytes,0)}]};
  if(sql.startsWith("INSERT INTO "+Store.TABLE)){
   db.rows.push({gapId:args[0],record:JSON.parse(args[3]),capturedAt:args[4],bodyBytes:args[5],recordBytes:args[6]});db.events.push("original-insert");if(db.insertFault)throw Object.assign(Error("synthetic original insert outage"),{code:"22012"});return{rows:[],rowCount:1};
  }
  if(sql.startsWith("INSERT INTO "+Refresh.TABLE)){
   if(args.length===11){db.state={...db.state,cursor:JSON.parse(args[1]),lastCompletedAt:args[2]?args[3]:db.state.lastCompletedAt,completedCycles:(db.state.completedCycles||0)+(args[2]?1:0),nativeTotal:args[4],pagesFetched:args[5],receivedCumulative:args[6],lastError:args[7],retryAfter:args[8],updatedAt:args[3],scanCoverage:JSON.parse(args[9]),ordinaryCycleId:args[10]};db.events.push("checkpoint");if(db.checkpointFault)throw Object.assign(Error("synthetic checkpoint outage"),{code:"22012"});}
   else if(args[6]||iso(Date.parse(db.state.updatedAt))===args[5]){db.state={...db.state,lastError:args[1],retryAfter:iso(Math.max(Date.parse(args[2]),Date.parse(db.state.retryAfter)||0)),cursor:args[4]&&db.state.updatedAt===args[5]?null:db.state.cursor,updatedAt:args[3]};db.events.push("failure");}
   return{rows:[],rowCount:1};
  }
  if(sql.startsWith('SELECT count(*)::int AS "listingGapCapturedCount"'))return{rows:[{listingGapCapturedCount:db.rows.length,listingGaps:db.rows.map(row=>Gap.summarize(row.record,{now:Date.parse(row.record.original.meta.capturedAt)}))}]};
  return{rows:[],rowCount:0};
 };
 return db;
}
const initial=previous=>({cursor:previous,updatedAt:iso(NOW-60000),nativeTotal:previous.total,pagesFetched:previous.pagesFetched,receivedCumulative:previous.received,completedCycles:2});
function run(db,result,now=NOW,deps={}){return Refresh.refresh({pool:db,now:()=>now,maxRequests:3},{collect:async()=>copy(result),quarantine:async()=>0,persist:async()=>{db.events.push("persist");return{accepted:[],duplicates:0,rejected:[],productsCreated:0,storeId:1775};},...deps});}
async function main(){
 const {previous,record,result}=Batches.batch();Refresh.confirmed(result,initial(previous),3,previous.cursorDay);assert.deepEqual(Refresh.confirmedListingGaps(result,initial(previous),NOW),[record]);cases++;
 const mixed=await Batches.mixed();assert.equal(mixed.result.accepted.length,1);Refresh.confirmed(mixed.result,initial(mixed.previous),4,mixed.previous.cursorDay);assert.equal(Refresh.confirmedListingGaps(mixed.result,initial(mixed.previous),mixed.time).length,1);for(const field of["sourceResponseHash","sourceResponseUrl","capturedAt","sourceResponseDate","sourceAgeSeconds"]){const altered=copy(mixed.result);altered.accepted[0][field]=field==="sourceAgeSeconds"?1:"synthetic forged proof";assert.throws(()=>Refresh.confirmedListingGaps(altered,initial(mixed.previous),mixed.time));cases++;}cases++;
 const edits=[r=>r.originalListingGaps=[],r=>r.originalListingGaps.push(record),r=>r.pages[0].diagnosticOnly=false,r=>r.pages[0].gapId="f".repeat(64),r=>r.pages[0].responseBytes++,r=>r.pages[0].storeProfile.storeId=1776,r=>r.pages[0].requestUrl+="?page=1",r=>r.pages[0].uniqueRowCount=1,r=>r.pages[0].accepted=1,r=>r.pages[0].children=["4261911"],r=>r.pages[0].conflictGtins=[Fixture.row(1).ean],r=>r.error.retryAfterMs=3599999,r=>r.error.code="hit-source-http-429",r=>r.nativePaginationComplete=true,r=>r.physicalStoreAssortmentComplete=true,r=>r.cursor.visited.at(-1).gapId="f".repeat(64),r=>r.cursor.visited.at(-1).unresolved=false,r=>r.cursor.visited.at(-1).children=["4261911"],r=>r.accepted=[{sourceResponseHash:record.original.meta.sourceResponseHash,sourceResponseUrl:record.original.meta.sourceResponseUrl}]];
 for(const edit of edits){const bad=copy(result);edit(bad);assert.throws(()=>Refresh.confirmedListingGaps(bad,initial(previous),NOW));cases++;}
 assert.throws(()=>Refresh.confirmedListingGaps(copy(result),{cursor:Fixture.cursor([Fixture.node("4261911")])},NOW),/pending-unconfirmed/);cases++;
 for(const edit of[r=>r.cursor.pending=[],r=>r.cursor.seenSkus=[Fixture.sku(1)],r=>r.cursor.visited[0].url="https://www.hit.de/sortiment/changed-overview"]){const bad=copy(result);edit(bad);assert.throws(()=>Refresh.confirmedListingGaps(bad,initial(previous),NOW));cases++;}
 for(const edit of[r=>r.cursor.pending=[],r=>r.cursor.seenSkus[0]=Fixture.sku(1),r=>r.cursor.seenSkus[1]=Fixture.sku(1),r=>r.cursor.seenQuotes={},r=>r.pages[0].nativeSkuIds=[Fixture.sku(1)],r=>r.pages[0].nativeQuotes=[]]){const bad=copy(mixed.result);edit(bad);assert.throws(()=>Refresh.confirmedListingGaps(bad,initial(mixed.previous),mixed.time));cases++;}
 for(const edit of[r=>r.categoryCoverage.unresolvedNodes=[],r=>{r.total=999;r.cursor.total=999;},r=>r.cursor.overviewLoaded=false,r=>r.cursor.initialIndexLoaded=false]){const bad=copy(mixed.result);edit(bad);assert.throws(()=>Refresh.confirmedListingGaps(bad,initial(mixed.previous),mixed.time));cases++;}
 const db=database(initial(previous));await assert.rejects(run(db,result),e=>e.code===Gap.CODE&&e.checkpointSaved&&e.partialResult.isolatedListingGapCount===1);assert.equal(db.rows.length,1);assert.deepEqual(db.state.cursor,result.cursor);assert.equal(db.state.retryAfter,iso(NOW+3600000));assert.equal(db.state.completedCycles,2);assert(db.events.indexOf("original-insert")<db.events.lastIndexOf("commit"));assert.equal((await run(db,null,NOW+3599999,{collect:async()=>{throw Error("cooldown must not request");}})).skipped,"source-cooldown");cases++;
 const archived=await Store.originals(db,[record.id]);assert.deepEqual(archived,[record]);const same=await Store.persist(db,[copy(record)],{now:NOW});assert.equal(same.inserted,0);assert.equal(db.rows.length,1);cases++;
 for(const field of["recordBytes","bodyBytes","capturedAt"]){const before=copy(db.rows);db.rows[0][field]=field==="capturedAt"?iso(NOW+1):db.rows[0][field]+1;await assert.rejects(Store.originals(db,[record.id]),/conflict/);db.rows=before;cases++;}
 const reordered=copy(db.rows[0].record);db.rows[0].record=Object.fromEntries(Object.entries(reordered).reverse());assert.deepEqual(await Store.originals(db,[record.id]),[record],"JSONB key reordering is canonicalized before byte checks");cases++;
 for(const fault of["insertFault","checkpointFault"]){const failed=database(initial(previous));failed[fault]=true;await assert.rejects(run(failed,result),e=>e.code==="22012");assert.equal(failed.rows.length,0);assert.deepEqual(failed.state.cursor,previous);assert.equal(failed.state.pagesFetched,1);assert.equal(failed.state.retryAfter,iso(NOW+3600000));assert(failed.events.includes("rollback"));cases++;}
 for(const forcedTotals of[{records:32,bytes:0},{records:0,bytes:Store.MAX_RECORD_BYTES},{records:-1,bytes:0},{records:0,bytes:"not-a-number"}]){const bounded=database(initial(previous));bounded.forcedTotals=forcedTotals;await assert.rejects(run(bounded,result),e=>e.code==="hit-list-gap-original-ledger-bound");assert.equal(bounded.rows.length,0);assert.deepEqual(bounded.state.cursor,previous);cases++;}
 const stale=database(initial(previous)),newer=copy(previous);newer.pending.reverse();const staleResult=await run(stale,result,NOW,{collect:async()=>{stale.state.cursor=newer;stale.state.updatedAt=iso(NOW-1);return copy(result);}});assert.equal(staleResult.skipped,"checkpoint-changed");assert.equal(stale.rows.length,0);assert.deepEqual(stale.state.cursor,newer);assert.equal(stale.state.retryAfter,iso(NOW+3600000));assert.equal(staleResult.nextAttemptAt,stale.state.retryAfter);cases++;
 const terminalBatch=Batches.batch(NOW,{terminal:true}),terminal=database(initial(terminalBatch.previous));await assert.rejects(run(terminal,terminalBatch.result),e=>e.code===Gap.CODE&&e.checkpointSaved);const originalRows=copy(terminal.rows),calls=terminal.calls.length;const done=await run(terminal,null,NOW+3600000,{collect:async()=>{throw Error("terminal must not fetch");},persist:async()=>{throw Error("terminal must not import or renew prices");},quarantine:async()=>{throw Error("terminal must not re-quarantine prices");}});assert.equal(done.requests,0);assert.equal(done.terminalOnly,true);assert.equal(done.accepted,0);assert.equal(done.nativePaginationComplete,false);assert.equal(done.publishedTraversalComplete,false);assert.equal(done.physicalStoreAssortmentComplete,false);assert.equal(done.categoryTraversalCycleComplete,true);assert.equal(terminal.state.cursor,null);assert.equal(terminal.state.completedCycles,3);assert.deepEqual(terminal.rows,originalRows);assert(terminal.calls.slice(calls).some(c=>c.sql.startsWith('SELECT gap_id AS "gapId"')));cases++;
 const missing=database(initial(terminalBatch.previous));await assert.rejects(run(missing,terminalBatch.result),e=>e.checkpointSaved);missing.rows=[];await assert.rejects(run(missing,null,NOW+3600000,{collect:async()=>{throw Error("no missing-proof fetch");}}),/stored-original-required/);assert.notEqual(missing.state.cursor,null);assert.equal(missing.state.completedCycles,2);cases++;
 const recovery=database(initial(terminalBatch.previous));await assert.rejects(run(recovery,terminalBatch.result),e=>e.checkpointSaved);recovery.checkpointFault=true;await assert.rejects(run(recovery,null,NOW+3600000,{collect:async()=>{throw Error("no terminal source request");}}),e=>e.code==="22012");assert.deepEqual(recovery.state.cursor,terminalBatch.result.cursor);assert.equal(recovery.state.lastError,"22012");recovery.checkpointFault=false;assert.equal((await run(recovery,null,NOW+7200000,{collect:async()=>{throw Error("terminal retry must not fetch");}})).requests,0);assert.equal(recovery.state.cursor,null);cases++;
 const publicState=await Refresh.status(db),json=JSON.stringify(publicState);assert.equal(publicState.listingGapCapturedCount,1);assert.equal(publicState.hasContinuation,true);assert.equal(publicState.publishedTraversalComplete,false);for(const forbidden of[record.original.body,Fixture.sku(1),'"original":','"body":','"invalidSkuIndexes":','"duplicates":','"seenSkus":','"seenQuotes":'])assert(!json.includes(forbidden));cases++;
 assert.throws(()=>Store.ids({visited:[{quarantinedListing:true,gapId:"bad"}]}));await assert.rejects(Store.originals(db,[record.id,record.id]));cases++;
 console.log("hit-list-gap-refresh: "+cases+" cases OK (synthetic; no source requests)");
}
main().catch(error=>{console.error(error);process.exitCode=1});
