"use strict";
const assert=require("node:assert/strict"),crypto=require("node:crypto"),Refresh=require("../hit-price-refresh"),Collector=require("../hit-assortment-collector"),Client=require("../hit-assortment-client"),Import=require("../hit-price-import"),Clock=require("../current-price-query-service"),Cycle=require("../hit-refresh-cycle");
const CYCLE_A="9e6605b8-1d77-4bbf-92b8-c9d4ce63feb8",CYCLE_B="3ff95695-3d53-4c2b-91b9-ae05f9db8a41";
const BrandFixture=require("./fixtures/hit-brand-probe");
const NOW=Date.parse("2026-10-01T20:10:15.527Z"),copy=structuredClone,iso=time=>new Date(time).toISOString(),sku=n=>String(n).padStart(18,"0")+"ST",originalNow=Date.now;
let wall=NOW;Date.now=()=>wall;
function gtin(n){const body="400000"+String(n).padStart(6,"0");let sum=0;for(let i=0;i<body.length;i++)sum+=Number(body[i])*(i%2?3:1);return body+String((10-sum%10)%10)}
function node(index,total=5,limit=2){return{id:String(4261890+index),name:"Native Kategorie "+index,url:"https://www.hit.de/sortiment/kategorie-"+(4261890+index),level:1,count:Math.min(limit,total-index*limit),order:index,parentId:null,observedChildIds:[],evidence:"native-assortment-filters"}}
function cursor(pages,total=5,limit=2,time=wall){
 const received=Math.min(pages*limit,total),seenQuotes={},count=Math.ceil(total/limit),pending=pages?Array.from({length:Math.max(0,count-pages)},(_,i)=>node(pages+i,total,limit)):[],visited=Array.from({length:pages},(_,i)=>({id:i?node(i,total,limit).id:null,url:i?node(i,total,limit).url:"https://www.hit.de/sortiment/uebersicht",level:i?1:null,total:i?Math.min(limit,total-i*limit):total,rowCount:Math.min(limit,total-i*limit),uniqueRowCount:Math.min(limit,total-i*limit),children:i?[]:Array.from({length:Math.max(0,count-1)},(_,n)=>node(n+1,total,limit).id),truncated:false,unresolved:false}));
 for(let id=1;id<=received;id++)seenQuotes[gtin(id)+"|g|500|1"]={gtin:gtin(id),signature:crypto.createHash("sha256").update(JSON.stringify(["Standardprodukt "+id,125,null,"standard"])).digest("hex")};
 return{version:2,cursorDay:Clock.today(new Date(time)),nativeStoreId:1775,nativeStoreNumber:"258",total:pages?total:null,pagesFetched:pages,received,initialIndexLoaded:true,overviewLoaded:pages>0,pending,visited,seenSkus:Array.from({length:received},(_,i)=>sku(i+1)),seenQuotes,categoryCoverage:{visited:pages,pending:pending.length,truncatedLeaves:[],unresolvedNodes:[]}};
}
function batch(start=0,count=1,{total=5,limit=2,time=wall,error=null,rejectedIds=[],requests=3+count}={}){
 const pages=[],accepted=[],rejected=[];
 for(let page=start;page<start+count;page++){
  const rowCount=Math.min(limit,total-page*limit),ids=Array.from({length:rowCount},(_,i)=>page*limit+i+1),sourceResponseUrl=page?node(page,total,limit).url:"https://www.hit.de/sortiment/uebersicht",sourceResponseHash=crypto.createHash("sha256").update("actual-test-page-"+page).digest("hex");
  const meta={storeProfile:Import.STORE_PROFILE,capturedAt:iso(time),responseDate:new Date(time).toUTCString(),responseAgeSeconds:0,sourceResponseHash,sourceResponseUrl};
  let pageAccepted=0,pageRejected=0;
  for(const id of ids){if(rejectedIds.includes(id)){rejected.push({retailerSku:sku(id),reasons:["hit-unconditional-normal-price-tag-required"]});pageRejected++;continue}
   const raw={external_id:sku(id),ean:gtin(id),storeId:1775,storeNumber:"258",headline:"Standardprodukt "+id,overview:"500g Beutel",price:"1.25",deposit:null,url:"https://www.hit.de/sortiment/vorraete/standardprodukt-"+sku(id),priceTag:{type:"standard",badgeText:null,priceEuro:"1",priceCent:"25"}};
   const parsed=Client.parseRow(raw,meta);assert.equal(parsed.ok,true,JSON.stringify(parsed));accepted.push(parsed.candidate);pageAccepted++;
  }
  pages.push({...meta,rowCount,uniqueRowCount:rowCount,categoryId:page?node(page,total,limit).id:null,children:page?[]:Array.from({length:Math.max(0,Math.ceil(total/limit)-1)},(_,i)=>node(i+1,total,limit).id),truncated:false,accepted:pageAccepted,rejected:pageRejected,pagination:{page:0,limit,total:page?rowCount:total}});
 }
 const end=start+count,state=cursor(end,total,limit,time),complete=!error&&state.received===total;for(const id of rejectedIds)delete state.seenQuotes[gtin(id)+"|g|500|1"];
 return{sourceId:Refresh.SOURCE,cursorDay:state.cursorDay,accepted,rejected,pages,requests,complete,categoryTraversalCycleComplete:complete,nativePaginationComplete:complete,publishedTraversalComplete:complete,categoryCoverage:state.categoryCoverage,physicalStoreAssortmentComplete:false,cursor:complete?null:state,total:count||start?total:null,pagesFetched:end,received:state.received,error};
}
function database(initial={}){
 const state=copy(initial),calls=[],events=[];
 return{state,calls,events,probeRecord:null,failCheckpoint:false,query:async function(sql,params=[]){
  calls.push({sql,params:copy(params)});
  if(sql.startsWith("SELECT cursor"))return{rows:Object.keys(state).length?[copy(state)]:[]};
  if(sql.startsWith("INSERT INTO "+Refresh.TABLE)&&params.length===7){events.push("failure-checkpoint");Object.assign(state,{lastError:params[1],retryAfter:params[2],updatedAt:params[3]});if(params[4])state.cursor=null;return{rows:[],rowCount:1};}
  if(sql.startsWith("INSERT INTO "+Refresh.TABLE)){events.push("progress-checkpoint");if(this.failCheckpoint)throw Error("checkpoint-write-failed");Object.assign(state,{cursor:JSON.parse(params[1]),lastCompletedAt:params[2]?params[3]:state.lastCompletedAt??null,completedCycles:(state.completedCycles||0)+(params[2]?1:0),nativeTotal:params[4],pagesFetched:params[5],receivedCumulative:params[6],lastError:params[7],retryAfter:params[8],scanCoverage:JSON.parse(params[9]),ordinaryCycleId:params[10],updatedAt:params[3]});return{rows:[],rowCount:1};}
  if(sql.startsWith("UPDATE "+Refresh.TABLE+" SET brand_filter_probe=")){events.push("brand-probe");if(state.brandFilterProbeAttempted)return{rows:[],rowCount:0};this.probeRecord=JSON.parse(params[1]);state.brandFilterProbeAttempted=true;state.brandFilterProbe={attempted:true,outcome:this.probeRecord.outcome,actualHTMLFilterVerified:this.probeRecord.actualHTMLFilterVerified,collectionEnabled:false,priceImportEnabled:false,complete:false};return{rows:[],rowCount:1};}
  if(sql.startsWith("UPDATE price_observations po SET truth_eligible=false,status='conflicting-source'")){events.push("invalidate-conflict");state.invalidatedGtins=copy(params[4]);return{rows:[],rowCount:params[4].length};}
  if(sql.includes('AS "historicalProducts"'))return{rows:[{historicalProducts:4,historicalCaptures:6,currentProducts:3,currentPrices:3,unknownDepositPrices:1}]};
  return{rows:[],rowCount:0};
 }};
}
const save=pool=>async(_pool,offers)=>{assert.equal(_pool,pool);pool.events.push("persist");return{accepted:offers.map((_,i)=>({id:"observation-"+i})),duplicates:0,rejected:[],productsCreated:offers.length,storeId:"native-store-test"}};
async function run(pool,result,{time=wall,maxRequests=8,persist=save(pool),collect}={}){
 wall=time;return Refresh.refresh({pool,maxRequests,now:()=>wall},{collect:collect||(async options=>{assert.equal(options.brandProbeEnabled,!pool.state.brandFilterProbeAttempted);assert.equal(options.maxRequests,Math.min(16,Math.max(1,maxRequests)));assert.deepEqual(options.storeProfile,Import.STORE_PROFILE);assert.equal(options.cursorDay,Clock.today(new Date(wall)));const prior=pool.state.cursor,legacy=prior?.version===1||prior?.version===2&&!Object.hasOwn(prior,"cursorDay"),rollover=prior&&Collector.validDay(prior.cursorDay)&&prior.cursorDay!==options.cursorDay;assert.deepEqual(options.cursor,legacy||rollover?null:prior||null);return copy(result)}),persist});
}
function probeBatch(time,{refused=false,inconclusive=false}={}){
 const probe=BrandFixture.record({now:time-1000,...(refused?{outcome:"source-refused",status:429}:{}),...(inconclusive?{filtered:{edit:(_data,params)=>{delete params.for_brands}}}:{})}),result=batch(0,1,{total:3,limit:3,time:time-1000,requests:5});
 result.accepted=[];result.rejected=probe.control.skuIds.map(retailerSku=>({retailerSku,reasons:["synthetic-diagnostic-fixture-without-prices"]}));result.pages[0]={...result.pages[0],...probe.control.meta,categoryId:probe.category.id,children:[],pagination:{page:0,limit:40,total:3},accepted:0,rejected:3};result.brandFilterProbe=probe;
 if(refused){result.error=copy(probe.error);result.complete=false;result.nativePaginationComplete=false;result.publishedTraversalComplete=false;result.categoryTraversalCycleComplete=false;result.cursor=cursor(1,3,3,time-1000);result.cursor.visited[0]={...result.cursor.visited[0],id:probe.category.id,url:probe.control.meta.sourceResponseUrl,total:3};result.cursor.seenQuotes={};}
 return result;
}
async function main(){
 wall=NOW;const probePool=database(),probeResult=probeBatch(wall);const probeSaved=await run(probePool,probeResult);assert.equal(probeSaved.accepted,0);assert.deepEqual(probePool.events,["persist","progress-checkpoint","brand-probe"]);assert.equal(probePool.probeRecord.outcome,"confirmed");assert.equal(probePool.probeRecord.priceImportEnabled,false);assert.equal(probePool.probeRecord.control.body,probeResult.brandFilterProbe.control.body);assert.equal(probePool.probeRecord.filtered.body,probeResult.brandFilterProbe.filtered.body);assert.equal(probeSaved.receivedCumulative,3,"Only ordinary control traversal contributes rows; two filtered SKUs are not added");
 const storedProbe=copy(probePool.probeRecord);wall=NOW+900001;await run(probePool,batch(0,1,{time:wall}));assert.deepEqual(probePool.probeRecord,storedProbe);assert.equal(probePool.events.filter(e=>e==="brand-probe").length,1,"Later cycles cannot repeat or replace an attempted diagnostic");
 const missing=probeBatch(NOW);missing.pages[0].sourceResponseHash="b".repeat(64);assert.throws(()=>Refresh.confirmedBrandProbe(missing,{},NOW),/control-not-in-batch/);const wrongCounts=probeBatch(NOW);wrongCounts.pages[0].pagination.total=4;assert.throws(()=>Refresh.confirmedBrandProbe(wrongCounts,{},NOW),/control-not-in-batch/);assert.throws(()=>Refresh.confirmedBrandProbe(probeResult,{brandFilterProbeAttempted:true},NOW),/already-attempted/);
 for(const patch of[{responseDate:new Date(NOW).toUTCString()},{responseAgeSeconds:1}]){const alteredHeaders=probeBatch(NOW);Object.assign(alteredHeaders.pages[0],patch);assert.throws(()=>Refresh.confirmedBrandProbe(alteredHeaders,{},NOW),/control-not-in-batch/,"Recorded control Date and Age must be the actual processed page values");}
 for(const retryAfterMs of[3600000,undefined,NaN,"broken","7200000",Infinity,-1]){const boundedRefusal=probeBatch(NOW,{refused:true});boundedRefusal.error.retryAfterMs=retryAfterMs;assert.throws(()=>Refresh.confirmedBrandProbe(boundedRefusal,{},NOW),/source-refusal-unconfirmed/,"A malformed/missing delay cannot shorten an observed two-hour native pause");}const refusalDb=database();await assert.rejects(run(refusalDb,probeBatch(NOW,{refused:true}),{time:NOW}),e=>e.code==="hit-source-http-429"&&e.checkpointSaved===true);assert.equal(refusalDb.state.retryAfter,iso(NOW+7200000));assert.equal(refusalDb.probeRecord.outcome,"source-refused");assert.equal(refusalDb.state.cursor.visited.length,1);assert.equal(refusalDb.state.cursor.pending.length,0);
 const ignoredDb=database();await run(ignoredDb,probeBatch(NOW,{inconclusive:true}),{time:NOW});assert.equal(ignoredDb.probeRecord.outcome,"inconclusive");assert.equal(ignoredDb.probeRecord.actualHTMLFilterVerified,false);assert.equal(ignoredDb.state.lastError,null);
 const initial=Date.parse(Collector.COOLDOWN_UNTIL),before=database();wall=initial-1;let collected=0;
 const held=await Refresh.refresh({pool:before,now:()=>wall},{collect:async()=>{collected++;throw Error("unexpected-network")},persist:save(before)});assert.equal(held.skipped,"source-cooldown");assert.equal(held.nextAttemptAt,Collector.COOLDOWN_UNTIL);assert.equal(collected,0);assert.deepEqual(before.state,{});assert.equal(await Refresh.resumeAt(before,wall),Collector.COOLDOWN_UNTIL);
 const delayed=database({cursor:cursor(1),updatedAt:new Date(NOW-60000),retryAfter:new Date(NOW+12345)});const heldAgain=await run(delayed,null,{time:NOW,collect:async()=>{throw Error("unexpected-network")}});assert.equal(heldAgain.skipped,"source-cooldown");assert.equal(heldAgain.nextAttemptAt,iso(NOW+12345),"PG Date objects preserve retry milliseconds");
 const due=database({cursor:cursor(1),updatedAt:new Date(NOW),retryAfter:null});assert.equal(await Refresh.resumeAt(due,NOW),iso(NOW+60000),"PG Date objects preserve continuation milliseconds");
 const old=database({cursor:null,updatedAt:new Date(NOW),lastCompletedAt:new Date(NOW-1000),completedCycles:2});assert.equal(await Refresh.resumeAt(old,NOW),iso(NOW+900000));
 const legacy=database({cursor:{version:1,nextPage:50},scanCoverage:{nativePaginationComplete:true},updatedAt:new Date(NOW-60000),retryAfter:new Date(NOW+54321),pagesFetched:50,receivedCumulative:2000}),legacyOriginal=copy(legacy.state);assert.equal((await run(legacy,null,{time:NOW,collect:async()=>{throw Error("unexpected-network")}})).nextAttemptAt,iso(NOW+54321));assert.deepEqual(legacy.state,legacyOriginal,"Legacy pagination migration preserves the saved source cooldown without a write");const migrated=await run(legacy,batch(0,1,{time:NOW+54321}),{time:NOW+54321});assert.equal(migrated.pagesFetched,1);assert.equal(legacy.state.cursor.version,2);assert(Cycle.validId(legacy.state.ordinaryCycleId),"Legacy adoption receives a durable generation without renewing historical captures");assert.equal(legacy.state.receivedCumulative,2);assert.equal(legacy.state.scanCoverage.nativePaginationComplete,false);
 wall=NOW;const oldV2=cursor(1);delete oldV2.cursorDay;const noDay=database({cursor:oldV2,scanCoverage:{nativePaginationComplete:true},updatedAt:iso(NOW-60000),retryAfter:iso(NOW+60000),pagesFetched:1,receivedCumulative:2}),oldV2State=copy(noDay.state);assert.equal((await run(noDay,null,{time:NOW,collect:async()=>assert.fail("Legacy migration cannot bypass cooldown")})).skipped,"source-cooldown");assert.deepEqual(noDay.state,oldV2State);wall=NOW+60000;const marked=await run(noDay,batch(0,1,{time:wall}),{time:wall});assert.equal(marked.pagesFetched,1);assert.equal(noDay.state.cursor.cursorDay,"2026-10-01");assert.equal(noDay.state.scanCoverage.nativePaginationComplete,false);
 const midnight=Date.parse("2026-10-01T22:00:01.000Z"),previousDay=cursor(1,5,2,NOW),dayPool=database({cursor:previousDay,ordinaryCycleId:CYCLE_A,updatedAt:iso(midnight-120000),pagesFetched:1,receivedCumulative:2,completedCycles:3,lastCompletedAt:iso(NOW-86400000)});wall=midnight;let freshCards;
 const dayResult=await run(dayPool,batch(0,1,{time:midnight}),{persist:async(pool,offers)=>{freshCards=copy(offers);return save(dayPool)(pool,offers)}});assert.equal(dayResult.dailyCycleReset,true);assert.equal(dayResult.cursorDay,"2026-10-02");assert.equal(dayResult.pagesFetched,1,"Rollover confirmation uses the same zero baseline passed to the collector");assert.equal(dayResult.receivedCumulative,2);assert.equal(dayResult.accepted,2);assert(freshCards.every(c=>c.capturedAt===iso(midnight)));assert.equal(dayPool.state.completedCycles,3);assert(Cycle.validId(dayPool.state.ordinaryCycleId));assert.notEqual(dayPool.state.ordinaryCycleId,CYCLE_A,"Berlin day reset starts a distinct durable traversal generation");assert.equal(dayPool.state.cursor.cursorDay,"2026-10-02");assert.deepEqual(dayPool.events,["persist","progress-checkpoint"]);assert.deepEqual(previousDay,cursor(1,5,2,NOW),"The earlier cursor and its evidence are never retimestamped");
 const midnightHeld=database({cursor:cursor(1,5,2,NOW),updatedAt:iso(midnight-60000),retryAfter:iso(midnight+3600000)}),heldSnapshot=copy(midnightHeld.state);assert.equal((await run(midnightHeld,null,{time:midnight,collect:async()=>assert.fail("Day rollover cannot bypass source Retry-After")})).nextAttemptAt,iso(midnight+3600000));assert.deepEqual(midnightHeld.state,heldSnapshot);
 const dayFailure=database({cursor:cursor(1,5,2,NOW),updatedAt:iso(midnight-120000),pagesFetched:1,receivedCumulative:2}),failureSnapshot=copy(dayFailure.state);wall=midnight;await assert.rejects(run(dayFailure,batch(0,1,{time:midnight}),{persist:async()=>{throw Object.assign(Error("new day admission failed"),{code:"XX000"})}}),e=>e.code==="XX000");assert.deepEqual(dayFailure.state.cursor,failureSnapshot.cursor);assert.equal(dayFailure.state.pagesFetched,1);assert(!dayFailure.events.includes("progress-checkpoint"));assert.equal(dayFailure.state.retryAfter,iso(midnight+3600000));
 wall=midnight+86400000;const after24h=await run(dayPool,batch(0,1,{time:wall}),{time:wall});assert.equal(after24h.dailyCycleReset,true);assert.equal(after24h.cursorDay,"2026-10-03");assert.equal(after24h.accepted,2);assert.equal(after24h.pagesFetched,1);
 wall=NOW;const pool=database(),first=batch();const output=await run(pool,first);assert.deepEqual(pool.events,["persist","progress-checkpoint"]);assert.equal(output.accepted,2);assert.equal(output.received,2);assert.equal(output.requests,4);assert.equal(output.pagesFetched,1);assert.equal(output.receivedCumulative,2);assert.equal(output.nativeTotal,5);assert.equal(output.publishedTraversalComplete,false);assert.equal(output.physicalStoreAssortmentComplete,false);assert.equal(pool.state.cursor.pagesFetched,1);assert.deepEqual(pool.state.cursor.seenSkus,[sku(1),sku(2)]);assert.equal(pool.state.completedCycles,0);assert(Cycle.validId(pool.state.ordinaryCycleId));const firstCycleId=pool.state.ordinaryCycleId;assert(!Object.hasOwn(output,"ordinaryCycleId"));assert.equal(pool.state.lastCompletedAt,null);assert.equal(pool.state.lastError,null);assert.equal(output.nextAttemptAt,iso(NOW+60000));
 const unchanged=copy(pool.state);const paused=await run(pool,null,{time:NOW+59999,collect:async()=>{throw Error("unexpected-network")}});assert.equal(paused.skipped,"source-cooldown");assert.deepEqual(pool.state,unchanged);
 const stamp=NOW+60000;wall=stamp;const remainder=batch(1,2,{time:stamp});const finished=await run(pool,remainder,{time:stamp});assert.equal(finished.accepted,3);assert.equal(finished.publishedTraversalComplete,true);assert.equal(finished.physicalStoreAssortmentComplete,false);assert.equal(pool.state.cursor,null);assert.equal(pool.state.completedCycles,1);assert.equal(pool.state.ordinaryCycleId,firstCycleId,"Completion preserves the generation of its actual final normal pages");assert.equal(pool.state.lastCompletedAt,iso(stamp));assert.equal(pool.state.receivedCumulative,5);assert.equal(finished.nextAttemptAt,iso(stamp+900000));const status=await Refresh.status(pool);assert.equal(status.publishedTraversalComplete,true);assert.equal(status.physicalStoreAssortmentComplete,false);assert.equal(status.currentPrices,3);assert.equal(status.city,"Berlin");
 assert.equal(status.captureValidity,"original-capture-24-hours");assert(!Object.hasOwn(status,"ordinaryCycleId"));assert(!JSON.stringify(status).includes(firstCycleId),"The durable cycle ID remains private");const countSql=pool.calls.find(c=>c.sql.includes('AS "historicalProducts"')).sql;for(const guard of["po.valid_from<=$2::date","po.valid_to>=$2::date","e.expires_at>statement_timestamp()","e.captured_at>statement_timestamp()-interval '24 hours'","e.captured_at<=statement_timestamp()","e.expires_at=e.captured_at+interval '24 hours'","po.observed_at=e.captured_at","po.truth_eligible=true","po.source_id=e.source_id","po.store_id=e.store_id"])assert(countSql.includes(guard),"Current counts retain the original expiry boundary: "+guard);
 const restart=database(copy(pool.state));const waiting=await run(restart,null,{time:stamp+899999,collect:async()=>{throw Error("unexpected-network")}});assert.equal(waiting.skipped,"source-cooldown");wall=stamp+900000;const newCycle=await run(restart,batch(0,1,{time:wall}),{time:wall});assert.equal(newCycle.pagesFetched,1);assert.equal(restart.state.completedCycles,1);assert(Cycle.validId(restart.state.ordinaryCycleId));assert.notEqual(restart.state.ordinaryCycleId,firstCycleId,"A new same-day traversal cannot alias the completed generation");assert.equal(restart.state.cursor.pagesFetched,1);
 wall=NOW;const failing=database({cursor:cursor(1),updatedAt:iso(NOW-60000),nativeTotal:5,pagesFetched:1,receivedCumulative:2}),beforeFailure=copy(failing.state);
 await assert.rejects(run(failing,batch(1,1),{persist:async()=>{failing.events.push("persist-failed");throw Object.assign(Error("actual SQL write failed"),{code:"XX000"})}}),error=>error.code==="XX000");assert.deepEqual(failing.state.cursor,beforeFailure.cursor);assert.equal(failing.state.pagesFetched,1);assert.equal(failing.state.receivedCumulative,2);assert.equal(failing.state.lastError,"XX000");assert.equal(failing.state.retryAfter,iso(NOW+3600000));assert(!failing.events.includes("progress-checkpoint"),"DB admission failure never advances traversal");
 const checkpoint=database();checkpoint.failCheckpoint=true;await assert.rejects(run(checkpoint,batch()),/checkpoint-write-failed/);assert.deepEqual(checkpoint.events,["persist","progress-checkpoint","failure-checkpoint"]);assert.equal(checkpoint.state.cursor,undefined,"A failed checkpoint cannot advance the durable cursor");
 const partialPool=database();let partial;
 await assert.rejects(run(partialPool,batch(0,1,{error:{code:"hit-source-http-403",retryAfterMs:3600000},requests:5})),error=>{partial=error;return error.code==="hit-source-http-403"});assert.equal(partial.checkpointSaved,true);assert.equal(partial.partialResult.accepted,2);assert.equal(partial.partialResult.physicalStoreAssortmentComplete,false);assert.deepEqual(partialPool.events,["persist","progress-checkpoint"]);assert.equal(partialPool.state.cursor.pagesFetched,1);assert.deepEqual(partialPool.state.cursor.seenSkus,[sku(1),sku(2)]);assert.equal(partialPool.state.lastError,"hit-source-http-403");assert.equal(partialPool.state.retryAfter,iso(NOW+3600000));assert.equal(partialPool.state.lastCompletedAt,null);assert.equal(partialPool.state.completedCycles,0);
 const survived=copy(partialPool.state);assert.equal((await run(partialPool,null,{time:NOW+3599999,collect:async()=>{throw Error("unexpected-network")}})).skipped,"source-cooldown");assert.deepEqual(partialPool.state,survived);wall=NOW+3600000;const recovered=await run(partialPool,batch(1,1,{time:wall}),{time:wall});assert.equal(recovered.accepted,2);assert.equal(partialPool.state.lastError,null);assert.equal(partialPool.state.retryAfter,null);assert.equal(partialPool.state.cursor.pagesFetched,2);
 wall=NOW;const overlapping=database({cursor:cursor(1),updatedAt:iso(NOW-60000)}),overlapBatch=batch(1,1),priorSeen=copy(overlapping.state.cursor);overlapBatch.accepted=[];overlapBatch.pages[0].uniqueRowCount=0;overlapBatch.received=2;overlapBatch.cursor.received=2;overlapBatch.cursor.seenSkus=priorSeen.seenSkus;overlapBatch.cursor.seenQuotes=priorSeen.seenQuotes;overlapBatch.cursor.visited[1].uniqueRowCount=0;let savedOverlap;const overlap=await run(overlapping,overlapBatch,{persist:async(_pool,quotes)=>{savedOverlap=quotes;return save(overlapping)(_pool,quotes)}});assert.deepEqual(savedOverlap,[]);assert.equal(overlap.accepted,0);assert.equal(overlap.receivedCumulative,2);assert.equal(overlapping.state.cursor.pagesFetched,2,"Overlapping categories advance category traversal without inventing new SKUs or renewing duplicated quotes");assert.deepEqual(overlapping.state.cursor.seenSkus,[sku(1),sku(2)]);
 wall=NOW;const retry429=database({cursor:cursor(1),ordinaryCycleId:CYCLE_A,updatedAt:iso(NOW-60000)}),nativeCursor=copy(retry429.state.cursor);await assert.rejects(run(retry429,null,{collect:async()=>{throw Object.assign(Error("blocked"),{code:"hit-source-http-429"})}}),error=>error.code==="hit-source-http-429");assert.deepEqual(retry429.state.cursor,nativeCursor);assert.equal(retry429.state.retryAfter,iso(NOW+3600000));assert.equal(retry429.state.ordinaryCycleId,CYCLE_A,"Native source refusal cannot rotate a continuing traversal");assert(!retry429.events.includes("persist"));
 for(const code of["hit-native-pagination-count-drift","hit-native-pagination-repeated-sku","hit-native-list-duplicate-or-invalid-sku"]){
  const state=database({cursor:cursor(1),ordinaryCycleId:CYCLE_A,updatedAt:iso(NOW-60000),lastCompletedAt:iso(NOW-86400000),completedCycles:2,nativeTotal:5,pagesFetched:1,receivedCumulative:2});let problem;
  await assert.rejects(run(state,batch(1,1,{error:{code,retryAfterMs:3600000},requests:5})),error=>{problem=error;return error.code===code});assert.equal(problem.partialResult.accepted,2,"Valid prices from earlier pages survive later catalog drift");assert.deepEqual(state.events,["persist","progress-checkpoint"]);assert.equal(state.state.cursor,null,"Drift or repeated SKU starts a new cycle after cooldown");assert.equal(state.state.ordinaryCycleId,CYCLE_A,"The partial checkpoint retains its actual original generation");assert.equal(state.state.completedCycles,2);assert.equal(state.state.lastCompletedAt,iso(NOW-86400000));assert.equal(state.state.retryAfter,iso(NOW+3600000));wall=NOW+3600000;const resumed=await run(state,batch(0,1,{time:wall}),{time:wall});assert.equal(resumed.pagesFetched,1);assert.equal(state.state.cursor.pagesFetched,1);assert(Cycle.validId(state.state.ordinaryCycleId));assert.notEqual(state.state.ordinaryCycleId,CYCLE_A,"Same-day reset receives a fresh generation only for the new traversal");wall=NOW;
 }
 const allRejected=database();const filtered=await run(allRejected,batch(0,1,{total:2,rejectedIds:[1,2]}));assert.equal(filtered.accepted,0);assert.equal(filtered.sourceRejected,2);assert.equal(filtered.publishedTraversalComplete,true,"Published row traversal does not claim physical/price completeness");assert.equal(filtered.physicalStoreAssortmentComplete,false);
 const truncated=database(),truncatedBatch=batch(0,1);truncatedBatch.complete=true;truncatedBatch.categoryTraversalCycleComplete=true;truncatedBatch.cursor=null;truncatedBatch.nativePaginationComplete=false;truncatedBatch.publishedTraversalComplete=false;truncatedBatch.pages[0].children=[];truncatedBatch.pages[0].truncated=true;truncatedBatch.categoryCoverage={visited:1,pending:0,truncatedLeaves:[{id:null,url:"https://www.hit.de/sortiment/uebersicht",total:5,received:2}],unresolvedNodes:[]};const categoryDone=await run(truncated,truncatedBatch);assert.equal(categoryDone.categoryTraversalCycleComplete,true);assert.equal(categoryDone.publishedTraversalComplete,false);assert.equal(categoryDone.nativePaginationComplete,false);assert.equal(categoryDone.physicalStoreAssortmentComplete,false);assert.equal(categoryDone.nextAttemptAt,iso(NOW+900000));assert.equal(truncated.state.completedCycles,1,"A category cycle can finish without claiming the full public assortment");assert.equal(truncated.state.cursor,null);assert.equal(truncated.state.scanCoverage.categoryCoverage.truncatedLeaves.length,1);const incompleteStatus=await Refresh.status(truncated);assert.equal(incompleteStatus.categoryTraversalCycleComplete,true);assert.equal(incompleteStatus.publishedTraversalComplete,false);assert.equal(incompleteStatus.physicalStoreAssortmentComplete,false);
 const unresolved=copy(truncatedBatch);unresolved.pages[0].truncated=false;unresolved.categoryCoverage.truncatedLeaves=[];unresolved.categoryCoverage.unresolvedNodes=[{id:null,url:"https://www.hit.de/sortiment/uebersicht",total:5,received:2,reason:"hit-native-category-children-unresolved"}];assert.equal((await run(database(),unresolved)).publishedTraversalComplete,false);
 const forgedFull=copy(truncatedBatch);forgedFull.nativePaginationComplete=true;await assert.rejects(run(database(),forgedFull),error=>error.code==="hit-refresh-assortment-completion-unconfirmed");
 const cross=database({cursor:cursor(1),updatedAt:iso(NOW-60000),nativeTotal:5,pagesFetched:1,receivedCumulative:2});wall=NOW;const conflictGtin=gtin(1),isolated=batch(1,1);isolated.conflictGtins=[conflictGtin];isolated.categoryCoverage.conflictingIdentities=[conflictGtin];isolated.pages[0].conflictGtins=[conflictGtin];isolated.cursor.conflictGtins=[conflictGtin];isolated.cursor.visited[1].conflictGtins=[conflictGtin];isolated.cursor.categoryCoverage.conflictingIdentities=[conflictGtin];
 const progressed=await run(cross,isolated);assert.equal(progressed.accepted,2);assert.deepEqual(cross.events,["invalidate-conflict","persist","progress-checkpoint"]);assert.deepEqual(cross.state.invalidatedGtins,[conflictGtin]);assert.equal(cross.state.cursor.pagesFetched,2,"A product conflict must keep the unrelated category continuation");assert.deepEqual(cross.state.cursor.conflictGtins,[conflictGtin]);assert.equal(cross.state.retryAfter,null);assert.equal(progressed.nextAttemptAt,iso(NOW+60000));assert.equal(progressed.publishedTraversalComplete,false);assert.equal(progressed.quarantinedObservations,1);const invalidation=cross.calls.find(call=>call.sql.startsWith("UPDATE price_observations po SET truth_eligible=false,status='conflicting-source'"));assert.deepEqual(invalidation.params.slice(0,5),[Refresh.SOURCE,1775,"258","1775",[conflictGtin]]);assert.match(invalidation.sql,/po.id=evidence.observation_id/);assert.match(invalidation.sql,/evidence.native_store_id=\$2/);assert.match(invalidation.sql,/evidence.native_store_number=\$3/);
 const conflictComplete=copy(isolated);conflictComplete.complete=true;conflictComplete.categoryTraversalCycleComplete=true;conflictComplete.cursor=null;conflictComplete.categoryCoverage.pending=0;const completedWithGap=await run(database({cursor:cursor(1),updatedAt:iso(NOW-60000)}),conflictComplete);assert.equal(completedWithGap.categoryTraversalCycleComplete,true);assert.equal(completedWithGap.publishedTraversalComplete,false);assert.equal((await Refresh.status(cross)).conflictingIdentityCount,1);
 const unsafe=copy(isolated);unsafe.accepted.push(batch().accepted[0]);await assert.rejects(run(database({cursor:cursor(1),updatedAt:iso(NOW-60000)}),unsafe),error=>error.code==="hit-refresh-conflict-progress-unconfirmed");const falselyComplete=copy(conflictComplete);falselyComplete.nativePaginationComplete=true;await assert.rejects(run(database({cursor:cursor(1),updatedAt:iso(NOW-60000)}),falselyComplete),error=>error.code==="hit-refresh-assortment-completion-unconfirmed");
 const longerRefusal=database({cursor:cursor(1),updatedAt:iso(NOW-60000)});await assert.rejects(run(longerRefusal,null,{collect:async()=>{throw Object.assign(Error("source asks for longer pause"),{code:"hit-source-http-429",retryAfterMs:7200000});}}),error=>error.code==="hit-source-http-429");assert.equal(longerRefusal.state.retryAfter,iso(NOW+7200000));
 const zero=database();await assert.rejects(run(zero,batch(0,1,{total:0})),error=>error.code==="hit-refresh-completion-unconfirmed");assert(!zero.events.includes("persist"));assert.equal(zero.state.completedCycles,undefined);
 const badBatches=[
  raw=>({...raw,sourceId:"unknown"}),raw=>({...raw,cursorDay:"2026-10-02"}),raw=>({...raw,cursor:{...raw.cursor,cursorDay:"2026-10-02"}}),raw=>({...raw,physicalStoreAssortmentComplete:true}),raw=>({...raw,requests:17}),raw=>({...raw,received:3}),raw=>({...raw,pagesFetched:2}),raw=>({...raw,complete:true,cursor:null}),
  raw=>({...raw,pages:raw.pages.map(p=>({...p,pagination:{...p.pagination,page:1}}))}),raw=>({...raw,pages:raw.pages.map(p=>({...p,rowCount:1}))}),raw=>({...raw,pages:raw.pages.map(p=>({...p,uniqueRowCount:3}))}),raw=>({...raw,categoryCoverage:null}),raw=>({...raw,nativePaginationComplete:true}),raw=>({...raw,cursor:{...raw.cursor,seenSkus:[sku(1),sku(1)]}}),raw=>({...raw,pages:[],pagesFetched:0,received:0,cursor:cursor(0),total:null,requests:2})
 ];
 for(const change of badBatches){const invalid=database();wall=NOW;await assert.rejects(run(invalid,change(batch())),error=>/unconfirmed|conflict|progress/.test(error.code));assert(!invalid.events.includes("persist"));assert.equal(invalid.state.cursor??null,null);assert.equal(invalid.state.retryAfter,iso(NOW+3600000));}
 const queryOnly=database();await assert.rejects(Refresh.refresh({pool:queryOnly,now:()=>wall},{collect:async()=>{throw Error("No collection without a transaction-capable production pool");}}),error=>error.code==="hit-refresh-transaction-pool-required");assert.equal(queryOnly.calls.length,0,"Reject before quarantine or any autocommit side effect");
 wall=NOW;const staleCycle=database({cursor:cursor(1),ordinaryCycleId:CYCLE_A,updatedAt:iso(NOW-60000)});staleCycle.connect=async()=>({query:(...args)=>staleCycle.query(...args),release(){}});const staleCycleResult=await run(staleCycle,batch(1,1),{collect:async()=>{staleCycle.state.ordinaryCycleId=CYCLE_B;return copy(batch(1,1));}});assert.equal(staleCycleResult.skipped,"checkpoint-changed");assert.equal(staleCycle.state.ordinaryCycleId,CYCLE_B);assert(!staleCycle.events.includes("persist"));assert(!staleCycle.events.includes("progress-checkpoint"),"A stale collector cannot overwrite a concurrently rotated durable cycle");
 for(const code of["hit-source-http-403","hit-source-http-429"]){const refusedCycle=database({cursor:cursor(1),ordinaryCycleId:CYCLE_A,updatedAt:iso(NOW-60000)});await assert.rejects(run(refusedCycle,null,{time:NOW,collect:async()=>{throw Object.assign(Error("synthetic source refusal with durable generation"),{code,retryAfterMs:7200000});}}),e=>e.code===code);assert.equal(refusedCycle.state.ordinaryCycleId,CYCLE_A);assert.equal(refusedCycle.state.retryAfter,iso(NOW+7200000));}
 assert.notEqual(Refresh.checkpointKey({ordinaryCycleId:CYCLE_A}),Refresh.checkpointKey({ordinaryCycleId:CYCLE_B}));assert.equal(typeof Refresh.readState,"function");
 console.log("hit-price-refresh: OK");
}
main().catch(error=>{console.error(error);process.exitCode=1}).finally(()=>{Date.now=originalNow});
