"use strict";const assert=require("node:assert/strict"),F=require("./fixtures/hit-brand-partition"),B=require("./fixtures/hit-brand-partition-refresh"),Binding=require("../hit-brand-partition-binding"),Collector=require("../hit-assortment-collector"),Import=require("../hit-price-import"),clone=structuredClone;
async function main(){let cases=0;
 const Preflight=require("../hit-brand-partition-preflight");
 const observed=await B.batch(),ordinary=await B.batch({enabled:false,maxRequests:3}),r=observed.result,record=r.brandPartitionProbe;assert.equal(record.outcome,"confirmed");assert.equal(record.newSkuIds.length,8);assert.equal(record.overlapSkuIds.length,4);assert.equal(r.requests,4);assert.equal(r.pages.length,1);assert.equal(r.pagesFetched,2);assert.equal(r.received,41);assert.equal(r.accepted.length,40);assert.deepEqual(r.cursor,ordinary.result.cursor);assert.deepEqual(r.accepted,ordinary.result.accepted);assert.deepEqual(r.rejected,ordinary.result.rejected);assert.equal(r.nativePaginationComplete,false);assert.equal(r.physicalStoreAssortmentComplete,false);assert.equal(r.cursor.pending.length,1);assert(!r.cursor.pending.some(node=>node.id===F.node().id));assert(!r.cursor.seenSkus.includes(F.sku(41)));assert.equal(r.accepted.some(c=>c.sourceResponseUrl===observed.filteredUrl),false);assert.deepEqual(Binding.confirmed(r,{cursor:observed.previous},observed.time),record);cases++;
 const budget=await B.batch({maxRequests:3});assert.equal(budget.result.brandPartitionProbe,null);assert.equal(budget.calls.some(url=>url.includes("for_brands")),false);assert.deepEqual(budget.result.cursor,r.cursor);cases++;
 for(const status of[403,429]){const refused=await B.batch({response:{status,headers:{"retry-after":"7200"}}});assert.equal(refused.result.brandPartitionProbe.outcome,"source-refused");assert.equal(refused.result.error.code,"hit-source-http-"+status);assert.equal(refused.result.error.retryAfterMs,7200000);assert.equal(refused.calls.length,4);assert.deepEqual(refused.result.cursor,r.cursor);assert.deepEqual(Binding.confirmed(refused.result,{cursor:refused.previous},refused.time),refused.result.brandPartitionProbe);cases++;}
 const ignored=await B.batch({filtered:{edit:(_data,params)=>{delete params.for_brands;}}});assert.equal(ignored.result.brandPartitionProbe.outcome,"inconclusive");assert.equal(ignored.result.error,null);assert.deepEqual(ignored.result.cursor,r.cursor);cases++;
 const redirect=await B.batch({response:{status:302,headers:{location:"https://www.hit.de/login"}}});assert.equal(redirect.result.brandPartitionProbe.outcome,"failed");assert.equal(redirect.calls.length,4);assert.equal(redirect.result.error,null);cases++;
 const tamper=[
 ["wrong native Date",x=>{x.pages[0].responseDate=new Date(observed.time+1000).toUTCString();}],
 ["wrong native Age",x=>{x.pages[0].responseAgeSeconds=1;}],
 ["wrong control context",x=>{x.brandPartitionProbe.nativeState.seenQuotes={};}],
 ["extra filtered source page",x=>{x.pages[0].sourceResponseUrl=observed.filteredUrl;}],
 ["filtered price admission",x=>{x.accepted[0].sourceResponseUrl=observed.filteredUrl;}],
 ["filtered SKU injected in normal state",x=>{x.cursor.seenSkus[0]=F.sku(41);}],
 ["normal quote invented",x=>{x.cursor.seenQuotes["4000000000013|g|500|1"].signature="a".repeat(64);}],
 ["control quote changed",x=>{x.pages[0].nativeQuotes[0].quote.signature="b".repeat(64);}],
 ["pending actual node changed",x=>{x.brandPartitionProbe.controlNode.name="SYNTHETIC invented";}],
 ["untouched remaining queue erased",x=>{x.cursor.pending=[];x.cursor.categoryCoverage.pending=x.categoryCoverage.pending=0;}],
 ["old original visit overwritten",x=>{x.cursor.visited[0].url="https://www.hit.de/sortiment";}],
 ["filtered row rebound to normal capture",x=>{const parsed=require("../hit-assortment-client").parseRow(F.row(41),x.pages[0]);assert(parsed.ok);assert(Import.validateCandidate(parsed.candidate,{now:observed.time}).ok);x.accepted[0]=parsed.candidate;}]
 ];for(const [name,edit] of tamper){const changed=clone(r);edit(changed);assert.throws(()=>Binding.confirmed(changed,{cursor:observed.previous},observed.time),undefined,name);cases++;}
 assert.throws(()=>Binding.confirmed(r,{cursor:observed.previous,brandPartitionProbeAttempted:true},observed.time),/already-attempted/);cases++;
 for(const delay of[undefined,3600000,"7200000",NaN]){const x=(await B.batch({response:{status:429,headers:{"retry-after":"7200"}}})).result;x.error.retryAfterMs=delay;assert.throws(()=>Binding.confirmed(x,{cursor:observed.previous},observed.time),/source-refusal-unconfirmed/);cases++;}
 const later=await B.batch({maxRequests:5});assert.equal(later.result.complete,true);assert.equal(later.result.cursor,null);assert.equal(later.result.pages.length,2);assert.equal(later.result.accepted.length,42);assert.deepEqual(Binding.confirmed(later.result,{cursor:later.previous},later.time),later.result.brandPartitionProbe);assert.equal(Object.keys(later.result.brandPartitionProbe.nativeState.seenQuotes).length,40,"Later native quotes cannot change the control-time snapshot");cases++;
 const rebound=clone(later.result),filteredOnly=require("../hit-assortment-client").parseRow(F.row(41),rebound.pages[1]);assert(filteredOnly.ok);assert(Import.validateCandidate(filteredOnly.candidate,{now:later.time}).ok);rebound.accepted[rebound.accepted.length-1]=filteredOnly.candidate;assert.throws(()=>Binding.confirmed(rebound,{cursor:later.previous},later.time),/price-page-unconfirmed/);cases++;
 const repeated=await B.batch({maxRequests:5,followingRows:[{...F.row(90),external_id:F.sku(999)},F.row(91)]});assert(!repeated.result.pages[1].nativeSkuIds.includes(F.sku(999)));assert(repeated.result.accepted.some(candidate=>candidate.retailerSku===F.sku(999)));assert.deepEqual(Binding.confirmed(repeated.result,{cursor:repeated.previous},repeated.time),repeated.result.brandPartitionProbe);cases++;
 for(const patch of[{country:"AT"},{region:"Hamburg"}]){const x=clone(r);Object.assign(x.pages[0].storeProfile,patch);assert.throws(()=>Binding.confirmed(x,{cursor:observed.previous},observed.time),/control-not-in-batch/);cases++;}
 for(const query of[observed.filteredUrl,observed.filteredUrl+"&page=1"]){assert.throws(()=>Collector.allowedUrl(query,Import.STORE_PROFILE));cases++;}
 const p=r.brandPartitionPreflight[0];assert.equal(p.outcome,"prepared");assert.equal(p.reason,"control-prepared");assert.equal(p.categoryName,null);assert.equal(p.nativeCategoryLevel,null);assert.deepEqual(Preflight.bind([p],r.pages,4,observed.time),[p]);cases++;
 assert.equal(budget.result.brandPartitionPreflight[0].reason,"request-budget-exhausted");assert.equal(budget.result.brandPartitionPreflight[0].requestsRemaining,0);assert.equal(ordinary.result.brandPartitionPreflight.length,0);cases++;
 const mismatched=clone(observed.previous);mismatched.pending[0].count=79;const rejected=await B.batch({previous:mismatched});assert.equal(rejected.result.brandPartitionProbe,null);assert.equal(rejected.result.brandPartitionPreflight[0].reason,"hit-brand-partition-fresh-large-leaf-required");assert(!rejected.calls.some(url=>url.includes("for_brands")));cases++;
 for(const edit of[x=>{x.body="PRIVATE";},x=>{x.categoryName="Guessed";},x=>{x.nativeCategoryLevel=3;},x=>{x.sourceResponseHash="f".repeat(64);},x=>{x.capturedAt=new Date(observed.time+1).toISOString();},x=>{x.reason="PRIVATE arbitrary error";},x=>{x.total++;}]){const forged=clone(p);edit(forged);assert.throws(()=>Preflight.bind([forged],r.pages,4,observed.time),/preflight-unconfirmed/);cases++;}
 assert.throws(()=>Preflight.bind(Array(17).fill(p),r.pages,4,observed.time));assert.throws(()=>Preflight.bind([p,p],r.pages,4,observed.time));cases++;
 let summary=null;for(let i=0;i<20;i++)summary=Preflight.merge(summary,[{...p,sourceResponseHash:String(i).padStart(64,"0"),capturedAt:new Date(observed.time+i).toISOString()}],r.cursorDay);assert.equal(summary.entries.length,16);assert.equal(summary.entries[0].sourceResponseHash,"4".padStart(64,"0"));assert.equal(summary.priceImportEnabled,false);assert.equal(summary.complete,false);cases++;
 let longSummary=null;const longUrl="https://www.hit.de/sortiment/"+"a".repeat(870)+"-"+p.categoryId;for(let i=0;i<16;i++)longSummary=Preflight.merge(longSummary,[{...p,sourceResponseUrl:longUrl,sourceResponseHash:String(i).padStart(64,"0"),capturedAt:new Date(observed.time+i).toISOString()}],r.cursorDay);assert(longSummary.entries.length<16&&longSummary.entries.length>0);assert(Buffer.byteLength(JSON.stringify(longSummary))<=Preflight.MAX_BYTES);assert.equal(longSummary.entries.at(-1).capturedAt,new Date(observed.time+15).toISOString());cases++;
 const privateSummary=clone(summary);privateSummary.body="PRIVATE BODY";privateSummary.entries[0].seenQuotes="PRIVATE QUOTES";const publicJson=JSON.stringify(Preflight.publicSummary(privateSummary));assert(!publicJson.includes("PRIVATE"));assert.equal(Preflight.publicSummary({}),null);cases++;
 const offset={...p,capturedAt:"2026-10-02T07:40:00.125+02:00"},offsetPage={...r.pages[0],capturedAt:offset.capturedAt};assert.deepEqual(Preflight.bind([offset],[offsetPage],4,observed.time),[offset]);assert.deepEqual(Preflight.bind([p],r.pages,4,observed.time+3600000),[p],"Historical diagnostic does not add an admission-freshness gate");cases++;
 console.log("hit-brand-partition-collector: "+cases+" actual synthetic collector/binding/preflight cases passed");
}
main().catch(error=>{console.error(error);process.exitCode=1;});
