"use strict";
const assert=require("node:assert/strict"),crypto=require("node:crypto"),{Pool}=require("pg"),Import=require("../hit-price-import"),Client=require("../hit-assortment-client"),Query=require("../current-price-query-service"),Benchmark=require("../current-price-benchmark-service"),Semantics=require("../source-semantics"),Aliases=require("../product-alias-store"),Browser=require("../app/current-price-client");
const Refresh=require("../hit-price-refresh"),SOURCE=Import.SOURCE,storeProfile=Import.STORE_PROFILE,sku="000000000000869561ST",gtin="4388844177314",hash=value=>crypto.createHash("sha256").update(value).digest("hex");
// Native identity/normal-price fields from the saved public Berlin-Mitte milk card.
// Capture metadata and subsequent changed prices are explicitly local TEST responses.
const raw={external_id:sku,ean:gtin,storeId:1775,storeNumber:"258",headline:"ja! H-Milch 1,5%",overview:"1l Packung",price:"0.85",deposit:null,url:"https://www.hit.de/sortiment/kaese-eier-molkerei/milch-h-kuh-4261891/ja-h-milch-15-"+sku,inventoryAvailable:true,inventoryUpdatedAt:"2026-10-01T19:24:29+02:00",priceTag:{type:"discount",badgeText:"DAUER\nDISCOUNT\nPREIS",priceEuro:"0",priceCent:"85",priceStrikeThroughText:null,beforeText:null,belowText:null,couponCode:null,couponName:null}};
function candidate(capture,changes={}){const result=Client.parseRow({...structuredClone(raw),...changes},{storeProfile,capturedAt:new Date(capture).toISOString(),responseDate:new Date(capture).toUTCString(),responseAgeSeconds:0,sourceResponseHash:hash("POSTGRES TEST HIT response "+capture+JSON.stringify(changes)),sourceResponseUrl:"https://www.hit.de/sortiment/kaese-eier-molkerei/milch-h-kuh-4261891?markt=258"});assert(result.ok,JSON.stringify(result));return result.candidate}
const count=async(pool,table,where="true",args=[])=>Number((await pool.query("SELECT count(*)::int AS n FROM "+table+" WHERE "+where,args)).rows[0].n);
async function main(){
 const connectionString=process.env.DATABASE_URL;assert(connectionString,"DATABASE_URL is required for the HIT PostgreSQL test");const database=new URL(connectionString);assert.equal(database.hostname,"localhost","HIT integration writes only to a dedicated local test database");assert(database.pathname.endsWith("_test"),"Use a dedicated _test database");
 const pool=new Pool({connectionString,ssl:false,connectionTimeoutMillis:5000}),api=require("../server");let testError;
 try{
  await api.initDb();await Import.ensure(pool);await Aliases.ensure(pool);assert(Semantics.policy({source:SOURCE,sourceType:"official_retailer"}).registered,"Root must register the real HIT source before API admission");
  const now=Date.now(),capture=now-120000,today=Query.today(new Date(capture)),good=candidate(capture),options={storeProfile,now};
  const baseline={products:await count(pool,"products"),observations:await count(pool,"price_observations"),receipts:await count(pool,"receipt_submissions"),availability:await count(pool,"availability_observations"),aliases:await count(pool,"product_alias_evidence")};
  const first=await Import.persist(pool,[good],options);assert.equal(first.accepted.length,1,JSON.stringify(first));assert.equal(first.rejected.length,0);const accepted=first.accepted[0],storeId=accepted.storeId,productId=accepted.productId;
  const product=(await pool.query("SELECT name,brand,pack_amount::float AS amount,pack_unit AS unit,pack_count::int AS count FROM products WHERE id=$1",[productId])).rows[0];assert.equal(product.amount*({l:1000,kg:1000,cl:10}[product.unit]||1),1000);assert.equal(product.count,1);
  if(first.productsCreated)assert.equal(product.brand,null,"ja! is not inferred as a canonical brand");
  const store=(await pool.query("SELECT s.*,m.name AS merchant FROM stores s JOIN merchants m ON m.id=s.merchant_id WHERE s.id=$1",[storeId])).rows[0];assert.equal(store.external_id,"hit:store:1775");assert.equal(store.address,storeProfile.address);assert.equal(store.postal_code,"10117");assert.equal(store.city,"Berlin");assert.equal(store.country,"DE");assert.equal(Number(store.latitude),storeProfile.latitude);assert.equal(Number(store.longitude),storeProfile.longitude);assert.equal(store.merchant,"HIT");assert.equal(store.active,true);
  const storeMap=(await pool.query("SELECT * FROM external_store_mappings WHERE source_id=$1 AND external_location_id='1775'",[SOURCE])).rows[0];assert.equal(storeMap.store_id,storeId);assert.equal(storeMap.status,"verified");assert.equal(Number(storeMap.confidence),1);
  const nativeId="hit:store:1775:sku:"+sku,productMap=(await pool.query("SELECT * FROM external_product_mappings WHERE source_id=$1 AND external_product_id=$2",[SOURCE,nativeId])).rows[0];assert.equal(productMap.product_id,productId);assert.equal(productMap.status,"verified");
  const fact=(await pool.query("SELECT *,date::text AS day,valid_from::text AS from_day,valid_to::text AS to_day FROM price_observations WHERE id=$1",[accepted.observationId])).rows[0];assert.equal(Number(fact.price),.85);assert.equal(fact.per,"piece");assert.equal(fact.source_type,"official_retailer");assert.equal(fact.source_id,SOURCE);assert.equal(fact.evidence_purpose,"current-price");assert.equal(fact.pack,"1000 ml");assert.equal(fact.status,"observed");assert.equal(fact.truth_eligible,true);assert.equal(fact.identity_verified,true);assert.equal(fact.proof_verified,false);assert.equal(fact.proof_actor,null);assert.equal(fact.min_quantity,null);assert.equal(fact.regular_price,null);assert.equal(fact.observed_at.toISOString(),good.capturedAt);assert.equal(fact.fetched_at.toISOString(),good.capturedAt);assert.equal(fact.day,today);assert.equal(fact.from_day,today);assert.equal(fact.to_day,today);assert.deepEqual(fact.eligibility,{scopeChannel:"physical-store",sourceScope:"physical-store",nativeStoreId:1775,nativeStoreNumber:"258",goodsPriceCents:85,depositCents:null,priceIncludesDeposit:false,checkoutPriceVerified:false,sourceExpiresAt:good.expiresAt});
  const ledger=(await pool.query("SELECT * FROM hit_price_import_evidence WHERE observation_id=$1",[accepted.observationId])).rows[0];assert.equal(ledger.expires_at.toISOString(),good.expiresAt);assert.equal(ledger.captured_at.toISOString(),good.capturedAt);assert.equal(ledger.source_response_hash,good.sourceResponseHash);assert.deepEqual(ledger.native_proof,good.nativeProof);assert.equal(ledger.deposit_cents,null);
  const fixed=await count(pool,"price_observations","source_id=$1",[SOURCE]);const duplicate=await Import.persist(pool,[good],options);assert.equal(duplicate.duplicates,1);assert.equal(duplicate.accepted.length,0);assert.equal(await count(pool,"price_observations","source_id=$1",[SOURCE]),fixed);
  const conflicting=candidate(capture,{price:"0.95",priceTag:{...raw.priceTag,priceCent:"95"}}),same=await Import.persist(pool,[conflicting],options);assert.equal(same.rejected[0].reasons[0],"hit-import-same-capture-conflict");assert.equal(await count(pool,"price_observations","source_id=$1",[SOURCE]),fixed);
  const wrongPack=candidate(capture+1000,{headline:"POSTGRES TEST HIT conflicting pack",overview:"2x500ml Packung"}),packBlocked=await Import.persist(pool,[wrongPack],options);assert.equal(packBlocked.rejected[0].reasons[0],"hit-import-canonical-product-pack-conflict");assert.equal(await count(pool,"price_observations","source_id=$1",[SOURCE]),fixed);
  await pool.query("UPDATE external_product_mappings SET status='review' WHERE source_id=$1 AND external_product_id=$2",[SOURCE,nativeId]);try{const blocked=await Import.persist(pool,[candidate(capture+2000)],options);assert.equal(blocked.rejected[0].reasons[0],"hit-import-product-mapping-conflict");assert.equal(await count(pool,"price_observations","source_id=$1",[SOURCE]),fixed)}finally{await pool.query("UPDATE external_product_mappings SET status='verified' WHERE source_id=$1 AND external_product_id=$2",[SOURCE,nativeId])}
  const newer=candidate(capture+10000,{price:"0.95",priceTag:{...raw.priceTag,priceCent:"95"}}),next=await Import.persist(pool,[newer],options);assert.equal(next.accepted.length,1);let history=(await pool.query("SELECT id,status,truth_eligible,observed_at FROM price_observations WHERE id=ANY($1::uuid[]) ORDER BY observed_at",[[accepted.observationId,next.accepted[0].observationId]])).rows;assert.equal(history[0].status,"superseded");assert.equal(history[0].truth_eligible,false);assert.equal(history[0].observed_at.toISOString(),good.capturedAt);assert.equal(history[1].status,"observed");assert.equal(history[1].truth_eligible,true);assert.equal(await count(pool,"hit_price_import_evidence","source_id=$1 AND retailer_sku=$2",[SOURCE,sku]),2,"New captures preserve both original proofs");
  const late=await Import.persist(pool,[candidate(capture+5000,{headline:"POSTGRES TEST HIT alternate native wording",brand:"POSTGRES TEST HIT explicit native brand"})],options);assert.equal(late.accepted.length,1);const lateFact=(await pool.query("SELECT status,truth_eligible FROM price_observations WHERE id=$1",[late.accepted[0].observationId])).rows[0];assert.equal(lateFact.status,"superseded");assert.equal(lateFact.truth_eligible,false,"Out-of-order arrival cannot make an older price current again");assert.deepEqual((await pool.query("SELECT name,brand FROM products WHERE id=$1",[productId])).rows[0],{name:product.name,brand:product.brand},"Existing canonical name/brand are not overwritten by retailer wording");
  const input={product:good.name,gtin,pack:"1 l",merchants:["HIT"],storeIds:{HIT:storeId},region:"Berlin",today,maxAgeDays:7,refresh:false};const quote=await Query.compareCurrentPrices(pool,input);assert.equal(quote.ok,true,JSON.stringify(quote));const row=quote.results.find(r=>r.merchant==="HIT");assert(row);assert.equal(row.price,.95,JSON.stringify(row));assert.equal(row.locationLevel,"store");assert.equal(row.storeId,storeId);assert.equal(row.source,SOURCE);assert.equal(row.identityVerified,true);assert.equal(row.proofVerified,false);assert.equal(row.sourceEligibility.depositCents,null);assert.equal(row.sourceEligibility.checkoutPriceVerified,false);
  assert.equal(row.region,"Berlin");assert.equal(quote.leaders.lowestCheckout,null);const browser=Browser.normalizeDecision(JSON.parse(JSON.stringify(row)),{query:{gtin,pack:"1 l"},region:"Berlin",storeId,today,maxAgeDays:7});assert.equal(browser.price,.95,JSON.stringify(browser));assert.equal(browser.checkoutPriceVerified,false);assert.equal(browser.payablePackPrice,null);assert.equal(Browser.toComparablePrice(browser,"piece","1 l"),null,"A physical goods price remains visible but cannot become a payable basket without a native deposit amount");
  const benchmark=await Benchmark.compare(pool,{products:[{product:good.name,gtin,pack:"1 l",quantity:1}],merchants:["HIT"],storeIds:{HIT:storeId},region:"Berlin",today,maxAgeDays:7});assert.equal(benchmark.ok,true,JSON.stringify(benchmark));assert.equal(benchmark.summary.knownCells,1);assert.equal(benchmark.summary.verifiedCells,0,"Native identity evidence does not claim a manually reviewed proof");
  const tomorrow=new Date(Date.parse(today+"T12:00:00Z")+86400000).toISOString().slice(0,10),expired=await Query.compareCurrentPrices(pool,{...input,today:tomorrow});assert.equal(expired.results.find(r=>r.merchant==="HIT").price,null,"Conservative date-only validity expires at the next Berlin day");
  const concurrent=candidate(capture+20000),parallel=await Promise.all([Import.persist(pool,[concurrent],options),Import.persist(pool,[concurrent],options)]);assert.equal(parallel.reduce((sum,r)=>sum+r.accepted.length,0),1);assert.equal(parallel.reduce((sum,r)=>sum+r.duplicates,0),1);assert.equal(await count(pool,"stores","external_id='hit:store:1775'"),1);assert.equal(await count(pool,"products","gtin=$1",[gtin]),1);
  const poolProxy={query:(...args)=>pool.query(...args),connect:async()=>{const tx=await pool.connect();return{release:()=>tx.release(),query:async(sql,args)=>{if(sql.startsWith("INSERT INTO product_identity_evidence"))throw Object.assign(Error("POSTGRES TEST injected source persistence outage"),{code:"XX000"});return tx.query(sql,args)}}}};
  const beforeFailure=await count(pool,"price_observations","source_id=$1",[SOURCE]),latest=(await pool.query("SELECT observation_id FROM hit_price_import_evidence WHERE source_id=$1 ORDER BY captured_at DESC LIMIT 1",[SOURCE])).rows[0].observation_id;
  await assert.rejects(Import.persist(poolProxy,[candidate(capture+30000)],options),error=>error.code==="XX000");assert.equal(await count(pool,"price_observations","source_id=$1",[SOURCE]),beforeFailure,"A database failure rolls back the real observation insert, not just a simulated counter");assert.equal((await pool.query("SELECT truth_eligible FROM price_observations WHERE id=$1",[latest])).rows[0].truth_eligible,true,"A failed capture does not supersede the previous valid price");
  const resume=await Import.persist(pool,[candidate(capture+30000)],options);assert.equal(resume.accepted.length,1,"The same capture can be retried after the failed transaction");
  const withDeposit=candidate(capture+40000,{headline:"POSTGRES TEST HIT ja! H-Milch 1,5% explicit deposit case",deposit:"0.25"}),paid=await Import.persist(pool,[withDeposit],options);assert.equal(paid.accepted.length,1);const depositQuote=await Query.compareCurrentPrices(pool,input),depositRow=depositQuote.results.find(r=>r.merchant==="HIT");assert.equal(depositRow.goodsPrice,.85,JSON.stringify(depositRow));assert.equal(depositRow.deposit,.25);assert.equal(depositRow.payablePackPrice,1.10);assert.equal(depositRow.checkoutPriceVerified,true);const payable=Browser.normalizeDecision(JSON.parse(JSON.stringify(depositRow)),{query:{gtin,pack:"1 l"},region:"Berlin",storeId,today,maxAgeDays:7});assert.equal(Browser.toComparablePrice(payable,"piece","1 l").price,1.10,"The browser uses the separately evidenced deposit without changing the goods price");
  await pool.query("UPDATE price_observations SET observed_at=statement_timestamp()-interval '24 hours 1 second' WHERE id=$1",[paid.accepted[0].observationId]);const beyond24h=await Query.compareCurrentPrices(pool,input);assert.equal(beyond24h.results.find(r=>r.merchant==="HIT").price,null,"A still-valid calendar day cannot admit a capture older than 24 hours, including the 25-hour DST day");await pool.query("UPDATE price_observations SET observed_at=$2 WHERE id=$1",[paid.accepted[0].observationId,withDeposit.capturedAt]);
  const invalid=await Import.persist(pool,[{...good,nativeStoreId:1776},{...good,gtin:"invalid"},{...good,capturedAt:new Date(now-300001).toISOString()}],options);assert.equal(invalid.rejected.length,3);assert.equal(invalid.accepted.length,0);
  assert.equal(await count(pool,"receipt_submissions"),baseline.receipts);assert.equal(await count(pool,"availability_observations"),baseline.availability,"Public price cards do not claim observed shelf stock");assert.equal(await count(pool,"product_alias_evidence"),baseline.aliases,"No alias EAN or receipt-name learning is performed");
  const status=await Refresh.status(pool);assert.equal(status.nativeStoreId,1775);assert.equal(status.physicalStoreAssortmentComplete,false);assert.equal(status.publishedTraversalComplete,false);assert.equal(status.historicalProducts,1);assert.equal(status.currentProducts,Query.today()===today?1:0);assert.equal(status.unknownDepositPrices,0);
  const oldKilogramSku="000000000002001956KG",paidObservation=paid.accepted[0].observationId;
  // Simulate a legacy kilogram observation in this isolated test DB. Historical evidence stays present.
  await pool.query("UPDATE price_observations SET external_product_id=$2 WHERE id=$1",[paidObservation,"hit:store:1775:sku:"+oldKilogramSku]);
  await pool.query("UPDATE hit_price_import_evidence SET retailer_sku=$2 WHERE observation_id=$1",[paidObservation,oldKilogramSku]);
  assert.equal((await Query.compareCurrentPrices(pool,input)).results.find(r=>r.merchant==="HIT").price,null,"Already stored kilogram prices are excluded from fixed pack queries");
  assert.equal(await count(pool,"price_observations","id=$1 AND truth_eligible=true",[paidObservation]),1,"The isolated legacy fixture starts with the incorrect active truth flag");
  const originalKilogramEvidence=(await pool.query("SELECT * FROM hit_price_import_evidence WHERE observation_id=$1",[paidObservation])).rows[0];
  assert.equal(await Import.quarantineUnsupportedWeight(pool),1,"Deactivate only the matching legacy source/store/SKU weight observation");
  assert.equal(await Import.quarantineUnsupportedWeight(pool),0,"The source repair is idempotent");
  assert.deepEqual((await pool.query("SELECT truth_eligible,status FROM price_observations WHERE id=$1",[paidObservation])).rows[0],{truth_eligible:false,status:"unsupported-weight-sale-unit"});
  assert.deepEqual((await pool.query("SELECT * FROM hit_price_import_evidence WHERE observation_id=$1",[paidObservation])).rows[0],originalKilogramEvidence,"Original native evidence, hashes, capture times and price remain unchanged");
  const quarantinedStatus=await Refresh.status(pool);assert.equal(quarantinedStatus.truthEligibleKilogramCaptures,0);assert.equal(quarantinedStatus.unsupportedKilogramCaptures,1);assert.equal(quarantinedStatus.currentPrices,0);assert.equal(quarantinedStatus.currentProducts,0);assert.equal(quarantinedStatus.historicalProducts,1,"Excluded observations remain historical evidence");
  await pool.query("UPDATE price_observations SET external_product_id=$2,truth_eligible=true,status='observed' WHERE id=$1",[paidObservation,nativeId]);
  await pool.query("UPDATE hit_price_import_evidence SET retailer_sku=$2 WHERE observation_id=$1",[paidObservation,sku]);
  assert.equal((await Refresh.status(pool)).unsupportedKilogramCaptures,0);
  const coverageColumn=(await pool.query("SELECT data_type FROM information_schema.columns WHERE table_name=$1 AND column_name='scan_coverage'",[Refresh.TABLE])).rows[0];assert.equal(coverageColumn.data_type,"jsonb","The persisted category coverage schema is real PostgreSQL DDL");
  console.log("hit-price-postgres tests passed");
 }catch(error){testError=error;throw error}finally{await pool.end();await api.closeDb();if(testError)process.exitCode=1}
}
main().catch(error=>{console.error(error);process.exitCode=1});
