"use strict";
const assert=require("node:assert/strict"),Client=require("../hit-assortment-client"),Import=require("../hit-price-import"),Hit=require("../hit-product-discovery"),Clock=require("../current-price-query-service"),Current=require("../app/current-price-client");
const NOW=Date.parse("2026-10-01T21:45:00.123Z"),sku="000000000000869561ST",productId="30000000-0000-4000-8000-000000000001",storeId="20000000-0000-4000-8000-000000000001",merchantId="10000000-0000-4000-8000-000000000001";
function row({capture=NOW-1000,overview="1l Packung",deposit=null,price="0.85",gtin="4388844177314",retailerSku=sku}={}){
 const raw={external_id:retailerSku,ean:gtin,storeId:1775,storeNumber:"258",headline:"ja! H-Milch 1,5%",overview,price,deposit,url:"https://www.hit.de/sortiment/kaese-eier-molkerei/milch-h-kuh-4261891/ja-h-milch-15-"+retailerSku,priceTag:{type:"discount",badgeText:"DAUER\nDISCOUNT\nPREIS",priceEuro:price.split(".")[0],priceCent:price.split(".")[1],priceStrikeThroughText:null,beforeText:null,belowText:null,couponCode:null,couponName:null}};
 const parsed=Client.parseRow(raw,{storeProfile:Import.STORE_PROFILE,capturedAt:new Date(capture).toISOString(),responseDate:new Date(capture).toUTCString(),responseAgeSeconds:0,sourceResponseHash:"a".repeat(64),sourceResponseUrl:"https://www.hit.de/sortiment/kaese-eier-molkerei/milch-h-kuh-4261891?markt=258"});assert(parsed.ok,JSON.stringify(parsed));const c=parsed.candidate,checked=Import.validateCandidate(c,{now:capture});assert(checked.ok,JSON.stringify(checked));
 const proof="hit:store:1775:sku:"+retailerSku+":capture:"+c.capturedAt+":sha256:"+c.sourceResponseHash,single=c.packCount===1&&(c.normalizedPack.unit!=="piece"||c.normalizedPack.amount===1),checkout=c.depositCents!==null&&(c.depositCents===0||single);
 return{evidence:{source_id:Import.SOURCE,native_store_id:1775,native_store_number:"258",retailer_sku:retailerSku,captured_at:new Date(capture),expires_at:new Date(c.expiresAt),observation_id:checked.observationId,product_id:productId,store_id:storeId,gtin,pack_amount:checked.pack.amount,pack_unit:checked.pack.unit,pack_count:checked.pack.count,price_cents:c.priceCents,deposit_cents:c.depositCents,source_response_hash:c.sourceResponseHash,source_response_date:new Date(c.sourceResponseDate),source_age_seconds:0,source_url:c.sourceUrl,source_response_url:c.sourceResponseUrl,proof_hash:c.proofHash,native_proof:c.nativeProof,signature:checked.signature},observation:{id:checked.observationId,product_id:productId,store_id:storeId,merchant_id:merchantId,gtin,source_id:Import.SOURCE,source:Import.SOURCE,store:"HIT",region:"Berlin",kind:"external",status:"observed",source_type:"official_retailer",proof_type:"OFFICIAL_STORE_ASSORTMENT",evidence_purpose:"current-price",truth_eligible:true,identity_verified:true,proof_verified:false,currency:"EUR",price_type:"regular",per:"piece",external_location_id:"1775",external_product_id:checked.externalProductId,price:c.price,proof,proof_hash:c.proofHash,source_url:c.sourceUrl,pack:checked.strictPack,pack_amount:checked.pack.amount,pack_unit:checked.pack.unit,product:c.name,observed_at:new Date(capture),fetched_at:new Date(capture),date:Clock.today(new Date(capture)),valid_from:Clock.today(new Date(capture)),valid_to:Clock.today(new Date(Date.parse(c.expiresAt)-1)),eligibility:{scopeChannel:"physical-store",sourceScope:"physical-store",nativeStoreId:1775,nativeStoreNumber:"258",goodsPriceCents:c.priceCents,depositCents:c.depositCents,priceIncludesDeposit:false,checkoutPriceVerified:checkout,sourceExpiresAt:c.expiresAt}},product:{id:productId,gtin,pack_amount:checked.pack.amount,pack_unit:checked.pack.unit,pack_count:checked.pack.count,identity_status:"verified"},store:{id:storeId,merchant_id:merchantId,external_id:"hit:store:1775",active:true,address:Import.STORE_PROFILE.address,postal_code:Import.STORE_PROFILE.postalCode,city:"Berlin",region:"Berlin",country:"DE",latitude:Import.STORE_PROFILE.latitude,longitude:Import.STORE_PROFILE.longitude},merchant:{id:merchantId,name:"HIT",normalized_name:"hit",active:true},productMapping:{source_id:Import.SOURCE,external_product_id:checked.externalProductId,product_id:productId,status:"verified",confidence:1},storeMapping:{source_id:Import.SOURCE,external_location_id:"1775",store_id:storeId,status:"verified",confidence:1},sourceHealthState:null};
}
async function main(){
 const previous=Date.now;Date.now=()=>NOW;try{
 const good=row(),before=JSON.stringify(good),offer=Hit.validateRow(good,{now:NOW});assert(offer);assert.equal(offer.price,.85);assert.equal(offer.goodsPrice,.85);assert.equal(offer.deposit,null);assert.equal(offer.checkoutPriceVerified,false);assert.equal(offer.payablePackPrice,null);assert.equal(offer.branch.id,storeId);assert.equal(offer.branch.nativeStoreId,1775);assert.equal(offer.pack,"1000 ml");assert.equal(offer.validFrom,"2026-10-01");assert.equal(offer.validTo,"2026-10-02");assert.equal(offer.proofVerified,false);assert.equal(offer.availability,"unknown");assert.equal(JSON.stringify(good),before);
 assert(Hit.validateOffer(offer,{now:NOW}));const decision=Current.normalizeDecision(offer,{query:{gtin:offer.gtin,pack:offer.pack},storeId,region:"Berlin",today:"2026-10-01",now:NOW});assert.equal(decision.state,"observed");assert.equal(decision.price,.85);assert.equal(decision.checkoutPriceVerified,false);assert.equal(decision.payablePackPrice,null);
 const canonicalLitres=structuredClone(good);canonicalLitres.product.pack_amount=1;canonicalLitres.product.pack_unit="l";assert(Hit.validateRow(canonicalLitres,{now:NOW}),"Verified canonical1l and native1000ml denote the same single sales pack");
 const postgresJson=JSON.parse(JSON.stringify(good));assert.equal(Hit.validateRow(postgresJson,{now:NOW}).capturedAt,offer.capturedAt,"PostgreSQL JSON timestamps retain original capture milliseconds");
 for(const mutate of[
 r=>r.evidence.source_id="Wolt EDEKA Berlin",r=>r.evidence.native_store_id=1,r=>r.evidence.native_store_number="259",r=>r.evidence.retailer_sku=sku.replace("ST","KG"),r=>r.evidence.signature="forged",r=>r.evidence.source_response_hash="b".repeat(64),r=>r.evidence.proof_hash="b".repeat(64),r=>r.evidence.source_age_seconds=301,r=>r.evidence.source_response_date=new Date(NOW-301000),r=>r.evidence.expires_at=new Date(NOW+DAY),r=>r.evidence.native_proof.storeNumber="259",r=>r.evidence.native_proof.price="0.95",r=>r.evidence.native_proof.ean="4388844177315",r=>r.evidence.native_proof.priceTag.type="promotion",r=>r.evidence.native_proof.url=r.evidence.native_proof.url.replace(sku,"1ST"),r=>r.evidence.price_cents=85.1,r=>r.evidence.deposit_cents=0,
 r=>r.observation.id=productId,r=>r.observation.store_id=productId,r=>r.observation.merchant_id=productId,r=>r.observation.gtin="4008452027602",r=>r.observation.price=.95,r=>r.observation.status="superseded",r=>r.observation.truth_eligible=false,r=>r.observation.identity_verified=false,r=>r.observation.proof_verified=true,r=>r.observation.proof="forged",r=>r.observation.observed_at=new Date(NOW),r=>r.observation.fetched_at=new Date(NOW),r=>r.observation.valid_to="2026-10-01",r=>r.observation.eligibility.depositCents=0,r=>r.observation.eligibility.checkoutPriceVerified=true,r=>r.observation.pack="2 x 500 ml",r=>r.observation.external_product_id="hit:store:1:sku:"+sku,
 r=>r.product.pack_count=2,r=>r.product.pack_amount=500,r=>r.product.identity_status="candidate",r=>r.store.active=false,r=>r.store.city="Hamburg",r=>r.store.country="AT",r=>r.store.address="Elsewhere",r=>r.store.longitude+=.001,r=>r.merchant.active=false,r=>r.merchant.name="EDEKA",r=>r.productMapping.status="review",r=>r.productMapping.product_id=storeId,r=>r.storeMapping.external_location_id="1780",r=>r.sourceHealthState="quarantine"
 ]){const bad=structuredClone(good);mutate(bad);assert.equal(Hit.validateRow(bad,{now:NOW}),null,mutate.toString())}
 assert.equal(Hit.validateRow(row({capture:NOW+1}),{now:NOW}),null);assert.equal(Hit.validateRow(row({capture:NOW-DAY}),{now:NOW}),null);assert.equal(Hit.validateRow(good,{now:Date.parse(offer.expiresAt)}),null);assert(Hit.validateRow(good,{now:Date.parse(offer.expiresAt)-1}),"A cross-midnight original24h capture remains usable through expiry-1ms");
 const known=Hit.validateRow(row({deposit:"0.25"}),{now:NOW});assert(known);assert.equal(known.goodsPrice,.85);assert.equal(known.deposit,.25);assert.equal(known.payablePackPrice,1.10);assert.equal(known.checkoutPriceVerified,true);
 const multi=Hit.validateRow(row({overview:"2x500ml Packung",deposit:"0.25"}),{now:NOW});assert(multi);assert.equal(multi.packCount,2);assert.equal(multi.packAmount,500);assert.equal(multi.checkoutPriceVerified,false);assert.equal(multi.payablePackPrice,null);assert.equal(multi.nativeDeposit,.25);assert.equal(multi.deposit,null);
 const zero=Hit.validateRow(row({overview:"2x500ml Packung",deposit:"0.00"}),{now:NOW});assert(zero);assert.equal(zero.checkoutPriceVerified,true);
 const calls=[],pool={query:async(sql,params)=>{calls.push({sql,params});return{rows:[good]}}},result=await Hit.search(pool,{search:" Milch_%\\ ",now:NOW,limit:1});assert.equal(result.items.length,1);assert.equal(result.truncated,true);assert.deepEqual(calls[0].params,[Import.SOURCE,1775,"258",new Date(NOW).toISOString(),"2026-10-01","%Milch\\_\\%\\\\%",1]);assert(calls[0].sql.includes("po.id=e.observation_id"));for(const marker of["po.truth_eligible=true","e.expires_at=e.captured_at+interval '24 hours'","e.captured_at>$4","po.valid_to>=$5","e.retailer_sku~'^[0-9]+ST$'","pm.status='verified'","sm.status='verified'","COALESCE(p.pack_count,1)=e.pack_count","s.city='Berlin'","NOT EXISTS","ESCAPE"])assert(calls[0].sql.includes(marker),marker);assert(!/\b(?:INSERT|UPDATE|DELETE|CREATE|ALTER)\b/.test(calls[0].sql));
 const conflictSql=calls[0].sql.slice(calls[0].sql.indexOf("JOIN price_observations conflictingPo"));for(const predicate of["conflictingPo.source_id=conflicting.source_id","conflictingPo.source=conflicting.source_id","conflictingPo.store_id=conflicting.store_id","conflictingPo.product_id=conflicting.product_id","conflictingPo.gtin=conflicting.gtin","conflictingPo.truth_eligible=true","conflictingPo.status='observed'","conflictingPo.observed_at=conflicting.captured_at","conflictingPo.valid_to>=$5::date","conflicting.retailer_sku<>e.retailer_sku","conflicting.expires_at=conflicting.captured_at+interval '24 hours'","conflictNewer.source_id=conflicting.source_id","conflictNewer.native_store_id=conflicting.native_store_id","conflictNewer.retailer_sku=conflicting.retailer_sku","conflictNewer.captured_at>conflicting.captured_at"])assert(conflictSql.includes(predicate),"Only another currently eligible latest-SKU observation may conflict; history must not block recovery: "+predicate);
 const unchanged=calls.length;assert.deepEqual(await Hit.search(pool,{search:"Milch",merchant:"EDEKA",now:NOW}),{items:[],truncated:false});assert.equal(calls.length,unchanged);
 const other=row({retailerSku:"000000000000999999ST",price:"0.95"}),conflict=await Hit.search({query:async()=>({rows:[good,other]})},{search:"Milch",now:NOW});assert.deepEqual(conflict.items,[],"Two current nativeSKUs with conflicting sameGTIN/sales-pack prices cannot manufacture a shop quote");
 await assert.rejects(()=>Hit.search({query:async()=>{throw Object.assign(Error("database outage"),{code:"XX000"})}},{search:"Milch",now:NOW}),error=>error.code==="XX000");assert.deepEqual(await Hit.search({query:async()=>{throw Object.assign(Error('relation "hit_price_import_evidence" does not exist'),{code:"42P01"})}},{search:"Milch",now:NOW}),{items:[],truncated:false});
 console.log("hit-product-discovery: original native proof, canonical store/GTIN/sales-pack/mapping joins, read-only bounded SQL, 24h/midnight/expiry and unknown-deposit separation OK");
 }finally{Date.now=previous}
}
const DAY=86400000;module.exports={row,NOW};if(require.main===module)main().catch(error=>{console.error(error);process.exitCode=1});
