"use strict";
const assert=require("node:assert/strict"),crypto=require("node:crypto"),Refresh=require("../hit-price-refresh"),Collector=require("../hit-assortment-collector"),Client=require("../hit-assortment-client"),Import=require("../hit-price-import");
const NOW=Date.parse("2026-10-01T20:10:15.527Z"),copy=structuredClone,iso=time=>new Date(time).toISOString(),sku=n=>String(n).padStart(18,"0")+"ST",originalNow=Date.now;
let wall=NOW;Date.now=()=>wall;
function gtin(n){const body="400000"+String(n).padStart(6,"0");let sum=0;for(let i=0;i<body.length;i++)sum+=Number(body[i])*(i%2?3:1);return body+String((10-sum%10)%10)}
function cursor(pages,total=5,limit=2){const received=Math.min(pages*limit,total),seenQuotes={};for(let id=1;id<=received;id++)seenQuotes[gtin(id)+"|g|500|1"]={gtin:gtin(id),signature:crypto.createHash("sha256").update(JSON.stringify(["Standardprodukt "+id,125,null,"standard"])).digest("hex")};return{version:1,nativeStoreId:1775,nativeStoreNumber:"258",nextPage:pages,total:pages?total:null,limit:pages?limit:null,pagesFetched:pages,received,seenSkus:Array.from({length:received},(_,i)=>sku(i+1)),seenQuotes}}
function batch(start=0,count=1,{total=5,limit=2,time=wall,error=null,rejectedIds=[],requests=3+count}={}){
 const pages=[],accepted=[],rejected=[];
 for(let page=start;page<start+count;page++){
  const rowCount=Math.min(limit,total-page*limit),ids=Array.from({length:rowCount},(_,i)=>page*limit+i+1),sourceResponseUrl="https://www.hit.de/sortiment/uebersicht"+(page?"?page="+page:""),sourceResponseHash=crypto.createHash("sha256").update("actual-test-page-"+page).digest("hex");
  const meta={storeProfile:Import.STORE_PROFILE,capturedAt:iso(time),responseDate:new Date(time).toUTCString(),responseAgeSeconds:0,sourceResponseHash,sourceResponseUrl};
  let pageAccepted=0,pageRejected=0;
  for(const id of ids){if(rejectedIds.includes(id)){rejected.push({retailerSku:sku(id),reasons:["hit-unconditional-normal-price-tag-required"]});pageRejected++;continue}
   const raw={external_id:sku(id),ean:gtin(id),storeId:1775,storeNumber:"258",headline:"Standardprodukt "+id,overview:"500g Beutel",price:"1.25",deposit:null,url:"https://www.hit.de/sortiment/vorraete/standardprodukt-"+sku(id),priceTag:{type:"standard",badgeText:null,priceEuro:"1",priceCent:"25"}};
   const parsed=Client.parseRow(raw,meta);assert.equal(parsed.ok,true,JSON.stringify(parsed));accepted.push(parsed.candidate);pageAccepted++;
  }
  pages.push({...meta,rowCount,accepted:pageAccepted,rejected:pageRejected,pagination:{page,limit,total}});
 }
 const end=start+count,state=cursor(end,total,limit),complete=!error&&state.received===total;for(const id of rejectedIds)delete state.seenQuotes[gtin(id)+"|g|500|1"];
 return{sourceId:Refresh.SOURCE,accepted,rejected,pages,requests,complete,physicalStoreAssortmentComplete:false,cursor:complete?null:state,total:count||start?total:null,pagesFetched:end,received:state.received,error};
}
function database(initial={}){
 const state=copy(initial),calls=[],events=[];
 return{state,calls,events,failCheckpoint:false,query:async function(sql,params=[]){
  calls.push({sql,params:copy(params)});
  if(sql.startsWith("SELECT cursor"))return{rows:Object.keys(state).length?[copy(state)]:[]};
  if(sql.startsWith("INSERT INTO "+Refresh.TABLE)&&params.length===5){events.push("failure-checkpoint");Object.assign(state,{lastError:params[1],retryAfter:params[2],updatedAt:params[3]});if(params[4])state.cursor=null;return{rows:[],rowCount:1};}
  if(sql.startsWith("INSERT INTO "+Refresh.TABLE)){events.push("progress-checkpoint");if(this.failCheckpoint)throw Error("checkpoint-write-failed");Object.assign(state,{cursor:JSON.parse(params[1]),lastCompletedAt:params[2]?params[3]:state.lastCompletedAt??null,completedCycles:(state.completedCycles||0)+(params[2]?1:0),nativeTotal:params[4],pagesFetched:params[5],receivedCumulative:params[6],lastError:params[7],retryAfter:params[8],updatedAt:params[3]});return{rows:[],rowCount:1};}
  if(sql.startsWith("UPDATE price_observations SET truth_eligible=false")){events.push("invalidate-conflict");state.invalidatedGtins=copy(params[2]);return{rows:[],rowCount:params[2].length};}
  if(sql.includes('AS "historicalProducts"'))return{rows:[{historicalProducts:4,historicalCaptures:6,currentProducts:3,currentPrices:3,unknownDepositPrices:1}]};
  return{rows:[],rowCount:0};
 }};
}
const save=pool=>async(_pool,offers)=>{assert.equal(_pool,pool);pool.events.push("persist");return{accepted:offers.map((_,i)=>({id:"observation-"+i})),duplicates:0,rejected:[],productsCreated:offers.length,storeId:"native-store-test"}};
async function run(pool,result,{time=wall,maxRequests=8,persist=save(pool),collect}={}){
 wall=time;return Refresh.refresh({pool,maxRequests,now:()=>wall},{collect:collect||(async options=>{assert.equal(options.maxRequests,Math.min(16,Math.max(1,maxRequests)));assert.deepEqual(options.storeProfile,Import.STORE_PROFILE);assert.deepEqual(options.cursor,pool.state.cursor||null);return copy(result)}),persist});
}
async function main(){
 const initial=Date.parse(Collector.COOLDOWN_UNTIL),before=database();wall=initial-1;let collected=0;
 const held=await Refresh.refresh({pool:before,now:()=>wall},{collect:async()=>{collected++;throw Error("unexpected-network")},persist:save(before)});assert.equal(held.skipped,"source-cooldown");assert.equal(held.nextAttemptAt,Collector.COOLDOWN_UNTIL);assert.equal(collected,0);assert.deepEqual(before.state,{});assert.equal(await Refresh.resumeAt(before,wall),Collector.COOLDOWN_UNTIL);
 const delayed=database({cursor:cursor(1),updatedAt:new Date(NOW-60000),retryAfter:new Date(NOW+12345)});const heldAgain=await run(delayed,null,{time:NOW,collect:async()=>{throw Error("unexpected-network")}});assert.equal(heldAgain.skipped,"source-cooldown");assert.equal(heldAgain.nextAttemptAt,iso(NOW+12345),"PG Date objects preserve retry milliseconds");
 const due=database({cursor:cursor(1),updatedAt:new Date(NOW),retryAfter:null});assert.equal(await Refresh.resumeAt(due,NOW),iso(NOW+60000),"PG Date objects preserve continuation milliseconds");
 const old=database({cursor:null,updatedAt:new Date(NOW),lastCompletedAt:new Date(NOW-1000),completedCycles:2});assert.equal(await Refresh.resumeAt(old,NOW),iso(NOW+900000));
 wall=NOW;const pool=database(),first=batch();const output=await run(pool,first);assert.deepEqual(pool.events,["persist","progress-checkpoint"]);assert.equal(output.accepted,2);assert.equal(output.received,2);assert.equal(output.requests,4);assert.equal(output.pagesFetched,1);assert.equal(output.receivedCumulative,2);assert.equal(output.nativeTotal,5);assert.equal(output.publishedTraversalComplete,false);assert.equal(output.physicalStoreAssortmentComplete,false);assert.equal(pool.state.cursor.nextPage,1);assert.deepEqual(pool.state.cursor.seenSkus,[sku(1),sku(2)]);assert.equal(pool.state.completedCycles,0);assert.equal(pool.state.lastCompletedAt,null);assert.equal(pool.state.lastError,null);assert.equal(output.nextAttemptAt,iso(NOW+60000));
 const unchanged=copy(pool.state);const paused=await run(pool,null,{time:NOW+59999,collect:async()=>{throw Error("unexpected-network")}});assert.equal(paused.skipped,"source-cooldown");assert.deepEqual(pool.state,unchanged);
 const stamp=NOW+60000;wall=stamp;const remainder=batch(1,2,{time:stamp});const finished=await run(pool,remainder,{time:stamp});assert.equal(finished.accepted,3);assert.equal(finished.publishedTraversalComplete,true);assert.equal(finished.physicalStoreAssortmentComplete,false);assert.equal(pool.state.cursor,null);assert.equal(pool.state.completedCycles,1);assert.equal(pool.state.lastCompletedAt,iso(stamp));assert.equal(pool.state.receivedCumulative,5);assert.equal(finished.nextAttemptAt,iso(stamp+900000));const status=await Refresh.status(pool);assert.equal(status.publishedTraversalComplete,true);assert.equal(status.physicalStoreAssortmentComplete,false);assert.equal(status.currentPrices,3);assert.equal(status.city,"Berlin");
 const restart=database(copy(pool.state));const waiting=await run(restart,null,{time:stamp+899999,collect:async()=>{throw Error("unexpected-network")}});assert.equal(waiting.skipped,"source-cooldown");wall=stamp+900000;const newCycle=await run(restart,batch(0,1,{time:wall}),{time:wall});assert.equal(newCycle.pagesFetched,1);assert.equal(restart.state.completedCycles,1);assert.equal(restart.state.cursor.nextPage,1);
 wall=NOW;const failing=database({cursor:cursor(1),updatedAt:iso(NOW-60000),nativeTotal:5,pagesFetched:1,receivedCumulative:2}),beforeFailure=copy(failing.state);
 await assert.rejects(run(failing,batch(1,1),{persist:async()=>{failing.events.push("persist-failed");throw Object.assign(Error("actual SQL write failed"),{code:"XX000"})}}),error=>error.code==="XX000");assert.deepEqual(failing.state.cursor,beforeFailure.cursor);assert.equal(failing.state.pagesFetched,1);assert.equal(failing.state.receivedCumulative,2);assert.equal(failing.state.lastError,"XX000");assert.equal(failing.state.retryAfter,iso(NOW+3600000));assert(!failing.events.includes("progress-checkpoint"),"DB admission failure never advances traversal");
 const checkpoint=database();checkpoint.failCheckpoint=true;await assert.rejects(run(checkpoint,batch()),/checkpoint-write-failed/);assert.deepEqual(checkpoint.events,["persist","progress-checkpoint"]);assert.equal(checkpoint.state.cursor,undefined,"A failed checkpoint cannot advance the durable cursor");
 const partialPool=database();let partial;
 await assert.rejects(run(partialPool,batch(0,1,{error:{code:"hit-source-http-403",retryAfterMs:3600000},requests:5})),error=>{partial=error;return error.code==="hit-source-http-403"});assert.equal(partial.checkpointSaved,true);assert.equal(partial.partialResult.accepted,2);assert.equal(partial.partialResult.physicalStoreAssortmentComplete,false);assert.deepEqual(partialPool.events,["persist","progress-checkpoint"]);assert.equal(partialPool.state.cursor.nextPage,1);assert.deepEqual(partialPool.state.cursor.seenSkus,[sku(1),sku(2)]);assert.equal(partialPool.state.lastError,"hit-source-http-403");assert.equal(partialPool.state.retryAfter,iso(NOW+3600000));assert.equal(partialPool.state.lastCompletedAt,null);assert.equal(partialPool.state.completedCycles,0);
 const survived=copy(partialPool.state);assert.equal((await run(partialPool,null,{time:NOW+3599999,collect:async()=>{throw Error("unexpected-network")}})).skipped,"source-cooldown");assert.deepEqual(partialPool.state,survived);wall=NOW+3600000;const recovered=await run(partialPool,batch(1,1,{time:wall}),{time:wall});assert.equal(recovered.accepted,2);assert.equal(partialPool.state.lastError,null);assert.equal(partialPool.state.retryAfter,null);assert.equal(partialPool.state.cursor.nextPage,2);
 wall=NOW;const retry429=database({cursor:cursor(1),updatedAt:iso(NOW-60000)}),nativeCursor=copy(retry429.state.cursor);await assert.rejects(run(retry429,null,{collect:async()=>{throw Object.assign(Error("blocked"),{code:"hit-source-http-429"})}}),error=>error.code==="hit-source-http-429");assert.deepEqual(retry429.state.cursor,nativeCursor);assert.equal(retry429.state.retryAfter,iso(NOW+3600000));assert(!retry429.events.includes("persist"));
 for(const code of["hit-native-pagination-count-drift","hit-native-pagination-repeated-sku"]){
  const state=database({cursor:cursor(1),updatedAt:iso(NOW-60000),lastCompletedAt:iso(NOW-86400000),completedCycles:2,nativeTotal:5,pagesFetched:1,receivedCumulative:2});let problem;
  await assert.rejects(run(state,batch(1,1,{error:{code,retryAfterMs:3600000},requests:5})),error=>{problem=error;return error.code===code});assert.equal(problem.partialResult.accepted,2,"Valid prices from earlier pages survive later catalog drift");assert.deepEqual(state.events,["persist","progress-checkpoint"]);assert.equal(state.state.cursor,null,"Drift or repeated SKU starts a new cycle after cooldown");assert.equal(state.state.completedCycles,2);assert.equal(state.state.lastCompletedAt,iso(NOW-86400000));assert.equal(state.state.retryAfter,iso(NOW+3600000));wall=NOW+3600000;const resumed=await run(state,batch(0,1,{time:wall}),{time:wall});assert.equal(resumed.pagesFetched,1);assert.equal(state.state.cursor.nextPage,1);wall=NOW;
 }
 const allRejected=database();const filtered=await run(allRejected,batch(0,1,{total:2,rejectedIds:[1,2]}));assert.equal(filtered.accepted,0);assert.equal(filtered.sourceRejected,2);assert.equal(filtered.publishedTraversalComplete,true,"Published row traversal does not claim physical/price completeness");assert.equal(filtered.physicalStoreAssortmentComplete,false);
 const cross=database({cursor:cursor(1),updatedAt:iso(NOW-60000),nativeTotal:5,pagesFetched:1,receivedCumulative:2});wall=NOW;const conflictGtin=gtin(1);await assert.rejects(run(cross,batch(1,1,{error:{code:"hit-native-cross-page-identity-conflict",conflictGtins:[conflictGtin],retryAfterMs:3600000},requests:5})),error=>error.code==="hit-native-cross-page-identity-conflict"&&error.checkpointSaved===true);assert.deepEqual(cross.events,["persist","invalidate-conflict","progress-checkpoint"]);assert.deepEqual(cross.state.invalidatedGtins,[conflictGtin]);assert.equal(cross.state.cursor,null);assert.equal(cross.state.retryAfter,iso(NOW+3600000));const invalidation=cross.calls.find(call=>call.sql.startsWith("UPDATE price_observations SET truth_eligible=false"));assert.deepEqual(invalidation.params,[Refresh.SOURCE,"1775",[conflictGtin]],"Invalidate only the conflicting source/store/GTIN prices, not other shops or variants");assert.match(invalidation.sql,/source_id=\$1/);assert.match(invalidation.sql,/external_location_id=\$2/);assert.match(invalidation.sql,/status='conflicting-source'/);
 const zero=database();await assert.rejects(run(zero,batch(0,1,{total:0})),error=>error.code==="hit-refresh-completion-unconfirmed");assert(!zero.events.includes("persist"));assert.equal(zero.state.completedCycles,undefined);
 const badBatches=[
  raw=>({...raw,sourceId:"unknown"}),raw=>({...raw,physicalStoreAssortmentComplete:true}),raw=>({...raw,requests:17}),raw=>({...raw,received:3}),raw=>({...raw,pagesFetched:2}),raw=>({...raw,complete:true,cursor:null}),
  raw=>({...raw,pages:raw.pages.map(p=>({...p,pagination:{...p.pagination,page:1}}))}),raw=>({...raw,pages:raw.pages.map(p=>({...p,rowCount:1}))}),raw=>({...raw,cursor:{...raw.cursor,seenSkus:[sku(1),sku(1)]}}),raw=>({...raw,pages:[],pagesFetched:0,received:0,cursor:cursor(0),total:null,requests:2})
 ];
 for(const change of badBatches){const invalid=database();wall=NOW;await assert.rejects(run(invalid,change(batch())),error=>/unconfirmed|conflict|progress/.test(error.code));assert(!invalid.events.includes("persist"));assert.equal(invalid.state.cursor??null,null);assert.equal(invalid.state.retryAfter,iso(NOW+3600000));}
 console.log("hit-price-refresh: OK");
}
main().catch(error=>{console.error(error);process.exitCode=1}).finally(()=>{Date.now=originalNow});
