"use strict";
const assert=require("node:assert/strict"),Resolver=require("../current-price-resolver"),Browser=require("../app/current-price-client");
const SOURCE="HIT Berlin store assortment",today="2026-10-01",storeId="hit-test-store",query={name:"Kerrygold Original",gtin:"4001954161010",pack:"250 g"};
const actualNow=Date.now;Date.now=()=>Date.parse(today+"T19:00:00Z");
const row={id:"hit-test-observation",sourceId:SOURCE,source:SOURCE,sourceType:"official_retailer",store:"HIT",storeId,product:"Kerrygold Original",gtin:query.gtin,pack:query.pack,price:3.29,per:"piece",currency:"EUR",priceType:"regular",identityVerified:true,proofVerified:false,status:"observed",truthEligible:true,observedAt:today+"T18:00:00Z",date:today,validFrom:today,validTo:today,proofHash:"a".repeat(64),eligibility:{scopeChannel:"physical-store",nativeStoreId:1775,nativeStoreNumber:"258",goodsPriceCents:329,depositCents:null,priceIncludesDeposit:false,checkoutPriceVerified:false,sourceExpiresAt:"2026-10-02T18:00:00.000Z"}};
function quote(value){return Resolver.resolveMerchant(query,"HIT",[value],{today,storeId,maxAgeDays:7});}
const unknown=quote(row);assert.equal(unknown.price,3.29);assert.equal(unknown.goodsPrice,3.29);assert.equal(unknown.locationLevel,"store");assert.equal(unknown.deposit,null);assert.equal(unknown.payablePackPrice,null);assert.equal(unknown.checkoutPriceVerified,false);assert.equal(Resolver.leaders([unknown]).lowestCheckout,null,"Unknown deposit cannot create a checkout winner");assert.equal(Resolver.leaders([unknown]).lowestUnitPrice.price,3.29,"Known goods unit price stays available");
row.eligibility.sourceExpiresAt="2026-10-02T18:00:00.000Z";const freshUnknown=quote(row);
const clientContext={today,storeId,query:{...query,product:query.name}},normalized=Browser.normalizeDecision(freshUnknown,clientContext);assert.equal(normalized.goodsPrice,3.29);assert.equal(normalized.deposit,null);assert.equal(normalized.checkoutPriceVerified,false);assert.equal(Browser.toComparablePrice(normalized,"kg"),null,"Basket excludes a quote with an unresolved checkout amount");
for(const eligibility of [{...row.eligibility,checkoutPriceVerified:true},{...row.eligibility,depositCents:-1,checkoutPriceVerified:true},{...row.eligibility,goodsPriceCents:328,depositCents:0,checkoutPriceVerified:true},{...row.eligibility,nativeStoreId:1729,depositCents:0,checkoutPriceVerified:true}]){const unsafe=quote({...row,eligibility});assert.equal(unsafe.checkoutPriceVerified,false);assert.equal(unsafe.payablePackPrice,null);assert.equal(Browser.toComparablePrice(Browser.normalizeDecision(unsafe,clientContext),"kg"),null);}
const withDeposit=quote({...row,eligibility:{...row.eligibility,depositCents:25,checkoutPriceVerified:true}});assert.equal(withDeposit.price,3.29);assert.equal(withDeposit.deposit,.25);assert.equal(withDeposit.payablePackPrice,3.54);assert.equal(withDeposit.checkoutPriceVerified,true);const compared=Browser.toComparablePrice(Browser.normalizeDecision(withDeposit,clientContext),"kg");assert.equal(compared.payablePrice,3.54);assert.equal(compared.price,14.16,"Conversion includes known pack deposit instead of reusing goods-only unit price");
const other={merchant:"Other",price:3.4,unitPrice:13.6,unit:"kg"};assert.equal(Resolver.leaders([withDeposit,other]).lowestCheckout.merchant,"Other","Checkout ranking uses goods plus separately evidenced deposit");
const noDeposit=quote({...row,eligibility:{...row.eligibility,depositCents:0,checkoutPriceVerified:true}});assert.equal(noDeposit.payablePackPrice,3.29);assert.equal(Browser.toComparablePrice(Browser.normalizeDecision(noDeposit,clientContext),"kg").price,13.16);
const bundleQuery={...query,pack:"6 x 250 g"},bundle=Resolver.resolveMerchant(bundleQuery,"HIT",[{...row,pack:bundleQuery.pack,eligibility:{...row.eligibility,depositCents:25,checkoutPriceVerified:true}}],{today,storeId});assert.equal(bundle.price,3.29);assert.equal(bundle.nativeDeposit,.25);assert.equal(bundle.deposit,null);assert.equal(bundle.payablePackPrice,null,"An amount stated per bottle cannot establish the total deposit of a multipack");assert.equal(Browser.toComparablePrice(Browser.normalizeDecision(bundle,{...clientContext,query:bundleQuery}),"kg"),null);
const stripped={...unknown,checkoutPriceVerified:undefined,sourceEligibility:undefined};assert.equal(Browser.toComparablePrice(stripped,"kg"),null,"Removing checkout metadata cannot turn a HIT goods quote into a payable basket quote");
assert.equal(quote({...row,pack:"500 g"}).price,null);assert.equal(Resolver.resolveMerchant(query,"HIT",[row],{today:"2026-10-02",storeId}).price,null);
assert.equal(quote({...row,externalProductId:"hit:store:1775:sku:000000000002001956KG"}).price,null,"A previously stored kilogram quote cannot become a fixed pack price");
assert.equal(quote({...row,externalProductId:"hit:store:1775:sku:000000000002001956ST"}).price,3.29,"A fixed sales unit retains its observed pack price");
assert.equal(Browser.normalizeDecision({...freshUnknown,sourceEligibility:{...freshUnknown.sourceEligibility,sourceExpiresAt:undefined}},clientContext).price,null,"Missing native expiry cannot silently fall back to date-only freshness");
assert.equal(Browser.normalizeDecision(freshUnknown,{...clientContext,now:Date.parse("2026-10-02T18:00:00.000Z")}).price,null,"Expiry wins even with an explicitly historical comparison date");
for(const eligibility of [undefined,{...row.eligibility,sourceExpiresAt:undefined},{...row.eligibility,sourceExpiresAt:"2026-10-03T18:00:00Z"}])assert.equal(quote({...row,eligibility}).price,null,"Missing or extended native expiry cannot establish current HIT evidence");
const nextDay={...row,validTo:"2026-10-02"};
assert.equal(quote({...row,observedAt:new Date("2026-10-01T18:00:00.123Z"),eligibility:{...row.eligibility,sourceExpiresAt:"2026-10-02T18:00:00.123Z"}}).price,3.29,"PostgreSQL Date objects retain the original capture milliseconds for exact native expiry");
assert.equal(Resolver.resolveMerchant(query,"HIT",[nextDay],{today:"2026-10-02",storeId,now:Date.parse("2026-10-01T22:01:00Z")}).price,3.29,"The original 24-hour capture stays usable across Berlin midnight");
assert.equal(Resolver.resolveMerchant(query,"HIT",[nextDay],{today:"2026-10-02",storeId,now:Date.parse("2026-10-02T18:00:00Z")}).price,null,"Actual expiry wins over date validity");
assert.equal(Resolver.resolveMerchant(query,"HIT",[row],{today,storeId,now:Date.parse("2026-10-01T17:59:59Z")}).price,null,"Future captures cannot be used");
Date.now=actualNow;
console.log("hit-price-decision tests passed");
