"use strict";
const assert=require("node:assert/strict"),P=require("../kaufland-berlin-publications");
// Explicitly synthetic HTML originals and clocks. Native observed card shapes are
// reproduced for portable tests, never imported as fresh merchant observations.
const at=Date.parse("2026-10-03T02:29:19.413Z"),now=at+120000,copy=v=>structuredClone(v),esc=v=>String(v).replace(/&/g,"&amp;").replace(/"/g,"&quot;").replace(/</g,"&lt;");
const examples=[{id:"01383309",title:"K-CLASSIC",subtitle:"Gouda jung",quantity:"je 450-g-Stück",base:"(1 kg = 6.65)",price:"2.99"},
 {id:"01202136",title:"MEGGLE",subtitle:"Baguette",quantity:"je 160-g-Packg.",base:"(1 kg = 6.19) / (1 kg = 5.50)**",price:"0.99",card:"0.88"},
 {id:"00450098",title:"WEIHENSTEPHAN",subtitle:"Haltbare Milch, 3,5 % Fett",quantity:"je 1-l-Packg.",base:"",price:"9.99",bby:"12 Stück",calculation:"entspr. pro Packg. 0.84",old:"11.88"},
 {id:"02005209",title:"CAPRI-SUN",subtitle:"Fruchtsaftgetränk",quantity:"je 10 x 0,2-l-Packg.",base:"(1 l = 1.50) / (1 l = 1.25)**",price:"2.99",card:"2.49"},
 {id:"01504659",title:"STORCK",subtitle:"Super Dickmann's",quantity:"je 6 St. = 168-g-Packg.",base:"(1 kg = 9.30)",price:"1.59 *"},
 {id:"01272955",title:"FROSTA",subtitle:"Fertiggericht",quantity:"je 450 - 500-g-Packg.",base:"(1 kg = 4.58 - 5.09)",price:"2.29"},
 {id:"00052837",title:"K-PURLAND",subtitle:"Schweinenacken/-kamm ohne Knochen",quantity:"je kg",base:"",price:"5.29"},
 {id:"01060509",title:"K-CLASSIC",subtitle:"Tomatenmark",quantity:"je 200-g-Tube",base:"",price:"2.31",bby:"3 + 1 gratis",calculation:"entspr. pro Tube 0.58"}];
function card(row){return `<a class="k-product-tile k-product-tile--slider" href="/angebote/uebersicht.html?kloffer-category=135_Foodknueller&amp;kloffer-articleID=${esc(row.id)}"><div class="k-product-tile__main"><img src="https://kaufland.media.schwarz/is/image/schwarz/4063367116285_DE_P-1"><div class="k-product-tile__title">${esc(row.title)}</div><div class="k-product-tile__subtitle">${esc(row.subtitle)}</div><div class="k-product-tile__unit-price">${esc(row.quantity)}</div><div class="k-product-tile__base-price">${esc(row.base)}</div></div><div class="k-product-tile__pricetags"><div class="k-product-tile__pricetags-normal"><div class="k-price-tag">${row.bby?`<div class="k-price-tag__bby-message"><div class="k-price-tag__bby-message-top">${esc(row.bby)}</div><div class="k-price-tag__bby-message-bottom">${esc(row.calculation)}</div></div>`:""}<div class="k-price-tag__price">${esc(row.price)}</div>${row.old?`<div class="k-price-tag__old-price"><span>${esc(row.old)}</span></div>`:""}</div></div>${row.card?`<div class="k-product-tile__pricetags-loyalty"><div class="k-price-tag k-price-tag--xtra" is-k-card-only="false"><div class="k-price-tag__with-card">Mit Kaufland Card XTRA **</div><div class="k-price-tag__price">${esc(row.card)}</div></div></div>`:""}</div></a>`;}
function rehash(raw){for(const r of[raw.branch,raw.index]){r.sourceResponseHash=P.hash(r.body);r.bytes=Buffer.byteLength(r.body);}return raw;}
function fixture(rows=examples,time=at){const branch=`<!doctype html><html><head><script class="o-special-offers-controller__settings" type="application/json">{"settings":{"apiUrl":"/.kloffers.storeName={storeName}.json"}}</script></head><body><div class="o-store-details" data-force-store-change="DE1980"><h1 class="m-store-info__headname" itemprop="name" content="Kaufland Berlin-Reinickendorf">Kaufland Berlin-Reinickendorf</h1><span itemprop="url" content="/service/filiale.storeName=DE1980.html"></span><div itemprop="streetAddress" content="Ollenhauerstraße 122">Ollenhauerstraße 122</div><span itemprop="addressLocality" content="Berlin"></span><span itemprop="postalCode" content="13403"></span></div><div class="t-tiles-slider"><h3>Unsere Knüller der Woche</h3><h3>Gültig vom 01.10.2026 bis 07.10.2026</h3><div class="o-slider__list">${rows.map(card).join("")}</div></div><span itemprop="url" content="https://filiale.kaufland.de"></span></body></html>`,index=JSON.stringify([...new Map(rows.map(r=>[r.id,{dateFrom:"2026-10-01",dateTo:"2026-10-07",klNr:r.id}])).values()]);return rehash({branch:{status:200,sourceResponseUrl:P.PAGE_URL,sourceResponseHash:null,body:branch,capturedAt:new Date(time).toISOString(),headers:{date:new Date(time).toUTCString(),age:"0","content-type":"text/html; charset=UTF-8"},bytes:null},index:{status:200,sourceResponseUrl:P.INDEX_URL,sourceResponseHash:null,body:index,capturedAt:new Date(time+1000).toISOString(),headers:{date:new Date(time+1000).toUTCString(),age:"0","content-type":"application/json"},bytes:null}});}
let groups=0;function test(name,fn){fn();groups++;console.log("ok "+groups+" - "+name);}const parse=r=>P.parseCapture(r,{now});
test("synthetic native shape binds originals without mutation or canonical identities",()=>{const raw=fixture(),before=JSON.stringify(raw),p=parse(raw);assert.equal(JSON.stringify(raw),before);assert.equal(p.received,8);assert.equal(p.accepted,8);assert.equal(p.rejected,0);for(const{publication:q,reference:r}of p.promotionalPublications){assert.equal(q.sourceId,P.SOURCE);assert.equal(q.gtin,null);assert.equal(q.retailerSku,null);assert.equal(q.nativeMarketId,"DE1980");assert.equal(q.deposit,null);assert.equal(q.payablePackPrice,null);assert.equal(q.current,false);assert.equal(q.expiresAt,null);assert.equal(q.priceObservedAt,null);assert.equal(q.truthEligible,false);assert.equal(q.physicalStorePriceVerified,false);assert.equal(q.normalPriceClassificationVerified,false);assert.equal(q.numericComparisonEligible,false);assert.equal(q.fullAssortment,false);assert.equal(q.availability,"unknown");assert.equal(q.nativeValidity,null);assert.equal(q.publicationOriginalValidityVerified,false);assert.equal(r.observedAt,raw.branch.capturedAt);assert.deepEqual(r.sourceMarket,P.SHOP);assert(!Object.hasOwn(q,"price"));assert(!Object.hasOwn(q,"body"));assert(!Object.hasOwn(q,"rawCapture"));assert(!Object.hasOwn(q,"nativeWitness"));assert(!Object.hasOwn(q,"storeId"));}});
test("unconditional, Card XTRA and twelve-pack milk amounts stay distinct",()=>{const p=parse(fixture()),get=id=>p.promotionalPublications.find(r=>r.publication.nativePublicationId===id).publication,gouda=get("01383309"),meggle=get("01202136"),milk=get("00450098");assert.equal(gouda.announcedAmounts.default.amount,2.99);assert.equal(gouda.packAmount,450);assert.equal(meggle.announcedAmounts.default.amount,.99);assert.equal(meggle.announcedAmounts.card.amount,.88);assert.equal(meggle.announcedAmounts.card.condition,"kaufland-card-xtra");assert.equal(milk.announcedAmounts.default,null);assert.equal(milk.announcedAmounts.multibuy.amount,9.99);assert.equal(milk.announcedAmounts.multibuy.minimumPurchaseCount,12);assert.equal(milk.announcedAmounts.multibuy.nativePerPackCalculation,"entspr. pro Packg. 0.84");assert.equal(milk.packCount,1);assert.equal(milk.packAmount,1000);assert.equal(milk.packUnit,"ml");assert.equal(milk.previousPublishedAmount,11.88);});
test("native inner multipack differs from minimum multibuy quantity",()=>{const p=parse(fixture()),capri=p.promotionalPublications.find(r=>r.publication.nativePublicationId==="02005209").publication;assert.equal(capri.packCount,10);assert.equal(capri.packAmount,200);assert.equal(capri.pack,"10 x 0.2 l");assert.equal(capri.announcedAmounts.multibuy,null);assert.equal(capri.announcedAmounts.default.amount,2.99);const gratis=p.promotionalPublications.find(r=>r.publication.nativePublicationId==="01060509").publication;assert.equal(gratis.announcedAmounts.default,null);assert.equal(gratis.announcedAmounts.multibuy.minimumPurchaseCount,4);assert.equal(gratis.announcedAmounts.multibuy.amount,2.31);});
test("ranges, loose kg and unproven individual piece weights never become exact packs",()=>{const p=parse(fixture());for(const id of["01504659","01272955","00052837"]){const q=p.promotionalPublications.find(r=>r.publication.nativePublicationId===id).publication;assert.equal(q.packVerified,false);assert.equal(q.packAmount,null);assert(q.numericComparisonHoldReasons.includes("exact-sale-pack-unresolved"));}const q=p.promotionalPublications.find(r=>r.publication.nativePublicationId==="01504659").publication;assert(q.numericComparisonHoldReasons.includes("native-pack-base-price-conflict"));assert.equal(q.announcedAmounts.default.amount,1.59);assert.equal(q.nativeBasePrice,"(1 kg = 9.30)");assert.equal(q.priceFootnote,"limited-promotional-stock");});
test("known cent rounding is retained; genuine base or explicit variant contradictions stay held",()=>{assert(!parse(fixture()).promotionalPublications[0].publication.numericComparisonHoldReasons.includes("native-pack-base-price-conflict"));const r=copy(examples[0]);r.base="(1 kg = 9.30)";r.subtitle="Gouda oder Edamer";const p=parse(fixture([r])).promotionalPublications[0].publication;assert(p.numericComparisonHoldReasons.includes("native-pack-base-price-conflict"));assert(p.numericComparisonHoldReasons.includes("exact-variant-unresolved"));assert.equal(p.announcedAmounts.default.amount,2.99);});
test("all fifty native documents are bounded without declaring an exhaustive catalog",()=>{const rows=Array.from({length:50},(_,i)=>({...examples[0],id:String(10000000+i)})),p=parse(fixture(rows));assert.equal(p.accepted,50);assert.equal(p.fullAssortment,false);assert.throws(()=>parse(fixture([...rows,{...examples[0],id:"10000050"}])),/card-bound-exceeded/);});
test("seven-digit/composite unrelated index IDs have no native card identity authority",()=>{const raw=fixture();const a=JSON.parse(raw.index.body);a.push({dateFrom:"2026-10-08",dateTo:"2026-10-14",klNr:"0370981"},{dateFrom:"2026-10-08",dateTo:"2026-10-14",klNr:"_00376764"},{dateFrom:"2026-10-08",dateTo:"2026-10-14",klNr:"09900168_09982466"});raw.index.body=JSON.stringify(a);rehash(raw);assert.equal(parse(raw).accepted,8);const invalid=fixture([{...examples[0],id:"0370981"}]);assert.equal(parse(invalid).accepted,0);});
for(const[name,mutate]of[
 ["corrupt original body",r=>r.branch.body+=" "],["corrupt byte length",r=>r.index.bytes--],["wrong original URL",r=>r.branch.sourceResponseUrl+="?store=DE1999"],["foreign index",r=>r.index.sourceResponseUrl=r.index.sourceResponseUrl.replace("DE1980","DE1999")],["HTTP refusal",r=>r.branch.status=403],["future capture",r=>r.branch.capturedAt=new Date(now+1).toISOString()],["stale native Date",r=>r.branch.headers.date=new Date(at-300001).toUTCString()],["cached Age",r=>r.index.headers.age="301"],["malformed Age",r=>r.index.headers.age="NaN"],["wrong content type",r=>r.branch.headers["content-type"]="application/json"],["index precedes page",r=>{r.index.capturedAt=new Date(at-1000).toISOString();r.index.headers.date=new Date(at-1000).toUTCString();}],["too long paired interval",r=>{r.index.capturedAt=new Date(at+300001).toISOString();r.index.headers.date=new Date(at+300001).toUTCString();}],["invalid UTF8 roundtrip",r=>{r.branch.body+="\ud800";rehash(r);}],["NUL body",r=>{r.branch.body+="\u0000";rehash(r);}],["body bound",r=>{r.branch.body+=" ".repeat(P.MAX_HTML_BYTES);rehash(r);}]
])test(name+" rejects before publishing",()=>{const r=fixture();mutate(r);assert.throws(()=>parse(r),/kaufland-/);});
for(const[name,from,to]of[["foreign branch","data-force-store-change=\"DE1980\"","data-force-store-change=\"DE1999\""],["foreign city","content=\"Berlin\"","content=\"Hamburg\""],["wrong address","Ollenhauerstraße 122","Ollenhauerstraße 123"],["wrong postcode","13403","13404"],["wrong route template","/.kloffers.storeName={storeName}.json","/.unobserved/{storeName}.json"],["invalid calendar date","01.10.2026","31.02.2026"],["old publication window","01.10.2026 bis 07.10.2026","01.09.2026 bis 07.09.2026"]])test(name+" cannot use hash-correct forged native context",()=>{const r=fixture();r.branch.body=r.branch.body.replace(from,to);rehash(r);assert.throws(()=>parse(r),/kaufland-/);});
test("native duplicate IDs withhold every version before validation",()=>{const rows=[examples[0],{...examples[0],price:"3.99"}],r=fixture(rows);assert.equal(parse(r).accepted,0);assert.equal(parse(r).held.length,2);const malformed=fixture(rows);malformed.branch.body=malformed.branch.body.replace(card(rows[1]),card(rows[1]).replace("k-product-tile__title","removed-title"));rehash(malformed);assert.equal(parse(malformed).accepted,0);assert(parse(malformed).held.every(r=>r.reasons.includes("duplicate-native-publication-id")));});
test("malformed cents or loyalty contract hold actual native document",()=>{for(const change of[r=>r.price="1.491",r=>r.price="0.00",r=>r.price="10000.01",r=>r.card="1.111"]){const row=copy(examples[1]);change(row);const p=parse(fixture([row]));assert.equal(p.accepted,0);assert.equal(p.rejected,1);}const r=fixture([examples[1]]);r.branch.body=r.branch.body.replace("Mit Kaufland Card XTRA **","Privater Couponpreis");rehash(r);assert.equal(parse(r).accepted,0);});
test("store index mismatches and extra unreviewed fields are not usable price proof",()=>{const r=fixture();const a=JSON.parse(r.index.body);a[0].dateFrom="2026-10-05";r.index.body=JSON.stringify(a);rehash(r);assert.equal(parse(r).accepted,7);assert(parse(r).held[0].reasons.includes("native-store-index-window-conflict"));a[0].price=1;r.index.body=JSON.stringify(a);rehash(r);assert.throws(()=>parse(r),/native-index-invalid/);});
test("script or comment fake tiles are not native visible publications",()=>{const r=fixture();r.branch.body=r.branch.body.replace("</body>",`<!--${card(examples[0])}--><script>"${card(examples[0])}"</script></body>`);rehash(r);assert.equal(parse(r).accepted,8);});
test("unrelated visible tiles are outside the original closed weekly slider",()=>{const r=fixture();r.branch.body=r.branch.body.replace("</body>",card({...examples[0],price:"8.88"})+"</body>");rehash(r);assert.equal(parse(r).accepted,8);const ambiguous=fixture();ambiguous.branch.body=ambiguous.branch.body.replace("</body>",'<div class="t-tiles-slider"><h3>Unsere Knüller der Woche</h3><h3>Gültig vom01.10.2026 bis07.10.2026</h3></div></body>');rehash(ambiguous);assert.throws(()=>parse(ambiguous),/weekly-slider-required/);});
test("unreviewed membership or combined card-and-bundle lane stays held",()=>{const r=fixture([examples[0]]);r.branch.body=r.branch.body.replace('<div class="k-price-tag">','<div class="k-price-tag k-price-tag--xtra">');rehash(r);assert.equal(parse(r).accepted,0);const combined=fixture([examples[1]]);combined.branch.body=combined.branch.body.replace('<div class="k-price-tag__with-card">','<div class="k-price-tag__bby-message"></div><div class="k-price-tag__with-card">');rehash(combined);assert.equal(parse(combined).accepted,0);});
test("old exact original keeps dated publication and capture without acquiring price freshness",()=>{const r=fixture(),p=P.parseCapture(r,{now:at+30*P.DAY_MS});assert.equal(p.current,false);assert.equal(p.promotionalPublications[0].publication.capturedAt,r.branch.capturedAt);assert.equal(p.promotionalPublications[0].publication.expiresAt,null);assert.equal(p.promotionalPublications[0].publication.numericComparisonEligible,false);});
function mockDatabase(){let row=null,staged,assigned=false,inside=false,ddl=0,failCommit=false;const events=[];const inherited={connect(){throw Error("Never reconnect a genuine-like PoolClient");}};const tx=Object.assign(Object.create(inherited),{release(){events.push("release");},async query(sql,p=[]){events.push(sql);if(sql.startsWith("CREATE")){ddl++;return{rows:[]};}if(sql==="BEGIN"){inside=true;staged=copy(row);return{rows:[]};}if(sql==="SELECT txid_current()"){assigned=inside;return{rows:[{id:"1"}]};}if(sql.startsWith("SELECT pg_current"))return{rows:[{id:assigned?"1":null}]};if(sql.startsWith("SELECT pg_advisory"))return{rows:[]};if(sql.startsWith("SELECT proof_hash"))return{rows:(inside?staged:row)?[copy(inside?staged:row)]:[]};if(sql.startsWith("INSERT INTO")){staged={proof_hash:p[1],captured_at:p[2],raw_capture:JSON.parse(p[3]),held:false};return{rows:[],rowCount:1};}if(sql.startsWith("UPDATE")){if(sql.includes("SET held=true")){staged.held=true;staged.conflicting_capture=JSON.parse(p[1]);}else staged={proof_hash:p[1],captured_at:p[2],raw_capture:JSON.parse(p[3]),held:false};return{rows:[],rowCount:1};}if(sql==="COMMIT"){if(failCommit)throw Error("synthetic commit failure");row=copy(staged);inside=false;assigned=false;return{rows:[]};}if(sql==="ROLLBACK"){inside=false;assigned=false;staged=null;return{rows:[]};}throw Error("Unexpected SQL "+sql);}});const pool={connect:async()=>tx,query:async(sql,p)=>{if(sql.startsWith("CREATE")){ddl++;return{rows:[]};}if(sql.startsWith("SELECT proof_hash"))return{rows:row?[copy(row)]:[]};return tx.query(sql,p);}};return{pool,tx,events,get row(){return row;},set row(v){row=copy(v);},get ddl(){return ddl;},set failCommit(v){failCommit=v;}};}
async function asyncTest(name,fn){await fn();groups++;console.log("ok "+groups+" - "+name);}
(async()=>{
 await asyncTest("fresh private persist revalidates originals and exact replay leaves capture unchanged",async()=>{const h=mockDatabase(),raw=fixture();const first=await P.persist(h.pool,raw,{now});assert.equal(first.upserted,1);assert(h.events.some(e=>e.startsWith("SELECT pg_advisory")));assert(h.events.indexOf("SELECT txid_current()")<h.events.findIndex(e=>e.startsWith("INSERT")));const before=copy(h.row);const again=await P.persist(h.pool,raw,{now});assert.equal(again.upserted,0);assert.equal(again.unchanged,1);assert.deepEqual(h.row,before);assert.equal((await P.search(h.pool,{now})).promotionalPublications.length,8);assert.equal(h.ddl,1);});
 await asyncTest("historical archive may read but never admit as freshly captured",async()=>{const h=mockDatabase();await assert.rejects(P.persist(h.pool,fixture(),{now:at+P.DAY_MS+1000}),/stale-original/);assert.equal(h.row,null);assert.equal(h.events.length,0);});
 await asyncTest("changing capture timestamps alone cannot renew unchanged original witnesses",async()=>{const h=mockDatabase(),raw=fixture();await P.persist(h.pool,raw,{now});const before=copy(h.row),retimed=copy(raw);retimed.branch.capturedAt=new Date(at+10000).toISOString();retimed.index.capturedAt=new Date(at+11000).toISOString();await assert.rejects(P.persist(h.pool,retimed,{now}),/retimed-original/);assert.deepEqual(h.row,before);assert(h.events.includes("ROLLBACK"));});
 await asyncTest("samecapture contradiction is durable and replay cannot reveal an older clean group",async()=>{const h=mockDatabase(),raw=fixture();await P.persist(h.pool,raw,{now});const changed=fixture([{...examples[0],price:"3.99"},...examples.slice(1)]);const saved=await P.persist(h.pool,changed,{now});assert.equal(saved.held,true);assert.equal(saved.accepted,0);assert.equal((await P.search(h.pool,{search:"Gouda",now})).promotionalPublications.length,0);const status=await P.status(h.pool,{now});assert.equal(status.ambiguousLatestCapture,true);assert.equal(status.storedLatestGroups,8);assert.equal(status.heldGroups,8);assert.equal(status.publishedOfferGroups,0);await P.persist(h.pool,raw,{now});assert.equal(h.row.held,true);const next=fixture(examples,at+20000);await P.persist(h.pool,next,{now});assert.equal(h.row.held,false);assert.equal((await P.search(h.pool,{now})).promotionalPublications.length,8);assert.equal((await P.status(h.pool,{now})).numericComparisonHeldGroups,8);});
 await asyncTest("older replay, newest empty snapshot and newest held card never fall back",async()=>{const h=mockDatabase(),raw=fixture();await P.persist(h.pool,raw,{now});const newer=fixture([{...examples[0],price:"0.00"}],at+20000);await P.persist(h.pool,newer,{now});assert.equal((await P.search(h.pool,{search:"Gouda",now})).promotionalPublications.length,0);await P.persist(h.pool,raw,{now});assert.equal(h.row.raw_capture.branch.capturedAt,newer.branch.capturedAt);await P.persist(h.pool,fixture([],at+30000),{now});assert.equal((await P.search(h.pool,{now})).promotionalPublications.length,0);});
 await asyncTest("realistic inherited connect method is accepted only with assigned client transaction",async()=>{const h=mockDatabase();assert.equal(typeof h.tx.connect,"function");await assert.rejects(P.persist(h.tx,fixture(),{now}),/writing-transaction-required/);await h.tx.query("BEGIN");await h.tx.query("SELECT txid_current()");assert.equal((await P.persist(h.tx,fixture(),{now})).upserted,1);await h.tx.query("ROLLBACK");assert.equal(h.row,null);const ddl=h.ddl;await P.ensure(h.tx);await P.ensure(h.tx);assert.equal(h.ddl,ddl+2,"No schema cache on a PoolClient across rollback");});
 await asyncTest("failed final commit rolls back original snapshot and permits genuine retry",async()=>{const h=mockDatabase();h.failCommit=true;await assert.rejects(P.persist(h.pool,fixture(),{now}),/commit failure/);assert.equal(h.row,null);assert(h.events.includes("ROLLBACK"));h.failCommit=false;assert.equal((await P.persist(h.pool,fixture(),{now})).upserted,1);});
 await asyncTest("reader reparses actual private bodies instead of trusting stored summary/hash fields",async()=>{const h=mockDatabase();await P.persist(h.pool,fixture(),{now});const original=copy(h.row);for(const change of[r=>r.raw_capture.branch.body+=" ",r=>r.proof_hash="0".repeat(64),r=>r.captured_at=new Date(at+5000).toISOString(),r=>{r.raw_capture.branch.body=r.raw_capture.branch.body.replace("content=\"Berlin\"","content=\"Hamburg\"");rehash(r.raw_capture);}]){const bad=copy(original);change(bad);h.row=bad;await assert.rejects(P.search(h.pool,{now}),/kaufland-/);}h.row=original;assert.equal((await P.status(h.pool,{now})).publishedOfferGroups,8);});
 await asyncTest("held snapshot requires both original-bound genuine conflict captures",async()=>{const h=mockDatabase();await P.persist(h.pool,fixture(),{now});await P.persist(h.pool,fixture([{...examples[0],price:"4.99"}]),{now});const bad=copy(h.row);bad.conflicting_capture.branch.body+=" ";h.row=bad;await assert.rejects(P.status(h.pool,{now}),/original-capture-required/);});
 await asyncTest("closed read filters never manufacture barcode, physical or differently sized offers",async()=>{const h=mockDatabase();await P.persist(h.pool,fixture(),{now});for(const query of[{gtin:"4063367116285"},{merchant:"REWE"},{scopeChannel:"physical-store"},{pack:"1 g"}])assert.equal((await P.search(h.pool,{...query,now})).promotionalPublications.length,0);assert.equal((await P.search(h.pool,{search:"Gouda",pack:"450 g",now})).promotionalPublications.length,1);assert.equal((await P.search(h.pool,{pack:"2 l",now})).promotionalPublications.length,0,"Inner multipack must not match a single2lpack");assert.equal((await P.search(h.pool,{pack:"10 x 200 ml",now})).promotionalPublications.length,1);assert.equal((await P.search(h.pool,{limit:2,now})).truncated,true);for(const query of[{limit:201},{limit:0},{pack:"ca.450g"},{unknown:true},{search:"<script>"}])await assert.rejects(P.search(h.pool,{...query,now}),/invalid-/);});
 console.log("kaufland-berlin-publications: "+groups+" original/store/week/card/conditions/private-latest/replay/transaction/read groups passed; no HTTP or real SQL");
})().catch(e=>{console.error(e);process.exitCode=1;});
