"use strict";
const assert=require("node:assert/strict"),fs=require("node:fs"),path=require("node:path"),vm=require("node:vm");
const Publications=require("../kaufland-berlin-publications"),View=require("../app/kaufland-publication-view");
const at=Date.parse("2026-10-03T02:29:19.413Z"),now=at+120000,copy=structuredClone;
// Portable, explicitly SYNTHETIC originals reproduce the already frozen native
// card shapes. The real source parser generates every DTO. No archived capture
// is retimed, and no HTTP, SQL or retailer authority is invented by this fixture.
const examples=[
  {id:"01383309",title:"K-CLASSIC",subtitle:"Gouda jung",quantity:"je 450-g-Stück",base:"(1 kg = 6.65)",price:"2.99"},
  {id:"01202136",title:"MEGGLE",subtitle:"Baguette",quantity:"je 160-g-Packg.",base:"(1 kg = 6.19) / (1 kg = 5.50)**",price:"0.99",card:"0.88"},
  {id:"00450098",title:"WEIHENSTEPHAN",subtitle:"Haltbare Milch, 3,5 % Fett",quantity:"je 1-l-Packg.",base:"",price:"9.99",bby:"12 Stück",calculation:"entspr. pro Packg. 0.84",old:"11.88"},
  {id:"02005209",title:"CAPRI-SUN",subtitle:"Fruchtsaftgetränk",quantity:"je 10 x 0,2-l-Packg.",base:"(1 l = 1.50) / (1 l = 1.25)**",price:"2.99",card:"2.49"},
  {id:"01504659",title:"STORCK",subtitle:"Super Dickmann's",quantity:"je 6 St. = 168-g-Packg.",base:"(1 kg = 9.30)",price:"1.59 *"},
  {id:"01272955",title:"FROSTA",subtitle:"Fertiggericht",quantity:"je 450 - 500-g-Packg.",base:"(1 kg = 4.58 - 5.09)",price:"2.29"},
  {id:"00052837",title:"K-PURLAND",subtitle:"Schweinenacken/-kamm ohne Knochen",quantity:"je kg",base:"",price:"5.29"},
  {id:"01060509",title:"K-CLASSIC",subtitle:"Tomatenmark",quantity:"je 200-g-Tube",base:"",price:"2.31",bby:"3 + 1 gratis",calculation:"entspr. pro Tube 0.58"}
];
const esc=v=>String(v).replace(/&/g,"&amp;").replace(/"/g,"&quot;").replace(/</g,"&lt;");
function card(r){return `<a class="k-product-tile k-product-tile--slider" href="/angebote/uebersicht.html?kloffer-category=135_Foodknueller&amp;kloffer-articleID=${esc(r.id)}"><div class="k-product-tile__title">${esc(r.title)}</div><div class="k-product-tile__subtitle">${esc(r.subtitle)}</div><div class="k-product-tile__unit-price">${esc(r.quantity)}</div><div class="k-product-tile__base-price">${esc(r.base)}</div><div class="k-product-tile__pricetags-normal"><div class="k-price-tag">${r.bby?`<div class="k-price-tag__bby-message"><div class="k-price-tag__bby-message-top">${esc(r.bby)}</div><div class="k-price-tag__bby-message-bottom">${esc(r.calculation)}</div></div>`:""}<div class="k-price-tag__price">${esc(r.price)}</div>${r.old?`<div class="k-price-tag__old-price">${esc(r.old)}</div>`:""}</div></div>${r.card?`<div class="k-product-tile__pricetags-loyalty"><div class="k-price-tag k-price-tag--xtra"><div class="k-price-tag__with-card">Mit Kaufland Card XTRA **</div><div class="k-price-tag__price">${esc(r.card)}</div></div></div>`:""}</a>`;}
function fixture(rows=examples,time=at,from="2026-10-01",to="2026-10-07"){
  const human=v=>v.slice(8)+"."+v.slice(5,7)+"."+v.slice(0,4);
  const body=`<!doctype html><html><head><script class="o-special-offers-controller__settings" type="application/json">{"settings":{"apiUrl":"/.kloffers.storeName={storeName}.json"}}</script></head><body><!-- SYNTHETIC VIEW TEST ORIGINAL -->
    <div data-force-store-change="DE1980"><h1 itemprop="name" content="Kaufland Berlin-Reinickendorf">Kaufland Berlin-Reinickendorf</h1><span itemprop="url" content="/service/filiale.storeName=DE1980.html"></span><div itemprop="streetAddress" content="Ollenhauerstraße 122">Ollenhauerstraße 122</div><span itemprop="addressLocality" content="Berlin"></span><span itemprop="postalCode" content="13403"></span></div>
    <div class="t-tiles-slider"><h3>Unsere Knüller der Woche</h3><h3>Gültig vom ${human(from)} bis ${human(to)}</h3><div class="o-slider__list">${rows.map(card).join("")}</div></div></body></html>`;
  const record=(url,text,capture,type)=>({status:200,sourceResponseUrl:url,sourceResponseHash:Publications.hash(text),body:text,capturedAt:new Date(capture).toISOString(),headers:{date:new Date(capture).toUTCString(),age:"0","content-type":type},bytes:Buffer.byteLength(text)});
  return {branch:record(Publications.PAGE_URL,body,time,"text/html; charset=UTF-8"),index:record(Publications.INDEX_URL,JSON.stringify([...new Map(rows.map(r=>[r.id,{dateFrom:from,dateTo:to,klNr:r.id}])).values()]),time+1000,"application/json")};
}
function response(parsed){return{ok:true,promotionalPublications:copy(parsed.promotionalPublications),promotionalPublicationCoverage:{sourceId:Publications.SOURCE,merchant:"Kaufland",receivedGroups:parsed.received,acceptedGroups:parsed.accepted,heldGroups:parsed.rejected,matchedGroups:parsed.accepted,documentCapturedAt:parsed.documentCapturedAt,ambiguousLatestCapture:false,current:false,physicalStorePriceVerified:false,normalPriceClassificationVerified:false,nativeProductIdentities:0,fullAssortment:false},truncated:false};}
const parsed=Publications.parseCapture(fixture(),{now}),raw=response(parsed),row=id=>copy(parsed.promotionalPublications.find(r=>r.publication.nativePublicationId===id));
let groups=0;function test(name,fn){try{fn();groups++;}catch(error){console.error("Failed: "+name);throw error;}}
function noAuthority(v){const p=v.publication;for(const flag of["current","truthEligible","physicalStorePriceVerified","normalPriceClassificationVerified","numericComparisonEligible","currentAvailabilityVerified","fullAssortment","publicationOriginalValidityVerified"])assert.equal(p[flag],false);for(const key of["gtin","retailerSku","deposit","payablePackPrice","nativeValidity","expiresAt","priceObservedAt"])assert.equal(p[key],null);for(const key of["price","displayedPrice","unitPrice","body","rawCapture","nativeWitness","canonicalSelectionEligible","storeId"])assert(!Object.hasOwn(p,key));assert.equal(p.availability,"unknown");assert.equal(p.priceType,"unknown");}
test("actual source parser DTOs normalize without mutation or price/product authority",()=>{const before=JSON.stringify(raw),v=View.normalizeResponse(raw,{now});assert.equal(v.ok,true);assert.equal(v.promotionalPublications.length,8);assert.equal(v.promotionalPublicationCoverage.nativeProductIdentities,0);assert.equal(v.promotionalPublicationCoverage.coverageComplete,false);assert.equal(v.promotionalPublicationCoverage.displayedGroups,8);assert.equal(JSON.stringify(raw),before);for(const r of v.promotionalPublications){noAuthority(r);assert.equal(r.reference.observedAt,r.publication.capturedAt);assert.equal(r.datedInfo.capturedAgeMs,now-at);assert.equal(r.datedInfo.kind,"dated-publication");}});
test("twelve-purchase milk preserves9.99 and native0.84 text without single-pack conversion",()=>{const v=View.candidate(row("00450098"),{now});assert(v);const p=v.publication;assert.equal(p.announcedAmounts.default,null);assert.equal(p.announcedAmounts.multibuy.amount,9.99);assert.equal(p.announcedAmounts.multibuy.minimumPurchaseCount,12);assert.equal(p.announcedAmounts.multibuy.nativePerPackCalculation,"entspr. pro Packg. 0.84");assert.equal(p.packCount,1);assert.equal(p.packAmount,1000);assert.equal(p.previousPublishedAmount,11.88);assert(p.numericComparisonHoldReasons.includes("article-sale-validity-unverified"));noAuthority(v);});
test("Card XTRA amount never replaces the separate no-card lane",()=>{const v=View.candidate(row("01202136"),{now});assert(v);assert.equal(v.publication.announcedAmounts.default.amount,.99);assert.equal(v.publication.announcedAmounts.card.amount,.88);assert.equal(v.publication.announcedAmounts.card.nativeLabel,"Mit Kaufland Card XTRA **");assert.equal(v.publication.announcedAmounts.card.condition,"kaufland-card-xtra");assert.equal(v.publication.announcedAmounts.multibuy,null);noAuthority(v);});
test("native inner multipack stays distinct from minimum purchase count",()=>{const v=View.candidate(row("02005209"),{now});assert(v);assert.equal(v.publication.pack,"10 x 0.2 l");assert.equal(v.publication.packCount,10);assert.equal(v.publication.packAmount,200);assert.equal(v.publication.announcedAmounts.default.amount,2.99);assert.equal(v.publication.announcedAmounts.card.amount,2.49);assert.equal(v.publication.announcedAmounts.multibuy,null);const gratis=View.candidate(row("01060509"),{now});assert.equal(gratis.publication.announcedAmounts.multibuy.minimumPurchaseCount,4);assert.equal(gratis.publication.announcedAmounts.multibuy.amount,2.31);});
test("variable ranges, loose kilogram amounts and unproven piece totals remain explicit unknown packs",()=>{for(const id of["01504659","01272955","00052837"]){const v=View.candidate(row(id),{now});assert(v);assert.equal(v.publication.packVerified,false);assert.equal(v.publication.pack,null);assert.equal(v.publication.packAmount,null);assert(v.publication.numericComparisonHoldReasons.includes("exact-sale-pack-unresolved"));noAuthority(v);}});
test("Dickmann total/base discrepancy stays a numeric hold while native1.59 remains information",()=>{const r=row("01504659"),v=View.candidate(r,{now});assert(v);assert.equal(v.publication.announcedAmounts.default.amount,1.59);assert.equal(v.publication.nativeBasePrice,"(1 kg = 9.30)");assert(v.publication.numericComparisonHoldReasons.includes("native-pack-base-price-conflict"));assert(v.publication.numericComparisonHoldReasons.includes("individual-piece-weight-unverified"));r.publication.numericComparisonHoldReasons=r.publication.numericComparisonHoldReasons.filter(v=>v!=="native-pack-base-price-conflict");assert.equal(View.candidate(r,{now}),null);});
test("known native cent rounding is retained; unreviewed variant and base holds cannot be dropped",()=>{assert(View.candidate(row("01383309"),{now}));const p=Publications.parseCapture(fixture([{...examples[0],subtitle:"Gouda oder Edamer",base:"(1 kg = 9.30)"}]),{now}).promotionalPublications[0];assert(View.candidate(p,{now}));p.publication.numericComparisonHoldReasons=p.publication.numericComparisonHoldReasons.filter(v=>v!=="exact-variant-unresolved");assert.equal(View.candidate(p,{now}),null);});
test("old exact documents stay dated with unchanged captures and no invented expiry or fresh flag",()=>{const v=View.normalizeResponse(raw,{now:at+366*Publications.DAY_MS});assert.equal(v.promotionalPublications.length,8);assert.equal(v.promotionalPublications[0].publication.capturedAt,new Date(at).toISOString());assert.equal(v.promotionalPublications[0].datedInfo.capturedAgeMs,366*Publications.DAY_MS);for(const r of v.promotionalPublications){noAuthority(r);assert.equal(r.datedInfo.fresh,undefined);assert.equal(r.datedInfo.current,undefined);}});
test("future source window and future milk capture are rejected without projecting week validity",()=>{assert.throws(()=>Publications.parseCapture(fixture([examples[2]],at,"2026-10-05","2026-10-07"),{now}),/window-binding/);const r=row("00450098");r.publication.nativePublicationWindow={dateFrom:"2026-10-05",dateTo:"2026-10-07"};r.reference.key=JSON.stringify([r.publication.identityKind,Publications.SOURCE,"DE1980",r.publication.nativePublicationId,"2026-10-05","2026-10-07"]);assert.equal(View.candidate(r,{now}),null);const future=row("00450098");future.publication.capturedAt=new Date(now+1).toISOString();future.publication.indexCapturedAt=new Date(now+1001).toISOString();future.reference.observedAt=future.publication.capturedAt;assert.equal(View.candidate(future,{now}),null);});
test("native Berlin calendar midnight follows the original capture rather than UTCday",()=>{const time=Date.parse("2026-09-30T22:30:00.000Z"),p=Publications.parseCapture(fixture([examples[0]],time),{now:time+2000});assert(View.candidate(p.promotionalPublications[0],{now:time+2000}));});
for(const[name,change]of[
  ["foreign source",p=>p.sourceId="Kaufland AT"],["foreign merchant",p=>p.merchant="PENNY"],["wrong kind",p=>p.kind="price"],["SKUidentity",p=>p.identityKind="retailer-sku"],
  ["wrong country",p=>p.scopeCountry="AT"],["foreign city",p=>p.scopeCity="Hamburg"],["physical channel",p=>p.scopeChannel="physical-store"],["wrong market",p=>p.nativeMarketId="DE1999"],
  ["numeric native ID",p=>p.nativePublicationId=1383309],["short native ID",p=>p.nativePublicationId="1383309"],["source URL identity",p=>p.sourceUrl=p.sourceUrl.replace("01383309","01383308")],
  ["foreign host",p=>p.sourceUrl=p.sourceUrl.replace("filiale.kaufland.de","example.invalid")],["wrong source path",p=>p.sourceUrl=p.sourceUrl.replace("uebersicht.html","produkt.html")],
  ["duplicate article query",p=>p.sourceUrl+="&kloffer-articleID=01383309"],["source URL fragment",p=>p.sourceUrl+="#x"],["source URL credentials",p=>p.sourceUrl=p.sourceUrl.replace("https://","https://user@")],
  ["page URL with query",p=>p.sourceResponseUrl+="?x=1"],["wrong index URL",p=>p.indexResponseUrl=p.indexResponseUrl.replace("DE1980","DE1999")],
  ["wrong shop city",p=>p.shop.city="Hamburg"],["wrong shop address",p=>p.shop.address="Ollenhauerstraße123"],["wrong shop native ID",p=>p.shop.nativeMarketId="DE1999"],
  ["wrong shop postal code",p=>p.shop.postalCode="13404"],["shop canonical ID",p=>p.shop.storeId="invented"],
  ["foreign currency",p=>p.currency="USD"],["unknown state",p=>p.state="draft"],["known stock",p=>p.availability="available"],
  ["exact price type",p=>p.priceType="normal"],["promotion upgrade",p=>p.promotionStatus="normal"],["empty name",p=>p.name=""],["HTML name",p=>p.name="<b>Gouda</b>"],
  ["control name",p=>p.name="Gouda\u0000"],["trailing name",p=>p.name+=" "],["invalid native pack",p=>p.nativeQuantity="ca.450g"],
  ["pack total inference",p=>p.packAmount=1],["wrong display pack",p=>p.pack="1 g"],["wrong inner count",p=>p.packCount=2],["wrong pack unit",p=>p.packUnit="ml"],
  ["missing fixed pack flag",p=>p.packVerified=false],["pack metadata Infinity",p=>p.packAmount=Infinity],["unsafe base markup",p=>p.nativeBasePrice="<b>6.65</b>"],
  ["missing hold",p=>p.numericComparisonHoldReasons=[]],["unknown hold",p=>p.numericComparisonHoldReasons.push("eligible")],["duplicate hold",p=>p.numericComparisonHoldReasons.push(p.numericComparisonHoldReasons[0])],
  ["raw body",p=>p.body="PRIVATE ORIGINAL"],["raw pair",p=>p.rawCapture={branch:"PRIVATE"}],["native witness",p=>p.nativeWitness={}],["displayed price",p=>p.displayedPrice=2.99],
  ["direct pack price",p=>p.price=2.99],["derived unit price",p=>p.unitPrice=6.65],["winner authority",p=>p.canonicalSelectionEligible=true],
  ["unknown publication validity",p=>p.validFrom="2026-10-01"],["known price footnote",p=>p.priceFootnote="normal-price"],
  ["index before original",p=>p.indexCapturedAt=new Date(at-1).toISOString()],["paired interval overflow",p=>p.indexCapturedAt=new Date(at+300001).toISOString()],
  ["invalid calendar",p=>p.capturedAt="2026-02-31T00:00:00.000Z"],["missing milliseconds",p=>p.capturedAt="2026-10-03T02:29:19Z"],
  ["invalid window date",p=>p.nativePublicationWindow.dateFrom="2026-02-31"],["window too long",p=>p.nativePublicationWindow.dateTo="2026-10-08"],
  ["window extra validity",p=>p.nativePublicationWindow.priceValid=true]
])test(name+" withholds candidate",()=>{const r=row("01383309");change(r.publication);assert.equal(View.candidate(r,{now}),null);});
for(const key of["gtin","retailerSku","deposit","payablePackPrice","nativeValidity","expiresAt","priceObservedAt"])test(key+" cannot gain authority",()=>{const r=row("01383309");r.publication[key]=key==="deposit"?0:"invented";assert.equal(View.candidate(r,{now}),null);});
for(const key of["publicationOriginalValidityVerified","numericComparisonEligible","current","truthEligible","physicalStorePriceVerified","normalPriceClassificationVerified","currentAvailabilityVerified","fullAssortment"])test(key+" cannot become true",()=>{const r=row("01383309");r.publication[key]=true;assert.equal(View.candidate(r,{now}),null);});
for(const key of["sourceResponseHash","indexResponseHash","proofHash"])test(key+" requires lowercase complete SHA256 representation",()=>{for(const value of[null,"0".repeat(63),"A".repeat(64),"g".repeat(64)]){const r=row("01383309");r.publication[key]=value;assert.equal(View.candidate(r,{now}),null);}});
test("lane cents and all announced conditions are independently checked",()=>{for(const mutate of[p=>p.announcedAmounts.default.amount=0,p=>p.announcedAmounts.default.amount=1.491,p=>p.announcedAmounts.default.amount=10000.01,p=>p.announcedAmounts.default.amount=NaN,p=>p.announcedAmounts.default.amount=Infinity,p=>p.announcedAmounts.default.condition="card",p=>p.announcedAmounts.default.price=2.99]){const r=row("01383309");mutate(r.publication);assert.equal(View.candidate(r,{now}),null);}const card=row("01202136");card.publication.announcedAmounts.card.nativeLabel="Coupon only";assert.equal(View.candidate(card,{now}),null);const milk=row("00450098");milk.publication.announcedAmounts.multibuy.minimumPurchaseCount=1;assert.equal(View.candidate(milk,{now}),null);const disguised=row("00450098");disguised.publication.announcedAmounts.default={amount:.84,condition:"no-card-or-multibuy-on-card"};assert.equal(View.candidate(disguised,{now}),null);});
test("previous published amount stays a bounded cent amount separate from current lanes",()=>{for(const value of[0,-1,10000.01,1.491,NaN,Infinity]){const r=row("00450098");r.publication.previousPublishedAmount=value;assert.equal(View.candidate(r,{now}),null);}});
test("unresolved native multibuy text stays dated only when its hold remains",()=>{const p=Publications.parseCapture(fixture([{...examples[2],bby:"Beim Kauf einer Aktion"}]),{now}).promotionalPublications[0];const v=View.candidate(p,{now});assert(v);assert.equal(v.publication.announcedAmounts.multibuy.minimumPurchaseCount,null);assert(v.publication.numericComparisonHoldReasons.includes("multibuy-terms-unresolved"));p.publication.numericComparisonHoldReasons=p.publication.numericComparisonHoldReasons.filter(v=>v!=="multibuy-terms-unresolved");assert.equal(View.candidate(p,{now}),null);});
for(const[name,mutate]of[["key",r=>r.key+="x"],["observation clock",r=>r.observedAt=new Date(at+1).toISOString()],["market count",r=>r.observedMarkets=2],["kind",r=>r.kind="physical-price"],["identity",r=>r.identityKind="gtin"],["city",r=>r.city="Hamburg"],["country",r=>r.country="AT"],["merchant",r=>r.merchant="REWE"],["source market",r=>r.sourceMarket.address="Elsewhere"],["price range inference",r=>r.knownPriceRange={min:2.99,max:2.99}]])test("reference "+name+" remains source-bound",()=>{const r=row("01383309");mutate(r.reference);assert.equal(View.candidate(r,{now}),null);});
test("duplicate IDs are withheld before validation and literal request filtering",()=>{for(const mutate of[r=>r.publication.name="Other nonmatching group",r=>r.publication.scopeCountry="AT",r=>delete r.publication.name,r=>r.publication.announcedAmounts.default.amount=0]){const r=copy(raw),duplicate=copy(r.promotionalPublications[0]);mutate(duplicate);r.promotionalPublications.push(duplicate);for(const key of["receivedGroups","acceptedGroups","matchedGroups"])r.promotionalPublicationCoverage[key]++;const v=View.normalizeResponse(r,{now,request:{search:"Gouda"}});assert.equal(v.ok,true);assert.equal(v.promotionalPublications.length,0);const all=View.normalizeResponse(r,{now});assert.equal(all.promotionalPublications.length,7);assert(!all.promotionalPublications.some(v=>v.publication.nativePublicationId==="01383309"));}});
test("mixed old/new or conflicting snapshot evidence cannot expose an older fallback",()=>{for(const change of[p=>p.capturedAt=new Date(at-1).toISOString(),p=>p.sourceResponseHash="1".repeat(64),p=>p.proofHash="2".repeat(64),p=>p.indexCapturedAt=new Date(at+1001).toISOString(),p=>p.nativePublicationWindow.dateFrom="2026-10-02"]){const r=copy(raw);change(r.promotionalPublications[1].publication);const v=View.normalizeResponse(r,{now});assert.equal(v.ok,false);assert.deepEqual(v.promotionalPublications,[]);}});
test("snapshot object key order cannot create a false conflict",()=>{const r=copy(raw),w=r.promotionalPublications[1].publication.nativePublicationWindow;r.promotionalPublications[1].publication.nativePublicationWindow={dateTo:w.dateTo,dateFrom:w.dateFrom};const v=View.normalizeResponse(r,{now});assert.equal(v.ok,true);assert.equal(v.promotionalPublications.length,8);});
test("durably ambiguous latest snapshot has zero display groups and never revives supplied old rows",()=>{const r=copy(raw);r.promotionalPublications=[];Object.assign(r.promotionalPublicationCoverage,{acceptedGroups:0,matchedGroups:0,heldGroups:8,ambiguousLatestCapture:true});const v=View.normalizeResponse(r,{now});assert.equal(v.ok,true);assert.equal(v.promotionalPublications.length,0);assert.equal(v.promotionalPublicationCoverage.ambiguousLatestCapture,true);r.promotionalPublications=[row("01383309")];assert.equal(View.normalizeResponse(r,{now}).ok,false);});
test("one invalid unique document is excluded without upgrading source coverage or mutating other groups",()=>{const r=copy(raw);r.promotionalPublications[0].publication.price=2.99;const v=View.normalizeResponse(r,{now});assert.equal(v.ok,true);assert.equal(v.promotionalPublications.length,7);assert.equal(v.promotionalPublicationCoverage.acceptedGroups,8);assert.equal(v.promotionalPublicationCoverage.displayedGroups,7);assert.equal(v.promotionalPublicationCoverage.nativeProductIdentities,0);assert.equal(v.promotionalPublicationCoverage.fullAssortment,false);});
test("request values are bounded literal search/limit only, never identity or scope authority",()=>{const all=View.normalizeResponse(raw,{now,request:{limit:1}});assert.equal(all.promotionalPublications.length,1);assert.equal(all.truncated,true);const found=View.normalizeResponse(raw,{now,request:{search:"milch"}});assert.equal(found.promotionalPublications.length,1);assert.equal(found.promotionalPublications[0].publication.nativePublicationId,"00450098");for(const request of[{gtin:"5449000017888"},{pack:"1 l"},{merchant:"Kaufland"},{scopeChannel:View.CHANNEL},{now:0},{limit:0},{limit:201},{limit:"2"},{limit:1.5},{search:""},{search:" Gouda"},{search:"Gouda "},{search:"<script>"},{search:"x".repeat(121)}]){assert.equal(View.normalizeResponse(raw,{now,request}).ok,false);assert.equal(View.candidate(row("01383309"),{now,request}),null);}});
test("malformed envelopes/coverage stay closed, and genuinely empty source has no stock-absence claim",()=>{for(const mutate of[r=>r.ok=false,r=>r.rawCapture="PRIVATE",r=>r.truncated="true",r=>r.promotionalPublications={},r=>r.promotionalPublicationCoverage.receivedGroups=51,r=>r.promotionalPublicationCoverage.acceptedGroups=7,r=>r.promotionalPublicationCoverage.matchedGroups=9,r=>r.promotionalPublicationCoverage.nativeProductIdentities=50,r=>r.promotionalPublicationCoverage.current=true,r=>r.promotionalPublicationCoverage.documentCapturedAt=null,r=>r.promotionalPublicationCoverage.documentCapturedAt=new Date(now+1).toISOString()]){const r=copy(raw);mutate(r);assert.equal(View.normalizeResponse(r,{now}).ok,false);}const r=response(Publications.parseCapture(fixture([]),{now})),v=View.normalizeResponse(r,{now});assert.equal(v.ok,true);assert.equal(v.promotionalPublications.length,0);assert.equal(v.promotionalPublicationCoverage.fullAssortment,false);assert.equal(v.available,undefined);});
test("fifty groups are the hard view bound and never a full assortment count",()=>{const rows=Array.from({length:50},(_,i)=>({...examples[0],id:String(10000000+i)})),r=response(Publications.parseCapture(fixture(rows),{now})),v=View.normalizeResponse(r,{now});assert.equal(v.promotionalPublications.length,50);assert.equal(v.promotionalPublicationCoverage.fullAssortment,false);r.promotionalPublications.push(copy(r.promotionalPublications[0]));assert.equal(View.normalizeResponse(r,{now}).ok,false);});
test("null, malformed options and hostile accessor data reject without throw or native reads",()=>{for(const value of[null,[],0,{},new Date(),{publication:null,reference:{}}])assert.equal(View.candidate(value,{now}),null);for(const value of[NaN,Infinity,-1,now+.5,"2026-10-03T02:30:00.000Z"])assert.equal(View.normalizeResponse(raw,{now:value}).ok,false);assert.equal(View.normalizeResponse(raw,{now,unknown:true}).ok,false);const r=row("01383309");Object.defineProperty(r.publication,"name",{get(){throw Error("No getter authority");},enumerable:true});assert.equal(View.candidate(r,{now}),null);});
test("UMD browser helper executes on browser JSON and has no fetch/storage/DOM side effects",()=>{let calls=0;const browser={};const context=vm.createContext({window:browser,URL,Intl,Date,console,fetch(){calls++;throw Error("No network allowed");},localStorage:{setItem(){calls++;}},document:{createElement(){calls++;}}});vm.runInContext(fs.readFileSync(path.join(__dirname,"../app/kaufland-publication-view.js"),"utf8"),context);assert(Object.isFrozen(browser.CaddyKauflandPublicationView));context.rawJson=JSON.stringify(raw);context.testNow=now;const result=vm.runInContext("CaddyResult=window.CaddyKauflandPublicationView.normalizeResponse(JSON.parse(rawJson),{now:testNow});JSON.stringify(CaddyResult)",context);const v=JSON.parse(result);assert.equal(v.promotionalPublications.length,8);assert.equal(v.promotionalPublications[2].publication.announcedAmounts.multibuy.amount,9.99);assert.equal(calls,0);assert(Object.isFrozen(View));});
console.log("kaufland-publication-view: "+groups+" actual source-parser/closed DTO/dated/Card-XTRA/multibuy/holds/duplicate/UMD groups passed; no HTTP or SQL");
