"use strict";
const assert=require('node:assert/strict'),{Pool}=require('pg'),Pub=require('../lidl-price-publications'),Directory=require('../berlin-reference-directory');
const {fixture,changeArticle}=require('./helpers/lidl-capture-fixture');
async function main(){
 const connectionString=process.env.DATABASE_URL;assert(connectionString,'DATABASE_URL required');const url=new URL(connectionString);assert.equal(url.hostname,'localhost');assert(/^\/[a-z0-9_]+_test$/i.test(url.pathname),'Dedicated local *_test database required');
 const pool=new Pool({connectionString,ssl:false,connectionTimeoutMillis:5000}),owned=[];let api,groups=0;const now=Date.now(),at=now-10000;
 async function snapshot(table,predicate='true',params=[]){if(!(await pool.query('SELECT to_regclass($1) AS name',['public.'+table])).rows[0].name)return null;return(await pool.query("SELECT count(*)::int AS count,md5(COALESCE(string_agg(to_jsonb(t)::text,E'\\n' ORDER BY to_jsonb(t)::text),'')) AS hash FROM "+table+' t WHERE '+predicate,params)).rows[0];}
 async function save(raw){const parsed=Pub.parseCapture(raw,{now});assert.equal((await pool.query(`SELECT count(*)::int AS count FROM ${Pub.TABLE} WHERE proof_hash=$1`,[parsed.proofHash])).rows[0].count,0,'Own proof must be absent');owned.push(parsed.proofHash);assert.equal((await Pub.persist(pool,raw,{now})).upserted,1);return parsed;}
 try{
  await Pub.ensure(pool);await require('../penny-berlin-publications').ensure(pool);const baseline=await snapshot(Pub.TABLE),others=new Map();for(const table of ['products','stores','price_observations','receipts','retailer_published_prices','wolt_retailer_published_prices','rewe_retailer_published_prices','aldi_assortment_published_prices','penny_berlin_publication_captures','price_source_refresh_state'])others.set(table,await snapshot(table));
  const raw=fixture(at),parsed=await save(raw);assert.equal(parsed.accepted,20);assert.equal(parsed.rejected,4);assert.equal((await Pub.persist(pool,raw,{now})).unchanged,1);assert.deepEqual((await pool.query(`SELECT raw_capture FROM ${Pub.TABLE} WHERE proof_hash=$1`,[parsed.proofHash])).rows[0].raw_capture,raw);groups++;
  const result=await Directory.search(pool,{search:'Cashewkerne',merchant:'lidl',pack:'200 g',now});assert.equal(result.items.length,0);assert.equal(result.publications.length,0);assert.equal(result.datedPublications.length,1);assert.equal(result.datedPublications[0].publication.price,2.49);assert.equal(result.datedPublications[0].publication.current,false);assert.equal(result.coverage.retailers.find(r=>r.merchant==='Lidl').missing,true);groups++;
  assert.equal((await Directory.search(pool,{search:'Cola',pack:'9 x 330 ml',merchant:'Lidl',now})).datedPublications.length,1);assert.equal((await Directory.search(pool,{search:'Cola',pack:'2.97 l',merchant:'Lidl',now})).datedPublications.length,0);assert.equal((await Directory.search(pool,{gtin:'4008400401621',merchant:'Lidl',now})).datedPublications.length,0);groups++;
  await save(changeArticle(fixture(at+1000),s=>s.replace('200 Gramm, neu 2,49 Euro (Grundpreis: 12,45','200 Gramm, neu 2,50 Euro (Grundpreis: 12,45')));assert.equal((await Directory.search(pool,{search:'Alesto Cashewkerne',pack:'200 g',merchant:'Lidl',now})).datedPublications.length,0,'No older usable price fallback');groups++;
  await save(fixture(at+2000));await save(changeArticle(fixture(at+2000),s=>s.replace('Alesto Cashewkerne,','Alesto OTHER Cashewkerne,')));assert.equal((await Pub.status(pool,{now})).ambiguousLatestCapture,true);assert.equal((await Pub.search(pool,{search:'Cashewkerne',now})).datedPublications.length,0);groups++;
  const final=await save(fixture(at+3000)),preRead=await snapshot(Pub.TABLE);
  process.env.PORT='0';api=require('../server');await new Promise((resolve,reject)=>{api.server.once('error',reject);api.server.listen(0,'127.0.0.1',()=>{api.server.off('error',reject);resolve();});});const base='http://127.0.0.1:'+api.server.address().port;
  const request=async route=>{const response=await fetch(base+route,{signal:AbortSignal.timeout(10000)});return{status:response.status,body:await response.json()};};
  const http=await request('/v1/berlin-reference-prices?'+new URLSearchParams({search:'Cashewkerne',merchant:'Lidl',pack:'200 g'}));assert.equal(http.status,200);assert.equal(http.body.items.length,0);assert.equal(http.body.datedPublications.length,1);assert.equal(http.body.datedPublications[0].publication.proofHash,final.proofHash);assert.equal(http.body.datedPublications[0].publication.sourcePublishedDate,'2026-10-01');groups++;
  const status=await request('/v1/lidl-price-publications/status');assert.equal(status.status,200);assert.equal(status.body.datedPublicationGroups,20);assert.equal(status.body.quarantinedGroups,4);assert.equal(status.body.currentPhysicalPriceImports,0);assert.equal(status.body.nativeProductIdentities,0);assert.equal(status.body.fullAssortment,false);groups++;
  assert.equal((await Pub.search(pool,{search:'Cashewkerne',now:now+86400000*30})).datedPublications[0].publication.current,false);assert.equal((await Pub.status(pool,{now:now+86400000*30})).sourcePublishedDate,'2026-10-01');assert.deepEqual(await snapshot(Pub.TABLE),preRead,'Reads cannot alter or renew original proof');
  for(const [table,value]of others)assert.deepEqual(await snapshot(table),value,'No existing price/product mutation: '+table);assert.deepEqual(await snapshot(Pub.TABLE,'NOT(proof_hash=ANY($1::text[]))',[owned]),baseline);groups++;
  console.log('lidl-publications-postgres: '+groups+' actual SQL/HTTP groups OK; immutable originals, separate dated coverage, quarantine, latest/ties, pack isolation, dates never renewed');
 }finally{if(api){if(api.server.listening)await new Promise((resolve,reject)=>api.server.close(e=>e?reject(e):resolve()));await api.closeDb();}if(owned.length)await pool.query(`DELETE FROM ${Pub.TABLE} WHERE proof_hash=ANY($1::text[])`,[owned]);await pool.end();}
}
main().catch(error=>{console.error(error);process.exitCode=1;});
