"use strict";
const assert=require("node:assert/strict"),fs=require("node:fs"),vm=require("node:vm"),Client=require("../app/lidl-reference-client"),Berlin=require("../app/berlin-reference-client"),Current=require("../app/current-price-client"),Products=require("../app/published-product-client");
const SOURCE="Lidl DE dated price announcements",URL_EXACT="https://unternehmen.lidl.de/pressemitteilungen/2026/261001_preissenkung-snack-getraenke",PUBLISHED="2026-10-01",CHANNEL="retailer-price-publication",now=Date.parse("2026-10-02T18:00:00Z");
function reference(p){return{kind:"dated-national-publication",identityKind:"publication-group-not-sku",city:"Berlin",country:"DE",merchant:"Lidl",key:JSON.stringify(["publication-group-not-sku",SOURCE,URL_EXACT,p.groupOrdinal,p.packCount,p.packAmount,p.packUnit]),publishedOn:PUBLISHED,sourceMarket:null,observedMarkets:0};}
// Synthetic DTOs are used only for adversarial contract checks. Real original
// groups are independently exercised below through the immutable HTML fixture.
function row(patch={}){const publication={kind:"dated-national-price-publication",identityKind:"publication-group-not-sku",sourceId:SOURCE,merchant:"Lidl",publicationId:URL_EXACT,groupOrdinal:1,gtin:null,retailerSku:null,name:"Alesto Cashewkerne",nativeQuantity:"200 Gramm",pack:"200 g",packCount:1,packAmount:200,packUnit:"g",price:2.49,displayedPrice:2.49,currency:"EUR",previousPublishedPrice:2.89,nativeBasePrice:"12,45 Euro/kg",sourcePublishedDate:PUBLISHED,nativeValidity:null,publicationOriginalValidityVerified:false,current:false,expiresAt:null,priceObservedAt:null,capturedAt:"2026-10-02T15:22:46.780Z",scopeCountry:"DE",scopeCity:null,scopeChannel:CHANNEL,nationalScopeVerified:true,appliesToBerlin:true,shop:null,nativeMarketId:null,deposit:null,payablePackPrice:null,truthEligible:false,physicalStorePriceVerified:false,normalPriceClassificationVerified:false,priceType:"unknown",promotionStatus:"dated-price-reduction-announcement",sourceUrl:URL_EXACT,sourceResponseUrl:URL_EXACT,sourceResponseHash:"a".repeat(64),proofHash:"b".repeat(64),state:"published",...patch};return{publication,reference:reference(publication)};}
const envelope=rows=>({ok:true,city:"Berlin",country:"DE",items:[],publications:[],datedPublications:rows,truncated:false});
let checks=0;function test(name,fn){fn();checks++;console.log("ok "+checks+" - "+name);}
test("Dated group keeps publication date distinct from document retrieval",()=>{const input=row(),before=JSON.stringify(input),accepted=Client.candidate(input,{now});assert(accepted);assert.equal(JSON.stringify(input),before);assert.equal(accepted.publication.sourcePublishedDate,PUBLISHED);assert.equal(accepted.publication.capturedAt,input.publication.capturedAt);assert.equal(accepted.publication.priceObservedAt,null);assert.equal(accepted.publication.current,false);assert.equal(accepted.publication.expiresAt,null);assert.equal(accepted.reference.observedMarkets,0);assert.equal(accepted.reference.sourceMarket,null);});
test("Dated publication can never normalize as an offer or selectable product",()=>{const p=Client.candidate(row(),{now}).publication;assert.equal(Current.normalizePublishedReference(p,{now}),null);assert.equal(Current.normalizePublishedAlternative(p,{gtin:"4008400401621",pack:"200 g"},{now}),null);assert.equal(Products.selection(p),null);assert.equal(p.truthEligible,false);});
test("Literal query, merchant and channel are strictly bound",()=>{assert(Client.candidate(row(),{now,request:{search:"cashew",pack:"0.2 kg",merchant:"Lidl",scopeChannel:CHANNEL,limit:20}}));for(const request of[{gtin:"4008400401621"},{gtin:null},{search:"Butter"},{merchant:"PENNY"},{merchant:"LIDL"},{scopeChannel:"physical-store"},{scopeChannel:"online"},{pack:"400 g"},{pack:"ca.200 g"},{search:5},{search:"x"},{search:"a".repeat(121)},{search:"\u00ad\u00ad"},{limit:201},{search:"Cashew",region:"Berlin"}])assert.equal(Client.candidate(row(),{now,request}),null,JSON.stringify(request));});
test("Literal search normalizes umlauts and soft hyphens without image authority",()=>{const input=row({name:"Alesto Frucht-Nuss-Mischung mit Nüssen\u00ad",imageTitle:"Butter",imageAlt:"Milch"});assert(Client.candidate(input,{now,request:{search:"Nussen"}}));assert.equal(Client.candidate(input,{now,request:{search:"Butter"}}),null);assert.equal(Client.candidate(input,{now}).publication.imageTitle,undefined);});
test("Exact native beverage multipack retains individual amount and count",()=>{const input=row({groupOrdinal:23,name:"Freeway Cola / Cola Zero / Tropic Lemonade sort.",nativeQuantity:"2,97-Liter-Packung (9 x 0,33 l)",pack:"9 x 0.33 l",packCount:9,packAmount:330,packUnit:"ml",price:2.59,displayedPrice:2.59,previousPublishedPrice:3.15,nativeBasePrice:"0,87 Euro/l"});const accepted=Client.candidate(input,{now,request:{pack:"9 x 330 ml"}});assert(accepted);assert.equal(accepted.publication.packCount,9);assert.equal(accepted.publication.packAmount,330);for(const pack of["2.97 l","2970 ml","330 ml","3 x 990 ml"])assert.equal(Client.candidate(input,{now,request:{pack}}),null,pack);});
test("Apfelschorle multipack cannot be priced as nine individual bottles",()=>{const input=row({groupOrdinal:24,name:"Solevita Apfelschorle sort.",nativeQuantity:"4,5-Liter-Packung (9 x 0,5 l)",pack:"9 x 0.5 l",packCount:9,packAmount:500,packUnit:"ml",price:2.99,displayedPrice:2.99,previousPublishedPrice:3.49,nativeBasePrice:"0,66 Euro/l"});assert(Client.candidate(input,{now}));assert.equal(Client.candidate(input,{now,request:{pack:"500 ml"}}),null);assert.equal(Client.candidate({...input,publication:{...input.publication,price:3.06,displayedPrice:3.06}},{now}),null);});
test("Rounded native base price does not require exact decimal division",()=>{assert(Client.candidate(row({groupOrdinal:6,name:"Alesto Mandeln sort.",nativeQuantity:"150 Gramm",pack:"150 g",packAmount:150,price:1.79,displayedPrice:1.79,previousPublishedPrice:2.19,nativeBasePrice:"11,93 Euro/kg"}),{now}));assert(Client.candidate(row({groupOrdinal:18,name:"Mister Choc Milch & Cerealien Riegel sort.",nativeQuantity:"211,5 Gramm",pack:"211.5 g",packAmount:211.5,price:1.99,displayedPrice:1.99,previousPublishedPrice:2.49,nativeBasePrice:"9,41 Euro/kg"}),{now}));});
test("Arithmetic conflict and all three ambiguous native packs stay withheld",()=>{for(const ordinal of[8,10,17,19])assert.equal(Client.candidate(row({groupOrdinal:ordinal}),{now}),null,"Held ordinal cannot be admitted after a caller correction");assert.equal(Client.candidate(row({groupOrdinal:7,nativeQuantity:"500 Gramm",pack:"500 g",packAmount:500,price:1.79,displayedPrice:1.79,nativeBasePrice:"3,38 Euro/kg"}),{now}),null);for(const nativeQuantity of["200/250 Gramm","125/200 Gramm","150/180 Gramm"])assert.equal(Client.candidate(row({nativeQuantity}),{now}),null);});
test("GTIN, SKU, product identity and source publication identity cannot be invented",()=>{for(const patch of[{gtin:"4008400401621"},{gtin:undefined},{retailerSku:"lidl-1"},{identityKind:"native-retailer-sku"},{publicationId:"fake-publication"},{sourceId:"Lidl current shelf prices"},{groupOrdinal:0},{groupOrdinal:25},{groupOrdinal:"1"},{groupOrdinal:1.5},{kind:"regional-price-publication"}])assert.equal(Client.candidate(row(patch),{now}),null,JSON.stringify(patch));});
test("National Berlin relevance never turns into a specific branch proof",()=>{for(const patch of[{scopeCountry:"AT"},{scopeCity:"Berlin"},{scopeCity:undefined},{scopeChannel:"physical-store"},{nationalScopeVerified:false},{appliesToBerlin:false},{shop:{}},{nativeMarketId:"123"},{merchant:"ALDI"},{nativeVenueId:"0".repeat(24)}])assert.equal(Client.candidate(row(patch),{now}),null,JSON.stringify(patch));});
test("Only the exact original first-party article URLs are admitted",()=>{for(const field of["publicationId","sourceUrl","sourceResponseUrl"])for(const value of[URL_EXACT+"?fresh=true",URL_EXACT+"#item1",URL_EXACT+"/",URL_EXACT.replace("https:","http:"),URL_EXACT.replace("unternehmen.lidl.de","evil.test"),URL_EXACT.replace("https://","https://user@")])assert.equal(Client.candidate(row({[field]:value}),{now}),null,field+":"+value);});
test("Original hashes must be lower-case full SHA256 values",()=>{for(const field of["sourceResponseHash","proofHash"])for(const value of[null,"a".repeat(63),"A".repeat(64),"bad"])assert.equal(Client.candidate(row({[field]:value}),{now}),null);});
test("Unknown price validity, normal status and currentness cannot be upgraded",()=>{for(const patch of[{sourcePublishedDate:"2026-10-02"},{current:true},{current:undefined},{expiresAt:"2026-10-03T15:22:46.780Z"},{priceObservedAt:row().publication.capturedAt},{nativeValidity:{validFrom:PUBLISHED}},{nativeValidity:undefined},{publicationOriginalValidityVerified:true},{truthEligible:true},{physicalStorePriceVerified:true},{normalPriceClassificationVerified:true},{priceType:"regular"},{promotionStatus:"permanent-reduction-publication"},{validFrom:PUBLISHED},{validTo:"2026-10-07"},{state:"withheld"}])assert.equal(Client.candidate(row(patch),{now}),null,JSON.stringify(patch));});
test("Deposit and payable amounts remain explicitly unknown",()=>{assert.equal(Client.candidate(row(),{now}).publication.deposit,null);for(const patch of[{deposit:0},{deposit:.25},{payablePackPrice:2.49},{deposit:undefined},{payablePackPrice:undefined}])assert.equal(Client.candidate(row(patch),{now}),null,JSON.stringify(patch));});
test("Amounts and crossed-out prices never replace the published pack price",()=>{assert(Client.candidate(row({previousPublishedPrice:null}),{now}));for(const patch of[{price:2.495},{price:"2.49"},{price:0},{displayedPrice:2.89},{displayedPrice:null},{previousPublishedPrice:"2.89"},{previousPublishedPrice:0},{previousPublishedPrice:2.49},{previousPublishedPrice:1.99}])assert.equal(Client.candidate(row(patch),{now}),null,JSON.stringify(patch));});
test("Native quantity and normalized unit, amount and count must agree",()=>{for(const patch of[{nativeQuantity:"ca.200 Gramm"},{nativeQuantity:"250 Gramm"},{pack:"200 g oder 250 g"},{pack:"2 x 100 g"},{packAmount:200000},{packUnit:"kg"},{packCount:2},{packCount:1.5},{nativeBasePrice:"12,45 Euro/l"},{nativeBasePrice:"ab 12,45 Euro/kg"},{nativeBasePrice:"(Grundpreis: 12,45 Euro/kg"},{name:"<img onerror=x>"},{name:"x".repeat(251)}])assert.equal(Client.candidate(row(patch),{now}),null,JSON.stringify(patch));});
test("Declared multipack total has to equal its native individual quantity",()=>{assert.equal(Client.candidate(row({groupOrdinal:23,nativeQuantity:"2,98-Liter-Packung (9 x 0,33 l)",pack:"9 x 0.33 l",packCount:9,packAmount:330,packUnit:"ml",price:2.59,displayedPrice:2.59,previousPublishedPrice:3.15,nativeBasePrice:"0,87 Euro/l"}),{now}),null);});
test("Capture cannot precede publication or occur in the future",()=>{for(const capturedAt of["2026-09-30T21:59:59Z","2026-10-02","2026-02-30T12:00:00Z",new Date(now+1).toISOString()])assert.equal(Client.candidate(row({capturedAt}),{now}),null,capturedAt);assert(Client.candidate(row({capturedAt:"2026-09-30T22:00:00Z"}),{now}),"Berlin publication date begins at local midnight, without an invented effective instant");for(const invalid of[null,"2026-10-02T18:00:00Z",NaN,Infinity,1e308])assert.equal(Client.candidate(row(),{now:invalid}),null);});
test("A later document retrieval preserves the old publication date without renewed price freshness",()=>{const later=Date.parse("2027-01-01T08:00:00Z"),accepted=Client.candidate(row({capturedAt:new Date(later-1000).toISOString()}),{now:later});assert(accepted);assert.equal(accepted.publication.sourcePublishedDate,PUBLISHED);assert.equal(accepted.publication.current,false);assert.equal(accepted.publication.priceObservedAt,null);assert.equal(accepted.publication.expiresAt,null);assert(Client.candidate(row(),{now:later}),"The dated fact can remain visible as a dated fact, never as a current price");});
test("Conditional or checkout authority is rejected rather than silently upgraded",()=>{for(const patch of[{requiresApp:true},{requiresMembership:true},{requiresCoupon:true},{multiBuy:true},{priceFrom:true},{minimumQuantity:2},{priceAudience:"members"},{identityVerified:true},{canonicalSelectionEligible:true},{checkoutPriceVerified:true},{storeId:"internal-id"},{productId:"internal-id"},{shippingIncluded:false},{serviceFeesIncluded:true}])assert.equal(Client.candidate(row(patch),{now}),null,JSON.stringify(patch));});
test("Reference identity, publication date and zero market proof are exact",()=>{const input=row();for(const patch of[{kind:"last-observed"},{identityKind:"native-retailer-sku"},{city:"Hamburg"},{country:"AT"},{merchant:"PENNY"},{key:"group1"},{publishedOn:"2026-10-02"},{sourceMarket:{}},{observedMarkets:1},{observedAt:input.publication.capturedAt},{knownPriceRange:{min:1,max:3}}])assert.equal(Client.candidate({...input,reference:{...input.reference,...patch}},{now}),null,JSON.stringify(patch));});
test("Duplicate group ordinals are counted before price and request validation",()=>{const a=row(),b=row({price:2.99,displayedPrice:2.99,nativeBasePrice:"14,95 Euro/kg",previousPublishedPrice:3.49});assert.equal(Client.normalizeResponse(envelope([a,b]),{now}).datedPublications.length,0);assert.equal(Client.normalizeResponse(envelope([a,a]),{now}).datedPublications.length,0);const otherPack=row({nativeQuantity:"150 Gramm",pack:"150 g",packAmount:150,nativeBasePrice:"16,60 Euro/kg"});assert.equal(Client.normalizeResponse(envelope([a,otherPack]),{now,request:{pack:"200 g"}}).datedPublications.length,0);});
test("Invalid latest copy suppresses older same-ordinal fallback",()=>{const old=row(),invalid=row({state:"withheld",sourceResponseUrl:"https://evil.test",nativeQuantity:"unreviewed"});assert.equal(Client.normalizeResponse(envelope([old,invalid]),{now}).datedPublications.length,0);});
test("Distinct native groups are retained separately even when names repeat",()=>{const a=row(),b=row({groupOrdinal:5,nativeQuantity:"150 Gramm",pack:"150 g",packAmount:150,price:1.95,displayedPrice:1.95,previousPublishedPrice:2.25,nativeBasePrice:"13,00 Euro/kg"});assert.equal(Client.normalizeResponse(envelope([a,b]),{now}).datedPublications.length,2);assert.equal(Client.normalizeResponse(envelope([a,b]),{now,request:{pack:"150 g"}}).datedPublications.length,1);});
test("Dated envelope is bounded, immutable and separated from canonical coverage",()=>{const input=envelope([row()]),before=JSON.stringify(input),out=Client.normalizeResponse({...input,datedPublicationCoverage:{coverageComplete:true,publicationGroups:9000}},{now});assert.equal(out.datedPublications.length,1);assert.equal(out.datedPublicationCoverage.publicationGroups,1);assert.equal(out.datedPublicationCoverage.coverageComplete,false);assert.equal(out.datedPublicationCoverage.fullAssortment,false);assert.equal(out.items,undefined);assert.equal(JSON.stringify(input),before);assert.equal(Client.normalizeResponse({...input,datedPublications:undefined},{now}).datedPublications.length,0);for(const raw of[null,{...input,ok:false},{...input,city:"Potsdam"},{...input,country:"AT"},{...input,datedPublications:{}},{...input,datedPublications:Array(25).fill(row())}])assert.equal(Client.normalizeResponse(raw,{now}).ok,false);});
test("Berlin union adds dated groups while ordinary offer candidate remains closed",()=>{const raw=envelope([row()]),out=Berlin.normalizeResponse(raw,{now,request:{search:"Cashew",pack:"200 g"}});assert.equal(out.items.length,0);assert.equal(out.publications.length,0);assert.equal(out.datedPublications.length,1);assert.equal(out.datedPublicationCoverage.publicationGroups,1);assert.equal(Berlin.candidate(row(),{now}),null);assert.equal(Berlin.request({search:"Cashew",scopeChannel:CHANNEL}).scopeChannel,CHANNEL);assert.equal(Berlin.normalizeResponse(raw,{now,request:{gtin:"4008400401621"}}).datedPublications.length,0);});
test("UMD export validates without fetch or product-selection helpers",()=>{const context={window:{},Intl,Date};vm.runInNewContext(fs.readFileSync(require.resolve("../app/lidl-reference-client"),"utf8"),context);assert(context.window.CaddyLidlReferenceClient.candidate(row(),{now}));assert.equal(typeof context.window.CaddyLidlReferenceClient.create,"undefined");assert.equal(typeof context.window.fetch,"undefined");});
test("Real original article parser and independent client agree on all 20 fixed groups",()=>{const Pub=require("../lidl-price-publications"),fixture=require("./helpers/lidl-capture-fixture").fixture,original=fixture(),before=JSON.stringify(original),parsed=Pub.parseCapture(original,{now:"2026-10-02T18:00:00Z"}),out=Client.normalizeResponse(envelope(parsed.datedPublications),{now});assert.equal(JSON.stringify(original),before);assert.equal(parsed.datedPublications.length,20);assert.equal(out.datedPublications.length,20);assert.deepEqual(out.datedPublications.map(x=>x.publication.groupOrdinal),[1,2,3,4,5,6,7,9,11,12,13,14,15,16,18,20,21,22,23,24]);for(const {publication:p} of out.datedPublications){assert.equal(p.gtin,null);assert.equal(p.retailerSku,null);assert.equal(p.current,false);assert.equal(p.sourcePublishedDate,PUBLISHED);}assert.equal(Client.normalizeResponse(envelope(parsed.datedPublications),{now,request:{pack:"9 x 0.33 l"}}).datedPublications.length,1);assert.equal(Client.normalizeResponse(envelope(parsed.datedPublications),{now,request:{pack:"2.97 l"}}).datedPublications.length,0);});
console.log("lidl-reference-client: "+checks+" focused groups passed; synthetic adversarial DTOs plus stored original article, no retailer requests");
