const assert=require("assert"),O=require("../open-prices-refresh"),Client=require("../open-prices-client"),Persist=require("../external-price-import"),Runner=require("../price-refresh-runner");
(async()=>{
 let inserts=0;const pool={query:async(sql,args)=>{if(sql.startsWith("INSERT INTO price_import_batches"))return{rows:[{id:"b1"}]};if(sql.startsWith("INSERT INTO price_observations")){inserts++;return{rowCount:1,rows:[]}}return{rows:[],rowCount:1}}};const fetchImpl=async url=>({ok:true,status:200,json:async()=>({page:1,pages:1,size:1,total:1,items:[{id:1,price:2.99,currency:"EUR",date:"2026-09-30",proof_id:4,product:{code:"3017620422003",product_name:"Nutella",quantity:"450 g"},location:{id:12,name:"REWE",city:"Berlin",country:"Deutschland"}}]})});const x=await O.refresh({pool,targets:[{productCode:"3017620422003"}],fetchImpl});assert.strictEqual(x.targets,1);assert.strictEqual(x.received,1);assert.strictEqual(x.accepted,1);assert.strictEqual(inserts,1);
 const originalFetch=Client.fetchAll,originalPersist=Persist.persist,targets=[{productCode:"target-a"},{productCode:"target-b"}],queries=[];
 const bookkeepingPool={query:async(sql,args=[])=>{queries.push({sql,args});if(sql.includes("RETURNING consecutive_failures"))return{rows:[{consecutive_failures:1}],rowCount:1};return{rows:[],rowCount:1}}};
 try{
  Client.fetchAll=async target=>{throw new Error("network-down-"+target.productCode)};Persist.persist=async()=>({received:0,accepted:0,rejected:0,duplicates:0});
  await assert.rejects(()=>O.refresh({pool:bookkeepingPool,targets,pauseMs:0}),error=>{assert(error instanceof AggregateError);assert.strictEqual(error.code,"open-prices-target-refresh-all-failed");assert.strictEqual(error.errors.length,2);assert.strictEqual(error.result.failedTargets,2);assert.strictEqual(error.result.succeededTargets,0);return true});
  assert.strictEqual(queries.filter(q=>q.sql.startsWith("INSERT INTO price_refresh_target_failures")&&q.sql.includes("last_error")).length,2,"Every failed target must retain its failure state");assert(queries.at(-1).sql.startsWith("INSERT INTO price_refresh_checkpoints"),"The queue checkpoint must be saved before reporting complete failure");
  const runner=await Runner.runOne("Open Prices",{}, {"Open Prices":()=>O.refresh({pool:bookkeepingPool,targets,pauseMs:0})},{force:true});assert.strictEqual(runner.ok,false);assert.strictEqual(runner.state.consecutiveFailures,1);assert.strictEqual(runner.state.lastSuccessAt,undefined,"A wholly failed refresh must not become a source success");
  Client.fetchAll=async target=>{if(target.productCode==="target-a")throw new Error("one-target-down");return{accepted:[],rejected:[],pages:[]}};const partial=await O.refresh({pool:bookkeepingPool,targets,pauseMs:0});assert.strictEqual(partial.failedTargets,1);assert.strictEqual(partial.succeededTargets,1);assert.strictEqual(partial.accepted,0,"A successful empty response still completes a target");
  let requests=0;Client.fetchAll=async()=>{requests++;throw new Error("A cooldown target must not fetch")};const cooldownPool={query:async(sql)=>({rows:sql.startsWith("SELECT cooldown_until")?[{cooldownUntil:"2099-01-01T00:00:00Z"}]:[],rowCount:1})};const cooldown=await O.refresh({pool:cooldownPool,targets,pauseMs:0});assert.strictEqual(requests,0);assert.strictEqual(cooldown.cooldownSkipped,2);assert.strictEqual(cooldown.failedTargets,0);assert.strictEqual(cooldown.succeededTargets,0);assert.strictEqual((await O.refresh({pool:bookkeepingPool,targets:[]})).targets,0);
 }finally{Client.fetchAll=originalFetch;Persist.persist=originalPersist}
 console.log("open-prices-refresh: imports, complete failure propagation after bookkeeping, partial success and cooldown skips OK");
})().catch(e=>{console.error(e);process.exit(1)});
