"use strict";
const assert=require("assert"),C=require("../open-prices-inventory-client");
const today="2026-09-30",base={id:1,date:today,price:1.99,currency:"EUR",product_code:"3017620422003",product:{code:"3017620422003",product_name:"Nutella",product_quantity:450,product_quantity_unit:"g"},location_id:12,location:{id:12,osm_address_country_code:"DE",osm_name:"EDEKA"},proof_id:8,proof:{id:8,image_md5_hash:"a".repeat(32)},duplicate_of:null};
const row=(id,patch={})=>({...base,id,...patch});
function response(items,page=1,pages=1,total=items.length){return{ok:true,status:200,json:async()=>({items,page,pages,size:100,total})}}
assert.strictEqual(C.params({today}).get("date__gte"),"2026-09-23");assert.strictEqual(C.params({today}).get("date__lte"),today);assert.strictEqual(C.params({today}).get("country"),null);assert.strictEqual(C.params({today}).get("order_by"),"-date,-id");
assert.strictEqual(C.params({today,locationIds:[12,"13",12]}).get("location_id__in"),"12,13");assert.strictEqual(C.normalizeInput({today,since:"2020-01-01",maxPages:500}).since,"2026-09-23");assert.strictEqual(C.normalizeInput({today,maxPages:500}).maxPages,20);
assert.strictEqual(C.germanLocation({osm_address_country:"Deutschland"}),true);assert.strictEqual(C.germanLocation({osm_address_country:"Germany"}),true);assert.strictEqual(C.germanLocation({osm_address_country_code:"FR",osm_address_country:"Deutschland"}),false);assert.strictEqual(C.germanLocation({}),false);
for(const bad of ["2026-02-30","2026-13-01","2026-1-01",null])assert.strictEqual(C.validDate(bad),false);
assert.throws(()=>C.params({today:"2026-02-30"}),/invalid-today/);assert.throws(()=>C.params({today,locationIds:[12,"garbage"]}),/invalid-locations/);assert.throws(()=>C.params({today,cursor:{nextPage:2,since:"2026-09-20",until:today,locationIds:""}}),/invalid-cursor/);
(async()=>{
 let calls=0;const source=async(url)=>{calls++;const page=Number(new URL(url).searchParams.get("page"));assert.strictEqual(new URL(url).searchParams.get("currency"),"EUR");return page===1?response([row(1),row(2,{location:{osm_address_country_code:"FR"}}),row(3,{date:"2026-09-22"}),row(4,{date:"2026-10-01"}),row(5,{currency:"USD"}),row(6,{price:Infinity}),row(7,{duplicate_of:1}),row(8,{date:"2026-02-30"})],1,2,10):response([row(1),row(9,{price:2.49})],2,2,10)};
 const collected=await C.fetchInventory({today},source);assert.strictEqual(calls,2);assert.strictEqual(collected.ok,true);assert.strictEqual(collected.complete,true);assert.strictEqual(collected.nextPage,null);assert.deepStrictEqual(collected.items.map(r=>r.id),[1,9]);assert.strictEqual(collected.items[0].product,base.product);assert.strictEqual(collected.received,10);assert.strictEqual(collected.total,10);assert.strictEqual(collected.coverage.withGtin,2);assert.strictEqual(collected.coverage.withPack,2);assert.strictEqual(collected.coverage.proofs,1);assert.strictEqual(collected.rejected.length,8);
 const scoped=await C.fetchInventory({today,locationIds:[13]},async()=>response([row(1)]));assert.strictEqual(scoped.items.length,0);assert(scoped.rejected[0].reasons.includes("location-outside-scope"));
 const first=await C.fetchInventory({today,maxPages:1},async()=>response([row(1)],1,2,2));assert.strictEqual(first.complete,false);assert.strictEqual(first.cursor.nextPage,2);const resumed=await C.fetchInventory({today,cursor:first.cursor},async(url)=>{assert.strictEqual(new URL(url).searchParams.get("page"),"2");return response([row(2)],2,2,2)});assert.deepStrictEqual(resumed.items.map(x=>x.id),[2]);assert.strictEqual(resumed.complete,true);
 let attempts=0;const failed=await C.fetchInventory({today,retries:0},async(url)=>{const p=Number(new URL(url).searchParams.get("page"));attempts++;if(p===2)throw new Error("unavailable");return response([row(1)],1,3,3)});assert.strictEqual(attempts,2);assert.strictEqual(failed.ok,false);assert.strictEqual(failed.items.length,1);assert.strictEqual(failed.cursor.nextPage,2);assert.strictEqual(failed.error,"unavailable");
 const invalid=await C.fetchInventory({today,retries:0},async()=>response([row(1)],2,2,2));assert.strictEqual(invalid.ok,false);assert.match(invalid.error,/invalid-pagination/);assert.strictEqual(invalid.cursor.nextPage,1);
 let retries=0;const retried=await C.fetchInventory({today,baseDelayMs:50},async()=>{retries++;return retries===1?{ok:false,status:503,headers:{get:()=>"0"}}:response([row(1)])});assert.strictEqual(retries,2);assert.strictEqual(retried.ok,true);
 let cancelled=false,released=false;const oversized=await C.fetchInventory({today,retries:0},async()=>({ok:true,status:200,body:{getReader:()=>({read:async()=>({done:false,value:new Uint8Array(5*1024*1024+1)}),cancel:()=>{cancelled=true},releaseLock:()=>{released=true}})}}));assert.strictEqual(oversized.ok,false);assert.match(oversized.error,/body-too-large/);assert.strictEqual(cancelled,true);assert.strictEqual(released,true);
 const began=Date.now();const stalledBody=await C.fetchInventory({today,timeoutMs:1000,retries:0},async(url,options)=>({ok:true,status:200,json:()=>new Promise((resolve,reject)=>options.signal.addEventListener("abort",()=>reject(new Error("body-aborted")),{once:true}))}));assert.strictEqual(stalledBody.error,"body-aborted");assert(Date.now()-began<2000);
 const empty=await C.fetchInventory({today},async()=>response([]));assert.strictEqual(empty.complete,true);assert.strictEqual(empty.items.length,0);
 console.log("open-prices-inventory-client: bounded current Germany collection, country and schema gates, retries and resumable cursor OK");
})().catch(e=>{console.error(e);process.exit(1)});
