const assert=require("assert"),O=require("../open-prices-refresh"),Client=require("../open-prices-client"),Persist=require("../external-price-import"),Runner=require("../price-refresh-runner"),Canonical=require("../canonical-inventory-import");
const today="2026-09-30";
(async()=>{
 let inserts=0,values,canonicalCalls=0;const pool={query:async(sql,args)=>{if(sql.startsWith("INSERT INTO price_import_batches"))return{rows:[{id:"b1"}]};if(sql.startsWith("INSERT INTO price_observations")){inserts++;values=args;return{rowCount:1,rows:[]}}return{rows:[],rowCount:1}}};
 const raw={id:1,type:"PRODUCT",price:2.99,currency:"EUR",date:today,proof_id:4,proof:{id:4,type:"PRICE_TAG",draft:false,date:today,currency:"EUR",location_id:12,location_osm_id:1234567,location_osm_type:"NODE"},product:{code:"3017620422003",product_name:"Nutella",quantity:"450 g"},location:{id:12,type:"OSM",osm_id:1234567,osm_type:"NODE",osm_tag_key:"shop",osm_tag_value:"supermarket",osm_brand:"REWE",osm_name:"REWE",osm_address_city:"Berlin",osm_address_country:"Deutschland",osm_address_country_code:"DE",osm_lat:52.52,osm_lon:13.4}};
 const originalCanonical=Canonical.prepare;
 try{
  Canonical.prepare=async(_pool,items,meta)=>{canonicalCalls++;assert.strictEqual(items[0],raw,"The target coordinator must retain original source identity metadata");assert.strictEqual(meta.sourceId,"Open Prices");const p=Canonical.productCandidate(raw),s=Canonical.storeCandidate(raw,[{id:"merchant",name:"REWE",active:true}]);assert(p.ok&&s.ok);return{accepted:[{raw,productId:"catalog-product",storeId:"exact-new-store",gtin:p.gtin,product:p.name,brand:p.brand,pack:"450 g",packAmount:450,packUnit:"g",packCount:1,merchant:s.merchant.name,region:s.region,externalProductId:p.externalProductId,externalLocationId:s.externalLocationId}],rejected:[],partial:[],counts:{productsCreated:0,storesCreated:1,productMappingsCreated:1,storeMappingsCreated:1}}};
  const fetchImpl=async url=>{const params=new URL(url).searchParams;assert.strictEqual(params.get("date__lte"),today);return{ok:true,status:200,json:async()=>({page:1,pages:1,size:100,total:1,items:[raw]})}};
  const x=await O.refresh({pool,today,targets:[{productCode:"3017620422003"}],fetchImpl,pauseMs:0});assert.strictEqual(x.targets,1);assert.strictEqual(x.received,1);assert.strictEqual(x.accepted,1);assert.strictEqual(inserts,1);assert.strictEqual(canonicalCalls,1);assert.strictEqual(x.catalog.storesCreated,1);
  assert.strictEqual(values[3],"exact-new-store");assert.strictEqual(values[5],"catalog-product");assert.strictEqual(values[24],"observed");assert.strictEqual(values[33],"Berlin, DE");assert.strictEqual(values[14],"openprices:proof:4");
 }finally{Canonical.prepare=originalCanonical}
 const originalFetch=Client.fetchAll,originalPersist=Persist.persist,targets=[{productCode:"3017620422003"},{productCode:"4006381333931"}],queries=[];
 const bookkeepingPool={query:async(sql,args=[])=>{queries.push({sql,args});if(sql.includes("RETURNING consecutive_failures"))return{rows:[{consecutive_failures:1}],rowCount:1};return{rows:[],rowCount:1}}};
 try{
  Client.fetchAll=async target=>{throw new Error("network-down-"+target.productCode)};Persist.persist=async()=>({received:0,accepted:0,rejected:0,duplicates:0});
  await assert.rejects(()=>O.refresh({pool:bookkeepingPool,today,targets,pauseMs:0}),error=>{assert(error instanceof AggregateError);assert.strictEqual(error.code,"open-prices-target-refresh-all-failed");assert.strictEqual(error.errors.length,2);assert.strictEqual(error.result.failedTargets,2);assert.strictEqual(error.result.succeededTargets,0);return true});
  assert.strictEqual(queries.filter(q=>q.sql.startsWith("INSERT INTO price_refresh_target_failures")&&q.sql.includes("last_error")).length,2,"Every failed target must retain its failure state");assert(queries.at(-1).sql.startsWith("INSERT INTO price_refresh_checkpoints"),"The queue checkpoint must be saved before reporting complete failure");
  const runner=await Runner.runOne("Open Prices",{}, {"Open Prices":()=>O.refresh({pool:bookkeepingPool,today,targets,pauseMs:0})},{force:true});assert.strictEqual(runner.ok,false);assert.strictEqual(runner.state.consecutiveFailures,1);assert.strictEqual(runner.state.lastSuccessAt,undefined,"A wholly failed refresh must not become a source success");
  Client.fetchAll=async target=>{if(target.productCode==="3017620422003")throw new Error("one-target-down");return{accepted:[],rejected:[],rawItems:[],pages:[]}};const partial=await O.refresh({pool:bookkeepingPool,today,targets,pauseMs:0});assert.strictEqual(partial.failedTargets,1);assert.strictEqual(partial.succeededTargets,1);assert.strictEqual(partial.accepted,0,"A successful empty response still completes a target");
  let requests=0;Client.fetchAll=async()=>{requests++;throw new Error("A cooldown target must not fetch")};const cooldownPool={query:async(sql)=>({rows:sql.startsWith("SELECT cooldown_until")?[{cooldownUntil:"2099-01-01T00:00:00Z"}]:[],rowCount:1})};const cooldown=await O.refresh({pool:cooldownPool,targets,pauseMs:0});assert.strictEqual(requests,0);assert.strictEqual(cooldown.cooldownSkipped,2);assert.strictEqual(cooldown.failedTargets,0);assert.strictEqual(cooldown.succeededTargets,0);assert.strictEqual((await O.refresh({pool:bookkeepingPool,targets:[]})).targets,0);
 }finally{Client.fetchAll=originalFetch;Persist.persist=originalPersist}
 console.log("open-prices-refresh: source → safe canonical identity → observed store price; complete failure bookkeeping, partial success and cooldown skips OK");
})().catch(e=>{console.error(e);process.exit(1)});
