"use strict";
const assert=require("assert/strict"),{Readable}=require("stream"),{gzipSync}=require("zlib"),C=require("../open-food-facts-catalog-client");
const header=["code","product_name","brands","quantity","countries_tags","categories_tags","unique_scans_n","popularity_tags","last_modified_t"],good=["4002971253504","Grand Dessert Double Coffee","Ehrmann","190 g","en:germany","en:desserts",42,"top-1000-de-scans-2025",1790726400];
const csvCell=x=>/[\t\r\n"]/.test(String(x))?'"'+String(x).replace(/"/g,'""')+'"':String(x),tsv=rows=>rows.map(row=>row.map(csvCell).join("\t")).join("\r\n")+"\r\n";
function source(rows,{chunkSize=7,etag="fixture-export",lastModified="Wed, 30 Sep 2026 10:00:00 GMT"}={}){const compressed=gzipSync(Buffer.from(tsv([header,...rows])));return async(url,opts)=>{assert.equal(url,C.SOURCE_URL);assert(opts.signal);const chunks=[];for(let i=0;i<compressed.length;i+=chunkSize)chunks.push(compressed.subarray(i,i+chunkSize));return{ok:true,status:200,headers:{get:k=>k==="etag"?etag:k==="last-modified"?lastModified:null},body:Readable.from(chunks)}}}
(async()=>{
 const parsed=[],parser=new C.TsvParser(row=>parsed.push(row)),text=tsv([["one","quoted\ttab","line\nnew","escaped \"quote\"","Schröder"]]);for(const ch of text)parser.feed(ch);parser.finish();assert.deepEqual(parsed,[["one","quoted\ttab","line\nnew","escaped \"quote\"","Schröder"]]);assert.throws(()=>{const p=new C.TsvParser(()=>{});p.feed('"unfinished');p.finish()},/incomplete-csv/);
 const second=["4006381333931","Tofu Räuchert \"Natur\"\tBio\nMultipack","Bio Brand","2.0 x 175 g","en:france,en:germany","en:tofu,en:plant-based-foods",10,"",1790726400],foreign=[...good],badCode=[...good],unknownPack=[...good];foreign[0]="3017620422003";foreign[4]="en:france";badCode[0]="4002971253505";unknownPack[0]="3017620422003";unknownPack[3]="unknown";
 const result=await C.fetchCatalog({limit:100},source([good,second,foreign,badCode,unknownPack,good]));assert.equal(result.ok,true);assert.equal(result.complete,true);assert.equal(result.products.length,2);assert.equal(result.rowsRead,6);assert.deepEqual(result.products[1].countries_tags,["en:france","en:germany"]);assert.deepEqual(result.products[1].categories_tags,["en:tofu","en:plant-based-foods"]);assert.equal(result.products[1].product_name,second[1]);assert.equal(result.products[0].unique_scans_n,42);assert.equal(result.truthEligible,false);assert.equal(result.rejected["duplicate-gtin"],1);assert.equal(result.rejected["outside-germany-market"],1);assert.equal(result.cursor,null);
 const limited=await C.fetchCatalog({limit:1},source([good,second]));assert.equal(limited.products.length,1);assert.equal(limited.complete,true);assert.equal(limited.sourceExhausted,false);assert.equal(limited.reason,"product-limit");assert.equal(limited.cursor.rowsRead,1);const resumed=await C.fetchCatalog({limit:100,cursor:limited.cursor},source([good,second]));assert.equal(resumed.complete,true);assert.equal(resumed.sourceExhausted,true);assert.equal(resumed.products.length,1);assert.equal(resumed.products[0].code,second[0]);assert.equal(resumed.rowsRead,2);
 const selection=await C.fetchCatalog({limit:100,stopWhen:row=>row.code===good[0]},source([good,second]));assert.equal(selection.products.length,1);assert.equal(selection.complete,true);assert.equal(selection.sourceExhausted,false);assert.equal(selection.reason,"selection-goal");assert.equal(C.options({maxBytes:1536*1024*1024,maxDurationMs:900000}).maxDurationMs,900000);
 await assert.rejects(()=>C.fetchCatalog({cursor:limited.cursor},source([good],{etag:"changed-export"})),/export-changed/);assert.throws(()=>C.options({sourceUrl:"https://evil.example/catalog"}),/source-not-allowed/);assert.throws(()=>C.options({cursor:{rowsRead:1,sourceUrl:"https://evil.example"}}),/invalid-cursor/);
 const budget=await C.fetchCatalog({maxBytes:1},source([good]));assert.equal(budget.complete,false);assert.equal(budget.reason,"byte-budget");assert.equal(budget.products.length,0);assert.equal(budget.ok,true);
 const malformedRow=tsv([header])+good[0]+'\t"bad"trailing\tBrand\t190 g\ten:germany\ten:desserts\t1\t\t1790726400\r\n'+tsv([good]);const isolated=await C.fetchCatalog({},async()=>({ok:true,status:200,body:Readable.from([gzipSync(Buffer.from(malformedRow))])}));assert.equal(isolated.products.length,1);assert.equal(isolated.rejected["malformed-csv-row"],1);assert.equal(isolated.complete,true);
 const malformed=async()=>({ok:true,status:200,body:Readable.from([gzipSync(Buffer.from("wrong\tcolumns\n1\t2\n"))])});await assert.rejects(()=>C.fetchCatalog({},malformed),/required-columns/);await assert.rejects(()=>C.fetchCatalog({},async()=>({ok:false,status:503})),/http-503/);
 const started=Date.now(),stalled=await C.fetchCatalog({maxDurationMs:1000},async(url,opts)=>new Promise((resolve,reject)=>opts.signal.addEventListener("abort",()=>reject(new Error("aborted")),{once:true})));assert.equal(stalled.reason,"duration-budget");assert.equal(stalled.complete,false);assert(Date.now()-started<2000);
 console.log("open-food-facts-catalog-client: official gzip export, bounded TSV streaming, quoted Unicode records, Germany and identity gates, resumable export cursor, byte and time budgets OK");
})().catch(e=>{console.error(e);process.exitCode=1});
