"use strict";
const assert=require("node:assert/strict"),fs=require("node:fs"),path=require("node:path"),vm=require("node:vm"),{createRequire}=require("node:module"),Status=require("../price-source-status"),Sources=require("../price-sources").SOURCES,Wake=require("../price-refresh-wake-plan");
const NOW=Date.parse("2026-10-02T07:00:00Z"),NAME="REWE Berlin pickup",HIT="HIT Berlin store assortment",source=Sources[NAME],iso=t=>new Date(t).toISOString(),fn=()=>{},handlers={[NAME]:fn},e=(state={},options={handlers})=>Status.eligibility(NAME,source,state,NOW,options);let cases=0;
function check(callback){callback();cases++;}
check(()=>{const x=e();assert.equal(x.status,"eligible-by-schedule");assert.equal(x.eligibleAt,iso(NOW));assert.equal(x.handlerConfigured,true);});
check(()=>{const x=e({},{});assert.equal(x.handlerConfigured,null);assert.equal(x.eligibleBySchedule,true);assert.equal(x.exactStartTimeVerified,false);assert.equal(x.nativeHandlerReadinessVerified,false);});
check(()=>{const x=e({},{handlers:{}});assert.equal(x.status,"no-handler");assert.equal(x.eligibleBySchedule,false);assert.deepEqual(x.blockedBy,["no-handler"]);});
check(()=>assert.equal(e({},{handlers:{[source.type]:fn}}).handlerConfigured,true));
check(()=>assert.equal(e({},{handlers:{[NAME]:{},[source.type]:fn}}).handlerConfigured,false));
check(()=>assert.equal(e({},{handlers:{[NAME]:null,[source.type]:fn}}).handlerConfigured,true));
check(()=>{const x=e({nextAttemptAt:iso(NOW+7200000)});assert.equal(x.status,"waiting");assert.equal(x.sourceDueAt,iso(NOW+7200000));assert.equal(x.eligibleAt,iso(NOW+7200000));assert.deepEqual(x.blockedBy,["source-deadline"]);});
check(()=>{const x=e({nextAttemptAt:iso(NOW-5*3600000),lastAttemptAt:iso(NOW-4*3600000),consecutiveFailures:13});assert.equal(x.sourceDueAt,iso(NOW-5*3600000));assert.equal(x.failureBackoffUntil,iso(NOW+2*3600000));assert.equal(x.eligibleAt,iso(NOW+2*3600000));assert.deepEqual(x.blockedBy,["failure-backoff"]);});
check(()=>{const x=e({nextAttemptAt:iso(NOW+7200000),lastAttemptAt:iso(NOW),consecutiveFailures:1});assert.equal(x.eligibleAt,iso(NOW+7200000));assert.equal(x.failureBackoffUntil,iso(NOW+60000));assert.deepEqual(x.blockedBy,["source-deadline","failure-backoff"]);});
check(()=>{const x=e({lastAttemptAt:iso(NOW),consecutiveFailures:99,nextAttemptAt:iso(NOW+3600000)});assert.equal(x.failureBackoffUntil,iso(NOW+21600000));assert.equal(x.eligibleAt,iso(NOW+21600000));});
check(()=>{const x=e({lastSuccessAt:iso(NOW-600000),lastAttemptAt:iso(NOW),consecutiveFailures:0});assert.equal(x.sourceDueAt,iso(NOW-600000+900000));assert.equal(x.failureBackoffUntil,null);});
for(const owner of["own-worker","other-worker"])check(()=>{const x=e({nextAttemptAt:iso(NOW),leaseUntil:iso(NOW+900000),leaseOwner:owner});assert.equal(x.eligibleAt,iso(NOW+900000));assert.equal(x.leaseBlocksUntil,iso(NOW+900000));assert.deepEqual(x.blockedBy,["lease-held"]);assert(!JSON.stringify(x).includes(owner));});
check(()=>{const x=e({lastAttemptAt:iso(NOW),consecutiveFailures:3,nextAttemptAt:iso(NOW+60000),leaseUntil:iso(NOW+300000),leaseOwner:"worker"});assert.equal(x.eligibleAt,iso(NOW+300000));assert.deepEqual(x.blockedBy,["source-deadline","failure-backoff","lease-held"]);});
for(const delta of[-1,0])check(()=>{const x=e({nextAttemptAt:iso(NOW),leaseUntil:iso(NOW+delta),leaseOwner:"worker"});assert.equal(x.leaseBlocksUntil,null);assert.equal(x.eligibleBySchedule,true);});
check(()=>{const x=e({nextAttemptAt:new Date(NOW+60000),lastAttemptAt:new Date(NOW-60000),consecutiveFailures:1});assert.equal(x.eligibleAt,iso(NOW+60000));});
check(()=>{const x=Status.eligibility("disabled",{...source,active:false},{nextAttemptAt:iso(NOW+1000)},NOW,{handlers:{"disabled":fn}});assert.equal(x.status,"inactive");assert.equal(x.eligibleAt,null);assert.equal(x.eligibleBySchedule,false);});
for(const state of[{nextAttemptAt:"invalid"},{lastAttemptAt:"2026-10-02T08:00:00+01:00"},{lastSuccessAt:"2026-02-30T00:00:00Z"},{consecutiveFailures:1},{consecutiveFailures:-1},{consecutiveFailures:1.5},{consecutiveFailures:"3"},{leaseUntil:iso(NOW+1000)},{leaseOwner:"worker"},{leaseUntil:"invalid",leaseOwner:"worker"},[],"invalid"])check(()=>{const x=e(state);assert.equal(x.status,"invalid-state");assert.equal(x.eligibleAt,null);assert.equal(x.eligibleBySchedule,false);});
check(()=>{const x=Status.eligibility(NAME,source,{},NaN,{handlers});assert.equal(x.status,"invalid-state");assert(x.blockedBy.includes("invalid-scheduler-context"));});
check(()=>{const state={lastSuccessAt:iso(NOW-86400000),lastAttemptAt:iso(NOW-3600000),nextAttemptAt:iso(NOW+7200000),consecutiveFailures:3,lastAccepted:9,lastReceived:12,lastDurationMs:42,leaseOwner:"private-worker",leaseUntil:iso(NOW+1000),privateOriginal:{body:"PRIVATE HTML"},nativeState:{seenQuotes:{}}},before=structuredClone(state),x=Status.view({[NAME]:state},NOW,{handlers}).find(row=>row.name===NAME);assert.deepEqual(state,before);assert.equal(x.nextAttemptAt,state.nextAttemptAt);assert.equal(x.lastSuccessAt,state.lastSuccessAt);assert.equal(x.lastAccepted,9);assert.equal(x.freshness,"stale");assert.equal(x.freshnessBasis,"fetch-success");assert(!JSON.stringify(x).includes("PRIVATE HTML"));assert(!JSON.stringify(x).includes("private-worker"));assert(!JSON.stringify(x).includes("seenQuotes"));});
for(const state of[{},{nextAttemptAt:iso(NOW+60000)},{nextAttemptAt:iso(NOW-1000),lastAttemptAt:iso(NOW-60000),consecutiveFailures:3},{leaseUntil:iso(NOW+50000),leaseOwner:"worker"}, {lastSuccessAt:iso(NOW-700000)}])check(()=>{const p=Wake.inspect({[NAME]:state},handlers,{now:NOW,nextFallbackAt:NOW,owner:"worker",registry:{[NAME]:source}}).candidates[0],x=e(state);assert.equal(x.eligibleAt,iso(p.eligibleAt));assert.equal(x.eligibleBySchedule,p.eligibleAt<=NOW);});
async function httpCases(){
 const root=path.resolve("server.js"),nativeRequire=createRequire(root),state={[NAME]:{nextAttemptAt:new Date(NOW-5*3600000),lastAttemptAt:new Date(NOW-4*3600000),consecutiveFailures:13,lastSuccessAt:new Date(NOW-86400000)},[HIT]:{nextAttemptAt:new Date(NOW+60000)}},before=structuredClone(state);let writes=0,collects=0,batches=0;
 class TestDate extends Date{constructor(...args){super(...(args.length?args:[NOW]));}static now(){return NOW;}}
 const pool={query:async()=>{writes++;throw Error("No DB query outside stubbed persisted status");},end:async()=>{}},mocks={pg:{Pool:function(){return pool;}},http:{createServer:()=>({listening:false,close:cb=>cb?.()})},"./price-refresh-state-store":{loadAll:async()=>structuredClone(state)},"./price-refresh-targets":{fromDatabase:async()=>[]},"./external-location-targets":{fromDatabase:async()=>[]},"./canonical-gap-refresh-targets":{build:async()=>[]},"./price-refresh-runner":{runDue:async()=>{batches++;return{results:[]};}}};
 for(const[file,name]of[["./hit-price-refresh",HIT],["./aldi-assortment-refresh","ALDI Nord published assortment"],["./rewe-retailer-price-refresh",NAME]])mocks[file]={SOURCE:name,resumeAt:async()=>null,refresh:async()=>{collects++;assert.fail("No real source handler");}};
 mocks["./wolt-retailer-price-refresh"]={SOURCE:"Wolt EDEKA Berlin",resumeAt:async()=>null,createRefresh:()=>({SOURCE:"Wolt nahkauf Berlin Wrangelstraße",resumeAt:async()=>null,refresh:async()=>{collects++;assert.fail("No real source handler");}})};
 const module={exports:{}},processDouble={env:{DATABASE_URL:"postgres://LOCAL_TEST/scheduler_status_test",PRICE_INVENTORY_ENABLED:"false",PRODUCT_CATALOG_ENABLED:"false"},pid:42},require=file=>Object.hasOwn(mocks,file)?mocks[file]:nativeRequire(file);
 vm.runInNewContext(fs.readFileSync(root,"utf8"),{require,module,exports:module.exports,process:processDouble,console:{log(){},error(){}},Buffer,URL,Date:TestDate,Promise,setTimeout,clearTimeout,setInterval,clearInterval},{filename:root});
 const get=async()=>{let result;await module.exports.handle({method:"GET",url:"/v1/admin/price-sources/status"},{writeHead(code){assert.equal(code,200);},end(body){result=JSON.parse(body);}});return result;};
 const initial=await get();assert.equal(initial.sources.find(x=>x.name===NAME).schedulerEligibility.handlerConfigured,false);cases++;
 await module.exports.refreshInternetPrices("manual");const loaded=await get(),rewe=loaded.sources.find(x=>x.name===NAME),hit=loaded.sources.find(x=>x.name===HIT),receipt=loaded.sources.find(x=>x.name==="SPARKORB receipt");
 assert.equal(rewe.schedulerEligibility.handlerConfigured,true);assert.equal(rewe.schedulerEligibility.eligibleAt,iso(NOW+7200000));assert.deepEqual(rewe.schedulerEligibility.blockedBy,["failure-backoff"]);assert.equal(rewe.nextAttemptAt,iso(NOW-5*3600000));assert.equal(hit.schedulerEligibility.handlerConfigured,false);assert.equal(hit.schedulerEligibility.status,"no-handler");assert.equal(hit.schedulerEligibility.eligibleBySchedule,false);assert.equal(hit.nextAttemptAt,iso(NOW+60000));assert.deepEqual(loaded.collectionFocus.retailers,["PENNY","EDEKA","Lidl","ALDI","Kaufland","REWE"]);assert.equal(loaded.collectionFocus.coverageComplete,false);assert.equal(receipt.schedulerEligibility.status,"no-handler");assert.equal(receipt.schedulerEligibility.eligibleBySchedule,false);assert.equal(writes,0);assert.equal(collects,0);assert.equal(batches,1);assert.deepEqual(state,before);cases++;
}
httpCases().then(()=>console.log("price-source-status: "+cases+" scheduling/actual HTTP cases passed; no source calls, state mutations, price freshness or pause changes")).catch(error=>{console.error(error);process.exitCode=1;});
