"use strict";
const assert=require("assert/strict"),{randomUUID}=require("crypto"),{Pool}=require("pg");
const Coverage=require("../price-coverage-status"),Legacy=require("../legacy-rewe-provenance"),Targets=require("../price-refresh-targets"),Queue=require("../stable-coverage-queue"),Refresh=require("../open-prices-refresh"),Current=require("../current-price-query-service");
// Recent coverage is tested against PostgreSQL's real clock; source/date-window
// fixtures follow today's Berlin date, and precise captures are already past.
const fixtureNow=new Date(),capturedAt=new Date(fixtureNow.getTime()-1000).toISOString(),today=Current.today(fixtureNow),offsetDay=days=>new Date(Date.parse(today+"T00:00:00Z")+days*864e5).toISOString().slice(0,10),futureDay=offsetDay(1),expiredDay=offsetDay(-9),yesterday=offsetDay(-1);
// The provenance repair intentionally targets a fixed historical importer cutoff.
const legacyDay="2026-09-30";
function testGtin(index){const body=String(950000000000+index),sum=[...body].reduce((total,digit,position)=>total+Number(digit)*(position%2?3:1),0);return body+(10-sum%10)%10}
async function main(){
 const connectionString=process.env.DATABASE_URL;assert(connectionString,"DATABASE_URL is required");const database=new URL(connectionString);assert.equal(database.hostname,"localhost");assert(database.pathname.endsWith("_test"),"Only a dedicated local PostgreSQL test database is allowed");
 const pool=new Pool({connectionString,ssl:false,connectionTimeoutMillis:5000});let testError;
 try{
  const selected=(await pool.query(`SELECT * FROM (SELECT p.id,p.gtin,p.name,p.brand,p.pack_amount::float AS amount,p.pack_unit AS unit,p.pack_count::float AS count,cm.basket_family AS family,row_number() OVER(PARTITION BY CASE WHEN cm.basket_family='eggs' THEN 'eggs' ELSE 'milk' END ORDER BY p.gtin) AS family_rank FROM products p JOIN product_catalog_metadata cm ON cm.product_id=p.id WHERE cm.source_id='Open Food Facts' AND cm.countries_tags ? 'en:germany' AND p.pack_amount>0 AND p.pack_count>0 AND cm.basket_family IN ('milk','milk_fresh','milk_uht','eggs') AND NOT EXISTS(SELECT 1 FROM price_observations o WHERE o.product_id=p.id OR o.gtin=p.gtin)) candidates WHERE family_rank<=3 ORDER BY gtin`)).rows;
  const eggs=selected.find(row=>row.family==="eggs"),milk=selected.filter(row=>row.family!=="eggs").slice(0,3);assert(eggs,"Run the real DE snapshot catalog integration before this test");assert.equal(eggs.unit,"piece");assert.equal(milk.length,3);const products=[milk[0],milk[1],milk[2],eggs];
  // A real source-shaped PriceFull fixture targets an already imported OFF identity and creates its precise new DE branch.
  const sourceProduct=products[2],sourcePack=(sourceProduct.count>1?sourceProduct.count+" x ":"")+sourceProduct.amount+" "+sourceProduct.unit,locationId=990501,osmId=990502,proofId=990503;
  const sourceRow={id:990504,type:"PRODUCT",product_code:sourceProduct.gtin,product_id:990505,product:{id:990505,code:sourceProduct.gtin,product_name:sourceProduct.name,brands:sourceProduct.brand,quantity:sourcePack},location_id:locationId,location_osm_id:osmId,location_osm_type:"NODE",location:{id:locationId,type:"OSM",osm_id:osmId,osm_type:"NODE",osm_name:"REWE",osm_brand:"REWE",osm_tag_key:"shop",osm_tag_value:"supermarket",osm_address_country:"Deutschland",osm_address_country_code:"DE",osm_address_road:"Coverage Source TEST",osm_address_house_number:"1",osm_address_city:"Berlin",osm_address_postcode:"10115",osm_lat:52.52,osm_lon:13.405},price:1.79,price_per:"UNIT",price_is_discounted:false,currency:"EUR",date:today,proof_id:proofId,proof:{id:proofId,type:"PRICE_TAG",draft:false,date:today,currency:"EUR",location_id:locationId,location_osm_id:osmId,location_osm_type:"NODE",image_md5_hash:"e".repeat(32),owner:"coverage-postgres-fixture"},owner:"coverage-postgres-fixture",duplicate_of:null};
  const beforeSource=(await pool.query("SELECT (SELECT count(*)::int FROM products) AS products,(SELECT count(*)::int FROM stores) AS stores")).rows[0];
  const refreshed=await Refresh.refresh({pool,today,targets:[{productCode:sourceProduct.gtin,priority:100}],maxTargets:1,maxPages:1,maxRequestsPerTarget:1,pauseMs:0,fetchImpl:async url=>{const params=new URL(url).searchParams;assert.equal(params.get("product_code"),sourceProduct.gtin);assert.equal(params.get("date__lte"),today);assert.equal(params.get("currency"),"EUR");return{ok:true,status:200,json:async()=>({items:[sourceRow],page:1,pages:1,size:100,total:1})}}});
  assert.equal(refreshed.accepted,1,JSON.stringify(refreshed));assert.equal(refreshed.catalog.productsCreated,0);assert.equal(refreshed.catalog.storesCreated,1);
  const sourceFact=(await pool.query("SELECT o.product_id AS product,o.store_id AS store,o.price::float AS price,o.status,o.proof_verified AS reviewed,o.identity_verified AS identity,s.country,s.external_id AS external,p.name FROM price_observations o JOIN stores s ON s.id=o.store_id JOIN products p ON p.id=o.product_id WHERE o.proof=$1",["openprices:proof:"+proofId])).rows[0];assert(sourceFact);assert.equal(sourceFact.product,sourceProduct.id);assert.equal(sourceFact.status,"observed");assert.equal(sourceFact.reviewed,false);assert.equal(sourceFact.identity,false);assert.equal(sourceFact.country,"DE");assert.equal(sourceFact.external,"osm:node:"+osmId);assert.equal(sourceFact.name,sourceProduct.name);
  const afterSource=(await pool.query("SELECT (SELECT count(*)::int FROM products) AS products,(SELECT count(*)::int FROM stores) AS stores")).rows[0];assert.equal(afterSource.products,beforeSource.products);assert.equal(afterSource.stores,beforeSource.stores+1);
  const exact=await Current.compareCurrentPrices(pool,{product:sourceProduct.name,productId:sourceProduct.id,gtin:sourceProduct.gtin,brand:sourceProduct.brand,pack:sourcePack,merchants:["REWE"],storeId:sourceFact.store,today},{includeRefreshTargets:false});assert.equal(exact.ok,true,JSON.stringify(exact));assert.equal(exact.results[0].state,"observed");assert.equal(exact.results[0].price,1.79);assert.equal(exact.results[0].storeId,sourceFact.store);assert.equal(exact.results[0].proofVerified,false);
  const merchantId=randomUUID(),inactiveMerchantId=randomUUID(),storeId=randomUUID(),inactiveStoreId=randomUUID(),foreignStoreId=randomUUID(),inactiveMerchantStoreId=randomUUID();
  await pool.query("INSERT INTO merchants(id,name,normalized_name,active) VALUES($1,'REWE Coverage TEST','rewe-coverage-test',true),($2,'Inactive Coverage TEST','inactive-coverage-test',false)",[merchantId,inactiveMerchantId]);
  await pool.query("INSERT INTO stores(id,merchant_id,country,active,address) VALUES($1,$5,'DE',true,'Coverage TEST 1'),($2,$5,'DE',false,'Coverage TEST 2'),($3,$5,'FR',true,'Coverage TEST 3'),($4,$6,'DE',true,'Coverage TEST 4')",[storeId,inactiveStoreId,foreignStoreId,inactiveMerchantStoreId,merchantId,inactiveMerchantId]);
  async function observation(product=products[0],patch={}){
   const id=randomUUID(),row={id,key:"gtin:"+product.gtin,store:"REWE Coverage TEST",store_id:storeId,product_id:product.id,gtin:product.gtin,price:1.29,per:"item",date:today,kind:"external",source:"Open Prices",source_id:"Open Prices",source_type:"open_data",evidence_purpose:"current-price",truth_eligible:true,product:product.name,proof:"coverage-test:"+id,proof_type:"PRICE_TAG",proof_hash:"coverage-hash:"+id,observed_at:capturedAt,identity_verified:false,proof_verified:false,currency:"EUR",status:"observed",pack_amount:product.amount,pack_unit:product.unit,...patch};
   const columns=Object.keys(row),params=columns.map((_,index)=>"$"+(index+1));await pool.query("INSERT INTO price_observations("+columns.join(",")+") VALUES("+params.join(",")+")",Object.values(row));return row;
  }
  const baseline=await Coverage.status(pool,{today}),familyBaseline=new Map(baseline.families.map(row=>[row.family,row]));assert(baseline.stapleProducts>=6000);
  const attached=await observation(),afterAttached=await Coverage.status(pool,{today});
  assert.equal(afterAttached.currentEvidenceObservations,baseline.currentEvidenceObservations+1);assert.equal(afterAttached.productsWithCurrentEvidence,baseline.productsWithCurrentEvidence+1);assert.equal(afterAttached.proofReviewedObservations,baseline.proofReviewedObservations);assert.equal(afterAttached.productsWithReviewedEvidence,baseline.productsWithReviewedEvidence,"One source proof never becomes reviewed automatically");
  await observation(products[0],{identity_verified:true,proof_verified:true});await observation(products[1],{identity_verified:true,proof_verified:false});await observation(products[3]);
  const covered=await Coverage.status(pool,{today});assert.equal(covered.currentEvidenceObservations,baseline.currentEvidenceObservations+4);assert.equal(covered.productsWithCurrentEvidence,baseline.productsWithCurrentEvidence+3);assert.equal(covered.proofReviewedObservations,baseline.proofReviewedObservations+1);assert.equal(covered.productsWithReviewedEvidence,baseline.productsWithReviewedEvidence+1);assert.equal(covered.staplesWithCurrentEvidence,baseline.staplesWithCurrentEvidence+3);assert.equal(covered.storesWithCurrentEvidence,baseline.storesWithCurrentEvidence+1);
  const eggsFamily=covered.families.find(row=>row.family==="eggs");assert.equal(eggsFamily.currentEvidenceProducts,familyBaseline.get("eggs").currentEvidenceProducts+1,"Real canonical eggs use piece packs and must count as evidence");
  const unknownId=randomUUID(),unknownGtin=testGtin(1);await pool.query("INSERT INTO products(id,canonical_key,gtin,name,identity_status) VALUES($1,$2,$3,'Coverage TEST unknown pack','verified')",[unknownId,"gtin:"+unknownGtin,unknownGtin]);
  const excluded=[{truth_eligible:false},{evidence_purpose:"corroboration"},{source_type:"aggregated_open_data"},{date:futureDay,observed_at:futureDay+"T12:00:00Z"},{date:expiredDay,observed_at:expiredDay+"T12:00:00Z"},{currency:"USD"},{store_id:null},{store_id:inactiveStoreId},{store_id:foreignStoreId},{store_id:inactiveMerchantStoreId},{gtin:products[0].gtin},{proof:""},{proof_type:"retailer_offer"},{price:0},{price:"Infinity"},{valid_from:futureDay},{valid_to:yesterday}];
  for(const patch of excluded)await observation(products[2],patch);await observation({id:unknownId,gtin:unknownGtin,name:"Coverage TEST unknown pack",amount:null,unit:null});
  const afterExcluded=await Coverage.status(pool,{today});for(const field of["currentEvidenceObservations","productsWithCurrentEvidence","proofReviewedObservations","productsWithReviewedEvidence","staplesWithCurrentEvidence","storesWithCurrentEvidence"])assert.equal(afterExcluded[field],covered[field],field+" must reject noncurrent/noncanonical/nonDE evidence");
  const originalLast=(await pool.query("SELECT observed_at FROM price_observations WHERE id=$1",[attached.id])).rows[0].observed_at;
  await observation(products[0],{truth_eligible:false,evidence_purpose:"corroboration",source_type:"aggregated_open_data",date:today,observed_at:today+"T16:00:00Z"});
  const query=Targets.querySpec({fullCoverage:true}),raw=(await pool.query(query.sql,query.params)).rows,actual=raw.find(row=>row.productId===products[0].id);assert.equal(actual.observationCount,2,"Product+GTIN match counts each observation once; historical false/corroboration evidence contributes zero");assert.equal(new Date(actual.lastObservedAt).getTime(),new Date(originalLast).getTime());
  await observation(products[0],{product_id:null});const fallback=(await pool.query(query.sql,query.params)).rows.find(row=>row.productId===products[0].id);assert.equal(fallback.observationCount,3,"Legacy GTIN-only observation is counted once without duplicating exact product observations");
  const all=await Targets.fromDatabase(pool,{fullCoverage:true,limit:250,candidateLimit:2000});assert(all.length>6000,"The real PostgreSQL candidate query must reach beyond6,000 rather than stop at2,000/5,000");assert(all.some(row=>row.productCode===products[3].gtin));let checkpoint={},seen=new Set(),runs=0;while(seen.size<all.length&&runs<700){const pick=Queue.select(all,checkpoint,20,.25);for(const target of pick.selected)seen.add(target.productCode);checkpoint=pick.next;runs++}assert.equal(seen.size,all.length);

  // The exact known legacy signature is repaired. Similar sources/URLs and native source dates are preserved.
  const legacyBatchId=randomUUID(),mismatchBatchId=randomUUID(),legacyUrl=Legacy.URLS[0];
  await pool.query("INSERT INTO price_import_batches(id,source,source_url,status,received) VALUES($1,$3,$4,'finished',10),($2,'different-source',$4,'finished',1)",[legacyBatchId,mismatchBatchId,Legacy.SOURCE,legacyUrl]);
  const legacyPatch={source:Legacy.SOURCE,source_id:Legacy.SOURCE,source_type:"aggregated_open_data",evidence_purpose:"corroboration",truth_eligible:false,kind:"external",source_url:legacyUrl,import_batch_id:legacyBatchId,date:legacyDay,fetched_at:legacyDay+"T15:00:00Z",observed_at:legacyDay+"T12:00:00Z",proof:"rewe:771001",proof_type:"retailer_offer"};
  const candidate=await observation(products[0],legacyPatch),original=(await pool.query("SELECT to_jsonb(o) AS raw FROM price_observations o WHERE id=$1",[candidate.id])).rows[0].raw;
  const protectedRows=[];
  for(const patch of[{source:"ECHTPREIS receipt",source_id:"ECHTPREIS receipt",source_type:"first_party_receipt",evidence_purpose:"current-price",truth_eligible:true,kind:"receipt",proof_type:"receipt"},{source_url:legacyUrl+"?date=old"},{import_batch_id:mismatchBatchId},{date:"2024-04-12",observed_at:"2024-04-12T12:00:00Z"},{proof_verified:true},{fetched_at:legacyDay+"T18:00:00Z"},{source_id:"different-source"}])protectedRows.push(await observation(products[0],{...legacyPatch,proof:"rewe:"+(771002+protectedRows.length),...patch}));
  const originalLegacyStatus=await Legacy.status(pool),moved=await Legacy.repair(pool);assert.equal(moved.moved,1);assert.equal((await pool.query("SELECT count(*)::int AS count FROM price_observations WHERE id=$1",[candidate.id])).rows[0].count,0);
  const preserved=(await pool.query("SELECT raw_payload AS raw,batch_id AS batch,reason,source FROM price_import_quarantine WHERE raw_payload->>'id'=$1 AND reason=$2",[candidate.id,Legacy.REASON])).rows;assert.equal(preserved.length,1);assert.deepEqual(preserved[0].raw,original,"Quarantine preserves every original observation field without assigning an invented source date");assert.equal(preserved[0].raw.import_batch_id,legacyBatchId);assert.equal(preserved[0].batch,moved.batchId);
  assert.equal((await pool.query("SELECT count(*)::int AS count FROM price_observations WHERE id=ANY($1::uuid[])",[protectedRows.map(row=>row.id)])).rows[0].count,protectedRows.length);assert.equal((await Legacy.repair(pool)).moved,0);assert.equal((await Legacy.status(pool)).preservedObservations,originalLegacyStatus.preservedObservations+1);
  // A real failing quarantine INSERT must roll its preceding DELETE back in PostgreSQL.
  const rollbackCandidate=await observation(products[0],{...legacyPatch,proof:"rewe:771099"});
  await pool.query("CREATE FUNCTION coverage_test_reject_quarantine() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN IF NEW.reason='"+Legacy.REASON+"' THEN RAISE EXCEPTION 'coverage-test-quarantine-failure'; END IF; RETURN NEW; END $$");
  await pool.query("CREATE TRIGGER coverage_test_reject_quarantine BEFORE INSERT ON price_import_quarantine FOR EACH ROW EXECUTE FUNCTION coverage_test_reject_quarantine()");
  try{await assert.rejects(()=>Legacy.repair(pool),/coverage-test-quarantine-failure/);assert.equal((await pool.query("SELECT count(*)::int AS count FROM price_observations WHERE id=$1",[rollbackCandidate.id])).rows[0].count,1);assert.equal((await pool.query("SELECT count(*)::int AS count FROM price_import_quarantine WHERE raw_payload->>'id'=$1",[rollbackCandidate.id])).rows[0].count,0)}finally{await pool.query("DROP TRIGGER coverage_test_reject_quarantine ON price_import_quarantine");await pool.query("DROP FUNCTION coverage_test_reject_quarantine()");}
  assert.equal((await Legacy.repair(pool)).moved,1);await assert.rejects(()=>Coverage.status(pool,{today:"invalid"}),/invalid-date/);
  console.log("price-coverage-postgres: real OFF milk/egg identities, DE branch evidence/review separation, current truth gates, linear observation aggregates, >6,000-product stable rotation and transactional lossless legacy repair/rollback OK");
 }catch(error){testError=error;throw error}finally{try{await pool.end()}catch(error){if(!testError)throw error}}
}
main().catch(error=>{console.error(error);process.exitCode=1});
