"use strict";
const assert=require("assert/strict"),{Pool}=require("pg");
const Inventory=require("../price-inventory-service"),BrowserClient=require("../app/current-price-client"),Lease=require("../price-refresh-state-store");
const StoreCoverage=require("../canonical-store-coverage"),GapTargets=require("../canonical-gap-refresh-targets");
const GeoState=require("../geo-discovery-state"),GeoGrid=require("../geo-discovery-grid"),GeoAdaptive=require("../geo-adaptive-discovery");
const Clock=require("../current-price-query-service");
// Store coverage uses PostgreSQL's real clock and its production 24-hour window.
// Keep the source's date-only fixtures on today's Berlin date on every CI run.
const fixtureNow=new Date(),today=Clock.today(fixtureNow),offsetDay=days=>new Date(Date.parse(today+"T00:00:00Z")+days*864e5).toISOString().slice(0,10),since=offsetDay(-7),futureDay=offsetDay(1),gtin="4002971253504",locationId=910001,proofId=920001;
function fixture(id=901001,patch={}){
 const proof={id:proofId,location_id:locationId,type:"PRICE_TAG",draft:false,image_md5_hash:"a".repeat(32),date:today,currency:"EUR",owner:"inventory-fixture-observer",location_osm_id:990001,location_osm_type:"NODE"};
 return{id,type:"PRODUCT",product_code:gtin,product_id:930001,product:{id:930001,code:gtin,product_name:"Grand Dessert Double Coffee",brands:"Ehrmann",quantity:"190 g",product_quantity:190,product_quantity_unit:"g",source:"off"},location_id:locationId,location_osm_id:990001,location_osm_type:"NODE",location:{id:locationId,type:"OSM",osm_id:990001,osm_type:"NODE",osm_name:"REWE",osm_brand:"REWE",osm_tag_key:"shop",osm_tag_value:"supermarket",osm_address_country:"Deutschland",osm_address_country_code:"DE",osm_address_city:"Berlin",osm_address_postcode:"10115",osm_display_name:"REWE, Inventory Test 1, Berlin, 10115, Deutschland",osm_lat:52.52,osm_lon:13.405},price:1.29,price_is_discounted:false,price_without_discount:null,discount_type:null,price_per:null,currency:"EUR",date:today,proof_id:proofId,proof,owner:"inventory-fixture-observer",source:"SPARKORB PostgreSQL fixture",duplicate_of:null,...patch};
}
function assertBerlinQuery(url){const params=new URL(url).searchParams;assert.equal(params.get("currency"),"EUR");assert.equal(params.get("date__gte"),since);assert.equal(params.get("date__lte"),today);assert.equal(params.get("lat"),"52.52");assert.equal(params.get("lon"),"13.405");assert.equal(params.get("radius_km"),"35");assert.equal(params.get("location__type"),"OSM");return params;}
function upstream(items){return async url=>{assertBerlinQuery(url);return{ok:true,status:200,json:async()=>({items,page:1,pages:1,size:100,total:items.length})}}}
async function scopedGeoSql(pool){
 const tx=await pool.connect(),source="SPARKORB PostgreSQL scoped-geo fixture",foreign=source+" foreign";
 try{
  await tx.query("BEGIN");await GeoState.ensure(tx);await tx.query("DELETE FROM price_geo_discovery_cells WHERE source_id=ANY($1::text[])",[[source,foreign]]);
  const root=GeoGrid.preset("berlin")[0],outside=GeoGrid.preset("germany")[0],child=GeoAdaptive.children(root)[0],grandchild=GeoAdaptive.children(child)[0],untrusted={key:"not-adaptive-child",lat:root.lat,lon:root.lon,radiusKm:3,parentKey:root.key};
  await GeoState.seed(tx,source,[outside,root,child,grandchild,untrusted]);await GeoState.seed(tx,foreign,[root,{...child,key:"adaptive:foreign-child"}]);
  const scope={rootKeys:[root.key]},expected=[root.key,child.key,grandchild.key].sort(),all=await GeoState.next(tx,source,100);
  assert(all.some(row=>row.key===outside.key),"The legacy unscoped API retains other regional work");
  assert.deepEqual((await GeoState.next(tx,source,100,scope)).map(row=>row.key).sort(),expected,"Real recursive SQL selects only the chosen preset root and its source-bound adaptive descendants");
  assert.deepEqual(await GeoState.next(tx,source,100,{rootKeys:[]}),[],"An empty scope never falls back to the nationwide queue");
  for(const key of expected)await GeoState.mark(tx,source,key,{received:20,accepted:2});await GeoState.mark(tx,source,outside.key,{received:999,accepted:999});
  assert.deepEqual((await GeoState.scanned(tx,source,100,scope)).map(row=>row.key).sort(),expected,"A dense old Germany cell cannot seed adaptive discovery for Berlin");
  await tx.query("UPDATE price_geo_discovery_cells SET cooldown_until=now()+interval '1 hour' WHERE source_id=$1 AND cell_key=$2",[source,child.key]);
  assert(!(await GeoState.next(tx,source,100,scope)).some(row=>row.key===child.key));assert(!(await GeoState.scanned(tx,source,100,scope)).some(row=>row.key===child.key),"Cooling-down parents cannot generate replacement discovery requests");
  assert.equal((await tx.query("SELECT count(*)::int AS count FROM price_geo_discovery_cells WHERE source_id=$1 AND cell_key=$2",[source,outside.key])).rows[0].count,1,"Regional selection does not delete previous discovery work");
 }finally{await tx.query("ROLLBACK");tx.release();}
}
async function main(){
 const connectionString=process.env.DATABASE_URL;assert(connectionString,"DATABASE_URL is required for the inventory PostgreSQL integration test");const database=new URL(connectionString);assert.equal(database.hostname,"localhost");assert(database.pathname.endsWith("_test"),"Use a dedicated local test database");
 const pool=new Pool({connectionString,ssl:false,connectionTimeoutMillis:5000}),api=require("../server");const originalRefresh=Inventory.refresh,originalToken=process.env.SPARKORB_INVENTORY_TOKEN;let testError,releaseHeld,heldRun;
 try{
  await api.initDb();await api.initDb();assert.equal(typeof api.seedMerchants,"function");await api.seedMerchants();await scopedGeoSql(pool);
  const regionalBaseline=await Inventory.status(pool,{today});const initialProducts=(await pool.query("SELECT count(*)::int AS count FROM products WHERE gtin=$1",[gtin])).rows[0].count;assert.equal(initialProducts,0,"The inventory fixture must not reuse the previous engine integration product");
  const good=fixture(),refresh=items=>Inventory.refresh(pool,{today,maxPages:20,force:true},{fetchImpl:upstream(items)});
  const first=await refresh([good]);assert.equal(first.ok,true,JSON.stringify(first));
  const product=(await pool.query("SELECT id,name,brand,pack_amount::float AS amount,pack_unit AS unit,pack_count::int AS count,identity_status AS status FROM products WHERE gtin=$1",[gtin])).rows[0];assert(product);assert.equal(product.name,"Grand Dessert Double Coffee");assert.equal(product.brand,"Ehrmann");assert.equal(product.amount,190);assert.equal(product.unit,"g");assert.equal(product.count,1);assert.equal(product.status,"verified");
  const mapping=(await pool.query("SELECT em.store_id AS id,em.status,em.confidence::float AS confidence,s.external_id AS external,s.country,m.name AS merchant FROM external_store_mappings em JOIN stores s ON s.id=em.store_id JOIN merchants m ON m.id=s.merchant_id WHERE em.source_id='Open Prices' AND em.external_location_id=$1",["openprices:"+locationId])).rows[0];assert(mapping);assert.equal(mapping.status,"verified");assert.equal(mapping.confidence,1);assert.equal(mapping.external,"osm:node:990001");assert.equal(mapping.country,"DE");assert.equal(mapping.merchant,"REWE");
  const storeId=mapping.id;assert.equal((await pool.query("SELECT status FROM external_product_mappings WHERE source_id='Open Prices' AND external_product_id=$1",["openprices:"+gtin])).rows[0].status,"verified");
  const branchCoverage=await StoreCoverage.product(pool,{productId:product.id,freshHours:24,merchant:"rewe"});assert.equal(branchCoverage.totalStores,1);assert.equal(branchCoverage.stores[0].storeId,storeId);assert.equal(branchCoverage.stores[0].merchant,"REWE");assert.equal(branchCoverage.coveredStores,1);
  const missingCoverage=await StoreCoverage.product(pool,{gtin:"4006381333931",freshHours:24,merchant:"REWE"});assert.equal(missingCoverage.coveredStores,0);assert.equal(missingCoverage.missingStores,1);
  const gaps=await GapTargets.build(pool,[{productCode:"4006381333931",priority:100}],{sourceId:"Open Prices",limit:20});const branchGap=gaps.find(g=>g.storeId===storeId);assert(branchGap);assert.equal(branchGap.locationId,String(locationId),"Canonical Open Prices mappings must yield the numeric upstream location ID");
  const count=async()=>Number((await pool.query("SELECT count(*)::int AS count FROM price_observations WHERE product_id=$1 AND store_id=$2 AND source_id='Open Prices'",[product.id,storeId])).rows[0].count);
  assert.equal(await count(),1);
  const fact=(await pool.query("SELECT price::float AS price,currency,date::text AS date,gtin,pack,proof_hash AS hash,status,truth_eligible AS eligible,price_type AS type FROM price_observations WHERE product_id=$1 AND store_id=$2",[product.id,storeId])).rows[0];assert.equal(fact.price,1.29);assert.equal(fact.currency,"EUR");assert.equal(fact.date,today);assert.equal(fact.gtin,gtin);assert.equal(fact.pack,"190 g");assert.equal(fact.hash,"a".repeat(32));assert.equal(fact.status,"observed");assert.equal(fact.eligible,true);assert.equal(fact.type,"regular");
  const repeated=await refresh([good]);assert.equal(repeated.ok,true,JSON.stringify(repeated));assert.equal(await count(),1,"A repeated inventory scan must not duplicate observations");assert.equal((await pool.query("SELECT count(*)::int AS count FROM products WHERE gtin=$1",[gtin])).rows[0].count,1);
  const loyaltyProof={...good.proof,id:proofId+1,image_md5_hash:"b".repeat(32)},loyalty=fixture(901002,{price:.75,price_is_discounted:true,price_without_discount:1.29,discount_type:"LOYALTY_PROGRAM",proof_id:proofId+1,proof:loyaltyProof});
  const rejectedGtin="9780201379624",invalidProof=fixture(901003,{product_code:rejectedGtin,product:{...good.product,code:rejectedGtin,product_name:"Unproven product"},proof_id:null,proof:null}),future=fixture(901004,{date:futureDay}),foreign=fixture(901005,{location:{...good.location,osm_address_country_code:"FR"}}),region=fixture(901006,{location:{...good.location,id:locationId+1,osm_id:990002,osm_name:"Bayern",osm_brand:null,osm_tag_key:"boundary",osm_tag_value:"administrative"},location_id:locationId+1,location_osm_id:990002,proof:{...good.proof,location_id:locationId+1,location_osm_id:990002}}),invalidPrice=fixture(901007,{price:Infinity}),conflictingPack=fixture(901008,{product:{...good.product,quantity:"750 g",product_quantity:750},proof_id:proofId+2,proof:{...good.proof,id:proofId+2,image_md5_hash:"c".repeat(32)}});
  const mixed=await refresh([good,loyalty,invalidProof,future,foreign,region,invalidPrice,conflictingPack]);assert.equal(mixed.ok,true,JSON.stringify(mixed));assert.equal(await count(),2,"Only the authenticated source's usable regular and loyalty observations may reach the canonical price store");
  assert.equal((await pool.query("SELECT count(*)::int AS count FROM stores WHERE external_id='osm:node:990002'")).rows[0].count,0,"Administrative regions cannot become stores");
  assert(mixed.reasons["missing-proof"]>=1);assert(mixed.reasons["store-retail-osm-entity-required"]>=1);assert(mixed.reasons["product-existing-pack-conflict"]>=1);assert.equal(mixed.scan.sourceRejected["date-outside-window"],1);assert.equal(mixed.scan.sourceRejected["country-outside-DE"],1);assert.equal((await pool.query("SELECT count(*)::int AS count FROM products WHERE gtin=$1",[rejectedGtin])).rows[0].count,0,"An unproven price cannot bootstrap a product identity");assert.equal((await pool.query("SELECT pack_amount::float AS amount FROM products WHERE id=$1",[product.id])).rows[0].amount,190,"Conflicting upstream pack metadata cannot overwrite a canonical SKU");
  const kgGtin="4006381333931",kgProof={...good.proof,id:proofId+3,image_md5_hash:"d".repeat(32)},kgRow=fixture(901009,{product_id:930002,product_code:kgGtin,product:{...good.product,id:930002,code:kgGtin,product_name:"Tofu Räuchert Multipack",quantity:"2.0 x 175 g",product_quantity:0},price:3,price_per:"KILOGRAM",proof_id:proofId+3,proof:kgProof});
  const kgImport=await refresh([kgRow]);assert.equal(kgImport.ok,true,JSON.stringify(kgImport));assert.equal(kgImport.import.accepted,1,JSON.stringify(kgImport));const kgProduct=(await pool.query("SELECT id,pack_amount::float AS amount,pack_unit AS unit,pack_count::int AS count FROM products WHERE gtin=$1",[kgGtin])).rows[0];assert(kgProduct);assert.equal(kgProduct.amount,175);assert.equal(kgProduct.count,2);assert.equal(kgProduct.unit,"g");const kgFact=(await pool.query("SELECT price::float AS price,per,pack,pack_amount::float AS amount,pack_unit AS unit FROM price_observations WHERE product_id=$1 AND store_id=$2",[kgProduct.id,storeId])).rows[0];assert.equal(kgFact.price,3);assert.equal(kgFact.per,"kg");assert.equal(kgFact.pack,"2 x 175 g");assert.equal(kgFact.amount,350);assert.equal(kgFact.unit,"g");
  const status=await Inventory.status(pool,{today});assert(status&&typeof status==="object");assert(status.lastRun,"Inventory status must persist the last completed run");assert(status.coverage.current_observations>=2);assert.equal(status.scope.region,"Berlin");assert.equal(status.scope.city,"Berlin");assert(status.berlinCoverage.current_observations>=3);assert(status.berlinCoverage.current_products>=2);assert(status.berlinSamples.every(row=>row.city==="Berlin"));assert.equal(status.berlinCoverage.reviewed_observations,regionalBaseline.berlinCoverage.reviewed_observations,"A regional import does not invent reviewed shelf-price proof");
  // Region gates run before canonical writes, even if a source ignores its native radius query.
  const outside=(id,city,lat,lon,type="OSM")=>{const loc=locationId+id,osm=990001+id;return fixture(901020+id,{location_id:loc,location_osm_id:osm,location:{...good.location,id:loc,osm_id:osm,osm_address_city:city,osm_lat:lat,osm_lon:lon,type},proof:{...good.proof,location_id:loc,location_osm_id:osm}});};
  const wrongRegion=[outside(10,"München",48.135,11.582),outside(11,"Potsdam",52.4,13.07),outside(12,"Berlin",48.135,11.582),outside(13,"Berlin",null,null),outside(14,"Berlin",52.52,13.405,"ONLINE")];
  const gated=await refresh(wrongRegion);assert.equal(gated.scope.region,"Berlin");assert.equal(gated.scan.sourceRejected["location-outside-Berlin"],5);assert.equal(gated.import.accepted,0);assert.equal(await count(),2);assert.equal((await pool.query("SELECT count(*)::int AS count FROM stores WHERE external_id=ANY($1::text[])",[wrongRegion.map(row=>"osm:node:"+row.location_osm_id)])).rows[0].count,0,"Rejected regional rows must not create canonical stores");
  const checkpoint=(await Inventory.status(pool,{today})).lastRun;
  await pool.query("UPDATE price_inventory_runs SET status='partial',cursor=$2::jsonb,result=NULL WHERE id=$1",[checkpoint.id,JSON.stringify({nextPage:8,since,until:today,locationIds:""})]);
  let pageAfterLegacy;const restarted=await Inventory.refresh(pool,{today,maxPages:1,force:true},{fetchImpl:async url=>{pageAfterLegacy=assertBerlinQuery(url).get("page");return{ok:true,status:200,json:async()=>({items:[],page:1,pages:2,size:100,total:1})};}});assert.equal(pageAfterLegacy,"1","A legacy nationwide cursor cannot skip the first Berlin page");assert.equal(restarted.cursor.region,"Berlin");assert.equal(restarted.cursor.nextPage,2);assert.equal(restarted.scan.complete,false);assert.equal(restarted.scan.worldwideTotal,null);
  let resumedPage;const resumed=await Inventory.refresh(pool,{today,maxPages:1,force:true},{fetchImpl:async url=>{resumedPage=assertBerlinQuery(url).get("page");return{ok:true,status:200,json:async()=>({items:[good],page:2,pages:2,size:100,total:1})};}});assert.equal(resumedPage,"2","Berlin continuation survives a fresh service invocation and real JSONB reload");assert.equal(resumed.scan.complete,true);assert.equal(resumed.cursor,null);assert.equal(await count(),2);
  await assert.rejects(()=>Inventory.refresh(pool,{today,maxPages:20,force:true},{fetchImpl:async()=>({ok:true,status:200,json:async()=>({items:[good],page:2,pages:2,size:100,total:2})})}),/invalid-pagination/);assert.equal(await count(),2,"A malformed source page must leave canonical prices intact");const failedStatus=await Inventory.status(pool,{today});assert.equal(failedStatus.lastRun.status,"failed");assert.equal(failedStatus.lastRun.result.scope.region,"Berlin","A failed source attempt keeps its actual scope from the initial SQL insert");
  const leaseOwner="inventory-postgres-other-process";assert.equal(await Lease.acquire(pool,Inventory.LEASE,leaseOwner,60000),true);try{let leaseFetches=0;const leaseBlocked=await Inventory.refresh(pool,{today,maxPages:20,force:true},{fetchImpl:async()=>{leaseFetches++;throw new Error("A leased refresh must not fetch")}});assert.equal(leaseBlocked.skipped,"lease-held");assert.equal(leaseFetches,0)}finally{await Lease.release(pool,Inventory.LEASE,leaseOwner)}
  let started;const entered=new Promise(resolve=>{started=resolve}),held=new Promise(resolve=>{releaseHeld=resolve});
  const running=heldRun=Inventory.refresh(pool,{today,maxPages:20,force:true},{fetchImpl:async url=>{started();await held;return upstream([good])(url)}});
  let sourceDeadline;try{await Promise.race([entered,new Promise((resolve,reject)=>{sourceDeadline=setTimeout(()=>reject(new Error("Inventory refresh did not reach its source fetch")),5000)})])}finally{clearTimeout(sourceDeadline)}
  let competingFetches=0;const competing=await Inventory.refresh(pool,{today,maxPages:20,force:true},{fetchImpl:async()=>{competingFetches++;throw new Error("Concurrent refresh must not fetch")}});assert.equal(competingFetches,0,"The database lease must prevent concurrent source scans");assert(competing.skipped||competing.ok===false,JSON.stringify(competing));releaseHeld();releaseHeld=null;assert.equal((await running).ok,true);assert.equal(await count(),2);
  await new Promise((resolve,reject)=>{api.server.once("error",reject);api.server.listen(0,"127.0.0.1",()=>{api.server.off("error",reject);resolve()})});const baseUrl="http://127.0.0.1:"+api.server.address().port;
  async function current(extra={}){const response=await fetch(baseUrl+"/v1/current-prices",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({product:product.name,brand:product.brand,pack:"190 g",gtin,productId:product.id,merchants:["REWE"],storeId,today,...extra}),signal:AbortSignal.timeout(10000)});const result=await response.json();assert.equal(response.status,200,JSON.stringify(result));assert.equal(result.ok,true);assert.equal(result.results.length,1);return result.results[0]}
  const publicPrice=await current();assert.equal(publicPrice.price,1.29,JSON.stringify(publicPrice));assert.equal(publicPrice.state,"observed");assert.equal(publicPrice.priceType,"regular");assert(Math.abs(publicPrice.unitPrice-1.29/.19)<1e-9);
  const loyalPrice=await current({eligibility:{loyalty:true}});assert.equal(loyalPrice.price,.75,JSON.stringify(loyalPrice));assert.equal(loyalPrice.conditional,true);assert.equal(loyalPrice.priceType,"loyalty");
  const kgDecision=await current({product:"Tofu Räuchert Multipack",pack:"2 x 175 g",gtin:kgGtin,productId:kgProduct.id});assert.equal(kgDecision.state,"observed",JSON.stringify(kgDecision));assert.equal(kgDecision.price,1.05,JSON.stringify(kgDecision));assert.equal(kgDecision.unitPrice,3);assert.equal(kgDecision.unit,"kg");assert.equal(kgDecision.priceBasis,"derived-pack");assert.equal(kgDecision.originalPrice,3);assert.equal(kgDecision.originalPer,"kg");const kgComparable=BrowserClient.toComparablePrice(kgDecision,"kg");assert(kgComparable);assert.equal(kgComparable.price,3);
  const query=await fetch(baseUrl+"/v1/price-query",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({product:product.name,gtin,merchants:["REWE"],storeId})}).then(res=>res.json());assert.equal(query.product.id,product.id);assert.equal(query.stores[0].id,storeId);
  const client=BrowserClient.create({apiBase:baseUrl,fetchImpl:fetch}),compared=await client.compare({product:product.name,brand:product.brand,pack:"190 g",gtin,productId:product.id,merchants:["REWE"]},{today,storeIds:{REWE:storeId},quantity:1,refresh:false});assert.equal(compared.ok,true);assert.equal(compared.results[0].price,1.29);assert.equal(compared.results[0].storeId,storeId);
  process.env.SPARKORB_INVENTORY_TOKEN="inventory-postgres-token";let routeCalls=0;Inventory.refresh=async(p,options)=>{assert(p&&typeof p.query==="function");assert.equal(options.force,true);routeCalls++;return{ok:true,status:"complete",testMarker:"inventory-token-accepted"}};
  async function trigger(token){const headers={"Content-Type":"application/json"};if(token)headers.Authorization="Bearer "+token;const response=await fetch(baseUrl+"/v1/admin/price-inventory/refresh",{method:"POST",headers,body:JSON.stringify({maxPages:1}),signal:AbortSignal.timeout(10000)});return{status:response.status,body:await response.json()}}
  assert.equal((await trigger()).status,403);assert.equal((await trigger("wrong-inventory-token")).status,403);assert.equal(routeCalls,0);const authorized=await trigger("inventory-postgres-token");assert.equal(authorized.status,200,JSON.stringify(authorized.body));assert.equal(authorized.body.testMarker,"inventory-token-accepted");assert.equal(routeCalls,1);Inventory.refresh=originalRefresh;
  console.log("price-inventory-postgres: native bounded Berlin collection, real recursive preset/descendant SQL and cooldown preservation, regional gates before canonical writes, scope-bound JSONB restart/legacy cursor reset, honest regional coverage, source quarantine, leases and exact current-price API OK");
 }catch(error){testError=error;throw error}
 finally{if(releaseHeld)releaseHeld();if(heldRun)await Promise.allSettled([heldRun]);Inventory.refresh=originalRefresh;if(originalToken===undefined)delete process.env.SPARKORB_INVENTORY_TOKEN;else process.env.SPARKORB_INVENTORY_TOKEN=originalToken;const cleanup=[pool.end()];if(typeof api.closeDb==="function")cleanup.push(api.closeDb());if(api.server.listening)cleanup.push(new Promise((resolve,reject)=>api.server.close(error=>error?reject(error):resolve())));const errors=(await Promise.allSettled(cleanup)).filter(r=>r.status==="rejected").map(r=>r.reason);if(errors.length&&!testError)throw new AggregateError(errors,"Inventory integration cleanup failed")}
}
main().catch(error=>{console.error(error);process.exitCode=1});
