"use strict";
const assert=require("node:assert/strict"),Discovery=require("../published-product-discovery"),Inventory=require("../published-retailer-inventory"),Products=require("../app/published-product-client"),Needs=require("../app/shopping-need-client"),capture=require("./fixtures/retailers/automatic-choice-berlin-capture.json");
const now=Date.parse(capture.ownApiCapturedAt),offers=capture.responses[0].items.flatMap(item=>item.offers);
(async()=>{
 const invoked=[],services=Object.fromEntries(["dm","wolt","woltNahkauf","rewe","aldi"].map(key=>[key,{search:async(_pool,query)=>{invoked.push({key,query});return{items:[]};}}]));
 await Inventory.search({}, {search:"Milch",priorityRetailersOnly:true,limit:200},services);assert.deepEqual(invoked.map(c=>c.key).sort(),["rewe","wolt"]);assert(invoked.every(c=>c.query.limit===200));
 invoked.length=0;await Inventory.search({}, {search:"Milch",priorityRetailersOnly:false},services);assert.equal(invoked.length,5,"Ordinary search remains broad");
 let physicalCalls=0,lookup;const inventory={search:async(_pool,options)=>{lookup=options;return{items:offers};}},physical={search:async()=>{physicalCalls++;return{items:[],truncated:false};}};
 const found=await Discovery.search({}, {search:"Milch",priorityRetailersOnly:true,now},inventory,physical);assert(found.items.length>0);assert.equal(physicalCalls,0,"Priority search skips the unrelated HIT proof scan");assert.equal(lookup.priorityRetailersOnly,true);assert.equal(lookup.limit,200);assert(found.items.every(item=>item.offers.every(o=>o.merchant==="EDEKA")));assert.equal(found.limit,20);
 await Discovery.search({}, {search:"Milch",now},inventory,physical);assert.equal(physicalCalls,1,"The optional broad picker preserves physical discovery");
 const actualNow=Date.now;let needed;try{Date.now=()=>now;needed=await Discovery.searchNeed({}, {search:"Milch",constraints:{family:"milk"},priorityRetailersOnly:true},inventory,physical);}finally{Date.now=actualNow;}assert.equal(physicalCalls,1);assert.equal(needed.need.constraints.family,"milk");assert.equal(needed.needCoverage.complete,false);
 for(const flag of["true","false",1,null,{}]){await assert.rejects(Discovery.search({}, {search:"Milch",priorityRetailersOnly:flag,now},inventory,physical),e=>e.code==="invalid-retailer-priority-filter");await assert.rejects(Inventory.search({}, {search:"Milch",priorityRetailersOnly:flag},services));assert.equal(Products.searchFilters({priorityRetailersOnly:flag}).ok,false);assert.throws(()=>Needs.request({search:"Milch",constraints:{family:"milk"},priorityRetailersOnly:flag}));}
 const mixed=JSON.parse(JSON.stringify(capture.responses[0].items));const one=mixed.find(item=>item.offers[0].availability!=="unavailable"&&item.name.includes("Haltbare")),o=one.offers[0];one.offers.push({...o,sourceId:"Wolt nahkauf Berlin Wrangelstraße",merchant:"nahkauf",nativeVenueId:"657acc4eba505a018fb31b05",sourceUrl:"https://wolt.com/de/deu/berlin/venue/nahcity-wrangelstrae",shop:{nativeVenueId:"657acc4eba505a018fb31b05",name:"Nahkauf Wrangelstraße",address:"Wrangelstraße 75",postalCode:"10997",city:"Berlin",country:"DE"}});
 assert.equal(Products.candidate(one,{now}).offers.length,2);assert.equal(Products.candidate(one,{now,priorityRetailersOnly:true}).offers.length,1,"Client independently filters a broad or ignored server flag");
 const broadInventory={search:async()=>({items:one.offers})};const tight=await Discovery.search({}, {search:"Milch",priorityRetailersOnly:true,now},broadInventory,physical);assert(tight.items.every(item=>item.offers.every(row=>row.merchant==="EDEKA")),"Discovery independently rejects an inventory reply ignoring priority scope");
 let url,body;const productClient=Products.create({now:()=>now,fetchImpl:async requested=>{url=requested;return{ok:true,json:async()=>({ok:true,items:[one]})};}});const response=await productClient.search("Milch",{priorityRetailersOnly:true});assert.equal(new URL(url,"https://prices.test").searchParams.get("priorityRetailersOnly"),"true");assert.equal(response.items[0].offers.length,1);assert.equal(response.appliedFilters.priorityRetailersOnly,true);
 const needClient=Needs.create({now:()=>now,fetchImpl:async(_url,options)=>{body=JSON.parse(options.body);return{ok:true,json:async()=>needed};}});assert((await needClient.search({search:"Milch",constraints:{family:"milk"},priorityRetailersOnly:true})).ok);assert.equal(body.priorityRetailersOnly,true);assert.equal(body.limit,20);
 console.log("priority-product-discovery: strict six-retailer narrowing skips unrelated proof scans; unchanged broad picker, native evidence, client/server boundaries OK");
})().catch(error=>{console.error(error);process.exitCode=1;});
