"use strict";
const assert=require("assert/strict"),Inventory=require("../published-retailer-inventory");
const NOW=Date.parse("2026-10-01T12:00:00Z"),GTIN="3017620422003";
function quote(sourceId,index,offset=0){return{sourceId,merchant:sourceId==="dm online"?"dm":"EDEKA",nativeVenueId:sourceId==="dm online"?undefined:"67ebb70ed3581534a525c522",retailerSku:String(index),gtin:GTIN,name:"UNIT TEST exact published product",brand:"UNIT TEST brand",pack:"450 g",price:3.99,capturedAt:new Date(NOW-offset-index*1000).toISOString(),scopeCountry:"DE",scopeChannel:"online",truthEligible:false,state:"published",shippingIncluded:false}}
async function main(){
 const calls=[],dm=Array.from({length:150},(_,i)=>quote("dm online",i,1000)),wolt=Array.from({length:150},(_,i)=>quote("Wolt EDEKA Berlin",i));const original=JSON.stringify({dm,wolt}),pool={query:async()=>{throw Error("Search must delegate to scoped ledgers")}};
 const services={dm:{search:async(db,options)=>{calls.push({ledger:"dm",options});assert.equal(db,pool);return{items:dm}}},wolt:{search:async(db,options)=>{calls.push({ledger:"wolt",options});assert.equal(db,pool);return{items:wolt}}}};
 const result=await Inventory.search(pool,{gtin:GTIN,merchant:"EDEKA",today:"2026-10-01",search:"Nutella%_",limit:999,now:NOW},services);assert.equal(result.items.length,200,"The limit bounds the combined result, rather than each ledger independently");assert.equal(result.items[0].sourceId,"Wolt EDEKA Berlin");assert.equal(result.items[0].retailerSku,"0");assert.equal(result.physicalStorePrices,false);assert.equal(result.scopeChannel,"online");assert(result.items.every(row=>row.gtin===GTIN&&row.truthEligible===false&&!row.storeId&&!row.productId));assert.equal(JSON.stringify({dm,wolt}),original,"Combining ledgers must not rewrite source identity or scope");for(const call of calls){assert.equal(call.options.gtin,GTIN);assert.equal(call.options.limit,200);assert.equal(call.options.today,"2026-10-01");assert.equal(call.options.merchant,"EDEKA");assert.equal(call.options.search,"Nutella%_");assert.equal(call.options.now,NOW)}for(let i=1;i<result.items.length;i++)assert(Date.parse(result.items[i-1].capturedAt)>=Date.parse(result.items[i].capturedAt),"Both ledgers must participate in one freshness ordering");
 const limited=await Inventory.search(pool,{limit:1},services);assert.equal(limited.items.length,1);assert.equal(limited.items[0].retailerSku,"0");assert.equal((await Inventory.search(pool,{limit:0},services)).items.length,1);assert.equal((await Inventory.search(pool,{limit:"invalid"},services)).items.length,50);
 const tied=[quote("Wolt EDEKA Berlin",0),{...quote("Wolt EDEKA Berlin",0),nativeVenueId:"UNIT-TEST-other-venue",retailerSku:"8"},quote("dm online",0)];const tieServices={dm:{search:async()=>({items:[tied[2]]})},wolt:{search:async()=>({items:[tied[1],tied[0]]})}};const tiedResult=await Inventory.search(pool,{gtin:GTIN},tieServices);assert.equal(tiedResult.items.length,3,"The same exact GTIN can retain separate retailer offers without coercing them into one physical price");assert.deepEqual(tiedResult.items.map(row=>row.sourceId+"@"+(row.nativeVenueId||"")),[...tied].sort((a,b)=>String(a.sourceId).localeCompare(String(b.sourceId))||String(a.nativeVenueId||"").localeCompare(String(b.nativeVenueId||""))).map(row=>row.sourceId+"@"+(row.nativeVenueId||"")));
 const dmStatus={storedPrices:"4",currentPrices:"3",productsWithCurrentPublishedPrices:2,availableCurrentPrices:"2",lastCapturedAt:new Date(NOW-1000),merchants:[{merchant:"dm",sourceId:"dm online",currentPrices:3}],scopeChannel:"online"},woltStatus={storedPrices:"5",currentPrices:"4",productsWithCurrentPublishedPrices:3,availableCurrentPrices:"3",lastCapturedAt:new Date(NOW).toISOString(),markets:[{merchant:"EDEKA",sourceId:"Wolt EDEKA Berlin",nativeVenueId:"67ebb70ed3581534a525c522",currentPrices:4}],truthEligible:false};const sqlCalls=[],statusPool={query:async(sql,params)=>{sqlCalls.push({sql,params});return{rows:[{productsWithCurrentPublishedPrices:4}]}}},statusServices={dm:{status:async(db,options)=>{assert.equal(db,statusPool);assert.equal(options.now,NOW);return dmStatus}},wolt:{status:async(db,options)=>{assert.equal(db,statusPool);assert.equal(options.now,NOW);return woltStatus}}};
 const status=await Inventory.status(statusPool,{now:NOW},statusServices);assert.equal(status.storedPrices,9);assert.equal(status.currentPrices,7);assert.equal(status.availableCurrentPrices,5);assert.equal(status.productsWithCurrentPublishedPrices,4,"Shared GTINs in dm and Wolt must be counted once; adding the source counts would falsely report 5");assert.equal(Date.parse(status.lastCapturedAt),NOW);assert.deepEqual(status.retailers.dm,dmStatus);assert.deepEqual(status.retailers.woltEdekaBerlin,woltStatus);assert.deepEqual(status.merchants,[...dmStatus.merchants,...woltStatus.markets]);assert.equal(status.scopeCountry,"DE");assert.equal(status.scopeChannel,"online");assert.equal(status.state,"published");assert.equal(sqlCalls.length,1);assert(sqlCalls[0].sql.includes("count(DISTINCT gtin)"));assert(sqlCalls[0].sql.includes("UNION SELECT gtin FROM wolt_retailer_published_prices"));assert(sqlCalls[0].sql.includes("SELECT gtin FROM retailer_published_prices"));assert.equal((sqlCalls[0].sql.match(/expires_at>\$1::timestamptz/g)||[]).length,2);assert.equal((sqlCalls[0].sql.match(/interval '24 hours'/g)||[]).length,2);assert.deepEqual(sqlCalls[0].params,[new Date(NOW).toISOString()]);assert(!sqlCalls.some(call=>/INSERT|UPDATE|price_observations|receipt_submissions|\bFROM (?:products|stores)\b/.test(call.sql)),"Published inventory status must read the separate ledgers without inventing physical evidence");
 await assert.rejects(()=>Inventory.status(statusPool,{now:"invalid"},statusServices),/invalid-time/);assert.equal(sqlCalls.length,1,"Invalid clocks cannot issue a freshness-union query");await assert.rejects(()=>Inventory.search(null),/database-required/);assert.equal(Inventory.matchesProductQuery(quote("dm online",0),{gtin:GTIN,pack:"0.45 kg",brand:"UNIT TEST BRAND"}),true);assert.equal(Inventory.matchesProductQuery(quote("dm online",0),{gtin:GTIN,pack:"2 x 225 g"}),false);assert.equal(Inventory.matchesProductQuery(quote("dm online",0),{name:"UNIT TEST exact published product"}),false);
 console.log("published-retailer-inventory: exact GTIN/merchant/date forwarding, one bounded freshest result across ledgers, stable separate retailer identities, true union of overlapping GTINs and zero physical evidence writes OK");
}
main().catch(error=>{console.error(error);process.exitCode=1});
