"use strict";
const assert=require("assert/strict"),{Pool}=require("pg"),Service=require("../published-price-service");
function gtin(index){const body=String(960000000000+index),sum=[...body].reduce((total,digit,position)=>total+Number(digit)*(position%2?3:1),0);return body+(10-sum%10)%10}
async function main(){
 const connectionString=process.env.DATABASE_URL;assert(connectionString,"DATABASE_URL is required");const database=new URL(connectionString);assert.equal(database.hostname,"localhost");assert(database.pathname.endsWith("_test"),"Only a dedicated local test database is allowed");
 const pool=new Pool({connectionString,ssl:false,connectionTimeoutMillis:5000}),now=Date.now();let testError,api;
 const offer=(index,patch={})=>({merchant:"dm",sourceId:"dm online",retailerSku:String(880000+index),gtin:gtin(index),name:"POSTGRES TEST published product "+index,brand:"POSTGRES TEST retailer",pack:"1 l",packAmount:1,packUnit:"l",packCount:1,price:1.29,currency:"EUR",sourceUrl:"https://www.dm.de/p/d/"+(880000+index)+"/postgres-test-product",proofHash:"c".repeat(64),capturedAt:new Date(now-1000).toISOString(),scopeCountry:"DE",scopeChannel:"online",availability:"available",...patch});
 try{
  const exists=async table=>!!(await pool.query("SELECT to_regclass($1) AS name",["public."+table])).rows[0].name;
  const existingTables=[];for(const table of["products","stores","price_observations"])if(await exists(table))existingTables.push(table);
  const counts=async()=>{const result={};for(const table of existingTables)result[table]=(await pool.query("SELECT count(*)::int AS count FROM "+table)).rows[0].count;return result};const baseline=await counts();
  await Service.ensure(pool);const fixtures=Array.from({length:501},(_,index)=>offer(index)),saved=await Service.persist(pool,fixtures,{now});assert.equal(saved.accepted,501);assert.equal(saved.upserted,501);assert.equal(saved.rejected,0);
  const stored=(await pool.query("SELECT count(*)::int AS total,count(*) FILTER(WHERE scope_country='DE' AND scope_channel='online' AND currency='EUR' AND pack_amount=1000 AND pack_unit='ml' AND pack_count=1)::int AS exact FROM retailer_published_prices WHERE retailer_sku=ANY($1::text[])",[fixtures.map(row=>row.retailerSku)])).rows[0];assert.equal(stored.total,501);assert.equal(stored.exact,501);
  const repeat=await Service.persist(pool,fixtures,{now});assert.equal(repeat.upserted,0);assert.equal(repeat.unchanged,501);
  await Service.persist(pool,[offer(0,{price:99,capturedAt:new Date(now-2000).toISOString()})],{now});assert.equal((await Service.search(pool,{gtin:gtin(0),now})).items[0].price,1.29);
  const changed=offer(0,{price:1.39,capturedAt:new Date(now).toISOString(),proofHash:"d".repeat(64),availability:"unavailable"});assert.equal((await Service.persist(pool,[changed],{now})).upserted,1);let selected=(await Service.search(pool,{merchant:"dm",gtin:gtin(0),now})).items;assert.equal(selected.length,1);assert.equal(selected[0].price,1.39);assert.equal(selected[0].availability,"unavailable");assert.equal(selected[0].state,"published");assert.equal(selected[0].scopeChannel,"online");assert(!("storeId"in selected[0]));
  assert.equal((await Service.search(pool,{merchant:"other merchant",gtin:gtin(0),now})).items.length,0);assert.equal((await Service.search(pool,{search:"product 500",now})).items.length,1);assert.equal((await Service.search(pool,{search:"product%_",now})).items.length,0,"SQL wildcards from a literal user search must not match every product");assert.equal((await Service.search(pool,{limit:999,now})).items.length,200);
  await Service.persist(pool,[offer(501,{capturedAt:new Date(now-Service.DAY_MS-1).toISOString(),availability:"unknown"})],{now});assert.equal((await Service.search(pool,{gtin:gtin(501),now})).items.length,0);
  const invalid=await Service.persist(pool,[offer(502,{gtin:"invalid"}),offer(503,{scopeChannel:"store",storeId:"imaginary"}),offer(504,{sourceUrl:"https://example.test/p/d/880504/product"}),offer(505,{capturedAt:new Date(now+1).toISOString()}),offer(506,{packAmount:500})],{now});assert.equal(invalid.accepted,0);assert.equal(invalid.rejected,5);
  const status=await Service.status(pool,{now});assert.equal(status.storedPrices,502);assert.equal(status.currentPrices,501);assert.equal(status.productsWithCurrentPublishedPrices,501);assert.equal(status.availableCurrentPrices,500);assert.equal(status.scopeChannel,"online");assert.equal(status.merchants.find(row=>row.merchant==="dm").currentPrices,501);
  // The normal HTTP routes expose separate online quotes. No source refresh or user receipt is needed to read them.
  api=require("../server");await new Promise((resolve,reject)=>{api.server.once("error",reject);api.server.listen(0,"127.0.0.1",()=>{api.server.off("error",reject);resolve()})});const base="http://127.0.0.1:"+api.server.address().port;
  async function get(path){const response=await fetch(base+path,{signal:AbortSignal.timeout(10000)});return{status:response.status,body:await response.json()}}
  const publicStatus=await get("/v1/published-prices/status");assert.equal(publicStatus.status,200,JSON.stringify(publicStatus));assert.equal(publicStatus.body.currentPrices,501);assert.equal(publicStatus.body.scopeChannel,"online");assert.equal(publicStatus.body.research.independentOfUserReceipts,true);
  const publicQuery=await get("/v1/published-prices?merchant=dm&gtin="+gtin(0));assert.equal(publicQuery.status,200);assert.equal(publicQuery.body.items.length,1);assert.equal(publicQuery.body.items[0].price,1.39);assert.equal(publicQuery.body.items[0].state,"published");assert.equal(publicQuery.body.items[0].availability,"unavailable");assert.equal(publicQuery.body.items[0].shippingIncluded,false);assert.equal((await get("/v1/published-prices?gtin=invalid")).status,400);
  if(existingTables.includes("products")&&existingTables.includes("stores")){
   const exactGtin="3017620422003",product=(await pool.query("SELECT id,name,brand,pack_amount::float AS amount,pack_unit AS unit,pack_count::int AS count FROM products WHERE gtin=$1",[exactGtin])).rows[0];assert(product,"Run the preceding physical price integration with its explicit TEST Nutella identity");assert.equal(product.amount,450);assert.equal(product.unit,"g");
   const store=(await pool.query("SELECT s.id FROM stores s JOIN merchants m ON m.id=s.merchant_id WHERE m.name='EDEKA' AND m.active=true AND s.active=true AND s.country='DE' ORDER BY s.id LIMIT 1")).rows[0];assert(store);
   const input={product:product.name,productId:product.id,gtin:exactGtin,brand:product.brand,pack:"450 g",merchants:["EDEKA"],storeId:store.id};
   async function current(request){const response=await fetch(base+"/v1/current-prices",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(request),signal:AbortSignal.timeout(10000)});const result=await response.json();assert.equal(response.status,200,JSON.stringify(result));assert.equal(result.ok,true);return result}
   const beforeOnline=await current(input);assert.equal(beforeOnline.publishedAlternatives.length,0);
   const exactOffer=offer(600,{gtin:exactGtin,name:"POSTGRES TEST online Nutella",brand:"Ferrero",pack:"450 g",packAmount:450,packUnit:"g",price:3.89});assert.equal((await Service.persist(pool,[exactOffer],{now})).upserted,1);
   const compared=await current(input);assert.deepEqual(compared.results,beforeOnline.results,"An online published quote cannot change any physical merchant price decision");assert.deepEqual(compared.coverage,beforeOnline.coverage);assert.equal(compared.publishedAlternatives.length,1);assert.equal(compared.publishedAlternatives[0].gtin,exactGtin);assert.equal(compared.publishedAlternatives[0].price,3.89);assert.equal(compared.publishedAlternatives[0].scopeChannel,"online");assert.equal(compared.publishedAlternatives[0].state,"published");assert(!("storeId"in compared.publishedAlternatives[0]));
   const generic=await current({product:"Nutella",merchants:["EDEKA"],storeId:store.id});assert.equal(generic.publishedAlternatives.length,0,"A name-only category query cannot receive a guessed GTIN-specific online price");
  }
  assert.equal((await Service.search(pool,{now:now+Service.DAY_MS+1})).items.length,0);assert.deepEqual(await counts(),baseline,"Publishing retailer online quotes must create no products, physical stores or price observations");
  for(const table of["products","stores","price_observations"])if(!existingTables.includes(table))assert.equal(await exists(table),false,"The separate price service must not create "+table);
  console.log("published-price-postgres: 501 bulk TEST online quotes, exact provenance and24h scope, HTTP status/search, exact-GTIN online alternatives with unchanged physical decisions, no guessed category price and zero user receipts/store/price-observation mutations OK");
 }catch(error){testError=error;throw error}finally{const cleanup=[pool.end()];if(api){if(api.server.listening)cleanup.push(new Promise((resolve,reject)=>api.server.close(error=>error?reject(error):resolve())));cleanup.push(api.closeDb())}const errors=(await Promise.allSettled(cleanup)).filter(result=>result.status==="rejected");if(errors.length&&!testError)throw errors[0].reason}
}
main().catch(error=>{console.error(error);process.exitCode=1});
