"use strict";
const assert=require("assert/strict"),Discovery=require("../published-product-discovery"),Dm=require("../published-price-service"),Wolt=require("../wolt-retailer-price-service");
const Hit=require("../hit-product-discovery"),HitFixture=require("./hit-product-discovery.test"),noPhysical={search:async()=>({items:[],truncated:false})};
const NOW=Date.parse("2026-10-01T12:00:00Z"),GTIN="4008452027602";
function dm(sku,patch={}){const result=Dm.validateOffer({sourceId:Dm.SOURCE,merchant:"dm",retailerSku:String(sku),gtin:GTIN,name:"TEST Milch",brand:null,pack:"1 l",price:1.29,currency:"EUR",capturedAt:new Date(NOW-1000).toISOString(),sourceUrl:"https://www.dm.de/p/d/"+sku+"/test-milch",proofHash:"a".repeat(64),scopeCountry:"DE",scopeChannel:"online",availability:"unknown",...patch},{now:NOW});assert(result.ok,JSON.stringify(result));return{...result.offer,current:true};}
function wolt(patch={}){const result=Wolt.validateOffer({sourceId:Wolt.SOURCE,merchant:Wolt.MERCHANT,nativeVenueId:Wolt.VENUE.nativeVenueId,retailerSku:"9".repeat(24),gtin:GTIN,name:"TEST Milch",brand:null,pack:"1000 ml",price:1.49,deposit:null,displayedPrice:1.49,nativePriceEUR:1.49,nativePriceIncludesDeposit:true,payablePackPrice:null,depositIncludedInDisplayedPrice:null,currency:"EUR",capturedAt:new Date(NOW-2000).toISOString(),proofHash:"b".repeat(64),sourceResponseHash:"b".repeat(64),sourceUrl:"https://wolt.com/de/deu/berlin/venue/edeka-hilbrecht",sourceResponseUrl:"https://consumer-api.wolt.com/consumer-api/consumer-assortment/v1/venues/slug/edeka-hilbrecht/assortment/categories/slug/milch-46",shop:Wolt.VENUE,scopeCountry:"DE",scopeChannel:"online",priceType:"unknown",promotionStatus:"unknown",availability:"unavailable",...patch},{now:NOW});assert(result.ok,JSON.stringify(result));return{...result.offer,current:true};}
async function main(){
 const priorClock=Date.now;Date.now=()=>HitFixture.NOW;try{
 const first=dm(123),second=wolt(),multi=dm(124,{pack:"2 x 500 ml"}),input=[first,second,multi],original=JSON.stringify(input),calls=[];
 const inventory={search:async(pool,options)=>{calls.push(options);return{items:input};}};
 const result=await Discovery.search({}, {search:" Milch ",limit:20,now:NOW},inventory,noPhysical);
 assert.equal(result.items.length,2);assert.equal(result.requiresProductSelection,true);assert.equal(result.physicalStorePrices,false);assert.equal(result.scopeCountry,"DE");assert.equal(result.discoveryTruncated,false);assert.deepEqual(calls,[{search:"Milch",limit:200,now:NOW}]);
 const single=result.items.find(row=>row.packCount===1);assert.equal(single.gtin,GTIN);assert.equal(single.packAmount,1000);assert.equal(single.packUnit,"ml");assert.equal(single.offers.length,2,"Matching 1l/1000ml identities retain two independent shop quotes");assert.deepEqual(single.offers,[first,second]);assert.equal(single.offers[1].availability,"unavailable");assert.equal(single.offers[1].deposit,null);assert.equal(result.items.find(row=>row.packCount===2).packAmount,500,"An equal total quantity cannot collapse a multipack");assert.equal(JSON.stringify(input),original,"Discovery preserves source price, proof, time and fee scope");assert(!single.productId&&!single.storeId&&!single.price);
 assert.equal((await Discovery.search({}, {search:"Milch",limit:1,now:NOW},inventory,noPhysical)).discoveryTruncated,true);
 const decimalOffers=[dm(151,{pack:"0.0049 kg",packAmount:.0049,packUnit:"kg"}),dm(152,{pack:"4.9 g",packAmount:4.9,packUnit:"g"})];
 const decimal=await Discovery.search({}, {search:"Milch",pack:"4.9 g",now:NOW},{search:async()=>({items:decimalOffers})},noPhysical);assert.equal(decimal.items.length,1,"Equivalent decimal unit notations remain one GTIN/sales-pack group");assert.equal(decimal.items[0].offers.length,2);
 const decimalMulti=dm(153,{pack:"2 x 4.9 g",packAmount:4.9,packUnit:"g",packCount:2}),decimalSingle=dm(154,{pack:"9.8 g",packAmount:9.8,packUnit:"g",packCount:1});assert.equal((await Discovery.search({}, {search:"Milch",now:NOW},{search:async()=>({items:[decimalMulti,decimalSingle]})},noPhysical)).items.length,2);
 const invalid=[{...first,gtin:"4008452027603"},{...first,gtin:null},{...first,sourceId:"Invented source"},{...first,scopeChannel:"store"},{...first,storeId:"invented"},{...first,productId:"invented"},{...first,truthEligible:true},{...first,expiresAt:new Date(NOW).toISOString()},{...first,capturedAt:new Date(NOW+1).toISOString()},{...first,capturedAt:new Date(NOW-86400001).toISOString()},{...first,expiresAt:new Date(NOW+86400000).toISOString()},{...first,packAmount:500},{...first,proofHash:"missing"},{...second,sourceUrl:"https://wolt.com/de/deu/berlin/venue/nahcity-wrangelstrae"},{...second,name:"TEST Milch 2 x 1000 ml"}];
 const rejected=await Discovery.search({}, {search:"Milch",now:NOW},{search:async()=>({items:invalid})},noPhysical);assert.deepEqual(rejected.items,[]);assert.equal(rejected.requiresProductSelection,false);
 let fetched=false;const never={search:async()=>{fetched=true;throw Error("Unexpected read");}};for(const search of[undefined,"", "x", "x".repeat(121),true])await assert.rejects(()=>Discovery.search({}, {search,now:NOW},never,noPhysical),/invalid-product-search/);for(const limit of[0,21,1.2,true,"bad"])await assert.rejects(()=>Discovery.search({}, {search:"Milch",limit,now:NOW},never),/invalid-product-limit/);await assert.rejects(()=>Discovery.search({}, {search:"Milch",now:"bad"},never),/invalid-time/);assert.equal(fetched,false);
 const dupe=await Discovery.search({}, {search:"Milch",now:NOW},{search:async()=>({items:[first,first]})},noPhysical);assert.equal(dupe.items.length,1);assert.equal(dupe.items[0].offers.length,1);
 const physicalTime=HitFixture.NOW,physicalOffer=Hit.validateRow(HitFixture.row(),{now:physicalTime});assert(physicalOffer);
 const related=dm(125,{gtin:physicalOffer.gtin}),injected={search:async()=>({items:[physicalOffer],truncated:false})},mixed=await Discovery.search({}, {search:"Milch",now:physicalTime},{search:async()=>({items:[{...related,capturedAt:new Date(physicalTime-1000).toISOString(),expiresAt:new Date(physicalTime-1000+86400000).toISOString()}]})},injected);
 assert.equal(mixed.items.length,1);assert.equal(mixed.items[0].offers.length,1);assert.equal(mixed.items[0].physicalOffers.length,1);assert.deepEqual(mixed.items[0].physicalOffers[0],physicalOffer);assert.equal(mixed.physicalStorePrices,true);assert.deepEqual(mixed.scopeChannels,["online","physical-store"]);assert.equal(mixed.items[0].physicalOffers[0].checkoutPriceVerified,false);
 const physicalOnly=await Discovery.search({}, {search:"Milch",now:physicalTime},{search:async()=>({items:[]})},injected);assert.equal(physicalOnly.items.length,1);assert.deepEqual(physicalOnly.items[0].offers,[]);assert.equal(physicalOnly.items[0].physicalOffers.length,1);assert.equal(physicalOnly.requiresProductSelection,true);
 const filtered=await Discovery.search({}, {search:"Milch",pack:"1 l",scopeChannel:"physical-store",merchant:"HIT",now:physicalTime},{search:async()=>{throw Error("Online provider cannot execute for a physical request");}},injected);assert.equal(filtered.items.length,1);assert.deepEqual(filtered.scopeChannels,["physical-store"]);
 assert.equal((await Discovery.search({}, {search:"Milch",pack:"2 x 500 ml",scopeChannel:"physical-store",now:physicalTime},inventory,injected)).items.length,0,"A provider that ignores a pack filter still cannot expose a mismatching quote");
 assert.equal((await Discovery.search({}, {search:"Milch",merchant:"REWE",now:physicalTime},{search:async()=>({items:[related]})},injected)).items.length,0,"An injected provider cannot cross the requested merchant scope");
 for(const patch of[{scopeChannel:"online"},{sourceId:Wolt.SOURCE},{storeId:"invented"},{gtin:"4388844177315"},{price:.95},{proofHash:"b".repeat(64)},{capturedAt:new Date(physicalTime+1).toISOString()},{expiresAt:new Date(physicalTime).toISOString()},{branch:{...physicalOffer.branch,city:"Hamburg"}},{pack:"2 x 500 ml"},{sourceEligibility:{...physicalOffer.sourceEligibility,depositCents:0}}]){const unsafe=await Discovery.search({}, {search:"Milch",now:physicalTime},{search:async()=>({items:[]})},{search:async()=>({items:[{...physicalOffer,...patch}]})});assert.deepEqual(unsafe.items,[],JSON.stringify(patch));assert.equal(unsafe.physicalStorePrices,false);}
 const multiPhysical=Hit.validateRow(HitFixture.row({overview:"2x500ml Packung"}),{now:physicalTime}),split=await Discovery.search({}, {search:"Milch",now:physicalTime},{search:async()=>({items:[]})},{search:async()=>({items:[physicalOffer,multiPhysical]})});assert.equal(split.items.length,2,"Single1l and2x500ml physical packs retain distinct selection identities");
 const many=Array.from({length:200},(_,index)=>({...related,retailerSku:String(2000+index),sourceUrl:"https://www.dm.de/p/d/"+(2000+index)+"/test-milch",capturedAt:new Date(physicalTime-1000).toISOString(),expiresAt:new Date(physicalTime-1000+86400000).toISOString()})),capped=await Discovery.search({}, {search:"Milch",now:physicalTime},{search:async()=>({items:many})},injected);assert.equal(capped.items.length,1);assert.equal(capped.items[0].physicalOffers.length,1);assert.equal(capped.items[0].offers.length,199);assert.equal(capped.discoveryTruncated,true,"The combined response cannot exceed200 quote proofs and explicitly signals truncation");
 console.log("published-product-discovery: exact GTIN/sales-pack grouping, current scoped proof preservation, no guessed identities, source/freshness rejection and bounded explicit lookup OK");
 }finally{Date.now=priorClock}
}
main().catch(error=>{console.error(error);process.exitCode=1;});
