"use strict";
const assert=require("assert/strict"),Service=require("../published-price-service");
const now=Date.parse("2026-10-01T10:00:00Z");
function offer(patch={}){return{merchant:"dm",sourceId:"dm online",retailerSku:"12345",gtin:"3017620422003",name:"LOCAL TEST Nutella",brand:"LOCAL TEST Ferrero",pack:"450 g",packAmount:450,packUnit:"g",packCount:1,price:3.99,currency:"EUR",capturedAt:new Date(now-1000).toISOString(),proofHash:"a".repeat(64),sourceUrl:"https://www.dm.de/p/d/12345/local-test-product",scopeCountry:"DE",scopeChannel:"online",availability:"available",...patch}}
const checked=Service.validateOffer(offer(),{now});assert.equal(checked.ok,true);assert.equal(checked.offer.state,"published");assert.equal(checked.offer.expiresAt,new Date(now-1000+86400000).toISOString());assert(!("storeId"in checked.offer));
assert.equal(checked.offer.priceBasis,"pack");assert.equal(checked.offer.shippingIncluded,false);
assert.equal(Service.validateOffer(offer({pack:"1 l",packAmount:1,packUnit:"l"}),{now}).offer.packAmount,1000);
const multi=Service.validateOffer(offer({pack:"2 x 175 g",packAmount:175,packCount:2}),{now});assert.equal(multi.ok,true);assert.equal(multi.offer.packAmount,175);assert.equal(multi.offer.packCount,2);
assert.equal(Service.validateOffer(offer({price:true}),{now}).ok,false,"A boolean source field cannot manufacture a1EUR quote");
assert.equal(Service.validateOffer(offer({pack:"10 piece",packAmount:10,packUnit:"piece",packCount:1}),{now}).offer.packUnit,"piece");
for(const [patch,reason]of[[{sourceId:"unknown source"},"retailer-source-not-approved"],[{retailerSku:"not-a-dan"},"retailer-sku-required"],[{gtin:"3017620422000"},"valid-gtin-required"],[{pack:"unknown"},"known-pack-required"],[{packAmount:750},"pack-metadata-conflict"],[{price:Infinity},"positive-finite-price-required"],[{price:null},"positive-finite-price-required"],[{currency:"USD"},"currency-outside-EUR"],[{scopeChannel:"store"},"online-DE-scope-required"],[{scopeCountry:"FR"},"online-DE-scope-required"],[{storeId:"fictional-store"},"physical-store-scope-unsupported"],[{sourceUrl:"https://example.test/p/d/12345/product"},"exact-first-party-source-url-required"],[{sourceUrl:"https://www.dm.de/p/d/54321/product"},"exact-first-party-source-url-required"],[{sourceUrl:"http://www.dm.de/p/d/12345/product"},"exact-first-party-source-url-required"],[{proofHash:"not-a-hash"},"source-proof-hash-required"],[{capturedAt:"2026-02-30T12:00:00Z"},"capture-time-required"],[{capturedAt:new Date(now+1).toISOString()},"capture-time-future"],[{availability:"assumed"},"invalid-availability"]]){const result=Service.validateOffer(offer(patch),{now});assert.equal(result.ok,false,reason);assert(result.reasons.includes(reason),reason)}
assert.equal(Service.validateOffer(offer({availability:undefined,expiresAt:"2099-01-01T00:00:00Z"}),{now}).offer.availability,"unknown");assert.equal(Service.validateOffer(offer({expiresAt:"2099-01-01T00:00:00Z"}),{now}).offer.expiresAt,checked.offer.expiresAt,"Untrusted expiry cannot extend the service24h freshness policy");
function pool(){const rows=new Map(),calls=[];return{rows,calls,query:async(sql,params=[])=>{calls.push({sql,params});if(sql.startsWith("CREATE TABLE"))return{rows:[],rowCount:0};if(sql.startsWith("INSERT INTO retailer_published_prices")){let rowCount=0;for(const row of JSON.parse(params[0])){const old=rows.get(row.retailer_sku);if(!old||row.captured_at>old.captured_at){rows.set(row.retailer_sku,row);rowCount++}}return{rows:[],rowCount}}return{rows:[],rowCount:0}}}}
assert.equal(Service.matchesProductQuery(offer(),{gtin:offer().gtin}),true);
assert.equal(Service.matchesProductQuery(offer(),{gtin:offer().gtin,pack:"0.45 kg",brand:offer().brand.toUpperCase()}),true);
assert.equal(Service.matchesProductQuery(offer(),{gtin:offer().gtin,pack:"250 g"}),false);
assert.equal(Service.matchesProductQuery(offer(),{gtin:offer().gtin,pack:"2 x 225 g"}),false);
assert.equal(Service.matchesProductQuery(offer(),{gtin:offer().gtin,pack:"unbekannt"}),false);
assert.equal(Service.matchesProductQuery(offer(),{gtin:offer().gtin,brand:"Andere Marke"}),false);
assert.equal(Service.matchesProductQuery(offer(),{gtin:"4008400401621"}),false);
assert.equal(Service.matchesProductQuery(offer(),{name:offer().name}),false);
(async()=>{
 const db=pool(),original=offer(),input=JSON.stringify(original);const first=await Service.persist(db,[original,offer({price:0})],{now});assert.equal(first.accepted,1);assert.equal(first.rejected,1);assert.equal(first.upserted,1);assert.equal(JSON.stringify(original),input);assert.equal(db.rows.get("12345").price,3.99);
 assert.equal((await Service.persist(db,[original],{now})).unchanged,1);assert.equal((await Service.persist(db,[offer({price:9.99,capturedAt:new Date(now-2000).toISOString()})],{now})).unchanged,1);assert.equal(db.rows.get("12345").price,3.99,"An older capture cannot overwrite a newer first-party quote");
 const latest=offer({price:4.29,capturedAt:new Date(now).toISOString(),proofHash:"b".repeat(64),availability:"unavailable"});assert.equal((await Service.persist(db,[original,latest],{now})).upserted,1);assert.equal(db.rows.get("12345").price,4.29);assert.equal(db.rows.get("12345").availability,"unavailable");assert(!db.calls.some(call=>/price_observations|INSERT INTO (?:products|stores)\b/.test(call.sql)),"Published online prices have their own table and create no physical price evidence");
 const query=Service.querySpec({now,merchant:"DM",gtin:original.gtin,search:"Milch%_",limit:999});assert.equal(query.params[1],"dm");assert.equal(query.params[2],original.gtin);assert.equal(query.params[3],"%Milch\\%\\_%");assert.equal(query.params.at(-1),200);assert(query.sql.includes("interval '24 hours'"));assert(query.sql.includes("captured_at<=$1"));
 assert.throws(()=>Service.querySpec({gtin:"invalid"}),/invalid-gtin/);assert.throws(()=>Service.querySpec({today:"2026-02-30"}),/invalid-date/);
 const saved=db.rows.get("12345"),searchPool={query:async sql=>({rows:sql.startsWith("SELECT merchant,source_id")?[{merchant:saved.merchant,retailerSku:saved.retailer_sku,gtin:saved.gtin,capturedAt:saved.captured_at,expiresAt:saved.expires_at,price:saved.price}]:[],rowCount:0})};
 const searched=await Service.search(searchPool,{now});assert.equal(searched.items[0].state,"published");assert.equal(searched.items[0].current,true);assert.equal(searched.scopeCountry,"DE");assert.equal(searched.scopeChannel,"online");
 await assert.rejects(()=>Service.persist(null,[]),/database-required/);await assert.rejects(()=>Service.persist(db,{}),/invalid-published-offers/);await assert.rejects(()=>Service.search(null),/database-required/);
 console.log("published-price-service: exact approved dm SKU/GTIN/pack, first-party quote/hash/time gates, online-only scope, newer-only idempotent upserts and literal bounded search OK");
})().catch(error=>{console.error(error);process.exitCode=1});
