"use strict";
const assert=require("node:assert/strict"),Client=require("../rewe-retailer-price-client"),fixture=require("./fixtures/retailers/rewe-berlin-pickup.json");
const clone=structuredClone,now=()=>fixture.capturedAt,proof={capturedAt:fixture.capturedAt,sourceResponseUrl:Client.PRODUCTS_URL+"?categorySlug=getraenke-genussmittel&marketId="+Client.MARKET_ID+"&serviceTypes=PICKUP&page=1&objectsPerPage=40",sourceResponseHash:"a".repeat(64)},native=fixture.items[0];
function response(data,accept=Client.PRODUCTS_ACCEPT,headers={},status=200){const body=JSON.stringify(data);return{status,headers:{get:key=>({"content-type":accept,date:new Date(fixture.capturedAt).toUTCString(),...headers})[key.toLowerCase()]??null},text:async()=>body};}
function page(items,currentPage=1,objectCount=items.length){return{hits:items,pagination:{objectsPerPage:40,currentPage,pageCount:Math.ceil(objectCount/40),objectCount},search:{term:{original:"*"}}};}
function source({filters=fixture.filters,pageFactory=(slug,index)=>slug==="kaese-eier-molkerei"?page(Array(index===1?40:1).fill(native),index,41):page([]),override={}}={}){const calls=[];return{calls,fetch:async(address,options)=>{calls.push({address,options});if(override[address])return override[address];const u=new URL(address);return u.pathname.endsWith("/filters")?response(filters,Client.FILTERS_ACCEPT):response(pageFactory(u.searchParams.get("categorySlug"),Number(u.searchParams.get("page"))))}};}
async function main(){
 const categories=Client.parseCategories(fixture.filters);assert.equal(categories.categories.length,20);assert.equal(categories.categories[0].slug,"kaese-eier-molkerei");assert(categories.nativeRootCountCapped);assert.equal(categories.categories.reduce((sum,c)=>sum+c.nativeCount,0),14736);assert.match(categories.assortmentHash,/^[a-f0-9]{64}$/);
 const changedCount=clone(fixture.filters);changedCount.items[0].options[0].productCount++;assert.equal(Client.parseCategories(changedCount).assortmentHash,categories.assortmentHash,"changing inventory counts must not restart every continuation");
 for(const patch of[{marketId:"wrong"},{serviceType:"DELIVERY"},{categorySlug:"wrong"}]){const wrong=clone(fixture.filters),option=wrong.items[0].options[0],q=new URLSearchParams(option.toggleQuery);for(const [key,value]of Object.entries(patch))q.set(key,value);option.toggleQuery=q.toString();assert.throws(()=>Client.parseCategories(wrong),/category-query-conflict/);}
 const capped=clone(fixture.filters);capped.items[0].options[0].productCount=10000;assert.throws(()=>Client.parseCategories(capped),/search-ceiling/);
 const selected=clone(fixture.filters);selected.items[0].options[0].applied=true;assert.throws(()=>Client.parseCategories(selected),/tree-invalid/);
 const valid=Client.parseItems(fixture.items,proof);assert(valid.offers.length>0);assert(valid.rejected.some(r=>r.reasons.includes("rewe-variable-weight-price")));
 const redBull=valid.offers.find(o=>o.nativeArticleId===native.articleId);assert.equal(redBull.price,1.49);assert.equal(redBull.deposit,.25);assert.equal(redBull.displayedPrice,1.49);assert.equal(redBull.payablePackPrice,1.74);assert.equal(redBull.nativePriceIncludesDeposit,false);assert.equal(redBull.scopeChannel,"pickup");assert.equal(redBull.nativeStoreId,Client.NATIVE_STORE_ID);assert.equal(redBull.shop.postalCode,"10963");assert.equal(redBull.sourceUrl,"https://www.rewe.de/shop/p/red-bull-energy-drink-glacier-0-25l/9482185");assert.equal(redBull.availability,"unknown");assert.equal(redBull.priceType,"unknown");assert.equal(redBull.proofHash,redBull.sourceResponseHash);assert.equal(redBull.productId,undefined);assert.equal(redBull.storeId,undefined);
 const withoutDeposit=clone(native);delete withoutDeposit.pricing.totalRefundPrice;const unknown=Client.parseItems([withoutDeposit],proof).offers[0];assert.equal(unknown.deposit,null);assert.equal(unknown.payablePackPrice,null);
 const zeroDeposit=clone(native);zeroDeposit.pricing.totalRefundPrice=0;assert.equal(Client.parseItems([zeroDeposit],proof).offers[0].payablePackPrice,1.49);
 assert(Client.parseItems([fixture.prefix13Item],proof).offers.length,"native listingprefix13 is a separate valid listing, not a guessed invalid type");
 assert.equal(Client.parseItems([fixture.conflictingPackItem],proof).offers.length,0,"native title4x150g and grammage4x600g must never become a comparable quote");
 const multipack=valid.offers.find(o=>o.nativeArticleId==="EWYNO6CE");assert.equal(multipack.packParsed.count,4);assert.equal(multipack.packParsed.total.amount,1000);assert.equal(multipack.payablePackPrice,6.49);
 const pieces=Client.parseItems(fixture.pieceItems,proof);assert.equal(pieces.offers.length,fixture.pieceItems.length);assert(pieces.offers.some(o=>o.packParsed.total.amount===10&&o.packParsed.total.unit==="piece"));assert.equal(Client.parseItems([{...fixture.pieceItems[0],quantityType:"UNKNOWN"}],proof).offers.length,0);assert.equal(Client.parseItems([{...fixture.pieceItems[0],baseQuantity:999}],proof).offers.length,0);
 for(const patch of[{pricing:{...native.pricing,currentRetailPrice:0}},{pricing:{...native.pricing,totalRefundPrice:-1}},{pricing:{...native.pricing,grammage:"ca. 250ml"}},{pricing:{...native.pricing,grammage:"1 l",currency:"USD"}},{pricing:{...native.pricing,bulkDiscountTiers:[{minimumQuantity:3,price:100}]}},{pricing:{...native.pricing,tiers:[{}]}},{gtin:"0000000000001"},{listingId:native.listingId.replace(Client.NATIVE_STORE_ID,"00000000-0000-0000-0000-000000000000")},{marketId:"8321065"},{serviceType:"DELIVERY"},{currency:"USD"},{detailsUrl:"https://evil.example/p/x/9482185"},{volumeCode:"KGG"},{baseQuantity:2},{multi1:2},{viewInfo:{detailsViewRequired:true}},{hasVariants:true},{options:[{}]},{tags:["bulk-discounted"]},{minOrderQuantity:2}])assert.equal(Client.parseItems([{...native,...patch}],proof).offers.length,0,JSON.stringify(patch));
 for(const bad of[Client.PRODUCTS_URL+"?marketId=8321066&serviceTypes=PICKUP&page=1&objectsPerPage=40",proof.sourceResponseUrl.replace("8321066","8321065"),proof.sourceResponseUrl+"&marketId=8321066",proof.sourceResponseUrl+"&bypass=1",proof.sourceResponseUrl.replace("PICKUP","DELIVERY"),proof.sourceResponseUrl.replace("www.rewe.de","evil.example")])assert.throws(()=>Client.allowedUrl(bad),/not-allowed/);
 const transport=source(),first=await Client.fetchOffers({maxRequests:2,pauseMs:0,now},transport.fetch);assert.equal(first.complete,false);assert.equal(first.nextCursor.categoryIndex,0);assert.equal(first.nextCursor.pageNumber,2);assert.equal(first.pagesFetched,1);assert.equal(first.received,40);assert.equal(first.offers.length,1,"overlapping native listings in a bounded batch are deduplicated by full listing ID");
 const second=await Client.fetchOffers({maxRequests:2,pauseMs:0,now,cursor:first.nextCursor},transport.fetch);assert.equal(second.complete,false);assert.equal(second.categoriesCompleted,1);assert.equal(second.nextCursor.categoryIndex,1);assert.equal(second.nextCursor.pageNumber,1);assert.equal(second.receivedCumulative,41);
 const last=await Client.fetchOffers({maxRequests:48,pauseMs:0,now,cursor:second.nextCursor},transport.fetch);assert.equal(last.complete,true);assert.equal(last.nextCursor,null);assert.equal(last.categoriesCompleted,20);assert.equal(last.pagesFetched,21);assert.equal(last.receivedCumulative,41);assert.equal(last.publishedAssortmentComplete,true);assert.equal(last.fullAssortmentVerified,false);assert.equal(last.physicalStoreAssortmentVerified,false);
 for(const call of transport.calls){assert.equal(call.options.method,"GET");assert.equal(call.options.credentials,"omit");assert.equal(call.options.redirect,"error");assert(!call.options.headers.Cookie);assert(call.options.headers.Accept.includes("application/vnd.rewe.digital."));assert(new URL(call.address).searchParams.get("categorySlug")||call.address.includes("/filters?"));}
 const bigFilters=clone(fixture.filters);bigFilters.items[0].options=bigFilters.items[0].options.filter(c=>["kaese-eier-molkerei","getraenke-genussmittel"].includes(c.value));for(const c of bigFilters.items[0].options)c.productCount=3600;
 const large=source({filters:bigFilters,pageFactory:(slug,index)=>page(Array.from({length:40},(_,offset)=>{const id=(slug==="kaese-eier-molkerei"?0:3600)+(index-1)*40+offset;return{...clone(native),articleId:"TEST"+id,listingId:"8-TEST"+id+"-"+Client.NATIVE_STORE_ID,productId:String(100000+id),detailsUrl:"/p/test-pack/"+(100000+id)};}),index,3600)});let cursor=null,result,calls=0,totalOffers=0;do{result=await Client.fetchOffers({maxRequests:16,pauseMs:0,now,cursor},large.fetch);cursor=result.nextCursor;calls++;totalOffers+=result.offers.length;assert(calls<20);}while(!result.complete);assert.equal(result.receivedCumulative,7200);assert.equal(result.pagesFetched,180);assert.equal(totalOffers,7200);assert.equal(result.categoriesCompleted,2,"native assortment completion must not stop at curated6000 catalog");
 await assert.rejects(()=>Client.fetchOffers({maxRequests:2,pauseMs:0,now,cursor:{...first.nextCursor,assortmentHash:"b".repeat(64)}},source().fetch),/cursor-conflict/);
 const firstProducts=transport.calls[1].address;
 for(const [headers,error]of[[{age:"901"},/cache-age/],[{age:"-1"},/cache-age/],[{date:"Thu, 01 Oct 2026 00:00:00 GMT"},/response-date/],[{date:null},/response-date/],[{"content-type":"application/vnd.rewe.fallback+json"},/content-type/],[{"content-length":"999999999"},/body-too-large/]]){const src=source({override:{[firstProducts]:response(page([native]),Client.PRODUCTS_ACCEPT,headers)}});await assert.rejects(()=>Client.fetchOffers({maxRequests:2,pauseMs:0,now},src.fetch),error);assert.equal(src.calls.length,2);}
 for(const status of[403,429]){const stopped=source({override:{[firstProducts]:response({},Client.PRODUCTS_ACCEPT,{"retry-after":"600"},status)}});await assert.rejects(()=>Client.fetchOffers({pauseMs:0,now},stopped.fetch),error=>error.status===status&&error.retryAfterMs===600000);assert.equal(stopped.calls.length,2,"blocks stop without retries, cookie borrowing or another endpoint");}
 for(const data of[page([],1,41),page([native],2,41),{...page([native]),pagination:{currentPage:1,pageCount:250,objectsPerPage:40,objectCount:10000}},{...page([native]),search:{marketCode:"8321065"}},{...page([native]),search:{serviceTypes:["DELIVERY"]}}])assert.throws(()=>Client.categoryPage(data,categories.categories[0],1),/page/);
 assert.doesNotThrow(()=>Client.categoryPage(page([]),categories.categories[0],1));
 for(const changed of[page([],27,1000),page(Array(40).fill(native),25,1000),page([])])assert.throws(()=>Client.categoryPage(changed,categories.categories[0],27),error=>error.code==="rewe-native-category-pagination-count-drift");assert.throws(()=>Client.categoryPage(page([],2,1000),categories.categories[0],2),error=>error.code==="rewe-native-category-page-conflict","an emptyearlypage must not reset or complete the scan");
 const nearCeiling=source({pageFactory:()=>page(Array(40).fill(native),249,9999)}),near=await Client.fetchOffers({maxRequests:2,pauseMs:0,now,cursor:{...first.nextCursor,pageNumber:249,received:9920,pagesFetched:248}},nearCeiling.fetch);assert.equal(near.nextCursor.pageNumber,250);assert.equal(near.stalled,false,"a legitimate9999-item category needsits final250thpage; exact10000is rejected separately");
 console.log("rewe-retailer-price-client: verified public Berlin pickup scope, native all-category paging past6000, bounded durable continuation, listingprefix13 and dedup, exact pack/deposit evidence, malformed/stale/cache/blocked source rejection OK");
}
main().catch(error=>{console.error(error);process.exitCode=1;});
