"use strict";
const assert=require("assert/strict"),Service=require("../rewe-retailer-price-service");
const now=Date.parse("2026-10-01T10:00:00Z"),market=Service.MARKET;
function offer(patch={}){return{sourceId:Service.SOURCE,merchant:"REWE",nativeMarketId:market.nativeMarketId,nativeStoreId:market.nativeStoreId,retailerSku:"8-FKRIL2JI-"+market.nativeStoreId,retailerProductId:"9482185",nativeArticleId:"FKRIL2JI",gtin:"90486647",name:"LOCAL TEST Red Bull Glacier 0,25l",brand:"Red Bull",pack:"0.25 l",packAmount:.25,packUnit:"l",packCount:1,price:1.49,deposit:.25,displayedPrice:1.49,nativePriceEUR:1.49,nativePriceIncludesDeposit:false,depositIncludedInDisplayedPrice:false,payablePackPrice:1.74,currency:"EUR",priceType:"unknown",promotionStatus:"unknown",availability:"unknown",capturedAt:new Date(now-1000).toISOString(),sourceUrl:"https://www.rewe.de/shop/p/red-bull-energy-drink-glacier-0-25l/9482185",sourceResponseUrl:"https://www.rewe.de/shop/api/products?marketId=8321066&serviceTypes=PICKUP&page=1&objectsPerPage=40",proofHash:"a".repeat(64),sourceResponseHash:"a".repeat(64),shop:{...market},scopeCountry:"DE",scopeChannel:"pickup",fulfillmentChannel:"pickup",serviceType:"PICKUP",priceBasis:"pack",...patch};}
function pool(){const rows=new Map(),calls=[];return{rows,calls,query:async(sql,params=[])=>{calls.push({sql,params});if(sql.startsWith("CREATE TABLE"))return{rows:[],rowCount:0};if(sql.startsWith("SELECT p.source_id"))return{rows:JSON.parse(params[0]).map(x=>rows.get(x.source_id+"|"+x.native_market_id+"|"+x.retailer_sku)).filter(Boolean),rowCount:0};if(sql.startsWith("INSERT INTO rewe_retailer_published_prices")){let rowCount=0;for(const row of JSON.parse(params[0])){const id=row.source_id+"|"+row.native_market_id+"|"+row.retailer_sku,old=rows.get(id);if(!old||row.captured_at>old.captured_at){rows.set(id,row);rowCount++;}}return{rows:[],rowCount};}return{rows:[],rowCount:0};}};}
const checked=Service.validateOffer(offer(),{now});assert.equal(checked.ok,true,JSON.stringify(checked));const approved=checked.offer;
assert.equal(approved.price,1.49);assert.equal(approved.deposit,.25);assert.equal(approved.displayedPrice,1.49,"REWE's native merchandise price excludes deposit");assert.equal(approved.nativePriceIncludesDeposit,false);assert.equal(approved.depositIncludedInDisplayedPrice,false);assert.equal(approved.payablePackPrice,1.74);assert.equal(approved.packAmount,250);assert.equal(approved.packUnit,"ml");assert.equal(approved.packCount,1);assert.equal(approved.expiresAt,new Date(now-1000+Service.DAY_MS).toISOString());assert.equal(approved.fulfillmentChannel,"pickup");assert.equal(approved.truthEligible,false);assert.equal(approved.shippingIncluded,false);assert.equal(approved.serviceFeesIncluded,false);assert(!("storeId"in approved));assert(!("canonicalProductId"in approved));assert(!("productId"in approved));
const unknown=Service.validateOffer(offer({deposit:null,payablePackPrice:null,depositIncludedInDisplayedPrice:null}),{now});assert.equal(unknown.ok,true);assert.equal(unknown.offer.deposit,null);assert.equal(unknown.offer.depositIncludedInDisplayedPrice,null);assert.equal(unknown.offer.payablePackPrice,null,"Missing native refund price cannot establish the checkout total");
assert.equal(Service.validateOffer(offer({gtin:null}),{now}).offer.identityStatus,"native-retailer-sku");assert.equal(Service.validateOffer(offer({gtin:""}),{now}).offer.gtin,null);
const crate=Service.validateOffer(offer({retailerSku:"13-5449000134271-"+market.nativeStoreId,nativeArticleId:"5449000134271",gtin:"5449000134271",pack:"12 x 1 l",packAmount:1,packUnit:"l",packCount:12,price:11.99,deposit:3.3,displayedPrice:11.99,nativePriceEUR:11.99,payablePackPrice:15.29}),{now});assert.equal(crate.ok,true,JSON.stringify(crate));assert.equal(crate.offer.packAmount,1000);assert.equal(crate.offer.packCount,12);assert.equal(crate.offer.payablePackPrice,15.29);
const queryUrl=offer().sourceResponseUrl;assert.equal(Service.validateOffer(offer({sourceResponseUrl:queryUrl+"&categorySlug=kaese-eier-molkerei"}),{now}).ok,true);
assert.equal(Service.validateOffer(offer({expiresAt:"2099-01-01T00:00:00Z"}),{now}).offer.expiresAt,approved.expiresAt);
const deadline="2026-10-01T14:00:00.000+02:00",sale=Service.validateOffer(offer({nativePromotionValidTo:deadline}),{now});assert.equal(sale.ok,true);assert.equal(sale.offer.nativePromotionValidTo,"2026-10-01T12:00:00.000Z");assert.equal(sale.offer.expiresAt,"2026-10-01T12:00:00.000Z");assert.equal(sale.offer.priceType,"unknown","A native expiry bounds validity even without proving a regular price");
assert.equal(Service.validateOffer(offer({nativePromotionValidTo:"2026-10-03T12:00:00Z"}),{now}).offer.expiresAt,approved.expiresAt);
for(const invalid of["2026-02-30T12:00:00Z","2026-10-01T12:00:00",true,"", "2026-10-01T12:00:00+25:00"]){const result=Service.validateOffer(offer({nativePromotionValidTo:invalid}),{now});assert.equal(result.ok,false);assert(result.reasons.includes("invalid-native-price-validity"));}
for(const expired of[new Date(now).toISOString(),new Date(now-1).toISOString()]){const result=Service.validateOffer(offer({nativePromotionValidTo:expired}),{now});assert.equal(result.ok,false);assert(result.reasons.includes("native-price-validity-expired"));}
assert.equal(Service.validateOffer(offer({retailerSku:"12345-FKRIL2JI-"+market.nativeStoreId}),{now}).ok,true);assert.equal(Service.validateOffer(offer({retailerSku:"0-FKRIL2JI-"+market.nativeStoreId}),{now}).ok,false);
for(const[patch,reason]of[
 [{sourceId:"REWE nationwide"},"retailer-source-not-approved"],[{merchant:"EDEKA"},"retailer-source-not-approved"],[{nativeMarketId:"999"},"native-market-not-approved"],[{nativeStoreId:"0".repeat(36)},"native-market-not-approved"],[{retailerSku:"synthetic"},"native-listing-id-required"],[{nativeArticleId:"wrong"},"native-listing-id-required"],[{retailerSku:"8-FKRIL2JI-ffffffff-fa98-3b7e-9ee5-8132f39c189c"},"native-listing-id-required"],[{retailerProductId:"fake"},"native-product-id-required"],[{serviceType:"DELIVERY"},"pickup-service-required"],[{fulfillmentChannel:"delivery"},"pickup-service-required"],
 [{gtin:"90486640"},"invalid-native-gtin"],[{pack:"unknown"},"known-pack-required"],[{pack:"ca. 250 g"},"known-pack-required"],[{variableWeight:true},"known-pack-required"],[{packAmount:1},"pack-metadata-conflict"],[{packCount:true},"pack-metadata-conflict"],[{pack:"4 x 600 g",packAmount:150,packUnit:"g",packCount:4},"pack-metadata-conflict"],
 [{price:true},"positive-finite-price-required"],[{price:Infinity},"positive-finite-price-required"],[{price:"1.49"},"positive-finite-price-required"],[{deposit:true},"invalid-deposit"],[{deposit:-1},"invalid-deposit"],[{price:1.491,displayedPrice:1.491,nativePriceEUR:1.491,payablePackPrice:1.741},"native-price-deposit-conflict"],[{displayedPrice:1.74,nativePriceEUR:1.74},"native-price-deposit-conflict"],[{nativePriceIncludesDeposit:true},"native-price-deposit-conflict"],[{depositIncludedInDisplayedPrice:true},"native-price-deposit-conflict"],[{payablePackPrice:1.49},"native-price-deposit-conflict"],[{deposit:null,payablePackPrice:1.49},"native-price-deposit-conflict"],
 [{priceType:"regular"},"unattested-price-type"],[{promotionStatus:"promotion"},"unattested-promotion-status"],[{personalizedPrice:true},"non-public-price-unsupported"],[{requiresMembership:true},"non-public-price-unsupported"],[{priceAudience:"loyalty"},"non-public-price-unsupported"],[{currency:"USD"},"currency-outside-EUR"],[{scopeChannel:"store"},"pickup-DE-scope-required"],[{scopeCountry:"AT"},"pickup-DE-scope-required"],[{storeId:"made-up-store"},"physical-identity-scope-unsupported"],[{canonicalProductId:"made-up-product"},"physical-identity-scope-unsupported"],[{productId:"9482185"},"physical-identity-scope-unsupported"],[{priceBasis:"kg"},"pack-price-required"],
 [{capturedAt:"2026-02-30T12:00:00Z"},"capture-time-required"],[{capturedAt:new Date(now+1).toISOString()},"capture-time-future"],[{sourceUrl:offer().sourceUrl.replace("9482185","9482186")},"exact-native-product-url-required"],[{sourceUrl:offer().sourceUrl+"?discount=1"},"exact-native-product-url-required"],[{sourceUrl:"https://evil.example/shop/p/red-bull/9482185"},"exact-native-product-url-required"],[{sourceResponseUrl:queryUrl.replace("8321066","9999999")},"exact-native-response-url-required"],[{sourceResponseUrl:queryUrl.replace("PICKUP","DELIVERY")},"exact-native-response-url-required"],[{sourceResponseUrl:queryUrl.replace("page=1","page=0")},"exact-native-response-url-required"],[{sourceResponseUrl:queryUrl.replace("objectsPerPage=40","objectsPerPage=200")},"exact-native-response-url-required"],[{sourceResponseUrl:queryUrl+"&marketId=8321066"},"exact-native-response-url-required"],[{sourceResponseUrl:queryUrl+"&userToken=abc"},"exact-native-response-url-required"],[{sourceResponseHash:"b".repeat(64)},"source-proof-hash-required"],[{availability:"inferred"},"invalid-availability"],[{shop:{...market,address:"Other Street 40"}},"native-Berlin-shop-scope-required"],[{shop:{...market,postalCode:"10117"}},"native-Berlin-shop-scope-required"]
]){const result=Service.validateOffer(offer(patch),{now});assert.equal(result.ok,false,reason);assert(result.reasons.includes(reason),reason);}
assert.equal(Service.validateOffer(offer({originalPrice:1.99,priceType:"promotion",promotionStatus:"promotion"}),{now}).ok,true);
assert(Service.validateOffer(offer({loyaltyPrice:1.19}),{now}).reasons.includes("non-public-price-unsupported"));
assert.equal(Service.matchesProductQuery(approved,{gtin:approved.gtin,pack:"250 ml"}),true);assert.equal(Service.matchesProductQuery(approved,{gtin:approved.gtin,pack:"4 x 250 ml"}),false);assert.equal(Service.matchesProductQuery(approved,{name:approved.name}),false);
(async()=>{
 const db=pool(),original=offer(),snapshot=JSON.stringify(original);let saved=await Service.persist(db,[original,offer({price:0})],{now});assert.equal(saved.accepted,1);assert.equal(saved.rejected,1);assert.equal(saved.upserted,1);assert.equal(JSON.stringify(original),snapshot);assert.equal((await Service.persist(db,[original],{now})).unchanged,1);
 const conflict=offer({price:1.59,displayedPrice:1.59,nativePriceEUR:1.59,payablePackPrice:1.84});saved=await Service.persist(db,[conflict],{now});assert.equal(saved.accepted,0);assert.equal(saved.reasons["same-capture-conflict"],1);
 const batchDb=pool();saved=await Service.persist(batchDb,[original,conflict],{now});assert.equal(saved.accepted,0);assert.equal(saved.rejected,2);assert.equal(batchDb.rows.size,0);saved=await Service.persist(batchDb,[original,original],{now});assert.equal(saved.accepted,1);assert.equal(saved.duplicates,1);
 const newer=offer({price:1.59,displayedPrice:1.59,nativePriceEUR:1.59,payablePackPrice:1.84,capturedAt:new Date(now).toISOString(),proofHash:"b".repeat(64),sourceResponseHash:"b".repeat(64),availability:"unavailable"});assert.equal((await Service.persist(db,[newer],{now})).upserted,1);assert.equal((await Service.persist(db,[original],{now})).unchanged,1);assert.equal([...db.rows.values()][0].price,1.59);
 const otherListing=offer({retailerSku:"13-FKRIL2JI-"+market.nativeStoreId});assert.equal((await Service.persist(db,[otherListing],{now})).upserted,1);assert.equal(db.rows.size,2,"Complete listingId retains native pack variants even for one GTIN");
 assert(!db.calls.some(call=>/price_observations|INSERT INTO (?:products|stores|receipts)\b/.test(call.sql)),"Pickup evidence must not mutate physical or receipt records");
 const many=Array.from({length:501},(_,index)=>offer({nativeArticleId:"TEST"+index,retailerSku:"8-TEST"+index+"-"+market.nativeStoreId})),bulk=pool();saved=await Service.persist(bulk,many,{now});assert.equal(saved.accepted,501);assert.deepEqual(bulk.calls.filter(call=>call.sql.startsWith("INSERT INTO ")).map(call=>JSON.parse(call.params[0]).length),[500,1]);
 const query=Service.querySpec({now,merchant:"rewe",nativeMarketId:market.nativeMarketId,nativeStoreId:market.nativeStoreId,gtin:original.gtin,search:"Milch%_",today:"2026-10-01",limit:999});assert.deepEqual(query.params.slice(1,5),["rewe",market.nativeMarketId,market.nativeStoreId,original.gtin]);assert.equal(query.params[5],"%Milch\\%\\_%");assert.equal(query.params.at(-1),200);assert(query.sql.includes("captured_at<=$1"));assert(query.sql.includes("expires_at>$1"));assert(query.sql.includes("Europe/Berlin"));assert(query.sql.includes("scope_channel='pickup'"));
 const union=Service.gtinQuerySpec({now});assert.deepEqual(union.params,[new Date(now).toISOString()]);assert(union.sql.includes("gtin IS NOT NULL"));assert(union.sql.includes("scope_channel='pickup'"));assert(union.sql.includes("expires_at>$1"));assert(!union.sql.includes("LIMIT"));
 assert.throws(()=>Service.querySpec({gtin:"invalid"}),/invalid-gtin/);assert.throws(()=>Service.querySpec({nativeMarketId:"invalid"}),/invalid-native-market-id/);assert.throws(()=>Service.querySpec({nativeStoreId:"invalid"}),/invalid-native-store-id/);assert.throws(()=>Service.querySpec({today:"2026-02-30"}),/invalid-date/);
 const searchDb={query:async sql=>({rows:sql.startsWith("SELECT source_id AS")?[approved]:[],rowCount:0})},found=await Service.search(searchDb,{now});assert.equal(found.items[0].price,1.49);assert.equal(found.items[0].payablePackPrice,1.74);assert.equal(found.items[0].nativePriceIncludesDeposit,false);assert.equal(found.items[0].fulfillmentChannel,"pickup");assert.equal(found.items[0].truthEligible,false);assert.equal(found.items[0].current,true);
 const statusDb={query:async sql=>({rows:sql.startsWith("SELECT count(*)")?[{storedPrices:2,currentPrices:1,productsWithCurrentPublishedPrices:1,marketsWithCurrentPublishedPrices:1,availableCurrentPrices:0,lastCapturedAt:approved.capturedAt}]:sql.startsWith("SELECT merchant")?[{...market,currentPrices:1}]:[],rowCount:0})},status=await Service.status(statusDb,{now});assert.equal(status.currentPrices,1);assert.equal(status.scopeChannel,"pickup");assert.equal(status.truthEligible,false);assert.equal(status.independentOfUserReceipts,true);assert.equal(status.markets.length,1);
 await assert.rejects(()=>Service.persist(null,[]),/database-required/);await assert.rejects(()=>Service.persist(db,{}),/invalid-published-offers/);await assert.rejects(()=>Service.search(null),/database-required/);
 console.log("rewe-retailer-price-service: exact native Berlin pickup scope/listings, optional GTIN and fixed packs, deposit excluded from merchandise price, truthful unknown classifications, proof/capture gates, conflict rejection, newer-only 500-row batches and bounded literal fresh queries OK");
})().catch(error=>{console.error(error);process.exitCode=1});
