"use strict";
const assert=require("assert/strict"),Refresh=require("../rewe-retailer-price-refresh"),Client=require("../rewe-retailer-price-client"),Runner=require("../price-refresh-runner"),Semantics=require("../source-semantics"),Sources=require("../price-sources");
const NOW=Date.parse("2026-10-01T12:00:00Z"),HASH="a".repeat(64),copy=value=>structuredClone(value),iso=value=>new Date(value).toISOString();
function cursor(page){return{version:1,nativeMarketId:Client.MARKET_ID,scopeChannel:"pickup",serviceType:"PICKUP",assortmentHash:HASH,categoryIndex:0,pageNumber:page+1,received:8000+page*40,pagesFetched:200+page};}
function batch(page,complete=false){return{offers:[{retailerSku:"TEST native offer"}],received:40,receivedCumulative:8000+page*40,pagesFetched:200+page,categoryCount:2,categoriesCompleted:complete?2:0,complete,nextCursor:complete?null:cursor(page),assortmentHash:HASH,requests:2,rejected:[]};}
function database(initial={}){
 const state=copy(initial),calls=[];
 return{state,calls,failCheckpoint:false,query:async function(sql,params=[]){
  calls.push({sql,params:copy(params)});
  if(sql.startsWith("SELECT cursor"))return{rows:Object.keys(state).length?[copy(state)]:[]};
  if(sql.startsWith("INSERT INTO rewe_retailer_catalog_state")&&params.length===4){state.lastError=params[1];state.retryAfter=params[2];if(params[3])Object.assign(state,{cursor:null,lastCompletedAt:null,categoriesCompleted:0});return{rows:[],rowCount:1};}
  if(sql.startsWith("INSERT INTO rewe_retailer_catalog_state")){if(this.failCheckpoint)throw Error("checkpoint-write-failed");Object.assign(state,{cursor:JSON.parse(params[1]),lastCompletedAt:params[2]?params[3]:state.lastCompletedAt||null,completedCycles:(state.completedCycles||0)+(params[2]?1:0),categoryCount:params[4],categoriesCompleted:params[5],pagesFetched:params[6],receivedCumulative:params[7],assortmentHash:params[8],lastError:null,retryAfter:null,updatedAt:params[3]});return{rows:[],rowCount:1};}
  return{rows:[],rowCount:0};
 }};
}
async function main(){
 assert.equal(Sources.canImport(Client.SOURCE),true);assert.equal(Semantics.truthEligible({sourceId:Client.SOURCE}),false);
 const pool=database({cursor:cursor(0)}),saved=[];
 const deps={fetchOffers:async options=>{assert.deepEqual(options.cursor,pool.state.cursor);assert.equal(options.maxRequests,16);return batch(pool.state.pagesFetched?2:1);},persist:async(db,offers)=>{assert.equal(db,pool);saved.push(offers);return{received:1,accepted:1};}};
 const first=await Refresh.refresh({pool,now:()=>NOW},deps);assert.equal(first.catalog.publishedAssortmentComplete,false);assert.equal(first.catalog.receivedCumulative,8040,"A resumed scan beyond 6,000 entries must keep progressing");assert.equal(first.nextAttemptAt,iso(NOW+60000));assert.deepEqual(pool.state.cursor,cursor(1));
 const second=await Refresh.refresh({pool,now:()=>NOW+60000},{...deps,fetchOffers:async()=>batch(2,true)});assert.equal(second.catalog.publishedAssortmentComplete,true);assert.equal(second.nextAttemptAt,null);assert.equal(pool.state.cursor,null);assert.equal(pool.state.completedCycles,1);assert.equal((await Refresh.status(pool)).publishedAssortmentComplete,true);assert.equal((await Refresh.status(pool)).scopeChannel,"pickup");assert.equal(saved.length,2);
 const dbFailure=database({cursor:cursor(0)});await assert.rejects(()=>Refresh.refresh({pool:dbFailure,now:()=>NOW},{fetchOffers:async()=>batch(1),persist:async()=>{throw Error("price-database-failed")}}),/price-database-failed/);assert.deepEqual(dbFailure.state.cursor,cursor(0));assert(!dbFailure.calls.some(call=>call.sql.startsWith("INSERT")),"Failed quote storage must not advance its native checkpoint");
 const checkpointFailure=database({cursor:cursor(0)});checkpointFailure.failCheckpoint=true;await assert.rejects(()=>Refresh.refresh({pool:checkpointFailure,now:()=>NOW},{fetchOffers:async()=>batch(1),persist:async()=>({accepted:1})}),/checkpoint-write-failed/);assert.deepEqual(checkpointFailure.state.cursor,cursor(0));
 const denied=database({cursor:cursor(0)}),error=Object.assign(Error("rewe-source-http-429"),{retryAfterMs:7200000});let fetches=0;
 await assert.rejects(()=>Refresh.refresh({pool:denied,now:()=>NOW},{fetchOffers:async()=>{fetches++;throw error;}}),e=>e.nextAttemptAt===iso(NOW+7200000));assert.deepEqual(denied.state.cursor,cursor(0));assert.equal(denied.state.retryAfter,iso(NOW+7200000));
 const skipped=await Refresh.refresh({pool:denied,now:()=>NOW+3600000},{fetchOffers:async()=>{fetches++;return batch(1);}});assert.equal(skipped.skipped,"source-cooldown");assert.equal(fetches,1);assert.equal(await Refresh.resumeAt(denied,NOW+3600000),iso(NOW+7200000));
 const oldState={lastAttemptAt:iso(NOW-900000),lastSuccessAt:iso(NOW-900000),lastReceived:40,lastAccepted:39,consecutiveFailures:2,lastError:"source-denied"};const run=await Runner.runOne(Client.SOURCE,oldState,{[Client.SOURCE]:async()=>skipped},{nowMs:NOW});assert.equal(run.skipped,"source-cooldown");for(const key of Object.keys(oldState))assert.equal(run.state[key],oldState[key]);assert.equal(run.state.nextAttemptAt,iso(NOW+7200000));
 const changed=database({cursor:cursor(0),lastCompletedAt:iso(NOW-86400000),completedCycles:1});await assert.rejects(()=>Refresh.refresh({pool:changed,now:()=>NOW},{fetchOffers:async()=>{throw Error("rewe-continuation-cursor-conflict");}}),/continuation-cursor-conflict/);assert.equal(changed.state.cursor,null);assert.equal(changed.state.lastCompletedAt,null);assert.equal((await Refresh.status(changed)).publishedAssortmentComplete,false);assert.equal(changed.state.completedCycles,1);
 for(const patch of[{complete:true,categoriesCompleted:0},{nextCursor:null},{nextCursor:{...cursor(1),nativeMarketId:"123"}},{nextCursor:{...cursor(1),scopeChannel:"online"}},{nextCursor:{...cursor(1),serviceType:"DELIVERY"}},{nextCursor:{...cursor(1),received:1}},{nextCursor:{...cursor(1),pagesFetched:99}},{complete:true,categoriesCompleted:2,nextCursor:cursor(1)}]){const invalid=database({cursor:cursor(0)});let writes=0;await assert.rejects(()=>Refresh.refresh({pool:invalid,now:()=>NOW},{fetchOffers:async()=>({...batch(1),...patch}),persist:async()=>{writes++;return{accepted:1};}}),/progress-unconfirmed/);assert.equal(writes,0);assert.deepEqual(invalid.state.cursor,cursor(0));}
 for(const patch of[{stalled:true},{pagesFetched:200},{receivedCumulative:7999}]){const invalid=database({cursor:cursor(0)});await assert.rejects(()=>Refresh.refresh({pool:invalid,now:()=>NOW},{fetchOffers:async()=>({...batch(1),...patch}),persist:async()=>{throw Error("Must not persist stalled progress");}}),/progress-stalled/);assert.deepEqual(invalid.state.cursor,cursor(0));}
 const shrink=database({cursor:cursor(0),lastCompletedAt:iso(NOW-86400000),completedCycles:1});await assert.rejects(()=>Refresh.refresh({pool:shrink,now:()=>NOW},{fetchOffers:async()=>{throw Error("rewe-native-category-pagination-count-drift");}}),/pagination-count-drift/);assert.equal(shrink.state.cursor,null,"A verified smaller native category restarts the scan instead of repeating its invalid page forever");assert.equal((await Refresh.status(shrink)).publishedAssortmentComplete,false);assert.equal(await Refresh.resumeAt(shrink,NOW),iso(NOW+3600000));
 assert.equal(await Refresh.resumeAt(database({cursor:cursor(0),updatedAt:iso(NOW)}),NOW),iso(NOW+60000));assert.equal(await Refresh.resumeAt(database({cursor:null,updatedAt:iso(NOW)}),NOW),null);
 let release,started;const start=new Promise(resolve=>{started=resolve;}),held=Refresh.refresh({pool:database(),now:()=>NOW},{fetchOffers:async()=>{started();return new Promise(resolve=>{release=()=>resolve(batch(1,true));});},persist:async()=>({accepted:1})});await start;assert.equal((await Refresh.refresh({pool:database(),now:()=>NOW})).skipped,"already-running");release();await held;
 let budget;await Refresh.refresh({pool:database(),maxRequests:999,now:()=>NOW},{fetchOffers:async options=>{budget=options.maxRequests;return batch(1,true);},persist:async()=>({accepted:1})});assert.equal(budget,48);
 assert(!pool.calls.some(call=>/price_observations|receipts|UPDATE products|INSERT INTO stores/.test(call.sql)));
 console.log("rewe-retailer-price-refresh: durable full-category progression past 6,000, completion/continuation, 429 cooldown, no fabricated freshness, invalid/stalled cursor rejection and failed-write recovery OK");
}
main().catch(error=>{console.error(error);process.exitCode=1;});
