"use strict";
const assert=require("node:assert/strict"),Client=require("../rewe-retailer-price-client"),Refresh=require("../rewe-retailer-price-refresh");
// Authored synthetic responses, not retimed archived captures. The native JSON
// shape is tested through the actual client and both original-response readers.
const TIME=Date.parse("2026-10-03T12:00:00.123Z"),OWNER="synthetic-rewe-refresh-owner",copy=structuredClone,iso=n=>new Date(n).toISOString();
const filtersUrl=Client.FILTERS_URL+"?marketId="+Client.MARKET_ID+"&serviceTypes=PICKUP";
const category=(id="3684",slug="kaese-eier-molkerei",count=41)=>({id,value:slug,label:"Synthetic native category "+id,applied:false,productCount:count,queryParams:[{name:"categorySlug",value:slug}]});
function filters(options=[category()]){return{productCount:options.reduce((n,c)=>n+c.productCount,0),items:[{type:"category",key:"CATEGORY",options}]};}
function item(changes={}){return{type:"LISTING",articleId:"SYNTHETIC1",productId:"9900001",listingId:"8-SYNTHETIC1-"+Client.NATIVE_STORE_ID,title:"Synthetic native fixed drink 250ml",gtin:"90486647",detailsUrl:"/p/synthetic-native-fixed-drink/9900001",serviceType:"PICKUP",volumeCode:"STK",baseQuantity:0.25,quantityType:"L",viewInfo:{detailsViewRequired:false},tags:[],pricing:{grammage:"250ml",currentRetailPrice:149,totalRefundPrice:25},...changes};}
function productPage(items,number=1,total=items.length,slug="kaese-eier-molkerei"){return{hits:items,pagination:{currentPage:number,objectsPerPage:40,pageCount:Math.ceil(total/40),objectCount:total},search:{marketCode:Client.MARKET_ID,serviceTypes:["PICKUP"],activeCategorySlug:slug}};}
function transport({nativeFilters=filters(),pages,status=200,onRequest,now=()=>TIME}={}){
 const calls=[];
 const fetch=async(url,options)=>{
  const u=new URL(url);calls.push({url,options});if(onRequest)await onRequest(calls.length,url);
  const first=u.pathname.endsWith("filters"),p=Number(u.searchParams.get("page")),slug=u.searchParams.get("categorySlug"),raw=first?nativeFilters:pages?pages({page:p,slug}):productPage(Array.from({length:p===1?40:1},()=>item()),p,41,slug),body=JSON.stringify(raw),code=typeof status==="function"?status(calls.length,url):first?200:status;
  return{status:code,url,headers:{get:key=>({date:new Date(now()).toUTCString(),"content-type":first?Client.FILTERS_ACCEPT:Client.PRODUCTS_ACCEPT,"retry-after":"7200"})[key.toLowerCase()]??null},text:async()=>body};
 };
 return{calls,fetch,collect:options=>Client.fetchOffers({...options,pauseMs:0},fetch)};
}
function database(initial={}){
 const state=copy(initial);if(Object.keys(state).length&&!state.checkpointVersion)state.checkpointVersion="700";
 const db={state,articles:[],prices:[],calls:[],releases:[],connections:0,source:{leaseOwner:OWNER,leaseUntil:iso(TIME+3600000),consecutiveFailures:0,lastAttemptAt:null,nextAttemptAt:null},active:false};
 function replace(target,value){for(const key of Object.keys(target))delete target[key];Object.assign(target,copy(value));}
 async function execute(writer,sql,params=[]){
  db.calls.push({writer,sql,params:copy(params)});const current=writer===db?db.state:writer.pendingState,source=writer===db?db.source:writer.pendingSource;
  if(sql.startsWith("SELECT cursor"))return{rows:Object.keys(current).length?[copy(current)]:[]};
  if(sql.startsWith("SELECT source_name"))return{rows:[{sourceName:Client.SOURCE,...copy(source)}]};
  if(sql.includes("FROM price_source_refresh_state WHERE source_name=$1")){assert.equal(writer.pending,true);assert(sql.endsWith("FOR UPDATE"));return{rows:[copy(source)]};}
  if(sql==="SELECT txid_current()")return{rows:[{txid_current:writer.xid}]};
  if(sql.includes("txid_current_if_assigned"))return{rows:[{transactionOpen:writer.pending===true}]};
  if(sql.startsWith("SELECT pg_advisory_xact_lock"))return{rows:[]};
  if(sql.startsWith("INSERT INTO "+Refresh.TABLE)){
   assert.equal(writer.pending,true,"Every checkpoint must use an assigned transaction");
   const failure=sql.includes("(source_id,last_error"),version=params[failure?5:9];
   if(Object.keys(current).length&&(db.casMiss||version!==current.checkpointVersion))return{rows:[],rowCount:0};
   if(db.failCheckpoint)throw Error("synthetic-checkpoint-write-failed");
   if(failure){Object.assign(current,{lastError:params[1],retryAfter:new Date(params[2]).toISOString(),updatedAt:params[4],checkpointVersion:String(writer.xid)});if(params[3])Object.assign(current,{cursor:null,lastCompletedAt:null,categoriesCompleted:0});}
   else Object.assign(current,{cursor:JSON.parse(params[1]),lastCompletedAt:params[2]?params[3]:current.lastCompletedAt||null,completedCycles:(current.completedCycles||0)+(params[2]?1:0),categoryCount:params[4],categoriesCompleted:params[5],pagesFetched:params[6],receivedCumulative:params[7],assortmentHash:params[8],lastError:null,retryAfter:null,updatedAt:params[3],checkpointVersion:String(writer.xid)});
   if(db.afterCheckpoint)await db.afterCheckpoint(writer);return{rows:[],rowCount:1};
  }
  if(/CREATE|ALTER|INDEX/.test(sql)){assert.equal(writer,db,"DDL belongs before BEGIN on the pool");return{rows:[],rowCount:0};}
  throw Error("Unexpected synthetic query: "+sql);
 }
 db.query=async(sql,params)=>{assert.equal(db.active,false,"No second pool read while the sole assigned client is in use");return execute(db,sql,params);};
 db.connect=async()=>{
  assert.equal(db.active,false);db.connections++;const tx={xid:1000+db.connections,pending:false,release:error=>{db.releases.push(error||null);db.active=false;},query:async(sql,params)=>{
   if(sql==="BEGIN"){assert.equal(tx.pending,false);tx.pending=true;db.active=true;tx.pendingState=copy(db.state);tx.pendingSource=copy(db.source);tx.articles=copy(db.articles);tx.prices=copy(db.prices);db.calls.push({writer:tx,sql});return{rows:[]};}
   if(sql==="COMMIT"){db.calls.push({writer:tx,sql});if(db.failCommit)throw Error("synthetic-commit-failed");replace(db.state,tx.pendingState);replace(db.source,tx.pendingSource);db.articles=copy(tx.articles);db.prices=copy(tx.prices);tx.pending=false;return{rows:[]};}
   if(sql==="ROLLBACK"){db.calls.push({writer:tx,sql});if(db.failRollback)throw Object.assign(Error("synthetic-rollback-failed"),{code:"synthetic-broken-transaction"});tx.pending=false;return{rows:[]};}
   return execute(tx,sql,params);
  }};return tx;
 };
 return db;
}
function dependencies(db,source=transport(),changes={}){
 const articleService={ensure:async pool=>{assert.strictEqual(pool,db);assert.equal(db.active,false);},persist:async(tx,pages,options)=>{
  assert.equal(tx.pending,true);assert.equal(db.active,true);let received=0;const products=[];
  for(const page of pages){const parsed=Client.reparseOriginalPage(page,options);received+=parsed.received;products.push(...parsed.products);}
  tx.articles.push(...copy(products));if(changes.articleHook)await changes.articleHook(tx);
  return{received,accepted:new Set(products.map(p=>p.retailerSku)).size,retimedReplays:0,sourceId:Client.ARTICLE_SOURCE,truthEligible:false};
 }};
 return{fetchOffers:source.collect,articleService,suppressHeldPrices:async tx=>{assert.equal(tx.pending,true);return{suppressed:0,retailerSkus:[]};},persist:async(tx,offers,options)=>{assert.equal(tx.pending,true);assert.equal(options.schemaEnsured,true);assert.equal(options.includeAcceptedSkus,true);tx.prices.push(...copy(offers));if(changes.priceHook)await changes.priceHook(tx);return{received:offers.length,accepted:offers.length,acceptedRetailerSkus:offers.map(offer=>offer.retailerSku)};},...changes};
}
const execute=(db,deps,options={})=>Refresh.refresh({pool:db,now:()=>TIME,leaseOwner:OWNER,...options},deps);
let groups=0;async function check(label,fn){try{await fn();groups++;}catch(error){error.message=label+": "+error.message;throw error;}}
async function main(){
 await check("assigned client commits native identities prices and cursor together",async()=>{const db=database(),source=transport(),r=await execute(db,dependencies(db,source));assert.equal(source.calls.length,2);assert.equal(r.requests,2);assert.equal(r.identityReceived,40);assert.equal(r.identityAccepted,1);assert.equal(db.articles.length,40);assert.equal(db.prices.length,1);assert.equal(db.state.cursor.pageNumber,2);assert.equal(db.state.cursor.received,40);assert.equal(r.catalog.publishedAssortmentComplete,false);assert.equal(r.catalog.physicalStoreAssortmentVerified,false);assert.equal(r.scope.channel,"pickup");assert.equal(r.nextAttemptAt,iso(TIME+60000));const cp=db.calls.find(c=>c.sql.startsWith("INSERT INTO "+Refresh.TABLE));assert.equal(cp.writer,db.calls.find(c=>c.sql==="BEGIN").writer);assert(cp.sql.includes(".xmin::text=$10"));assert.equal(db.connections,1);assert(!db.calls.some(c=>/price_observations|UPDATE products|INSERT INTO stores/.test(c.sql)));});
 await check("price-less fixed article records identities without fake prices",async()=>{const db=database(),raw=item();delete raw.pricing.currentRetailPrice;const source=transport({nativeFilters:filters([category("3684","kaese-eier-molkerei",1)]),pages:()=>productPage([raw])}),r=await execute(db,dependencies(db,source));assert.equal(r.accepted,0);assert.equal(r.identityAccepted,1);assert.equal(db.articles.length,1);assert.equal(db.prices.length,0);assert.equal(r.catalog.publishedAssortmentComplete,true);assert.equal(r.catalog.physicalStoreAssortmentVerified,false);assert.equal(db.state.completedCycles,1);});
 await check("genuine empty category checkpoints without inventing native identities",async()=>{const db=database(),source=transport({nativeFilters:filters([category("3684","kaese-eier-molkerei",0)]),pages:()=>productPage([],1,0)}),r=await execute(db,dependencies(db,source));assert.equal(r.identityReceived,0);assert.equal(r.identityAccepted,0);assert.equal(r.accepted,0);assert.equal(db.state.cursor,null);assert.equal((await Refresh.status(db)).physicalStoreAssortmentVerified,false);});
 for(const patch of [{hasVariants:"true"},{hasDiverseVariantPrices:1}])await check("unresolved native identity cannot use legacy price eligibility "+JSON.stringify(patch),async()=>{const db=database(),row=item(patch),source=transport({nativeFilters:filters([category("3684","kaese-eier-molkerei",1)]),pages:()=>productPage([row])}),raw=await source.collect({now:()=>iso(TIME)});assert.equal(raw.offers.length,1,"Regression specifically exercises unchanged legacy price eligibility");assert.equal(raw.products.length,0);db.prices.push({retailerSku:row.listingId,old:true});const deps=dependencies(db,source);let observedSKUs;deps.suppressHeldPrices=async(tx,{identityRejectedSKUs})=>{observedSKUs=identityRejectedSKUs;const deleted=tx.prices.filter(p=>identityRejectedSKUs.includes(p.retailerSku)).map(p=>p.retailerSku);tx.prices=tx.prices.filter(p=>!identityRejectedSKUs.includes(p.retailerSku));return{suppressed:deleted.length,retailerSkus:deleted};};const r=await execute(db,deps);assert.equal(r.identityAccepted,0);assert.equal(r.accepted,0);assert.equal(r.identityRejectedPrices,1);assert.equal(r.suppressedHeldPrices,1);assert.deepEqual(observedSKUs,[row.listingId]);assert.equal(db.articles.length,0);assert.equal(db.prices.length,0);assert.equal(db.state.pagesFetched,1);});
 await check("valid earlier identity cannot authorize same SKU from a different rejected original page",async()=>{const db=database(),source=transport({nativeFilters:filters([category("3684","kaese-eier-molkerei",1),category("999","kaffee-tee-kakao",1)]),pages:({slug})=>productPage([item(slug==="kaffee-tee-kakao"?{hasVariants:"true"}:{})],1,1,slug)}),raw=await source.collect({now:()=>iso(TIME),maxRequests:3});assert.equal(raw.products.length,1);assert.equal(raw.offers.length,1);assert.notEqual(raw.products[0].sourceResponseHash,raw.offers[0].sourceResponseHash);const r=await execute(db,dependencies(db,source),{maxRequests:3});assert.equal(r.identityAccepted,1);assert.equal(r.accepted,0);assert.equal(r.identityRejectedPrices,1);assert.equal(db.prices.length,0);assert.equal(db.articles.length,1);assert.equal(db.articles[0].truthEligible,false);});
 await check("rejected foreign or missing native SKU cannot target historical price deletion",async()=>{const bad=item({listingId:"8-SYNTHETIC1-00000000-0000-0000-0000-000000000000"}),db=database(),source=transport({nativeFilters:filters([category("3684","kaese-eier-molkerei",2)]),pages:()=>productPage([item(),bad])}),deps=dependencies(db,source);deps.suppressHeldPrices=async(tx,{identityRejectedSKUs})=>{assert.deepEqual(identityRejectedSKUs,[]);return{suppressed:0,retailerSkus:[]};};const r=await execute(db,deps);assert.equal(r.identityAccepted,1);assert.equal(r.accepted,1);assert.equal(db.prices.length,1);});
 await check("raw duplicate native products retained but native prices deduplicated",async()=>{const db=database(),source=transport(),r=await execute(db,dependencies(db,source),{maxRequests:3});assert.equal(r.identityReceived,41);assert.equal(db.articles.length,41);assert.equal(db.prices.length,1);assert.equal(r.catalog.publishedAssortmentComplete,true);assert.equal(r.requests,3);});
 await check("native progression above six thousand retains legacy cursor",async()=>{const source=transport(),listing=Client.parseCategories(filters()),cursor={...Client.cursorState(null,listing),categoryIndex:0,pageNumber:1,received:8000,pagesFetched:200},db=database({cursor});const r=await execute(db,dependencies(db,source));assert.equal(r.catalog.receivedCumulative,8040);assert.equal(r.catalog.pagesFetched,201);assert.equal(db.state.cursor.pageNumber,2);});
 await check("JSONB key ordering and PostgreSQL Date milliseconds do not break CAS",async()=>{const listing=Client.parseCategories(filters()),cursor=Client.cursorState(null,listing),reordered=Object.fromEntries(Object.entries(cursor).reverse()),db=database({cursor:reordered,updatedAt:new Date(TIME-123),checkpointVersion:"8192"}),r=await execute(db,dependencies(db));assert.equal(r.identityReceived,40);assert.equal(db.calls.find(c=>c.sql.startsWith("INSERT INTO "+Refresh.TABLE)).params[9],"8192");assert.equal(Refresh.checkpointKey({cursor,updatedAt:new Date(TIME)}),Refresh.checkpointKey({cursor:reordered,updatedAt:iso(TIME)}));});
 await check("private checkpoint version is never public status metadata",async()=>{const db=database({checkpointVersion:"98765"}),r=await Refresh.status(db);assert(!Object.hasOwn(r,"checkpointVersion"));assert.equal((await Refresh.load(db)).checkpointVersion,"98765");});
 for(const place of ["article","price","checkpoint","commit"])await check(place+" failure rolls back identities prices and checkpoint",async()=>{const db=database(),source=transport(),deps=dependencies(db,source,{articleHook:place==="article"?async()=>{throw Error("synthetic-article-failed");}:undefined,priceHook:place==="price"?async()=>{throw Error("synthetic-price-failed");}:undefined});db.failCheckpoint=place==="checkpoint";db.failCommit=place==="commit";await assert.rejects(()=>execute(db,deps),/synthetic-.*failed/);assert.deepEqual(db.state,{});assert.deepEqual(db.articles,[]);assert.deepEqual(db.prices,[]);assert(db.calls.some(c=>c.sql==="ROLLBACK"));assert.equal(db.releases.length,1);});
 await check("failed rollback evicts assigned client and retains primary failure",async()=>{const db=database();db.failRollback=true;await assert.rejects(()=>execute(db,dependencies(db,transport(),{priceHook:async()=>{throw Error("synthetic-primary-write-failed");}})),e=>e.message==="synthetic-primary-write-failed"&&e.rollbackErrorCode==="synthetic-broken-transaction");assert.equal(db.releases[0].code,"synthetic-broken-transaction");assert.deepEqual(db.state,{});});
 await check("retimed original replay aborts price write and checkpoint",async()=>{const db=database();let prices=0;const deps=dependencies(db);deps.persistArticles=async(tx)=>{tx.articles.push({fake:true});return{received:40,accepted:0,retimedReplays:1};};deps.persist=async()=>{prices++;return{accepted:1};};await assert.rejects(()=>execute(db,deps),/capture-replay-retimed/);assert.equal(prices,0);assert.deepEqual(db.articles,[]);assert.deepEqual(db.state,{});});
 await check("historical A to B to retimed A capture rolls back despite no latest-row replay",async()=>{const db=database();db.articles.push({historical:"B"});db.prices.push({historical:"B"});const priorArticles=copy(db.articles),priorPrices=copy(db.prices),deps=dependencies(db);let priceWrites=0;deps.persistArticles=async(tx)=>{tx.articles.push({retimed:"A"});return{received:40,accepted:0,retimedReplays:0,retimedCaptures:1};};deps.persist=async()=>{priceWrites++;return{accepted:0,acceptedRetailerSkus:[]};};await assert.rejects(()=>execute(db,deps),/capture-replay-retimed/);assert.equal(priceWrites,0);assert.deepEqual(db.articles,priorArticles);assert.deepEqual(db.prices,priorPrices);assert.deepEqual(db.state,{});});
 await check("held incoming prices are suppressed in the same transaction without private SKU echo",async()=>{const db=database(),deps=dependencies(db);deps.suppressHeldPrices=async tx=>{const retailerSkus=tx.prices.map(p=>p.retailerSku);tx.prices=[];return{suppressed:retailerSkus.length,retailerSkus};};const r=await execute(db,deps);assert.equal(r.accepted,0);assert.equal(r.suppressedHeldPrices,1);assert.equal(db.prices.length,0);assert.equal(db.articles.length,40);assert.equal(db.state.pagesFetched,1);assert(!Object.hasOwn(r,"acceptedRetailerSkus"));assert(!Object.hasOwn(r,"retailerSkus"));});
 await check("suppressing an older held SKU does not subtract unrelated incoming acceptance",async()=>{const db=database(),oldSku="9-SYNTHETICOLD-"+Client.NATIVE_STORE_ID;db.prices.push({retailerSku:oldSku});const deps=dependencies(db);deps.suppressHeldPrices=async tx=>{tx.prices=tx.prices.filter(p=>p.retailerSku!==oldSku);return{suppressed:1,retailerSkus:[oldSku]};};const r=await execute(db,deps);assert.equal(r.accepted,1);assert.equal(r.suppressedHeldPrices,1);assert.equal(db.prices.length,1);});
 await check("held price suppression failure rolls back every prior write",async()=>{const db=database(),deps=dependencies(db);deps.suppressHeldPrices=async()=>{throw Error("synthetic-suppression-write-failed");};await assert.rejects(()=>execute(db,deps),/suppression-write-failed/);assert.equal(db.articles.length,0);assert.equal(db.prices.length,0);assert.deepEqual(db.state,{});});
 for(const suppression of [{suppressed:1,retailerSkus:[]},{suppressed:2,retailerSkus:[item().listingId,item().listingId]},{suppressed:1,retailerSkus:["foreign-market-sku"]}])await check("unconfirmed held-price suppression aborts checkpoint",async()=>{const db=database(),deps=dependencies(db);deps.suppressHeldPrices=async()=>suppression;await assert.rejects(()=>execute(db,deps),/held-price-suppression-unconfirmed/);assert.equal(db.prices.length,0);assert.deepEqual(db.state,{});});
 for(const result of [{accepted:1,acceptedRetailerSkus:[]},{accepted:1,acceptedRetailerSkus:["foreign"]},{accepted:2,acceptedRetailerSkus:[item().listingId,item().listingId]}])await check("unconfirmed accepted-price identity cannot inflate reporting",async()=>{const db=database(),deps=dependencies(db);deps.persist=async tx=>{tx.prices.push({fake:true});return result;};await assert.rejects(()=>execute(db,deps),/native-price-result-unconfirmed/);assert.equal(db.prices.length,0);assert.deepEqual(db.state,{});});
 await check("foreign checkpoint changed during collection is never overwritten",async()=>{const db=database(),source=transport({onRequest:n=>{if(n===2)Object.assign(db.state,{cursor:null,lastError:"foreign-checkpoint",checkpointVersion:"9000"});}}),r=await execute(db,dependencies(db,source));assert.equal(r.skipped,"checkpoint-changed");assert.equal(r.requests,2);assert.equal(db.state.lastError,"foreign-checkpoint");assert.equal(db.articles.length,0);assert.equal(db.prices.length,0);});
 await check("checkpoint compare-and-swap miss rolls all prior writes back",async()=>{const db=database({cursor:Client.cursorState(null,Client.parseCategories(filters()))});db.casMiss=true;const initial=copy(db.state),r=await execute(db,dependencies(db));assert.equal(r.skipped,"checkpoint-changed");assert.equal(r.requests,2);assert.deepEqual(db.state,initial);assert.deepEqual(db.articles,[]);assert.deepEqual(db.prices,[]);});
 for(const phase of ["before-write","after-checkpoint"])await check(phase+" lease loss cannot commit",async()=>{const db=database(),deps=dependencies(db);if(phase==="before-write"){deps.fetchOffers=async o=>{const r=await transport().collect(o);db.source.leaseOwner="foreign-owner";return r;};}else db.afterCheckpoint=tx=>{tx.pendingSource.leaseOwner="foreign-owner";};const r=await execute(db,deps);assert.equal(r.skipped,"source-lease-not-owned");assert.equal(r.requests,2);assert.deepEqual(db.state,{});assert.equal(db.articles.length,0);assert.equal(db.prices.length,0);});
 await check("final lifecycle gate after checkpoint rolls back committed-looking counts",async()=>{const db=database();let proceed=true;db.afterCheckpoint=()=>{proceed=false;};const r=await execute(db,dependencies(db,transport(),{shouldContinue:async()=>proceed}));assert.equal(r.skipped,"server-stopping");assert.equal(r.requests,2);assert.equal(r.accepted,0);assert.deepEqual(db.state,{});assert.equal(db.articles.length,0);});
 await check("late original expiry after checkpoint never commits earlier fresh results",async()=>{const db=database();let now=TIME;db.afterCheckpoint=()=>{now=TIME+300001;};await assert.rejects(()=>execute(db,dependencies(db),{now:()=>now}),/live-capture-invalid/);assert.deepEqual(db.state,{});assert.equal(db.articles.length,0);assert.equal(db.prices.length,0);});
 for(const patch of [{leaseOwner:"foreign"},{leaseUntil:iso(TIME)},{leaseUntil:null},{consecutiveFailures:4,lastAttemptAt:iso(TIME-60000)},{consecutiveFailures:1,lastAttemptAt:iso(TIME-60000),nextAttemptAt:iso(TIME+7200000)}])await check("persisted lease or backoff gate "+JSON.stringify(patch),async()=>{const db=database();Object.assign(db.source,patch);const source=transport(),r=await execute(db,dependencies(db,source));assert.equal(source.calls.length,0);assert.equal(r.accepted,0);assert.equal(db.connections,0);assert.deepEqual(db.state,{});});
 await check("nextAttemptAt of successful source cannot fabricate failure cooldown",async()=>{const db=database();db.source.nextAttemptAt=iso(TIME+86400000);const r=await execute(db,dependencies(db));assert.equal(r.requests,2);assert.equal(db.articles.length,40);});
 await check("catalog native retry dominates source eligible status",async()=>{const db=database({retryAfter:iso(TIME+86400000),lastError:"rewe-source-http-429"}),source=transport(),r=await execute(db,dependencies(db,source));assert.equal(r.skipped,"source-cooldown");assert.equal(r.nextAttemptAt,iso(TIME+86400000));assert.equal(source.calls.length,0);assert.equal(await Refresh.resumeAt(db,TIME),iso(TIME+86400000));});
 await check("gate before each GET prevents page request after filter-time lease loss",async()=>{const db=database(),source=transport({onRequest:n=>{if(n===1)db.source.leaseOwner="foreign";}}),r=await execute(db,dependencies(db,source));assert.equal(source.calls.length,1);assert.equal(r.skipped,"source-lease-not-owned");assert.equal(r.requests,1);assert.equal(db.connections,0);assert.deepEqual(db.state,{});});
 for(const status of [403,429])await check("HTTP"+status+" all-or-nothing failure persists exact stage and native cooldown",async()=>{const db=database(),source=transport({status});let error;try{await execute(db,dependencies(db,source));}catch(e){error=e;}assert(error);assert.equal(error.status,status);assert.equal(error.failureCheckpointPersisted,true);assert.equal(error.nextAttemptAt,iso(TIME+7200000));assert.equal(db.articles.length,0);assert.equal(db.prices.length,0);assert.equal(db.state.cursor,undefined);const observed=await Refresh.status(db);assert.equal(observed.lastError,"rewe-source-http-"+status);assert.equal(observed.lastFailureRequest.requestStage,"products");assert.equal(observed.lastFailureRequest.requestOrdinal,2);assert.equal(observed.lastFailureRequest.requests,2);assert.equal(observed.lastFailureRequest.status,status);assert.equal(observed.retryAfter,iso(TIME+7200000));});
 await check("filters failure reports first attempted GET and no product original",async()=>{const db=database(),source=transport({status:()=>403});await assert.rejects(()=>execute(db,dependencies(db,source)),e=>e.failureCheckpointPersisted===true);const r=await Refresh.status(db);assert.equal(r.lastFailureRequest.requestStage,"filters");assert.equal(r.lastFailureRequest.requestOrdinal,1);assert.equal(r.lastFailureRequest.totalBytes,0);assert.equal(r.lastFailureRequest.sourceResponseUrl,filtersUrl);});
 await check("HTTP failure checkpoint uses failure clock instead of stale run start",async()=>{const db=database();let now=TIME;const deps=dependencies(db);deps.fetchOffers=async()=>{now+=20000;throw Object.assign(Error("rewe-source-http-403"),{code:"rewe-source-http-403"});};await assert.rejects(()=>execute(db,deps,{now:()=>now}),e=>e.nextAttemptAt===iso(TIME+20000+3600000));assert.equal(db.state.updatedAt,iso(TIME+20000));});
 await check("huge genuine retry duration is bounded without losing the durable failure pause",async()=>{const db=database(),deps=dependencies(db);deps.fetchOffers=async()=>{throw Object.assign(Error("rewe-source-http-429"),{code:"rewe-source-http-429",retryAfterMs:1e30});};await assert.rejects(()=>execute(db,deps),e=>e.failureCheckpointPersisted===true&&e.nextAttemptAt===iso(8640000000000000));const call=db.calls.find(c=>c.sql.startsWith("INSERT INTO "+Refresh.TABLE));assert(call.params[2] instanceof Date);assert.equal((await Refresh.status(db)).retryAfter,iso(8640000000000000));});
 await check("failure CAS cannot overwrite concurrent cursor or forge persisted status",async()=>{const db=database(),deps=dependencies(db);deps.fetchOffers=async()=>{Object.assign(db.state,{lastError:"foreign",checkpointVersion:"9000"});throw Object.assign(Error("rewe-source-http-403"),{code:"rewe-source-http-403"});};await assert.rejects(()=>execute(db,deps),e=>e.failureCheckpointPersisted===false);assert.equal(db.state.lastError,"foreign");assert.equal(db.state.retryAfter,undefined);});
 await check("failure persistence error leaves frontier unchanged and reports no saved hold",async()=>{const db=database(),source=transport({status:403});db.failCheckpoint=true;await assert.rejects(()=>execute(db,dependencies(db,source)),e=>e.failureCheckpointPersisted===false&&e.failurePersistenceErrorCode==="rewe-failure-checkpoint-failed");assert.deepEqual(db.state,{});});
 for(const mutate of [r=>r.products=[],r=>r.products[0].name="Forged",r=>r.offers[0].price=0.01,r=>r.categoryCount++,r=>r.pagesThisBatch++,r=>r.requests++,r=>r.originalPages[0].category.name="Borrowed header",r=>r.originalPages[0].meta.sourceResponseHash="f".repeat(64),r=>r.nextCursor.pageNumber++,r=>r.receivedCumulative++,r=>r.originalFilters.body+=" "])await check("unconfirmed result or native original fails before any writes",async()=>{const db=database(),deps=dependencies(db);deps.fetchOffers=async o=>{const r=await transport().collect(o);mutate(r);return r;};await assert.rejects(()=>execute(db,deps),/original|progress|body/);assert.equal(db.articles.length,0);assert.equal(db.prices.length,0);assert.equal(db.state.cursor,undefined);});
 await check("diagnostic envelope rejects tampered JSON without private content exposure",()=>{for(const raw of [JSON.stringify({v:1,code:"rewe-source-http-403-TAMPER",request:null,rawBody:"PRIVATE_SECRET"}),JSON.stringify({v:1,request:{token:"PRIVATE_SECRET"}}),"[\"PRIVATE_SECRET\"]"," {bad PRIVATE_SECRET}"]){const r=Refresh.publicFailure(raw);assert.equal(r.lastError,"rewe-refresh-diagnostic-invalid");assert.equal(r.lastFailureRequest,null);assert(!JSON.stringify(r).includes("PRIVATE_SECRET"));}});
 await check("unknown network error text is not copied into the durable public diagnostic",async()=>{const db=database(),deps=dependencies(db);deps.fetchOffers=async()=>{throw Object.assign(Error("PRIVATE_BODY_TOKEN"),{requestStage:"filters",requestOrdinal:1,status:403,requests:1,totalBytes:0,sourceResponseUrl:filtersUrl});};await assert.rejects(()=>execute(db,deps),/PRIVATE_BODY_TOKEN/);const r=await Refresh.status(db);assert.equal(r.lastError,"rewe-refresh-failed");assert.equal(r.lastFailureRequest.requestStage,"filters");assert(!JSON.stringify(db.state).includes("PRIVATE_BODY_TOKEN"));assert.equal(Refresh.publicFailure("PRIVATE_BODY_TOKEN").lastError,"rewe-refresh-diagnostic-invalid");});
 await check("diagnostic witness accepts only actual allowed stage URL counts",()=>{const good={requestStage:"filters",requestOrdinal:1,status:403,requests:1,totalBytes:0,sourceResponseUrl:filtersUrl};assert.deepEqual(Refresh.requestDiagnostic(good),good);for(const patch of [{requestStage:"product"},{requestOrdinal:49},{requests:49},{totalBytes:Infinity},{sourceResponseUrl:filtersUrl+"&cookie=SECRET"},{sourceResponseUrl:filtersUrl.replace("rewe.de","evil.example")},{requestStage:"products"}])assert.equal(Refresh.requestDiagnostic({...good,...patch}),null);});
 await check("invalid transaction pool or missing lease cannot invoke source",async()=>{await assert.rejects(()=>Refresh.refresh({pool:{query:async()=>({rows:[]})},leaseOwner:OWNER}),/transaction-pool/);await assert.rejects(()=>Refresh.refresh({pool:database()}),/lease-owner/);const db=database();db.release=()=>{};await assert.rejects(()=>Refresh.refresh({pool:db,leaseOwner:OWNER}),/transaction-pool/);});
 await check("per-call budget bounded and shared running guard leaves other state alone",async()=>{const db=database();let started,resolve;const ready=new Promise(r=>{started=r;}),deps=dependencies(db);deps.fetchOffers=async o=>{assert.equal(o.maxRequests,48);started();return new Promise(r=>{resolve=async()=>r(await transport().collect({...o,maxRequests:2}));});};const pending=execute(db,deps,{maxRequests:999});await ready;const other=database(),r=await execute(other,dependencies(other));assert.equal(r.skipped,"already-running");assert.equal(other.connections,0);await resolve();await pending;});
 console.log("rewe-native-article-refresh: "+groups+" groups verified; synthetic originals/fake transaction only, no source or database requests");
}
module.exports={TIME,OWNER,copy,iso,category,filters,item,productPage,transport,database,dependencies,execute};
if(require.main===module)main().catch(error=>{console.error(error);process.exitCode=1;});
