"use strict";
const assert=require("assert/strict"),{Pool}=require("pg"),Service=require("../rewe-retailer-price-service"),Dm=require("../published-price-service"),Wolt=require("../wolt-retailer-price-service"),Inventory=require("../published-retailer-inventory"),Refresh=require("../rewe-retailer-price-refresh");
function gtin(index){const body=String(960000000000+index),sum=[...body].reduce((total,digit,position)=>total+Number(digit)*(position%2?3:1),0);return body+(10-sum%10)%10;}
async function main(){
 const connectionString=process.env.DATABASE_URL;assert(connectionString,"DATABASE_URL is required");const database=new URL(connectionString);assert.equal(database.hostname,"localhost");assert(database.pathname.endsWith("_test"),"Only a dedicated local test database is allowed");
 const pool=new Pool({connectionString,ssl:false,connectionTimeoutMillis:5000}),now=Date.now(),market=Service.MARKET;let api;
 const fixture=(index,patch={})=>({sourceId:Service.SOURCE,merchant:"REWE",nativeMarketId:market.nativeMarketId,nativeStoreId:market.nativeStoreId,retailerSku:"8-PGTEST"+index+"-"+market.nativeStoreId,retailerProductId:String(9000000+index),nativeArticleId:"PGTEST"+index,gtin:gtin(index),name:"POSTGRES TEST Berlin pickup product "+index,brand:"POSTGRES TEST",pack:"1 l",packAmount:1,packUnit:"l",packCount:1,price:1.29,deposit:.25,displayedPrice:1.29,nativePriceEUR:1.29,nativePriceIncludesDeposit:false,payablePackPrice:1.54,depositIncludedInDisplayedPrice:false,currency:"EUR",priceType:"unknown",promotionStatus:"unknown",availability:"unknown",capturedAt:new Date(now-1000).toISOString(),proofHash:"c".repeat(64),sourceResponseHash:"c".repeat(64),sourceUrl:"https://www.rewe.de/shop/p/postgres-test-product/"+(9000000+index),sourceResponseUrl:"https://www.rewe.de/shop/api/products?marketId=8321066&serviceTypes=PICKUP&page=1&objectsPerPage=40",shop:{...market},scopeCountry:"DE",scopeChannel:"pickup",serviceType:"PICKUP",...patch});
 try{
  const exists=async table=>!!(await pool.query("SELECT to_regclass($1) AS name",["public."+table])).rows[0].name;
  const baseline={};for(const table of["products","stores","price_observations","receipts","retailer_published_prices","wolt_retailer_published_prices"]){baseline[table]=await exists(table)?(await pool.query("SELECT count(*)::int AS count FROM "+table)).rows[0].count:null;}
  const fixtures=Array.from({length:501},(_,index)=>fixture(index)),saved=await Service.persist(pool,fixtures,{now});assert.equal(saved.accepted,501);assert.equal(saved.rejected,0);assert.equal(saved.upserted,501);
  assert.equal((await Service.search(pool,{...{gtin:gtin(0),now,limit:1},pack:"1 l"})).items.length,1,"Real SQL selects an equivalent normalized single pack before its cap");
  assert.equal((await Service.search(pool,{...{gtin:gtin(0),now,limit:1},pack:"2 x 500 ml"})).items.length,0,"Equal total volume must not admit a different sales pack");
  assert.equal((await Service.search(pool,{...{gtin:gtin(0),now,limit:1},pack:"500 ml"})).items.length,0);
  const stored=(await pool.query("SELECT count(*)::int AS total,count(*) FILTER(WHERE scope_country='DE' AND scope_channel='pickup' AND currency='EUR' AND pack_amount=1000 AND pack_unit='ml' AND pack_count=1 AND price=1.29 AND deposit=.25 AND displayed_price=1.29)::int AS exact FROM rewe_retailer_published_prices WHERE retailer_sku=ANY($1::text[])",[fixtures.map(row=>row.retailerSku)])).rows[0];assert.equal(stored.total,501);assert.equal(stored.exact,501);
  assert.equal((await Service.persist(pool,fixtures,{now})).unchanged,501);
  assert.equal((await Service.persist(pool,[fixture(0,{price:1.59,displayedPrice:1.59,nativePriceEUR:1.59,payablePackPrice:1.84})],{now})).rejected,1);
  const changed=fixture(0,{price:1.39,displayedPrice:1.39,nativePriceEUR:1.39,payablePackPrice:1.64,capturedAt:new Date(now).toISOString(),proofHash:"d".repeat(64),sourceResponseHash:"d".repeat(64),availability:"available"});assert.equal((await Service.persist(pool,[changed],{now})).upserted,1);assert.equal((await Service.persist(pool,[fixture(0)],{now})).unchanged,1);
  let selected=(await Service.search(pool,{merchant:"rewe",gtin:gtin(0),nativeMarketId:market.nativeMarketId,now})).items;assert.equal(selected.length,1);assert.equal(selected[0].price,1.39);assert.equal(selected[0].deposit,.25);assert.equal(selected[0].displayedPrice,1.39);assert.equal(selected[0].payablePackPrice,1.64);assert.equal(selected[0].nativePriceIncludesDeposit,false);assert.equal(selected[0].availability,"available");assert.equal(selected[0].scopeChannel,"pickup");assert.equal(selected[0].fulfillmentChannel,"pickup");assert.equal(selected[0].truthEligible,false);assert.equal(selected[0].shippingIncluded,false);assert.equal(selected[0].serviceFeesIncluded,false);assert(!("storeId"in selected[0]));assert(!("canonicalProductId"in selected[0]));assert(!("productId"in selected[0]));
  assert.equal((await Service.search(pool,{merchant:"EDEKA",gtin:gtin(0),now})).items.length,0);assert.equal((await Service.search(pool,{nativeMarketId:"999",now})).items.length,0);assert.equal((await Service.search(pool,{search:"product 500",now})).items.length,1);assert.equal((await Service.search(pool,{search:"product%_",now})).items.length,0);assert.equal((await Service.search(pool,{limit:999,now})).items.length,200);
  assert.equal((await Service.search(pool,{today:new Date(now-Service.DAY_MS).toISOString().slice(0,10),now})).items.length,0,"Fresh snapshots do not answer historical requests");
  const expired=fixture(501,{capturedAt:new Date(now-Service.DAY_MS-1).toISOString()});assert.equal((await Service.persist(pool,[expired],{now})).upserted,1);assert.equal((await Service.search(pool,{gtin:expired.gtin,now})).items.length,0);
  const noGtin=fixture(502,{gtin:null,deposit:null,depositIncludedInDisplayedPrice:null,payablePackPrice:null});assert.equal((await Service.persist(pool,[noGtin],{now})).upserted,1);selected=(await Service.search(pool,{search:"product 502",now})).items;assert.equal(selected.length,1);assert.equal(selected[0].gtin,null);assert.equal(selected[0].identityStatus,"native-retailer-sku");assert.equal(selected[0].payablePackPrice,null);assert.equal(selected[0].depositIncludedInDisplayedPrice,null);
  const conflictA=fixture(503),conflictB=fixture(503,{price:1.39,displayedPrice:1.39,nativePriceEUR:1.39,payablePackPrice:1.64}),rejected=await Service.persist(pool,[conflictA,conflictB],{now});assert.equal(rejected.accepted,0);assert.equal(rejected.rejected,2);assert.equal((await Service.search(pool,{gtin:gtin(503),now})).items.length,0);
  const invalid=await Service.persist(pool,[fixture(504,{gtin:"invalid"}),fixture(505,{scopeChannel:"store",storeId:"imaginary"}),fixture(506,{nativeMarketId:"999"}),fixture(507,{displayedPrice:1.54,nativePriceEUR:1.54}),fixture(508,{capturedAt:new Date(now+1).toISOString()}),fixture(509,{personalizedPrice:true})],{now});assert.equal(invalid.accepted,0);assert.equal(invalid.rejected,6);
  // At-rest constraints enforce REWE's deposit-excluded goods amount and native market scope.
  await assert.rejects(()=>pool.query("UPDATE rewe_retailer_published_prices SET displayed_price=price+COALESCE(deposit,0) WHERE retailer_sku=$1",[fixtures[1].retailerSku]),error=>error.code==="23514");
  await assert.rejects(()=>pool.query("UPDATE rewe_retailer_published_prices SET native_market_id='999' WHERE retailer_sku=$1",[fixtures[1].retailerSku]),error=>error.code==="23514");
  await assert.rejects(()=>pool.query("UPDATE rewe_retailer_published_prices SET price_type='promotion',original_price=NULL WHERE retailer_sku=$1",[fixtures[1].retailerSku]),error=>error.code==="23514");
  await assert.rejects(()=>pool.query("UPDATE rewe_retailer_published_prices SET shop='{}'::jsonb WHERE retailer_sku=$1",[fixtures[1].retailerSku]),error=>error.code==="23514");
  const status=await Service.status(pool,{now});assert.equal(status.storedPrices,503);assert.equal(status.currentPrices,502);assert.equal(status.productsWithCurrentPublishedPrices,501);assert.equal(status.marketsWithCurrentPublishedPrices,1);assert.equal(status.availableCurrentPrices,1);assert.equal(status.markets[0].currentPrices,502);assert.equal(status.scopeChannel,"pickup");assert.equal(status.truthEligible,false);assert.equal(status.independentOfUserReceipts,true);
  const union=Service.gtinQuerySpec({now}),gtins=await pool.query(union.sql,union.params);assert.equal(gtins.rows.length,501);
  // Upgrade the previous table shape without deleting existing prices or relaxing article identity.
  const migration=await pool.connect();
  try{
   await migration.query("BEGIN");await migration.query("ALTER TABLE rewe_retailer_published_prices DROP CONSTRAINT rewe_retailer_published_expiry_scope");
   await migration.query("ALTER TABLE rewe_retailer_published_prices RENAME CONSTRAINT rewe_retailer_published_prices_check1 TO rewe_retailer_legacy_article_guard");
   await migration.query("ALTER TABLE rewe_retailer_published_prices DROP COLUMN native_promotion_valid_to");
   await migration.query("ALTER TABLE rewe_retailer_published_prices ADD CONSTRAINT rewe_retailer_published_prices_check1 CHECK(expires_at=captured_at+interval '24 hours')");
   await Service.ensure(migration);await Service.ensure(migration);
   const upgraded=(await migration.query("SELECT count(*)::int AS total,count(*) FILTER(WHERE native_promotion_valid_to IS NULL)::int AS unchanged FROM rewe_retailer_published_prices")).rows[0];assert.equal(upgraded.total,503);assert.equal(upgraded.unchanged,503);
   assert.equal((await migration.query("SELECT count(*)::int AS count FROM pg_constraint WHERE conrelid='rewe_retailer_published_prices'::regclass AND conname='rewe_retailer_legacy_article_guard'")).rows[0].count,1,"Expiry migration preserves the unrelated article check");
  }finally{await migration.query("ROLLBACK");migration.release();}
  const deadline=new Date(now+10000).toISOString(),sale=fixture(510,{nativePromotionValidTo:deadline});assert.equal((await Service.persist(pool,[sale],{now})).upserted,1);
  selected=(await Service.search(pool,{gtin:sale.gtin,now:now+9999})).items;assert.equal(selected.length,1);assert.equal(selected[0].nativePromotionValidTo,deadline);assert.equal(selected[0].expiresAt,deadline);assert.equal(selected[0].priceType,"unknown");
  assert.equal((await Service.search(pool,{gtin:sale.gtin,now:now+10000})).items.length,0,"Native validity end excludes the price at its exact boundary");
  assert.equal((await Service.persist(pool,[sale],{now:now+10000})).rejected,1,"An already expired native price cannot be refreshed");
  await assert.rejects(()=>pool.query("UPDATE rewe_retailer_published_prices SET expires_at=captured_at+interval '24 hours' WHERE retailer_sku=$1",[sale.retailerSku]),error=>error.code==="23514");

  // Real SQL, not per-source count arithmetic: one fresh GTIN in three ledgers adds one identity.
  const composite=await pool.connect();
  try{
   await composite.query("BEGIN");
   await Dm.ensure(composite);await Wolt.ensure(composite);
   const before=await Inventory.status(composite,{now}),shared=gtin(7000);
   assert.equal((await Inventory.search(composite,{gtin:shared,now})).items.length,0,"The explicit composite TEST identity must be new");
   const rewe=fixture(7000),dm={sourceId:"dm online",merchant:"dm",retailerSku:"988888001",gtin:shared,name:"POSTGRES TEST shared composite product",brand:"POSTGRES TEST",pack:"1 l",packAmount:1,packUnit:"l",packCount:1,price:1.59,currency:"EUR",sourceUrl:"https://www.dm.de/p/d/988888001/postgres-rewe-composite-test",proofHash:"e".repeat(64),capturedAt:new Date(now-1000).toISOString(),scopeCountry:"DE",scopeChannel:"online",availability:"unknown"};
   const wolt={sourceId:Wolt.SOURCE,merchant:"EDEKA",nativeVenueId:Wolt.VENUE.nativeVenueId,retailerSku:"fa0000000000000000007000",gtin:shared,name:"POSTGRES TEST shared composite product",brand:"POSTGRES TEST",pack:"1 l",packAmount:1,packUnit:"l",packCount:1,price:1.79,deposit:.25,displayedPrice:2.04,nativePriceEUR:2.04,nativePriceIncludesDeposit:true,payablePackPrice:2.04,depositIncludedInDisplayedPrice:true,currency:"EUR",priceType:"unknown",promotionStatus:"unknown",availability:"unknown",capturedAt:new Date(now-1000).toISOString(),proofHash:"e".repeat(64),sourceResponseHash:"e".repeat(64),sourceUrl:"https://wolt.com/de/deu/berlin/venue/edeka-hilbrecht",sourceResponseUrl:"https://consumer-api.wolt.com/consumer-api/consumer-assortment/v1/venues/slug/edeka-hilbrecht/assortment/categories/slug/test-native-category",shop:{...Wolt.VENUE,address:"Ritterstr.38-40"},scopeCountry:"DE",scopeChannel:"online"};
   assert.equal((await Service.persist(composite,[rewe],{now})).upserted,1);assert.equal((await Dm.persist(composite,[dm],{now})).upserted,1);assert.equal((await Wolt.persist(composite,[wolt],{now})).upserted,1);
   const after=await Inventory.status(composite,{now});assert.equal(after.currentPrices,before.currentPrices+3);assert.equal(after.productsWithCurrentPublishedPrices,before.productsWithCurrentPublishedPrices+1,"GTIN union counts three retailers as one exact product");assert.equal(after.scopeChannel,"mixed");assert.deepEqual(after.scopeChannels,["online","pickup"]);
   const found=await Inventory.search(composite,{gtin:shared,now});assert.equal(found.items.length,3);assert.equal(found.scopeChannel,"mixed");const pickup=found.items.find(row=>row.sourceId===Service.SOURCE);assert(pickup);assert.equal(pickup.scopeChannel,"pickup");assert.equal(pickup.fulfillmentChannel,"pickup");assert.equal(pickup.nativeMarketId,market.nativeMarketId);assert.equal(pickup.truthEligible,false);assert(!("storeId"in pickup));
   const onlyPickup=await Inventory.search(composite,{merchant:"REWE",gtin:shared,now});assert.equal(onlyPickup.items.length,1);assert.equal(onlyPickup.scopeChannel,"pickup");assert.deepEqual(onlyPickup.scopeChannels,["pickup"]);
  }finally{await composite.query("ROLLBACK");composite.release();}

  // Legacy flat quote fixtures cannot stand in for native original pages or a
  // leased catalog run. Actual joint-TX success/CAS/final-gate rollback is covered
  // by rewe-native-article-postgres.test.js against its isolated PostgreSQL 18 schema.
  const checkpoint=await pool.connect();
  try{
   await checkpoint.query("BEGIN");await Refresh.ensure(checkpoint);
   const checkpointBefore=(await checkpoint.query("SELECT * FROM rewe_retailer_catalog_state ORDER BY source_id")).rows;
   const pricesBefore=(await checkpoint.query("SELECT count(*)::int AS total,md5(string_agg(row_to_json(p)::text,chr(10) ORDER BY row_to_json(p)::text)) AS hash FROM rewe_retailer_published_prices p")).rows;
   const hash="f".repeat(64),cursor={version:1,nativeMarketId:market.nativeMarketId,scopeChannel:"pickup",serviceType:"PICKUP",assortmentHash:hash,categoryIndex:0,pageNumber:2,received:1,pagesFetched:1};
   const first={offers:[fixture(8000)],rejected:[],complete:false,categoryCount:2,categoriesCompleted:0,pagesFetched:1,received:1,receivedCumulative:1,assortmentHash:hash,nextCursor:cursor,requests:2};
   let fetched=0;const fetchOffers=async()=>{fetched++;return first;};
   await assert.rejects(()=>Refresh.refresh({pool:checkpoint,now:()=>now,leaseOwner:"POSTGRES TEST unowned lease"},{fetchOffers}),/rewe-refresh-transaction-pool-required/);
   await assert.rejects(()=>Refresh.refresh({pool,now:()=>now},{fetchOffers}),/rewe-source-lease-owner-required/);
   await assert.rejects(()=>Refresh.refresh({pool,now:()=>now,leaseOwner:""},{fetchOffers}),/rewe-source-lease-owner-required/);
   assert.throws(()=>Refresh.nativeBatch(first,{},2,now),/rewe-native-original-batch-required/);
   assert.equal(fetched,0,"Structural and original-proof guards prevent a synthetic source request");
   assert.deepEqual((await checkpoint.query("SELECT * FROM rewe_retailer_catalog_state ORDER BY source_id")).rows,checkpointBefore,"Rejected legacy admission preserves the actual checkpoint");
   assert.deepEqual((await checkpoint.query("SELECT count(*)::int AS total,md5(string_agg(row_to_json(p)::text,chr(10) ORDER BY row_to_json(p)::text)) AS hash FROM rewe_retailer_published_prices p")).rows,pricesBefore,"Rejected legacy admission preserves all native price rows exactly");
  }finally{await checkpoint.query("ROLLBACK");checkpoint.release();}

  process.env.PORT="0";api=require("../server");await new Promise((resolve,reject)=>{api.server.once("error",reject);api.server.listen(0,"127.0.0.1",()=>{api.server.off("error",reject);resolve()})});const base="http://127.0.0.1:"+api.server.address().port;
  async function current(request){const response=await fetch(base+"/v1/current-prices",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(request),signal:AbortSignal.timeout(10000)}),result=await response.json();assert.equal(response.status,200,JSON.stringify(result));return result;}
  const direct=await current({gtin:gtin(0),pack:"1 l",merchants:["REWE"]}),published=direct.publishedAlternatives.find(row=>row.sourceId===Service.SOURCE);assert(published);assert.equal(published.price,1.39);assert.equal(published.scopeChannel,"pickup");assert.equal(published.fulfillmentChannel,"pickup");assert.equal(published.truthEligible,false);assert(direct.results.every(row=>row.state==="unknown"&&row.price===null),"A public pickup price must not create a physical REWE branch decision");
  const canonical=(await pool.query("SELECT id,name,brand,gtin FROM products WHERE gtin='3017620422003'")).rows[0];assert(canonical,"Run the preceding physical integration with its canonical TEST Nutella");assert(canonical.brand);
  const request={productId:canonical.id,gtin:canonical.gtin,pack:"450 g",merchants:["REWE"]},beforeCanonical=await current(request),nativeBrandAbsent=fixture(7010,{gtin:canonical.gtin,brand:null,pack:"450 g",packAmount:450,packUnit:"g",name:"POSTGRES TEST REWE Nutella 450g"});assert.equal((await Service.persist(pool,[nativeBrandAbsent],{now})).upserted,1);
  const resolved=await current(request);assert(resolved.publishedAlternatives.some(row=>row.sourceId===Service.SOURCE),"Canonical autofilled brand must not hide a native brand-absent exact GTIN and pack quote");assert.deepEqual(resolved.results,beforeCanonical.results,"Pickup quote leaves physical decisions unchanged");assert.equal((await current({...request,brand:canonical.brand})).publishedAlternatives.some(row=>row.sourceId===Service.SOURCE),false,"An explicit brand constraint still requires native brand evidence");assert.equal((await current({...request,pack:"250 g"})).publishedAlternatives.some(row=>row.sourceId===Service.SOURCE),false,"The same GTIN with a different requested pack cannot match");
  assert.equal((await Service.search(pool,{now:now+Service.DAY_MS+1})).items.length,0);
  await pool.query("UPDATE rewe_retailer_published_prices SET captured_at=$2::timestamptz,expires_at=$2::timestamptz+interval '24 hours' WHERE retailer_sku=$1",[fixtures[1].retailerSku,new Date(now+1000).toISOString()]);assert.equal((await Service.search(pool,{gtin:gtin(1),now})).items.length,0,"Future stored captures must not be current");
  for(const[table,count]of Object.entries(baseline)){if(count===null)assert.equal(await exists(table),false,"Separate REWE evidence must not create "+table);else assert.equal((await pool.query("SELECT count(*)::int AS count FROM "+table)).rows[0].count,count,"Separate REWE evidence must not mutate "+table);}
  console.log("rewe-retailer-price-postgres: 501 TEST native pickup prices, deposit separation, source validity expiry, real cross-ledger GTIN union, legacy catalog-admission guards (actual atomic checkpoints in the separate PG18 program), HTTP pickup alternatives and canonical brand handling, idempotent writes, conflict/future/expiry gates and unchanged preexisting physical/receipt/retailer records OK");
 }finally{if(api){if(api.server.listening)await new Promise((resolve,reject)=>api.server.close(error=>error?reject(error):resolve()));await api.closeDb();}await pool.end();}
}
main().catch(error=>{console.error(error);process.exitCode=1});
