"use strict";
const assert=require("node:assert/strict"),Refresh=require("../rewe-retailer-price-refresh"),Client=require("../rewe-retailer-price-client"),Runner=require("../price-refresh-runner"),Semantics=require("../source-semantics"),Sources=require("../price-sources");
const {TIME,copy,iso,category,filters,item,productPage,transport,database,dependencies,execute}=require("./rewe-native-article-refresh.test");
let groups=0;async function check(label,fn){try{await fn();groups++;}catch(error){error.message=label+": "+error.message;throw error;}}
async function main(){
 await check("approved pickup source preserves nonphysical truth policy",()=>{assert.equal(Sources.canImport(Client.SOURCE),true);assert.equal(Semantics.truthEligible({sourceId:Client.SOURCE}),false);});
 await check("actual first and resumed batches preserve cumulative progress then complete",async()=>{const db=database(),source=transport(),first=await execute(db,dependencies(db,source));assert.equal(first.catalog.publishedAssortmentComplete,false);assert.equal(first.catalog.receivedCumulative,40);assert.equal(await Refresh.resumeAt(db,TIME),iso(TIME+60000));const second=await execute(db,dependencies(db,source));assert.equal(second.catalog.publishedAssortmentComplete,true);assert.equal(second.catalog.receivedCumulative,41);assert.equal(second.nextAttemptAt,null);assert.equal(db.state.cursor,null);assert.equal(db.state.completedCycles,1);const status=await Refresh.status(db);assert.equal(status.publishedAssortmentComplete,true);assert.equal(status.scopeChannel,"pickup");assert.equal(status.physicalStoreAssortmentVerified,false);});
 await check("new partial scan cannot reuse earlier completed-cycle authority",async()=>{const db=database();await execute(db,dependencies(db),{maxRequests:3});assert.equal(db.state.completedCycles,1);await execute(db,dependencies(db));assert.equal(db.state.completedCycles,1);assert.equal((await Refresh.status(db)).publishedAssortmentComplete,false);});
 await check("native HTTP cooldown preserves cursor and runner does not fabricate freshness",async()=>{const listing=Client.parseCategories(filters()),cursor={...Client.cursorState(null,listing),pageNumber:2,received:8040,pagesFetched:201},db=database({cursor}),source=transport({status:429});await assert.rejects(()=>execute(db,dependencies(db,source)),e=>e.nextAttemptAt===iso(TIME+7200000));assert.deepEqual(db.state.cursor,cursor);const skipped=await execute(db,dependencies(db));assert.equal(skipped.skipped,"source-cooldown");assert.equal(await Refresh.resumeAt(db,TIME),iso(TIME+7200000));const oldState={lastAttemptAt:iso(TIME-900000),lastSuccessAt:iso(TIME-900000),lastReceived:40,lastAccepted:39,consecutiveFailures:2,lastError:"source-denied"},run=await Runner.runOne(Client.SOURCE,oldState,{[Client.SOURCE]:async()=>skipped},{nowMs:TIME});assert.equal(run.skipped,"source-cooldown");for(const key of Object.keys(oldState))assert.equal(run.state[key],oldState[key]);assert.equal(run.state.nextAttemptAt,iso(TIME+7200000));});
 await check("genuine changed native category snapshot clears frontier only with failure hold",async()=>{const old=Client.parseCategories(filters()),cursor=Client.cursorState(null,old),db=database({cursor,lastCompletedAt:iso(TIME-86400000),completedCycles:1}),source=transport({nativeFilters:filters([category("999","kaese-eier-molkerei",41)])});await assert.rejects(()=>execute(db,dependencies(db,source)),/continuation-cursor-conflict/);assert.equal(db.state.cursor,null);assert.equal(db.state.lastCompletedAt,null);assert.equal(db.state.completedCycles,1);assert.equal(db.state.categoriesCompleted,0);assert.equal((await Refresh.status(db)).publishedAssortmentComplete,false);assert.equal(await Refresh.resumeAt(db,TIME),iso(TIME+3600000));assert.equal(db.articles.length,0);});
 await check("native smaller category restarts without repeating nonexistent old page",async()=>{const listing=Client.parseCategories(filters()),cursor={...Client.cursorState(null,listing),pageNumber:2,received:8040,pagesFetched:201},db=database({cursor,lastCompletedAt:iso(TIME-86400000),completedCycles:1}),source=transport({pages:()=>productPage([item()],1,1)});await assert.rejects(()=>execute(db,dependencies(db,source)),/pagination-count-drift/);assert.equal(db.state.cursor,null);assert.equal(db.state.lastCompletedAt,null);assert.equal(db.state.completedCycles,1);assert.equal(db.state.retryAfter,iso(TIME+3600000));});
 const source=transport(),batch=await source.collect({now:()=>iso(TIME),maxRequests:2}),state={};
 for(const patch of [{complete:true,categoriesCompleted:0},{nextCursor:null},{nextCursor:{...batch.nextCursor,nativeMarketId:"123"}},{nextCursor:{...batch.nextCursor,scopeChannel:"online"}},{nextCursor:{...batch.nextCursor,serviceType:"DELIVERY"}},{nextCursor:{...batch.nextCursor,received:1}},{nextCursor:{...batch.nextCursor,pagesFetched:99}},{complete:true,categoriesCompleted:1,nextCursor:batch.nextCursor}])await check("closed coarse progress rejects invalid cursor "+JSON.stringify(patch),()=>assert.throws(()=>Refresh.confirmedProgress({...copy(batch),...patch},state),/progress-unconfirmed/));
 for(const patch of [{stalled:true},{pagesFetched:0},{receivedCumulative:39}])await check("closed coarse progress rejects stalled cumulative state "+JSON.stringify(patch),()=>assert.throws(()=>Refresh.confirmedProgress({...copy(batch),...patch},{cursor:{pagesFetched:0,received:40,categoryIndex:0}}),/progress-stalled|progress-unconfirmed/));
 await check("resume timing preserves loaded Date milliseconds",async()=>{const db=database({cursor:batch.nextCursor,updatedAt:new Date(TIME)});assert.equal(await Refresh.resumeAt(db,TIME),iso(TIME+60000));assert.equal(await Refresh.resumeAt(database({cursor:null,updatedAt:iso(TIME)}),TIME),null);});
 await check("database failure and retry retain original capture without retiming",async()=>{const db=database(),deps=dependencies(db,transport(),{priceHook:async()=>{throw Error("synthetic-price-failed");}});await assert.rejects(()=>execute(db,deps),/synthetic-price-failed/);assert.deepEqual(db.state,{});assert.equal(db.articles.length,0);const r=await execute(db,dependencies(db));assert.equal(r.identityReceived,40);assert.equal(db.articles[0].observedAt,iso(TIME));assert.equal(db.prices[0].capturedAt,iso(TIME));assert.equal(r.catalog.physicalStoreAssortmentVerified,false);});
 console.log("rewe-retailer-price-refresh: "+groups+" groups verified; original native pagination, legacy large frontier, completion/continuation and durable cooldown preserved");
}
main().catch(error=>{console.error(error);process.exitCode=1;});
