"use strict";
const assert=require("node:assert/strict"),crypto=require("node:crypto"),Client=require("../rewe-retailer-price-client"),fixture=require("./fixtures/retailers/rewe-berlin-pickup.json");
// All altered bodies and clock values below are synthetic original responses;
// archived native fixture identities are never declared newly observed live.
const AT=fixture.capturedAt,TIME=Date.parse(AT),copy=structuredClone,native=fixture.items[0],sha=value=>crypto.createHash("sha256").update(value).digest("hex"),categories=Client.parseCategories(fixture.filters).categories,category=categories[0];
const pageUrl=(slug=category.slug,page=1)=>Client.PRODUCTS_URL+"?categorySlug="+slug+"&marketId="+Client.MARKET_ID+"&serviceTypes=PICKUP&page="+page+"&objectsPerPage=40";
const filtersUrl=Client.FILTERS_URL+"?marketId="+Client.MARKET_ID+"&serviceTypes=PICKUP";
function page(items=[copy(native)],number=1,total=items.length){return{hits:items,pagination:{objectsPerPage:40,currentPage:number,pageCount:Math.ceil(total/40),objectCount:total},search:{marketCode:Client.MARKET_ID,serviceTypes:["PICKUP"],activeCategorySlug:category.slug}};}
function record(raw,url=pageUrl(),accept=Client.PRODUCTS_ACCEPT){const body=typeof raw==="string"?raw:JSON.stringify(raw);return{body,meta:{status:200,sourceResponseUrl:url,sourceResponseHash:sha(Buffer.from(body)),capturedAt:AT,sourceResponseDate:new Date(Math.floor(TIME/1000)*1000).toISOString(),sourceAgeSeconds:null,responseDate:new Date(TIME).toUTCString(),responseAge:null,contentType:accept,bytes:Buffer.byteLength(body)}};}
function original(raw=page()){return{...record(raw),category:copy(category),pageNumber:raw.pagination?.currentPage||1};}
const proof=()=>({...record(page()).meta,shop:Client.MARKET});
function response(raw,accept=Client.PRODUCTS_ACCEPT,{status=200,headers={},bytes,url}={}){const body=typeof raw==="string"?raw:JSON.stringify(raw),values={"content-type":accept,date:new Date(TIME).toUTCString(),...headers};return{status,url,headers:{get:key=>values[key.toLowerCase()]??null},...(bytes?{body:new ReadableStream({start(controller){controller.enqueue(bytes);controller.close();}})}:{text:async()=>body})};}
function transport({laterStatus=200,firstResponse,filtersResponse}={}){const calls=[];return{calls,fetch:async(url,options)=>{calls.push({url,options});const query=new URL(url);if(query.pathname.endsWith("/filters"))return filtersResponse||response(fixture.filters,Client.FILTERS_ACCEPT,{url});const number=Number(query.searchParams.get("page"));if(number===1)return firstResponse||response(page(Array.from({length:40},()=>copy(native)),1,41),Client.PRODUCTS_ACCEPT,{url});return response(page([copy(native)],2,41),Client.PRODUCTS_ACCEPT,{url,status:laterStatus,headers:{"retry-after":"7200"}});}};}
let groups=0;async function check(label,fn){await fn();groups++;}
async function main(){
 await check("native identity retains exact originals and excludes price authority",()=>{const item=copy(native),r=Client.parseArticles([item],proof());assert.equal(r.products.length,1);const a=r.products[0];assert.equal(a.sourceId,"REWE Berlin pickup articles");assert.equal(a.retailerSku,item.listingId);assert.equal(a.nativeArticleId,item.articleId);assert.equal(a.retailerProductId,item.productId);assert.equal(a.gtin,item.gtin);assert.equal(a.packAmount,250);assert.equal(a.packUnit,"ml");assert.equal(a.packCount,1);assert.equal(a.observedAt,AT);assert.strictEqual(a.nativeWitness,item);assert.equal(a.nativeStoreId,Client.NATIVE_STORE_ID);assert.equal(a.shop.city,"Berlin");assert.equal(a.scopeChannel,"pickup");assert.equal(a.purpose,"identity");assert.equal(a.identityScope,"retailer-sku");assert.equal(a.truthEligible,false);assert.equal(a.storeId,null);for(const key of ["price","deposit","current","availability","expiresAt","canonicalProductId"])assert(!Object.hasOwn(a,key));});
 await check("price absence/invalid amount/conditions do not fabricate or suppress identity",()=>{for(const patch of [{currentRetailPrice:undefined},{currentRetailPrice:0},{currentRetailPrice:NaN},{currentRetailPrice:-1},{currentRetailPrice:"149"},{totalRefundPrice:-1},{bulkDiscountTiers:[{minimumQuantity:3,price:100}]},{conditions:{requiresMembership:true}}]){const item={...copy(native),pricing:{...native.pricing,...patch},tags:["bulk-discounted","app-exclusive"],minOrderQuantity:2};assert.equal(Client.parseArticles([item],proof()).products.length,1);assert.equal(Client.parseItems([item],proof()).offers.length,0);}});
 await check("missing/null/empty GTIN stays genuine SKU only",()=>{for(const value of [undefined,null,""]){const item={...copy(native),gtin:value},r=Client.parseArticles([item],proof());assert.equal(r.products.length,1);assert.equal(r.products[0].gtin,null);}});
 await check("malformed existing native GTIN is never normalized away",()=>{for(const gtin of [90486647,"GTIN 90486647"," 90486647 ","90486647\n","0000000000001",[],false]){const r=Client.parseArticles([{...copy(native),gtin}],proof());assert.equal(r.products.length,0);assert(r.identityRejected[0].reasons.includes("rewe-native-article-invalid-gtin"));}});
 await check("listing prefix13 is preserved, no synthesized native identity",()=>{const a=Client.parseArticles([copy(fixture.prefix13Item)],proof()).products[0];assert(a);assert.equal(a.retailerSku,fixture.prefix13Item.listingId);for(const patch of [{listingId:native.listingId.replace("8-","0-")},{listingId:native.listingId.replace(Client.NATIVE_STORE_ID,"00000000-0000-0000-0000-000000000000")},{articleId:"OTHER"},{productId:9482185},{productId:"09482185"},{detailsUrl:"/p/red-bull/999"},{type:"GROUP"},{title:"Milk <script>"}])assert.equal(Client.parseArticles([{...copy(native),...patch}],proof()).products.length,0);});
 await check("DE native market and pickup channel cannot be widened",()=>{for(const patch of [{serviceType:"DELIVERY"},{marketId:"8321065"},{nativeStoreId:"different"}])assert.equal(Client.parseArticles([{...copy(native),...patch}],proof()).products.length,0);for(const shop of [{...Client.MARKET,city:"Potsdam"},{...Client.MARKET,address:"Other"},{...Client.MARKET,country:"AT"},{...Client.MARKET,scopeChannel:"physical-store"}])assert.throws(()=>Client.parseArticles([native],{...proof(),shop}),/market-proof/);});
 await check("native fixed multipack and pieces retain individual sales quantities",()=>{const m=fixture.items.find(x=>x.articleId==="EWYNO6CE"),a=Client.parseArticles([copy(m)],proof()).products[0];assert.equal(a.packCount,4);assert.equal(a.packAmount,250);assert.equal(a.packUnit,"ml");const pieces=Client.parseArticles(copy(fixture.pieceItems),proof()).products;assert.equal(pieces.length,fixture.pieceItems.length);assert(pieces.some(x=>x.packAmount*x.packCount===10&&x.packUnit==="piece"));});
 await check("native pack mismatches and variable weight remain withheld",()=>{assert.equal(Client.parseArticles([copy(fixture.conflictingPackItem)],proof()).products.length,0);for(const patch of [{baseQuantity:999},{multi1:2},{volumeCode:"KGG"},{variableWeight:true},{sellByWeight:true},{pricing:{grammage:"ca. 250ml"}},{pricing:{grammage:"250 - 500ml"}},{pricing:null}])assert.equal(Client.parseArticles([{...copy(native),...patch}],proof()).products.length,0);});
 await check("closed article pack bounds reject per-row without aborting other identities",()=>{for(const grammage of ["1001x250ml","1000x100001g","100000001g","1e10g","0g"]){const item={...copy(native),title:"Synthetic bounded article",pricing:{grammage},baseQuantity:undefined,multi1:undefined},r=Client.parseArticles([native,item],proof());assert.equal(r.products.length,1);assert.equal(r.identityRejected.length,1);}});
 await check("unresolved native variants remain identities, not price-only exclusions",()=>{for(const patch of [{viewInfo:{detailsViewRequired:true}},{hasVariants:true},{hasDiverseVariantPrices:true},{variants:[]},{options:[]},{variant:"different"}])assert.equal(Client.parseArticles([{...copy(native),...patch}],proof()).products.length,0);});
 await check("supplied malformed native variant booleans cannot bypass identity hold",()=>{for(const key of ["hasVariants","hasDiverseVariantPrices"]){assert.equal(Client.parseArticles([{...copy(native),[key]:false}],proof()).products.length,1);for(const value of ["true","false",1,0,[],{}]){const r=Client.parseArticles([{...copy(native),[key]:value}],proof());assert.equal(r.products.length,0);assert(r.identityRejected[0].reasons.includes("rewe-variant-or-option-identity-unresolved"));}}});
 await check("article proof requires genuine product-source date/age/hash/profile",()=>{for(const patch of [{sourceResponseDate:null},{sourceResponseDate:new Date(TIME-900001).toISOString()},{sourceResponseDate:new Date(TIME+300001).toISOString()},{sourceAgeSeconds:901},{sourceAgeSeconds:-1},{sourceAgeSeconds:"0"},{sourceResponseHash:"A".repeat(64)},{sourceResponseUrl:filtersUrl},{capturedAt:true}])assert.throws(()=>Client.parseArticles([native],{...proof(),...patch}),/proof|clock/);});
 await check("original page reparses own bytes into identity and original prices",()=>{const o=original(),r=Client.reparseOriginalPage(o,{now:TIME});assert.equal(r.products.length,1);assert.equal(r.offers.length,1);assert.equal(r.products[0].observedAt,AT);assert.equal(r.products[0].sourceResponseHash,sha(Buffer.from(o.body)));assert.deepEqual(r.products[0].nativeWitness,JSON.parse(o.body).hits[0]);assert.equal(r.meta.responseDate,o.meta.responseDate);});
 await check("original page closes envelope and metadata keys",()=>{for(const mutate of [o=>o.untrusted=true,o=>delete o.body,o=>o.meta.extra=true,o=>o.meta.status=304,o=>o.meta.bytes++,o=>o.meta.contentType="application/json",o=>o.meta.responseDate=new Date(TIME+1000).toUTCString(),o=>o.meta.responseAge="0",o=>o.meta.sourceResponseHash="f".repeat(64)]){const o=original();mutate(o);assert.throws(()=>Client.reparseOriginalPage(o,{now:TIME}),/original/);}});
 await check("original page URL cannot borrow category, market, page or external scope",()=>{for(const mutate of [o=>o.category.slug="other",o=>o.category.id="not-native",o=>o.category.nativeCount=10000,o=>o.category.fake=true,o=>o.pageNumber=2,o=>o.meta.sourceResponseUrl=pageUrl().replace("PICKUP","DELIVERY"),o=>o.meta.sourceResponseUrl=pageUrl()+"&page=1",o=>o.meta.sourceResponseUrl=pageUrl().replace("www.rewe.de","evil.example")]){const o=original();mutate(o);assert.throws(()=>Client.reparseOriginalPage(o,{now:TIME}),/original|not-allowed/);}});
 await check("live admission has exact five-minute bound and historical identity explicit clock",()=>{const o=original();assert.doesNotThrow(()=>Client.reparseOriginalPage(o,{now:TIME+300000}));assert.throws(()=>Client.reparseOriginalPage(o,{now:TIME+300001}),/live-capture/);assert.throws(()=>Client.reparseOriginalPage(o,{now:TIME-1}),/live-capture/);assert.throws(()=>Client.reparseOriginalPage(o,{now:true}),/live-capture/);assert.doesNotThrow(()=>Client.reparseOriginalPage(o,{now:o.meta.capturedAt}));});
 await check("body hash covers exact whitespace; serializing data is not original proof",()=>{const o=original();o.body=" "+o.body;assert.throws(()=>Client.reparseOriginalPage(o,{now:TIME}),/body-invalid/);o.meta.bytes=Buffer.byteLength(o.body);assert.throws(()=>Client.reparseOriginalPage(o,{now:TIME}),/body-invalid/);o.meta.sourceResponseHash=sha(Buffer.from(o.body));assert.equal(Client.reparseOriginalPage(o,{now:TIME}).products.length,1);});
 await check("canonical UTF8, finite body bound and single JSON document required",()=>{const surrogate=original();surrogate.body=surrogate.body.slice(0,-1)+"\ud800}";surrogate.meta.bytes=Buffer.byteLength(surrogate.body);surrogate.meta.sourceResponseHash=sha(Buffer.from(surrogate.body));assert.throws(()=>Client.reparseOriginalPage(surrogate,{now:TIME}),/body-invalid/);const huge=original();huge.body=" ".repeat(Client.MAX_ORIGINAL_BYTES+1);huge.meta.bytes=Buffer.byteLength(huge.body);huge.meta.sourceResponseHash=sha(huge.body);assert.throws(()=>Client.reparseOriginalPage(huge,{now:TIME}),/body-invalid/);const multiple=original();multiple.body+="{}";multiple.meta.bytes=Buffer.byteLength(multiple.body);multiple.meta.sourceResponseHash=sha(multiple.body);assert.throws(()=>Client.reparseOriginalPage(multiple,{now:TIME}),/json-invalid/);});
 await check("native page pagination/scope checks remain authoritative",()=>{for(const p of [{...page(),search:{marketCode:"8321065"}},{...page(),search:{serviceTypes:["DELIVERY"]}},{...page(),search:{activeCategorySlug:"other"}},{...page(),pagination:{objectsPerPage:40,currentPage:1,pageCount:2,objectCount:41}}])assert.throws(()=>Client.reparseOriginalPage(original(p),{now:TIME}),/page/);});
 await check("original filters authenticate native frontier without body rewrite",()=>{const o=record(fixture.filters,filtersUrl,Client.FILTERS_ACCEPT),r=Client.reparseOriginalFilters(o,{now:TIME});assert.equal(r.categories.length,20);assert.equal(r.assortmentHash,Client.parseCategories(fixture.filters).assortmentHash);assert.equal(r.meta.sourceResponseHash,sha(o.body));const wrong=copy(o);wrong.meta.sourceResponseUrl=pageUrl();assert.throws(()=>Client.reparseOriginalFilters(wrong,{now:TIME}),/proof/);});
 await check("default small batch retains original filters and one native product page",async()=>{const source=transport(),r=await Client.fetchOffers({pauseMs:0,now:()=>AT},source.fetch);assert.equal(source.calls.length,2);assert.equal(r.requests,2);assert.equal(r.originalPages.length,1);assert.equal(r.products.length,40);assert.equal(r.nextCursor.pageNumber,2);assert.equal(r.complete,false);assert.equal(r.fullAssortmentVerified,false);assert.equal(Client.reparseOriginalFilters(r.originalFilters,{now:TIME}).categories.length,20);assert.equal(Client.reparseOriginalPage(r.originalPages[0],{now:TIME}).products.length,40);for(const c of source.calls){assert.equal(c.options.credentials,"omit");assert.equal(c.options.redirect,"error");assert.equal(c.options.method,"GET");assert(!c.options.headers.Cookie);}});
 await check("earlier committed-sized batch survives later denial without fabricated partial return",async()=>{const source=transport({laterStatus:403}),first=await Client.fetchOffers({pauseMs:0,now:()=>AT},source.fetch);assert.equal(first.products.length,40);await assert.rejects(()=>Client.fetchOffers({pauseMs:0,now:()=>AT,cursor:first.nextCursor},source.fetch),e=>e.code==="rewe-source-http-403"&&e.requestStage==="products"&&e.requestOrdinal===2&&e.requests===2&&!e.originalPages);assert.equal(first.originalPages.length,1);assert.equal(first.nextCursor.pageNumber,2);});
 await check("larger batch later denial still throws; no hidden partial authority",async()=>{const source=transport({laterStatus:403});await assert.rejects(()=>Client.fetchOffers({maxRequests:3,pauseMs:0,now:()=>AT},source.fetch),e=>e.code==="rewe-source-http-403"&&e.requestOrdinal===3&&e.requests===3&&e.totalBytes>0&&e.sourceResponseUrl===pageUrl(category.slug,2)&&!e.products);assert.equal(source.calls.length,3);});
 await check("filters403 diagnoses actual first ordinal and stops without products",async()=>{const source=transport({filtersResponse:response({},Client.FILTERS_ACCEPT,{status:403,headers:{"retry-after":"7200"}})});await assert.rejects(()=>Client.fetchOffers({pauseMs:0,now:()=>AT},source.fetch),e=>e.requestStage==="filters"&&e.requestOrdinal===1&&e.requests===1&&e.retryAfterMs===7200000&&e.sourceResponseUrl===filtersUrl);assert.equal(source.calls.length,1);});
 await check("gate before first GET fails closed and starts no request",async()=>{const source=transport();await assert.rejects(()=>Client.fetchOffers({canFetch:async()=>false,pauseMs:0,now:()=>AT},source.fetch),e=>e.code==="rewe-source-fetch-not-allowed"&&e.skipped==="source-gate"&&e.requests===0&&e.requestOrdinal===1);assert.equal(source.calls.length,0);await assert.rejects(()=>Client.fetchOffers({canFetch:()=>1},source.fetch),/not-allowed/);await assert.rejects(()=>Client.fetchOffers({canFetch:true},source.fetch),/gate-required/);});
 await check("gate loss after real pause cannot start product GET",async()=>{const source=transport();let permission=0;await assert.rejects(()=>Client.fetchOffers({pauseMs:100,now:()=>AT,canFetch:async()=>++permission<3},source.fetch),e=>e.code==="rewe-source-fetch-not-allowed"&&e.requests===1&&e.requestOrdinal===2&&e.totalBytes>0);assert.equal(permission,3);assert.equal(source.calls.length,1);});
 await check("product403 and429 preserve ordinal retry and request budget",async()=>{for(const status of [403,429]){const source=transport({firstResponse:response({},Client.PRODUCTS_ACCEPT,{status,headers:{"retry-after":"864000"}})});await assert.rejects(()=>Client.fetchOffers({pauseMs:0,now:()=>AT},source.fetch),e=>e.status===status&&e.requestStage==="products"&&e.requestOrdinal===2&&e.requests===2&&e.retryAfterMs===864000000);assert.equal(source.calls.length,2);}});
 await check("fatal native UTF8 cannot become a successful original witness",async()=>{const source=transport({firstResponse:response({},Client.PRODUCTS_ACCEPT,{bytes:Uint8Array.from([123,34,120,34,58,34,0xc3,0x28,34,125])})});await assert.rejects(()=>Client.fetchOffers({pauseMs:0,now:()=>AT},source.fetch),e=>e.code==="rewe-source-utf8-invalid"&&e.requestOrdinal===2);assert.equal(source.calls.length,2);});
 await check("original GET proof refuses body overflow and changed actual URL",async()=>{for(const firstResponse of [response(page(),Client.PRODUCTS_ACCEPT,{headers:{"content-length":String(Client.MAX_ORIGINAL_BYTES+1)}}),response(page(),Client.PRODUCTS_ACCEPT,{url:pageUrl().replace("8321066","8321065")})]){const source=transport({firstResponse});await assert.rejects(()=>Client.fetchOffers({pauseMs:0,now:()=>AT},source.fetch),/body-too-large|not-allowed/);assert.equal(source.calls.length,2);}});
 await check("price-less source remains a dated article page, not completed stock",async()=>{const item=copy(native);delete item.pricing.currentRetailPrice;const source=transport({firstResponse:response(page([item]),Client.PRODUCTS_ACCEPT)}),r=await Client.fetchOffers({pauseMs:0,now:()=>AT},source.fetch);assert.equal(r.offers.length,0);assert.equal(r.products.length,1);assert.equal(r.identityRejected.length,0);assert.equal(r.rejected.length,1);assert.equal(r.complete,false);assert.equal(r.physicalStoreAssortmentVerified,false);assert.equal(r.products[0].observedAt,AT);assert.equal(Client.reparseOriginalPage(r.originalPages[0],{now:TIME}).products.length,1);});
 console.log("rewe-native-article-client: "+groups+" groups verified; synthetic transport only, original Date/Age/bytes and safe priced/priceless native identities, no merchant requests");
}
main().catch(error=>{console.error(error);process.exitCode=1;});
