const assert=require("assert");
const api=require("../server.js");
assert.strictEqual(typeof api.handle,"function");
assert.strictEqual(typeof api.receiptHash,"function");
assert.strictEqual(typeof api.validReceiptPayload,"function");
assert.strictEqual(api.clean("x".repeat(200)).length,120);
const a={store:"EDEKA",date:"2026-09-28",total:"2.98",items:[{rawName:"Red Bull",lineTotal:2.98}]};
const b={...a,total:"3.98"};
assert.strictEqual(api.receiptHash(a),api.receiptHash(a),"receipt hash must be deterministic");
assert.notStrictEqual(api.receiptHash(a),api.receiptHash(b),"different receipts need different hashes");
assert(api.validReceiptPayload(a),"valid receipt payload rejected");
assert(!api.validReceiptPayload({...a,total:"3.48"}),"receipt with inconsistent item sum accepted");
assert(api.validReceiptPayload({store:"EDEKA",date:"2026-09-28",total:"8.46",items:[{rawName:"G&G Mini-Hörnchen",lineTotal:1.49},{rawName:"Oetker Ristorante",lineTotal:3.49},{rawName:"Red Bull",lineTotal:2.98},{rawName:"Pfand",lineTotal:.50}]}),"realistic EDEKA receipt total rejected");
assert(!api.validReceiptPayload({...a,total:"0"}),"zero-total receipt accepted");
assert(!api.validReceiptPayload({...a,items:[]}),"empty receipt accepted");
assert(!api.validReceiptPayload({...a,items:[{rawName:"Red Bull",lineTotal:0}]}),"zero-price line accepted");
assert(api.receiptCodeHash({store:"EDEKA",receiptBarcode:"12345678"}),"barcode hash missing");
assert.strictEqual(api.receiptCodeHash({store:"EDEKA"}),null);
assert.strictEqual(api.rewardScore({itemCount:5,isDuplicate:true}).xp,0);
assert(api.rewardScore({itemCount:5,recentCount:0}).xp>0);
const good={pricingConfidence:"confirmed",store:"EDEKA",key:"bananen",price:1.99,per:"kg",date:"2026-09-28",proof:"receipt_1"};
assert(api.validObs(good),"valid observation rejected");
assert(!api.validObs({...good,pricingConfidence:"guess"}),"unconfirmed observation accepted");
assert(!api.validObs({...good,price:-1}),"negative price accepted");
assert(!api.validObs({...good,per:"pack"}),"invalid unit accepted");
console.log("server unit smoke OK");
