"use strict";
const assert=require("node:assert/strict"),Client=require("../app/shopping-need-client"),Products=require("../app/published-product-client"),Matcher=require("../shopping-need-matcher"),Hit=require("../hit-product-discovery"),Fixture=require("./hit-product-discovery.test");
const NOW=Fixture.NOW,physical=Hit.validateRow(Fixture.row(),{now:NOW});assert(physical);
const identity={gtin:physical.gtin,name:physical.name,brand:null,pack:physical.pack,packAmount:physical.packAmount,packUnit:physical.packUnit,packCount:physical.packCount};
function online(name="TEST Milch",patch={}){return{sourceId:"Wolt nahkauf Berlin Wrangelstraße",merchant:"nahkauf",nativeVenueId:"657acc4eba505a018fb31b05",retailerSku:"657acc4eba505a018fb31b06",...identity,name,price:1.49,deposit:null,displayedPrice:1.49,nativePriceIncludesDeposit:true,payablePackPrice:null,currency:"EUR",priceBasis:"pack",capturedAt:new Date(NOW-1000).toISOString(),expiresAt:new Date(NOW+3600000).toISOString(),proofHash:"a".repeat(64),sourceUrl:"https://wolt.com/de/deu/berlin/venue/nahcity-wrangelstrae",shop:{nativeVenueId:"657acc4eba505a018fb31b05",name:"Nahkauf Wrangelstraße",address:"Wrangelstraße 75",postalCode:"10997",city:"Berlin",country:"DE"},scopeCountry:"DE",scopeChannel:"online",state:"published",current:true,truthEligible:false,shippingIncluded:false,serviceFeesIncluded:false,availability:"unknown",...patch};}
const requested={search:"Milch",constraints:{family:"milk",processing:"uht",fatPercent:1.5},pack:"1 l"};
function binding(offer){return{sourceId:offer.sourceId,scopeChannel:offer.scopeChannel,retailerSku:offer.retailerSku,storeId:offer.storeId||null,nativeVenueId:offer.nativeVenueId||null,nativeMarketId:offer.nativeMarketId||null,gtin:offer.gtin,pack:offer.pack};}
function response(offers=[online()],physicalOffers=[physical],input=requested){offers=structuredClone(offers);physicalOffers=structuredClone(physicalOffers);const need=Matcher.parse({search:input.search,constraints:input.constraints}),all=[...offers,...physicalOffers],offerMatches=all.map(offer=>({...binding(offer),...Matcher.classify(need,{name:offer.scopeChannel==="physical-store"?offer.nativeProof.headline:offer.name,...(offer.description?{description:offer.description}:{})})}));return{ok:true,items:[{...identity,offers,physicalOffers,needAssessment:{selectionRequired:true,status:offerMatches.some(match=>match.status==="confirmed")?"confirmed":"unconfirmed",offerMatches}}],scopeCountry:"DE",selectionRequired:true,automaticSelection:false,needCoverage:{complete:false},need,discoveryTruncated:true};}
let result=Client.normalizeResponse(response(),requested,{now:NOW});assert.equal(result.ok,true);assert.equal(result.items.length,1);assert.equal(result.items[0].needAssessment.status,"confirmed");assert.equal(result.items[0].needAssessment.offerMatches.length,2);assert.equal(result.items[0].needAssessment.offerMatches[0].status,"unconfirmed");assert.equal(result.items[0].physicalOffers[0].payablePackPrice,null);
assert(Client.candidate(result.items[0],{now:NOW,request:requested}),"Original source evidence is revalidated at manual click time");assert.equal(Client.candidate(result.items[0],{now:NOW,request:{...requested,constraints:{family:"milk",processing:"fresh"}}}),null,"Changed needs cannot reuse older candidates");
const lineBreak={...physical,nativeProof:{...physical.nativeProof,headline:physical.name.replace(' ', '\n')}};assert.equal(Client.normalizeResponse(response([],[lineBreak]),requested,{now:NOW}).items.length,1,"Literal native line breaks remain in semantic evidence while display names have whitespace collapsed");
assert.deepEqual(Products.selection(result.items[0]),identity,"Only GTIN and sales-pack identity is eligible for saved state");
for(const [label,mutate] of[
 ["missing binding",r=>r.items[0].needAssessment.offerMatches.pop()],
 ["duplicate binding",r=>r.items[0].needAssessment.offerMatches.push(r.items[0].needAssessment.offerMatches[0])],
 ["wrong store",r=>r.items[0].needAssessment.offerMatches[1].storeId="55555555-5555-4555-8555-555555555555"],
 ["wrong native venue",r=>r.items[0].needAssessment.offerMatches[0].nativeVenueId="invented"],
 ["wrong GTIN",r=>r.items[0].needAssessment.offerMatches[0].gtin="4046700026519"],
 ["wrong sale pack",r=>r.items[0].needAssessment.offerMatches[0].pack="2 x 500 ml"],
 ["forged status",r=>r.items[0].needAssessment.offerMatches[0].status="confirmed"],
 ["forged evidence",r=>r.items[0].needAssessment.offerMatches[1].evidence=[]],
 ["rewritten physical headline",r=>r.items[0].physicalOffers[0].nativeProof.headline="TEST Haferdrink"],
 ["canonical title is not native",r=>r.items[0].physicalOffers[0].name="TEST Milch"]
]){const raw=response();mutate(raw);assert.deepEqual(Client.normalizeResponse(raw,requested,{now:NOW}).items,[],label);}
for(const patch of[{scopeCountry:"AT"},{automaticSelection:true},{selectionRequired:false},{needCoverage:{complete:true}},{need:{search:"Milch",constraints:{family:"milk",processing:"fresh"}}},{items:Array(21).fill(response().items[0])}])assert.equal(Client.normalizeResponse({...response(),...patch},requested,{now:NOW}).ok,false,JSON.stringify(patch));
assert.deepEqual(Client.normalizeResponse(response(Array(201).fill(online()),[]),requested,{now:NOW}).items,[]);
const duplicate=response();duplicate.items.push(structuredClone(duplicate.items[0]));assert.deepEqual(Client.normalizeResponse(duplicate,requested,{now:NOW}).items,[]);
const dropped=Client.normalizeResponse(response([online()],[{...physical,expiresAt:new Date(NOW).toISOString()}]),requested,{now:NOW});assert.equal(dropped.items[0].needAssessment.status,"unconfirmed","An expired confirmed physical proof cannot colour the surviving unknown online quote");assert.equal(dropped.items[0].needAssessment.offerMatches.length,1);assert.equal(dropped.needCoverage.confirmedIdentities,0);
const scoped=Client.normalizeResponse(response(),{...requested,scopeChannel:"online"},{now:NOW});assert.equal(scoped.items[0].needAssessment.status,"unconfirmed");assert.equal(scoped.items[0].physicalOffers.length,0);
assert.equal(Client.candidate(result.items[0],{now:Date.parse(physical.expiresAt),request:requested}),null,"All original quotes expire rather than refreshing their timestamps at click");
const described=Client.normalizeResponse(response([online("TEST Milch",{description:"H-Milch 1,5% Fett"})],[]),requested,{now:NOW});assert.equal(described.items[0].needAssessment.status,"confirmed");
const contradiction=Client.normalizeResponse(response([online("TEST Frischmilch 3,5%")],[]),requested,{now:NOW});assert.deepEqual(contradiction.items,[]);
const changed=structuredClone(response());changed.items[0].needAssessment.status="confirmed";const unknown=Client.normalizeResponse(changed,{...requested,scopeChannel:"online"},{now:NOW});assert.equal(unknown.items[0].needAssessment.status,"unconfirmed","Recompute aggregate from actually admitted sources, never from the supplied group caption");
const butterPhysical=Hit.validateRow(Fixture.row({headline:"SYNTHETIC Butter Ungesalzen",overview:"250g Packung",gtin:"4000000000020",retailerSku:"000000000000007201ST"}),{now:NOW});assert(butterPhysical);const butterIdentity=Object.fromEntries(Object.keys(identity).map(key=>[key,key==="brand"?null:butterPhysical[key]])),butterRequest={search:"Butter",constraints:{family:"butter",salt:"unsalted"},pack:"250 g"};
function butterResponse(offers=[online("SYNTHETIC Butter",{...butterIdentity,name:"SYNTHETIC Butter"})],physicalOffers=[butterPhysical],input=butterRequest){const raw=response(offers,physicalOffers,input);Object.assign(raw.items[0],butterIdentity);return raw;}
const butter=Client.normalizeResponse(butterResponse(),butterRequest,{now:NOW});assert.equal(butter.items.length,1);assert.equal(butter.items[0].needAssessment.offerMatches[0].status,"unconfirmed");assert(butter.items[0].needAssessment.offerMatches[0].missing.includes("salt"));assert.equal(butter.items[0].needAssessment.offerMatches[1].status,"confirmed");assert.equal(butter.items[0].physicalOffers[0].payablePackPrice,null);assert.equal(butter.items[0].offers[0].scopeChannel,"online");assert(Client.candidate(butter.items[0],{now:NOW,request:butterRequest}));assert.equal(Client.candidate(butter.items[0],{now:NOW,request:{...butterRequest,constraints:{family:"butter",salt:"salted"}}}),null);assert.deepEqual(Products.selection(butter.items[0]),butterIdentity);
const missingButter=Client.normalizeResponse(butterResponse(),{...butterRequest,scopeChannel:"online"},{now:NOW});assert.equal(missingButter.items[0].needAssessment.status,"unconfirmed");assert.equal(missingButter.items[0].physicalOffers.length,0);for(const mutate of[r=>r.items[0].needAssessment.offerMatches[0].status="confirmed",r=>r.items[0].physicalOffers[0].nativeProof.headline="SYNTHETIC Butter Gesalzen",r=>r.items[0].needAssessment.offerMatches[1].pack="2 x 125 g"]){const forged=butterResponse();mutate(forged);assert.deepEqual(Client.normalizeResponse(forged,butterRequest,{now:NOW}).items,[]);}
assert.deepEqual(Client.normalizeResponse(butterResponse(),{...butterRequest,pack:"2 x 125 g"},{now:NOW}).items,[]);assert.equal(Client.candidate(butter.items[0],{now:Date.parse(butterPhysical.expiresAt),request:butterRequest}),null);
assert.deepEqual(Client.request({search:"Butter",constraints:{family:"butter"},pack:"",scopeChannel:""}).payload,{search:"Butter",constraints:{family:"butter"},limit:20},"Blank butter salt does not infer unsalted or a pack");
(async()=>{
 let calls=0,seen;const client=Client.create({apiBase:"https://prices.example.test/",now:()=>NOW,fetchImpl:async(url,options)=>{calls++;seen={url,options};return{ok:true,json:async()=>response()};}});
 result=await client.search(requested);assert.equal(result.items.length,1);assert.equal(seen.url,"https://prices.example.test/v1/shopping-need");assert.equal(seen.options.method,"POST");assert.equal(seen.options.credentials,"omit");assert.deepEqual(JSON.parse(seen.options.body),{...requested,limit:20});assert.equal(seen.options.headers["Content-Type"],"application/json");
 const before=calls;for(const raw of[{...requested,constraints:{family:["milk"]}},{...requested,constraints:{family:"milk",fatPercent:"1.5"}},{...requested,refresh:true},{...requested,now:NOW},{...requested,limit:200},{...requested,search:"Milch 1-3%"},{...requested,pack:"ca. 1 l"}])assert.equal((await client.search(raw)).ok,false);assert.equal(calls,before,"Invalid needs never make inventory or source requests");
 const blank=Client.request({search:"Milch",constraints:{family:"milk"},pack:"",scopeChannel:""});assert.deepEqual(blank.payload,{search:"Milch",constraints:{family:"milk"},limit:20},"Generic milk has no fat, process or pack defaults");
 const bad=Client.create({fetchImpl:async()=>({ok:false,status:400,json:async()=>({error:"invalid-shopping-need-constraints"})})});assert.equal((await bad.search(requested)).reason,"invalid-shopping-need-constraints","A malformed need is never retried as unrestricted keyword search");
 const aborted=new AbortController();aborted.abort();assert.equal((await client.search(requested,{signal:aborted.signal})).reason,"cancelled");assert.equal(calls,before);
 let release;const controller=new AbortController(),held=Client.create({fetchImpl:()=>new Promise(resolve=>{release=()=>resolve({ok:true,json:async()=>response()});})}),pending=held.search(requested,{signal:controller.signal});await Promise.resolve();controller.abort();release();assert.equal((await pending).reason,"cancelled");
 const timed=Client.create({fetchImpl:()=>new Promise(()=>{}),timeoutMs:5});assert.equal((await timed.search(requested)).ok,false);
 console.log("shopping-need-client: bounded read-only POST, independent native semantic checks, exact per-source binding, expiry and explicit selection OK");
})().catch(error=>{console.error(error);process.exitCode=1});
