"use strict";
const assert=require("node:assert/strict"),fs=require("node:fs"),path=require("node:path"),Discovery=require("../published-product-discovery"),Dm=require("../published-price-service"),Wolt=require("../wolt-retailer-price-service"),Hit=require("../hit-product-discovery"),Fixture=require("./hit-product-discovery.test");
const NOW=Fixture.NOW,noPhysical={search:async()=>({items:[],truncated:false})},noOnline={search:async()=>({items:[]})};
function gtin(index){const body="400001"+String(index).padStart(6,"0");return body+String((10-[...body].reduce((sum,n,i)=>sum+Number(n)*(i%2?3:1),0)%10)%10);}
function dm(index,name,patch={}){const checked=Dm.validateOffer({sourceId:Dm.SOURCE,merchant:"dm",retailerSku:String(index),gtin:gtin(index),name,brand:null,pack:"1 l",price:1.29,currency:"EUR",capturedAt:new Date(NOW-1000).toISOString(),sourceUrl:"https://www.dm.de/p/d/"+index+"/local-test-product",proofHash:"a".repeat(64),scopeCountry:"DE",scopeChannel:"online",availability:"unknown",...patch},{now:NOW});assert.equal(checked.ok,true,JSON.stringify(checked));return checked.offer;}
function wolt(name,description,patch={}){const checked=Wolt.validateOffer({sourceId:Wolt.SOURCE,merchant:Wolt.MERCHANT,nativeVenueId:Wolt.VENUE.nativeVenueId,retailerSku:"9".repeat(24),gtin:gtin(99),name,description,brand:null,pack:"1000 ml",price:1.49,deposit:null,displayedPrice:1.49,nativePriceEUR:1.49,nativePriceIncludesDeposit:true,currency:"EUR",capturedAt:new Date(NOW-2000).toISOString(),proofHash:"b".repeat(64),sourceResponseHash:"b".repeat(64),sourceUrl:"https://wolt.com/de/deu/berlin/venue/edeka-hilbrecht",sourceResponseUrl:"https://consumer-api.wolt.com/consumer-api/consumer-assortment/v1/venues/slug/edeka-hilbrecht/assortment/categories/slug/milch-46",shop:Wolt.VENUE,scopeCountry:"DE",scopeChannel:"online",priceType:"unknown",promotionStatus:"unknown",availability:"unknown",...patch},{now:NOW});assert.equal(checked.ok,true,JSON.stringify(checked));return checked.offer;}
async function main(){const originalClock=Date.now;Date.now=()=>NOW;try{
 const physical=Hit.validateRow(Fixture.row(),{now:NOW});assert(physical);const physicalInput={search:"H-Milch 1,5%",constraints:{family:"milk",processing:"uht",fatPercent:1.5},pack:"1 l",scopeChannel:"physical-store"},calls=[];
 const first=await Discovery.searchNeed({},physicalInput,{search:async()=>{throw Error("No online lookup for physical scope");}},{search:async(pool,options)=>{calls.push(options);return{items:[physical],truncated:false};}});assert.equal(first.items.length,1);assert.equal(first.items[0].needAssessment.status,"confirmed");assert.equal(first.selectionRequired,true);assert.equal(first.automaticSelection,false);assert.equal(first.requiresProductSelection,true);assert.deepEqual(first.items[0].physicalOffers,[physical],"Need classification cannot rewrite source price, deposit, proof or capture");assert.deepEqual(first.items[0].offers,[]);assert.equal(first.items[0].needAssessment.offerMatches[0].storeId,physical.storeId);assert.deepEqual(calls,[{search:"Milch",limit:200,now:NOW,pack:"1 l",scopeChannel:"physical-store"}]);assert.equal(first.needCoverage.complete,false);assert.equal(first.items[0].physicalOffers[0].payablePackPrice,null);
 const missing=await Discovery.searchNeed({}, {...physicalInput,search:"Milch",constraints:{family:"milk",lactose:"contains"}},noOnline,{search:async()=>({items:[physical],truncated:false})});assert.equal(missing.items[0].needAssessment.status,"unconfirmed");assert(missing.items[0].needAssessment.offerMatches[0].missing.includes("lactose"));assert.equal(missing.selectionRequired,true);
 const fresh=await Discovery.searchNeed({}, {...physicalInput,search:"Milch",constraints:{family:"milk",processing:"fresh"}},noOnline,{search:async()=>({items:[physical],truncated:false})});assert.deepEqual(fresh.items,[]);assert.equal(fresh.selectionRequired,true);assert.equal(fresh.needCoverage.contradictedOffers,1);
 const wrongPack=await Discovery.searchNeed({}, {...physicalInput,pack:"2 x 500 ml"},noOnline,{search:async()=>({items:[physical],truncated:false})});assert.deepEqual(wrongPack.items,[]);
 for(const patch of[{branch:{...physical.branch,country:"AT"}},{gtin:"4388844177315"},{expiresAt:new Date(NOW).toISOString()},{proofHash:"b".repeat(64)},{pack:"2 x 500 ml"},{price:.99}]){const result=await Discovery.searchNeed({},physicalInput,noOnline,{search:async()=>({items:[{...physical,...patch}],truncated:false})});assert.deepEqual(result.items,[],JSON.stringify(patch));assert.equal(result.needCoverage.confirmedOffers,0);}
 const blockers=Array.from({length:25},(_,i)=>dm(i+1,"TEST Frisch-Milch 3,5%")),confirmed=dm(31,"TEST H-Milch 1,5%"),unknown=dm(32,"TEST Milch"),sourceInput=[...blockers,unknown,confirmed],before=JSON.stringify(sourceInput),online=await Discovery.searchNeed({}, {...physicalInput,scopeChannel:"online",limit:1},{search:async()=>({items:sourceInput})},{search:async()=>{throw Error("No physical lookup for online scope");}});
 assert.equal(online.items.length,1);assert.equal(online.items[0].gtin,confirmed.gtin,"Contradicted or missing variants cannot crowd a confirmed candidate out of the final20 limit");assert.deepEqual(online.items[0].offers,[confirmed]);assert.equal(online.needCoverage.contradictedOffers,25);assert.equal(online.discoveryTruncated,true);assert.equal(JSON.stringify(sourceInput),before);assert.equal(online.physicalStorePrices,false);
 const described=wolt("TEST Milch","H-Milch, 1,5% Fett"),describedResult=await Discovery.searchNeed({}, {...physicalInput,scopeChannel:"online"},{search:async()=>({items:[described]})},noPhysical);assert.equal(describedResult.items[0].needAssessment.status,"confirmed");assert(describedResult.items[0].needAssessment.offerMatches[0].evidence.some(e=>e.field==="description"));assert.equal(describedResult.items[0].offers[0].truthEligible,false);assert.equal(describedResult.items[0].offers[0].scopeChannel,"online");
 const mixedNative=dm(42,"TEST Frisch-Milch 1,5%",{gtin:physical.gtin}),mixed=await Discovery.searchNeed({}, {...physicalInput,scopeChannel:undefined},{search:async()=>({items:[mixedNative]})},{search:async()=>({items:[physical],truncated:false})});assert.equal(mixed.items.length,1);assert.deepEqual(mixed.items[0].offers,[]);assert.deepEqual(mixed.items[0].physicalOffers,[physical],"Use each source's native wording, never a group's first canonical caption");
 const manyQuotes=Array.from({length:200},(_,index)=>dm(2000+index,index===199?"TEST H-Milch 1,5%":"TEST Milch",{gtin:physical.gtin})),capped=await Discovery.searchNeed({}, {...physicalInput,scopeChannel:undefined},{search:async()=>({items:manyQuotes})},{search:async()=>({items:[physical],truncated:false})});assert.equal(capped.items.length,1);assert.equal(capped.items[0].offers.length+capped.items[0].physicalOffers.length,200);assert.equal(capped.items[0].physicalOffers.length,1);assert(capped.items[0].offers.some(offer=>offer.retailerSku==="2199"),"Reserve a confirmed native proof before unconfirmed variants fill the shared200 budget");assert.equal(capped.items[0].needAssessment.offerMatches.length,200,"Semantic assessments bind only actually emitted proofs");assert.equal(capped.discoveryTruncated,true);
 const generic=await Discovery.searchNeed({}, {search:"Milch",constraints:{family:"milk"},scopeChannel:"online"},{search:async()=>({items:[unknown,confirmed]})},noPhysical);assert.deepEqual(generic.need.constraints,{family:"milk"});assert(generic.items.every(item=>item.needAssessment.status==="confirmed"));assert.equal(generic.selectionRequired,true);
 const legacy=await Discovery.search({}, {search:"Milch",limit:1}, {search:async()=>({items:sourceInput})},noPhysical);assert(legacy.items.length);assert(!Object.hasOwn(legacy,"need"));assert(!Object.hasOwn(legacy.items[0],"needAssessment"));
 let fetched=false;const never={search:async()=>{fetched=true;throw Error("Invalid need must fail before provider reads");}};
 for(const input of[null,[],{search:"Milch"},{search:"Milch",constraints:{family:"invented"}},{search:"H-Milch",constraints:{family:"milk",processing:"fresh"}},{search:"Milch",constraints:{family:"milk",fatPercent:"1.5"}},{...physicalInput,refresh:true},{...physicalInput,now:NOW},{...physicalInput,limit:21},{...physicalInput,pack:"2 x 500 nonsense"},{...physicalInput,constraints:{family:"milk",size:"M"}}])await assert.rejects(()=>Discovery.searchNeed({},input,never,never),error=>/^invalid-/.test(error.code));assert.equal(fetched,false);
 for(const [search,constraints] of [["Milch",{family:["milk"]}],["frische fettarme Milch",{family:"milk"}],["Milch ESL",{family:"milk"}],["Milch 1,5-3,5%",{family:"milk"}],["Brot nicht aus Vollkorn",{family:"bread"}],["Eier Gewichtsklasse: nicht M",{family:"eggs"}]]) await assert.rejects(()=>Discovery.searchNeed({}, {search,constraints},never,never),error=>/^invalid-/.test(error.code));assert.equal(fetched,false,"Unsupported qualifiers and malformed family must reject before inventory access");
 const mislabelled=wolt("TEST Milch","Pflanzlicher Haferdrink"),excludedDescription=await Discovery.searchNeed({}, {search:"Milch",constraints:{family:"milk"},scopeChannel:"online"},{search:async()=>({items:[mislabelled]})},noPhysical);assert.deepEqual(excludedDescription.items,[]);assert.equal(excludedDescription.needCoverage.contradictedOffers,1,"Native excluded identity cannot become a broad milk candidate");
 const butterNeed={search:"Butter ungesalzen",constraints:{family:"butter",salt:"unsalted"},pack:"250 g",scopeChannel:"physical-store"},butterRows=["SYNTHETIC Butter Ungesalzen","SYNTHETIC Butter","SYNTHETIC Butter Gesalzen","SYNTHETIC Buttertoast","SYNTHETIC Erdnussbutter","SYNTHETIC Butter mit Rapsöl"].map((headline,index)=>Hit.validateRow(Fixture.row({headline,overview:"250g Packung",gtin:gtin(7100+index),retailerSku:String(7100+index).padStart(18,"0")+"ST"}),{now:NOW}));assert(butterRows.every(Boolean));const originalButter=JSON.stringify(butterRows),butterCalls=[];
 const butter=await Discovery.searchNeed({},butterNeed,noOnline,{search:async(pool,query)=>{butterCalls.push(query);return{items:butterRows,truncated:false};}});assert.deepEqual(butterCalls,[{search:"Butter",limit:200,now:NOW,pack:"250 g",scopeChannel:"physical-store"}]);assert.equal(butter.items.length,2);assert.equal(butter.items[0].needAssessment.status,"confirmed");assert.equal(butter.items[1].needAssessment.status,"unconfirmed");assert(butter.items[1].needAssessment.offerMatches[0].missing.includes("salt"));assert.equal(butter.needCoverage.contradictedOffers,4);assert.equal(butter.selectionRequired,true);assert.equal(butter.automaticSelection,false);assert.equal(butter.needCoverage.complete,false);assert.equal(JSON.stringify(butterRows),originalButter);assert.equal(butter.items[0].physicalOffers[0].payablePackPrice,null,"Salt wording does not create a deposit or payable price");assert.equal(butter.items[0].offers.length,0);
 const unsaltedOnline=dm(7201,"SYNTHETIC Butter Ungesalzen",{pack:"250 g"}),saltedOnline=dm(7202,"SYNTHETIC Butter Gesalzen",{pack:"250 g"});const butterOnline=await Discovery.searchNeed({}, {...butterNeed,scopeChannel:"online"},{search:async()=>({items:[saltedOnline,unsaltedOnline]})},noPhysical);assert.equal(butterOnline.items.length,1);assert.equal(butterOnline.items[0].offers[0].scopeChannel,"online");assert.equal(butterOnline.items[0].physicalOffers.length,0);assert.equal(butterOnline.physicalStorePrices,false);
 for(const input of[{...butterNeed,pack:"2 x 125 g"},{...butterNeed,scopeChannel:"pickup"}]){const result=await Discovery.searchNeed({},input,noOnline,{search:async()=>({items:butterRows,truncated:false})});assert.equal(result.items.length,0);}
 const queriedButter=calls.length;for(const constraints of[{family:"butter",salt:true},{family:"butter",salt:"none"},{family:"butter",composition:"pure"},{family:"milk",salt:"unsalted"}])await assert.rejects(()=>Discovery.searchNeed({}, {...butterNeed,constraints},never,never),e=>/^invalid-/.test(e.code));assert.equal(calls.length,queriedButter);assert.equal(fetched,false);
 const s=fs.readFileSync(path.join(__dirname,"../server.js"),"utf8"),start=s.indexOf('req.url==="/v1/shopping-need"'),route=s.slice(start,start+900);assert(start>0);assert(route.includes("PublishedProductDiscovery.searchNeed(pool,b)"));assert(!route.includes("refreshInternetPrices"));
 console.log("shopping-need-discovery: current native evidence, semantic uncertainty, exact packs, scoped sources, explicit selection, pre-limit filtering and read-only HTTP contract OK");
 }finally{Date.now=originalClock}}
main().catch(error=>{console.error(error);process.exitCode=1});
