const fs=require("fs"),os=require("os"),path=require("path"),cp=require("child_process"),assert=require("assert");
const html=fs.readFileSync("index.html","utf8");
const scripts=[...html.matchAll(/<script(?:\s[^>]*)?>([\s\S]*?)<\/script>/gi)].map(m=>m[1]).filter(x=>x.trim());
assert(scripts.length>=3,"inline scripts missing");
scripts.forEach((code,i)=>{const file=path.join(os.tmpdir(),"echtpreis-inline-"+(i+1)+".js");fs.writeFileSync(file,code);const r=cp.spawnSync(process.execPath,["--check",file],{encoding:"utf8"});assert.strictEqual(r.status,0,"inline script "+(i+1)+" syntax: "+(r.stderr||r.stdout));});
const ids=[...html.matchAll(/\bid="([^"]+)"/g)].map(m=>m[1]);assert.strictEqual(new Set(ids).size,ids.length,"duplicate HTML ids");
["productInput","addBtn","compareBtn","demoListBtn","list","stores","results","receiptFile","receiptStore","receiptDate","finishPurchaseBtn","reviewRows","ocrStatus","receiptTotalCheck","receiptStoreDetail","receiptPaymentDetail","receiptInsight","receiptInsightTitle","statsAverage","statsBreakdown","statsTrend","statsDiscoveries","statsRecent","statsInsight","feedbackText","feedbackSend","feedbackStatus","homePulse","homePulseTitle","homePulseDetail"].forEach(id=>assert(ids.includes(id),"missing required element #"+id));
assert(!html.includes('addEventListener("click",compareStable)'),"legacy compare engine is still bound");
assert(!html.includes('var demo=byId("demoListBtn")'),"obsolete demo handler is still bound");
assert(html.includes("window.addEchtpreisItem"),"single-basket bridge missing");
assert(html.includes("window.replaceEchtpreisList"),"saved-list bridge missing");
assert(html.includes("rawForAmount"),"decimal-comma quantity parser missing");
assert(html.includes("receiptCandidateScore"),"multi-pass receipt scoring missing");
assert(!html.includes('label for="receiptTotalInput"'),"manual receipt-total editor must stay hidden");
assert.strictEqual((html.match(/function importRecipeIngredients\s*\(/g)||[]).length,1,"recipe import must have one implementation");
assert(html.includes("plausibleReceiptItemName"),"receipt item plausibility guard missing");
assert(html.includes("comparisonQuality"),"comparison confidence labelling missing");
assert(!html.includes("compareStable"),"obsolete duplicate comparison engine must stay removed");
assert(html.includes('history.sort((a,b)=>String(b.date).localeCompare(String(a.date))||Number(b.trust||0)-Number(a.trust||0)||a.price-b.price)'),"historical fallback must prioritize freshness and trust");
assert(html.includes("echtpreis_openprices_sync_by_key_v1"),"Open Prices should be cached per product key");
assert(html.includes("const keys=[...new Set(basket.map(w=>w.key).filter(Boolean))]"),"manual compare should derive and deduplicate basket price categories");
assert(!html.includes("syncSharedData();ingestOpenPrices();"),"startup must not fetch the full Open Prices catalog");
assert(html.includes('<script src="app/config.js"></script>'),"store-ready config layer missing");
assert(html.includes('<script src="app/runtime.js"></script>'),"platform runtime layer missing");
assert(html.includes("window.EchtpreisRuntime"),"location flow must use the platform runtime");
assert(html.includes('href="privacy.html"'),"privacy entry point missing");
assert(html.includes('rel="manifest"'),"installable web-app manifest missing");
assert(html.includes('apple-mobile-web-app-capable'),"iOS home-screen metadata missing");
assert(html.indexOf('id="homeReceipt"')<html.indexOf('id="homePlan"'),"receipt scan should be the primary home action");
assert(html.includes("Bon scannen"),"primary receipt action copy missing");
assert(html.includes("function buildReceiptInsight"),"personal receipt insight engine missing");
assert(html.includes("function renderStatsBreakdown"),"monthly spending breakdown missing");
assert(html.includes("sicher kategorisiert"),"spending breakdown confidence coverage missing");
assert(html.includes('x.category!=="Sonstiges"'),"uncertain categories must not drive post-scan category facts");
assert(html.includes("echtpreis_insight_history_v1"),"personal insight history missing");
assert(html.includes("function renderStatsCategoryChanges"),"monthly category-change analysis missing");
assert(html.includes("function renderStatsYearTrend"),"fair year-to-date comparison missing");
assert(html.includes('id="statsMore"'),"advanced statistics should be grouped for mobile readability");
assert(html.includes("Nähe vs. Preis"),"price-versus-distance tradeoff missing");
assert(html.includes("function renderStatsMarketProfile"),"personal market profile missing");
assert(html.includes('<details><summary style="cursor:pointer;font-weight:900">Meine Märkte'),"secondary market analytics should stay compact");
assert(html.includes('x.category==="Sonstiges"'),"uncertain categories should be filtered from trend drivers");
assert(html.includes("function renderStatsPriceMemory"),"personal product price memory missing");
assert(html.includes("function renderStatsRhythm"),"personal shopping rhythm analysis missing");
assert(html.includes("function searchPersonalPurchases"),"personal purchase search missing");
assert(html.includes("function renderPurchaseSearch"),"personal purchase search renderer missing");
assert(html.includes("purchase-rhythm"),"post-scan rhythm insight missing");
assert(html.includes("top-item-share"),"dominant receipt-item insight missing");
assert(html.includes("gleiche")||html.includes("identisch"),"market profile must explain direct-product comparison");
assert(html.includes("function renderStatsTrend"),"month-over-month shopping trend missing");
assert(html.includes("function renderHomePulse"),"personal home pulse missing");
assert(html.includes('API_BASE+"/v1/feedback"'),"tester feedback endpoint is not wired into the UI");
assert(html.includes("echtpreis_feedback_queue_v1"),"offline feedback queue missing");
assert(html.includes("flushFeedbackQueue"),"queued feedback retry missing");
assert(html.includes("items:valid.map"),"local receipt history must retain line items for future insights");
assert(html.includes("typicalQty=medianNumber(priorQty)"),"household forecast must normalize latest quantity against typical purchase quantity");
assert(html.includes("if(storeCanCarry(store,wish,key))"),"primary price comparison must enforce retailer assortment");
assert(html.includes("reward.ok&&!reward.duplicate&&receiptTotalVerified"),"duplicate or server-unverified receipts must never contribute market prices");
assert(html.includes("Number(r.packAmount||0)*(Number(r.count)||1)"),"multipack receipt observations must normalize by total purchased quantity");
assert(html.includes("lineTotal:Number(x.price)||0,price:Number(x.price)||0,count:Number(x.count)||1"),"receipt sync must preserve line total so multipacks are not divided twice after reload");
assert(html.includes("globalAdjustments=receiptDraft.filter"),"coupon receipts must not produce misleading cross-store savings");
assert(html.includes("plausibleObservationPrice(x)"),"trusted prices must reject implausible price outliers");
assert(html.includes("x.per!==catalog[x.key].unit"),"price observations with the wrong comparison unit must be rejected");
assert(html.includes("function exactBrandFallbackPrice"),"cold-start exact-brand orientation is missing");
assert(html.includes('referenceType:"brand-estimate"'),"estimated exact-brand prices must be explicitly labeled");
assert(html.includes("verifiedBest.total<=win.total*1.12"),"basket ranking must balance evidence quality with useful cold-start savings");
assert(html.includes('type:"first-receipt-fact"'),"first receipt should produce an immediate useful fact");
assert(html.includes("currentReceiptSaving=Number(saving.toFixed(2))"),"estimated receipt savings should remain available with confidence labeling");
assert(html.includes("comparisonRefreshPromise=Promise.allSettled"),"shopping comparison should render cache-first while refreshing asynchronously");
assert(html.includes("Promise.allSettled([loadNearbyStores(),ingestOpenPrices(false,keys)])"),"location and live price refresh should run in parallel");
assert(html.includes("comparisonRefreshPromise"),"concurrent background comparison refreshes should be deduplicated");
assert(html.includes("echtpreis_nearby_store_cache_v1"),"nearby stores should persist across sessions for fast repeat comparisons");



const cat=(html.match(/openPricesCategory:/g)||[]).length;assert(cat>=15,"too few live Open Prices categories: "+cat);
const products=(html.match(/label:"/g)||[]).length;assert(products>=30,"primary product catalog unexpectedly small: "+products);
assert(!html.includes("stableBasket"),"obsolete duplicate basket state must stay removed");
assert(html.includes("if(dataEngineCache)return dataEngineCache"),"normalized observation engine should be cached");
assert(html.includes("priceLookupMemo"),"basket price lookups should be memoized within a comparison");
console.log("static smoke OK · scripts="+scripts.length+" · catalog labels="+products+" · Open Prices categories="+cat);
