const fs=require("fs"),os=require("os"),path=require("path"),cp=require("child_process"),assert=require("assert");
const html=fs.readFileSync("index.html","utf8");
const scripts=[...html.matchAll(/<script(?:\s[^>]*)?>([\s\S]*?)<\/script>/gi)].map(m=>m[1]).filter(x=>x.trim());
assert(scripts.length>=3,"inline scripts missing");
scripts.forEach((code,i)=>{const file=path.join(os.tmpdir(),"echtpreis-inline-"+(i+1)+".js");fs.writeFileSync(file,code);const r=cp.spawnSync(process.execPath,["--check",file],{encoding:"utf8"});assert.strictEqual(r.status,0,"inline script "+(i+1)+" syntax: "+(r.stderr||r.stdout));});
const ids=[...html.matchAll(/\bid="([^"]+)"/g)].map(m=>m[1]);assert.strictEqual(new Set(ids).size,ids.length,"duplicate HTML ids");
["productInput","addBtn","compareBtn","demoListBtn","list","stores","results","receiptFile","receiptStore","receiptDate","finishPurchaseBtn","reviewRows","ocrStatus","receiptTotalCheck","receiptStoreDetail","receiptPaymentDetail","statsAverage","statsRecent"].forEach(id=>assert(ids.includes(id),"missing required element #"+id));
assert(!html.includes('addEventListener("click",compareStable)'),"legacy compare engine is still bound");
assert(!html.includes('var demo=byId("demoListBtn")'),"obsolete demo handler is still bound");
assert(html.includes("window.addEchtpreisItem"),"single-basket bridge missing");
assert(html.includes("window.replaceEchtpreisList"),"saved-list bridge missing");
assert(html.includes("rawForAmount"),"decimal-comma quantity parser missing");
assert(html.includes("receiptCandidateScore"),"multi-pass receipt scoring missing");
assert(!html.includes('label for="receiptTotalInput"'),"manual receipt-total editor must stay hidden");
assert.strictEqual((html.match(/function importRecipeIngredients\s*\(/g)||[]).length,1,"recipe import must have one implementation");
assert(html.includes("plausibleReceiptItemName"),"receipt item plausibility guard missing");
assert(html.includes("comparisonQuality"),"comparison confidence labelling missing");
assert(html.includes('String(b.validFrom||"").localeCompare(String(a.validFrom||""))||(Number(b.trust)||0)-(Number(a.trust)||0)||a.price-b.price'),"legacy price chooser must prioritize freshness and trust before cheapness");
assert(html.includes('history.sort((a,b)=>String(b.date).localeCompare(String(a.date))||Number(b.trust||0)-Number(a.trust||0)||a.price-b.price)'),"historical fallback must prioritize freshness and trust");
const cat=(html.match(/openPricesCategory:/g)||[]).length;assert(cat>=15,"too few live Open Prices categories: "+cat);
const products=(html.match(/label:"/g)||[]).length;assert(products>=30,"primary product catalog unexpectedly small: "+products);
console.log("static smoke OK · scripts="+scripts.length+" · catalog labels="+products+" · Open Prices categories="+cat);
