"use strict";

const assert=require("node:assert/strict"),crypto=require("node:crypto"),Client=require("../wolt-retailer-price-client"),Service=require("../wolt-retailer-article-service"),fixture=require("./fixtures/retailers/wolt-edeka-berlin.json");
const clone=structuredClone,now=Date.parse("2026-10-03T02:00:00.000Z"),base=now-10000,sha=v=>crypto.createHash("sha256").update(v).digest("hex");let groups=0;
const check=fn=>{fn();groups++;};
// These are explicitly synthetic native originals, not retimed source imports.
function capture(patch={},at=base){const venue=clone(fixture.venueState.queries[0].state.data),stamp=new Date(at).toISOString(),venueIdentityProof={capturedAt:stamp,sourceResponseUrl:Client.VENUE_API_URL,sourceResponseHash:sha(JSON.stringify(venue)),sourceResponseDate:stamp,sourceAgeSeconds:0},shop=Client.parseNativeVenue(venue,venueIdentityProof),item={...clone(fixture.pages[1].items[0]),price:null,deposit:null,original_price:null,unit_price:null,...patch},meta={shop,capturedAt:stamp,sourceResponseUrl:Client.API_ORIGIN+Client.API_PATH+"/categories/slug/synthetic-test-items",sourceResponseHash:sha(JSON.stringify({syntheticOriginal:true,items:[item]})),sourceResponseDate:stamp,sourceAgeSeconds:0,venueIdentityOriginal:venue,venueIdentityProof};return{item,meta,parsed:Client.parseItems([item],meta)};}
function product(patch={},at=base){const result=capture(patch,at);assert.equal(result.parsed.products.length,1,JSON.stringify(result.parsed));return result.parsed.products[0];}
const row=a=>({...Service.rowForArticle(a),held:false,conflict_capture:null});
const reader=rows=>({query:async()=>({rows:clone(rows)})});
async function main(){
 const p=product();check(()=>{const checked=Service.validateArticle(p,{now});assert(checked.ok,JSON.stringify(checked));assert.equal(checked.article.gtin,"5449000017888");assert.equal(checked.article.price,undefined);assert.equal(checked.article.packAmount,1000);assert.equal(checked.article.packUnit,"ml");assert.equal(checked.article.packCount,1);assert(p.description.includes("\n"),"Actual native Coca-Cola description contains a legitimate line break");});
 check(()=>{for(const raw of[null,[],"",0]){assert.equal(Service.validateArticle(raw,{now}).ok,false);assert.equal(Service.validateView(raw,{now}).ok,false);}const circular=clone(p);circular.nativeWitness.loop=circular.nativeWitness;assert.equal(Service.validateArticle(circular,{now}).ok,false);});
 check(()=>{const old=product({},now-30*86400000);assert(Service.validateArticle(old,{now}).ok);assert.equal(old.observedAt,new Date(now-30*86400000).toISOString());});
 check(()=>{const native=product({barcode_gtin:null,name:"Food 5449000017888",description:"GTIN 5449000017888"});assert.equal(native.gtin,null);assert(Service.validateArticle(native,{now}).ok);});
 check(()=>{for(const barcode_gtin of[1234567890123,false,{},[],"0000000000001","GTIN 5449000017888"," 5449000017888 ","5449000-017888"," "]){const r=capture({barcode_gtin});assert.equal(r.parsed.products.length,0);assert(r.parsed.identityRejected[0].reasons.includes("wolt-product-invalid-gtin"));}for(const barcode_gtin of[null,undefined,""]){const r=capture({barcode_gtin});assert.equal(r.parsed.products.length,1);assert.equal(r.parsed.products[0].gtin,null);}});
 check(()=>{const input=capture({price:null,disabled_info:{reason:"unavailable"},is_wolt_plus_only:true,min_quantity_per_purchase:2,deposit:{amount:999999,label:"unknown"}});assert.equal(input.parsed.offers.length,0);assert.equal(input.parsed.products.length,1);const a=input.parsed.products[0];assert(Service.validateArticle(a,{now}).ok);for(const key of["price","deposit","availability","disabled_info","is_wolt_plus_only","min_quantity_per_purchase"])assert.equal(a[key],undefined);});
 check(()=>{for(const patch of[{unit_info:null},{unit_info:"ca. 1 kg"},{sell_by_weight_config:{}},{options:[{}]},{options:null},{variant:{}},{name:"Food ca. 1 kg",unit_info:"1 kg"},{name:"<b>Food</b>"},{description:"<script>bad</script>"}])assert.equal(capture(patch).parsed.products.length,0,JSON.stringify(patch));});
 check(()=>{for(const unit_info of["37 g","185 g"]){const r=capture({name:"Milka Tender Milch 5 x 37 g",unit_info,barcode_gtin:"7622400004483"});assert.equal(r.parsed.products.length,0);}const a=product({name:"Milka Tender Milch 5 x 37 g",unit_info:"5 x 37 g",barcode_gtin:"7622400004483"});assert(Service.validateArticle(a,{now}).ok);assert.equal(a.packAmount,37);assert.equal(a.packCount,5);});
 const mutations=[
  ["sourceId","Wolt nahkauf Berlin Wrangelstraße"],["merchant","nahkauf"],["scopeCountry","AT"],["scopeChannel","physical-store"],["locationScope","Berlin"],["nativeVenueId","0".repeat(24)],["nativeMarketId","561888"],["nativeAssortmentId","0".repeat(24)],["retailerSku","0".repeat(24)],["gtin","3017620422003"],["storeId","fake"],["truthEligible",true],["productId",4],["brand","invented"],["variant","invented"],["name","Different label"],["nativeUnitInfo","500 ml"],["pack","500 ml"],["packCount",2],["packAmount",Infinity],["packUnit","l"],["shop",{...p.shop,city:"Hamburg"}],["sourceUrl",Client.VENUE_URL+"?fresh=1"],["sourceResponseUrl",Client.VENUE_API_URL],["sourceResponseHash","A".repeat(64)],["venueSourceUrl",Client.VENUE_URL],["sourceResponseDate",new Date(base-16*60000).toISOString()],["sourceAgeSeconds",901],["venueSourceAgeSeconds",-1],["observedAt",new Date(now+1).toISOString()],["venueCapturedAt",new Date(base+1).toISOString()],["venueCapturedAt",new Date(base-31*60000).toISOString()],["current",true],["availability","available"],["price",1.79],["deposit",.15],["expiresAt",new Date(now+86400000).toISOString()]
 ];for(const[key,value]of mutations)check(()=>assert.equal(Service.validateArticle({...p,[key]:value},{now}).ok,false,key));
 for(const key of["currentPriceVerified","currentAvailabilityVerified","assortmentComplete","physicalStorePriceVerified","normalPriceClassificationVerified"])check(()=>assert.equal(Service.validateArticle({...p,[key]:true},{now}).ok,false,key));
 check(()=>{const r=clone(p);delete r.sourceAgeSeconds;assert.equal(Service.validateArticle(r,{now}).ok,false);});
 check(()=>{const r=clone(p);r.nativeWitness.venue.venue.city="Hamburg";assert.equal(Service.validateArticle(r,{now}).ok,false,"Flattened valid shop cannot override the original venue witness");});
 check(()=>{const r=clone(p);r.nativeWitness.item.barcode_gtin=1234567890123;assert.equal(Service.validateArticle(r,{now}).ok,false);});
 check(()=>{const r=clone(p);r.nativeWitness.item.unit_info="500 ml";assert.equal(Service.validateArticle(r,{now}).ok,false,"A native pack mismatch cannot be covered by a caller hash");});
 check(()=>{const other={...clone(p),sourceResponseUrl:Client.API_ORIGIN+Client.API_PATH+"/categories/slug/another-category",sourceResponseHash:"b".repeat(64),venueResponseHash:"c".repeat(64)};assert(Service.validateArticle(other,{now}).ok);const a=Service.rowForArticle(p),b=Service.rowForArticle(other);assert.equal(a.identity_hash,b.identity_hash,"Multiple category appearances are the same identity");assert.notEqual(a.capture_hash,b.capture_hash);assert.equal(a.witness_hash,b.witness_hash);assert.notEqual(a.source_response_hash,a.witness_hash,"Native response byte hash is not the minimal witness hash");});
 check(()=>{const q=Service.querySpec({search:"Milk%_",pack:"2 x 500 ml",limit:"200",offset:"10",now});assert(q.params.includes("%Milk\\%\\_%"));assert(q.params.includes(2));assert(q.params.includes(500));assert(!q.params.includes(1000));assert(q.sql.includes("held=false"));assert(!q.sql.includes("interval '24 hours'"));assert(!q.sql.includes("SELECT *"));});
 for(const options of[{limit:true},{limit:null},{limit:[]},{limit:201},{limit:0},{limit:"01"},{offset:null},{offset:"-1"},{offset:10001},{search:""},{merchant:""},{retailerSku:"fake"},{gtin:"0000000000001"},{scopeChannel:"store"},{pack:"ca. 1 kg"},{now:"2026-10-03"},{unapproved:1}])check(()=>assert.throws(()=>Service.querySpec(options),/invalid-/));
 check(()=>assert(Service.querySpec({scopeChannel:"pickup",now}).sql.includes("false")));
 const tx=Object.create(require("pg").Client.prototype),calls=[];tx.release=()=>{};tx.query=async(sql,params)=>{calls.push({sql,params});if(sql.includes("txid_current_if_assigned"))return{rows:[{transactionOpen:true}]};if(sql.startsWith("SELECT count(*)"))return{rows:[{count:0}]};return{rows:[],rowCount:sql.startsWith("INSERT INTO ")?1:0};};
 assert.equal(typeof tx.connect,"function");assert.equal(Object.hasOwn(tx,"connect"),false);const saved=await Service.persist(tx,[p],{now});check(()=>{assert.equal(saved.accepted,1);assert.equal(saved.priceRowsCreated,0);assert.equal(saved.canonicalProductsCreated,0);assert(calls[1].sql.includes("pg_advisory_xact_lock"));const inserted=calls.find(c=>c.sql.startsWith("INSERT INTO "));assert.equal(JSON.parse(inserted.params[0])[0].source_response_hash,p.sourceResponseHash);assert(!inserted.sql.includes("price_observations"));});
 await assert.rejects(()=>Service.persist({query:async()=>({rows:[]})},[p],{now}),/transaction-client-required/);groups++;
 tx.query=async()=>({rows:[{transactionOpen:false}]});await assert.rejects(()=>Service.persist(tx,[p],{now}),/open-writing-transaction-required/);groups++;
 const actualPool=new(require("pg").Pool)();await assert.rejects(()=>Service.persist(actualPool,[],{now}),/transaction-client-required/);await actualPool.end();groups++;
 const malformed={release(){},query:async(sql)=>({rows:sql.includes("txid_current_if_assigned")?[{transactionOpen:true}]:[]})};const refused=await Service.persist(malformed,[null,{}],{now});check(()=>{assert.equal(refused.rejected,2);assert.equal(refused.accepted,0);});
 let poolDDLs=0;const pool={connect(){},query:async()=>{poolDDLs++;return{rows:[]};}};await Service.ensure(pool);await Service.ensure(pool);check(()=>assert.equal(poolDDLs,1));
 let clientDDLs=0;tx.query=async()=>{clientDDLs++;return{rows:[]};};await Service.ensure(tx);await Service.ensure(tx);check(()=>assert.equal(clientDDLs,2,"Inherited connect does not make a PoolClient schema-cacheable"));
 let retryDDLs=0;const retry={connect(){},query:async()=>{if(++retryDDLs===1)throw Error("synthetic-ddl-error");return{rows:[]};}};await assert.rejects(()=>Service.ensure(retry),/synthetic-ddl-error/);await Service.ensure(retry);check(()=>assert.equal(retryDDLs,2));
 const recorded=row(p),publicResult=await Service.search(reader([recorded]),{now}),view=publicResult.items[0];check(()=>{assert(view);assert.equal(view.nativeWitness,undefined);assert.equal(view.storeId,undefined);assert.equal(view.currentPriceVerified,false);assert.equal(view.currentAvailabilityVerified,false);assert.equal(view.availability,"unknown");assert.equal(view.state,"last-observed");assert.equal(view.expiresAt,null);assert(Service.validateView(view,{now}).ok);assert.equal(Service.validateArticle(view,{now}).ok,false,"Public read metadata alone cannot authorize new native admission");});
 check(()=>{for(const patch of[{currentPriceVerified:true},{currentAvailabilityVerified:true},{physicalStorePriceVerified:true},{normalPriceClassificationVerified:true},{assortmentComplete:true},{nativeWitness:p.nativeWitness},{captureHash:null},{price:1.79}])assert.equal(Service.validateView({...view,...patch},{now}).ok,false);});
 const old=row(product({},now-30*86400000)),legacy=clone(p);legacy.name=legacy.nativeWitness.item.name="Milka Tender Milch 5 x 37 g";legacy.nativeUnitInfo=legacy.nativeWitness.item.unit_info="37 g";legacy.pack="37 g";legacy.packAmount=37;legacy.packUnit="g";legacy.packCount=1;
 const bad=row(legacy),held={...recorded,held:true},invalidHash={...recorded,capture_hash:"0".repeat(64)},future=row(product({},now+1)),rows=[old,bad,held,invalidHash,future];const status=await Service.status(reader(rows),{now}),search=await Service.search(reader(rows),{now});check(()=>{assert.equal(status.storedArticles,5);assert.equal(status.heldArticles,1);assert.equal(status.excludedInvalidArticles,3);assert.equal(status.lastObservedArticles,1);assert.equal(status.lastObservedAt,old.observed_at);assert.equal(search.items.length,1);assert.equal(search.items[0].recentlyObserved,false);assert.equal(search.items[0].observedAt,old.observed_at);assert.equal(status.storedArticles,status.heldArticles+status.excludedInvalidArticles+status.lastObservedArticles);});
 const reordered=clone(recorded);reordered.native_witness=Object.fromEntries(Object.entries(reordered.native_witness).reverse());reordered.shop=Object.fromEntries(Object.entries(reordered.shop).reverse());check(()=>assert.equal(Service.serializationHash(recorded.native_witness),Service.serializationHash(reordered.native_witness)));assert.equal((await Service.search(reader([reordered]),{now})).items.length,1);groups++;
 const tieCalls=[],a=product({unit_info:"2 x 500 ml"}),ties={release(){},query:async(sql,params)=>{tieCalls.push({sql,params});if(sql.includes("txid_current_if_assigned"))return{rows:[{transactionOpen:true}]};if(sql.startsWith("SELECT count(*)"))return{rows:[{count:1}]};return{rows:[],rowCount:sql.startsWith("INSERT INTO ")?1:0};}};const tie=await Service.persist(ties,[p,p,a],{now});check(()=>{assert.equal(tie.duplicates,1);assert.equal(tie.heldArticles,1);assert.equal(tie.accepted,0);const data=JSON.parse(tieCalls.find(c=>c.sql.startsWith("INSERT INTO ")).params[0])[0];assert.equal(data.held,true);assert.notEqual(data.conflict_capture.identity_hash,data.identity_hash);assert.equal(data.conflict_capture.observed_at,data.observed_at);});
 const replayCalls=[],retimed={...clone(p),observedAt:new Date(base+1000).toISOString(),venueCapturedAt:new Date(base+1000).toISOString(),venueResponseDate:new Date(base+1000).toISOString(),venueResponseHash:"f".repeat(64)},replayTx={release(){},query:async(sql,params)=>{replayCalls.push({sql,params});if(sql.includes("txid_current_if_assigned"))return{rows:[{transactionOpen:true}]};return{rows:sql.startsWith("SELECT retailer_sku")?[recorded]:[]};}};assert(Service.validateArticle(retimed,{now}).ok);const replay=await Service.persist(replayTx,[retimed],{now});check(()=>{assert.equal(replay.accepted,0);assert.equal(replay.rejected,1);assert.equal(replay.reasons["original-capture-replay-retimed"],1);assert(!replayCalls.some(c=>c.sql.startsWith("INSERT INTO ")),"Fresh venue proof cannot renew the identical item original");});
 const genuine=product({},base+1000);const genuineTx={release(){},query:async(sql)=>{if(sql.includes("txid_current_if_assigned"))return{rows:[{transactionOpen:true}]};if(sql.startsWith("SELECT retailer_sku"))return{rows:[recorded]};if(sql.startsWith("SELECT count(*)"))return{rows:[{count:0}]};return{rows:[],rowCount:sql.startsWith("INSERT INTO ")?1:0};}};check(()=>assert.equal(genuine.sourceResponseHash,p.sourceResponseHash,"A genuinely new item GET may have the same bytes"));const genuineSaved=await Service.persist(genuineTx,[genuine],{now});check(()=>assert.equal(genuineSaved.upserted,1,"A newer original HTTP Date distinguishes a real new item response"));
 const filteredPage=await Service.search(reader(Array.from({length:50},(_,i)=>i===0?recorded:invalidHash)),{now,offset:100});check(()=>{assert.equal(filteredPage.items.length,1);assert.equal(filteredPage.scannedRows,50);assert.equal(filteredPage.nextOffset,150);assert.equal(filteredPage.hasMore,true,"Reader exclusions must not conceal the next raw SQL page");});
 console.log(`wolt-retailer-article-service: ${groups} groups passed; price-independent original native identities, exact sales packs, separated venue/item proof clocks, latest-only held/replay protection, genuine client/schema guards and identical search/status revalidation`);
}
main().catch(error=>{console.error(error);process.exitCode=1;});
