"use strict";
const assert=require("node:assert/strict"),{Pool}=require("pg"),Wolt=require("../wolt-retailer-price-service"),Refresh=require("../wolt-retailer-price-refresh"),Venues=require("../wolt-retailer-venues"),Inventory=require("../published-retailer-inventory");
const Schema=require("../retailer-schema-lifecycle"),SalesPack=require("../wolt-sales-pack-validation");
function gtin(index){const body=String(989000000000+index),sum=[...body].reduce((n,d,i)=>n+Number(d)*(i%2?3:1),0);return body+(10-sum%10)%10;}
async function main(){
 const connectionString=process.env.DATABASE_URL;assert(connectionString,"DATABASE_URL is required");const database=new URL(connectionString);assert.equal(database.hostname,"localhost");assert(database.pathname.endsWith("_test"),"Only a dedicated local test database is allowed");
 const pool=new Pool({connectionString,ssl:false,connectionTimeoutMillis:5000}),now=Date.now(),edeka=Wolt.createService("edekaBerlin"),nahkauf=Wolt.createService("nahkaufWrangelBerlin"),edekaRefresh=Refresh.createRefresh("edekaBerlin"),nahkaufRefresh=Refresh.createRefresh("nahkaufWrangelBerlin"),shared=gtin(1);let api;
 const fixture=(key,index,price,patch={})=>{const service=key==="edekaBerlin"?edeka:nahkauf,profile=Venues.resolve(key),sku=(880000+index).toString(16).padStart(24,"0");return{sourceId:service.SOURCE,merchant:service.MERCHANT,nativeVenueId:service.VENUE.nativeVenueId,retailerSku:sku,gtin:shared,name:"POSTGRES TEST multi-market milk "+index,brand:"POSTGRES TEST",pack:"1 l",packAmount:1,packUnit:"l",packCount:1,price,deposit:0,displayedPrice:price,nativePriceEUR:price,nativePriceIncludesDeposit:true,payablePackPrice:price,depositIncludedInDisplayedPrice:true,currency:"EUR",priceType:"unknown",promotionStatus:"unknown",availability:"unknown",capturedAt:new Date(now-1000).toISOString(),proofHash:"7".repeat(64),sourceResponseHash:"7".repeat(64),sourceUrl:"https://wolt.com/de/deu/berlin/venue/"+profile.slug,sourceResponseUrl:"https://consumer-api.wolt.com/consumer-api/consumer-assortment/v1/venues/slug/"+profile.slug+"/assortment/categories/slug/test-native-category",shop:{...service.VENUE,address:profile.address},scopeCountry:"DE",scopeChannel:"online",...patch};};
 try{
  const exists=async table=>!!(await pool.query("SELECT to_regclass($1) AS name",["public."+table])).rows[0].name,baseline={};for(const table of["products","stores","price_observations","receipts","receipt_submissions"])baseline[table]=await exists(table)?(await pool.query("SELECT count(*)::int AS count FROM "+table)).rows[0].count:null;
  await Inventory.status(pool,{now});for(const table of["retailer_published_prices","rewe_retailer_published_prices","aldi_assortment_published_prices"])baseline[table]=(await pool.query("SELECT count(*)::int AS count FROM "+table)).rows[0].count;
  assert.equal(edeka.TABLE,nahkauf.TABLE,"All approved Wolt venues share the existing price ledger");
  // Recreate the former three EDEKA-only column checks in a rollback-only transaction.
  // Real migration must keep every EDEKA record and admit only the approved coupled identities.
  const migration=await pool.connect();try{
   await migration.query("BEGIN");await edeka.ensure(migration);await migration.query("DELETE FROM "+edeka.TABLE+" WHERE source_id=$1",[nahkauf.SOURCE]);
   assert.equal((await edeka.persist(migration,[fixture("edekaBerlin",999,1.99,{gtin:gtin(999)})],{now})).accepted,1);
   const oldRecords=(await migration.query("SELECT to_jsonb(p) AS row FROM "+edeka.TABLE+" p WHERE source_id=$1 ORDER BY native_venue_id,retailer_sku",[edeka.SOURCE])).rows;assert(oldRecords.length>0);
   const checks=(await migration.query("SELECT conname,pg_get_constraintdef(oid) AS definition FROM pg_constraint WHERE conrelid=$1::regclass AND contype='c'",[edeka.TABLE])).rows;
   for(const check of checks.filter(c=>/source_id/.test(c.definition)&&/merchant/.test(c.definition)&&/native_venue_id/.test(c.definition)))await migration.query('ALTER TABLE '+edeka.TABLE+' DROP CONSTRAINT "'+check.conname.replace(/"/g,'""')+'"');
   for(const field of["source_id","merchant","native_venue_id"])await migration.query("ALTER TABLE "+edeka.TABLE+" DROP CONSTRAINT IF EXISTS "+edeka.TABLE+"_"+field+"_check");
   await migration.query("ALTER TABLE "+edeka.TABLE+" ADD CONSTRAINT "+edeka.TABLE+"_source_id_check CHECK(source_id='Wolt EDEKA Berlin'),ADD CONSTRAINT "+edeka.TABLE+"_merchant_check CHECK(merchant='EDEKA'),ADD CONSTRAINT "+edeka.TABLE+"_native_venue_id_check CHECK(native_venue_id='67ebb70ed3581534a525c522')");
   Schema.reset(migration,edeka.TABLE); // The fixture deliberately replaced the initialized schema.
   await nahkauf.ensure(migration);
   const migratedRecords=(await migration.query("SELECT to_jsonb(p) AS row FROM "+edeka.TABLE+" p WHERE source_id=$1 ORDER BY native_venue_id,retailer_sku",[edeka.SOURCE])).rows;assert.deepEqual(migratedRecords,oldRecords,"Venue migration must preserve existing EDEKA rows and their proof/capture metadata");
   const coupled=(await migration.query("SELECT pg_get_constraintdef(oid) AS definition FROM pg_constraint WHERE conrelid=$1::regclass AND contype='c'",[edeka.TABLE])).rows.find(c=>/source_id/.test(c.definition)&&/merchant/.test(c.definition)&&/native_venue_id/.test(c.definition));assert(coupled,"A coupled source/merchant/venue constraint is mandatory");assert(coupled.definition.includes(edeka.SOURCE));assert(coupled.definition.includes(nahkauf.SOURCE));assert(coupled.definition.includes(edeka.VENUE.nativeVenueId));assert(coupled.definition.includes(nahkauf.VENUE.nativeVenueId));
   assert.equal((await nahkauf.persist(migration,[fixture("nahkaufWrangelBerlin",999,2.19,{gtin:gtin(999)})],{now})).accepted,1);
  }finally{await migration.query("ROLLBACK");Schema.reset(migration,edeka.TABLE);migration.release();}
  const before=await Inventory.status(pool,{now}),beforeE=await edeka.status(pool,{now}),beforeN=await nahkauf.status(pool,{now}),eQuote=fixture("edekaBerlin",1,2.04),nQuote=fixture("nahkaufWrangelBerlin",1,2.56);
  assert.equal((await edeka.persist(pool,[eQuote],{now})).accepted,1);assert.equal((await nahkauf.persist(pool,[nQuote],{now})).accepted,1);
  assert.equal((await edeka.persist(pool,[eQuote],{now})).unchanged,1);assert.equal((await nahkauf.persist(pool,[nQuote],{now})).unchanged,1);
  const stored=(await pool.query("SELECT source_id,merchant,native_venue_id,price::float AS price,gtin FROM "+edeka.TABLE+" WHERE gtin=$1 ORDER BY price",[shared])).rows;assert.equal(stored.length,2,"The same native SKU and GTIN in two venues must retain both market quotes");assert.deepEqual(stored.map(row=>row.price),[2.04,2.56]);assert.notEqual(stored[0].source_id,stored[1].source_id);assert.notEqual(stored[0].native_venue_id,stored[1].native_venue_id);
  const after=await Inventory.status(pool,{now}),afterE=await edeka.status(pool,{now}),afterN=await nahkauf.status(pool,{now});assert.equal(after.currentPrices,before.currentPrices+2);assert.equal(after.productsWithCurrentPublishedPrices,before.productsWithCurrentPublishedPrices+1,"Two Wolt market quotes must contribute one GTIN to the composite union");assert.equal(afterE.currentPrices,beforeE.currentPrices+1);assert.equal(afterN.currentPrices,beforeN.currentPrices+1);assert.equal(afterE.productsWithCurrentPublishedPrices,beforeE.productsWithCurrentPublishedPrices+1);assert.equal(afterN.productsWithCurrentPublishedPrices,beforeN.productsWithCurrentPublishedPrices+1);
  const all=await Inventory.search(pool,{gtin:shared,now});assert.equal(all.items.length,2);for(const[service,price]of[[edeka,2.04],[nahkauf,2.56]]){const found=await service.search(pool,{gtin:shared,now});assert.equal(found.items.length,1);assert.equal(found.items[0].price,price);assert.equal(found.items[0].sourceId,service.SOURCE);assert.equal(found.items[0].nativeVenueId,service.VENUE.nativeVenueId);assert.equal(found.items[0].truthEligible,false);assert.equal(found.items[0].shippingIncluded,false);assert.equal(found.items[0].serviceFeesIncluded,false);assert(!("storeId"in found.items[0]));assert.equal((await service.search(pool,{nativeVenueId:service===edeka?nahkauf.VENUE.nativeVenueId:edeka.VENUE.nativeVenueId,gtin:shared,now})).items.length,0);}
  assert.equal((await Inventory.search(pool,{merchant:"nahkauf",gtin:shared,now})).items.length,1);assert.equal((await Inventory.search(pool,{merchant:"EDEKA",gtin:shared,now})).items.length,1);
  const badMix=await nahkauf.persist(pool,[{...nQuote,sourceId:edeka.SOURCE},{...nQuote,merchant:edeka.MERCHANT},{...nQuote,nativeVenueId:edeka.VENUE.nativeVenueId},{...nQuote,shop:eQuote.shop},{...nQuote,sourceUrl:eQuote.sourceUrl},{...nQuote,sourceResponseUrl:eQuote.sourceResponseUrl},{...nQuote,storeId:"invented"}],{now});assert.equal(badMix.accepted,0);assert.equal(badMix.rejected,7);
  for(const[assignment,value]of[["merchant=$2",edeka.MERCHANT],["native_venue_id=$2",edeka.VENUE.nativeVenueId],["source_id=$2",edeka.SOURCE]])await assert.rejects(()=>pool.query("UPDATE "+edeka.TABLE+" SET "+assignment+" WHERE source_id=$1 AND retailer_sku=$3",[nahkauf.SOURCE,value,nQuote.retailerSku]),error=>error.code==="23514","Database must reject valid-looking identities combined from different approved markets");
  const checkpoint=await pool.connect();try{
   await checkpoint.query("BEGIN");await edekaRefresh.ensure(checkpoint);await checkpoint.query("DELETE FROM wolt_retailer_catalog_state WHERE source_id=ANY($1::text[])",[[edeka.SOURCE,nahkauf.SOURCE]]);
   function batch(service,page){const hash=service===edeka?"4".repeat(64):"5".repeat(64),cursor={version:1,nativeVenueId:service.VENUE.nativeVenueId,nativeAssortmentId:service===edeka?"a".repeat(24):"b".repeat(24),assortmentHash:hash,categoryIndex:page-1,pageToken:null,pageNumber:1,received:page,pagesFetched:page};return{offers:[],rejected:[],complete:false,categoryCount:3,categoriesCompleted:page-1,pagesFetched:page,received:1,receivedCumulative:page,assortmentHash:hash,nextCursor:cursor,requests:3};}
   await edekaRefresh.refresh({pool:checkpoint,now:()=>now},{fetchOffers:async()=>batch(edeka,1)});await nahkaufRefresh.refresh({pool:checkpoint,now:()=>now},{fetchOffers:async()=>batch(nahkauf,1)});
   const eState=await edekaRefresh.load(checkpoint),nState=await nahkaufRefresh.load(checkpoint);assert.equal(eState.cursor.nativeVenueId,edeka.VENUE.nativeVenueId);assert.equal(nState.cursor.nativeVenueId,nahkauf.VENUE.nativeVenueId);
   await assert.rejects(()=>edekaRefresh.refresh({pool:checkpoint,now:()=>now},{fetchOffers:async()=>{throw Object.assign(Error("wolt-source-http-429"),{retryAfterMs:7200000});}}),/429/);
   await nahkaufRefresh.refresh({pool:checkpoint,now:()=>now},{fetchOffers:async options=>{assert.deepEqual(options.cursor,nState.cursor);return batch(nahkauf,2);}});
   const eAfter=await edekaRefresh.status(checkpoint),nAfter=await nahkaufRefresh.status(checkpoint);assert.equal(eAfter.lastError,"wolt-source-http-429");assert.equal(new Date(eAfter.retryAfter).getTime(),now+7200000);assert.deepEqual(eAfter.cursor,eState.cursor);assert.equal(nAfter.lastError,null);assert.equal(nAfter.pagesFetched,2);assert.equal(nAfter.nativeVenueId,nahkauf.VENUE.nativeVenueId);assert.equal(nAfter.publishedAssortmentComplete,false);assert.equal(nAfter.physicalStoreAssortmentVerified,false);assert.equal(await edekaRefresh.resumeAt(checkpoint,now),new Date(now+7200000).toISOString());
  }finally{await checkpoint.query("ROLLBACK");checkpoint.release();}
  const packMigration=await pool.connect();try{
   await packMigration.query("BEGIN");const legacyGTIN=gtin(55),legacy=fixture("nahkaufWrangelBerlin",55,4.2,{gtin:legacyGTIN,name:"POSTGRES TEST legacy snack",pack:"37 g",packAmount:37,packUnit:"g"});assert.equal((await nahkauf.persist(packMigration,[legacy],{now})).accepted,1);
   await packMigration.query("UPDATE "+nahkauf.TABLE+" SET name='Milka Tender Milch, 5 x 37 g' WHERE source_id=$1 AND retailer_sku=$2",[nahkauf.SOURCE,legacy.retailerSku]);const retained=(await packMigration.query("SELECT to_jsonb(p) AS row FROM "+nahkauf.TABLE+" p WHERE source_id=$1 AND retailer_sku=$2",[nahkauf.SOURCE,legacy.retailerSku])).rows[0].row;
   assert.equal(retained.validation_issue,null);
   assert.equal((await nahkauf.search(packMigration,{gtin:legacyGTIN,now})).items.length,0,"A later unsafe row is excluded without rerunning DDL or historical quarantine");
   assert.equal((await Inventory.search(packMigration,{gtin:legacyGTIN,now})).items.length,0);assert.equal((await Inventory.status(packMigration,{now})).productsWithCurrentPublishedPrices,after.productsWithCurrentPublishedPrices,"A later unquarantined conflict must not inflate the current GTIN union");
   const unsafeStatus=await nahkauf.status(packMigration,{now});assert(unsafeStatus.excludedPackConflicts>=1);assert.equal(unsafeStatus.currentPrices,afterN.currentPrices);
   assert.equal((await packMigration.query("SELECT validation_issue FROM "+nahkauf.TABLE+" WHERE source_id=$1 AND retailer_sku=$2",[nahkauf.SOURCE,legacy.retailerSku])).rows[0].validation_issue,null,"Read safety does not depend on repeated modifying quarantine queries");
   Schema.reset(packMigration,nahkauf.TABLE); // Explicitly exercise the historical migration again.
   await nahkauf.ensure(packMigration);const excluded=(await packMigration.query("SELECT to_jsonb(p) AS row FROM "+nahkauf.TABLE+" p WHERE source_id=$1 AND retailer_sku=$2",[nahkauf.SOURCE,legacy.retailerSku])).rows[0].row;assert.equal(excluded.validation_issue,"wolt-native-sales-pack-conflict");delete retained.validation_issue;delete excluded.validation_issue;assert.deepEqual(excluded,retained,"Pack exclusion must retain native identity, price, proof and real capture/expiry unchanged");
   assert.equal((await nahkauf.search(packMigration,{gtin:legacyGTIN,now})).items.length,0);assert.equal((await Inventory.search(packMigration,{gtin:legacyGTIN,now})).items.length,0);assert.equal((await Inventory.status(packMigration,{now})).productsWithCurrentPublishedPrices,after.productsWithCurrentPublishedPrices,"Excluded legacy pack conflicts cannot inflate the distinct GTIN union");assert((await nahkauf.status(packMigration,{now})).excludedPackConflicts>=1);
   const repaired={...legacy,name:"Milka Tender Milch, 5 x 37 g",pack:"5 x 37 g",packAmount:37,packCount:5,capturedAt:new Date(now-500).toISOString()};assert.equal((await nahkauf.persist(packMigration,[repaired],{now})).accepted,1);assert.equal((await nahkauf.search(packMigration,{gtin:legacyGTIN,now})).items.length,1,"Only a real newer consistent quote may reenter the inventory");assert.equal((await packMigration.query("SELECT validation_issue FROM "+nahkauf.TABLE+" WHERE source_id=$1 AND retailer_sku=$2",[nahkauf.SOURCE,legacy.retailerSku])).rows[0].validation_issue,null);
  }finally{await packMigration.query("ROLLBACK");Schema.reset(packMigration,nahkauf.TABLE);packMigration.release();}

  // Same total with unknown inner count must be held before migration and in all SQL counts.
  const structureMigration=await pool.connect();try{
   await structureMigration.query("BEGIN");const structureGTIN=gtin(56),legacy=fixture("edekaBerlin",56,2.59,{gtin:structureGTIN,name:"POSTGRES TEST structure plain yoghurt",pack:"600 g",packAmount:600,packUnit:"g",packCount:1});assert.equal((await edeka.persist(structureMigration,[legacy],{now})).accepted,1);
   const structuredBefore=await Inventory.status(structureMigration,{now});
   await structureMigration.query("UPDATE "+edeka.TABLE+" SET name='POSTGRES TEST structure yoghurt 4 x 150 g' WHERE source_id=$1 AND retailer_sku=$2",[edeka.SOURCE,legacy.retailerSku]);
   const retained=(await structureMigration.query("SELECT to_jsonb(p) AS row FROM "+edeka.TABLE+" p WHERE source_id=$1 AND retailer_sku=$2",[edeka.SOURCE,legacy.retailerSku])).rows[0].row;assert.equal(retained.validation_issue,null);
   assert.equal((await edeka.search(structureMigration,{gtin:structureGTIN,now})).items.length,0);assert.equal((await Inventory.search(structureMigration,{gtin:structureGTIN,now})).items.length,0);assert.equal((await Inventory.status(structureMigration,{now})).productsWithCurrentPublishedPrices,structuredBefore.productsWithCurrentPublishedPrices-1);assert((await edeka.status(structureMigration,{now})).excludedPackStructures>=1);
   Schema.reset(structureMigration,edeka.TABLE);await edeka.ensure(structureMigration);const held=(await structureMigration.query("SELECT to_jsonb(p) AS row FROM "+edeka.TABLE+" p WHERE source_id=$1 AND retailer_sku=$2",[edeka.SOURCE,legacy.retailerSku])).rows[0].row;assert.equal(held.validation_issue,"wolt-native-sales-pack-structure-unresolved");delete retained.validation_issue;delete held.validation_issue;assert.deepEqual(held,retained,"Holding structure preserves price, GTIN/SKU, original proof/capture/expiry");
   const native={...legacy,name:"POSTGRES TEST structure yoghurt 4 x 150 g",pack:"4 x 150 g",packAmount:150,packCount:4,capturedAt:new Date(now-500).toISOString()};assert.equal((await edeka.persist(structureMigration,[native],{now})).accepted,1);assert.equal((await edeka.search(structureMigration,{gtin:structureGTIN,pack:"4 x 150 g",now})).items.length,1);assert.equal((await edeka.search(structureMigration,{gtin:structureGTIN,pack:"600 g",now})).items.length,0,"Exact single and multipack queries remain different");
   for(const[name,amount,unit,count]of[["Joghurt 4 x 150 g",600,"g",1],["Joghurt 4 x 150 g",150,"g",4],["Joghurt 4 x 150 g",100,"g",6],["Joghurt ４ × １５０ ｇ",150,"g",4],["Joghurt 4 x 0,15 kg",150,"g",4],["Wasser 6 X 50 CL",3000,"ml",1],["Tücher 3 x 4 Stück",4,"piece",3],["Joghurt 4 x 150 g",149.85,"g",4],["Joghurt 4 x 150 g",149.84,"g",4],["SYNTHETIC zero amount 1 x 0 g",.001,"g",1],["Dose 20 x 30 cm, 37 g",37,"g",1],["Snack 2,5x37g",37,"g",1],["Snack 5x37grams",37,"g",1],["Joghurt 4 x 150 g und 6 x 100 g",150,"g",4]]){
    const result=(await structureMigration.query("SELECT "+SalesPack.SQL_STRUCTURE_UNRESOLVED+" AS unresolved FROM (SELECT $1::text AS name,$2::numeric AS pack_amount,$3::text AS pack_unit,$4::int AS pack_count) p",[name,amount,unit,count])).rows[0];assert.equal(result.unresolved,SalesPack.structureUnresolved(name,amount,unit,count),"PostgreSQL/native/browser structure parity: "+name);
   }
  }finally{await structureMigration.query("ROLLBACK");Schema.reset(structureMigration,edeka.TABLE);structureMigration.release();}
  process.env.PORT="0";api=require("../server");await new Promise((resolve,reject)=>{api.server.once("error",reject);api.server.listen(0,"127.0.0.1",()=>{api.server.off("error",reject);resolve();});});const base="http://127.0.0.1:"+api.server.address().port;
  const finderResponse=await fetch(base+"/v1/published-products?search="+encodeURIComponent("POSTGRES TEST multi-market milk 1"),{signal:AbortSignal.timeout(10000)}),finder=await finderResponse.json();assert.equal(finderResponse.status,200,JSON.stringify(finder));assert.equal(finder.ok,true);assert.equal(finder.items.length,1);const selected=finder.items[0];assert.equal(selected.gtin,shared);assert.equal(selected.packAmount,1000);assert.equal(selected.packUnit,"ml");assert.equal(selected.packCount,1);assert.equal(selected.offers.length,2,"Name search must offer the exact product without requiring its EAN, while preserving both market prices");assert.equal(finder.requiresProductSelection,true);assert.equal(finder.physicalStorePrices,false);assert(!selected.productId&&!selected.storeId&&!selected.price);for(const path of["/v1/published-products","/v1/published-products?search=x","/v1/published-products?search=Milch&limit=21"])assert.equal((await fetch(base+path,{signal:AbortSignal.timeout(10000)})).status,400,"Unbounded/invalid product discovery must fail");
  const response=await fetch(base+"/v1/current-prices",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({gtin:shared,pack:"1 l",merchants:["EDEKA","nahkauf"]}),signal:AbortSignal.timeout(10000)}),compared=await response.json();assert.equal(response.status,200,JSON.stringify(compared));const alternatives=compared.publishedAlternatives.filter(row=>[edeka.SOURCE,nahkauf.SOURCE].includes(row.sourceId));assert.equal(alternatives.length,2);assert.deepEqual(alternatives.map(row=>row.price).sort((a,b)=>a-b),[2.04,2.56]);assert(compared.results.every(row=>row.state==="unknown"&&row.price===null),"Wolt online evidence must not create a physical shelf price");
  const statusResponse=await fetch(base+"/v1/published-prices/status",{signal:AbortSignal.timeout(10000)}),publicStatus=await statusResponse.json();assert.equal(statusResponse.status,200,JSON.stringify(publicStatus));assert.equal(publicStatus.retailers.woltEdekaBerlin.currentPrices,afterE.currentPrices);assert.equal(publicStatus.retailers.woltNahkaufWrangelBerlin.currentPrices,afterN.currentPrices);assert.equal(publicStatus.retailerResearch.woltEdekaBerlin.nativeVenueId,edeka.VENUE.nativeVenueId);assert.equal(publicStatus.retailerResearch.woltNahkaufWrangelBerlin.nativeVenueId,nahkauf.VENUE.nativeVenueId);assert.equal(publicStatus.retailerResearch.woltNahkaufWrangelBerlin.physicalStoreAssortmentVerified,false);assert.equal(publicStatus.retailerResearch.woltNahkaufWrangelBerlin.independentOfUserReceipts,true);

  const unsafeHTTP=fixture("edekaBerlin",57,2.59,{gtin:gtin(57),name:"POSTGRES TEST HTTP structure",pack:"600 g",packAmount:600,packUnit:"g"});
  try{
   assert.equal((await edeka.persist(pool,[unsafeHTTP],{now})).accepted,1);await pool.query("UPDATE "+edeka.TABLE+" SET name='POSTGRES TEST HTTP structure 4 x 150 g' WHERE source_id=$1 AND retailer_sku=$2",[edeka.SOURCE,unsafeHTTP.retailerSku]);
   for(const suffix of["/v1/published-products?search=POSTGRES%20TEST%20HTTP%20structure","/v1/berlin-reference-prices?gtin="+unsafeHTTP.gtin]){const res=await fetch(base+suffix,{signal:AbortSignal.timeout(10000)}),body=await res.json();assert.equal(res.status,200,JSON.stringify(body));assert.equal(body.items.length,0,"Unknown native structure cannot enter product discovery or Berliner prices");}
   const res=await fetch(base+"/v1/current-prices",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({gtin:unsafeHTTP.gtin,pack:"600 g",merchants:["EDEKA"]}),signal:AbortSignal.timeout(10000)}),body=await res.json();assert.equal(res.status,200,JSON.stringify(body));assert.equal(body.publishedAlternatives.length,0);assert(body.results.every(row=>row.state==="unknown"&&row.price===null));
  }finally{await pool.query("DELETE FROM "+edeka.TABLE+" WHERE source_id=$1 AND retailer_sku=$2",[edeka.SOURCE,unsafeHTTP.retailerSku]);}
  for(const[table,count]of Object.entries(baseline)){if(count===null)assert.equal(await exists(table),false,"Multi-market Wolt evidence must not create "+table);else assert.equal((await pool.query("SELECT count(*)::int AS count FROM "+table)).rows[0].count,count,"Multi-market Wolt evidence must not mutate "+table);}
  console.log("wolt-multi-market-postgres: preserved EDEKA-only constraint migration, coupled venue/source SQL allowlist, two independent price quotes/one GTIN, isolated checkpoints/cooldowns, original-preserving aggregate-structure holding, PostgreSQL/browser parity and filtered discovery/reference/current HTTP alternatives and unchanged physical/receipt/other ledgers OK");
 }finally{if(api){if(api.server.listening)await new Promise((resolve,reject)=>api.server.close(error=>error?reject(error):resolve()));await api.closeDb();}await pool.end();}
}
main().catch(error=>{console.error(error);process.exitCode=1;});
