"use strict";
const assert=require("assert/strict"),crypto=require("crypto"),Client=require("../wolt-retailer-price-client"),Service=require("../wolt-retailer-price-service"),fixture=require("./fixtures/retailers/wolt-edeka-berlin.json");
const now=()=>fixture.capturedAt,clone=x=>structuredClone(x),html=state=>'<script type="application/json" class="query-state">'+JSON.stringify(state)+'</script>',url=Client.API_ORIGIN+Client.API_PATH;
function response(value,type="json",headers={},status=200){const body=type==="html"?value:JSON.stringify(value);return{status,headers:{get:key=>({"content-type":type==="html"?"text/html":"application/json",...headers})[key.toLowerCase()]??null},text:async()=>body};}
function source(overrides={}){const calls=[];return{calls,fetch:async(address,options)=>{calls.push({address,options});if(overrides[address])return overrides[address];if(address===Client.VENUE_URL)return response(html(fixture.venueState),"html");if(address===url)return response(fixture.listing);const category=new URL(address).pathname.split("/").pop(),page=new URL(address).searchParams.has("page_token")?2:1;const raw=fixture.pages.find(x=>x.category.slug===category&&x.metadata.page===page);assert(raw,address);return response(raw)}};}
async function main(){
 const shop=Client.parseVenue(html(fixture.venueState),{capturedAt:fixture.capturedAt});assert.equal(shop.city,"Berlin");assert.equal(shop.nativeMarketId,"800401");assert.equal(shop.postalCode,"10969");
 const changed=clone(fixture.venueState);changed.queries[0].state.data.venue.post_code="10117";assert.throws(()=>Client.parseVenue(html(changed),{capturedAt:fixture.capturedAt}),/identity-conflict/);
 const stale=clone(fixture.venueState);stale.queries[0].state.dataUpdatedAt-=16*60000;assert.throws(()=>Client.parseVenue(html(stale),{capturedAt:fixture.capturedAt}),/stale-or-future/);
 for(const bad of["https://example.test/","https://consumer-api.wolt.com/consumer-api/consumer-assortment/v1/venues/slug/other/assortment",url+"?page_token=bad","https://wolt.com/de/deu/berlin/venue/edeka-hilbrecht?bypass=1"])assert.throws(()=>Client.allowedUrl(bad),/not-allowed/);
 const transport=source(),first=await Client.fetchOffers({maxRequests:3,pauseMs:0,now},transport.fetch);assert.equal(first.complete,false);assert.equal(first.categoriesCompleted,1);assert.equal(first.categoryCount,2);assert.equal(first.received,2);assert.equal(first.nextCursor.categoryIndex,1);assert(first.offers.length>0);assert.equal(first.physicalStoreAssortmentVerified,false);
 const second=await Client.fetchOffers({maxRequests:3,pauseMs:0,now,cursor:first.nextCursor},transport.fetch);assert.equal(second.complete,false);assert.equal(second.nextCursor.pageNumber,2);assert(second.nextCursor.pageToken);assert.equal(second.categoriesCompleted,1);
 const third=await Client.fetchOffers({maxRequests:3,pauseMs:0,now,cursor:second.nextCursor},transport.fetch);assert.equal(third.complete,true);assert.equal(third.nextCursor,null);assert.equal(third.categoriesCompleted,2);assert.equal(third.pagesFetched,3);assert.equal(third.receivedCumulative,6);assert.equal(third.publishedAssortmentComplete,true);assert.equal(third.fullAssortmentVerified,false);assert.equal(transport.calls.length,9);assert(transport.calls.at(-1).address.includes("page_token="));
 for(const offer of[...first.offers,...second.offers,...third.offers]){const checked=Service.validateOffer(offer,{now:Date.parse(fixture.capturedAt)});assert.equal(checked.ok,true,JSON.stringify(checked.reasons));assert.equal(checked.offer.truthEligible,false);assert.equal(offer.scopeChannel,"online");assert.equal(offer.priceType,"unknown");assert.equal(offer.proofHash,offer.sourceResponseHash);}
 for(const call of transport.calls){assert.equal(call.options.redirect,"error");assert.equal(call.options.credentials,"omit");assert.equal(call.options.method,"GET");assert(!call.options.headers.Cookie);}
 const native=clone(fixture.pages[1].items[0]);native.price=204;native.deposit={amount:15,label:"MEHRWEG"};native.unit_info="1 l";native.unit_price={base:1,price:189,unit:"liter"};native.original_price=null;const parsed=Client.parseItems([native],{shop,capturedAt:fixture.capturedAt,sourceResponseUrl:url+"/categories/slug/"+fixture.pages[1].category.slug,sourceResponseHash:"a".repeat(64)});assert.equal(parsed.offers[0].price,1.89);assert.equal(parsed.offers[0].deposit,.15);assert.equal(parsed.offers[0].displayedPrice,2.04);
 for(const patch of[{price:0},{unit_info:"ca. 1 kg"},{barcode_gtin:"0000000000001"},{sell_by_weight_config:{}},{options:[{}]},{variant:{}},{is_wolt_plus_only:true},{deposit:{amount:999,label:"wrong"}},{min_quantity_per_purchase:2}])assert.equal(Client.parseItems([{...native,...patch}],{shop,capturedAt:fixture.capturedAt,sourceResponseUrl:url,sourceResponseHash:"a".repeat(64)}).offers.length,0);
 for(const [headers,reason]of[[{age:"901"},"cache-age"],[{date:"Thu, 01 Oct 2026 00:00:00 GMT"},"response-date"]]){const src=source({[url]:response(fixture.listing,"json",headers)});await assert.rejects(()=>Client.fetchOffers({maxRequests:3,pauseMs:0,now},src.fetch),new RegExp(reason));assert.equal(src.calls.length,2);}
 const throttled=source({[url]:response({},"json",{"retry-after":"600"},429)});await assert.rejects(()=>Client.fetchOffers({pauseMs:0,now},throttled.fetch),error=>error.status===429&&error.retryAfterMs===600000);assert.equal(throttled.calls.length,2,"429 cannot trigger retries or another endpoint");
 const badCursor={...first.nextCursor,assortmentHash:"b".repeat(64)};await assert.rejects(()=>Client.fetchOffers({pauseMs:0,now,cursor:badCursor},source().fetch),/cursor-conflict/);
 const wrongPage=clone(fixture.pages[0]);wrongPage.metadata.page=2;const bad=source({[url+"/categories/slug/"+wrongPage.category.slug]:response(wrongPage)});await assert.rejects(()=>Client.fetchOffers({pauseMs:0,now},bad.fetch),/page-conflict/);
 console.log("wolt-retailer-price-client: native Berlin identity, every category and opaque next page through bounded continuation, service-compatible GTIN/pack/deposit evidence, stale HTTP/native response rejection, no login or retry on 429 OK");
}
main().catch(error=>{console.error(error);process.exitCode=1});
