"use strict";
const assert=require("assert/strict"),Service=require("../wolt-retailer-price-service");
const now=Date.parse("2026-10-01T10:00:00Z"),venue=Service.VENUE;
function offer(patch={}){return{sourceId:Service.SOURCE,merchant:"EDEKA",nativeVenueId:venue.nativeVenueId,retailerSku:"1dc18e85145be6774701f54d",gtin:"5449000017888",name:"LOCAL TEST Coca-Cola,1 l",brand:null,pack:"1 l",packAmount:1,packUnit:"l",packCount:1,price:1.89,deposit:0.15,depositLabel:"MEHRWEG",displayedPrice:2.04,nativePriceEUR:2.04,nativePriceIncludesDeposit:true,payablePackPrice:2.04,depositIncludedInDisplayedPrice:true,currency:"EUR",priceType:"unknown",promotionStatus:"unknown",availability:"unknown",capturedAt:new Date(now-1000).toISOString(),sourceUrl:"https://wolt.com/de/deu/berlin/venue/edeka-hilbrecht",sourceResponseUrl:"https://consumer-api.wolt.com/consumer-api/consumer-assortment/v1/venues/slug/edeka-hilbrecht/assortment/categories/slug/cola-cola-mix-127",proofHash:"a".repeat(64),sourceResponseHash:"a".repeat(64),shop:{...venue,address:"Ritterstr.38-40"},scopeCountry:"DE",scopeChannel:"online",priceBasis:"pack",...patch};}
function pool(){const rows=new Map(),calls=[];return{rows,calls,query:async(sql,params=[])=>{calls.push({sql,params});if(sql.startsWith("CREATE TABLE"))return{rows:[],rowCount:0};if(sql.startsWith("SELECT p.source_id"))return{rows:JSON.parse(params[0]).map(x=>rows.get(x.source_id+"|"+x.native_venue_id+"|"+x.retailer_sku)).filter(Boolean),rowCount:0};if(sql.startsWith("INSERT INTO wolt_retailer_published_prices")){let rowCount=0;for(const row of JSON.parse(params[0])){const id=row.source_id+"|"+row.native_venue_id+"|"+row.retailer_sku,old=rows.get(id);if(!old||row.captured_at>old.captured_at){rows.set(id,row);rowCount++;}}return{rows:[],rowCount};}return{rows:[],rowCount:0};}};}
const approved=Service.validateOffer(offer(),{now});assert.equal(approved.ok,true,JSON.stringify(approved));assert.equal(approved.offer.price,1.89);assert.equal(approved.offer.deposit,0.15);assert.equal(approved.offer.displayedPrice,2.04);assert.equal(approved.offer.payablePackPrice,2.04);assert.equal(approved.offer.depositIncludedInDisplayedPrice,true);assert.equal(approved.offer.packAmount,1000);assert.equal(approved.offer.packUnit,"ml");assert.equal(approved.offer.packCount,1);assert.equal(approved.offer.expiresAt,new Date(now-1000+Service.DAY_MS).toISOString());assert.equal(approved.offer.truthEligible,false);assert.equal(approved.offer.shippingIncluded,false);assert.equal(approved.offer.serviceFeesIncluded,false);assert(!("storeId"in approved.offer));assert(!("canonicalProductId"in approved.offer));
const unknownDeposit=offer({deposit:null,depositLabel:null,price:2.04,depositIncludedInDisplayedPrice:null,payablePackPrice:null});const absent=Service.validateOffer(unknownDeposit,{now});assert.equal(absent.ok,true);assert.equal(absent.offer.deposit,null);assert.equal(absent.offer.depositIncludedInDisplayedPrice,null);assert.equal(absent.offer.payablePackPrice,null,"Missing native deposit cannot establish a complete pack checkout price");
assert.equal(Service.validateOffer(offer({gtin:null}),{now}).offer.identityStatus,"native-retailer-sku");assert.equal(Service.validateOffer(offer({gtin:""}),{now}).offer.gtin,null);
const multi=Service.validateOffer(offer({pack:"6 x 0.5 l",packAmount:0.5,packUnit:"l",packCount:6}),{now});assert.equal(multi.ok,true);assert.equal(multi.offer.packAmount,500);assert.equal(multi.offer.packCount,6);
for(const patch of[{name:"Milka Tender Milch, 5 x 37 g",pack:"37 g",packAmount:37,packUnit:"g",packCount:1},{name:"LOCAL TEST water 6 × 0,5 l",pack:"0.5 l",packAmount:.5,packUnit:"l",packCount:1}]){const invalid=Service.validateOffer(offer(patch),{now});assert.equal(invalid.ok,false);assert(invalid.reasons.includes("wolt-native-sales-pack-conflict"));}
assert.equal(Service.validateOffer(offer({name:"Milka Tender Milch, 5 x 37 g",pack:"185 g",packAmount:185,packUnit:"g",packCount:1}),{now}).ok,true);
assert.equal(Service.validateOffer(offer({name:"Milka Tender Milch, 5 x 37 g",pack:"5 x 37 g",packAmount:37,packUnit:"g",packCount:5}),{now}).ok,true);
assert(Service.querySpec().sql.includes("validation_issue IS NULL"));
assert.equal(Service.validateOffer(offer({expiresAt:"2099-01-01T00:00:00Z"}),{now}).offer.expiresAt,approved.offer.expiresAt);
assert.equal(Service.validateOffer(offer({sourceResponseUrl:offer().sourceResponseUrl+"?page_token=opaque%3D%3D"}),{now}).ok,true);
for(const[patch,reason]of[[{sourceId:"unapproved"},"retailer-source-not-approved"],[{merchant:"REWE"},"retailer-source-not-approved"],[{nativeVenueId:"0".repeat(24)},"native-venue-not-approved"],[{retailerSku:"synthetic-sku"},"native-article-id-required"],[{gtin:"5449000017880"},"invalid-native-gtin"],[{pack:"unknown"},"known-pack-required"],[{packAmount:2},"pack-metadata-conflict"],[{packCount:true},"pack-metadata-conflict"],[{price:true},"positive-finite-price-required"],[{price:Infinity},"positive-finite-price-required"],[{price:"1.89"},"positive-finite-price-required"],[{deposit:true},"invalid-deposit"],[{deposit:-1},"invalid-deposit"],[{displayedPrice:2.05,nativePriceEUR:2.05},"native-price-deposit-conflict"],[{depositIncludedInDisplayedPrice:false},"native-price-deposit-conflict"],[{priceType:"regular"},"unattested-price-type"],[{promotionStatus:"promotion"},"unattested-promotion-status"],[{currency:"USD"},"currency-outside-EUR"],[{scopeChannel:"store"},"online-DE-scope-required"],[{scopeCountry:"GB"},"online-DE-scope-required"],[{storeId:"made-up-store"},"physical-identity-scope-unsupported"],[{canonicalProductId:"made-up-product"},"physical-identity-scope-unsupported"],[{priceBasis:"kg"},"pack-price-required"],[{capturedAt:"2026-02-30T12:00:00Z"},"capture-time-required"],[{capturedAt:new Date(now+1).toISOString()},"capture-time-future"],[{sourceUrl:"https://wolt.com/de/deu/berlin/venue/another-shop"},"exact-native-venue-url-required"],[{sourceUrl:"https://wolt.com/de/deu/berlin/venue/edeka-hilbrecht?fake=1"},"exact-native-venue-url-required"],[{sourceResponseUrl:"https://example.test/assortment"},"exact-native-response-url-required"],[{sourceResponseUrl:offer().sourceResponseUrl+"?language=de"},"exact-native-response-url-required"],[{sourceResponseHash:"b".repeat(64)},"source-proof-hash-required"],[{availability:"assumed"},"invalid-availability"],[{shop:{...offer().shop,postalCode:"10117"}},"native-Berlin-shop-scope-required"]]){const result=Service.validateOffer(offer(patch),{now});assert.equal(result.ok,false,reason);assert(result.reasons.includes(reason),reason);}
const promotion=Service.validateOffer(offer({originalPrice:2.19,priceType:"promotion",promotionStatus:"promotion"}),{now});assert.equal(promotion.ok,true);
assert.equal(Service.matchesProductQuery(approved.offer,{gtin:approved.offer.gtin,pack:"1000 ml"}),true);assert.equal(Service.matchesProductQuery(approved.offer,{gtin:approved.offer.gtin,pack:"2 x 500 ml"}),false);assert.equal(Service.matchesProductQuery(approved.offer,{name:approved.offer.name}),false);assert.equal(Service.matchesProductQuery(absent.offer,{gtin:"4008400401621"}),false);
(async()=>{
 const db=pool(),original=offer(),snapshot=JSON.stringify(original);let saved=await Service.persist(db,[original,offer({price:0})],{now});assert.equal(saved.accepted,1);assert.equal(saved.rejected,1);assert.equal(saved.upserted,1);assert.equal(JSON.stringify(original),snapshot);
 assert.equal((await Service.persist(db,[original],{now})).unchanged,1);
 const conflicting=offer({price:1.99,displayedPrice:2.14,nativePriceEUR:2.14,payablePackPrice:2.14});saved=await Service.persist(db,[conflicting],{now});assert.equal(saved.accepted,0);assert.equal(saved.rejected,1);assert.equal(saved.reasons["same-capture-conflict"],1,"A contradiction at the saved capture time cannot silently replace or reuse the price");
 const batchDb=pool();saved=await Service.persist(batchDb,[original,conflicting],{now});assert.equal(saved.accepted,0);assert.equal(saved.rejected,2);assert.equal(batchDb.rows.size,0);
 saved=await Service.persist(batchDb,[original,original],{now});assert.equal(saved.accepted,1);assert.equal(saved.duplicates,1);assert.equal(saved.upserted,1);
 const newer=offer({price:1.99,displayedPrice:2.14,nativePriceEUR:2.14,payablePackPrice:2.14,capturedAt:new Date(now).toISOString(),proofHash:"b".repeat(64),sourceResponseHash:"b".repeat(64),availability:"unavailable"});assert.equal((await Service.persist(db,[newer],{now})).upserted,1);assert.equal((await Service.persist(db,[original],{now})).unchanged,1);assert.equal([...db.rows.values()][0].price,1.99);assert.equal([...db.rows.values()][0].availability,"unavailable");
 const another=offer({retailerSku:"2".repeat(24),gtin:original.gtin});assert.equal((await Service.persist(db,[another],{now})).upserted,1);assert.equal(db.rows.size,2,"Separate native article IDs retain their own price even when they share a GTIN");
 assert(!db.calls.some(call=>/price_observations|INSERT INTO (?:products|stores|receipts)\b/.test(call.sql)),"Online shop evidence must not modify physical or receipt records");
 const query=Service.querySpec({now,merchant:"edeka",nativeVenueId:venue.nativeVenueId,gtin:original.gtin,search:"Milch%_",today:"2026-10-01",limit:999});assert.equal(query.params[1],"edeka");assert.equal(query.params[2],venue.nativeVenueId);assert.equal(query.params[3],original.gtin);assert.equal(query.params[4],"%Milch\\%\\_%");assert.equal(query.params.at(-1),200);assert(query.sql.includes("captured_at<=$1"));assert(query.sql.includes("interval '24 hours'"));assert(query.sql.includes("Europe/Berlin"));
 assert.throws(()=>Service.querySpec({gtin:"invalid"}),/invalid-gtin/);assert.throws(()=>Service.querySpec({nativeVenueId:"invalid"}),/invalid-native-venue-id/);assert.throws(()=>Service.querySpec({today:"2026-02-30"}),/invalid-date/);
 const selected=approved.offer,searchDb={query:async sql=>({rows:sql.startsWith("SELECT source_id AS")?[selected]:[],rowCount:0})};const found=await Service.search(searchDb,{now});assert.equal(found.items[0].price,1.89);assert.equal(found.items[0].payablePackPrice,2.04);assert.equal(found.items[0].truthEligible,false);assert.equal(found.items[0].current,true);
 await assert.rejects(()=>Service.persist(null,[]),/database-required/);await assert.rejects(()=>Service.persist(db,{}),/invalid-published-offers/);await assert.rejects(()=>Service.search(null),/database-required/);
 console.log("wolt-retailer-price-service: exact native Berlin shop/article scope, validated optional GTIN and pack, native deposit split, unknown normal-price classification, conflicting captures rejected, newer-only upserts and literal bounded online queries OK");
 const nahkauf=Service.createService("nahkaufWrangelBerlin"),nv=nahkauf.VENUE,second=offer({sourceId:nahkauf.SOURCE,merchant:nahkauf.MERCHANT,nativeVenueId:nv.nativeVenueId,price:2.56,deposit:.15,displayedPrice:2.71,nativePriceEUR:2.71,payablePackPrice:2.71,sourceUrl:"https://wolt.com/de/deu/berlin/venue/"+nv.slug,sourceResponseUrl:"https://consumer-api.wolt.com/consumer-api/consumer-assortment/v1/venues/slug/"+nv.slug+"/assortment/categories/slug/milch-47",shop:{...nv,address:nv.address}});
 assert.equal(nahkauf.validateOffer(second,{now}).ok,true);assert.equal(Service.validateOffer(second,{now}).ok,false,"A real nahkauf offer cannot enter the EDEKA source through a different closure");assert.equal(nahkauf.validateOffer(original,{now}).ok,false);assert.equal(nahkauf.validateOffer({...second,sourceResponseUrl:original.sourceResponseUrl},{now}).ok,false);assert.equal(nahkauf.validateOffer({...second,shop:original.shop},{now}).ok,false);assert.equal(nahkauf.validateOffer({...second,nativeMarketId:"800401"},{now}).ok,false);
 for(const key of["another-market",{},null])assert.throws(()=>Service.createService(key),/wolt-venue-profile-not-approved/);assert.throws(()=>Service.createService("nahkaufWrangelBerlin",{nativeVenueId:venue.nativeVenueId}),/wolt-venue-profile-not-approved/);
 const multi=pool();assert.equal((await Service.persist(multi,[original],{now})).upserted,1);assert.equal((await nahkauf.persist(multi,[second],{now})).upserted,1);assert.equal(multi.rows.size,2,"One exact GTIN and SKU in different native venues retain both source prices");assert.equal([...multi.rows.values()].find(row=>row.source_id===Service.SOURCE).price,original.price);assert.equal([...multi.rows.values()].find(row=>row.source_id===nahkauf.SOURCE).price,2.56);assert.equal((await nahkauf.persist(multi,[{...second,price:2.99,displayedPrice:3.14,nativePriceEUR:3.14,payablePackPrice:3.14}],{now})).rejected,1);assert.equal([...multi.rows.values()].find(row=>row.source_id===Service.SOURCE).price,original.price);
 const secondQuery=nahkauf.querySpec({now,gtin:original.gtin});assert(secondQuery.sql.includes("source_id='"+nahkauf.SOURCE+"'"));assert(!secondQuery.sql.includes("source_id='"+Service.SOURCE+"'"));assert(multi.calls.some(c=>c.sql.includes("wolt_published_approved_venue")&&c.sql.includes(nv.nativeVenueId)&&c.sql.includes(venue.nativeVenueId)));
})().catch(error=>{console.error(error);process.exitCode=1});
