"use strict";
const assert=require("assert/strict"),{Pool}=require("pg"),Service=require("../wolt-retailer-price-service"),RefreshStore=require("../price-refresh-state-store"),SourceRefresh=require("../price-source-refresh"),SourceState=require("../source-refresh-state"),Sources=require("../price-sources").SOURCES;
function gtin(index){const body=String(970000000000+index),sum=[...body].reduce((total,digit,position)=>total+Number(digit)*(position%2?3:1),0);return body+(10-sum%10)%10;}
async function main(){
 const connectionString=process.env.DATABASE_URL;assert(connectionString,"DATABASE_URL is required");const database=new URL(connectionString);assert.equal(database.hostname,"localhost");assert(database.pathname.endsWith("_test"),"Only a dedicated local test database is allowed");
 const pool=new Pool({connectionString,ssl:false,connectionTimeoutMillis:5000}),now=Date.now();let testError,api;
 const fixture=(index,patch={})=>({sourceId:Service.SOURCE,merchant:"EDEKA",nativeVenueId:Service.VENUE.nativeVenueId,retailerSku:(900000+index).toString(16).padStart(24,"0"),gtin:gtin(index),name:"POSTGRES TEST Berlin published product "+index,brand:"POSTGRES TEST",pack:"1 l",packAmount:1,packUnit:"l",packCount:1,price:1.29,deposit:0.25,displayedPrice:1.54,nativePriceEUR:1.54,nativePriceIncludesDeposit:true,payablePackPrice:1.54,depositIncludedInDisplayedPrice:true,currency:"EUR",priceType:"unknown",promotionStatus:"unknown",availability:"unknown",capturedAt:new Date(now-1000).toISOString(),proofHash:"c".repeat(64),sourceResponseHash:"c".repeat(64),sourceUrl:"https://wolt.com/de/deu/berlin/venue/edeka-hilbrecht",sourceResponseUrl:"https://consumer-api.wolt.com/consumer-api/consumer-assortment/v1/venues/slug/edeka-hilbrecht/assortment/categories/slug/test-native-category",shop:{...Service.VENUE,address:"Ritterstr.38-40"},scopeCountry:"DE",scopeChannel:"online",...patch});
 try{
  const exists=async table=>!!(await pool.query("SELECT to_regclass($1) AS name",["public."+table])).rows[0].name;
  const baseline={};for(const table of["products","stores","price_observations","receipts","retailer_published_prices"]){baseline[table]=await exists(table)?(await pool.query("SELECT count(*)::int AS count FROM "+table)).rows[0].count:null;}
  await RefreshStore.ensure(pool);const stateName="POSTGRES TEST bounded grocery continuation",owner="POSTGRES TEST worker",scheduled=new Date(now+60000).toISOString();
  assert(await RefreshStore.acquire(pool,stateName,owner));assert.equal(await RefreshStore.save(pool,stateName,{lastAttemptAt:new Date(now).toISOString(),lastSuccessAt:new Date(now).toISOString(),nextAttemptAt:scheduled,lastReceived:400,lastAccepted:368},"OTHER TEST worker"),false,"A different worker cannot overwrite the schedule of a held lease");
  assert(await RefreshStore.save(pool,stateName,{lastAttemptAt:new Date(now).toISOString(),lastSuccessAt:new Date(now).toISOString(),nextAttemptAt:scheduled,lastReceived:400,lastAccepted:368},owner));
  let resumed=(await RefreshStore.loadAll(pool))[stateName];assert.equal(new Date(resumed.nextAttemptAt).toISOString(),scheduled);assert.equal(SourceRefresh.due(Sources[Service.SOURCE],resumed,now+59999),false);assert.equal(SourceRefresh.due(Sources[Service.SOURCE],resumed,now+60000),true);
  const sourceFailure=Object.assign(Error("wolt-source-http-429"),{nextAttemptAt:new Date(now+7200000).toISOString()});resumed=SourceState.failure(resumed,sourceFailure,new Date(now+60000).toISOString());assert(await RefreshStore.acquire(pool,stateName,owner));assert(await RefreshStore.save(pool,stateName,resumed,owner));
  resumed=(await RefreshStore.loadAll(pool))[stateName];assert.equal(new Date(resumed.lastSuccessAt).getTime(),now);assert.equal(resumed.consecutiveFailures,1);assert.equal(SourceRefresh.due(Sources[Service.SOURCE],resumed,now+3600000),false);assert.equal(SourceRefresh.due(Sources[Service.SOURCE],resumed,now+7200000),true);
  await pool.query("DELETE FROM price_source_refresh_state WHERE source_name=$1",[stateName]);
  const fixtures=Array.from({length:501},(_,index)=>fixture(index)),saved=await Service.persist(pool,fixtures,{now});assert.equal(saved.accepted,501);assert.equal(saved.rejected,0);assert.equal(saved.upserted,501);
  const stored=(await pool.query("SELECT count(*)::int AS total,count(*) FILTER(WHERE scope_country='DE' AND scope_channel='online' AND currency='EUR' AND pack_amount=1000 AND pack_unit='ml' AND pack_count=1 AND price=1.29 AND deposit=0.25 AND displayed_price=1.54)::int AS exact FROM wolt_retailer_published_prices WHERE retailer_sku=ANY($1::text[])",[fixtures.map(row=>row.retailerSku)])).rows[0];assert.equal(stored.total,501);assert.equal(stored.exact,501);
  assert.equal((await Service.persist(pool,fixtures,{now})).unchanged,501);
  assert.equal((await Service.persist(pool,[fixture(0,{price:1.59,displayedPrice:1.84,nativePriceEUR:1.84,payablePackPrice:1.84})],{now})).rejected,1,"Contradictory stored captures are rejected");
  const changed=fixture(0,{price:1.39,displayedPrice:1.64,nativePriceEUR:1.64,payablePackPrice:1.64,capturedAt:new Date(now).toISOString(),proofHash:"d".repeat(64),sourceResponseHash:"d".repeat(64),availability:"available"});assert.equal((await Service.persist(pool,[changed],{now})).upserted,1);
  assert.equal((await Service.persist(pool,[fixture(0)],{now})).unchanged,1);
  let selected=(await Service.search(pool,{merchant:"edeka",gtin:gtin(0),nativeVenueId:Service.VENUE.nativeVenueId,now})).items;assert.equal(selected.length,1);assert.equal(selected[0].price,1.39);assert.equal(selected[0].deposit,0.25);assert.equal(selected[0].displayedPrice,1.64);assert.equal(selected[0].payablePackPrice,1.64);assert.equal(selected[0].availability,"available");assert.equal(selected[0].scopeChannel,"online");assert.equal(selected[0].truthEligible,false);assert.equal(selected[0].shippingIncluded,false);assert.equal(selected[0].serviceFeesIncluded,false);assert(!("storeId"in selected[0]));assert(!("canonicalProductId"in selected[0]));
  assert.equal((await Service.search(pool,{merchant:"REWE",gtin:gtin(0),now})).items.length,0);assert.equal((await Service.search(pool,{nativeVenueId:"0".repeat(24),now})).items.length,0);assert.equal((await Service.search(pool,{search:"product 500",now})).items.length,1);assert.equal((await Service.search(pool,{search:"product%_",now})).items.length,0);assert.equal((await Service.search(pool,{limit:999,now})).items.length,200);
  assert.equal((await Service.search(pool,{today:new Date(now-Service.DAY_MS).toISOString().slice(0,10),now})).items.length,0,"Today's captured prices do not answer historical queries");
  const expired=fixture(501,{capturedAt:new Date(now-Service.DAY_MS-1).toISOString()});assert.equal((await Service.persist(pool,[expired],{now})).upserted,1);assert.equal((await Service.search(pool,{gtin:expired.gtin,now})).items.length,0);
  const noGtin=fixture(502,{gtin:null,deposit:null,price:1.54,depositIncludedInDisplayedPrice:null,payablePackPrice:null});assert.equal((await Service.persist(pool,[noGtin],{now})).upserted,1);selected=(await Service.search(pool,{search:"product 502",now})).items;assert.equal(selected.length,1);assert.equal(selected[0].gtin,null);assert.equal(selected[0].identityStatus,"native-retailer-sku");assert.equal(selected[0].payablePackPrice,null);
  const conflictA=fixture(503),conflictB=fixture(503,{price:1.39,displayedPrice:1.64,nativePriceEUR:1.64,payablePackPrice:1.64});const rejected=await Service.persist(pool,[conflictA,conflictB],{now});assert.equal(rejected.accepted,0);assert.equal(rejected.rejected,2);assert.equal((await Service.search(pool,{gtin:gtin(503),now})).items.length,0);
  const invalid=await Service.persist(pool,[fixture(504,{gtin:"invalid"}),fixture(505,{scopeChannel:"store",storeId:"imaginary"}),fixture(506,{nativeVenueId:"0".repeat(24)}),fixture(507,{displayedPrice:99,nativePriceEUR:99,payablePackPrice:99}),fixture(508,{capturedAt:new Date(now+1).toISOString()})],{now});assert.equal(invalid.accepted,0);assert.equal(invalid.rejected,5);
  const status=await Service.status(pool,{now});assert.equal(status.storedPrices,503);assert.equal(status.currentPrices,502);assert.equal(status.productsWithCurrentPublishedPrices,501,"A missing native GTIN must not count as an exact product identity");assert.equal(status.marketsWithCurrentPublishedPrices,1);assert.equal(status.availableCurrentPrices,1);assert.equal(status.markets[0].currentPrices,502);assert.equal(status.scopeChannel,"online");assert.equal(status.truthEligible,false);assert.equal(status.independentOfUserReceipts,true);
  assert.equal((await Service.search(pool,{now:now+Service.DAY_MS+1})).items.length,0);
  process.env.PORT="0";api=require("../server");await new Promise((resolve,reject)=>{api.server.once("error",reject);api.server.listen(0,"127.0.0.1",()=>{api.server.off("error",reject);resolve()})});const base="http://127.0.0.1:"+api.server.address().port;
  async function get(path){const response=await fetch(base+path,{signal:AbortSignal.timeout(10000)});return{status:response.status,body:await response.json()};}
  const publicQuery=await get("/v1/published-prices?merchant=EDEKA&gtin="+gtin(0));assert.equal(publicQuery.status,200,JSON.stringify(publicQuery));assert.equal(publicQuery.body.items.length,1);assert.equal(publicQuery.body.items[0].price,1.39);assert.equal(publicQuery.body.items[0].deposit,.25);assert.equal(publicQuery.body.items[0].displayedPrice,1.64);assert.equal(publicQuery.body.items[0].shop.postalCode,"10969");assert.equal(publicQuery.body.items[0].truthEligible,false);
  const publicStatus=await get("/v1/published-prices/status");assert.equal(publicStatus.status,200);assert.equal(publicStatus.body.retailers.woltEdekaBerlin.currentPrices,502);assert.equal(publicStatus.body.retailerResearch.woltEdekaBerlin.physicalStoreAssortmentVerified,false);assert.equal(publicStatus.body.retailerResearch.woltEdekaBerlin.independentOfUserReceipts,true);
  const request={gtin:gtin(0),pack:"1 l",merchants:["EDEKA"]},response=await fetch(base+"/v1/current-prices",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(request),signal:AbortSignal.timeout(10000)}),compared=await response.json();assert.equal(response.status,200,JSON.stringify(compared));assert.equal(compared.publishedAlternatives.length,1);assert.equal(compared.publishedAlternatives[0].sourceId,Service.SOURCE);assert(compared.results.every(row=>row.state==="unknown"&&row.price===null),"A Wolt GTIN cannot create a physical branch price");
  for(const[table,count]of Object.entries(baseline)){if(count===null)assert.equal(await exists(table),false,"Separate Wolt evidence must not create "+table);else assert.equal((await pool.query("SELECT count(*)::int AS count FROM "+table)).rows[0].count,count,"Separate Wolt evidence must not mutate "+table);}
  console.log("wolt-retailer-price-postgres: 501 bulk TEST native Berlin online prices, deposit split, source/shop isolation, optional GTIN counting, newer-only idempotency, contradictory capture rejection, literal search/history/expiry and zero canonical/receipt mutations OK");
 }catch(error){testError=error;throw error;}finally{const cleanup=[pool.end()];if(api){if(api.server.listening)cleanup.push(new Promise((resolve,reject)=>api.server.close(error=>error?reject(error):resolve())));cleanup.push(api.closeDb())}const errors=(await Promise.allSettled(cleanup)).filter(x=>x.status==="rejected");if(errors.length&&!testError)throw errors[0].reason;}
}
main().catch(error=>{console.error(error);process.exitCode=1});
