"use strict";
const assert=require("assert/strict"),Refresh=require("../wolt-retailer-price-refresh"),Client=require("../wolt-retailer-price-client");
const NOW=Date.parse("2026-10-01T12:00:00Z"),copy=value=>structuredClone(value);
function database(initial={}){
 const state=copy(initial),calls=[];let failCheckpoint=false;
 return{state,calls,get failCheckpoint(){return failCheckpoint},set failCheckpoint(value){failCheckpoint=value},query:async(sql,params=[])=>{
  calls.push({sql,params:copy(params)});if(sql.startsWith("SELECT cursor"))return{rows:Object.keys(state).length?[copy(state)]:[]};
  if(sql.startsWith("INSERT INTO wolt_retailer_catalog_state")&&params.length===4){state.lastError=params[1];state.retryAfter=params[2];if(params[3]){state.cursor=null;if(/last_completed_at\s*=\s*(?:NULL|CASE)/i.test(sql))state.lastCompletedAt=null}return{rows:[],rowCount:1}}
  if(sql.startsWith("INSERT INTO wolt_retailer_catalog_state")){if(failCheckpoint)throw Error("checkpoint-database-down");const completed=params[2];Object.assign(state,{cursor:JSON.parse(params[1]),lastCompletedAt:completed?params[3]:state.lastCompletedAt||null,completedCycles:(state.completedCycles||0)+(completed?1:0),categoryCount:params[4],categoriesCompleted:params[5],pagesFetched:params[6],receivedCumulative:params[7],assortmentHash:params[8],lastError:null,retryAfter:null});return{rows:[],rowCount:1}}
  return{rows:[],rowCount:0};
 }};
}
const quote=index=>({retailerSku:index.toString(16).padStart(24,"0"),gtin:null,name:"UNIT TEST published online product "+index,price:1.29,scopeChannel:"online",truthEligible:false});
const cursor=page=>({version:1,nativeVenueId:Client.VENUE_ID,nativeAssortmentId:"a".repeat(24),assortmentHash:"b".repeat(64),categoryIndex:page<3?0:1,pageToken:page<3?"TEST-page-"+(page+1):null,pageNumber:page<3?page+1:1,received:page*1800,pagesFetched:page});
function batch(page,patch={}){const complete=page===4;return{offers:Array.from({length:1800},(_,index)=>quote((page-1)*1800+index)),complete,nextCursor:complete?null:cursor(page),categoryCount:2,categoriesCompleted:complete?2:page===3?1:0,pagesFetched:page,received:1800,receivedCumulative:page*1800,requests:3,rejected:[],assortmentHash:"b".repeat(64),...patch}}
function sourceDatabase(){const databases=new Map();return{databases,source(name){if(!databases.has(name))databases.set(name,database());return databases.get(name);},query:async function(sql,params=[]){if(!params.length)return{rows:[],rowCount:0};return this.source(params[0]).query(sql,params);}};}
function venueCursor(client,page){return{...cursor(page),nativeVenueId:client.VENUE_ID};}
function venueBatch(client,page,patch={}){const result=batch(page);return{...result,offers:result.offers.map(o=>({...o,sourceId:client.SOURCE,nativeVenueId:client.VENUE_ID})),nextCursor:result.complete?null:venueCursor(client,page),...patch};}
async function multiMarket(){
 for(const invalid of["unapprovedMarket",{},null])assert.throws(()=>Refresh.createRefresh(invalid),/profile-not-approved/);assert.throws(()=>Refresh.createRefresh("edekaBerlin",{nativeVenueId:"invented"}),/profile-not-approved/);
 const edeka=Client.createClient("edekaBerlin"),nahkauf=Client.createClient("nahkaufWrangelBerlin"),edekaRefresh=Refresh.createRefresh("edekaBerlin"),nahkaufRefresh=Refresh.createRefresh("nahkaufWrangelBerlin"),pool=sourceDatabase();assert.notEqual(edeka.SOURCE,nahkauf.SOURCE);assert.notEqual(edeka.VENUE_ID,nahkauf.VENUE_ID);
 for(const[client,worker]of[[edeka,edekaRefresh],[nahkauf,nahkaufRefresh]]){const result=await worker.refresh({pool,maxRequests:3,now:()=>NOW},{fetchOffers:async options=>{assert.equal(options.cursor,null);return venueBatch(client,1);},persist:async(_,offers)=>{assert(offers.every(o=>o.sourceId===client.SOURCE&&o.nativeVenueId===client.VENUE_ID));return{accepted:offers.length};}});assert.equal(result.sourceId,client.SOURCE);assert.equal(result.scope.nativeVenueId,client.VENUE_ID);const state=await worker.status(pool);assert.equal(state.sourceId,client.SOURCE);assert.equal(state.nativeVenueId,client.VENUE_ID);assert.equal(state.scopeChannel,"online");assert.equal(state.physicalStoreAssortmentVerified,false);assert.equal(state.normalPriceClassificationVerified,false);assert.equal(state.independentOfUserReceipts,true);assert.deepEqual(state.cursor,venueCursor(client,1));}
 const edekaBefore=copy(pool.source(edeka.SOURCE).state);
 await nahkaufRefresh.refresh({pool,maxRequests:3,now:()=>NOW},{fetchOffers:async options=>{assert.deepEqual(options.cursor,venueCursor(nahkauf,1));return venueBatch(nahkauf,2);},persist:async()=>({accepted:1800})});assert.deepEqual(pool.source(edeka.SOURCE).state,edekaBefore,"Another market cannot overwrite EDEKA's source checkpoint");
 await assert.rejects(()=>edekaRefresh.refresh({pool,now:()=>NOW},{fetchOffers:async options=>{assert.deepEqual(options.cursor,venueCursor(edeka,1));throw Object.assign(Error("wolt-source-http-429"),{retryAfterMs:7200000});}}),/429/);
 const edekaBlocked=copy(pool.source(edeka.SOURCE).state);assert.equal((await edekaRefresh.refresh({pool,now:()=>NOW+60000},{fetchOffers:async()=>{throw Error("EDEKA denial must stay paused");}})).skipped,"source-cooldown");
 await nahkaufRefresh.refresh({pool,now:()=>NOW+60000},{fetchOffers:async options=>{assert.deepEqual(options.cursor,venueCursor(nahkauf,2));return venueBatch(nahkauf,3);},persist:async()=>({accepted:1800})});assert.deepEqual(pool.source(edeka.SOURCE).state,edekaBlocked,"EDEKA's cooldown cannot pause an independent nahkauf scan");assert.equal(await edekaRefresh.resumeAt(pool,NOW),new Date(NOW+7200000).toISOString());
 const nahBefore=copy(pool.source(nahkauf.SOURCE).state);let invalidPersists=0;await assert.rejects(()=>nahkaufRefresh.refresh({pool,now:()=>NOW},{fetchOffers:async()=>venueBatch(nahkauf,3,{nextCursor:{...venueCursor(nahkauf,3),nativeVenueId:edeka.VENUE_ID,pagesFetched:4,received:7200},pagesFetched:4,receivedCumulative:7200}),persist:async()=>{invalidPersists++;}}),/progress-unconfirmed/);assert.equal(invalidPersists,0);assert.deepEqual(pool.source(nahkauf.SOURCE).state,nahBefore);
 Object.assign(pool.source(nahkauf.SOURCE).state,{lastError:"wolt-native-venue-stale-or-future",retryAfter:new Date(NOW+3600000).toISOString()});assert.equal(await nahkaufRefresh.resumeAt(pool,NOW),new Date(NOW+3600000).toISOString());assert.equal((await nahkaufRefresh.refresh({pool,now:()=>NOW},{fetchOffers:async()=>{throw Error("Legacy EDEKA cache bypass must not apply to another market");}})).skipped,"source-cooldown");
 // Distinct sources may run together; constructing a second factory cannot evade the same-source lock.
 const parallelDb=sourceDatabase(),releases={},started={};
 const begin=(key,client,worker)=>{const signal=new Promise(resolve=>{started[key]=resolve;});const run=worker.refresh({pool:parallelDb,now:()=>NOW},{fetchOffers:async()=>{started[key]();return new Promise(resolve=>{releases[key]=()=>resolve(venueBatch(client,4));});},persist:async()=>({accepted:1800})});return{signal,run};};
 const heldE=begin("edeka",edeka,edekaRefresh);await heldE.signal;const heldN=begin("nahkauf",nahkauf,nahkaufRefresh);await heldN.signal;
 assert.equal((await Refresh.createRefresh("edekaBerlin").refresh({pool:parallelDb,now:()=>NOW})).skipped,"already-running");assert.equal((await Refresh.createRefresh("nahkaufWrangelBerlin").refresh({pool:parallelDb,now:()=>NOW})).skipped,"already-running");releases.edeka();releases.nahkauf();await Promise.all([heldE.run,heldN.run]);assert.equal((await edekaRefresh.status(parallelDb)).completedCycles,1);assert.equal((await nahkaufRefresh.status(parallelDb)).completedCycles,1);
}
async function main(){
 const pool=database(),quotes=new Map(),steps=[],seenCursors=[];let page=0;
 const deps={fetchOffers:async options=>{assert.equal(options.maxRequests,3,"Each run remains bounded to venue/listing plus one completed native page");seenCursors.push(copy(options.cursor));assert.equal(options.now(),new Date(NOW).toISOString());steps.push("fetch");return batch(++page)},persist:async(db,offers)=>{assert.equal(db,pool);steps.push("save-quotes");for(const offer of offers)quotes.set(offer.retailerSku,copy(offer));return{received:offers.length,accepted:offers.length,rejected:0,upserted:offers.length}}};
 for(let i=1;i<=4;i++){const result=await Refresh.refresh({pool,maxRequests:3,now:()=>NOW},deps);assert.equal(result.accepted,1800);assert.equal(result.catalog.publishedAssortmentComplete,i===4,"A bounded partial scan must not claim the published assortment is complete");assert.equal(result.catalog.categoryCount,2);assert.equal(result.catalog.categoriesCompleted,i===4?2:i===3?1:0);assert.equal(result.catalog.receivedCumulative,i*1800);assert.equal(result.catalog.physicalStoreAssortmentVerified,false);assert.equal(result.independentOfUserReceipts,true);assert.equal(result.scope.channel,"online");assert.equal(result.scope.city,"Berlin");const status=await Refresh.status(pool);assert.equal(status.publishedAssortmentComplete,i===4);assert.equal(status.normalPriceClassificationVerified,false);assert.equal(status.physicalStoreAssortmentVerified,false);assert.equal(status.completedCycles||0,i===4?1:0);}
 assert.equal(quotes.size,7200,"Completed continuation pages beyond 5,000 native articles must all reach persistence");assert.deepEqual(seenCursors,[null,cursor(1),cursor(2),cursor(3)]);assert.deepEqual(steps,["fetch","save-quotes","fetch","save-quotes","fetch","save-quotes","fetch","save-quotes"]);assert.equal(pool.state.pagesFetched,4);assert.equal(pool.state.receivedCumulative,7200);assert.equal(pool.state.cursor,null);assert(pool.state.lastCompletedAt);
 assert(!pool.calls.some(call=>/INSERT INTO (?:products|stores|price_observations|receipt_submissions|receipts)\b/.test(call.sql)),"The autonomous online collector cannot invent canonical stores, physical prices or user receipts");
 const checkpoint=database({cursor:cursor(1),categoryCount:2,categoriesCompleted:0,pagesFetched:1,receivedCumulative:1800});let savedCount=0;const before=copy(checkpoint.state);
 await assert.rejects(()=>Refresh.refresh({pool:checkpoint,maxRequests:3,now:()=>NOW},{fetchOffers:async()=>batch(2),persist:async()=>{throw Error("quote-database-down")}}),/quote-database-down/);assert.deepEqual(checkpoint.state,before,"Failed quote persistence cannot move the source cursor");
 checkpoint.failCheckpoint=true;await assert.rejects(()=>Refresh.refresh({pool:checkpoint,maxRequests:3,now:()=>NOW},{fetchOffers:async()=>batch(2),persist:async(_,offers)=>{savedCount+=offers.length;return{accepted:offers.length}}}),/checkpoint-database-down/);assert.equal(savedCount,1800);assert.deepEqual(checkpoint.state,before,"A failed checkpoint write must leave the saved-page continuation retryable");checkpoint.failCheckpoint=false;
 let retriedCursor;await Refresh.refresh({pool:checkpoint,maxRequests:3,now:()=>NOW},{fetchOffers:async options=>{retriedCursor=options.cursor;return batch(2)},persist:async(_,offers)=>({accepted:offers.length})});assert.deepEqual(retriedCursor,before.cursor);assert.deepEqual(checkpoint.state.cursor,cursor(2));
 for(const[code,retryAfterMs,cooldown]of[["wolt-source-http-403",undefined,3600000],["wolt-source-http-429",2*3600000,2*3600000]]){
  const blocked=database({cursor:cursor(2)}),beforeCursor=copy(blocked.state.cursor);let fetchCalls=0,persistCalls=0;const blockedDeps={fetchOffers:async()=>{fetchCalls++;throw Object.assign(Error(code),{code,retryAfterMs})},persist:async()=>{persistCalls++;return{accepted:0}}};
  await assert.rejects(()=>Refresh.refresh({pool:blocked,now:()=>NOW},blockedDeps),new RegExp(code));assert.equal(blocked.state.lastError,code);assert.equal(blocked.state.retryAfter,new Date(NOW+cooldown).toISOString());assert.deepEqual(blocked.state.cursor,beforeCursor);assert.equal(persistCalls,0);
  const skipped=await Refresh.refresh({pool:blocked,now:()=>NOW+cooldown-1},blockedDeps);assert.equal(skipped.skipped,"source-cooldown");assert.equal(fetchCalls,1,"403/429 must pause the native source until its persisted cooldown ends");
 }
 const legacy=database({cursor:cursor(2),lastError:"wolt-native-venue-stale-or-future",retryAfter:new Date(NOW+3600000).toISOString()});assert.equal(await Refresh.resumeAt(legacy,NOW),new Date(NOW).toISOString(),"The obsolete HTML metadata error may obtain the new native identity proof now");let legacyReads=0;await Refresh.refresh({pool:legacy,now:()=>NOW},{fetchOffers:async options=>{legacyReads++;assert.deepEqual(options.cursor,cursor(2));return batch(3);},persist:async(_,offers)=>({accepted:offers.length})});assert.equal(legacyReads,1);assert.equal(legacy.state.lastError,null);assert.equal(legacy.state.retryAfter,null);assert.deepEqual(legacy.state.cursor,cursor(3));
 const legacyDenied=database({cursor:cursor(2),lastError:"wolt-native-venue-stale-or-future",retryAfter:new Date(NOW+3600000).toISOString()});await assert.rejects(()=>Refresh.refresh({pool:legacyDenied,now:()=>NOW},{fetchOffers:async()=>{throw Object.assign(Error("wolt-source-http-429"),{retryAfterMs:7200000});}}),/429/);assert.equal(await Refresh.resumeAt(legacyDenied,NOW),new Date(NOW+7200000).toISOString());assert.equal((await Refresh.refresh({pool:legacyDenied,now:()=>NOW+60000},{fetchOffers:async()=>{throw Error("Must preserve native denial cooldown");}})).skipped,"source-cooldown");
 const stalePrices=database({cursor:cursor(2),lastError:"wolt-source-response-date-stale-or-invalid",retryAfter:new Date(NOW+3600000).toISOString()});assert.equal(await Refresh.resumeAt(stalePrices,NOW),stalePrices.state.retryAfter);assert.equal((await Refresh.refresh({pool:stalePrices,now:()=>NOW},{fetchOffers:async()=>{throw Error("Must preserve actual source freshness failure");}})).skipped,"source-cooldown");
 const changedCatalog=database({cursor:cursor(2),lastCompletedAt:new Date(NOW-86400000).toISOString(),completedCycles:1});await assert.rejects(()=>Refresh.refresh({pool:changedCatalog,now:()=>NOW},{fetchOffers:async()=>{throw Object.assign(Error("wolt-continuation-cursor-conflict"),{code:"wolt-continuation-cursor-conflict"})}}),/continuation-cursor-conflict/);assert.equal(changedCatalog.state.cursor,null);assert.equal((await Refresh.status(changedCatalog)).publishedAssortmentComplete,false,"Resetting an invalidated catalog cursor must not turn a former cycle into a completed new catalog");
 let restartCursor;await Refresh.refresh({pool:changedCatalog,now:()=>NOW+3600000},{fetchOffers:async options=>{restartCursor=options.cursor;return batch(1)},persist:async(_,offers)=>({accepted:offers.length})});assert.equal(restartCursor,null);assert.deepEqual(changedCatalog.state.cursor,cursor(1));assert.equal((await Refresh.status(changedCatalog)).publishedAssortmentComplete,false);
 for(const patch of[{complete:false,nextCursor:null},{complete:true,nextCursor:null,categoriesCompleted:1},{categoryCount:-1},{categoriesCompleted:-1},{categoriesCompleted:3},{complete:false,categoriesCompleted:2},{pagesFetched:-1},{receivedCumulative:NaN},{offers:null}]){const malformed=database({cursor:cursor(1)}),original=copy(malformed.state);let persists=0;await assert.rejects(()=>Refresh.refresh({pool:malformed,now:()=>NOW},{fetchOffers:async()=>batch(2,patch),persist:async()=>{persists++;return{accepted:0}}}),/wolt-catalog-progress-unconfirmed/);assert.equal(persists,0);assert.deepEqual(malformed.state,original,"Unconfirmed page/category counts must never advance the source checkpoint")}
 let release,fetchStarted;const started=new Promise(resolve=>{fetchStarted=resolve}),held=Refresh.refresh({pool:database(),now:()=>NOW},{fetchOffers:async()=>{fetchStarted();return new Promise(resolve=>{release=()=>resolve(batch(4))})},persist:async(_,offers)=>({accepted:offers.length})});await started;const concurrent=await Refresh.refresh({pool:database(),now:()=>NOW},{});assert.equal(concurrent.skipped,"already-running");release();await held;
 const resumed=database({cursor:cursor(1),updatedAt:new Date(NOW).toISOString()});assert.equal(await Refresh.resumeAt(resumed,NOW),new Date(NOW+60000).toISOString());resumed.state.retryAfter=new Date(NOW+7200000).toISOString();assert.equal(await Refresh.resumeAt(resumed,NOW),resumed.state.retryAfter,"An unfinished scan cannot override its persisted source cooldown");assert.equal(await Refresh.resumeAt(database({cursor:null,updatedAt:new Date(NOW).toISOString()}),NOW),null);assert.equal(await Refresh.resumeAt(database({cursor:cursor(1),lastError:"stalled",updatedAt:new Date(NOW).toISOString()}),NOW),null);
 for(const patch of[{stalled:true},{pagesFetched:1,nextCursor:cursor(1),receivedCumulative:1800}]){const stalled=database({cursor:cursor(1)}),original=copy(stalled.state);let persists=0;await assert.rejects(()=>Refresh.refresh({pool:stalled,now:()=>NOW},{fetchOffers:async()=>batch(2,patch),persist:async()=>{persists++;return{accepted:0}}}),/wolt-catalog-progress-stalled/);assert.equal(persists,0);assert.deepEqual(stalled.state,original);}
 for(const patch of[{nextCursor:true},{nextCursor:{...cursor(2),nativeVenueId:"0".repeat(24)}},{nextCursor:{...cursor(2),categoryIndex:1}},{nextCursor:{...cursor(2),pagesFetched:3}},{nextCursor:{...cursor(2),received:99}},{nextCursor:{...cursor(2),pageToken:null,pageNumber:2}},{complete:true,categoriesCompleted:2,nextCursor:cursor(2)}]){let persists=0;await assert.rejects(()=>Refresh.refresh({pool:database({cursor:cursor(1)}),now:()=>NOW},{fetchOffers:async()=>batch(2,patch),persist:async()=>{persists++;return{accepted:0}}}),/wolt-catalog-progress-unconfirmed/);assert.equal(persists,0);}
 let requestBudget;await Refresh.refresh({pool:database(),maxRequests:999,now:()=>NOW},{fetchOffers:async options=>{requestBudget=options.maxRequests;return batch(4)},persist:async(_,offers)=>({accepted:offers.length})});assert.equal(requestBudget,64);await assert.rejects(()=>Refresh.refresh({}),/database-required/);
 await multiMarket();
 console.log("wolt-retailer-price-refresh: 7,200 TEST articles across persisted bounded pages, default EDEKA regression, independent multi-market checkpoints/cooldowns/concurrency, venue-bound cursors, 403/429 cooldown, safe changed-catalog restart, failed-write preservation and no physical/receipt writes OK");
}
main().catch(error=>{console.error(error);process.exitCode=1});
