"use strict";
const assert=require("assert/strict"),crypto=require("crypto"),Client=require("../wolt-retailer-price-client"),Service=require("../wolt-retailer-price-service"),fixture=require("./fixtures/retailers/wolt-edeka-berlin.json");
const Venues=require("../wolt-retailer-venues"),nahkaufFixture=require("./fixtures/retailers/wolt-nahkauf-berlin-wrangel.json");
const SalesPack=require("../wolt-sales-pack-validation");
const now=()=>fixture.capturedAt,clone=x=>structuredClone(x),html=state=>'<script type="application/json" class="query-state">'+JSON.stringify(state)+'</script>',url=Client.API_ORIGIN+Client.API_PATH,nativeVenue=fixture.venueState.queries[0].state.data,date=new Date(fixture.capturedAt).toUTCString();
function response(value,type="json",headers={},status=200){const body=type==="html"?value:JSON.stringify(value);return{status,headers:{get:key=>({"content-type":type==="html"?"text/html":"application/json",date,...headers})[key.toLowerCase()]??null},text:async()=>body};}
function source(overrides={}){const calls=[];return{calls,fetch:async(address,options)=>{calls.push({address,options});if(overrides[address])return overrides[address];if(address===Client.VENUE_API_URL)return response(nativeVenue);if(address===Client.VENUE_URL)return response(html(fixture.venueState),"html");if(address===url)return response(fixture.listing);const category=new URL(address).pathname.split("/").pop(),page=new URL(address).searchParams.has("page_token")?2:1;const raw=fixture.pages.find(x=>x.category.slug===category&&x.metadata.page===page);assert(raw,address);return response(raw)}};}
async function main(){
 const shop=Client.parseVenue(html(fixture.venueState),{capturedAt:fixture.capturedAt});assert.equal(shop.city,"Berlin");assert.equal(shop.nativeMarketId,"800401");assert.equal(shop.postalCode,"10969");
 const changed=clone(fixture.venueState);changed.queries[0].state.data.venue.post_code="10117";assert.throws(()=>Client.parseVenue(html(changed),{capturedAt:fixture.capturedAt}),/identity-conflict/);
 const stale=clone(fixture.venueState);stale.queries[0].state.dataUpdatedAt-=16*60000;assert.throws(()=>Client.parseVenue(html(stale),{capturedAt:fixture.capturedAt}),/stale-or-future/);
 assert.equal(Client.allowedUrl(Client.VENUE_API_URL),Client.VENUE_API_URL);
 for(const bad of["https://example.test/","https://consumer-api.wolt.com/consumer-api/consumer-assortment/v1/venues/slug/other/assortment",url+"?page_token=bad","https://wolt.com/de/deu/berlin/venue/edeka-hilbrecht?bypass=1",Client.VENUE_API_URL+"?bypass=1",Client.VENUE_API_URL.replace("edeka-hilbrecht","other"),Client.VENUE_API_URL+"/extra"])assert.throws(()=>Client.allowedUrl(bad),/not-allowed/);
 const identityProof={capturedAt:fixture.capturedAt,sourceResponseUrl:Client.VENUE_API_URL,sourceResponseHash:"a".repeat(64),sourceResponseDate:date,sourceAgeSeconds:null},freshShop=Client.parseNativeVenue(nativeVenue,identityProof);
 assert.equal(freshShop.nativeAssortmentId,shop.nativeAssortmentId);assert.equal(freshShop.nativeUpdatedAt,undefined,"HTTP Date must not become an invented native cache or price timestamp");assert.equal(freshShop.nativeIdentityResponseDate,new Date(date).toISOString());
 const identityCases=[[{venue:{...nativeVenue.venue,id:"1".repeat(24)}},/identity-conflict/],[{venue:{...nativeVenue.venue,merchant:{...nativeVenue.venue.merchant,city:"Hamburg"}}},/identity-conflict/],[{venue_raw:{location:{type:"Point",coordinates:[13.4,48.1]}}},/location-conflict/]];
 for(const [patch,reason]of identityCases)assert.throws(()=>Client.parseNativeVenue({...nativeVenue,...patch},identityProof),reason);
 for(const patch of[{sourceResponseUrl:Client.VENUE_URL},{sourceResponseHash:null}])assert.throws(()=>Client.parseNativeVenue(nativeVenue,{...identityProof,...patch}),/response-proof-required/);
 for(const [patch,reason]of[[{sourceResponseDate:null},/response-date-required/],[{sourceResponseDate:new Date(Date.parse(fixture.capturedAt)-16*60000).toISOString()},/response-date-stale-or-invalid/],[{sourceResponseDate:new Date(Date.parse(fixture.capturedAt)+6*60000).toISOString()},/response-date-stale-or-invalid/],[{sourceAgeSeconds:901},/cache-age-stale-or-invalid/]])assert.throws(()=>Client.parseNativeVenue(nativeVenue,{...identityProof,...patch}),reason);
 const transport=source({[Client.VENUE_URL]:response(html(stale),"html")}),first=await Client.fetchOffers({maxRequests:3,pauseMs:0,now},transport.fetch);assert.equal(first.complete,false);assert.equal(first.categoriesCompleted,1);assert.equal(first.categoryCount,2);assert.equal(first.received,2);assert.equal(first.nextCursor.categoryIndex,1);assert(first.offers.length>0);assert.equal(first.physicalStoreAssortmentVerified,false);assert.equal(first.shop.nativeUpdatedAt,undefined);assert.equal(transport.calls[0].address,Client.VENUE_API_URL);assert.equal(first.shop.nativeIdentitySourceUrl,Client.VENUE_API_URL);assert(!transport.calls.some(call=>call.address===Client.VENUE_URL),"a stale hydrated HTML cache cannot gate fresh native identity responses");
 const second=await Client.fetchOffers({maxRequests:3,pauseMs:0,now,cursor:first.nextCursor},transport.fetch);assert.equal(second.complete,false);assert.equal(second.nextCursor.pageNumber,2);assert(second.nextCursor.pageToken);assert.equal(second.categoriesCompleted,1);
 const third=await Client.fetchOffers({maxRequests:3,pauseMs:0,now,cursor:second.nextCursor},transport.fetch);assert.equal(third.complete,true);assert.equal(third.nextCursor,null);assert.equal(third.categoriesCompleted,2);assert.equal(third.pagesFetched,3);assert.equal(third.receivedCumulative,6);assert.equal(third.publishedAssortmentComplete,true);assert.equal(third.fullAssortmentVerified,false);assert.equal(transport.calls.length,9);assert(transport.calls.at(-1).address.includes("page_token="));
 for(const offer of[...first.offers,...second.offers,...third.offers]){const checked=Service.validateOffer(offer,{now:Date.parse(fixture.capturedAt)});assert.equal(checked.ok,true,JSON.stringify(checked.reasons));assert.equal(checked.offer.truthEligible,false);assert.equal(offer.scopeChannel,"online");assert.equal(offer.priceType,"unknown");assert.equal(offer.proofHash,offer.sourceResponseHash);}
 for(const call of transport.calls){assert.equal(call.options.redirect,"error");assert.equal(call.options.credentials,"omit");assert.equal(call.options.method,"GET");assert.equal(call.options.headers.Accept,"application/json");assert.equal(call.options.headers["App-Language"],"de");assert(!call.options.headers.Cookie);}
 const native=clone(fixture.pages[1].items[0]);native.price=204;native.deposit={amount:15,label:"MEHRWEG"};native.unit_info="1 l";native.unit_price={base:1,price:189,unit:"liter"};native.original_price=null;const parsed=Client.parseItems([native],{shop,capturedAt:fixture.capturedAt,sourceResponseUrl:url+"/categories/slug/"+fixture.pages[1].category.slug,sourceResponseHash:"a".repeat(64)});assert.equal(parsed.offers[0].price,1.89);assert.equal(parsed.offers[0].deposit,.15);assert.equal(parsed.offers[0].displayedPrice,2.04);
 for(const patch of[{price:0},{unit_info:"ca. 1 kg"},{barcode_gtin:"0000000000001"},{sell_by_weight_config:{}},{options:[{}]},{variant:{}},{is_wolt_plus_only:true},{deposit:{amount:999,label:"wrong"}},{min_quantity_per_purchase:2}])assert.equal(Client.parseItems([{...native,...patch}],{shop,capturedAt:fixture.capturedAt,sourceResponseUrl:url,sourceResponseHash:"a".repeat(64)}).offers.length,0);
 salesPackCases(shop);
 const firstCategoryUrl=url+"/categories/slug/"+fixture.pages[0].category.slug;
 for(const [address,value,count]of[[Client.VENUE_API_URL,nativeVenue,1],[url,fixture.listing,2],[firstCategoryUrl,fixture.pages[0],3]]){
  for(const [headers,reason]of[[{age:"901"},"cache-age"],[{age:"-1"},"cache-age"],[{date:"Thu, 01 Oct 2026 00:00:00 GMT"},"response-date-stale-or-invalid"],[{date:null},"response-date-required"],[{date:"invalid"},"response-date-stale-or-invalid"]]){const src=source({[address]:response(value,"json",headers)});await assert.rejects(()=>Client.fetchOffers({maxRequests:3,pauseMs:0,now},src.fetch),new RegExp(reason));assert.equal(src.calls.length,count,"fresh native venue identity cannot relax freshness of prices or trigger HTML fallback");}
 }
 for(const status of[403,429]){const denied=source({[Client.VENUE_API_URL]:response({},"json",{"retry-after":"600"},status)});await assert.rejects(()=>Client.fetchOffers({pauseMs:0,now},denied.fetch),error=>error.status===status&&error.retryAfterMs===600000);assert.equal(denied.calls.length,1,"native identity denial cannot trigger retries, hydrated HTML fallback or another endpoint");}
 const throttled=source({[url]:response({},"json",{"retry-after":"600"},429)});await assert.rejects(()=>Client.fetchOffers({pauseMs:0,now},throttled.fetch),error=>error.status===429&&error.retryAfterMs===600000);assert.equal(throttled.calls.length,2,"429 cannot trigger retries or another endpoint");
 const badCursor={...first.nextCursor,assortmentHash:"b".repeat(64)};await assert.rejects(()=>Client.fetchOffers({pauseMs:0,now,cursor:badCursor},source().fetch),/cursor-conflict/);
 const changedAssortment=clone(nativeVenue);changedAssortment.venue.active_menu="b".repeat(24);const mismatched=source({[Client.VENUE_API_URL]:response(changedAssortment)});await assert.rejects(()=>Client.fetchOffers({pauseMs:0,now},mismatched.fetch),/native-assortment-conflict/);assert.equal(mismatched.calls.length,2);
 const wrongPage=clone(fixture.pages[0]);wrongPage.metadata.page=2;const bad=source({[url+"/categories/slug/"+wrongPage.category.slug]:response(wrongPage)});await assert.rejects(()=>Client.fetchOffers({pauseMs:0,now},bad.fetch),/page-conflict/);
 await closedProfileCases(first.nextCursor,shop);
 console.log("wolt-retailer-price-client: fresh public native Berlin identity independent of stale HTML hydration, mandatory HTTP Date on identity and prices, bounded opaque pagination, service-compatible GTIN/pack/deposit evidence, no login, fallback or retry on 403/429 OK");
}
function salesPackCases(edekaShop){
 assert.equal(SalesPack.multipackConflict("Milka Tender Milch, 5 x 37 g",37,"g"),true);assert.equal(SalesPack.multipackConflict("Milka Tender Milch, 5 x 37 g",185,"g"),false);assert.equal(SalesPack.multipackConflict("Milka Tender Milch, 5 x 37 g",37,"g",5),false);
 assert.equal(SalesPack.multipackConflict("Milka Tender Milch, 5 x 37 g",184.815,"g"),false,"Binary rounding must not create a conflict at the shared 0.1% numeric tolerance boundary");assert.equal(SalesPack.multipackConflict("Milka Tender Milch, 5 x 37 g",184.8,"g"),true);
 for(const[name,amount,unit,count,conflict]of[["Milch 6 x 1 l",1000,"ml",1,true],["Milch 6 x 1 l",1000,"ml",6,false],["Milch 6×1 l",6000,"ml",1,false],["Milk 6 X 1 L",1000,"ml",1,true],["Saft 3 × 0,25 l",750,"ml",1,false],["Saft 3 x 0.25 l",250,"ml",1,true],["Snack 5×0,037 kg",185,"g",1,false],["Drink 2 x 25 cl",500,"ml",1,false],["Snack 5x37g",185,"ml",1,true],["Tücher 3 x 4 Stück",12,"piece",1,false],["Tücher 3 x 4 Stück",4,"piece",1,true],["Milch 3,5 % 1 l",1000,"ml",1,false],["Milch 123456789 1 l",1000,"ml",1,false],["Dose 20 x 30 cm, 37 g",37,"g",1,false],["Produktmodell X5 37 g",37,"g",1,false],["Rezeptbuch für 6 Personen, 37 g",37,"g",1,false],["Snack 2,5x37g",37,"g",1,false],["Snack 5x37grams",37,"g",1,false],["Snack 5 x 37 g und 2 x 100 g",185,"g",1,true]])assert.equal(SalesPack.multipackConflict(name,amount,unit,count),conflict,name);
 assert(SalesPack.SQL_CONFLICT.includes("regexp_matches"));assert(SalesPack.SQL_CONFLICT.includes(SalesPack.TITLE_MULTIPACK_PATTERN));
 for(const[key,shop,page,at]of[["edekaBerlin",edekaShop,fixture.pages[1],fixture.capturedAt],["nahkaufWrangelBerlin",null,nahkaufFixture.pages[0],nahkaufFixture.capturedAt]]){
  const client=Client.createClient(key),nativeShop=shop||client.parseNativeVenue(nahkaufFixture.venue,{capturedAt:at,sourceResponseUrl:client.VENUE_API_URL,sourceResponseHash:nahkaufFixture.sourceProofs.venue.responseHash,sourceResponseDate:nahkaufFixture.sourceProofs.venue.date,sourceAgeSeconds:null}),item=clone(page.items.find(x=>x.id&&x.name&&x.options?.length===0&&x.unit_info)),proof={shop:nativeShop,capturedAt:at,sourceResponseUrl:client.API_ORIGIN+client.API_PATH+"/categories/slug/"+page.category.slug,sourceResponseHash:"8".repeat(64),sourceResponseDate:at,sourceAgeSeconds:null};
  Object.assign(item,{name:"Milka Tender Milch, 5 x 37 g",barcode_gtin:"7622400004483",unit_info:"37 g",price:key==="edekaBerlin"?379:420,deposit:null,unit_price:{base:1,price:0,unit:"kilogram"},original_price:null,variant:null,options:[],sell_by_weight_config:null,is_wolt_plus_only:false,min_quantity_per_purchase:null});
  const bad=client.parseItems([item],proof);assert.equal(bad.offers.length,0,"A 185-g title with 37-g native quantity must never become a cheap exact 37-g quote");assert.equal(bad.received,1);assert.equal(bad.rejected.length,1);assert(bad.rejected[0].reasons.includes("wolt-native-sales-pack-conflict"));assert.equal(bad.rejected[0].retailerSku,item.id);
  for(const unit_info of["185 g","5 x 37 g","0,185 kg"]){const consistent=client.parseItems([{...item,unit_info}],proof);assert.equal(consistent.rejected.length,0,unit_info);assert.equal(consistent.offers.length,1);assert.equal(consistent.offers[0].packParsed.total.amount,185);assert.equal(consistent.offers[0].packParsed.total.unit,"g");assert.equal(consistent.offers[0].gtin,"7622400004483");assert.equal(consistent.offers[0].price,item.price/100);const admission=Service.createService(key).validateOffer(consistent.offers[0],{now:Date.parse(at)});assert.equal(admission.ok,true,JSON.stringify(admission.reasons));}
  const nativeMissing=client.parseItems([{...item,unit_info:null}],proof);assert.equal(nativeMissing.offers.length,0);assert(nativeMissing.rejected[0].reasons.includes("wolt-exact-sales-pack-required"),"The title never supplies a missing native quantity");
  const ordinary=client.parseItems([{...item,name:"Ordinary cake 37 g",description:"Recipe for 6 x 1 l milk, GTIN 3017620422003"}],proof);assert.equal(ordinary.offers.length,1,"Recipe text and other description numbers are not pack evidence");assert.equal(ordinary.offers[0].packParsed.total.amount,37);assert.equal(ordinary.offers[0].gtin,"7622400004483","Description GTIN-like text cannot replace the native barcode");
  const noGtin=client.parseItems([{...item,name:"Cake 37 g, code 7622400004483",barcode_gtin:null}],proof);assert.equal(noGtin.offers.length,1);assert.equal(noGtin.offers[0].gtin,null,"The sales-pack validator must never infer GTIN from a title");
 }
}
async function closedProfileCases(edekaCursor,edekaShop){
 assert.equal(Venues.resolve(),Venues.PROFILES.edekaBerlin);assert.equal(Client.createClient().SOURCE,Client.SOURCE);assert.deepEqual(Object.keys(Venues.PROFILES),["edekaBerlin","nahkaufWrangelBerlin"]);
 for(const key of[null,{},[],"nahcity-wrangelstrae","unknown","__proto__","constructor"]){assert.throws(()=>Venues.resolve(key),/profile-not-approved/);assert.throws(()=>Client.createClient(key),/profile-not-approved/);}
 assert.throws(()=>Venues.resolve("edekaBerlin",{}),/profile-not-approved/);assert.throws(()=>Client.createClient("edekaBerlin",{}),/profile-not-approved/);assert.throws(()=>{Venues.PROFILES.nahkaufWrangelBerlin.slug="fake";},TypeError);assert.throws(()=>Venues.PROFILES.nahkaufWrangelBerlin.stapleSlugs.push("fake"),TypeError);
 const N=Client.createClient("nahkaufWrangelBerlin"),f=nahkaufFixture,base=N.API_ORIGIN+N.API_PATH,clock=()=>f.capturedAt,native=f.venue,proof={capturedAt:f.capturedAt,sourceResponseUrl:N.VENUE_API_URL,sourceResponseHash:f.sourceProofs.venue.responseHash,sourceResponseDate:f.sourceProofs.venue.date,sourceAgeSeconds:null},shop=N.parseNativeVenue(native,proof),listing=N.parseAssortment(f.listing,shop),milk=f.pages[0];
 assert.equal(N.PROFILE,Venues.PROFILES.nahkaufWrangelBerlin);assert.equal(N.SOURCE,"Wolt nahkauf Berlin Wrangelstraße");assert.equal(shop.nativeMarketId,"561888");assert.equal(shop.city,"Berlin");assert.equal(shop.postalCode,"10997");assert.equal(shop.address,"Wrangelstraße 75");assert.equal(shop.officialMarketUrl,Venues.PROFILES.nahkaufWrangelBerlin.officialMarketUrl);assert.equal(listing.leaves.length,236);assert.equal(listing.leaves[0].slug,"milch-47");
 for(const forbidden of[Client.VENUE_URL,Client.VENUE_API_URL,url,url+"/categories/slug/milch-46",base+"?page_token=bad",N.VENUE_API_URL+"?bypass=1",N.VENUE_API_URL.replace("nahcity-wrangelstrae","other")])assert.throws(()=>N.allowedUrl(forbidden),/not-allowed/);
 assert.throws(()=>Client.allowedUrl(N.VENUE_API_URL),/not-allowed/);assert.throws(()=>Client.parseNativeVenue(native,{...proof,sourceResponseUrl:Client.VENUE_API_URL}),/identity-conflict/);assert.throws(()=>N.parseNativeVenue(native,{...proof,sourceResponseUrl:Client.VENUE_API_URL}),/response-proof-required/);assert.throws(()=>N.parseAssortment(fixture.listing,edekaShop),/assortment-conflict/);
 for(const [key,value]of Object.entries({id:Client.VENUE_ID,slug:Client.VENUE_SLUG,name:"EDEKA Hilbrecht",brand_name:"Edeka",country:"AUT",currency:"USD",city:"Hamburg",post_code:"10969",address:"Ritterstr. 38-40",share_url:Client.VENUE_URL,active_menu:"wrong"})){const changed=clone(native);changed.venue[key]=value;assert.throws(()=>N.parseNativeVenue(changed,proof),/identity-conflict/,key);}
 for(const [key,value]of Object.entries({city:"Hamburg",post_code:"10969",street_address:"Ritterstr. 38-40"})){const changed=clone(native);changed.venue.merchant[key]=value;assert.throws(()=>N.parseNativeVenue(changed,proof),/identity-conflict/);}
 const wrongLocation=clone(native);wrongLocation.venue_raw.location.coordinates=[13.40358,52.50356];assert.throws(()=>N.parseNativeVenue(wrongLocation,proof),/location-conflict/);
 const calls=[],fetchNative=async(address,options)=>{calls.push({address,options});assert.equal(options.credentials,"omit");assert.equal(options.redirect,"error");assert.equal(options.headers.Cookie,undefined);if(address===N.VENUE_API_URL)return response(native,"json",{date:f.sourceProofs.venue.date});if(address===base)return response(f.listing,"json",{date:f.sourceProofs.listing.date});if(address===base+"/categories/slug/milch-47")return response(milk,"json",{date:f.sourceProofs.milk.date});throw Error("Unexpected Nahkauf source URL: "+address);};
 const first=await N.fetchOffers({maxRequests:3,pauseMs:0,now:clock},fetchNative);assert.equal(first.requests,3);assert.equal(calls.length,3);assert.equal(first.categoryCount,236);assert.equal(first.categoriesCompleted,1);assert.equal(first.complete,false);assert.equal(first.received,13);assert.equal(first.offers.length,12);assert.equal(first.rejected.length,1);assert(first.rejected[0].reasons.includes("wolt-exact-sales-pack-required"),"A missing native sales unit must not be inferred from the product name");assert.equal(first.nextCursor.nativeVenueId,N.VENUE_ID);assert.equal(first.nextCursor.nativeAssortmentId,shop.nativeAssortmentId);assert.equal(first.physicalStoreAssortmentVerified,false);
 for(const offer of first.offers){assert.equal(offer.merchant,"nahkauf");assert.equal(offer.sourceId,N.SOURCE);assert.equal(offer.nativeVenueId,N.VENUE_ID);assert.equal(offer.nativeMarketId,"561888");assert.equal(offer.sourceUrl,N.VENUE_URL);assert.equal(offer.sourceResponseUrl,base+"/categories/slug/milch-47");assert.equal(offer.sourceResponseDate,new Date(f.sourceProofs.milk.date).toISOString());assert.match(offer.sourceResponseHash,/^[a-f0-9]{64}$/);assert.equal(offer.currency,"EUR");assert.equal(offer.scopeChannel,"online");assert.equal(offer.priceType,"unknown");}
 const landliebe=first.offers.find(o=>o.gtin==="4046700026519");assert(landliebe);assert.equal(landliebe.packParsed.total.amount,1000);assert.equal(landliebe.packParsed.total.unit,"ml");assert.equal(landliebe.price,2.56);assert.equal(landliebe.deposit,.15);assert.equal(landliebe.displayedPrice,2.71);assert.equal(landliebe.nativeUnitPrice.price,256);
 const priceProof={shop,capturedAt:f.capturedAt,sourceResponseUrl:base+"/categories/slug/milch-47",sourceResponseHash:"a".repeat(64),sourceResponseDate:new Date(f.sourceProofs.milk.date).toISOString(),sourceAgeSeconds:null};
 assert.throws(()=>N.parseItems(milk.items,{...priceProof,shop:edekaShop}),/source-proof-required/);assert.throws(()=>N.parseItems(milk.items,{...priceProof,shop:{...shop,nativeMarketId:"800401"}}),/source-proof-required/);assert.throws(()=>N.parseItems(milk.items,{...priceProof,sourceResponseUrl:url}),/not-allowed/);assert.throws(()=>N.parseItems(milk.items,{...priceProof,sourceResponseUrl:N.VENUE_API_URL}),/source-proof-required/);
 await assert.rejects(()=>N.fetchOffers({maxRequests:3,pauseMs:0,now:clock,cursor:edekaCursor},fetchNative),/cursor-conflict/);await assert.rejects(()=>Client.fetchOffers({maxRequests:3,pauseMs:0,now,cursor:first.nextCursor},source().fetch),/cursor-conflict/);
 for(const override of[{venueUrl:Client.VENUE_URL},{url:Client.VENUE_API_URL},{nativeVenueId:Client.VENUE_ID},{nativeMarketId:"800401"},{sourceId:Client.SOURCE},{headers:{Cookie:"fake"}},{credentials:"include"},{profile:Venues.PROFILES.edekaBerlin}]){let requests=0;await assert.rejects(()=>N.fetchOffers({...override,now:clock},async()=>{requests++;throw Error("Must not fetch caller configuration");}),/configuration-override-not-allowed/);assert.equal(requests,0);}
 for(const status of[403,429]){let requests=0;await assert.rejects(()=>N.fetchOffers({pauseMs:0,now:clock},async()=>{requests++;return response({},"json",{"retry-after":"600"},status);}),e=>e.status===status&&e.retryAfterMs===600000);assert.equal(requests,1);}
 let overBudget=0;await assert.rejects(()=>N.fetchOffers({maxRequests:1,pauseMs:0,now:clock},async()=>{overBudget++;return response(native);}),/budget-exhausted/);assert.equal(overBudget,0);
 let tooLarge=0;await assert.rejects(()=>N.fetchOffers({maxRequests:3,maxResponseBytes:1,pauseMs:0,now:clock},async()=>{tooLarge++;return response(native,"json",{date:f.sourceProofs.venue.date});}),/body-too-large/);assert.equal(tooLarge,1);
 for(const[headers,reason]of[[{date:null},/response-date-required/],[{date:"invalid"},/response-date-stale-or-invalid/],[{date:new Date(Date.parse(f.capturedAt)-16*60000).toUTCString()},/response-date-stale-or-invalid/],[{date:new Date(Date.parse(f.capturedAt)+6*60000).toUTCString()},/response-date-stale-or-invalid/],[{age:"901"},/cache-age-stale-or-invalid/],[{age:"1.5"},/cache-age-stale-or-invalid/]]){let count=0;await assert.rejects(()=>N.fetchOffers({maxRequests:3,pauseMs:0,now:clock},async()=>{count++;return response(native,"json",{date:f.sourceProofs.venue.date,...headers});}),reason);assert.equal(count,1);}
 console.log("wolt-retailer-price-client profiles: closed immutable EDEKA/Nahkauf venues, native shop and cross-venue URL/cursor/proof boundaries, precise market/pack/deposit identity and bounded anonymous transport OK");
}
main().catch(error=>{console.error(error);process.exitCode=1});
